string DLG_TEXT_Q [107] = {
	"What do you want, my son?",
	"You again? Did you forget something? ",
	"What ails you, my son? How many times have you come here, yet said nothing?",
	"Listen, ",
	", if you've nothing to say, then you've got no reason to come here.",
	"Oh, nothing important, Padre...",
	"Oh, no, just because...",
	"I've got nothing to say, Padre...",
	"Fine, Padre...",
	"Welcome to the bosom of the church, my son.",
	"Padre, I'm here on order from the Governor-General...",
	"I'm happy to see you, ",
	". Are you ready to report for your assignment?",
	"Padre, I've visited all the people you requested.",
	"Not yet, monsignor. I'm still working on it...",
	"You've got your assignment, my son. Begin completing it.",
	"Fine, monsignor...",
	"I'm happy to see you, ",
	". Are you ready to report your assignment?",
	"Monsignor, I've visited all the people you requested.",
	"Not yet, monsignor. I'm still working on it...",
	"What's happened, my son? Do you need your sins atoned?",
	"No, monsignor. I didn't return for that. Someone named Francisco de San Augustinio came up to me, and began softly singing about the morality of your assignment. He knows where I'm going, and what for. Don't you find that strange?",
	"My son, you may return to Havana. I don't need you anymore...",
	"Fine, monsignor...",
	"I'm listening to you, my son. Why have you come?",
	"Monsignor, according to the order I received from Governor-General Don Francisco Oregon y Gaston of Havana, I'm turning over the infamous Ladron Rock the Brazilian, captured by me in a heated battle at Maracaibo.",
	"I know, my son, I know. I was waiting for you. Now, about your mission...",
	"There are a few people living in darkness, and we don't have the strength yet to let them see the light. These are the Florentine merchants Joao Ilhao, Josef Nunen de Foncesao, and Jacob Lopez de Fonseca. We've managed to discover that they have fallen under the heretical teachings of Jansen.",
	"We cleanse the souls of those contaminated by the Jansenist sect by burning their bodies at the stake. Though they don't treasure this, the soul salvation that we give to them...",
	"I'm sorry, monsignor, but I have a question. If you'll, of course, permit me to ask it.",
	"Ask it, my son.",
	"I heard that Jansenists believe in Christ, the same as Catholics. Why burn them, if they're the same?",
	"Jansen perverted the dogmas of the Church. We have differences in the question of the existence of free will, and the requirements of divine grace - without which human salvation is impossible.",
	"And to come to an agreement, to negotiate a compromise, would be impossible?",
	"Indeed that would be impossible, my son. The enemies of the Church have been waiting to lead the lost souls from their Shepherd. No one can dictate the postulates of the Christian faith haphazardly, or - worse yet - put them to doubt. No one!",
	"Furthermore, the Jansenists have sullied themselves with a crime for which their can be no forgiveness. About twenty years ago, one of the first followers of this sect, Samuel Coheno, stole ancient church documents from our archives in Seville!",
	"Is that so! I always thought the Holy Inquisition was impregnable. How could that have happened?",
	"With the help of the enemy of the human race, my son! We fight his intrigues every minute, but at times he holds victory over some of our brothers. This happened that time. Our Seville archive fell under the weight of one of the deadly sins: greed...",
	"He admitted to everything?",
	"Admitted, confessed, and cleansed his soul - what else? We're happy to have helped him. I'm sure that the Lord welcomed his soul...",
	"Amen... So what is the point of my mission?",
	"You must visit the fled merchants, with a certain goal.",
	"And do you know where they currently are?",
	"Of course, my son. First they fled to the Netherlands, but they couldn't settle down there - the heresy of the Calvinists is very jealous of other heresies.",
	"Then they took off for the New World, and have organized a sect settlement on the island of Curacao. You're mission is to convince these merchants - very wealthy people that they are - to buy a pardon from the Pope.",
	"The indulgence will cost 50,000 a head. And if they refuse, then for the glory of God, I give you permission to use extreme measures.",
	"So 50,000 from each of them. And if they don't obey, I can do with them as I will. I understand correctly?",
	"Yes, my son, you've understood everything correctly...",
	"But is 50,000 enough to pardon the sins of Jansenists against God?",
	"No, of course. But we have to start with something. We need to shift their gaze towards the Lord, and we shall do that. Do you understand everything? Are you ready for the mission?",
	"Yes, monsignor. I'll begin immediately!",
	"Thank you for the warning, my son. Too much softness in dealing with heretics will only lead to more suffering for their souls. I'll worry about Francisco; he will pester you no more. Take this is as a sign of gratitude. I think you'll need it...",
	"Thank you, Father.",
	"And how did you fare, my son?",
	"I couldn't get a bit out of any of 'em. ",
	"I only managed to collect from the moneylender in Curacao, Joseph Nunes da Fonseca.",
	"I only managed to collect from a shop-keeper in Curacao, Joao d'Ylan, and his companion, Jacob Lopez da Fonseca.",
	"Just swell, father. You name 'em, I shake 'em down. That's three Jansenists covered.",
	"Your words plunge my soul into sorrow. You have failed in the simplest of charges.",
	"Well, father, I did my best.",
	"I understand, my son. Effort is the greatest human virtue... Pray, pass on to Havana, my son. I have no more need for you... ",
	"Well, okay, Monsignor. Farewell... ",
	"Hmm... Partial success is better than none, I suppose... Though I am not entirely pleased, my son.",
	"Well, father, I did what I could. ",
	"Er... The mission may be completed, but where is the money? Go, my son, and come back when you have your... full report.",
	"Oh, I do beg your pardon, Monsignor. I must have left it in my cabin. I'll be back in a shot... ",
	"All right, all right... Let's tally up, shall we? According to a decree from the Papal Office, debt collection is on an even keep with treasure location - which would mean between twenty and thirty percent of the takings (according to current market value) for the agent.",
	"Money taken is subject to a church tithe, the standard ten percent - which is why we call it a tithe, ho ho! Therefore, your compensation amounts to... hmm. It amounts to... nine thousand piasters. Take it, my son. Sign here, and you're free to go.",
	"Thank you, Monsignor. Farewell! ",
	"Wait, Monsignor. There's one more thing we must discuss... ",
	"Hmm... Partial success is better than none, I suppose... Though I am not entirely pleased, my son.",
	"Well, father, I did what I could. ",
	"Er... The mission may be completed, but where is the money? Go, my son, and come back when you have your... full report.",
	"Oh, I do beg your pardon, Monsignor. I must have left it in my cabin. I'll be back in a shot... ",
	"All right, all right... Let's tally up, shall we? According to a decree from the Papal Office, debt collection is on an even keep with treasure location - which would mean between twenty and thirty percent of the takings (according to current market value) for the agent.",
	"Money taken is subject to a church tithe, the standard ten percent - which is why we call it a tithe, ho ho! Therefore, your compensation amounts to... hmm. It amounts to... eighteen thousand piasters. Take it, my son. Sign here, and you're free to go.",
	"Thank you, Monsignor. Farewell! ",
	"Wait, padre. There's one more thing we must discuss... ",
	"Splendid, my son! Such a sum is a tremendous contribution to our cause. We are most grateful... ",
	"I do my best, father.",
	"Er... The mission may be completed, but where is the money? Go, my son, and come back when you have your... full report.",
	"Oh, I do beg your pardon, Monsignor. I must have left it in my cabin. I'll be back in a shot... ",
	"All right, all right... Let's tally up, shall we? According to a decree from the Papal Office, debt collection is on an even keep with treasure location - which would mean between twenty and thirty percent of the takings (according to current market value) for the agent.",
	"Money taken is subject to a church tithe, the standard ten percent - which is why we call it a tithe, ho ho! Therefore, your compensation amounts to... hmm. It amounts to... twenty-seven thousand piasters. Take it, my son. Sign here, and you're free to go.",
	"Thank you, Monsignor. Farewell! ",
	"Wait, Monsignor. There's one more thing we must discuss... ",
	"Oh yes? And what is that, my son?",
	"Father, do you remember telling me of a man called Samuel Coheno? I think he stole some old church documents from your archives in Seville?",
	"Indeed I do. What of it?",
	"Didn't he also steal a manuscript by one of the First Apostles, with a copy of the New Testament? Not one of the more well-remembered Apostles, at that... ",
	"It is forbidden to even speak of it. But go on, my son. You have certainly seized my attention... ",
	"Well, the fact of the matter, Monsignor... is I found the book. And here it is.",
	"Jesus Christ! I mean, Holy Mary... I... Oh dear. Such a recovery is well beyond our dreams! It has occupied all our thoughts - where this heretical squib might turn up, and what we might do, should that happen... ",
	"What a burden just fell from my shoulders! My son, in return I atone all of your sins and three more in advance! ",
	"Well, just glad to be of service, padre... ",
	"It doesn't end there, my son. As a token of our appreciation for your unduly noble service, The Holy Inquisition is eager to award you this splendid gold-encrusted body armor. ",
	"However, the true worth of this cuirass lies not in its detail, but in the greatest safety that it lends its owner - a feature of great value to one of your sort, I assume... ",
	"You got that right, padre. I do put quite the high value on my hide... Well, thanks for that too. And now, my Godly associate, I take my leave.",
	"Of course, of course. I must busy myself as well. Seville will be in an uproar, to hear of this! ",
	"Farewell, Monsignor! ",
	"Splendid, my son! You have my full admiration! ",
	"I ain't gonna lie to you, taking the lout was no cakewalk. In the end, I had to board a corvette brimming over with Tortuga scum, cut my way through them, and capture it almost single-handed.",
	"But he is not in your cargo hold! My son, go forth and bring me Rock the Brazilian.",
	"Yeah, okay... ",
	"Well, then bring this Ladrone before me, without hesitation! I can delay the court proceedings no longer. And please visit the Governor-General, while you're here.",
	"Sure thing, Monsignor... ",
};
