string DLG_TEXT_Q [24] = {
	"I've nothing to say to you.",
	"Okay...",
	"Good day. Who are you, and what do you want?",
	"My name is ",
	". I've come here on Askold's orders.",
	"I think I'll keep from associating with you. I don't like you, even if you're a friend of Askold's.",
	"Well, you know...",
	"Which Askold?",
	"The usual one. The one who lives on Guadalupe. There isn't another in the Caribbean.",
	"Talk lower. I understood you clearly. What does my friend Askold need?",
	"There's one problem. A little while ago a man-o'-war left from Havana, loaded to the gills with items of the Indian cult.",
	"To the gills is a bit of a boast. There were some items from the Indian cult, but not that many.",
	"I was sent to Havana, and personally took inventory of the cargo.",
	"Those would be the records that Askold is after.",
	"Oh. Well, if I knew he needed a record, I would have kept a copy. Now I can't even remember half of it.",
	"It's been so long... Really, I don't know what to tell you.",
	"I understand. But tell me something - what happened to the the man-o-war?",
	"I believe it made for Amatica Bay, to the south of Belize.",
	"Well, that's a fun place to gather... So, what, it just went off alone? ",
	"Yes, just the one ship. See, Amatica Bay is where all the Spanish colonial vessels meet up. If you can imagine, they found an abandoned Indian temple deep inland. So right now, a royal expedition's working on the site. Once they've done what they're doing, the squadron will make out for the Old World. ",
	"That's about all I know.",
	"Well, that's plenty. Thank you, my friend. I'll tell Askold you said 'hi'.",
	"Hey, wait! Buddy! What about the money?",
	"Yes, well. You and I, we're fresh new friends. Askold is your good old friend. And wealth, well, it comes with time. Farewell, amigo, and 'til we meet again! ",
};
