string DLG_TEXT_Q [269] = {
	"Greetings. My name is Askold. Who do I have the honor of addressing?",
	"My name is ",
	"I don't like it when people I don't know bother me.",
	"Got it. I'm leaving.",
	"You jest, sir?",
	"Who are you and what are you doing?",
	"I'm a privateer.",
	"Listen, privateer...",
	"Yes?",
	"Uh... You're not just a privateer, but a terrible privateer! Get the hell out of here!",
	"Again the terrible, nasty privateer dares to break the silence?! Let's repeat carrying out the body...",
	"Reaching into the bottle again... Time to take measures.",
	"Oh, I'm gonna...",
	"We'll see who throws whom out of the house, this time...",
	"Greetings. My name is Askold. Who do I have the honor of addressing?",
	"My name is ",
	". I was sent by ",
	", owner of a store located at ",
	"Our terrible corsair comes up on the horizon again. What do you want this time?",
	"This time I was sent by ",
	", owner of a store located at ",
	"Heh, I know this person. Well, then. Sit down, and we'll knock back some vodka.",
	"Confidentially, in these parts Russian vodka is in deficit. You can soak yourself in Jamaican rum, but compared to vodka, rum is shark's piss.",
	"So sum it up. Tell me roughly what business you have with me.",
	" said that you were looking for mummy powder. I've got it.",
	"Very good. I'll pay you 30,000 for that powder.",
	"A good price. Let's shake on it.",
	"Hey, pal, buzz off! You don't have the powder. I don't talk to people who try to trick me.",
	"So get the hell out of here!",
	"Oh, come on! I was joking! That never passed my mind... ",
	"The matter's settled! Now to wash it down...",
	"No, I'm not washing anything. Instead, why don't you tell me what this dirt's for? I tried to figure it out, but couldn't. An absolutely useless and vile thing.",
	"Well, how can I put it. This powder, and other items from the Indian cults, are ordered from Europe by the famous scientist Pierre de la Fontaine.",
	"I'm here as his trusted representative. In general, I'm pretty happy. De la Fontaine pays my rent and living expenses.",
	"And for every little thing like this that I find to order, he pays me not at all shabbily.",
	"Understood.",
	"Listen. If things have come to this, and we've worked out so well, then I'm offering you another job.",
	"I've just gotten the order to get three Aztec artifacts.",
	"I'll take it, I guess. I agree.",
	"No, I won't take. I'm neck deep in other matters.",
	"Yes? I don't like it when I'm denied. Makes me not want to know a person any longer. So get out of my house!",
	"Hey, hey! What are you doing?!",
	"Good. Then listen now to what I need you to find.",
	"I need to a find a statuette of Axoacatzin, the ambassador of the Aztecs who declared war, a ceremonial vessel, and ceremonial knife.",
	"Got it. I'll be on the lookout. Once I collect the three items, I'll come to you.",
	"Did you find that Indian crockery? I need to see all three at once. Don't bother to bring me them piecemeal. ",
	"Not yet, but I'm handling it.",
	"Yes, I've got it. Where's my money?",
	"Heh. For each item, I'm prepared to lay down 30,000. So that's 90,000 coins. You agree?",
	"I'm satisfied with that price. Let's shake on it.",
	"If you knew, Askold, how much I paid for these artifacts... But I understand that to demand the money back would be unrealistic, and anyway you are suggesting a sum six times more expensive... so I'll agree.",
	"No, give me more money.",
	"Oh, is that so. Looks like I was wrong about you. You're a man greedy beyond measure. I don't know these people; they mean nothing to me. And don't wish to know you any longer.",
	"Get out!",
	"Hey, Askold, wait! We're both reasonable people. Let's bargain, sort something out...",
	"Now, here's your 90,000, and the items are yours.",
	"Take them.",
	"Listen. If you want, why don't you come by in a month or two. Maybe I'll have some other work for you.",
	"If I'm in the area, I'll definitely visit you. You throw work around that ain't dusty. And the pay's good, too.",
	"Oho! Finally! And I was waiting for you. I need your services, ",
	"What do you need to find this time?",
	"Oho! Who's this I see?! None other but my friend, ",
	"! Happy to see you. If you've come about work, I can't cheer you up there. I've been sitting without a coin myself. Come back later.",
	"Fine, Askold. If I'm in the area, I'll stop by.",
	"You know, this time the matter isn't a search, but something more serious.",
	"Whoo, a chill on the skin... I smell big money! Come on, tell me the heart of the matter.",
	"The problem is thus. The Spanish, who have been mercilessly eliminating the continental Indians and their culture for a hundred years now, have suddenly begun worrying about collecting items from that same Indian culture.",
	"The thing is, in the court of Marie Anne - who knows from where - there's a strange new fad for Indian cult items. And now the Spanish are searching everywhere and collecting the artifacts that I need, hell or high water. And they're sending everything they find to the old world. My business is suffering, and I'm not ready for that.",
	"Anyway, I've discovered that there's a big lot of Aztec cult items, of unimaginable value, collected in Havana. I want to get these items. I understand that I won't be able to take everything, but a little bit wouldn't be bad.",
	"And also, as a matter of fact... I want to get an inventory list of the Indian goods collected by the Spanish. De la Fontaine would be interested to take a look at it.",
	"And that's it? No problem. You'll have it all. But do you know for sure that there is such a list?",
	"Listen. Don't get sad, but I can't now. I've no time.",
	"Yes, positive. A few friends let me know, not-for-free... The list is attached to the cargo, so where you'll find the artifacts, you'll find the list.",
	"I understand. Then I'll do it. As they say, wait for me and I'll return.",
	"Have you dug something out? Finished the mission?",
	"Not yet, but I'm handling it.",
	"I have no desire to work on your problems anymore. Sorry.",
	"Listen, in our last conversation you mentioned something about your friend, who whispered something about the list that I'm seeking.",
	"Askold! I've found your informant-friend! It's a Spanish officer by the name of Fernando Gonzalez in Santiago. He told me to say hi...",
	"Askold! There's ten Spanish men-o'-war out there!",
	"Askold! The list's yours, but there are still Spanish men-o'-war floating out there.",
	"Askold! The list's yours, but there are still Spanish men-o'-war floating out there.",
	"I've sunk all the men-o'-war, but I was unable to find an inventory list on any of the ships.",
	"The Devil take me! I've gone through all the seven layers of hell, but I got you this list. Here it is.",
	"The Devil take me! I've gone through all the seven layers of hell, but I got you this list. Here it is.",
	"I've eliminated the Spanish men-o'-war. The inventory list is also with me.",
	"I sent the men-o'-war to the bottom!",
	"And so?",
	"I need your help. Thing is, I ran into some trouble on Havana. I can't find out where the man-o'-war with the Indian artifacts went. Get your friend to help.",
	"No, it won't work. I'm bragging about my connections all over the Caribbean.",
	"But I'm working in your interest, after all!",
	"That's so, but work independently. Don't count on my help.",
	"Well, then. Thank you, friend Askold...",
	"We'll figure out a way of communicating, without you butting in... And have you discovered something?",
	"Yes. Near the shores of Amatica, south of Belize, they found a Indian temple - and now there's a whole expedition working there. There are loaded ships coming there from all over the New World.",
	"What for?",
	"Probably to loot the Indian temple and go back to Spain with it.",
	"Sad news. I've got a request for you, then. You must eliminate all the Spanish located near the shores of Amatica. All the ships must go to the bottom, and the expedition at the temple must be eliminated.",
	"And I need the Spanish inventory list.",
	"I'm ready. I can begin now, if you want.",
	"Don't you think you're demanding a bit much from me, pal? Find your stooges somewhere else.",
	"That's great. I don't even know how to repay you for the help...",
	"We'll handle this later, Askold.",
	"Very good. That must make you happy. Are you a corsair, or a rag? Eliminate all the Spanish, and get me that damned inventory list.",
	"A corsair, of course. I'll do it. You'll get your inventory list, and the Spanish will be eliminated.",
	"You can do that without me. Find another idiot!",
	"Well, what are you standing around for! Go and eliminate them.",
	"I'm already gone.",
	"Oh, isn't that something. You could send a staggering number of Spanish to their forefathers, yet you couldn't find a list. I can't believe the inexperienced people I deal with.",
	"So get out of here!",
	"And after all that I've had to suffer because of you...",
	"The list is good. You're great. But I need you to sink all of the ships near the shores of Amatica, and clear out the temple. Nobody should leave there alive.",
	"Tell me a good reason that would interest me...",
	"You'll have to pardon me, but I didn't want to cut down the poor Spanish.",
	"Askold, I need money. I got you the list, and I would like my reward.",
	"I'm waiting for the money from my patron, Pierre de la Fontaine. Have patience, and I'll pay you everything.",
	"Fine, I'll eliminate the Spanish. I hope I'll be happy with the size of the reward.",
	"You didn't eliminate the Spanish on the actual island. All the Spanish conducting work in the temple must be eliminated.",
	"Fine, I'll finish the job.",
	"You'll have to pardon me, but I didn't want to cut down the poor Spanish any further.",
	"What, you're dropping the matter in the middle?",
	"Oh, yeah. I'm dropping it because I'm sick of you.",
	"Now you're back. Anything to make me happy?",
	"Askold, the Spanish expedition to the temple of the Incas has been completely eliminated. But I was unable to find that damned inventory list.",
	"Askold, the Spanish expedition to the temple of the Incas has been completely eliminated.",
	"Excellent! I knew that I could count on you.",
	"I wanted to talk about my reward.",
	"Yes, of course.... Listen, I have nothing to pay you with. I haven't gotten my money from my patron. You'll have to wait a bit.",
	"Mmm, I'm speechless... If you knew what I had to live through...",
	"I understand, but I just don't have any money. I've got to send the inventory list to Spain, the one you captured. I think this will speed things up. Drop by from time to time...",
	"Well, then. Have it your way. I'll drop by whenever I can.",
	"Happy to see you, ",
	". I have no news for now. The money hasn't come yet...",
	"A pity... We'll wait, then.",
	"Oho! Who do I spy, but my friend ",
	"Any news?",
	"Yes, but you won't like it. I got word from de La Fontaine.",
	"And? Did he send the money?",
	"Some. But he was less than pleased with your work. The inventory log was useless, and the destruction of the expedition... how did he put it? He said It was a blow to the very institution of Western science.",
	"Well, isn't that something. ",
	"Frankly, I'm hard for words myself. But life goes on. And I have some business for you.",
	"Oh? What now? ",
	"Yeah, well I'll tell you where to put your business.",
	"Over in Europe, de La Fontaine dug up some old parchments that - well, from what I hear, they say there's some kind of a tomb here on our island. ",
	"If it's true, we must set to work and comb the sands before someone else finds it. ",
	"Yeah, I can do that. I don't suppose you're interested in paying me this time? ",
	"Askold... Do I look like a gravedigger to you? Have you nothing more... white-collar?",
	"Oh, no worries there. This assignment comes straight from my patron, so there will be a reward all right... provided you find something.",
	"Fine, all right. I guess I'll get searching.",
	"So did you find anything?",
	"Not yet. Keep your hair on.",
	"Good day, my friend. What's happening? What's the good word?",
	"Dammit, Askold. I combed the entire district, inch by inch. There's nothing here. Absolutely nothing. ",
	"So, tell me. Did you find anything?",
	"Not a thing. I tell you, there is no tomb around here. This is a waste of time... ",
	"Still on the search, I take it? Any news?",
	"Not sure... I found an entrance to something, in a cave near here. It's blocked, though.",
	"Did you find the tablets?",
	"I'm working on it. No sense rushing me.",
	"Oho! You've found something. I can see it in your eyes! I know that twinkle! ",
	"Good lord, did I ever... ",
	"Did you find a way into the tomb?",
	"I'm working on it... ",
	"Hmm... Don't even know what to say. ",
	"Mind you, this tomb may not even exist. Anyway, if you do hit on something, I'll be happy to see you.",
	"Well, maybe I'll give it one more go... ",
	"Maybe it does, maybe it doesn't... Keep searching.",
	"Yeah, sure... Whatever. ",
	"Aha! That looks like something de La Fontaine would be after... ",
	"Oh my demons, that has to be it! I'm certain of it! We just must get inside... ",
	"Maybe you can talk our way in, then. Look, unless you've got a way to move a boulder... ",
	"Hmm, so that's it... Listen, it probably was meant to protect against thieves - you know, like the pharaohs.",
	"Now, from my time with de La Fontaine, who amongst other accomplishments is a well-respected Egyptologist, I would say that there must be some kind of an opening mechanism, hidden nearby. Maybe in plain sight.",
	"Generally speaking, it involves putting... something, somewhere... ",
	"That's lovely. Could you possibly be more vague? Putting what, where? ",
	"Well, clearly I don't know exactly. But... hold on... ",
	"In his letter that describes the tomb, de La Fontaine tells of a note, detailing a stone tablet... At the time I paid it no mind, but I gather it must be important.",
	"Yes... It's coming back to me. It mentioned some tablets, more than one, that open the way to Leif the Happy. I'm guessing those are our 'something'.",
	"And who is this Leif the Happy?",
	"Oh, didn't I mention? He's the man you're digging up. ",
	"Great, so at least I'll have a jolly host. Listen, tell me about these tablets. Where are they, and what do I do with them?",
	"They're here, somewhere in the Caribbean. But you know, for all the junk people bring me, I've never heard of the like. So my guess is, we'd best keep to desert isles or the west coast of the Main, where the pearl trade goes on. Or maybe they're stashed in that ruined temple, found by the Spanish. If they were more obvious, they would have turned up long ago and I'd at least have heard of 'em... ",
	"As for what to do when you have them... well, I imagine there's a spot for them near the entrance. We'll must take a look. ",
	"Interesting. Well then, I guess I'd better get cracking. I sure hope this isn't one of your wild goose chases... ",
	"Yes, well. All this aimless searching has tired me out. I think I've had my fill, thanks.",
	"I am counting on it. Well... Good luck in your search! ",
	"Yes, thank you ever so much.",
	"You use them, try to enter the tomb.",
	"If all this comes to nothing, you do realize I'm going to kill you?",
	"Ah! Here you are, ",
	"! So out with it, what did you find?",
	"So I found the entrance to a cave. There were a few tunnels to explore. And in one of them... well, there it was. The entrance. I found it. ",
	"Oh my giddy aunt! A thousand devils! What was inside?",
	"In the middle was a stone sarcophagus, covered by a massive slab. I couldn't shift the slab on my own. I wasn't equipped for it.",
	"Hmm... So no treasure? No burial trinkets or anything?",
	"Nothing to speak of, no. ",
	"Hmm... So everything must be with the body. ",
	"Listen, here's a crowbar. How big is the slab? Will that be enough to shift it?",
	"Hmm... You know, I'm not so sure how thrilled I am to bother the poor man's sleep. However happy he might be.",
	"You can't be serious. Captain, by now he'll be nothing but crumbling bones. This is a first, a pirate afraid of a little corpse.",
	"No, that's not it. I fear nothing, arr. It's just that, well, how would you feel, some stranger pawing through your remains? ",
	"Look, are you with me or not?",
	"Hey, I've come this far, haven't I? I'm plenty curious myself.",
	"Splendid! Take your crowbar. I'll be here, waiting impatiently.",
	"I have no doubt, Askold.",
	"There you are! You can't imagine what's been happening since you left! Living skeletons - they were everywhere! It was an infestation! ",
	"Well isn't that just something. ",
	"So did you slay the monster?",
	"Not yet. Call this an intermission.",
	"So, how's the world doing? You save it yet?",
	"Sure, sure. The world is once again at peace. Children can sleep in safety, etcetera.",
	"It's unbelievable! They killed half the garrison, and made the Governor soil his pants! Or so I hear... ",
	"Of course, first word of danger I barricaded myself on the second floor. Good luck to any mummy climbing his way up here, I tell you... ",
	"Well, isn't that a relief. Listen, don't you want to know what went on inside that tomb?",
	"What tomb? Oh! So you opened it?",
	"Your fire iron proved handy.",
	"Oh dear... that would be it, then. The moment you left, I got a letter from de La Fontaine. He said he had deciphered the ancient manuscripts. ",
	"It said that he who opened a stone grave would awake... well, some ancient Indian monster.",
	"And here we are. That monster would be the same damn mummy that I've been seeking for so long.",
	"So what happened next?",
	"Next, I... Well, what happened was the skeleton assault on the town - surely that was his doing.",
	"So what you're saying is we tampered in forces beyond our understanding?",
	"All right. What do we do next? I take it this monster will destroy all life on the island?",
	"Not just the island! It has its sights on the entire world! And even that won't be enough for it... ",
	"Yes, you're right. Lister... I feel distinctly foolish saying it, but you must save the world.",
	"Why me? Aren't you in a world-saving mood? You're stronger than me, and hell, all this was your idea in the first place! ",
	"True, I am stronger. No argument there. And my skills with a staff are beyond refute. But a sword... that's just not for me.",
	"The tomb is in a cave, you say? Well, how would I wield a staff in such a tight space? You tell me that! ",
	"Yes, I see what you mean. It would be quite impossible. Very well then. I'll just go save the world by myself. See if I care.",
	"Phew... I'm so glad we agree. Best of luck to you, my friend.",
	"Thanks for the kind words, Askold. I'm sure they'll be a great help.",
	"Oh, good. Yeah... looks like you had a time of it.",
	"Listen, did you find anything interesting? De La Fontaine will be here soon, and it would be great to have something to show him.",
	"Nope. Nothing.",
	"This Leif guy had some sort of an oriental lamp. Can't be more specific. I'm no expert.",
	"Eh, a pity... Listen, surely another look wouldn't hurt?",
	"Surely there must be something to interest de La Fontaine? One curious bauble could pull a good deal of money... ",
	"For the luvva... Listen, Askold. Your fool errands have put me through ten lifetimes of trouble. You've put the world in danger, you've nearly gotten both of us killed many times over. That's it, enough! Our business relationship is over! ",
	"Well, that's a shame. But I see there's no changing your mind. Very well, but let's walk away friends.",
	"Yes... yes, all right. Fair enough.",
	"Oh! Look who's here! My old buddy, ",
	"! How splendid to see you again. Here on business, or just visiting?",
	"Just wanted to see my old friend.",
	"Listen, I've got something to ask you. Do you by any chance know where I might find a demon?",
	"Well, then sell it to me. I'll give you fifty thousand for this junk.",
	"Too light to be hiding much of anything... Yeah, fine, take it. I have no use for it.",
	"Nah... I think I'll head back to the ship and see if someone there can pry it open for me. There may be something inside.",
	"Fair enough; the dingus is yours and the money is ours. Hey, perhaps we can do this again sometime? Such deeds await us... ",
	"No, Askold. I've had enough of your kind of adventure.",
	"What?! ",
	"There's a certain demon I must track down. I swear, it's a matter of life and death.",
	"What, you're doing business with demons now?",
	"In a way of speaking... Look, it's all thanks to you - or, rather, your errands. Listen, maybe there's some kind of a recipe for calling demons? I think the Toltecs may have one. ",
	"I actually know one of their rituals. No guarantee it'll work, of course, but it's worth a shot.",
	"What... kind of ritual? It doesn't involve virgins, does it?",
	"No, just three crystal Toltec skulls. By coincidence our governor had them on his mantle, but, well, remember the skeleton attack? They took the skulls back with them.",
	"Oh, so that's what Leif was talking about... I think I see now. Well, is that all?",
	"We also need a strange... thing, an idol of some ancient deity. You just go gather the skulls, and then look for someone who can perform the rite for us. A witch of some sort, maybe.",
	"A witch, you say? I believe I know just the lady... ",
	"I imagine you do. Being who she is, I suppose your witch will be familiar with the rite. So that's half your job done, then. Now for the skulls. ",
	"Yeah, all right. I don't suppose you managed to hang onto any of them yourself?",
	"Nope, got nothing. You're on your own here. ",
	"Well, thanks anyway. Stay alive, will you.",
	"Well, actually... I was risking my life in the caves, when the Governor's three skulls, er, happened to fall into my possession... ",
	"Oh, really. Well, I am prepared to pay whatever it takes. How much do you want?",
	"I won't take your money. de La Fontaine and I are still indebted to you. You've done so much for us, and we've given you so little in return. Let's just call it even, shall we? The skulls are yours.",
	"Well, that was... unexpected. Many thanks, Askold. You wouldn't by any chance have a strange idol lying around? A figurine of a local god?",
	"Oh... Yes, of course. Take that, too. No problem.",
	"Well that's all right then. Now I am ready to return to a normal life. Thanks, Askold... ",
};
