string DLG_TEXT_Q [247] = {
	"Good day, ",
	". Fresh wind across the sea... I like it. I think they wear dresses like that now?",
	"Yes, the dress is just right... I was just at the docks, in ",
	"! How did I get here?! Damn it, what's happening?!",
	"There's no need to worry yourself.",
	"First, I'm not just some banal devil, but a demon! I took you for a bit. We'll talk now, and then I'll put you back in place.",
	"Second, thanks for opening the lamp after all.",
	"What?! Again?!",
	"About Leif Ericson - don't worry. I'm not going to force you to look for items, or assault cities for me.",
	"I've been stuck in that lamp for a long time. I've got other matters to worry about.",
	"What about switching bodies? You're not going to do that either?",
	"No, I won't. That's forbidden by circular 15315/28. And what's the point, anyway?",
	"Hmph. Well, that's a relief... Listen, so Leif's mightier than you, demon?",
	"What gave you that idea? Ahh! Oh, that's because he switched bodies twice?",
	"I'm a demon, and not the last one in the hierarchy I can do everything, including giving you any body. But circular No.15315/28 of the Management Review Council of Hell doesn't allow the swapping of bodies, without the agreement of the mortal and going through the proper paperwork.",
	"And Leif is a small-time crook; got himself a bunch of Indian occult rituals, and managed to summon me. Saddest thing is that he managed to trick me. Though that's all my own fault...",
	"How so? Sorry, for the question, of course, but I'm very interested.",
	"No problem. I'm somewhat grateful to you for opening up this tin can, and not giving it to the church.",
	"So, then. That slimeball Leif, in his old age, started thinking about how he could gain immortality. Of course, all paths to that goal lead to Hell.",
	"By that time, having scoured half the continent now called America and having visited many local tribes, Leif studied a rather large amount of strong incantations. So he became a real sorcerer, in the European understanding of the word. In fact, he learned that body-swap trick from the Aztecs.",
	"In Europe, he also diddled around (it's no coincidence that he was known as Leif the Lucky), because he knew that if there's a demon near at the moment of death, the soul doesn't leave the body for the Final Judgment",
	"And from the Toltecs, Leif learned the ritual of summoning demons. He performed the ritual, and unfortunately summoned me.",
	"Then how was he able to trick you? Don't demons know everything?",
	"They do, that's correct. But understand that we use this summoning procedure to receive the body and the soul of the mortal directly into Hell, bypassing the chancellery of the Final Judgment",
	"There are enough mortal idiots who try to get us into a bottle through a special method, to fulfill their wishes. Under an oath not to close the bottle, by putting up their own souls as collateral, we calmly go inside - and after a moment, the bottle ends up closed.",
	"The mortals presume that the cat's in the bag, but each one of us has a diamond ring just for these situations. Using it as a glass cutter, we free ourselves and take the soul owed to us.",
	"However, Leif used a tin can instead of a bottle...",
	"That's right. They put Eastern demon-slaves, djinns, into these tin cans. Leif used a djinn lamp to imprison men.",
	"And it had to happen that he summoned me on the day after Walpurgis Night - my favorite holiday on Earth.",
	"As usual, I spent that holiday pretty well. I like getting it on with some Earth girls, and those Gothic witches are sooooo hot!",
	"Anyway, with that hangover, I didn't even know where I was going. And there I was, caught. And Leif sent a letter to his relatives after my imprisonment, where he described the ritual of his resurrection. That letter was found by the Frenchman de la Fontaine, and you put the ritual into motion.",
	"Listen, couldn't your brothers - the demons - have freed you?",
	"No, I wasn't on duty then. I took an unlimited vacation. And those that wander the Earth for adventures aren't missed too much by the Hell chancellery. So I got myself into a real pickle.",
	"Yeah, I don't even know what to say...",
	"Yeah, what can I say? The old demon Ozzie really got himself screwed like some Earth loser.",
	"Oho! So you're called Ozzie?! Very nice to meet you.",
	"Yeah, likewise. Considering that the result of this meeting was my liberation, it's twice as pleasant.",
	"However, you know my name and can conduct the ritual of my summoning. I hope you aren't thinking of summoning me, with or without good reason.",
	"You know, I really hate that. You get me in a bad mood, and my good feelings toward you will evaporate in a second. And I'm scary when I'm angry...",
	"Well, I don't know the rituals anyway. I'm a real greenhorn in these matters. I mean, what? I need to run to the Toltecs, to get the ritual that Leif found?",
	"Suit yourself. I'm not going to help you in these matters. Whatever you need - or, rather, whatever you want to take - I can give you now.",
	"Hmm... Gifts from evil forces? I'll be frank with you, I don't want anything evil for myself.",
	"Good, evil... Two sides of the same coin, and all.",
	"Quoth Zoroastrianism, from the time of Persian King Darius - the first religion in the history of mankind to come close to understanding the true nature of things, though even the prophet Zoroaster was far away from the truth.",
	"Good and evil are sometimes so entwined that it's difficult to tell them apart. And the nature of events is such that's nothing is ever one-sided.",
	"How so?",
	"It's difficult to explain in human terms, but let look at an example.",
	"Let's imagine that you healed a man from a heavy illness. that's a good deed. But your good deed would be an evil deed, in regards to his unhappy stepdaughter.",
	"Or, let's say you smite a person. That's an evil deed. But that evil deed will be a boon to that same stepdaughter, suffering under her stepfather's tyranny.",
	"Hm. So that's how it is...",
	"In the end, the forces of good and evil. in their resistance to each other, create acts that are difficult to interpret from just one perspective.",
	"In that way, it's absolutely imperative that I begin sowing evil, in regard to you. No one's forcing me to do it, even though I am a demon.",
	"That means I can make wishes, and you'll grant them?",
	"Theoretically, yes. But there is a but - and it's a big one.",
	"The issue is that our relationships with mortals are regulated by circulars. I've given you an example - body swapping.",
	"I can act only within the confines of these rules. So let's discuss your wishes.",
	"With pleasure.",
	"I'm listening to you closely. What do you want?",
	"So what do you want?",
	"I'm listening to you. What do you want?",
	"For you to kill my enemies.",
	"Money.",
	"Rum.",
	"A good ship.",
	"Immortality.",
	"To become the governor-general of Jamaica.",
	"To be the strongest, cleverest, smartest, luckiest...",
	"I don't want anything else. Or nothing comes to mind anyway.",
	"Kill people, by your wish? A completely incorrect path to understanding of the forces of Evil.",
	"We've discussed this wish already.",
	"I already told you that we've discussed that wish. Don't drive me nuts, or I might lose my patience.",
	"Well, it looks as if you're a complete madman. Farewell, mortal.",
	"I don't get it... What does understanding have to do with it?",
	"Okay, sure, everything's done with. Let's discuss the rest.",
	"Sorry, I didn't want to anger you. Let's continue.",
	"What do you mean, farewell?!",
	"You see, ",
	", the forces of evil, with a few rare exceptions, don't kill people. Those scary tales your nannies and grannies told you, when you were children, are nothing more than fairy tales.",
	"But you hunt after our souls!",
	"Correct. As do the forces of good, who are after those very same souls.",
	"Killing a man doesn't mean that his soul will go to Hell. That's decided by the council of the Final Judgment. The goal of the forces of darkness is to influence a decision in our favor.",
	"And that's reached not through killing a man, but by infecting him with vices. His own actions must give his soul to us. The passions in the soul of a mortal must grow from a flickering ember to an all-engulfing flame, and every soul has one of those embers...",
	"Hm. Walk into any cave on the archipelago, and there's plenty of your kind there. Yawn a little, and they'll take your head off, not noticing my vices at all...",
	"Oh, that... Those chaotic masses have little to do with the forces of evil. There are some souls that don't end up in the chancellery of the Final Judgment. There are a few reasons for that.",
	"We've got a few Indian demons. They're in there own department, ruled by a little Aztec god Mictlantecuhtli. This band forces the soul, already losing consciousness after death, to control a dead body - and not necessarily its own.",
	"It's a busy and wasteful task, making a dead body move. As far as I know, they found a way of tying the elements of chaos to this business, made from pure natural energy. So those walking corpses are autonomous, in the end.",
	"Why the redskins need this, I have no clue. They're walled off at our end; their department reports only to upper management. They're weird.",
	"To add to that, unmotivated killings of men are forbidden by circular No. 55115/13.",
	"That means you can't kill anyone by my wish?",
	"Oh, I can. I can put the nearest city to the knife, if you so desire. Only one condition - I'm going to take your immortal soul.",
	"And rip apart and eat your body beforehand. I'm a demon, and the Management Review Council of Hell monitors and makes sure that all demons do their duty.",
	"Do you agree?",
	"No, too small a price for my soul. And I don't plan on selling it anyway. Let's talk about other wishes instead.",
	"We can do that.",
	"We've discussed this wish already.",
	"I repeat, we've discussed this wish already. You shouldn't aggravate me.",
	"It looks like you're the dullest and most annoying person in this world. Farewell.",
	"And what, you'll demand my soul in return?",
	"Right, we've discussed this. Let's talk about other wishes.",
	"Sorry. Didn't mean to piss you off. Let's move on.",
	"What do you mean, farewell?!",
	"Well, the imps do it that way. Money, jewels, gold - and then the soul goes straight to hell. But I'm a demon, and I'm not about to lower myself to such a pitiful affair.",
	"Moreover, you've done me a certain favor so I don't want to bring harm to you.",
	"Oh. Well, that's good to hear...",
	"I'll provide you with money. But I won't just give it to you.",
	"In the city Charlestown, you'll go to a money-lender by the name of ",
	". You'll tell him that he owes you three million, and you'll get the entire sum at once.",
	"And he's sold his soul to you?",
	"Ha-aahaha-haha! Every person who channels money into interest has already sold his soul.",
	"Most just don't realize it until it's too late...",
	"Anyway, let's not get sidetracked. Are you satisfied? Or does your soul demand that more wishes be fulfilled? Harr harr!",
	"Uh. I guess it'd be nice to see a price list.",
	"Very good. From now on you're the governor of Jamaica. No problems.",
	"You've already become Governor.",
	"I've already made you the governor of Jamaica. What, you want I should do it again?",
	"It looks like you're the dumbest person on Earth. Farewell.",
	"That means I can go to my residency on Port Royal? And the English fleet in the Caribbean will be subordinated to me? And I might be able to socialize with the king?",
	"Yes, that's right. You've become the governor of Jamaica...",
	"I don't even know, should I?",
	"What do you mean, farewell?!",
	"How can I put it... That's a bit more difficult.",
	"What do you mean, difficult? You've just made me the governor of Jamaica!",
	"That's true. You're now the governor. I never said I'd change anyone else.",
	"So the actual world won't see me as the governor? Then why do I need this, then?",
	"What am I, a mind reader? You wanted to be governor, so I made you governor. ",
	"But for the world to recognize your title, do you understand the whole chain of events I would have to change? ",
	"I would must draw up a whole elaborate sequence of events that would inevitably place you in the governor's chair. That would mean changing the whole world and everyone in it. The consequences of all that change - well, I don't want to think about it! ",
	"Plus, doing that may change the sequence of events that led you to make the wish in the first place. Anyway, I would have to execute the Existing Reality Per Administrative circular No. 315/188. And nobody wants that.",
	"Still, if you insist... Are you prepared to face the consequences?",
	"Not when you make it sound so complicated! Never mind... ",
	"All right, so I take it you don't want to be governor anymore?",
	"No, forget it. What else can you offer me? That won't make my head explode?",
	"How about immortality? I can do that. But first we'd better narrow this down. I assume by 'immortality' you mean you would prefer your soul not to be excised from your body for any of the variety of reasons that usually result in death. Is that right?",
	"We've gone over that.",
	"I tell you, we've already discussed immortality. Not wise to irritate a magical being, my boy.",
	"Hey, look at that! The dumbest man under this sun! Lucky old me. Look, I don't need this. See you.",
	"Well, that seems right... ",
	"That's right. The topic of immortality has been closed.",
	"We've discussed it and come to a decision. You're absolutely right! ",
	"See me? Wait, hang on. What do you mean?",
	"This is doable. But do understand that immortality isn't the same as invulnerability. You keep on being an idiot, your body is going to start falling apart anyway... ",
	"Soon you'll be little different from one of those wraiths crowding the local catacombs - hey, you know my friend Leif? Like that. Shall we talk about that?",
	"All right, that's not what I want. How about this: I want my body to be impervious to damage. Bullets, blades, the works.",
	"Now we're getting somewhere. You want invulnerability, then. It's no skin off my nose. ",
	"There's just one hitch - it'll take a lot of work to achieve. It's one thing to bind a soul - that's nothing. Snap of the fingers. But safeguarding a body under a hail of bullets - think about the amount of energy that would entail.",
	"Oh, come on. Azzy, you're a demon - a supernatural being. There's no end to your power, and you're saying I must do your footwork?",
	"What did you expect? We're all subject to the laws of creation, whether we're aware of them or not.",
	"So here's how we'll do this. You want invulnerability? I'll tell you what you must do, so this whole thing works out.",
	"Okay, all right. Tell me what I must do.",
	"What you do is, you sign a contract with Hell's Human Resources department. The contract will stipulate a certain volume of life energy - your Chinese people call it 'chi'; I don't know about Europeans - that you are obliged to supply. ",
	"The purified energy that fuels all those unkempt charmers in the catacombs - that'll do, in a pinch.",
	"Supply it? What do you mean, exactly? What do I must do to... collect this... energy?",
	"What you're best at. Send people and ghoulies to the afterlife. ",
	"And the Hell department will automatically add that energy to the balance sheet that goes towards the maintenance of your invulnerability. See, the energy has to come from somewhere.",
	"Is this necessary? Granted, I have sent quite a few people on a permanent vacation with their ancestors, but up to now it's all been contextualized, you know? This is kind of... cold.",
	"Listen, love, I'm doing you a big favor here. What, do you think contracts with Hell's HR department are available at the county clerk? ",
	"These deals are rare and exclusive. This is how it should be, else there would be no miracles in this world.",
	"So how many people or... things would I must kill, to maintain a normal function of my... er, invulnerability system?",
	"That's something the department will have to determine. But I don't foresee any problems - a few units a day should be plenty. ",
	"As I'm saying, you do this every day. What's your hangup? ",
	"Well, what do you think? That all good?",
	"Yeah, let's do it. Do I must sign in blood or something?",
	"No, this is too... no, let's just keep everything as it is. What other kinds of wishes can you do?",
	"Blood?! Ha, you've been reading too many of those cheap necromancy novels! ",
	"Just say, 'I, ",
	", being of sound mind and spirit, hereby form contract with the demon Azzy, to the purpose of securing my body's invulnerability.'",
	"I, ",
	", being of sound mind and spirit, hereby form contract with the demon Azzy, to the purpose of securing my body's invulnerability",
	"And there we have it. The text of the contract will be added to your ship's log. Peruse it when you have the time.",
	"Congratulations to you. You are now perfectly invulnerable.",
	"Huzzah! Listen, what other kinds of wishes are you good for? ",
	"Well, you've got more than enough money. And surely you can find your own rum?",
	"What's the deal with pirates and rum? Look, we've gone over this.",
	"Don't annoy me. I don't like to repeat myself.",
	"Okay, dumbo. I've had enough of you. Farewell. ",
	"You know... I can and do find my own supplies, and money comes and goes, but the thirst for rum is never quenched.",
	"Yes, that's right. Never mind.",
	"I'm sorry... ",
	"Wait, what? What do you mean, farewell?! ",
	"All right, then. This, I can arrange. Let's agree to the following: if you ever need rum, just go to the owner of the eponymous store at Port-au-Prince. ",
	"Sounds great! I'm living the pirate's dream! What do I owe you?",
	"Not a thing. It's a simple fix; I can do it with my own energy, without bothering anyone else.",
	"Great. So what other interesting offers can you give me, in terms of wish fulfillment? ",
	"Well, let me ask you this: who do you want to be?",
	"I already referred you to someone. I see no must repeat myself.",
	"Don't annoy me. I don't like to repeat myself.",
	"That's great. I've found myself the dumbest human under this sun. Farewell, chump.",
	"Well, I don't know... Wouldn't hurt to be stronger... luckier, maybe?",
	"Yes, all right. I'll find her well enough. ",
	"I'm sorry... ",
	"Wait... hang on, what do you mean, chump?! ",
	"I see. In Tortuga, there is a bordello run by a certain Margarita. This woman is a witch, and can give you what you need. By the time you find her, she and I will have struck a deal. ",
	"Oh. Well, all right. I'll go to her. Thank you! Anything else I should wish for?",
	"What do you mean good?",
	"We've already discussed ships... ",
	"I understand your dreams of the Flying Dutchman, but we've gone over this... ",
	"Good grief. I sure can pick 'em, can't I. Farewell, genius.",
	"I want to be able to outrun any ship. I want a ship with sails full of wind and knippels that won't tear. I want cannon balls to harmlessly bounce off my ship's hull... ",
	"Yes, ships are my favorite subject.",
	"I was talking about the Black Pearl, but nonetheless, it's all true.",
	"Genius? Me? Wait, where are you going? Hello? ",
	"This, I won't do - it's too expensive.",
	"How about the 'Flying Dutchman'?",
	"The Flying Dutchman' is under a terrible curse. A bunch of Indian demons deal exclusively with tracking the condition of its curse and maintaining its functionality.",
	"Next you'll suggest that I join your crew, to ensure the speed and safety of your noble bucket?",
	"Of course not, Azzy. Until this moment, it hadn't even crossed my mind... ",
	"Good, since it's unsafe for you. ",
	"Though, wait. I can't remember exactly, but the protection of a ship's hull is a clause in one of the contracts with mortals. ",
	"And overall, I would advise you to visit the shipyard on Bermuda, run by the Master. He fixes the local sailships right.",
	"My dear Azzy, thank you for the advice. I'll look into it, for sure. So about this wish business... ",
	"Hold on, remember that invulnerability business? See here, this contract has a clause regarding the integrity of your ship's hull, so you don't accidentally drown in the middle of the ocean. Otherwise, I'd have to negotiate with the mermaids to drag you out of the depths... And I'd rather avoid that, if possible... ",
	"Oh, Azzy, that's fantastic! So what else can you do for me?",
	"You have exhausted me, but on the other hand I have put my patience to a test. Now let the angels speak of demons, and their wild and unruly nature.",
	"It has been my pleasure, speaking with you. Should you at some point choose to summon me, I promise I will at least listen to you before devouring your body. Hwa-ha-ha! ",
	"Farewell, privateer.",
	"Farewell, Azzy. Thank you again.",
	"So. You rang? ",
	", you know I can't abide being summoned. You'd better have a really good reason... ",
	"Azzy, I want to annul the invulnerability contract.",
	"Why all of a sudden? These things don't grow on trees, you know. ",
	"Dammit, Azzy! This Hell Office of yours keeps changing the rules! I'm risking my life here! ",
	"As well as your immortal soul. So what did you expect? ",
	"Azzy, I want to break the contract. Look, there's a clause that deals with this issue. But I need your help, and that's why I called you.",
	"Hmm, all right. Say, 'By consent of the most spectacular Azzy, I hereby divulge myself of any claim to invulnerability.' Simple enough, really.",
	"By consent of the most... the most spectacular Azzy, I hereby divulge myself of any claim to invulnerability.",
	"Oh, such passion! Fine, it's done. You are hereby vulnerable. The contract is no more.",
	"Thanks, Azzy. You more than saved my skin.",
	"So I did. Well, let's say our goodbyes, mortal. This time, it's for keeps. If you summon me again... well, you know how it goes. ",
	"Try praying for forgiveness. It could work! Or not. Farewell... ",
	"Farewell, Azzy. I'll do my best.",
	"Hee, hee... What's up, friend? Bit off more than you can chew?",
	"God damn, Azzy, am I ever glad to see you! ",
	"Don't take the Lord's name in vain. It's rude.    \n What's your problem, then?",
	"I thought I was finished. Now... maybe I've got a chance. Azzy, my friend, I'm so happy to see you! ",
	"I'm glad to see you, too. I find you entertaining, mortal. You always need something, constantly sticking your nose where it doesn't belong...    \n Now you've even gotten mixed up with those Indian demons. You're just a bottle of energy, aren't you.",
	"Azzy, I had no idea it would go this far! Incidentally... er, can you tell me where I am?",
	"You're in Tenochtitlan, the abandoned capital of the Aztecs. The demon that grabbed you is called Mictlantecuhtli. He's pretending to lord over the dead Aztecs around here.",
	"By all that is holy... Azzy, get me out of here! Please! ",
	"I don't know about that... He locked you up for a reason. What were you thinking, borrowing money from his underlings? ",
	"I wouldn't have, if I knew I'd end up in here. Azzy... ",
	"All right, all right.    \nListen, if I get you out of here, you'll promise to be careful in the future. Got it?",
	"Got it, I'm no fool.",
	"That's debatable. All right. Farewell, mortal.",
	"Thank you, Azzy, from the deepest recesses of my heart... ",
	", has anyone ever told you what a bore you are? See you around, dumbo.",
	"Listen... ",
	"Nah, done with listening. Farewell, mortal... ",
};
