string DLG_TEXT_Q [19] = {
	"Who are you?",
	"Quiet, fishy. Don't make a fuss. Yo homey sent me - man what's chillin' in the joint. ",
	", you know the man?",
	"You gonna answer fo' runnin' yo mouth?",
	"I gots a note for ya.",
	"Thanks for the note. Whatchoo got in yo pockets? Give it, we's short.",
	"Are you in your right mind?! You owe me money for helping you!",
	"Very good! A reward is in order, for matters like this... ",
	"Thanks. Not bad.",
	"We ain't owe you nuffin. Run the piasters, homes, or you ain't walkin'.",
	"Well, we'll see about that... ",
	"Take it, and get lost.",
	"All the best.",
	"Rat's lost his nose? ",
	"Devil! ",
	"¡Ay caramba! ",
	"Oh hell! ",
	"We ain't got nothin' to converse. Git, while you can git.",
	"All right, all right... ",
};
