string DLG_TEXT_Q [156] = {
	"Wait, buddy... Be so kind as to tell me your name.",
	", in the flesh. What's the matter?",
	"Aha. I need you...",
	"I'm listening closely.",
	"under",
	"behind",
	"That's good that you're listening closely, 'cause we've got something important to talk about. Here goes: There's a dungeon somewhere ",
	"the city. You can find me there. ",
	"Maybe we should go to the tavern, discuss things there? What's the hell's the point of wandering around dungeons at night?",
	"No, I don't need any extra eyes or hands. Believe that...",
	"Hm, I don't know... What this matter worth to me?",
	"It's a matter of life and death.   \nAnyway, I've got no time to chat with you. I'll wait for you at the dungeon at midnight. If you don't come, well. You know best...",
	"I wanted to ask this, too...",
	"Ah! You've come after all...",
	"Yeah, I've come. Talk quickly. What's this matter of life and death?",
	"It's so... Man, it's... It's the matter of YOUR death.",
	"What are you talking about?",
	"I hope you've been to confession recently, 'cause you're going to your forefathers. I want you to go get cleaned, or I'll be worried about you...",
	"Okay, uh. Thanks for the concern. Do you actually know who I am, for you to talk with me like this?",
	"Some captain, and I don't need anything else. You're not the first idiot to come here and stay here forever. In fact, you're standing on one of them now. Good guy, he was. And he was beautiful, like Apollo. \nUnderstand, I have to kill you. There's no way around it.",
	"Wow, I never would have thought that a cynical killer could be behind such an appearance...",
	"Heh. That's the rub, pal. Appearances can be deceiving. I, uh, was about to suggest you remember that in the future, but...",
	"I want to hope it's a happy one...",
	"Tell me, may I have a minute of your time?",
	"You may.",
	"Your name...",
	". And what of it?",
	"Then I need just you. I've got something for you, but I have to meet you in secluded place.",
	"Let's go to a tavern.",
	"under",
	"behind",
	"Sorry, that's no good. Believe me, there's a reason for it. I can't talk long with you, so I'll ask you to come to a certain dungeon in ",
	".",
	"Hmm. This all seems familiar, somehow...",
	"I've waited long enough...",
	"Yes. As you see, I've come. What do you have for me? Speak quickly!",
	"Run everything you have, and tell me what kind of ship you've got and what kind of cargo in the holds...",
	"And why should I do that?",
	"Say it, idiot, or you'll lose your head in a second!",
	"Hot damn, is this ridiculous. You're the second person who's tried to kill me this way.",
	"Hm. Is that how it is?   \nWell, that clears up a few things for me...",
	"And what has cleared up for you?",
	"Beware the optimates, pal!",
	"The what-now?",
	"Sulla's proscripts are pure evil! If only he'd known what it would do to the empire...",
	"What are you jabbering about?",
	"What do mean? Don't you understand?!   \nBeware the strapping young men- that's what Sulla said to the optimates - and he was right! Holy Julius eliminated the remnants of the Republic...",
	"Bud, it looks like you're really and truly sick. Excuse me, but I must be going...",
	"Where?! Where will you go?! Evil is on every corner, and you've had the misfortune of feeling its icy touch! To twice get into a trap and avoid death... hee-hehehee...",
	"Are you talking about the strange people who've been calling me into dungeons and trying to kill me?",
	"Quite so, my friend. Quite so...",
	"Damn it, who are they?!",
	"Hee-hehehee! I won't tell you...",
	"You'll tell me, or I'll ring your neck in a second!",
	"I'm not scared anymore... I've killed captains as well! I've had the chance to do that! Ahh, fear ate at my soul!   \nBut I'm not scared anymore! It's all over... And I've got to hurry! I've got to warn August, against warming his gallbladder! To the contrary, he should apply a cold compress. Then the bile would leave...",
	"Um...",
	"Oh, piss off! This has nothing to do with you! This just between me and the Caesars!",
	"Okay, got it...",
	"And you should seek them! You must find Austin, before they realize that you've killed both. Be careful and clever. Don't scare them away, or they'll disappear!",
	"Austin?",
	"Hello, ",
	"Hello. To what do I owe the honor?",
	"Listen, I've got a little item that you'd definitely be interested in. And for a good price!",
	"Well, I'm always happy to receive good business offers. Show me what you've got.",
	"under",
	"behind",
	"Not here, ",
	". We don't need any extra eyes or ears. I'll wait for you at midnight in a dungeon, in ",
	". Come! You won't regret it!",
	"You know, buddy, you're the third unseemly type who's called me out to the local catacombs. The previous two ended in big trouble...",
	"Ha! I'll come to the meeting place, with pleasure. Is the thing expensive?",
	"Oh, is that it... Sorry, our deal's off.",
	"Oh, you don't mean?!",
	"Yeah, it isn't cheap.",
	"Then I'd better take more money!",
	"Well, then I can't wait to meet you, ",
	"Til we meet again, buddy.",
	"Ah! You came after all...",
	"Spill it. Tell me what you got.",
	"Ho, you spill it. How much money did you bring?",
	"Show me the goods, first.",
	"Ain't no goods. A little slow, are we? ",
	"Nah, doesn't take a great mind. You're the third guy who's tried to pull this on me. So go ahead, tell me who you and this Austin are.",
	"Well, this is unexpected... ",
	"So are the runs... Now quit the stallin', and start the squawkin'. If you value your life, that is.",
	"Hmm... Cocky ain't we, brother.",
	"Yeah, that's right... And that's not all I got.",
	"Hello, ",
	". Tell me, are you that famous captain who brought in a whole mess of copra from the Old World?",
	"Nah, I don't do business with Europe.",
	"Ah, a pity. Such a pity! I has an extremely profitable deal for that captain.",
	"So you're in the market for copra?",
	"No, not at all! I deal in compact, yet quite valuable, goods. They're the dream of any merchant captain - take up a minimum of space, yet provide maximum of profit.",
	"What kind of goods, if I may ask? I might be interested.",
	"Hmm... I'm afraid I can't just tell you, Captain. Security and all. Mum's the word, I'm sure you understand. I can't just show my cards to the first person I meet.",
	"All right. So if you're unwilling to discuss the goods, how might I, or any other captain, ascertain the value in this deal?",
	"under",
	"behind",
	"I'm prepared to discuss it in detail, but not here. I propose we meet, one on one, in the catacombs under the city of ",
	". I won't take too much of your time, and I will be sure of my own security.",
	"Ha! I've been down this road before, brother. Every time, someone's tried to kill me. ",
	"Fair enough, I guess. I know how it pays to be cautious... ",
	"In that case, we have no more to talk about! ",
	"Then we're agreed. I will wait for you till midnight. If you fail to show, the deal is off.",
	"Fine, I understand.",
	"Very well. Sounds grand! ",
	"So. Show me the goods.",
	"You know, I have some bad news. The goods have vanished, but you'll have to pay for them anyway.",
	"Hmm. Every single time... ",
	"What do you mean?",
	"If I'm counting right, you're the fourth scoundrel that has pulled this scheme on me. What is it about me, do I have the face of a greenhorn?",
	"So... I take it you killed them all? Hmm... Quite the worthy opponent... ",
	"Look, just tell me where Austin is, and I'll let you live.",
	"If I tell you where Austin is, I know I'm a dead man - the gang doesn't abide betrayal. This way, 'least I got a chance to survive.",
	"No. No, you don't. Tell me, and at least you'll have a little longer to settle your affairs.",
	"I think I'll take my chances.",
	"Well, it's your life. ",
	"Hey, ",
	" . Tell me, are you Captain ",
	"Yes, that's my name.",
	"Got a message for you. Man named Austin wants to meet with you.",
	"Hmm... Tell him I agree.",
	"under",
	"behind",
	"Great. He'll wait for you until midnight, in the catacombs ",
	"the city. You can find me there. ",
	"This is getting monotonous. Yes, all right.",
	"Ah, here you are... ",
	"Where is Austin?",
	"He didn't make it, but asked me to give you his greetings. And then to kill you.",
	"Yes, all right. Look, do you even know what happened to the last four guys?",
	"I do, but I think I'll manage.",
	"Yeah? Well, if I'm going to die anyway, you might as well tell me where I can find this Austin guy. I hear he's in the market for a new scam.",
	"He lives in one of the pearl diver villages, on the west side of the Main.",
	"Ah, thank you. I would never have looked in such a far-away place. ",
	"Not that the information will do you much good. ",
	"Well, you never know.",
	"Why, hullo! Visitors are right uncommon 'round these parts. What can I do you for?",
	"Hello, Austin. I just wanted to break out of the catacombs and meet you face to face. All these messengers start to look the same after a while... ",
	"Austin, you say? Ain't too many folks know that name. Oh, I get it. You're that captain what's been slaughterin' all my men! ",
	", if I ain't altogether mistaken... ",
	"Yes, Austin, that's right. Tell me, friend, what is the world coming to when murderers lurk the streets, luring the innocent into dark holes and then ripping their guts out?",
	"Lawd, I can't believe my ears! You ain't tryin' to shame me? You think you're so diffn't a' me?",
	"And what do you mean by that?",
	"Don't you tail merchants all over th' sea? Don't you chop up people by the barrel? And what for? Wait, I'll answer that my own self: for money.   \nYou and I, we's brothers in blood! Only diff'nce is, my operation is land-based.",
	"I don't fall so low as to lure people into burrows! ",
	"Yeah, well. Don't you raise other people's flags, pull the wool-eyes over yer victims to thusly approach unhindered?",
	"That's different... ",
	"Oh, it is, is it! It is, is it! Mah friend, deceit, murder, takin' a victim's possessions. It's all the same, my sea brother.   \nLook, I'll answer yer question f'm the beginning of our conversation: nothing extraordinary is afoot. Everything is copus mentis.",
	"You're a real smooth talker, you know that?",
	"Hmm, may be. May well be! Tell me why you're here, sea brother.",
	"Look, you're certainly adept at spinning the dials, but I wasn't born yesterday. The difference between us is enormous. I offer people a choice: surrender or die. You give no option, and your meeting place is quite literally a burial ground. So you are no brother of mine.",
	"You sayin' you wish to further escalate our hostilities?",
	"Nothing would give me greater pleasure. I want to finish what I started, and rid the Caribbean of your bile.",
	"Wal... Guess it's fer the best, then. You're a bit of an itch on my unmentionables as well. Let's get it on, Seignior! ",
	"About time... ",
};
