string DLG_TEXT_Q [177] = {
	"Nothing to say.",
	"Okay...",
	"I'm listening closely.",
	"My name is ",
	". I received the needed instructions from Governor Maddyford.",
	"Well. Caught you, birdy!",
	"What? Are you joking?",
	"Argh... Cursed English dogs! I'll cut open the belly of one, at least...",
	"Try it..",
	"May the day you came aboard my deck be cursed...",
	"Hm. You shouldn't be like that...",
	"Greetings! What fate brings you to my deck?",
	"I'm here to see a successful privateer. They say you've taken three Spanish galleons!",
	"We've discussed  everything already, ",
	". I'm docking to unload at Port Royal.",
	"Very good.",
	"Dammit! I listened to you, went into port, and my cargo was confiscated immediately! You set me up!",
	"What? Who confiscated it?",
	"So, what did our old fox in fancy dress of a governor say?",
	"It's difficult for me to admit this, but it looks as if we've been had. Maddyford won't return your cargo.",
	"Do you have my indigo?",
	"I went after a pinas, but I didn't even see its stern before it got away from me. Sorry...",
	"Do you have my indigo?",
	"I captured that Spanish pinas next to the shores of San Juan. Only there wasn't any indigo, gold, or mahogany in the hold.",
	"Do you have my indigo?",
	"I captured that Spanish pinas next to the shores of San Juan. Only there wasn't any indigo, gold, or mahogany in the hold. I searched the whole ship, but didn't find anything valuable inside. Sorry.",
	"Do you have my indigo?",
	"Sorry, but that pinas was too much for me. I was unable to take it.",
	"Do you have my indigo?",
	"The damn pinas went to the ocean floor - and the prize, with it. I did everything I could. Sorry.",
	"Who do I have the honor of speaking with? Introduce yourself!",
	"I'm an English privateer. My name is ",
	"You must arrest Maddyford. Hurry.",
	"Fine, sir.",
	"Are you and your ship ready to do this mission?",
	"I'm ready. We'll leave immediately.",
	"Later. I need to replenish supplies. The journey will be dangerous.",
	"You're inexcusably late with finishing your assignment! You already know that I'm pressed for time. How long can a man wait?",
	"Sir, forgive the delay, but it was necessary. I'm ready now, so let's go at once!",
	"Sir, I need to conduct a few more preparations. I can't place your life in any unjustified risk from not being prepared enough. I'll ask you to wait a little longer.",
	"I'm grateful, from the bottom of my heart. You've shown real spirit, while battling a serious enemy. Moreover, you've made it in time to Saint Jones. I'm giving you a letter for Sir Thomas Maddyford. Place this dispatch into his hands personally. Farewell!",
	"A good trip to England! Farewell, sir.",
	"I'm grateful to you for the heroism shown in the battles with the Spanish. But your slowness has ruined all of my plans! I'm giving you a letter meant for Maddyford. Go! I'm not holding you any longer.",
	"All the best, sir.",
	"No, I'm asking. You've gotten in deep. And what happened? Was all that noise in the city because of you?",
	"Your moneylender, Josef Nunen de Foncesao, is an honest villain. I had a business proposition for him, but when we made our deal he summoned the guards and I was arrested, my money and weapons taken away. Now I'm being accused of spying.",
	"Hm, that sounds like our Josef... And what deal did you offer him?",
	"To buy some jewelry and some Spanish junk. I'm a corsair. Didn't want to go to Tortuga, and wanted to trade it nearer.",
	"Heh. I've got nothing against you corsair boys. I like you guys. However, once you let Joseph drink, he'll try to kill you that very same night, just so you don't blab anything unnecessary. He doesn't need any corsair connections, and the reputation of a junkman. He is, after all, a respected person in the city.",
	"If you help me get out, I won't stay in your debt.",
	"I'll open your lock on the grating. You can leave as soon I go. I don't need any money I've got my own score to settle with Josef...",
	"Gotcha. Well, thanks.",
	"Get out of here yourself. I won't be any help to you. Actually, since you don't have a weapon, let me give you a sword from the prison arsenal.",
	"Goodbye. I hope that Josef will be long in rage.",
	"Don't doubt that. Farewell, friend. Once again, thanks for the help.",
	"Maddyford, under his orders.",
	"I don't understand anything. Why did they confiscate it?",
	"They gave the cargo over to the Spanish owner.",
	"I don't believe my ears! And we're friends with the Spanish?",
	"Who the hell knows!",
	"I'll sort things out. Wait for me here.",
	"Well, did you learn anything?",
	"Not yet, but I'll figure this case out for sure. Wait, and don't leave the tavern.",
	"You've just floored me. Those goods were needed, to put out my debts.",
	"As soon as I stepped ashore, into port, I found that all of my bills had been bought by a small-time moneylender. He blocked my way to sea, and my ship is collateral for the loan. That's how it is!",
	"How much do you owe?",
	"My loan consists of about 140,000.",
	"You know what? Your debts are your own problems. Goodbye, and be healthy.",
	"I've got 140,000. I'm in your debt, since you got into the trap because of me. So take it, and resolve your problems.",
	"I'll return your goods.",
	"And the best of health to you, my oh-so dearest friend.",
	"May we all be healthy. Farewell, and amen... ",
	"Captain, there are rumors that you weren't too nice with Williams, the poor lad...",
	"You're a real dishonorable man, Captain ",
	". I don't want to speak with you.",
	"You know, Captain.",
	"Morris Williams says horrible things about you! If you were to listen to him, you'd think that you were a real villain...",
	"Oh boy, you don't have that kind of money. Well, I'll wait at the tavern until you find it.",
	"Yeah, that's right, I let things out of sight... Don't worry. I'll be back soon. You won't have to wait long.",
	"You're an honest and honorable person, Captain. The laws of the Brotherhood of the Coast aren't an empty sound for you. I'll take this money, because I require it. I thank you.",
	"No need for gratitude. It was my fault. As soon as you're finished with your debts, I hope to meet you at sea. Goodbye, friend.",
	"Captain, they say you really saved Williams; that you took care of his debt. You're an honorable person, Captain. It's an honor to talk to you!",
	"Very happy to see you, my friend! How are things, Captain ",
	"Everyone is good, Morris. I hope things are in order on your side.",
	"I wanted to take care of it, but I can't my ships in lockdown.",
	"I wish you luck. The confiscated goods must've been taken already, by the Spanish. You need to find out which ship they're taking it on. From there, it should be easy!",
	"Who do you think might know this?",
	"Your friend Maddyford, first of all. Who else?",
	"Otherwise, I don't know. Ask around the tavern? Try the brothel, the port. Maybe you'll even meet someone on the street. ",
	"I'll go look. Time is short.",
	"Yes, please hurry. My cargo is mahogany, silver and indigo. I don't care much for anything else.",
	"All right. Wait for me here. I'll settle this matter.",
	"Did you find anything? When will I get my cargo?",
	"I'm working on it. Hold your horses.",
	"By God! Where are my goods?",
	"No clue. The Spaniards may have unloaded them along the way somewhere. Sorry.",
	"My guess is, the Spaniards sold it along the way. I found a hundred-forty thousand coins in the captain's cabin! The money is yours, so maybe you can settle your debts.",
	"That's it, I'm finished. Oh well, my friend. Thank you, you've done all you could.",
	"See you, Morris. Do your best to stay free, won't you.",
	"Captain, people say that because of you that Morris Williams became penniless... ",
	"Oh, thank you! You're a man of your word! You'll be my friend forever. I have nothing to express my gratitude. Actually... no, there is one thing, veritably priceless in our line of work. You've shown yourself a fearless man, so maybe you can do what my crew and I daren't.",
	"Well, you've piqued my interest. What is this thing that gives even such roughnecks as yourselves the shivers?",
	"And where is the money? You don't have it, do you! ",
	"Oh. I knew I forgot something. Don't worry, it will all be in your hands presently. I'll be right back... ",
	"It's a cuirass. Not just a cuirass, though; I can't imagine there's another like it in all the Caribbean. Here, it's a long story... ",
	"Two and a half years ago, my frigate was thrown to the reefs in the northern Main - the Bay of Death, they call it. Only half my crew survived. The rest never got off the sand of that beach.",
	"My navigator, a Dutchman named Lambert Groff - an extremely brave man. He was amongst those who vanished that night.",
	"On his person was all manner of gear, of the highest order - amongst it, that cuirass. More than a tremendous piece of armor, it was a real work of art. I wanted to return to the ship, but the cutthroats who were left talked me out it, their eyes filled with tears.",
	"The thing is, after the crash we somehow managed to reach the gulf of Cozumel, where a Dutch merchant ship picked us up and brought us to Tortuga. On arrival, five of my crew elected to take a lugger to Cabo Catoche, to the harbor with our ruined frigate.",
	"Which is understandable - to salvage their own jewelry, money, what-have-you. When those five didn't come back, another five went after them. Of the ten, not one has been seen again. To this day, I don't know what happened to them. I just know I'll probably never return to the grave of my old frigate.",
	"As to whether it's worth a look - well, judge for yourself. It's possible the pirates simply took what loot they could and made straight for the Old World, or maybe the Colonies. Who knows... ",
	"The damned cuirass, however, is a prize and a half. Its true value, of course, is not monetary but in the protection it offers in combat.",
	"Indeed. Well, thank you, my friend. It's certainly an interesting story.",
	"Morris Williams is always extolling your bravery. An excellent pirate and an honest man, he says - a description that is simply amazing! I never dreamed such men still graced the earth.",
	"To hell with your apologies. I've got a jail term on my head, and you're whining about a wounded pride! ",
	"Well, I'll do my best for you... despite that unfortunate business with the pinnace.",
	"You know, I'm getting sick of your rudeness. All told, I don't really owe you a thing. Goodbye, and be well.",
	"Well then, I'll be grateful for any help. And what do you intend to do?",
	"Don't know yet. Let's see what happens next, before we commit ourselves.",
	"Whatever you say. ",
	", thanks for not leaving me in the lurch. Now I have some business to clear up. We'll meet again later.",
	"Don't worry. It'll all be okay.",
	"It is so. I managed to intercept a small Spanish squadron.",
	"My frigate attacked the Catholic hypocrites, and they elected to flee for themselves, instead of working together to fight me. I took the galleons, one-by-one.",
	"So. Did you bleed the Spaniards?",
	"On the contrary. On the first galleon, I disallowed my men from drawing a drop. After that, seeing there was no threat to their lives, the others gave up practically without a fight.",
	"Hm. When the Spartans engaged in battle, they never chased a fleeing opponent. Actually, it was banned by law. Their Lacedemonian opponents knew that if they dropped their weapons, they would live. That's why, as a rule, the enemy would give in to the Spartans after the very first strike. Seems this strategy still holds water.",
	"I don't know about any Spartans, but a reputation as a merciful pirate may make me very rich. That much I do know.",
	"Fine, speak. What do you want? ",
	"Thomas Modyford gives you permission to dock at Port Royal, and sell your plunder in the island's stores.",
	"Hm, I have a French privateer patent and want to go to Tortuga. I have there well-established connections.",
	"You don't ignore an invitation from the Governor of Jamaica. My advice to you is to accept.",
	"Well, all right. No skin off my nose. More convenient, anyway. ",
	"All right. It means losing some profit, but whatever. I'll head to port immediately.",
	"Good luck, Morris. We'll meet again.",
	"I have heard of you. Your service to the British crown has been extremely impressive. ",
	"Thank you, sir.",
	"My name is Thomas Lynch. I was chairman to the Jamaica Council till 1664 - until this bum Modyford was appointed Governor.",
	"Sir, Thomas Modyford is the Governor of Jamaica... ",
	"No longer. You should know that the government's patience has run out.",
	"From the beginning of his governance, Modyford had clear orders from His Highness Charles II to curb piracy and maintain friendly relations with Spain.",
	"Instead of following this directive, Modyford supported piracy, and his last trick - capturing and looting the mainland coast - caused a scandal unprecedented in Europe! Spain's own Queen Anna spent three days in hysterics.",
	"Sir, surely it's the Spaniards' own fault? They started hostilities by attacking Port Royal.",
	"Yes, but it would be difficult to blame them for it, since Port Royal is a haven to all manner of bandits and robbers.",
	"You should understand that the balance of power in Europe cannot be risked for the sake of a pocket of criminals! ",
	"What about Tortuga, sir?",
	"Tortuga is a French colony, and France is in a permanent state of war with Spain. Ha, Louis, if I may say so, cools off the fervor of Papal followers in Europe.",
	"England cannot afford a significant strengthening of the French influence in the Old World, which is why we are moving towards a peace treaty with Spain.",
	"And in the midst of this, our dear Sir Thomas Modyford does devil-knows-what! ",
	"I see.",
	"Moreover, we have clear reasons to believe that Modyford is preserving the current status quo in Port Royal for his own financial gain.",
	"Plainly speaking, he robs privateers that rob the Spanish.",
	"Sir, we do actually surrender ten percent of our plunder to the British treasury.",
	"Like hell! The British government has never seen this money.",
	"We also know that Modyford enjoys a special relationship with important pirates and buccaneers. Their so-called joint ventures provide them with astronomical profits.",
	"Sir, I have taken part in some of these... ventures, and can confirm that things are exactly as you say.",
	"I had no doubts... Listen, I have a business proposition for you.",
	"I'm all ears, sir.",
	"You see, Modyford is going to be arrested. However, this is no easy thing to do.",
	"The garrison stationed in Port Royal remains loyal to him. We actually may provoke violence of British against British, which I care to avoid. Anyway, the garrison at Port Royal is quite strong.",
	"Is it true that you have direct access to Modyford?",
	"That's correct, sir.",
	"Very good. I need you to take one or two of my men to Modyford in his residence, as inconspicuously as possible. Nothing out of the ordinary.",
	"When you're with Modyford, you are to quietly arrest him. I will give you all the necessary authority.",
	"Obviously, Modyford is not nearly a fool, so this will be extremely dangerous.",
	"Indeed it will. Presumably the reward accounts for this?",
	"That is my expectation. What would you like?",
	"I've been quite close to Modyford of late, so whoever you install as the new British authority, I want some indulgence for my activities. There's no sense in my taking a backward step.",
	"You are in no wrong, by my eyes. You have acted according to a your privateer license. If you successfully arrest Modyford, then I guarantee you not only an indulgence, but a certain fealty of the British authority toward your person.",
	"Excellent! Second, I would like half of Modyford's ill-gotten wealth.",
	"Hmm... You are a very crafty fellow, ",
	"Believe me, I have some stake in this money. My own contribution to his piggy bank is not insignificant.",
	"Well, damn... You got yourself a deal! Half of all the confiscated money is yours. I thus declare you deputy, and give a mission of an extreme import.",
	"So. You are to go immediately to Port Royal and arrest former governor and enemy of the state Thomas Modyford, for trial in London.",
	"Aye-aye, sir.",
	"Haste is a virtue, in this case. Now go and complete your mission.",
	"Yessir.",
};
