string DLG_TEXT_Q [79] = {
	"Nothing to say.",
	"Okay...",
	"Hey, Captain. I think you were planning on going out to sea?",
	"Yes, I'm leaving. And what business is it of yours? Who are you?",
	"Good day, Captain. It's me again, the boatswain from the Favorite.",
	"What do you say, this time?",
	"What do you want from me?",
	"Listen, the Holy Father asked me to ask you...",
	"Did you find anything about my husband, sir?",
	"Not yet. I'm working on it. I'll do everything to find him,",
	"Sir, I'll never forget what you've done for us. You've saved my husband's life, and freed our family of debt. We'll name our child in your honor.",
	"It's you again, sir. I'm so happy to see you!",
	"Sir, how many times have we seen each other today? This is just wonderful!",
	"No matter how many times you address me, sir, I'll always be happy.",
	"Well, now it's empty... But know that it feels nice anyway,..",
	"Fine...",
	"I think so too...",
	"Hm, it feels so good! Thank you.",
	"Damn...",
	"Who are you, and what are you doing here?!",
	"You've saved my life! Thank you!",
	"Save the thanks for later. You're called Tom Attreberry?",
	"An English privateer! Thank the Lord!",
	"What's happened here?",
	"You must hurry. The galleons left almost a day ago. You might not make it.",
	"Yes, I know. I really must hurry...",
	"I'm the boatswain from the frigate they call the Favorite. I saw you just recently, on our deck. You were talking with the Cap...",
	"That's correct. Continue.",
	"Our Cap's in the tavern. he's already drunk a small barrel of rum. He sent me to find you. He's waiting. This is urgent.",
	"Fine. I'll go at once.",
	"There's little that's good... Or, rather, nothing at all. Our Cap'n Williams was just arrested as he was leaving the tavern.",
	"He was surrounded by about ten soldiers. The head of the jail showed him some paper, and the Cap was whisked away.",
	"And you didn't stand up for him? Where's your team?",
	"There's no team. Everyone's run off. Only a few people are left on the ship. And the ship's been taken as well...",
	"In general, things are going badly. Very badly...",
	"I'll go to the head of the jail, and find out what's what. Don't gawk. Go to your old tub, and keep everything in order. I'll get your captain out, without a doubt.",
	"What's the matter, sir?",
	"Don't be scared. I won't harm you. I've got a score to settle with the moneylender. As far as I understand, we've got things in common.",
	"Sir, this... this is horrible! M.. my husband, Tom, has disappeared!",
	"Calm down, please, and tell me in more detail.",
	"We borrowed some money from the moneylender, and couldn't repay it in time. So he came to our home and told my husband he would throw him in jail unless we repaid the loan within a week, with interest.",
	"We sold all that we had, but it still wasn't enough to cover the interest built up throughout the year.",
	"My husband asked for an extension, but all he got was another week to pay the remainder.",
	"So he left to look for money. Instead, he found something that he sad would deliver us from fear of ever facing prison again.",
	"Yesterday he spent the entire day in the city, then came back for a moment, got his things, and disappeared into the night. I haven't seen him since. I'm terrified for him! ",
	"Where did he go? Did he say anything?",
	"He only said he was going outside the city. No more. Just, he was in a great hurry... Sir, I beg you, help me find my husband! ",
	"I will do everything in my power.",
	"Finish him off! We need no witnesses... ",
	"Hmm... ",
	"Yes, how did you know? No, it doesn't matter - I couldn't be more happy to see the Archangel Gabriel! ",
	"Tell me, what happened?",
	"I don't even know where to begin... About a year ago we borrowed some money from the moneylender... ",
	"I already know all that. Start from the moment you left your home. What did you learn about the moneylender?",
	"It turns that devil is connected to smugglers! Yesterday I saw a queer-looking stranger, entering his house. I waited 'til he left, and followed him.",
	"I managed to track him, until I walked straight into an ambush. They grabbed me, and dragged me here. They wanted to kill me, but then decided to learn who I was first, and if I was any good to them alive.",
	"You arrived just in time. Thank you, sir, from the depths of my heart! ",
	"Yes, I see. All right, run back to your wife. She's at wits' end. No must worry about the moneylender from here. But don't mention this to anyone. Better yet, best leave town, soon as you can.",
	"Three galleons full of Spaniards, arrived at port... They took the town by storm.",
	"Dammit! Where is Mansfield?",
	"Dead, like so many others. About half of the buccaneers managed to withdraw, else we'd all be dead too.",
	"You call yourselves buccaneers? Since when do you retreat before Spaniards?",
	"There were a lot of them. And well-armed.",
	"They removed the culverins from their ships, and shot us to pieces, while staying just out of range of our firearms.",
	"We attempted a raid on the Spanish battery, but in three musket volleys they annihilated the assault group.",
	"None of our men survived - these devils immediately counter-attacked, finishing off the wounded on the way... ",
	"Curses! I came to Mansfield on Modyford's orders. I'm here to take the gold that's waiting for him.",
	"The Spaniards took everything. Mansfield is dead.",
	"What else can you tell me?",
	"I know they sailed back to Cuba, to Santiago.",
	"How do you know?",
	"When the Spaniards burst in here, I played possum, and lay over there, to the side.",
	"I understand a bit of Spanish, enough to get by, and heard their captain talk. They called him Manuel.",
	"They combed the settlement, loaded everything they found onto their ships, and left for Santiago. Or at least, that's what they were planning. From what they said, that's where they came from.",
	"Manuel... This wouldn't be Rivero Pardal? The only Spanish corsair in our waters? Hmm... all right, thank you. Your comrades will return soon. Tell them I will avenge all this.",
	"Thank you. You'd better hurry, if you want to catch them up.",
	"Don't worry, I won't have any trouble catching a bunch of galleons.",
	"I couldn't even image that you'd treat me this way... ",
	"I'll paraphrase you, sir: 'I have nothing further to say. Politics decide the fates of nations; there is no point in sweating the fate of individual... governor-generals.' Farewell.",
};
