string DLG_TEXT_Q [696] = {
	"Nothing to say.",
	"Okay...",
	"Good day, Captain. Won't you allow me to discuss one matter with you?",
	"Why not? With pleasure!",
	"Hm. Understood... Well, then. That's a pity.",
	"Wonderful! I can see you're a busy man.",
	"Closer to the point, dear.",
	"Ha-ha! I like your style!   \nLet's introduce ourselves, first. My name is ",
	". Forgive me, but I've checked a few things out, and know that you're captain ",
	". I also know that you are a privateer. Is that so?",
	"Correct. Everyone knows about me well enough. And what kind of business do you handle?",
	"Let's just say I'm a busy man.",
	"Wonderful! And what business do you have for me?",
	"Well, it's a small matter for a courageous man such as yourself. My employer has seriously begun worrying about the moral and ethical state on the islands of the Caribbean.",
	"I'm very happy for your employer. I'm not for moralizing though...",
	"But you'd make a great scavenger!",
	"What are you talking about? I'll repeat myself: get to the point...",
	"Well, fine. I need you to get rid of the poor and the panhandlers in the cities. By that I mean every city, whatever the nationality. We're ready to pay a million piasters for this job!",
	"Heh. Intriguing. You won't find a million lying on the road...",
	"Who do you take me for? A hired killer?! Get out of here while you're still whole...",
	"My dear, you won't find it lying around anywhere. Alone, or in bunches... Hee, hee... ",
	"Oh, I see you're a joker as well! Let's discuss the conditions of this deal.",
	"With pleasure! Now, I put a million piasters in your name with the moneylender of, let's say, this city. A deposit. Upon finishing the assignment, you can take that money.",
	"An advance? I'll have to travel a lot.",
	"Unfortunately, there can be no talk of an advance. That's absolutely forbidden.",
	"Hm. A pity... And the deadline? Am I time-limited?",
	"No, not really. Just do it, and you'll get the million. I don't expect you'll be wasting any time, hee hee...",
	"Hm. Well, I'll get around to it. When, and how, can I certify that a deposit has been made in my name?",
	"At the local moneylender, today even. And you can take your million, with my permission. When I don't see any poor on the streets of the cities, I'll let the moneylender know about the successful completion of your assignment.",
	"Well, let's shake on it!",
	"Now, that's wonderful. I don't think we'll see each other again. I'm happy that you've agreed to this job. I hope to see the job finished soon.",
	"Farewell. Actually, who's the employer that's got such a bug about these bums?",
	"Forgive me, but I can't say.",
	"Hm. Well, okay. Farewell...",
	"What? Who confiscated it?",
	"Hm, listen. Is that you, Keymaster?",
	"Yes. And who are you?",
	"I'm called Captain ",
	"And what do you need, Captain ",
	"Listen, were you the one who made the chests in the house of Governor-General Stuyvesant? I want to order the same thing, with a lock. ",
	"The one with the lock was made by me. I can tell you without exaggeration that you've come to the right place. I'm the most famous Keymaster! I do have a namesake, some slant-eyed bastard who doesn't hold a candle to me. But I'm the real-deal Keymaster!",
	"Well, excellent! This is what I need. I need the same exact chest as the Governor-General.",
	"Heh, I don't make duplicates. I'm not a factory, you know! Every one of my works is one-of-a-kind. And whoever heard of putting in the same lock? That way the keys would match!",
	"See, pal, that's what I'm talking about...",
	"Ha! So you aren't a regular customer, I see...",
	"That's it, buddy! This isn't a regular order - so the payment won't be regular, either...",
	"A special payment, you say? As I understand, all you need is the key.",
	"You got it.",
	"Mm... Well, that's fine! For such a key I've got to ask ",
	"?Caramba! Not a bad price!",
	"Hoo, buddy... So you're a bum, are you? What kind of payments were you talking about?! You know, those who have wind whisting in their pockets can't be my customers. What were you thinking?",
	"What do you mean?!",
	"What I'm sayin', pal, is you aren't even up to paying my usual service fees, never mind special orders. Come back when you've got the piasters. Until then, don't bother me.",
	"Okay, I'll come back later...",
	"Well, that's much better. Let's get back to our talk about the keys. Anyway, I'm prepared to make it for, let's say, ",
	"Ha-ho! Not too shabby!",
	"Don't even come here, with your offers. You were without a coin in your pocket, and have remained so. I don't need clients like that.",
	"Hm. Guess I'll get myself some cash.",
	"I'm not used to small-time jobs. You must understand, I am THE Keymaster! Anyway, show me the money and the job's done. Otherwise, no way!",
	"Hm. It looks like I've got nowhere to go... Listen, maybe you'll knock the price down?",
	"No way, pal. You yourself understand what you're asking..",
	"Take it. Where's my key?",
	"It's got to be made, dumbo. Come back to me in a day or to. I live in a house not far from the stairway to the church.",
	"Fine.",
	"Aha! Here you are!",
	"Yes, it's me! Where's my key?",
	"Key? Hmm, you know... It's hard for me to say this, but the Governor-General really wants to talk to you...",
	"What?! You ratted me out?! You bastard!",
	"And what did you want? I'm not an enemy to myself! Anyway, there are some soldiers here. They'll escort you.",
	"Why, you... You parasite! Why'd you take the money, then?!",
	"For the work. I made the key, like I promised. I keep my word!",
	"Oh, yeah...",
	"Come with me, Captain!",
	"Where to?",
	"To the jail. And don't even think about trying something funny, or I'll be forced to use force!",
	"Ah, officer... The sad thing is, I too will be forced to use force...",
	"Er... I didn't count on meeting you again... Have you completed the assignment? Any issues with the deposit?",
	"Oh, no. Everything's in order with the deposit. It's just... the thing is, I can't find one bum - Teaser Dan.",
	"You don't have to worry about him. You won't find him at all. Worry about the rest.",
	"Understood... But, really, where's Teaser?",
	"What, I'm not making myself clear? Teaser Dan isn't on the contest list. You got me?",
	"I understand, of course. But I'd really like to know where he is.",
	"Man, I don't like you persistence. If you continue in this fashion, you'll go right after Teaser.",
	"You mean he's dead...",
	"They don't come any more dead. And now please explain your relative curiosity!",
	"Fine. I know that you're the representative of the Dutch East Indian Company in the Caribbean Sea. I also know that you conduct business with Governor-General Stuyvesant. I also want to know why the hell the local bums have got you down.",
	"Don't you think you're asking a bit too much?",
	"Those aren't all of my questions for you. I want to know about the Island!",
	"Do you even know what you're getting yourself into, Captain? Sail to your health, fleece the odd merchant - that's not scary. But to get into the business of the company that owns the entire Indian Ocean is madness.",
	"Complete the mission you took upon yourself, take off the deposit, and continue playing the prankster, and no one will lay a finger on you. But your curiosity might quickly lead you to the grave. I'm giving you one last chance, Captain, to leave here in peace.",
	"I gather I won't be using that chance. I also want to know about all those luxury items whose price-drops you so fear...",
	"Ahh... Captain, I'm afraid you've played your last tune. As one of my deceased acquaintances once said, I know too much...",
	"Well, what are you going to do, West Indian weasel?",
	"I'll kill you. Right now, in fact!",
	"Don't lose your pantaloons when you're planning to kill...",
	"Well, tell me. What news have you got?",
	"What are you talking about?",
	"Enough acting! Andre has told me about your plans.",
	"That idiot!",
	"Andre Labor is a law-abiding citizen of the city. But you're going to have to tell me about Teaser Dan, or the admiral will be working you over tomorrow.",
	"Oh, he doesn't know yet? That's great! Hm... I'm afraid you'll have to die.",
	"What?! Andre, come here!",
	"Ha! The carpenter's on watch? That's good, too!",
	"What are you doing here?!",
	"Me? Well, how can I put it...",
	"You idiot, don't you know that this is the territory of the narwhals?",
	"Oh, I know...",
	"What are you, crazy? Are you looking for death?",
	"Well, yeah... But just your death. Sorry, buddy. I'll have to kill you now.",
	"I'd like to know who you are.",
	"I'm called ",
	". I'm a privateer.",
	"Why the hell did you attack my xebec?!",
	"Just orders. I have to send you to the bottom. You ruined our relations with the merchants...",
	"And a privateer's saying this?! I don't think you pity the merchants that much...",
	"This is work, pal. Nothing personal. Why don't you tell me how you and Pascal keep in touch. Just curious, mind. It was too difficult to find you.",
	"?Caramba! That ain't your business! Thanks for letting me catch my breath, and let's continue!",
	"Well, fair enough...",
	"Damn it, why the hell did you attack us?!",
	"This is revenge for your owner, pal. I got nothing against you.",
	"Good to hear...",
	"Take your lifeboats, and with the remains of your team go back to your owner. Tell him that ",
	" sends him a hello.",
	"Sure, I'll give him a hello.",
	"Then that's that. Live for now...",
	"Hello, pal. What do I owe the pleasure of seeing you on my brig?",
	"Greetings, Captain Bartholomew Sharpe! It's been hard to find you..",
	"Pal, I'm busy now! I can't help you now. No grudges...",
	"Okay, buddy...",
	"Yes, it's not easy... So what brought you to me?",
	"You know, buddy, I want to get in on that pearl business. Get a little something, so to say...",
	"Oh, a common soul! Then what's the problem? Come along!",
	"The problem with that is that I don't know where they conduct their operations. They're very elusive, and move around all the time! I just came to get the advice of an expert in this field.",
	"Hmm... Yeah, the pearl divers have started coming in a bit clever. You can't take them bare-handed anymore.   \nHere, I'll help you the first time; give you a pointer to the catching site.",
	"Ah! Sharpe, my pal. Thank you!",
	"Oh, no need for thanks.   \nListen to the strategies of our trade. Now, the pearl divers are real careful. They only work at uninhabited islands, or far away from the curious eye.   \nThat's why you've got to take them when they're hot, right when they're still in the sea!",
	"Listen, how do you discover where they're diving at any given moment?",
	"That's my big secret. I won't tell a soul, so don't even ask!",
	"Hm. Okay, you know...",
	"Now, hear this. They're in ",
	" at a place called ",
	". If you make it there in ",
	", then the pearl divers will still be there.",
	"Got it. Thank you, Bartholomew...",
	"Just cal me Captain Sharpe! I like it more...",
	"I prefer to be called Captain Sharpe!",
	"Hm. Okay. Thank you, Captain Sharpe. You've really helped me out!",
	"Don't mention it, pal. If anything else comes up, just ask me...",
	"They say, to help your colleagues is a sacred duty... So stop by again, and I'll do what I can! ",
	"Of course, Captain Sharpe!",
	"Ooh, who am I seeing?! Greetings to a fellow believer!",
	"Hello, Captain Sharpe. How's life?",
	"Buddy, I'm busy now! I can't help you. No grudges...",
	"Well. Okay, pal...",
	"Yeah, everything's okay. Can't complain.   \n Well, tell me. What have you come for this time?",
	"For the same thing, pal. Tip on the dive sites...",
	"You know, pal, I've got some problems with that. My informant from the team's gone missing, and with him... Well, anyway, I don't know where the divers are.",
	"Hmm, that's a pity. That's life. Farewell, Sharpe.",
	"Yeah, it's a good business. But I can't use all my resources on you. I've got to live, myself.",
	"Resources?",
	"This is a regular one, and it's really none of your business.   \nAs a general policy, I can give you the occasional tip - but not for free. You have to compensate my lost profits, buddy.",
	"Hm. And how much do you want?",
	"I think that a sum of ",
	" would satisfy me.",
	"Hey. Captain Sharpe, buddy. What's the deal? That's too much for the moment! Be a friend, drop the price.",
	"Well, then. I agree, pal. Take your compensation!",
	"Okay then! This way is close to me, pal.",
	"That's great. So, what about the tip?",
	"Praise be! Did you, ",
	", find the sucker?! I'm no rag-stuffer, I'm Captain Sharpe! Sounds proud, don't it?! You think I don't know what you're worth? Oh I know, buddy. I know just fine. So c'mon. Out with the dough, or get off my deck and go wherever the wind may land you! ",
	"Why are you flipping out, Bartholomew?! Squeaky like a spar... I haven't come here to swab your deck or sharpen your anchor. So be more careful in your choice of words. Remember who you're talking to...",
	"I'm not hearing things right. You think I'm a sucker? What, are you powdering me up? I know you've got a good amount of dough. I know it, pal, real well. So out with the dough, or look for the pearl divers somewhere sou-sou-west of here...",
	"Bartholomew, you're always winding up, or creaking, like a spar. Remember who you're talking to...",
	"No, buddy. Not today! Things aren't going too well for me here, even without your requests. I didn't sign up to be a sponsor. Money on the table, anyway...",
	"Mmm... Yeah. A pity, Sharpe. A real pity. I thought you were a real friend...",
	"Well, what can you do. There's a lack of pearls for my Caribbean dream... Take your compensation!",
	"Okay, we'll let it be. I'm in too good a mood today. How's about I help you!",
	"Now that's the spirit! That's shore brotherly! So what about the tip, oh patron Sharpe?",
	"Okay, sorry I flared up a bit. But that doesn't change things. You shouldn't be such a miser, ",
	". It doesn't do the color of one's face good... Anyway, money on the table, or you won't be getting any tip.",
	"Well fine. Take your compensation!",
	"No, I'll decline from this business. Another time...",
	"Now that's what I'm talking about! I respect a captain, a colleague, and a comrade-in-arms!",
	"Likewise, Sharpe, likewise. So what about the tip?",
	"Well, you know. Farewell!",
	"All the best...",
	"We've discussed  everything already, pal. I wouldn't lose time, in your position.",
	"Yes, Captain Sharpe.",
	"We've talked already...",
	"Yeah, well...",
	"I can't help you there, friend. I'm without work too. I'll have to go after galleons now...",
	"To your return, buddy!",
	"Ah, Captain ",
	"! I'm listening to you closely.",
	"Bartholomew, I'm so happy to meet you! I had to search you out, but I was lucky in this city...",
	"Oh, who am I seeing in this city?! It's Captain ",
	"! My brother-in-arms and fellow believer!",
	"Yes, Bartholomew, in the flesh...",
	"Now, to what do I owe this attention?",
	"You see, I was going to go to the pearl divers and you're a known specialist in this stuff...",
	"Hey, buddy, great to see you! Well, then. let's begin... First to the tavern, then to the girls. Who do you prefer? White, or mulatto? I've got so many connections here, it'll make your head spin...",
	"Listen, Sharpe, I'm not worried about that at the moment. I've got a matter for you.",
	"Buddy, I'm busy now! I can't help you. No grudges..",
	"Well. Okay, buddy...",
	"Oh, it's not interesting that way... And what's the deal?",
	"Well, I wanted to rid the pearl divers of their extras...",
	"Oh, ",
	"! Pal! Come on up with me to the top! It's so much fun up there!",
	"No, buddy, I can't go now. I'm busy. I'm here on business.",
	"Pal, I'm busy now! I can't help you now. No grudges...",
	"Well. Okay, buddy...",
	"Say...",
	"I want to head over to the pearl divers. Shake them down a bit.",
	"Damn, we're being listened to!",
	"Ah, Captain ",
	"! I wasn't expecting to see you here...",
	"Well, surprise! And do I know you, friend?",
	"Well, how can I say... Maybe you didn't notice me, but I remember you from when you were visiting our brig, the Sharpener.",
	"Ha! So you're from Sharpe's team?! That means you've come to the right place.",
	"I don't understand what you mean, Captain.",
	"Well, buddy, I was very interested in finding out where Sharpe gets the locations for the divers' tartans. Now I know.",
	"Captain, Sharpe could kill for such a secret...",
	"Aha, and here I done gone and pissed my pants. Moreover, someone at the pearl setters would sure want to know about this secret...",
	"And who is this lover of secrets?",
	"Mmm...",
	"Isn't it obvious? Some officer, of course!   \nAnyway, let's drop him. For the cause...",
	"Well, try it.",
	"Come on, pal. Empty your pockets.",
	"What?!",
	"Out with it! Come on, faster! No talking. I don't like it...",
	"This is a set-up! And ",
	" works in a pair with you, is that it?",
	"In a pair, out of a pair. Empty your pockets, or I'll cut you down!",
	"Damn it all! For my pockets, I'd cut someone down myself...",
	"Take it, vermin! But this won't slide easily...",
	"Of course it won't. Who's arguing? See you, pal. And remember, you're not so beautiful as to have waitresses latch onto you while walking. You'll be smarter in the future!",
	"That's for sure!",
	"Well, you know.",
	"I know, pal. I know...",
	"And here I am! I hope you didn't get too lonely, cutey?",
	"I didn't have a chance.",
	"Then let's not lose time!",
	"Ha! Okay.",
	"Hello. I'm called ",
	". I'm captain of the ",
	"Excellent! I finally found you...",
	"Found?!",
	"Anyway, I've brought your ship's log, which you forgot at the port master's. ",
	"Damn, so that's where I lost it! Yes, that loss would have led to a mutiny on ship...",
	"All's well that ends well. Take your journal, and let's talk about my reward for all the trouble.",
	"I have yet to begin a new log, as was my plan, so I'll pay you the maximum that I can allow. ",
	"Not bad. Take your notebook, then.",
	"Hm. You know, I've started a new log. Nevertheless, I still need my old log, to shift into the new one. So I'll take it for ",
	"We're in agreement. The notebook again belongs to you!",
	"But I started a new log already. And I've already reconstructed the old entries from memory - it took me two whole days to sit and write it! Day and night! So I've no more need of he old log. So I can't pay anything for it.",
	"Nothing at all? So I pursued you in vain?",
	"Thank you. Well. All the best, pal.",
	"And the same to you...",
	"Well. If you wanted to pursue me, you should've been more industrious about it.",
	"Hm, That's right, I suppose... ",
	"Welcome to my deck. To be honest, I thought we were finished. Almost pissed my pants...",
	"Oh, pal, I'm in good mood today. I found you to help you.",
	"Welcome to my deck! What did you want?",
	"I was looking for you pal. Barely caught up with you...",
	"Looking? What for?",
	"You forgot your ship's log at the master-of-port's in ",
	". I've got it here! That's why I was looking for you - to return it.",
	"Damn, so that's where I lost it! This is valuable service, buddy. I'm at a loss for words. I'd have lost my captain's status... A really big thanks.",
	"So about that reward...",
	"Damn, so that's where I lost it! Thank you, of course, but you've spent so long looking for me that I've started a new one. Still, I do need a few things out of it - so I'll take the log that you have. But I can't pay much...",
	"How can you pay?",
	"Damn, so that's where I lost it! Thank you, of course, but you've spent so long looking for me that I've started a new one. I transferred the old notes from memory.",
	"What, you don't need your old log at all? At all?!",
	"I'm prepared to pay you ",
	". That's all that I can afford, myself.",
	"Well, okay. Here's your log.",
	"Thank you again. Goodbye, buddy. Be healthy.",
	"And health to you, too.",
	"Absolutely, buddy. You've spent too long looking for me. You should have hurried.",
	"Heh. Well, you shouldn't be losing your logs and I shouldn't be bouncing around without cause. Ah, well. Here - take your book. I don't need it, anyway.",
	"I thought we'd decided everything.",
	"Yes, that's correct...",
	"Greetings. What do you need, on my ship?",
	"I just wanted to trade news. Maybe you're selling...",
	"Nothing is being sold, and I don't have any news. And in any case, your presence on my deck isn't desired. I think I've made myself clear?",
	"Yeah, it doesn't get clearer... Well, okay. See you, pal.",
	"I said you've got nothing to do here!",
	"Understood...",
	"Why have you attacked us?!",
	"I wanted to return the ship to its owner.",
	"Which owner?! I am the owner!",
	"No, that's not so. I don't know who owns the ship, but I know that the ship was stolen off the ship lot of one of the ports. I must return it to its place.",
	"Damn! Well, everything isn't lost yet. I'll try to send you to the next world at least...",
	"Well, try it.",
	"That's something! What are you doing here?!",
	"Me? I'm guarding the church.",
	"Heh. That's how it goes, eh? And how's it coming along? ",
	"It looks like there are.",
	"Of course you'll forgive me, buddy, but you're not leaving here alive. It's a real pity, but you shouldn't have taken on this guard job...",
	"Ha! It's no pity to me. Robbing churches is going too far. I'll send you to your forefathers, without any pangs of conscience.",
	"Hell, Captain. I'd like to ask you to help me.",
	"Captain! Won't you do me a favor? The thing is, I'm in need of help.",
	"Captain, I ask you to help me!",
	"I'm busy! Not today!",
	"I don't have time to listen to you, at the moment.",
	"What's going down, with you?",
	"Tell me the heart of the matter. It's possible that I might be able to help.",
	"Once, a year ago, a captain agreed to transport me to ",
	". Aboard his ship, I was thrown into the hold and then sold into slavery. I got out of that pickle with a lot of effort. I was between life and death, many times... Anyway, I want to remind my friend that I'm still alive.",
	"You mean... Hmm. Be more specific about what you want.",
	"The thing is, my wife was captured. One captain, a rumored pirate, harassed her as much as he could. For a time, my wife didn't even leave her home, he was so persistent. I tried to get the city authorities on this problem, without results. And now they've done it...",
	"Done what?",
	"You know, I'm looking for my countryman - a man with whom I left the Old World, in search of a new life. It happened that we lost each other on the road, yet recently I discovered that he has become a trade captain! I tried to find him, but I couldn't handle it alone.",
	"What do you need him for? Many captains, including me, can get you wherever you desire.",
	"I want you to find him and send him to the next world. I'm so hungry for revenge that I can't eat...",
	"Understood... I think I can help you, in any case. Tell me the name of the captain, and the ship on which he sails.",
	"Sorry, that doesn't interest me.",
	"The captain is called ",
	". And he sails on a ",
	" by the name of the '",
	"ÿ. I can pay you in the area of ",
	"Gotcha. Well, then. I'll pay attention, when crossing the Caribbean. If I meet this captain, he's a-goner...",
	"I won't move a finger for that money. Find an idiot somewhere else.",
	"Phew... Oh, how I wanted to hear that! Oh, I can eat again! I need a snack...",
	"All right, pal. Once I do the job - I can find you here, in the city?",
	"Fine, I'll wait for you at the local church. I'll pay you there.",
	"All good.",
	"My relative inaction has led to sad results. That villain has taken my wife, and hauled her to sea on his ship. I'm asking you to find this scoundrel!",
	"Hm. I don't want to get between colleagues...",
	"I'm not rich, but I'll happily give you everything that I have! If you free my wife and bring her to me, I can pay you ",
	"Hm, well. I'm prepared to work on this matter. What's the name of this lovestruck knave, and what ship is he on? And what's your wife's name, while we're at it?",
	"Nah, buddy. I won't take this case, for that kind of money. My sympathies, though...",
	"Her name is ",
	". The villain captain is called ",
	". He floats on a ",
	" that he calls the '",
	"Certain byproducts of human life will float, buddy. Captains sail...",
	"Yes, yes, of course. Sorry! I'm no sailor, you understand...",
	"Everything's cool. Don't worry. Anyway, wait for the results of my search now.",
	"Thank you very much! I'll wait for you at the local church. But I beg you, hurry. I'm really worried about my wife...",
	"I'll do everything I can. Wait.",
	"The thing is, my countryman didn't get any real estate here. His home is his ship. So he's very hard for me to catch. He's always moving. And I can't allow myself to waste time on useless travels. I have to earn a living.",
	"If you don't have the money, I can't help you...",
	"I can pay you ",
	". That's all that I can afford myself, at the moment.",
	"The sum's satisfactory enough. All right, I'm ready to take the case. You can, if you please, come with me as a passenger. That way, you won't need to go to your countryman when he's found.",
	"That's too little for me. Find someone else for the job.",
	"No, I'd rather remain here. I don't know how long this search will take, and I might not have enough money. I have work here.",
	"I understand. Well, now tell me who your friend is and what kind of a ship he's got.",
	"His name is ",
	". As far as I know, he sails a ",
	" they call '",
	"I see. All right, as soon as I meet your compatriot, I will certainly let him know you're looking for him.",
	"Thank you. I will sit and wait for you in the local church. I suppose I'll have to part with the money once the job is done.",
	"Of course. Goodbye, then. Just you wait and see what I turn up. ",
	"Hello, Captain. Everything going okay? ",
	"Remind me, what was it that you want?",
	"Judging by the way you look, I'm guessing I have been avenged. Is that so?",
	"Precisely. ",
	" dead, and his ",
	" on the bottom.",
	"Is it true? Have you really found my wife?! ",
	"It sure is! She is currently a passenger on my ship. You can pick her up at any time... provided ",
	" is truly your wife... ",
	"Hello Captain. Did you find my compatriot?",
	"I did, and told him you were waiting for him here. So seems everything turned out well.",
	"What, have you forgotten my call for vengeance on Captain ",
	", for the year I spent in slavery?! ",
	"I don't forget things! I'm on it. Just hold your horses.",
	"I don't believe my ears! Did you forget your promise to find and liberate my wife? She was kidnapped by the pirate ",
	"You insult me, sir. It's just that the search has yet to see any results. The Caribbean is a big place, so you will allow me some time... ",
	"Wait... Did you forget about your promise to find my compatriot? A merchant captain, ",
	"No, I didn't forget. I just hasn't found him yet. Keep your feet on.",
	"Excellent, I knew I was right about you! As we agreed, here's your ",
	". Thank you for all your effort.",
	"Aw, weren't nothin'. ",
	"My God, you have given me a new life! Please accept your ",
	". Know what we will pray for you for the rest of our lives! ",
	"Sounds like fun.",
	"Wonderful! Here's what I promised - ",
	". And thank you, Captain.",
	"You are altogether welcome, my friend. Farewell... ",
	"Hello Captain. I would like to ask a favor of you.",
	"Captain! Won't you do me a favor? I am in dire need! ",
	"Surely, Captain, you won't reject a lady's pleas for aid?",
	"Not today, doll. I'm busy.",
	"Forgive me, ",
	", but I'm a bit under the wire at the moment... ",
	"What happened, ",
	"Tell me what is going on, ",
	". I will try to help you.",
	"My husband is a businessman. He hauls commercial cargo all around the area. Three months ago, he went to sea. Three months, and he has not returned! ",
	"A lot can happen in three months.",
	"Captain, I look at you and see a brave seaman, a skilled rogue... ",
	"What are you getting at, ",
	"Help me, Captain, I beg of you! My husband was captured by pirates! Please, will you save him?",
	"Hang about. I'm missing something, go back a bit - who was captured by whom?",
	"I don't know... I hope that he's just away on business. But he would have sent word. He knows how I worry! ",
	"As I say, anything can happen at sea nowadays... ",
	"Exactly! You look like a man of courage and integrity, and that is why I chose you to ask. I am prepared to pay for your services. Though all I have is ",
	"All right. If I meet your husband, at sea or elsewhere, I'll tell him your concerns. So what's his name? What kind of a ship is he sailing?",
	"No, I'm a little out of your league, honey. I'm afraid I must decline... ",
	"His name is ",
	". He works on the ",
	" they call '",
	"I see. Okay, you just sit tight. Also, don't wander too far from the church. I don't want to have to wander all over the city for you.",
	"I mean to, as they say, employ your services. I have a certain captain who has been a thorn in my side, and I would like to see him plucked.",
	"Good gracious! I didn't see that one coming! And what exactly did this poor soul do to you?",
	"The mongrel played me for a fool. He pretended to like me, even courted me. Then it turned out he was using me to get get a loan from my husband! Once this scoundrel found his loan, it quickly became quite clear that I meant nothing to him... ",
	"Hmm... you sure about that?",
	"What am I, a fool? Do you think I can't tell the difference between true courtship and empty blubbering?",
	"No, no. Forget I said anything.",
	"The bastard simply used me! I will never forgive him! ",
	"Yes, well. Perhaps you should take a step back and give it some time. These things pass, you know... ",
	"These things' pass?! What are you, a pirate or a priest?! ",
	"There, there. I can see you're committed. That's all I must know.",
	"You just don't know the rage of a scorned woman! ",
	"In some matters, my dear, innocence is bliss.",
	"You're a lucky man. A woman betrayed is the embodiment of fury, a devil in a dress! Nothing might soothe her rage!    \nAnd so... I want you to kill him personally, you understand. Make sure you tell him who sent you, before he draws his last breath... ",
	"Hmm. Really, I don't know what to say... How much are you prepared to pay for this?",
	"All that I have. I bequeath you my jewelry and, and a sum of ",
	". Are you with me? ",
	"Yes, all right. That's fine. So who is this rascal, and where can I find him?",
	"Well... no offense, miss, but I'd prefer to hear his side of the story before jumping into things. You know how it is. I'm a pirate. Must be fair.",
	"The bastard's name is ",
	", he is the captain of the ",
	" they call '",
	"Yes, all right, ",
	". Now how about you go sit in the church over there, and try to calm yourself.",
	"Yes, yes. I'll explain everything. You see, my husband - he's just an ordinary man, completely unremarkable - he was on this ship, and... well, he was kidnapped by pirates! They were killing everyone, totally no compunction, and... ",
	"So the Captain resisted, then. Otherwise they would have been spared.",
	"Well, I don't know about that. Maybe, but he's not that brave. He was just a passenger. Anyway, to save his life, he told the pirates he was a rich man - fabulously rich! And you know, they didn't even throw him into the cargo bay! ",
	"How would you know that?",
	"He sent me a letter, somehow, to tell me he was all right. He's being held in a cabin, away from the other prisoners.",
	"So what do you plan to do? This can't go on forever. Sooner or later the pirates will find him out.",
	"You tell me! Aren't you a pirate yourself? I beg you, sir, help us! Save my husband! I can describe the pirate ship for you, and tell you the captain's name... That should make it easy, shouldn't it?",
	"Lady, it's not that simple. All prisoners are lawful bounty of the captain who took the ship. Anyway, it'll take a while to do... ",
	"But you can try, can't you! Anyway, I don't think you must hurry. My husband is no fool - he told them he was a merchant from the Old World, so it will take a while for the pirates to try to cash in on him. If you save him, I'll give you all that I have! ",
	"And how much is that?",
	"Not... much. Just ",
	"... But I will pray for you for the rest of your life! ",
	"Yes, you're right. That isn't much. But never mind, I'll help you.",
	"Look, there's a certain professional courtesy at work here. I'm afraid I would need far more to attack a fellow member of the Brotherhood of the Coast.",
	"Oh, thank you! Thank you so much! ",
	"Yes, well. Save your thanks until we see how this turns out. Tell me your husband's name, and all you know of these pirates.",
	"Yes, of course. My husband's name is ",
	". He said the pirates called their captain ' ",
	", he commands the ",
	" they call '",
	"I see. Well, now it's time to wait and hope. Try to stay near the church, so I can find you in a hurry.",
	"Oh, Captain! How glad I am to see you! Quickly, tell me - what have you learned? ",
	"Hmm... Yes... ",
	", wasn't it? What was your problem, again?",
	"Captain, I received a letter from my husband! He said you found him.",
	"Yes, ",
	", that's right. ",
	" is alive and well. He just, er... lost himself in work, so to speak. You know how it is. At sea, I often lose track of time myself.",
	"What have you to say for yourself, Captain? Have you done as I asked? Is Captain ",
	" dead yet?",
	"Yes, ",
	". As a doornail. And I told him why I was there. Your name was the last thing to cross his ears, besides my blade.",
	"Tell me you freed my husband! Please tell me it's so! ",
	"Yes, he's sitting aboard my ship right now. You can go over and pick him up... Assuming ",
	" is really your husband... ",
	"You didn't forget your promise? You were going to find my husband for me! His name is ",
	"Ooh, right, right. Yes, of course I was. Mind like a steel trap, me. No, nothing yet. These things take time, you know. ",
	"Am I missing something? You didn't forget your promise, did you?! You were going to deliver my fury to Captain ",
	"Patience, ",
	". I'm on top of it. Just hold your horses. I'll let you know when it's done... ",
	"My God, you didn't forget about my husband?! You promised to free him! ",
	"Forget? Me? Of course not. I'm just biding my time, love. Don't worry yourself. ",
	"My God, I can't express my gratitude! My tongue is all thumbs! I... Well, I... here's the money I promised - all ",
	" of it. Thank you once again... ",
	"Aw, weren't nothin'. ",
	"Excellent! Here is your ",
	", and here is my jewelry. Farewell! ",
	"Yes, farewell.",
	"That's him! Oh Lord, Captain! Thank you so much! I can't tell you how grateful I am! Here, here's the full ",
	". I will pray for you each and every day 'til the end of my days! ",
	"That's nice. You do that.",
	"Greetings, colleague! What brings you, friend?",
	"I take it your name is ",
	"? Is that right?",
	"Yes, it is! ",
	"Ah, that's a shame. Then here's another question. Do you remember a certain ",
	"? Think hard.",
	"Hmm... Yes, I believe I do... ",
	"Well, he's not happy with you, friend. Free man sold into slavery, and all. So I'm here to extract payment. Nothing personal, you understand.",
	"Oh are you now? How much is he asking, then?",
	"Look, I'm talking about killing you.",
	"My friend, stop and think of whom you're representing. Who is this little man? What good is he? Surely he belonged on a plantation as well as anywhere. ",
	"Well, that's as maybe. But that's not your decision to make. So, you know. Hubris and all. What goes around comes around.",
	"Ha! Then I'll give as much as I take! ",
	"Yes, fair enough.",
	"What are you doing on the deck?",
	"I'd like to ask if you take on passengers.",
	"What's it to you?",
	"Nothing, really. ",
	"Well, nothing. Listen, why don't you leave while you still can? You're rubbing me the wrong way.",
	"All right, all right. Keep your teeth in.",
	"This conversation is over. You watch yourself.",
	"It's what I do best.",
	"Greetings, colleague! What do you want, friend?",
	"Look, you were in ",
	" recently, weren't you? I was wondering, did you find a woman there, name of ",
	"Hee hee, did I ever. She's in my cabin now! Pretty little minx! Why you asking?",
	"Buddy, she's married. You kidnapped a married woman! ",
	"So? I don't mind. I like her like she is. I ain' lettin' some bum get between us just because he happened to marry her! ",
	"Look, friend, the Brotherhood of the Coast isn't going to like this.",
	"What are you, my dad? What's the Brotherhood got to do with this? She's mine, and that's that! ",
	"All right, get your rankles down. I'm just saying. Anyway, see you 'round.",
	"Look, no offense but I believe I've said all I've got to say about women. ",
	"Yes, all right... ",
	"I'm so pleased to entertain a fellow scalawag! What brings you to my deck, friend?",
	"Look, you were in ",
	" recently, weren't you? I was wondering, did you find a woman there, name of ",
	"Hee hee, did I ever. She's in my cabin now! Pretty little minx! Why you asking?",
	"Buddy, she's married. You kidnapped a married woman!",
	"So? I don't mind. I like her like she is. I ain' lettin' some bum get between us just because he happened to marry her! ",
	"Look, friend, the Brotherhood of the Coast isn't going to like this.",
	"Did you come here to preach me morals? The Coastal Brotherhood has nothing to do with this, so your words won't change anything. She's mine, period!",
	"All right, get your rankles down. I'm just saying. Anyway, see you 'round.",
	"What do you want, bastard?! ",
	"I came for the woman you took from her husband. Remember ",
	"? Her name is ",
	"Hell, you've as much chance of seeing her as of seeing your own ears.",
	"You dolt, I can see my ears in a mirror. Yours, now, I'll be pleased to show you in person. Now hold still... ",
	"Who are you?",
	"Hello. Your husband sent me. C'mon.",
	"Is this a dream?! I can't believe it! ",
	"Nah. Real enough, ",
	"Oh Lord almighty! My prayers are answered! I take back all I ever said about you! All right, I'm ready. Let's get out of here! ",
	"Yeah, okay, ",
	". C'mon, follow me. Your man's a-waiting.",
	"Why, hello! Fancy meeting a colleague, so to speak, here on this dry harbor... ",
	", well, it's no coincidence really.",
	"Oh no?",
	"You've got a friend looking for you. He tells me you left the Old World together. ",
	" - the name mean anything to you?",
	"Ha! Of course, yes! Where has the old fool got himself?",
	"He lives in ",
	". I suggest he visit you in person, but no. I was going this way, so he asked me to invite you over instead. ",
	"Splendid! Of course I'll come! Thank you very much! Say... by the look of you, I'd say you're a pirate! Am I right?",
	"Right enough. But don't worry, I'm in a good mood today. Anyway, that's that. Goodbye. ",
	"Is everything all right? No problems? Forgive me, I'm just a bit worried... ",
	"Everything's just fine, friend.",
	". What do you want with me? I'm just a merchant captain, and... ",
	"Yeah, yeah, I know. Simmer down, don't stress your liver. I'm here on business.",
	"Business?",
	"Messenger duty. ",
	" is looking for you. You know the man?",
	"Oh, at last! Yes, all right. Forgive my awkwardness. By your appearance, well, I mistook you for a pirate! Ho ho! ",
	"Yo ho indeed. Well, anyway. There's your message. You can find your friend in ",
	"Really? You are a gentleman and a giant, ",
	". Thank you! ",
	"Not bad, eh? Goodbye, friend... and watch out for those pirates.",
	"Hello. Can I help you?",
	"Your name is ",
	", isn't it?",
	"Yes, that is I.",
	"All right. This may sound dumb, but your wife asked me to tell you that she's really worried about you.",
	"Ah! Oho! Yes, of course... Silly me, I've been so busy I'd forgotten all about her. You know how it is, business never sleeps! Can't drop everything just to placate a woman's worries.",
	"Yes, well. You could have written. ",
	"I suppose. Yes, there's an idea. Brilliant, actually. I'll do that right now, in fact! Thank you very much for your assistance in our family matters! ",
	"Uh-huh. My pleasure. ",
	"Greetings. What brings you to my ship?",
	"Your name is ",
	", isn't it?",
	"Yes, that is I.",
	"All right. This may sound dumb, but your wife asked me to tell you that she's really worried about you.",
	"Agh! Goddamn you! Honestly, man! When I saw your ship approach, I nearly soiled myself! Er... But moving on...    \nYou know, I've been so busy I'd forgotten all about her. You know how it is, business never sleeps! Can't drop everything just to placate a woman's worries.",
	"Yes, well. You could have written. ",
	"Yes, quite right. Quite right! I shall do just that, the next port I enter... Thank you very much for your assistance in our family matters! ",
	"Uh-huh. Thrilled, I'm sure. ",
	"Please allow me to thank you one more time... ",
	"That's all right. No need.",
	"I'm glad to see you here, Captain. Is there something you need?",
	"Yeah, actually... Woof, how do I put this... ",
	"Just say it like it is.",
	"Yeah, all right... Okay, here's a question for you. Do you know a lady, name of ",
	"Ha! Do I ever. Yes, I have the misfortune of her acquaintance. And if I may be so bold, what a fruitcake... ",
	"Yes, well, this fruitcake has hired me to kill you, friend.",
	"Oh she has, has she! Well, that's rich! ",
	"Yes, I know. Look, I don't know what's going on between you, but I'm afraid if there's a price on your head, I'm obliged to follow through. ",
	"Ho ho... Wait... you're not serious, are you? Captain? ",
	"Yeah... I'm afraid I am. Sorry.",
	"You dolt! What kind of a man are you?! You're no pirate! You're just some shrew's nightingale! ",
	"Careful... ",
	"Well, what do you expect? You march in here, you tell my you're going to kill me, and on what basis? Whatever. At least I won't have to hear from her again... ",
	"Yes, well. Might as well defend yourself. Go on, I'll wait.",
	"I've talked to you already. Get out, bastard! ",
	"Bastard, you say? All right, all right... ",
	"I'm glad to entertain you Captain. To what do I owe the pleasure?",
	"I've got a question for you. Do you know a lady called ",
	"Ha! Do I ever. Yes, I have the misfortune of her acquaintance. And if I may be so bold, what a fruitcake... ",
	"Yes, well, this fruitcake has hired me to kill you, friend.",
	"Ho ho! Come now, Captain. If you've no serious business here, I am a very busy man. ",
	"Yes, well. Farewell, then. But consider what I've told you.",
	"Yes, Captain. Of course.",
	"All the best.",
	"Captain, I don't wish to discuss this any further. It's quite ridiculous. ",
	"As you wish... ",
	"What the hell is going on?! Why did you attack my ship?! ",
	"At the request of a certain Lady ",
	". The name ring a bell?",
	"What the hell?! Oh, I don't believe this! ",
	"Believe it, friend. ",
	"All right, all right. But don't expect me to just curl up and die. Anyway, thank you for the chat. It has granted me some strength. But mind, it hasn't pleasantly disposed me toward you! ",
	"Well, I guess that's unavoidable. Okay, give me your best shot... ",
	"Happy to receive you. How may I be of service?",
	"I'm looking for a man named ",
	"Oh, yes. That man is my prisoner. I mean to exchange him for a kingly ransom.",
	"Yes, well. Could I have him?",
	"No, I'm afraid that's impossible. Now, if that is the sum of your business here, I will thank you to leave my ship.",
	"All right Captain. As you wish.",
	"We have already discussed my prisoner. Nothing has changed.",
	"Yes, I understand.",
	"Greetings. How may I help you? ",
	"I'm looking for a man named ",
	"Oh, yes. That man is my prisoner. I mean to exchange him for a kingly ransom.",
	"Yes, well. Could I have him?",
	"I'm afraid that's impossible.",
	"That's too bad... ",
	"The devil! What the hell?! ",
	"I need your prisoner called ",
	"Ha! Never! Over my dead body! ",
	"As ye please.",
	"Who are you?",
	"The name's Captain ",
	". No fear! I've come to return you to your loving wife.",
	"Good lord. Am I dreaming?",
	"Nope. All right, enough with the formalities. Let's go. ",
	"Welcome, noble visitor! What brings you here? ",
	"Just want to get acquainted. The name's Captain ",
	"Good to meet you, Captain. What can I do for you?",
	"Well, nothing in particular... You look like a military man. Still in service?",
	"No, already let go.",
	"I see. What was your specialty?",
	"I was a musketeer. Best shot in the regiment! ",
	"Oho! That's just the kind of man I need. Would you like to join my crew, as an officer?",
	"Thank you for the offer, but I must decline.",
	"Oh? Why? If you don't mind my asking, that is.",
	"Well, it's... a bit complicated. I've got a problem. I... well, I can't hold a weapon.",
	"That's strange. How did you fight in the army?",
	"It wasn't always a problem! You see, at one point I came to own a rare British musket. It had two barrels, and a sophisticated breach that allowed for rapid loading. Real work of art, by a real master.",
	"I got so used to that gun, that now I just can't use any other. ",
	"That's... interesting. So where is the musket now?",
	"It hurts to talk about. You see... When I was sailing here from the Old World, our ship was attacked by pirates. I wanted to fire on them, and had I done so I probably would have slain many - but my own crew jumped me, and tied me up! ",
	"Trust me, they did the right thing. At least you're alive.",
	"Alive, maybe! But without my musket! What life is it without glory! ",
	"Well, there must be other nice muskets in the world.",
	"Maybe. Hmm... Listen, if you somehow find my musket, I will follow you wherever you go. I swear it.",
	"Fair enough. Who was it that captured your ship, and when?",
	"It was a couple of years ago, and I've been in a hole since then... I didn't see who the pirates were - I was tied down, with a sack on my head. I heard the crew yelling about some kind of arrow, but I don't know what that means, if anything.",
	"Okay... So this isn't going to be so simple. Never mind, I'll keep my eye out. If I find your musket, I'll definitely return it to you.",
	"Thank you. I won't keep my hopes up, though.",
	"Cheery fellow, aren't you.",
	"Did you find my musket?",
	"Yes, here it is. One double musket, like no other. ",
	"Yeah, pal, I did. Here it is, a rare two-barreled musket.",
	"Not yet, but I'm working on it.",
	"Excellent! This is the start of a new life! ",
	"My word is my bond. I'm ready. But first, let's discuss my honorarium. For my loyal service, I expect in the neighborhood of ",
	" per month.",
	"A bit much, wouldn't you say?",
	"Very well. Agreed.",
	"No, I'm worth whole a lot more.",
	"Very well. Agreed.",
	"All right. But there's one more thing. I need a one-time advance, so to speak. I was out of work for a while, and would like to pay off my debts. I think that ",
	" should do it.",
	"Are you serious?",
	"Of course! Those are my terms. It's all up to you. ",
	"I don't have that kind of money.",
	"That's... a bit steep for me.",
	"Oh, all right. Deal. ",
	"Then come back when you're rich. Best of luck.",
	"Thank you... ",
	"That's different! My loyalty is yours! ",
	"Excellent. Welcome to my crew.",
	"So, how's the moneymaking? In case you forgot, I'm looking for a one-time fee of ",
	", in addition to my ",
	" a month.",
	"No, that's still ridiculous. ",
	"This is very expensive for me.",
	"Very well, I agree.",
	". It's close to Belize",
	". It's close to Cumana",
	"Your wanted Captain ",
	" came out of: ",
	" and headed for: ",
	"Albert",
	"Zivert",
	"Arrow",
	"The captain with the musket came out of ",
	" and headed for: ",
	"the brigantine 'Arrow'",
};
