string DLG_TEXT_Q [94] = {
	"Nothing to say.",
	"Okay...",
	"Hey, buddy! We need to have a talk with your friend, there. Step aside, and don't get in the way. You'll be healthier...",
	"Hm. I gather it would be better if you left the road. And protected your ears!",
	"Give over your weapons! And don't even think of resisting!",
	"Well, all right. Have it your way. And only because Curacao is friends with Tortuga...",
	"Feeding the ticks there? Tomorrow you'll get fed like a king - like one sentenced to the gallows. And it's being built already... hee, hee!",
	"I doubt you'll get anything from the windfall...",
	"Hello, Captain.",
	"Monsieur Stuyvesant... How is this possible?!",
	"Damned Ladron!",
	"Quiet, Spanish dog! I'll ask you a pair of questions. If you answer with the truth, you'll live.",
	"God! What's happened? Did you come from Bertran? What was that noise?",
	"My lady - I don't if this is sad news for you or not, but I was forced to kill your spouse. We have no time for worrying or wailing; we need to run at once! Governor-General Bertran d'Ojeron is waiting for you.",
	"Señor, who are you? And what do you want in my house?",
	"Señora, I've come here under orders from Dona Anna, your girlfriend. As far as I'm aware, you've warned her of a certain danger...",
	"Oh, do hurry up, Señor. I tell you, Anna's life is hanging by a thread!",
	"Everything will be in order, Lady Ines. Don't worry.",
	"Well, Captain? What news?",
	"Everything is in order. There are no more problems with the relatives of Dona Anna.",
	"Monsieur, we need rush on all sails to Cumana. God forbid that we get there late - the reales will be gone! You don't know our Captain...",
	"Hmm. Who doesn't know Francois Olone, the famed filibuster?",
	"That's something! Who dared to do this?!",
	"Well, let's continue our conversation. Who is the hero of our time?",
	"Continue? Who are you?",
	"Hm. Let's finish our chat. Who are you?",
	"I dared. My name is ",
	". I've come to get you out of here.",
	"Let's continue. They call me ",
	". I've come for you.",
	"I'm called ",
	"No doubt. Let's finish this. My name is ",
	"Now is not the time to talk. We've got to deal with everyone here!",
	"Who are you?",
	"I've come for you. d'Ojeron sent me...",
	"Captain, I haven't had the opportunity to thank you yet.",
	"Everything's in order, Captain Rock...",
	"Who are you?",
	"It doesn't matter who I am. John Morris sends his regards. He wants to take a look at your ship's log.",
	"You asked for it! Say goodbye to life..",
	"Eh, you're not looking after your ears....",
	"What? What?! What are you talking about?!",
	"I'm saying that you'll see my execution for free. Though you'd be a few zeroes richer, were Stuyvesant to search through the cabin on my ship.",
	"And why?",
	"So that he can see my papers, my log, and so on. Then he'd really understand that I'm the messenger of the Governor-General of Tortuga.",
	"Ahh, I see... I can arrange that. One of Stuyvesant's officer is my father-in-law.",
	"Well, come on. You won't regret it. Listen, do you know why I was picked up? I can't understand a thing...",
	"Pirates, you all are .... And just look like a privateer.",
	"Never said I wasn't. All right, listen. Let's not waste time here. You get to work before someone gets the smart idea to play jungle gym with my neck.",
	"Fine, I'll make sure Stuyvesant sees your log. You have my word. Pray they are convincing enough.",
	"My father in law wants to borrow a few coins. You don't mind, do you?",
	"Of course not! Don't waste your breath, my friend! ",
	"Don't fret, Captain. Everything is in order. ",
	"One of my officers took the initiative to check your cabin. There, he found a French privateer license. Then we read your log, and all became clear.",
	"You truly are a filibuster in aid to France. I shan't apologize, as I merely follow my orders. But you are free to go, Captain.",
	"Much obliged. Be embarrassing to be strung up for something I didn't do.",
	"All your possessions will be returned to you. Give my best regards to Bertran. And be careful on your way back - we have had odd reports from the island's vicinity.",
	"Odd how? ",
	"Nothing good, Captain. Nothing good... But never mind, it's of no consequence to you. Farewell.",
	"Farewell, Monsieur Governor-General.",
	"The very thought that I, ",
	", a Spanish privateer, would retreat before a Ladrone! I've already decorated this seabed twenty times over, so don't think for a moment you scare me. I'd rather face death than lose face! ",
	"And what a lovely face it is. Very well, I've already got what I need.",
	"José is dead... Lord knows I didn't want that. He found a letter that I wrote, and locked me in here... ",
	"Yes, Señora. So it would seem. Please follow me. Be careful, Miss... ",
	"Yes, Señor, that is so. Doña de Leiva is in mortal danger! Oregon y Gascon has dug deep, and now he knows all about Anna's flight to Tortuga.",
	"He then passed all he knew to Don José's grieving relatives. De Leiva belongs to an ancient Castilian family, and by their code of honor, Doña Anna must pay for her infidelity.",
	"They won't make it to Tortuga... ",
	"You are wrong, Señor. Don Jose's cousins have already arrived. I chanced to see them, and trust me, they are bard news. When a Castilian noble is out for revenge, the devil himself could not deter him! ",
	"Well, I don't deal in devils, so I suppose I'll have to make do. Where can I find them?",
	"Not here. They went into the jungle yesterday. Probably to talk some smugglers into freighting them to Tortuga.",
	"To the jungle, then! If they reach the city, I'll have to fight the whole Spanish garrison - which I would prefer to avoid. Thank you, dear Ines. I've never seen much of friendship in a woman before, but you... you're something else. Well, be seeing you.",
	"Phew, there's relief. Now Doña Anna will have a chance to calm herself... ",
	"I suppose.",
	"I'm merry and swell, my friend. My new friend. Who are you? ",
	"Monsieur d'Ogeron sent me. I'm guessing you know him... Okay, let's make haste. We're expected in Tortuga. Can you fight? ",
	"Oh, how lovely... ",
	"We'll settle later. First we must deal with everyone here... ",
	"No, unfortunately. Some man of God broke my hands... ",
	"That's not good... Then stay close to me. And be ready to run. ",
	"Alas, no... ",
	"We'll talk later. After we kill all these people. ",
	"Yes, whatever you say. My options here are few... ",
	"Then forward, man! And don't fall behind.",
	"Listen, I want to thank you for saving my life. I have no money to give you - what I did have is owed to the French treasury...",
	"But I can give you something that may more than money to a man in your position.",
	"How can I refuse an offer like that... ",
	"Then listen carefully... There is an underground chamber under the city of Fort de France, on Martinique. In that chamber is an object of great practical value... ",
	"It's... No, I shan't spoil the discovery. You will just have to see for yourself. In short, that is my gift to you.",
	"A queer gift, to say the least... But, gift horse teeth. Goodbye, Rock. Get well! ",
	"You're... too late... They've been... torturing me for... for a week... And... and now... nothing... will save me... Augh! ",
	"Oh dear.",
	"Oho! This bastard sends his lackies instead of facing me himself! Well, my hapless friends, I hope you get some satisfaction when he joins you in Hell! ",
	"You begin to bore me, Captain. Let's get down to business, shall we?",
};
