string DLG_TEXT_Q [210] = {
	"Nothing to say.",
	"Okay...",
	"I'm listening to you. What do you want?",
	"Monsieur, as far as I know, you're... Pierre Lagrange?",
	"I need to hurry up. I don't have the time...",
	"Monsieur, I've brought you to shore. My mission is done...",
	"And we're here already! I've decided that your money will come in handy for me.",
	"to Palm Shore",
	"oh... Palm Shore...",
	"... our galleon should be here already.",
	"oh... the galleon...",
	"And here we see our guest. Welcome to dinner, monsieur. The main course for you today will be good old Toledo steel!",
	"What a meeting! What's the matter?!",
	"You were send by Señor d'Ojeron, I presume?",
	"Yes, madam. How many I be of service?",
	"Tell me, Señor. What have you learned?",
	"Nothing yet. But I'm working on this case. Don't worry, madam...",
	"Tell me, Señor. What have you learned?",
	"Nothing yet. But I'm working on this case. Don't worry, madam...",
	"What do you need here?",
	"Tell me, Señor. Are you not the relatives of Dona Jose Ramirez de Leiva?",
	"Señor, this is the second time you've saved my life. Know that you've found a true friend in me.",
	"Hello again, captain. Happy to see you.",
	"And hello again, captain...",
	"How many hellos does it take, Captain? Hello again. ",
	"Señora! By a total coincidence, on the border of Havana we met two Castilian nobleman - and you should have heard how they spoke of you! It seems your memory is well-kept in Castille, Dona Anna.",
	"And I'm happy to see you as well.",
	"And I'm happy to see you as well. Again...",
	"Ah. Hello, Señora!",
	"Señor, this is the second time you've saved my life. Know that you've found a true friend in me.",
	"Hello again, captain. Happy to see you.",
	"And hello again, captain...",
	"How many hellos does it take, Captain? Hello again. ",
	"Señora! By a total coincidence, on the border of Havana we met two Castilian nobleman - and you should have heard how they spoke of you! It seems your memory is well-kept in Castille, Dona Anna.",
	"And I'm happy to see you as well.",
	"And I'm happy to see you as well. Again...",
	"Ah. Hello, Señora!",
	"Sir, do you need to be given a lesson in etiquette?! No one dares enter my house without an invitation!",
	"We've discussed everything already...",
	"Something else?",
	"The same again? How long can this go on?!",
	"I've got my invitation with me. Here it is - an express packet from Governor-General d'Ojeron.",
	"Yes, got it...",
	"No, everything's okay...",
	"Come on, don't fume...",
	"Did you find our reales?",
	"Yeah, everything's in order. Luckily, we made it in time. The money's with me.",
	"Did you find our reales?",
	"No, Francois...",
	"With whom do I have the honor?",
	"Ah, Captain ",
	". I'm here under orders from Governor-General d'Ojeron.",
	"Now, how successfully is the mission moving along?",
	"It's completed. None of the three will take part in war on the side of England.",
	"I didn't have a chance to meet everyone yet. I'm working on it.",
	"Ah, Baron! Happy to see you. More than that, I was waiting for you...",
	"I'm happy to see you as well, Marquis.",
	"That's it, Baron. I won't hold you any longer. Farewell...",
	"Farewell, Marquis...",
	"Yes, that's so.",
	"I'm called ",
	". I was sent to you by Governor-General d'Ojeron. I'm ordered to quietly and stealthily transport you to the shore of Le Maren.",
	"If the Governor-General trusts you, then so do I. When do we leave?",
	"As soon as possible. Wait for me on my ship.",
	"Yes, yes, you've undeniably completed the duties that you took upon yourself. Let me reward you in the proper way. A sum of 20,000 looks pretty dignified, I gather?",
	"Rather, yes...",
	"This money's yours, then. Please accept it.",
	"Goodbye, and good health, monsieur.",
	"Farewell, sir. I wish you a successful trip home, to France... Farewell!",
	"Oh, you villain! I'll tell the Governor-General what kind of scoundrel clawed into his trust!",
	"First stay alive, you lump!",
	"Hey, what do you need here? Why are you standing around? We didn't ask you out for a drink.",
	"I'm called Captain ",
	". I've just come from Tortuga. You want to join my team?",
	"No, we don't!",
	"Just think about it. I've got good conditions... Maybe we'll have a drink? Let me sit down here...",
	"Sit down and have a drink, but it's about time we headed out.",
	"Oh, okay...",
	"You again? And what are you doing here?",
	"I want to find something out. You said something about your galleon...",
	"You've got a shark's hearing...",
	"I'm waiting for an answer!",
	"And who are you, to demand an answer?",
	"I've already introduced myself, if my memory hasn't failed me. Or perhaps you don't know of Tortuga? Or are unfamiliar with filibusters?!",
	"We know what a filibuster is. We call you Ladrones.",
	"Only the Spanish call us that way...",
	"That's right... Amigo, Saint Antonio has allowed us to receive a Ladron captain - and by grace, he's alone. We won't lose time...",
	"Hot damn, Spaniards! But what's your galleon? You didn't answer!",
	"We're waiting for our galleon here. It's going to drop anchor any minute. Now you know everything, not that you'll need this knowledge...",
	"Well, that's your opinion. I think it's time to see the color of Castilian blood...",
	"Now, how would you like it... Bursting into a stranger's house in the middle of the night, and then asking What's the matter?!",
	"Don't make an idiot of yourself! My wife is locked up! I found that damn d'Ojeron's ring in her possessions.",
	"Everything is clear... Well, then. I'll apply all of my strength to treat you to the meal that you've treated me to today.",
	"Begin the meal!",
	"Let's begin...",
	"I received a letter from my girlfriend in Havana, Ines de las Sierras. The governor-general of Havana has begun an investigation into the death of my husband, and is convinced that I'm to blame. Oh, it's so! But my countrymen has planned revenge. I'm in danger of kidnapping or death, and I don't know which is more frightening.",
	"Sir, I'll ask you to go to Havana and find out how serious this is.",
	"Madam, you can count on me.",
	"Ines",
	"de Las Sierras",
	"What business is it of yours?",
	"If it were none, I wouldn't be asking. You can believe that...",
	"Possibly. And what do you need from us?",
	"As I understand it, you plan to get revenge for Don Jose?",
	"Identify yourself immediately, else I'll cut your long tongue out.",
	"I am the man who sent the honorable Don José to Hell. And his servants after him.",
	"Ho! Today, fortune smiles on us! We're halfway done, brother. All that's left is to find that rogue Anna, and then we may go home.",
	"Hey, what about me?",
	"You're already history... Come, brother, let's finish this fool! ",
	"Oh come, you flatter me. Maybe someday, friends. Anyway, en garde... ",
	"I could do without this kind of attention.",
	"Trust me, there's no must fear. I managed to change the minds of these brave Castilians... ",
	"Oh, Señor ",
	"! However might I thank you?",
	"Doña Anna, I'd like you to look after Monsieur d'Ogeron. He deserves it.",
	"As you wish! Dear Bertran's spirit is no longer your burden.",
	"Madam, you have done a favor not just to me, but to filibusters everywhere. You can call us even. ",
	"Aha! That changes things. Make yourself comfortable while I read the letter.",
	"By the way, Monsieur, I feel I should tell you the Spaniards expressed great interest in this letter. They even sent a warship to intercept my vessel.",
	"Ha-ho! I suppose since you are here, the Spanish will be waiting for their warship for quite some time! Yes, they dream of proving an allegiance between us filibusters and the French Governor-General. Thus by safely delivering this letter, you have done Monsieur d'Ogeron and me a big favor. And big favors curry big rewards! What form would you like?",
	"Pardon?",
	"I could give you a pouch of gold. Or I could cut you in on an interesting development. In this letter, the Governor-General informs me that there's at least two hundred thousand reals of gold at Fort Cumana. There are three ships in my fleet, each captain a personal companion of mine. Join us, and we shall divide the plunder four ways, according to the Brotherhood's charter. What do you say to that?",
	"Thanks for the interest, but money in the hand... ",
	"Bloody yet profitable. What corsair could refuse? I'm with you, of course! ",
	"As you wish. Here is your reward.",
	"Thank you, Francois. Now I will probably head for Tortuga... ",
	"Very well. I trust you are ready to take your place in our squadron? Welcome - and to Cumana! ",
	"Swell! So, Francois, what's our course of action here?",
	"Well, where you have been all this time?",
	"Getting rid of ships, as you asked me to.",
	"My colleague... I can include you in this offer, but your share may be no more than a quarter. I need no other companions, so if you care to participate, get rid of the extra ships. And quickly! ",
	"All right, Francois, I'll be back soon.",
	"No, that split doesn't work for me. I'd rather just take my money and run... ",
	"The plan is simple as they come. We go and take Cumana by storm. Then we find the gold, split it, and go our separate ways.",
	"Splendid. I'm ready.",
	"Then to Cumana! On the double! ",
	"Very well. Let's begin... ",
	"Did you get rid of them?",
	"Yes, of course.",
	"I congratulate you, but there will be no attack on Cumana.",
	"How's that?! ",
	"Very simple, mon cher. There is no gold there; it has been moved elsewhere. The time you wasted has cost us two hundred thousand reals. ",
	"Hot damn, that's a disappointment. Oh well, I'll just take the delivery money then.",
	"Time is of the essence, Captain. We must take Cumana soon, while the gold is still there.",
	"Yes, Francois, don't worry. We'll make it in time. Trust me. ",
	"Why does that not reassure me, ",
	"We are too late, Francois. The money left for the Old World about a week ago. All our effort is for naught... ",
	"I think not, mon cher. I think that we are late because of you! ",
	"That's debatable... ",
	"But we shall not. Tongues are too blunt to resolve such a disagreement. En guard, Sir! Let's see what your blood tastes like... ",
	"I thought tongues were... I mean, I don't want to fight you! God... ",
	"Then I'll kill you like a dog! Arm yourself; this is your last chance.",
	"All right, Francois, if that is your real name... Remember, you asked for it.",
	"Excellent, my brother! Let's split the takings, and go on home.",
	"Farewell! Sorry to leave you all Olone, but I still have some business here... ",
	"Split, nothing. I'm the one who pulled this operation! ",
	"If you found the money, then where is it? You wouldn't be toying with us, would you? ",
	"Why, Francois! The very thought... ",
	"Do your thing, but don't stay too long - those Iberian rats may be not far.",
	"Sure thing, Francois. Be well... ",
	"You think you're smart, don't you. Well, we'll see whose wit is sharper. Have at you! ",
	"No, if you ask me, that wasn't too clever... ",
	"Rats like you deserve to be punished! ",
	"Oh, are we changing the subject? Fine.",
	"Oh, so that's how it is? Then prepare for the worst... ",
	"A pirate's always prepared, Francois... ",
	"Aha! finally! I was starting to worry. D'Ogeron had his share of praise for you; let's hope he was right. Anyway, listen here. The words you hear today, they don't leave these walls. They're for your ears only. Got that? ",
	"Yes, I know the drill. ",
	"Magnificent! To business, then.",
	"The current political situation in Europe is very complicated. Another trade war is brewing between England and Holland, and our great Sun-king Louis XIV is starting a devolutionary war with Spain.",
	"Excuse me, Marquis. What's this war about?",
	"Hmm.... Yeah, how would a simple privateer know better.",
	"It's a matter of national pride, about control of historical territory. France claims sovereignty over parts of Flanders and Burgundy, currently under Spanish control. The Dutch have been trying to oust the Iberian devils in priests' clothing for over a century.",
	"We desperately need Dutch funding to conduct our war, so it is imperative to prevent a British attack on their colonies. This task is directly overseen by Jean-Batiste Colbert. I hope you know who he is... ",
	"All right, so how would a man go about this? ",
	"The Dutch are quite capable of defending themselves - that is, unless Thomas Modyford, the governor-general of Jamaica, were to receive reinforcements. If push comes to shove, all they've got to turn to is certain figures of authority in the Brotherhood of the Coast.",
	"There are only three men who could influence the conflict - Henry Morgan of Jamaica, Jackmann of Bermuda, and John Morris of Trinidad. Your mission would be to meet each in turn, convince them to stay out of the conflict. Money is no concern for you, as it will be of the utmost concern to them.",
	"And where would I get this money?",
	"I have to admit you surprise me. I was led to understand you were a man of a rare intellect and resourcefulness! Had I such a sum to distribute, why would I need your help? Of course, you're free to refuse, but... ",
	"But?",
	"Then I would be forced to place you behind bars. You, my dear sir, are now the intellectual bearer of a state secret! I can't allow loose cannons to wander around so armed. ",
	"First you'd have to arrest me... and good luck to you! ",
	"Well, if the king's so hard up he needs a loan, far be it for me to deny him.",
	"Excellent! I see d'Ogeron was right about you. I hope you'll bring me good news.",
	"Count on me, Marquis.",
	"John",
	"Morris",
	"I must admit, this was one of the most complicated affairs I have entrusted to a single man. Surely such a hand for diplomacy is wasted without a title to precede it. Fortunately, I have been vested the authority to grant you the title of Baron! France needs men such as you! ",
	"Oh, really. Baron, you say? Well, what about the expenses I incurred?",
	"Once a pirate, always a pirate! Har har! ",
	"My dear sir, I have given you more than mere metal! I have given you honor and audience with the King himself! Well, I shall delay you no longer. D'Ogeron is expecting you. I believe he has another vital mission for you. Farewell! ",
	"Farewell, Commissary Bonrepaux... ",
	"Baron ",
	"As you know, the war with Spain is ended. Spain has been brought to its knees! ",
	"Yes, Marquis. Fine news.",
	"Your efforts were invaluable - even Louis himself knows your name... ",
	"Frankly, Marquis, I'd prefer a different show of appreciation. ",
	"Such as?",
	"All that sparkles. I'm not sure if you realize the financial burden I've been put under in the name of your country. I'd like to make some of it back, if you don't mind. ",
	"My friend, you have become nobleman! The entire Louvre knows your name! Is that not enough?! ",
	"Oh, it makes me plenty proud. But it doesn't buy me anything. ",
	"Baron, don't for one moment think me a fool - I don't expect you to report the plunder you captured along the way. That's all the compensation you need.",
	"Hmm... So that's how it is.",
	"So, now that everything is cleared up, we shall reclaim the 'Soleil Royal' from your squadron.",
	"You're welcome to it. ",
	"In a month I will send this magnificent ship to the Old World. I am grateful that you have kept it in a such good order.",
	"That's what I do, Marquis... ",
	"Well, thank you again, Baron. I shan't delay you longer. Goodbye.",
	"All the best, Marquis.",
	"I hear you are a marquis now! You are a man of fortune, Captain... ",
};
