string DLG_TEXT_Q [28] = {
	"Greetings, brother!",
	"What kind of brother am I to you? You're clearly an Indian half-blood. And what's with the rags?",
	"Me, mistaken? You white man, I white. My name even White Boy. My clothes are remember my ancestors. Me wearing when can, long time ago.",
	"Oh. Uh, yeah. Definitely not a girl, though you're just a few years over a boy. No mind, of course... Why spend your life in rags?",
	"Me no understand. I son of main shaman and white captain, big ship! I wear this, so evil soul no see and take me to them.",
	"So, another blessed one. Okay, I got it. Are you selling pearls?",
	"Me buy pearl.",
	"Buy or sell? You got them?",
	"No, not now. Need.",
	"You've got me confused, blessed one. Farewell.",
	"White brother returns. Something say?",
	"No, I've got nothing to talk about.",
	"What do you know about the ghost ship?",
	"Hey, kid. I brought you your pearls.",
	"Big ship? Sailed long, long way, before was common, then was ghost with black sail?",
	"When and how did it appear?",
	"Was mistake. Maybe visited by evil captain's ghost? They here forty winters ago, lived and traded in peace. Then captain offended tribe big-time. Took my mother by force, robbed us, stole sacred pearls. ",
	"Hmm... Yes, typical. So what about the ship?",
	"I already explain! You no listen? Chief wanted captain's life to make peace. Sailors took captain's side, and ship sailed far, far away. Then our shaman cursed captain and ship.",
	"Curse, you say. Aren't those normally bad things? What's with the power and immortality?",
	"They suffer big time. So long as sacred pearls protect them, they suffer until all is put right. From birth, I seek our pearls. Trade for white. They sell, I find.",
	"You know... I think this curse causes more suffering for others than for the pirates. You should have just cut their throats and been done with it. How do I kill the bastards?",
	"Not long now. They spend almost all. I collect them, I count. Just six-six-six more black pearls. Then curse over. Joke on them! ",
	"Okay, then. Don't go anywhere! ",
	"Very good! You save us! Give them, real quick. Now you meet ship again, and break it. Or take it. They done now. Now they just pirates.",
	"Sure, you're welcome to them.",
	"Thank you, friend.",
	"Yeah, I hope it's all like you said... We'll see! ",
};
