string DLG_TEXT_Q [114] = {
	"Nothing to say.",
	"Okay...",
	"Get lost, while you're still whole...",
	"My name is ",
	". I'm looking for Aaron Mendes Chumaceiro.",
	"I think you saved my skin! What are you doing here?",
	"My name is ",
	". I'm looking for Aaron Mendes Chumaceiro.",
	"I'm grateful for the successful journey. And I'm twice as grateful that we've arrived in San Martin on time. I hope we'll meet again.",
	"With pleasure.",
	"Hm. I don't believe I've seen you before. Who are you?",
	"I'm come to free you!",
	"Oh, you've come at a sad time. Mansfield's dead.",
	"What do you mean, dead?!",
	"Tell us, are you none other than the messenger of the governor-general of Curacao?",
	"And what did you want?",
	"Ah, here you are! I was tired of waiting...",
	"You wanted to see me? Who are you?",
	"Damn it! I didn't think it'd see you again - and so quickly!",
	"Hello, Antonio. Let's continue our amusing talk. Only now, everything will be by my rules.",
	"Happy to see you, my friend. What brings you here?",
	"Mynheer, I've been sent into your service by Peter Stuyvesant.",
	"I can't wait for your search report.",
	"I'm working on it. The results will be in...",
	"I can't wait for your search report.",
	"Mynheer, I was able to discover who was selling the sought-after Christian book. The filibuster is called Loran de Graf. Or, rather, was called - as he has died. When I reached him on the shores of Cartagena, he was in battle with a mighty Spanish squadron. I was unable to save his frigate. Loran himself sank with his ship. I'm afraid that's all. The book will be impossible to find.",
	"I can't wait for your search report.",
	"Mynheer, I was able to discover who was selling the sought-after Christian book. The filibuster is called Loran de Graf. Or, rather, was called - as he has died. When I reached him on the shores of Cartagena, he was in battle with a mighty Spanish squadron. I was unable to help de Graf. The forces were too unequal. I had to leave the battlefield.",
	"I've got nothing more to say to you. Go to Stuyvesant.",
	"Fine, mynheer.",
	"I can't wait for your search report.",
	"I was unable to find a thing. I am forced to end the search.",
	"I've been looking everywhere, I've been fighting, sinking Spaniards... I haven't found the book yet... Though I do press on. ",
	"I can't wait for your search report.",
	"I was unable to find a thing. I am forced to end the search.",
	"I was able to find a book of some sort. I don't know if this is what you're looking for, but there's definitely a cross on the cover.",
	"I have been unable to find the book, but I'm still searching. You'll have to wait...",
	"I pray for you, as does the whole society...",
	"Heh. Thanks...",
	"I told you - take off, or I'll gut you.",
	"Well, I'm kind off against such a method. I value my guts very much. But I think it's time to take a look at your guts, I suppose...",
	"It's me.",
	"Peter Stuyvesant sent me for you. I must transport you to Curacao. And what were those uncivil people doing in your house?",
	"It looks like they were robbing me. The thing is, I've been waiting for a person from Peter for three days now, and when they knocked on the door I didn't even ask who it was before opening it. In one minute, I was twisted and thrown into this room, and the robbers began rummaging through my things.",
	"Well, all's well that ends well. Get ready and aboard my sailer. Stuyvesant's waiting for you. We leave immediately.",
	"I'll ask you to accept a small reward from me, of 30,000 coins.",
	"I won't decline. Thank you.",
	"Oh wow, that's awesome! To what do I owe such attention to my person, and such care about my fate?",
	"I need to find something out from you.",
	"I'm at your service. But first, let's pick a more peaceful place for such an intriguing talk.",
	"I promise that I'll set you free. But first I need some information. I need to know where Maddyford is planning his assault detachment.",
	"The Dutch Fort Orange will be taken and destroyed.",
	"Dammit, everything pointed to this! Well, I'm a man of my word. You're free to go, and can go where you like. Farewell.",
	"That Spanish attacked us. A good half of the people went down.",
	"That's something! A pity, Edward. A great old man he was.",
	"There's a trusted official of Stuyvesant's waiting for you at the tavern.",
	"And what does the official want from me?",
	"An urgent order from the Governor-General. Familiarize yourself with it.",
	"Hmm... Very well.",
	"Antonio",
	"da Barra",
	"Isabella",
	"My name is Antonio, but that's of no importance. For now, ",
	"Wow! Just look who's here! ",
	"Ah?",
	"And what would the etiquette be, here?",
	"You will answer my questions, and for every wrong answer I shall cut off a finger. Ten wrong answers, no more fingers. Do you understand?",
	"Aha. Well, at the moment you could say that my extremities are quite attached to me. So don't be shy; I'll tell you whatever you like.",
	"Then your first question is, who are you and what are you doing on Tortuga?",
	"Technically, you know, that's two questions. But I am Antonio da Barra, an agent of Spain. I wasn't interested in you particularly, you know. I was asked to watch for Stuyvesant's messenger. I know a Dutch ship when I see one, so when you went straight to d'Ogeron, I knew I was onto something.",
	"All right... My second question, then: where is the dispatch?",
	"Oh, this? I have it. Here, take it. It's a boring read anyway.",
	"Splendid. Clearly you are a man who knows when to fold his hand... All right, that's enough. We can continue this when we get to Willemstad. I do hope, Señor Antonio, you will do me the honor of visiting our great city?",
	"In this case, I am afraid my own wishes are of no consequence... ",
	"No, I'm sure that is true. ",
	"It is grand that you will help me in my search. I have seen you in action.",
	"What searching do you mean? Stuyvesant was not very specific... ",
	"Ah, I imagine not... Best, then, we start from the beginning.",
	"The first Jansenist to arrive in Curacao, about twenty years back, was a certain Samuel Coheno. He was a very wealthy man, and at one point, by pushing a tremendous sum through the right series of hands, managed to buy an profoundly mysterious document from the Seville office of the Inquisition itself. That document was the Gospel.",
	"I assume you've read the Bible? ",
	"Not for fun, but yes.",
	"You are aware, I assume, that the passages in current circulation are not the... originals, so to speak?",
	"You've lost me.",
	"You see, the Bible was written over an extended period, and not as a single work. Years passed before the church grew sufficiently established to think about compiling and ordering the Christian texts - building an authoritative record of their beliefs. ",
	"The time came for a detailed account of the Church's library holdings. When all the texts were collected and studied, they were found to be riddled with contradictions - some irresolvable. So a council was called, to choose which passages to accept into the canon, and which to set aside.",
	"That's all fascinating of course, but what does it have to do with my mission?",
	"Patience, my friend. As I say, it's a long story.",
	"Whatever failed to make the cut was deemed heresy, and either destroyed or hidden so deep that it would never again see the light of day. And yet, Coheno pulled it off! With his impossible wealth, he actually bribed the Jesuit registrar, and thereby stole a previously unknown version of the Gospel from the Inquisition's archive! ",
	"Though Coheno immediately fled the Old World, misfortune was quick at his heels. In the end, this man of nobility and measureless wealth was brought to a measure of nothing. He was sold to slavery, and perished on a sugar plantation not far from here, in the British settlements.",
	"So I am to find the place of his death?",
	"No, that would be meaningless. You must find the missing tract.",
	"I can't even imagine where to start... ",
	"We do have something, that led me to beg Stuyvesant for your use.",
	"I'm all ears, Aaron.",
	"I've heard rumors that a British corsair, from a pirate settlement on Bermuda, aimed to sell an ancient Christian text, written in a language unknown to him.",
	"Hmm... How'd he know it was Christian, if he couldn't read it?",
	"The faith does have its icons, my friend... ",
	"Oh, right. Okay, so who is this man? ",
	"I don't know.",
	"Ah. Well. I've had harder jobs before. I imagine I can track him down. Find him, find the book. Presumably.",
	"I'm certain you can, my friend. If you succeed, you will be generously rewarded. ",
	"That certainly doesn't hurt my motivation. I'll get right on it, then. 'Til next time, Aaron.",
	"This is very, very bad... Well, I will have no more need of you. You may return to Stuyvesant.",
	"Fine, Mynheer.",
	"Let's see, then... Yes, this is it! This is it exactly! By God, you have found the lost treasure of Samuel Coheno! ",
	"Now, for days to come, and to the end of time, amen.",
	", I promised you a hefty reward. So how would you price your efforts?",
	"Well, I spent two hundred thirty-five thousand on the book, so anything above that is profit.",
	"Then I'll give you a million on top of that, and the endless respect of our community, 'til the end of days - which, incidentally, is not far off... ",
	"Ha... hwah! Yes, that's... acceptable. What was that about the end of days?",
	"The mortality of man is its own great tragedy. Soon, however, all will return to normal, to where it all began... ",
	"Are you... yes, you're serious. Well, aren't you a party and a half. Never mind. You go ahead with your waiting. I've got a lot of living to get done before I face my tragedy. And now, I have the method. Oh yes... The catharsis of unchecked hedonism. It is good to be a pirate.",
	"Farewell, and let the Lord keep you safe! ",
	"And all the best to you too. Farewell.",
};
