string DLG_TEXT_Q [34] = {
	"Nothing to say.",
	"Okay...",
	"You've won! I surrender...",
	"I want to know where that damn Antonio is! Answer me!",
	"Sir, now is not the time for questions! There's a battle going on.",
	"Yes, yes, I know...",
	"I'm certainly grateful for the help, sir. You made it just in the nick of time. Allow me to introduce myself. My name is Loran de Graf.",
	"I know, I was first looking to meet you on Bermuda, then at Tortuga.",
	"I think our deal is finished, sir.",
	"Correct. It's finished.",
	"Have you found the money, sir?",
	"Yes, I have. I'm ready to hand it over...",
	"Not yet. I'm still searching...",
	"Antonio de Barras? I transferred on the way here to a Spanish war galleon.",
	"Damn! What was the name of that galleon, and where was it going?",
	"The galleon Isabella, went bearing on Main to Santa Catalin. Antonio told me that he absolutely and immediately needs to go there.",
	"Ah, damn! Listen, you're a pirate! What the devil are you schmoozing with the Spanish for?!",
	"Here now! None of your shenanigans... ",
	"Hey, guys. Right on time! Let's tip this fop. I'm sick of the sight of him.",
	"Argh... ",
	"What can I do for you?",
	"Hm? Oh, the name's ",
	". You offered to sell a book to Jackmann. I'd like to buy it from you.",
	"Oh, really? That could be arranged. Since I couldn't sell the book, and I've hidden it in a safe place. Here is my offer - you pay me two hundred thirty-five thousand, and I hand you a map, disclosing the book's location.",
	"Two hun... er... Isn't that a bit much?",
	"Ultimately, no. The book is not all I have stored in this cache, so the price covers the value of all the articles at that location.",
	"Well... okay. I wasn't in the market for a box set, but here you go.",
	"I don't have that kind of money on me. I'll have to come back later.",
	"And here is the map. Listen, it's not that I'm ungrateful for the chance to unload this article, as it is of no practical use to me, I must ask why you place such value in it... ",
	"I'm acting on request of the Dutch authorities. That's all I can tell you, I'm afraid.",
	"Oh, I see. Well, then this is a fine deal for both of us.",
	"That's right. I'm grateful to you, Lorraine de Graf. I hope we'll meet again. ",
	"Splendid! You will find me in the tavern on Tortuga.",
	"Great. I'll be sure to swing by there soon. Look out for me.",
};
