string DLG_TEXT_Q [69] = {
	"I should like you to leave my house. I'm busy, and I don't have time to talk with you.",
	"I'm already gone.",
	"John, I hear we've got pearl divers working our waters. You know anything about that? ",
	"! Happy to see you! Why have you dropped by, this time?",
	" Who's that I see?! Why, it's my friend, ",
	". What fate brings you to this island?",
	"Now, now. ",
	" is my guest. I'd like to see your dagger work again... So what do you have to ask me, my friend?",
	"I just stopped by to see you.",
	"Small stuff. Nothing vital.",
	"John, I hear we've got pearl divers working our waters. You know anything about that? ",
	"No, it's news to me. That's for Sharpe, buddy. Can't quite move my tongue to call him Captain...",
	"You know where I might find him, then?",
	"No idea. I've got no interest in oysters. Still, if I was in your place, I'd look for him in the brothels. Sooner or later, he'll turn up there...",
	"Got it, John. Thank you.",
	"I'll ask you to leave my house. I'm busy, and I don't have time to talk with you.",
	"I'm already gone.",
	"Say, what have you come for?",
	"I've come under orders from Governor-General Thomas Maddyford, of Jamaica.",
	"I'm already interested! Maddyford ain't too fond of me. What's made him send me a pirate?",
	"Maddyford's assembling a squadron to attack Curacao.",
	"Without me.",
	"Why?",
	"The Governor-General and me, we ain't exactly the closest of friends. So you can see how this invitation inspires some serious misgivings in me. Something's not right here.",
	"It's possible that Maddyford's traded his rage for kindness.",
	"You don't know Maddyford. No, I'm not so dumb. Something's not right here. It's possible that there's a bloodbath in store, and I kind of don't want to wash myself in blood for the governor-general of Jamaica. So do without me, corsair. But good luck, anyway!",
	"Thank you. And good luck to you too, friend.",
	"Aha! And you're back again. What do you say now?",
	"I'm in action with Morgan. Are you ready to storm Belize?",
	"I'm ready to join immediately.",
	"Then, onward!",
	"I see you already got four ships. If I tag along too, I'll get underfoot. Do without me, this time.",
	"Well, you know. Be healthy.",
	"We must hurry. Time waits for no man.",
	"We'll manage.",
	"Blue blazes of damnation, my galleon went under! I lost my ship, and a quarter of my crew. Pity. They were good men...",
	" Eh, life goes on, one way or the other. At least, for those who survive. And for us, the Cumana gold will be our reward. We found the gold in this room, under the floorboards. You are a true corsair!",
	"Damn, that didn't take long! We found the gold in this room, under the floorboards. You are a true corsair!",
	"Thank you. I'm glad to hear that from you.",
	"I'm going home, to Trinidad. You can always find me there.",
	"Good luck, John. We will meet again! ",
	"Who are you, and what do you need?",
	"I'm Captain ",
	". I need a small favor. You'll probably receive messengers from Governor-General Modyford...",
	"What messengers? Talk straight, man! Don't beat about the bush! ",
	"Okay, John. Here's the thing - Modyford is preparing to attack the Dutch, and wants the Brotherhood of the Coast involved. ",
	"All right. So?",
	"It's important to me that you don't take part in this recklessness.",
	"Ha! I don't like the idea of attacking the Dutch, so I'll accept your proposal. But you must do something for me.",
	"What is it?",
	"I don't know if you've heard this story before, but here's the gist. This merry fellow, Captain Gay, got it in his head to take a merry jaunt across the sea, not much mind to friend or foe. He plundered a couple of British merchants, then when things got hot... well, blamed it all on me. I was also at sea around then, and Modyford has been itching to get ahold of me. So what I'm sayin' is, right now I'm shut out of Port Royal.",
	"All right. So what do you propose?",
	"See, one way or t'other, all this commotion works for me. If Modyford asks me a favor, then I'm Scot free. Or if you dig up some papers that show I had nothing to do with this commotion - well, that ain't bad neither! The second is, of course, far tidier, as I would prefer not to spoil my relationship with the Dutch.",
	"Well, tit for tat. I'll see what I can do. So what kind of a document are we talking about?",
	"I mean Gay's ship's log. You'll have to go over there and rummage around.",
	"Oh, that makes sense. All right, I get you. While I'm working on that, you just sit tight, okay? ",
	"Best hurry...",
	"Of course!",
	"Captain ",
	"Gay",
	"So how goes it, Captain? How's our merry friend's penmanship? ",
	"I've got good news, and good news. Gay is on a fast boat to Hell... and his journal... well, see for yourself.",
	"Still working on it. I'll let you know soon.",
	"Well, well... Oh dear... Yes, I figured on purple prose from that peacock... Still, I'm sure it'll entertain Modyford plenty. I'll send one of my men right over to him. And you can reassure the Dutch that I won't so much as stroke them roughly. ",
	"That's just swell, Morris. Well, that's all the business I've got here. Farewell...",
	"What are you doing on my deck? Aren't we going to Puerto Bello?",
	"Yes, apparently... ",
	"Believe me, we'd best not waste time.",
	"Yes, I know.",
};
