string DLG_TEXT_Q [74] = {
	"You've managed my servants. That's good. And now tell me, what year is it?",
	"... Christing infernos, what's happening?!",
	"Now everything is in order. Are you ready to fulfill your destiny?",
	"What have you done?! Listen, Leif Frickin' Ericson, the world's changed a whole lot since your day. There are a whole lot of white people around here, now.",
	"Now you're ready. I'm allowing you to leave the crypt.",
	"And what will happen to my body?",
	"Do your job, privateer.",
	"Fine, Leif.",
	"Ahh! And here you are, at last! Where are the objects for which I sent you?",
	"I have them. Take them, already. And give me back my body!",
	"I don't have them. I didn't find them...",
	"I'm freeing you now. You may go. The exit is open.",
	"Thank you. I hope we don't meet again.",
	"Farewell, privateer...",
	"Farewell, Leif.",
	"Now, the following is happening: we are talking. ",
	"And a great event has already happened, which I have awaited for six hundred years - I've have risen from my sleep.",
	"(Hot damn!) And it looks like I woke you...",
	"What are you called, and who are you? Answer, and you will live.",
	"My name is ",
	". I'm a privateer.",
	"Isn't that a bit too high-brow for a peeled skull?",
	"Privateer? Explain.",
	"A privateer is a corsair. A filibuster. A, well... A pirate.",
	"Filibuster? Pirate?",
	"Well, how can I explain it... I'm a free seaman, and a free warrior. I have my own ship, and do what I consider to be needed.",
	"Oho! So you and I are blood brothers! I'm happy that my plan was brought into being by a fellow soul. This is sign of great luck for me...",
	"What plan?",
	"What plan? Hwa-ha-ha... You're talking to a person who died more than six hundred years ago! ",
	"That's what my plan is about. It means the message to my descendants has been found...",
	"Wait, what... Who are you?",
	"My name is Leif Ericson. I, like you, am a seaman and warrior. I am my own boss. ",
	"Only the I wandered was somewhat north of here.",
	"When I was coming here, I heard that Leif the Lucky was buried here. That's you, I take it? ",
	"Yes. I'm Leif the Lucky. Son of Erik the Red. Ancestor of the ancient Cimbrians, vikings, and Jorsalirsfari.",
	"So you're a viking, from a nation of barbarians that raided Europe six hundred years ago?",
	"The vikings aren't a nation, corsair. Viking is a way of life - the profession of a seaman and a warrior. ",
	"And you, libertine warrior - you call us barbarians? Six hundred years hither, we were the greatest warriors and seamen on the face of this earth. I've been to Iorsalir and marched on Rome, and my brother - why, he ruled Gardariki! ",
	"That's great, but how did you get here? Columbus only discovered America a hundred fifty years ago.",
	"Ho ho ho! Is that what you call all this land? America? Listen to me, wanton corsair...",
	"In your year 986, the viking Biarni Heriolfsson was on a routine voyage to Greenland, when he was blown off course. Off his bow, he saw a land of trees - a new and unexplored haven. But winter approached, so he changed course and never set foot on its soil.",
	"Fourteen years thence, I set off to find this land - and find it I did! I discovered the nobbly plains of Helluland, the forests of Markland, and finally the wealth of Vinland. It is there, amidst the rolling hills, that I founded my settlement.",
	"Some years later, I traveled on to warmer and warmer climes, and ultimately to this endless domain. I docked much farther to the north.",
	"Six hundred years ago? No, that can't be right...",
	"By your reckoning, it was in 1002 A.D. that I claimed this land.",
	"I penetrated deeply, and found a land of no borders, inhabited by the red skrælings...",
	"Scray... what? You mean the Indians?",
	"No, I never encountered that tribe. ",
	"But I lived twenty years with the Toltecs, who worshiped me as a god. When I had my fill, I returned to my settlement in Vinland and there left a will to my progeny.",
	"Six hundred years later, it was carried out. By you.",
	"Great! Is that all, then?",
	"Don't rush me. First, I shall make you a worthy present that will help set you free.",
	"Nothing like a practical gift, I always say. But what do you mean, exactly?",
	"Your life. As a show of gratitude to you, I grant you your life.",
	"Oh... yes, that's nice to have. Well... Thanks for the lovely conversation and all...",
	"I said, don't rush. In return for this gift, I would like some favors of you.",
	"Aha. What do you have in mind?",
	"Hell no, you rotten ape! I've had just about enough of this! It's time to taste steel... ",
	"I feel that a big city is nearby. The most important man in the city has the items that I need. I feel his presence.",
	"You must bring me three crystal Toltec skulls, of white, pink, and blue. Also, an ancient object... you will know it as a strange thing. Then I will regain my power, and may become bodily once more. The world awaits its master... ",
	"(Yeah, right...) That's lovely. Can I go now?",
	"Go. Before you go, however, I take one more liberty of you - as insurance, you understand.",
	"For the moment, I shall your body and you shall take mine. I am sure this will put speed in your sails.",
	"Wait... what? ",
	"Yeah? Whatever...",
	"Look, this isn't helping. The city there - it's not Toltec, you know. It's not Aztec. It's French! Do you know anything about modern civilization? I can't go around looking like this!",
	"And you need not. All you need do is capture the city. To that end, I lend you my servants - number enough to give you your way.",
	"And no need to worry about your own body. I find it quite unsavory, to be honest. It will be here when you return.",
	"Now you may go. ",
	"Fine, I'll do as you say. But be careful with me!",
	"Until you found what I ask, your body remains in my care.",
	"Okay, okay... I'll get looking.",
	"This is in your own interest. I shall make you no other present of value.",
	"I see. Well... Take care. If that, er, means anything in your case.",
};
