string DLG_TEXT_Q [243] = {
	"I've nothing to say to you.",
	"Alright...",
	"You'd better not walk around Des Moines with unsheathed weapon.",
	"Um. Sure, okay.",
	"Alright.",
	"Whatever you say.",
	"Hey, sailor, wanna take part? You'd come in useful!",
	"I might take part, if you tell me what it's all about.",
	"Er, well, there's a werewolf in the tavern. So-o-o, we were thinking - hic! - of giving him a good fry-up, ha-ha-ha!",
	"You're drunk as a fish, buddy! Go and get some sleep!",
	"I'll be damned, if I'm lying - I saw it! I just took a couple of drinks to get brave! You don't meet a werewolf everyday, you know.",
	"A werewolf, you say? So why are you all standing here? Get him fried up now!",
	"The tavern keeper locked the door, damn him! So the fellows went to get a big good log to - hic! - break the door!",
	"Hey, you, busted bastards, will destroy half of the city! Let me in, I'll want to see your werewolf myself. Anybody follow me and you'll be dead!",
	"Who are you, and what do you need?",
	"I'm Captain ",
	". And who are you? You see, there're some fellows outside going to pay you a visit and they aren't coming with Christmas present, you know.",
	"They are going to burn me! But God is my witness, I'm innocent! I fled from Maracaibo to avoid a terrible curse which was cast upon all the people of our city. Captain! You must help me. I need to confess.",
	"Wrong number, my friend. I'm not a priest.",
	"But you can bring a priest here, can't you?",
	"I ruined so many souls that I might have a chance for salvation if I save at least one. Wait here and try not to give in!",
	"So? The werewolf's still there?",
	"Here, you'd better go home, all of you. There's no werewolf in there!",
	"Hey you! We need no strangers here! Get lost while it's not too late!",
	"Maybe a hundred of yellow fluffy chickens will teach you to cackle more politely, what do you think?",
	"Watch your mouth yourself, little rooster! If you don't go of your free will, we'll make you do it!",
	"Who is it to forbid me to walk anywhere I want to?",
	"Three inches of steel to rip you up are here!",
	"Let's see whose steel is better, shall we?",
	"What do you need in our city?",
	"Visitors are rare in our city. What do you want?",
	"It's not that we're too happy to meet you. What do you need in Des Moines?",
	"Just looking around, the way you live, you know...",
	"Damn you! Get out while you still have a chance...",
	"Go on, run for your life, you, sissy...",
	"Get lost! I don't want to see you here anymore...",
	"Required!",
	"They say you agreed to help us. Good luck to you, Captain.",
	"God bless you, Señor Captain!",
	"I really wish everything would be fine with you!",
	"Required!",
	"Señor, you're our savior! God bless you!",
	"Thanks. They will do it, for sure...",
	"Everything's fine.",
	"Well, that's great!",
	"If I were you I wouldn't stay here long. Our city isn't really hospitable...",
	"Hum... Er, we'll see.",
	"The curse got us!",
	"Our city is cursed!",
	"Look what's happening to us! What a terrible misfortune!",
	"Yeah, well...",
	"Damn you! Get out while you still have a chance...",
	"Go on, run for your life, you, sissy...",
	"Get lost! I don't want to see you here anymore...",
	"Required!",
	"They say you agreed to help us. Good luck to you, Captain.",
	"God bless you, Señor Captain!",
	"I really wish everything would be fine with you!",
	"Required!",
	"Since you've seen this nightmare for yourself, you must now go to our leader Fernando Torres. Do talk to him.",
	"Um. Sure, okay.",
	"Hello. What brought you to Des Moines?",
	"Well, just looking around... Tell me, is everything fine in the city?",
	"Go away! I don't want to talk to you.",
	"Hmm... as you wish, bad for you, though.",
	"Señor Captain, as soon as you learn something new, I beg you to inform me immediately. In fact, you're our last hope for a normal life.",
	"I'll do my best to break this horrible curse. Brace yourselves!",
	"Hello, Captain! What's new?",
	"I found Elizabeth Sheppard.",
	"Hello, Captain! What's new?",
	"I went to look for the brig Queen. It seems to be the last step to your salvation.",
	"Have you removed the curse? In an instant we all returned to normal here!",
	"Yes, I found the brig Queen and did everything. Glad I could help you.",
	"Señor, you saved us! Did you want anything?",
	"No, nothing special...",
	"Everything's fine. Why are you asking?",
	"When I disembarked at the Cape of Unfulfilled Hope, some people attacked me. No idea why they did it.",
	"I can't tell you anything on this matter. Have no clue who it could be.",
	"I see... So you say, everything's fine in Des Moines.",
	"Exactly.",
	"I see then. Sorry for bothering you...",
	"Great! So, what have you learned?",
	"We've spoken about it already, Captain.",
	"Captain, we've been over this already.",
	"Captain, that's enough, stop it, will you?",
	"Elizabeth doesn't know how and why the curse was laid upon the city, but she found out how to remove it.",
	"Yes, I remember.",
	"Yes, of course ...",
	"I am like this, never give up quickly. I was thinking, if I ask one and the same thing again and again, a miracle might happen! The curse might disappear or anything else...",
	"Good Lord, Captain! Our hope isn't hopeless! Tell us how to do it, quick, please!",
	"With the help of a jade skull of Aztecs. We have to find it and then Elizabeth will tell us what to do next.",
	"Captain, please, do whatever you can.",
	"That's exactly what I'm doing.",
	"Many thanks to you! On behalf of our citizens I have a great pleasure to tell you that we've got a reward for you for everything you did.",
	"What kind of reward?",
	"Twenty thousand piasters! It might be little for you, but our city got very poor during the cursed times, so it's all we've got.",
	"Go on, take this money back. You need them more than me now.",
	"I'll accept your money.",
	"Thanks again. To tell you the truth, I wasn't expecting this...",
	"Not at all. Be happy.",
	"Great! So, er, all the best to you, Señor.",
	"And to you too.",
	"I can't recall the time when I would see a fine living man at night, not some ugly skeleton!",
	"Good Lord, this is a cursed town! For God's sake, what's going on here?",
	"Go away! I don't want to talk to you.",
	"Hmm... as you wish, bad for you, though.",
	"Señor Captain, as soon as you learn something new, I beg you to inform me immediately. In fact, you're our last hope for a normal life.",
	"I'll do my best to break this horrible curse. Brace yourselves!",
	"Hello, Captain! What's new?",
	"I found Elizabeth Sheppard.",
	"Hello, Captain! What's new?",
	"I went to look for the brig Queen. It seems to be the last step to your salvation.",
	"I'll tell you, if it is what you wish! Anyway you won't go far with this story.",
	"I do not frighten easily, so don't you try to scare me. Spill out your story.",
	"Many moons ago the pirate brig Queen sailed in and moored at our cape. The pirates sold some slaves to smugglers here. They were negotiating\n",
	"So... they sold their slaves and then had some quarrel among themselves. Part of the crew stayed here and the other part joined the captain and sailed away. It all started at that moment.",
	"What started? Come on, explain yourself!",
	"Here's what started! You can see for yourself. During the day we're all ordinary humans, but as soon as the sun sets - the party begins. We realised it was all because of the pirates, damn them! However, they also turned into skeletons at night. But anyway it didn't save them. Every pirate who stayed here was fried up one night, one way or another. It didn't help us, though...",
	"We-ell, it's a sad story, right...",
	"So, Captain, now you know our secret and our great grief. I guess you understand you'll have to share it with us now you're here, don't you?",
	"What do you mean?",
	"I mean now you're not allowed to leave Des Moines. We don't particularly need publicity.",
	"It's not my plan to stay here, you know.",
	"The guards of the Cape of Unfulfilled Hope were doing their job well not letting you in here, but you got through anyway. So it's all your fault now.",
	"I wouldn't advise you to hold me here against my free will.",
	"I guess, you're right.\nWell, nobody's going to force you into staying. Anyway, no one's going to believe your story, and even if they do, they'll just sent the Inquisition here with a hundred soldiers and... well, the life of the whole city will be on your conscience. However...you  probably won't suffer much, though...",
	"You're damn right! Maybe I can help you?",
	"You're absolutely right, Torres. I don't give a damn about you and your city! Good night to you!",
	"The same to you, dear Captain.",
	"So long. And cheer up...",
	"Removing the curse is all we're dreaming of. The thing is we don't even know the reason for the curse.",
	"That's bad... Maybe we should try to find the brig the pirates sailed away on. It seems to be the only hope.",
	"You know, not long ago a young lady named, as far as I remember, Elizabeth Sheppard came to the city. So, this girl hired a tartane at Maracaibo, came here and talked the guards into letting her go and meet me.",
	"And?",
	"She tried to find out what exactly happened on that night among the pirates. I asked her why she needed to know, but she was a tough cookie! Didn't tell me a thing.",
	"And did you let her go?",
	"I did. She didn't see us as skeletons, you know.\nSo, I'm telling you all this, because...er, the more time passes since that conversation with her, the more convinced I get that Miss Elizabeth Sheppard knows something I don't.",
	"Is she British?",
	"No doubt. I admit I made a big mistake letting her go like that. I should've got all the information she had from her.\nNow I'm asking you to find her and learn everything she knows about those pirates and the brig Queen.",
	"Fine. I'll do that.",
	"Elizabeth",
	"Sheppard",
	"Hello, Captain. What do I owe the pleasure of seeing you in my house?",
	"Hello, Elizabeth. My name's ",
	". I came her to have a word with you about one...er, unusual matter.",
	"I'm all ears, Captain.",
	"Not long ago you visited the Spanish city Des Moines. The mayor of this city, Fernando Torres, who I presume you should know, asked me to find you. So I did, with pleasure I should say.",
	"You've surprised me, Captain. Go on.",
	"Fernando asked you for help.",
	"How can I help him?",
	"Help him to find the brig Queen.",
	"Why does he need to find this brig?",
	"The think is, young lady, that the people of the city believe the brig has something to do with... a sudden epidemic which struck the city.",
	"So the curse affected the people of Des Moines too, didn't it?",
	"Yes, it's true. So you know about the curse, don't you?",
	"Of course I do! You see, the captain of the brig Queen is a very close and dear person to me. I've been trying to unravel this mystery and remove the curse for a long time now.",
	"Has it worked?",
	"Partially. You see, I'm the daughter of one person quite famous among pirates. My father, captain Stayton was the closest friend and partner of Edward Mansfield!",
	"Oh,..it does you credit, Miss.",
	"So I didn't have any other choice but to go to Jackman with this problem. I hope you know who he is. Do you?",
	"I'll be damned if I don't!",
	"The thing the Indian slaves told the pirates just made the corsairs laugh their guts out. But I wasn't laughing at all, I saw it with my own eyes!..",
	"I saw it too, Elizabeth. Talking and walking human skeletons sin't a pleasant scene, I must admit. So what did my colleagues learn from the Indians?",
	"Only the Aztec god of the dead named Mictlantecuhtli could do it.",
	"Well... What are we to do now?",
	"We have to find the jade skull, it's the artifact of this god. Only the skull can help us remove the curse.",
	"Where do you think it might be?",
	"In the lost Aztec city, I guess.",
	"But, Elizabeth, what happened at the Cape of Unfulfilled Hope? Why were the people of Des Moines affected by the curse?",
	"I don't know   \nOne night, more than a year ago, I heard somebody enter the house. I went downstairs and saw a decomposed skeleton. It was horrible   \nI gave out a cry. The skeleton cried too and ran away. Only then I realised it was the captain of the brig Queen. And I scared him away!",
	"You know, Miss, you're a young lady of great composure. Most young girls would die of heart attack on spot.",
	"Nevertheless, I know I spurned a close person. I decided then that I'd do all I could to find out about the misery of the captain of the brig Queen and help him!",
	"Damn it, it's so romantic! He's lucky to have such a faithful girlfriend as you are.",
	"Captain, I'd ask you to choose your words carefully. Don't you forget who's standing right in front of you!   \nNow that we're in on the same business I want to ask you to fetch the jade skull of the god of the dead. As you see, I can't do it myself.",
	"I have the skull already, Elizabeth.",
	"Well, young lady, I'm ready to do it, at least to honor the memory of your father. So you say the skull is in some Aztec city?",
	"Exactly. In the abandoned Aztec capital Tenochtitlan.",
	"Got it. If I'm lucky to find this skull, I'll head here, to Charlestown, immediately.",
	"Fine, Captain, I'll be waiting for you. Thank you.",
	"Anytime...",
	"How did you manage to get it?",
	"Oh, it's a long story... You'd better tell me what to do next.",
	"Have you brought the jade skull, Captain?",
	"It's with me, Elizabeth.",
	"Not yet. But I'm working on it.",
	"So you've finally found it, haven't you?!",
	"It wasn't an easy thing to do, I must admit... What's next, Miss?",
	"Now we have the thing which can remove the curse. All we have to do now is to find the brig Queen and, well, just remove the curse from its captain.",
	"The Aztec god of the dead, who gave this skull to me, told me among other things that the skull could help the cursed people. But he didn't say how exactly... ",
	"I guess we should deliver the skull to the cabin of the captain of the brig Queen. This way the curse is going to be removed by itself.",
	"Maybe... But where are we going to find the brig?",
	"I don't know. The captain is likely to lead to far into the sea away from the cities. Look around carefully, you won't miss it, I'm sure.",
	"Fine. I'll start the search then.",
	"Captain, have you found the brig Queen?",
	"No, not yet...",
	"So you've removed the curse, haven't you?!",
	"Yes, I did it.",
	"Good lord, I'm so glad for my sister!",
	"By the way, Elizabeth, why didn't you tell me that close and dear friend of yours was your sister?",
	"Just in case...",
	"I see. You're your father's daughter, I can see... By the way, Danielle joined my crew as an officer.",
	"That's fine. I guess you'll be able to take care of her, she's totally lost her mind with all this corsairship.",
	"Well, I'll try.",
	"Did you want to say something, Captain?",
	"No, nothing special...",
	"I'll make you bleed!",
	"Hey, lady, easy, easy! Let's talk, why are you jumping at me as a mad fury!",
	"We've nothing to talk about! You've attacked my brig!",
	"I had no choice, I had to get to the captain's cabin! Wait a minute, is this your brig, you say?",
	"It has been for five years now.",
	"So you're that close and dear friend of Elizabeth... I thought she was talking about a man!",
	"Do you know my sister Elizabeth?",
	"Sure, it's on her request that I'm here now. And you are, I presume, her elder sister Danielle Sheppard, aren't you?",
	"Exactly! Let me ask you who you are.",
	"I'm called Captain ",
	". I've been looking for your brig to remove the curse. Tell me how it happened, how the curse of the Aztec god of the dead affected you.",
	"So that's what it was! I still thought it was some scarecrow\nIt all happened at the Cape of Unfulfilled Hope in Maracaibo Bay, near Des Moines. You probably know that I'm the daughter of Captain Stayton. Despite the fact that I'm a woman I won the right to be the captain of the brig Queen.",
	"Once somewhere around Bermuda I hired a Captain named Pierre Cabal. It was my mistake, he's an utmost bastard. He captured some young Indian near Santa Catalina. Unfortunately, I learnt about it only when we were entering Maracaibo. The bastard decided to sell the Indian and took the money. He said the Indian was his personal catch.",
	"Sure I couldn't let this scandal happen. When we were in the middle of the bargain near Des Moines I declared that it was either we shared the money or I'd let the Indian go. Finally, I had to let him go. But that bastard Cabal took out the gun and shot the Indian in the back. A fight between us was inevitable.",
	"But you never know. As soon as the Indian fell onto the grass, moaning, some scarecrow jumped out of thin air, grabbed the dead Indian and told us in a thundering voice we were all, my crew and I, cursed. Then it disappeared.",
	"Yeah, that was Mictlantecuhtli in flesh.",
	"We were all struck dumb. Nobody thought of fighting anymore, but we couldn't take Cabal to the brig either. So I took the bigger part of the brig and we sailed away. Those who liked Pierre stayed with him.",
	"And ten it dawned on you that the curse wasn't a joke...",
	"That same night, to be more exact. Can you imagine how horrified we were?!",
	"Yeah, I can imagine. By the way, it wasn't only you who the curse affected. The people of Des Moines suffered from it too.",
	"Dash it!",
	"You're lucky, Danielle, that Elizabeth recognized you when you came to her at night as a skeleton, and she started to look for the answer.",
	"Dear Elizabeth! Yeah, I should be proud of my sister   \nWell, Captain, since you came to remove the curse, do it then!",
	"I guess I've already done it. All I had to do is deliver the jade skull of Mictlatnecuhtli as close to the captain of the brig Queen as possible, so I did.",
	"The curse's gone? I'm not going to be a skeleton anymore, am I?",
	"I think you aren't. It's all over.",
	"How can I thank you for this, Captain?",
	"Thank your sister... Though, you know, I have an offer to you - join my crew as an officer. I'm a pirate just like you are. I guess we'll be a good team.",
	"Well, the hell with it, why not? I agree.",
	"Excellent!",
	"Danielle",
	"Sheppard",
	"Danielle",
	"Sheppard",
	"Queen",
	"The brig Queen left the: ",
	" and headed for: ",
	"The brig Queen",
};
