string DLG_TEXT_Q [35] = {
	"I don't want to talk right now.",
	"As you wish.",
	"You owe my disciple, Augusto Brahms!",
	"Uh... Well, yeah. See, there was this deal... Hm. Only I didn't know he was your adept.",
	"Nevertheless, it is so. So you must pay me ",
	", immediately. Do you have that kind of money?",
	"Hm. I guess I do...",
	"This is a bit unexpected... I didn't expect to have settled things so quickly.",
	"Fine. I'll release you.",
	"Thank you.",
	"Didn't know?! \n Then you'll stay in the temple of Sacrifice forever! One skull more, one skull less...",
	"How is that so?!",
	"How dare you, mortal?!",
	"Oh, there it is! If I'm not mistaken, then you're the one and only God of the Dead.",
	"That is so. \n I have long watched you. Your wanderings in Tenochtitlan amused me. But now you have taken an item of my cult, and I am no longer amused...",
	"You see, your godliness, I was tasked with getting this mask by a certain Aztec, whose name isn't usually pronounced in these parts.",
	"Montezuma? Har har, so he can't sit still yet! Well, no surprise there. \n Anyway, you've touched the jade skull, and that's a crime. But you've managed to neutralize the guards, who were all once great heroes. \n Moreover, Aztecs respect above all else the courage of a warrior. And you've shown that you're a good warrior, at least, so I'll give you a chance to live. Prove your greatness as a warrior, and you will be allowed to leave here.",
	"What must I do?",
	"Fight with me! Come, let's begin!",
	"Guess I have no choice...",
	"Well, you've shown that you deserve it. Now you may leave this place alive.",
	"Ooh... If you wish, I'll put the skull back.",
	"No need. I've got many. You may take it; you've earned it.",
	"Many thanks to you, respected God.",
	"But before you leave, I want to tell you about Montezuma.",
	"It's most interesting.",
	"Montezuma II is the last chief of the Aztec empire. 150 years ago, he betrayed the gods of his people when he tried to negotiate adoption of Christianity with Spanish missionaries.",
	"As for us Aztec gods, we didn't forgive Montezuma his betrayal, and we cursed him. Almost all gods retreated to the limb. I was the only one who stayed here.",
	"Sorry, retreat where? To the limb?",
	"Gods can only live when people worship them. If people forget them, they must retreat to the limb - the world of oblivion. I stayed on Earth only because I now own the Aztec people, for all Aztecs were killed by Spaniards when they lost our support.",
	"I have the power to return dead bodies to life. Being the master of Tenochtitlan, I raise the deceased to serve me.",
	"And as for Montezuma, he's cursed; he cannot join his people in the realm of the dead. He roams around Texcoco Lake, and grieves over the loss of his people.",
	"So he's a ghost, is he?",
	"You can say so, yes. Now you know who the Aztec near Texcoco Lake is. You should also know that the jade skull has power over the dead, and can help the cursed live.   \nFarewell, warrior.",
	"Farewell, brave Mitch... Mitclo... Er. Bye, then!",
};
