string DLG_TEXT_Q [526] = {
	"You have business with me? No? Then leave my residence at once!",
	"I think I've made myself clear.",
	"Even though I've made myself clear, you continue to distract me!",
	"Okay. Now you're starting to seem rude, and that tires me out.",
	"I'm gone, already.",
	"Yes, Morgan. Perfectly clear.",
	"Sorry, Morgan...",
	"Hey...",
	"Morgan, listen. Have you heard anything about pearl diving at sea? I hear they're doing it somewhere around here.",
	"A broken version of the game.",
	"! Happy to see you! Why have you come this time?",
	"What else do you need?",
	"How long will this go on? If you've got nothing to do, don't distract others!",
	"You're a good privateer, so live for now. But I don't want to socialize or talk with you any longer.",
	"Oh, nothing, really. Just wanted to stop by and say hi. Nothing business-related.",
	"Nothing. Just... y'know...",
	"Fine, Morgan. Sorry...",
	"That's it, dammit! You've played your game!",
	"Morgan, listen. Have you heard anything about pearl diving at sea? I hear they're doing it somewhere around here.",
	"Listen, Henry, you got any fitting assignments for me?",
	"I've arrived, Henry, as we agreed.",
	"Heh. They're hunting, all right. Only they only take in pennies. Peanuts! Look for Sharp. He's our pearl specialist. Hee hee...",
	"And you aren't going to say where they might be found?",
	"I have no clue. Anyway, the best corsair in the whole wide world usually hangs out at brothels. Look for him there...",
	"Got it... Thanks, Morgan.",
	"You've got business for me?",
	"Sir, Governor General Thomas Modyford of Jamaica needs your help.",
	"And who are you?",
	"I'm his envoy.",
	"Hm. Good. And how may I help Sir Thomas Modyford?",
	"You must attack the Dutch city of Curacao.",
	"I don't think that's possible, at the moment. I don't have enough strength for such an operation. Tell that to Modyford.",
	"Sir Thomas Modyford is counting on you in this matter.",
	"I think I stated clearly enough that I can't pull of such an operation right now. However, if you find me sometime later, at my house in Jamaica, then, possibly, I might be in a position to discuss business with you. Something for a real corsair. For now, all the best.",
	"I'll remember your words. I think we'll have something to talk about, once I'm free. All the best.",
	"Ah, so you found time to drop by after all?",
	"Good day, Henry. I've come to find out about that hot mission for a 'real corsair'. Has the time come?",
	"Hee hee... The time has come and gone! When you were here trying to talk me into attacking Curacao, I was already planning an expedition, and had begun preparing for it. But not on Curacao.",
	"Why didn't you say so immediately?",
	"The time has passed. You thought I'd wait for you forever? Ha! I wanted to offer you a journey to Cumana, but you were sailing around the whole ocean! We managed without you.",
	"Oh, what a pity...",
	"Well, you were sailing around the archipelago like a man possessed, jealously trying to complete Modyford's assignment. And I only invite those people into the fold who can immediately flow into my squadron. I don't need any extra lip. Moreover, that order from Modyford smelled fishy anyway.",
	"Fishy? Explain?",
	"Modyford knows that, as a rule, we don't attack the Dutch, even at sea - never mind capturing settlements. The Dutch are the most active traders. We depend on them for our flow of goods in the archipelago. If we turn them away from trading, we'll lose many things that are now sold everywhere.",
	"Beyond that, amongst the corsairs there's quite a good lot of Dutchman. That's also a factor. So Modyford gave you a practically impossible mission.",
	"I get it now. If you don't mind, let's get back to our business. What's that hot thingamabob, you mentioned?",
	"I want to attack a Spanish city. Are you ready to join in a Spanish blood-letting?",
	"Naturally, I'm with you! That is, for an equal share, under the laws of the Brotherhood of the Coast.",
	"Damn! However intriguing that may sound, I must decline. The condition of my ships leaves much to be desired, and the team's at the limit after such a rough trip around the Caribbean. Not this time.",
	"Well, then! The city to be attacked is Belize. It's been reported that a lot of gold has been pooled there, scraped out of the Spanish mines on the American continent. The gold is being readied to be shipped to Europe, so we have no time to lose. ",
	"All that's left is to finish the final preparations for the expedition. We need to get to Jackmann, in Bermuda, and to John Morris in Port-of-Spain, on Trinidad. They're ready and waiting for us. To take Belize, we have fifty days.",
	"And another important note - know that if you storm the fort, and fortune smiles upon you, our ship teams will support you in the assault. ",
	"And now we must hurry.",
	"Forward!",
	"There's a whole tail stretching behind you! We're going for serious business. We don't need any extra burden.",
	"So worry about getting ready for the operation. Get rid of your extra companions. And don't take too long, or you won't be able to participate in the mission.",
	"I'll do what I can.",
	"I don't have the luxury to change my plans so drastically. I'm forced to decline the mission that you suggested.",
	"What are we waiting for? Time is valuable. We must move out.",
	"Of course. Move out immediately.",
	"Well, then. You know best about not needing money... Haw haw! ",
	"You won't see another offer like this from me. All the best.",
	"See you, Morgan. Sorry...",
	"While we were futzing around who-knows-where, the gold from Belize left for Spain, and I'm not interested in Belize without that gold. You've ruined our plans! We're leaving.",
	"Well, that's your right.",
	"The ships of the famous corsairs left the squadron.",
	"The gold's been found in the fort, as you suggested. We're finishing loading it up into the hold. You are a courageous and skillful warrior.",
	"Thank you.",
	"Well, the time has come to leave this city. And though I left my wonderful frigate here, I consider this raid a success. Each of us is leaving Belize on his own course. Goodbye, and be healthy.",
	"Well, the time has come to leave this city. We did what we wanted, and are leaving with a good prize. Each of us is leaving Belize on his own course. Goodbye, and be healthy.",
	"All the best, Morgan.",
	"Wait another minute. I've been thinking, here. Maybe, actually, you don't want to burden yourself with buying and selling? If not, I'm prepared to buy out your share of the gold. ",
	"Wait a minute. Look, your ships are sagging below the waterline. You're overburdened. You can't go far from the fort. ",
	"No, Morgan. I'll deal with my gold myself. Goodbye.",
	"I really do need to sell the excess.",
	"Let me think. I'm not ready to answer yet.",
	"Well, then! Have you decided to sell your gold to me?",
	"Eh, all right. I'll sell...",
	"No, Morgan. I'll sell it somewhere else. Goodbye.",
	"Let me think a bit more...",
	"Fine. How much gold do you want to sell?",
	"I'm ready to sell 25% of the share belonging to me.",
	"I'm ready to sell 50% of the share belonging to me.",
	"I'm ready to sell 75% of the share belonging to me.",
	"I'm ready to sell everything.",
	"Sorry, Morgan. I changed my mind... Farewell.",
	"Fine, you've sold a quarter of your share. Well, then! A good deal for both of us. Farewell.",
	"Bye, Morgan. Be seeing you.",
	"Fine, you've sold half of your share. Well, then! A good deal for both of us. Farewell.",
	"Bye, Morgan. Be seeing you.",
	"Fine, you've sold three quarters of your share. Well, then! A good deal for both of us. Farewell.",
	"Bye, Morgan. Be seeing you.",
	"You're selling everything to me? Wonderful! Well, then! A good deal for both of us. Farewell.",
	"Bye, Morgan. Be seeing you.",
	", I'm grateful to you from the bottom of my boots. Old Man Mansfield was a very good man, who deserved more than being cut down by the Spanish.",
	"I saw Mansfield only a few times, and didn't socialize with him closely. But he seemed like an honest and honorable man.",
	"Yes, that really is so. ",
	"As a reward for such a mission, please accept a present from me - my rapier. This blade has no equal on the Caribbean.",
	"Thank you, Morgan. This present honors me. Farewell.",
	"To what do I owe the pleasure of seeing you here?",
	"I'm here on orders from Edward Mansfield.",
	"I'm listening to you, very closely.",
	"Edward's asking me to assist him. I need information regarding the plans of  Governor-General Thomas Modyford, of Port Royal. I'm interested in if he has an order to begin military acts against the Dutch colonies, and what he wants to do specifically.",
	"Hm. Not a lot, and not too little. And this is what interests you, specifically?!",
	"Yes. That is so, sir.",
	"Well, then! Let's get to the matter at hand. Mansfield is like a father to me. I'm ready to do a lot for him. But I'm not ready to do much for the sake of Holland. So if you want me to help me, you'll have to work for me personally.",
	"I only answer to the governor-general of Curacao.",
	"Sure. I'm open to suggestion.",
	"In that case, goodbye. We have nothing more to talk about.",
	"A pity...",
	"Good. The order is follows. There's a filibuster hanging out on Tortuga now, named Pierre de Picard. We were in a deal together, and I suspect that Picard has claimed part of the gains for himself. ",
	"I need to check that. Go off to Tortuga. Nobody knows you there. Try to find a maximum of information about Picard.",
	"Wait here. I'll back back with the results soon.",
	"What did you discover? How's my big friend and brother-in-arms Pierre de Picard?",
	"Not bad. He throws money around, left and right.",
	"I haven't found anything notable as yet...",
	"I was able to find out the following facts.",
	" Pierre de Picard has rented a room in a Tortuga tavern, for a year in advance.",
	" He's buying valuables in a store in Tortuga, at almost wholesale rates.",
	" He's got a bunch of the newest, most expensive culverins on his frigate. ",
	" He's given the moneylender such a sum of money that he doesn't take anyone's money anymore.",
	" He's a regular at the brothel, and an honored guest.",
	"From here, I want you to speak as detailed as possible. On what is he spending his money, specifically?",
	"Well, then! I presume that everything is clear. Picard didn't have such a sum at his disposal before, and didn't get it as a result of our cooperative operation. Taking my suspicions into account, he'll have to sweat pretty bad to justify these expenses... I thank you.",
	"Hm. Happy to have helped you. Now, if you don't mind, let's get to that matter for which I actually came here.",
	"Understood. But that doesn't prove anything in particular. I know that he has that much on hand. So you'll have to return to Tortuga and continue gathering information.",
	"I found out a good lot, to make the following conclusions.",
	"Fine. I'll go once again to Tortuga, and continue asking around.",
	"I don't think so.",
	"Pierre de Picard has money.",
	"Of course he does. He got his share. The question is, how much?",
	"I can't figure that out.",
	"In that case, consider us in disagreement. For the sake of Mansfield, I won't inform anyone of your strange wish to know so much. Farewell. You're free to walk.",
	"Well, then. Farewell.",
	"The thing is, I don't know Modyford's plans, if any, or what orders he's got concerning his participation in the war. However, I am aware that Modyford is getting a landing operation ready, using the strength of the garrison of Port Royal.",
	"That's too little for me. I need to know specifically what he's planning.",
	"There is a way to learn that. There's an English officer sitting in jail now, a certain Lieutenant Allan Maclaine, who tomorrow is due at the rope tailor's. Yesterday, he sent his garrison colleague to his forefathers in a drunken brawl. Get him out of jail, and he'll tell you what they're planning. And remember that he'll be hanged tomorrow.",
	"I got it. Thanks for the tip, Henry.",
	"Allan",
	"Maclaine.",
	"What brings you to me this time?",
	"I've been tasked to tell you that the Netherlands wants revenge for the death of Edward Mansfield.",
	"Well, then! I realize that Edward was Dutch... What do you plan to do?",
	"I need to coordinate the order of my actions with you.",
	"Hmm. Good thinking. All right, let me lay out what I know myself. The Spanish have waged an attack on the buccaneer settlement. The instigator and prime organizer of this is Governor-General José Sánchez Jiménez of Santiago. It was he specifically who thought up and financed this operation.",
	"So we are attacking Santiago?",
	"Possibly. Let's not get ahead of ourselves, though. There's a whole line forming for the head of the governor-general of Santiago. The English want his blood, but you're at war with England and cooperative actions are impossible. So our methodology must be clearly drawn out.",
	"Yeah... It's true. Jiménez has big problems.",
	"He sure does. Now. If want to take part in this in this action, you must conduct a recon operation.",
	"What exactly do you have in mind? ",
	"You must sneak into Santiago, and learn if the governor-general is on site. Don't worry, there's no mistaking José Sánchez Jiménez. The attack must be conducted at a time when the governor-general is in the city. So we must know his schedule for the near future.",
	"All clear. I'll be at your place soon, with the required information.",
	"Well, tell me, quickly, what you've managed to uncover.",
	"Jiménez is in the city, and isn't planning on going anywhere in the near future. They've got the city holiday lined up in Santiago, and it can't go on without the governor-general.",
	"Excellent! You've done your job well. Thank you. Your weighty contribution to this sacred mission will be handsomely rewarded by the Brotherhood of the Coast.",
	"I'm very happy that we could have helped you. So how's the assault going on the city?",
	"That's not your concern. You've done your part. Mansfield will be avenged.",
	"Sure. I get it. Farewell, Morgan.",
	"Aha! Why, it's Captain ",
	"! I've been noting you for a while. Before now you haven't stuck your nose into my business, which is why you're still alive and well. Say what you've come for. I don't think it was for celebratory conversations",
	"Listen, Morgan. You know I wouldn't disturb you if it weren't business. I've got a matter for you.",
	"Lay it out...",
	"What do you think about the upcoming Anglo-Dutch mix-up?",
	"So you know, too... Well, then! I can say that the Dutch don't get into our way in these waters. Moreover, they're profitable for us. All trade rests on them in these parts. So I don't like the idea of war itself, and the English military won't damage the Dutch enough anyway. They'll just spill useless blood, for the happiness of the Spaniards.",
	"However, I think that the old fox Modyford is trying to pull the chestnuts out of the fire with someone else's hands.",
	"What's right is right. There is conjecture that he'll try to use the Brotherhood of the Coast in the war.",
	"It's possible...",
	"Henry, I don't want to beat around the bush. I need you to not take part in the attack against the Dutch. I can say that I'm happy that this war isn't interesting for you...",
	"Hm. There is a problem. Although this war is unpleasant for me, I wouldn't call it uninteresting. The thing is, my drunken guards have already sunk their last piasters into the taverns and we haven't had any big deals in a while. That said, I presume that whoever has sent you to talk me out of this has already foreseen such a development?",
	"Yeah, without giving a single crumb. But that's my worry. How much do your cutthroats need, to have fun on shore and not get involved in big politics?",
	"They've got no head for politics, but 250,000 will last them a couple of weeks.",
	"I'm prepared to compensate you the losses of not attacking the Dutch.",
	"250 on the table, then, and I'll pass on all of Modyford's Dutch angling.",
	"Well, you let your boys chug that rum! Take the money, and remember I'm holding you to your honor.",
	"I don't have the money now, but I'll find them and give it to you. So wait just a bit...",
	"And you think you have to tell me that? Go on, out with it - but be succinct. ",
	"Sorry, Henry, I don't mean to offend. It's just a formality. Well, farewell and be well.",
	"Yeah... Man, you are in a pickle, aren't you. It's good that you didn't start resisting arrest. Here, in Port Royal, I've got a lot of control. \n The commandant immediately reported to me about you, so the question of your liberation has already been decided.",
	"And how is John Bolton? I was bringing him to you from Puerto Principe.",
	"I'll free him, too. Later. Someone tried to set me up, and I'll find out who. I'll have a job for you soon, and I warn you now that I won't take no for an answer. You owe me. Get your matters in order, and come to me.",
	"Fine, I'll come. And Morgan...",
	"Yes?",
	"Thanks!",
	"Ahh, so you've come. That's good. \n I've learned something about Bolton. You've got to go to Martinique now. There's a loser there by the name of Edward Low. When you find him, give him this here Black Spot.",
	"Do I need to relay some words?",
	"Ha. What words can there be, when you unveil the BLACK SPOT?! \n That alone is enough. But you shouldn't kill him. Let him stew a bit. And with the Black Mark, he won't live more than a few days. \n That's it. Go. When you return, your reward will be waiting for you.",
	"Gotcha, Henry. I'll begin.",
	"Sea Wolf",
	"Edward",
	"Low",
	"Did you give him the Spot?",
	"Not yet, Morgan. I'm dealing with it...",
	"Well, tell me how it all went!",
	"Henry, I'm returning the spot to you.",
	"Are you quite sane?!",
	"Yes, very much so. Edward told me that you smoothed everything out...",
	"Smoothed out?! I, Henry Morgan, smoothed things over with that creep?! Man, you really amaze me, buddy...",
	"So I take it that Low tricked me?",
	"He tied you around his little finger like a blind puppy! Mm... Yeah, I don't even know what to think about you anymore... ",
	"Ah, Henry. Go on, give me a chance to redeem myself! I'll rip him apart like an old newspaper! I'll cut him into belts, with or without any Black Spot!",
	"Ooh dearie me! What a terrifying privateer! I'm a-tremblin'! Ah, well, You mess up, you clean it up, I suppose that's reasonable. All right, go find our friend and let his blood out.",
	"I'll do so, Admiral!",
	"Good. And I'll wait for the good news. And don't be so gullible!",
	"Of course, Henry. I'll begin!",
	"Edward Low is dead?",
	"Not yet, Morgan. Soon!",
	"You know, Morgan, I'm sick of all of this. I didn't find Low, and don't have the strength to look for him...",
	"You've got a sad face. Did you let Low slip away?",
	"Yes...",
	"Well, then! I somehow thought so. Maybe I shouldn't have given you such an assignment. Maybe your element is raids, boarding actions, battles? \n Time will tell. Go. Possibly one day I'll give you another chance.",
	"Thanks for that, Morgan. Sorry...",
	"From your sparkling demeanor, I gather that everything went well.",
	"Yes! Edward Low is dead!",
	"Wonderful news. Did you learn anything?",
	"Only that there are a lot of unhappy pirates around you. That's what Low said.",
	"Well, you can't please them all - and neither should you try! Still, all in all, you've earned your reward. Take 20,000. Stop by from time to time. It's possible that there will be a mission for you soon.",
	"Fine, Morgan. Thanks!",
	"It's good that you stopped by. I need someone like you. Do you want to take part in my scheme? I'll warn you, right off the bat, there isn't much glory. Still, the profit's good.",
	"Well, money doesn't grow on trees. Why not. What's the plan?",
	"Hm. In this case, everything is fairly simple. We'll begin by competing with the greatest pirate of all time, Mr. Bartholomew Sharpe. To cut to the chase, I've received information on where the pearl divers are going to be for the next month or so. ",
	"Not bad. Where's that, then?",
	"At Turks, in the North Bay. So be off there, and take down the operation. I'm awaiting you with a bag of pearls.",
	"Will do...",
	"You need to bring me no less than a thousand small, and five hundred large, pearls. So try your best. We'll split the catch.",
	"I got it, Henry. You can count on me. I won't let you down!",
	"Did you rob the pearl divers?",
	"Not yet, Morgan. I'm on it...",
	"Well, what do you say?",
	"Sorry, Henry. I was late to Turks.",
	"My friend, you are a real clumsy oaf. Still, I suppose I'm at fault here. I've got a ton of pirates at my command, and I gave this business to you. What a mess.",
	"Henry, baby, I can change!",
	"Of course you can. But change takes time. For now, go somewhere far away. I'm not in the mood for you now...",
	"Suits me, Admiral...",
	"Well? How are things with the pearls?",
	"Bad. Those damned Tartans scattered all over. I couldn't net a one...",
	"Ha! You're a real web-footed goose! You should have prepared! Still, I suppose I'm at fault here. I've got a ton of pirates at my command, and I gave this business to you. What a mess.",
	"Henry, this is my mistake. But I'm asking you not to make any hasty decisions! I'll fix things...",
	"Where are our pearls, buddy?",
	"You know, Henry, it didn't go so well. The trouble with the pearls is... They weren't there.",
	"Here with me. I've got ",
	" small and ",
	" large pearls!",
	"So it turns out that you're a rat! You think I'm not aware that you went through with the operation, you idiot?!",
	"Henry, simmer down...",
	"Simmer down?! Yeah, you sure don't need to borrow any extra insolence from anyone. Tell you what what, rat, you're finished. I'll finish you with my own hands... Close the door!",
	"Henry, Henry!",
	"Hmm. Hold up. I've got other information You've taken ",
	" small and ",
	" large pearls from the raid. What do you say?",
	"Oh come on, Henry! I'm telling you the truth.",
	"Excellent. Then you've done well. Moreover, you've completed the conditions of the deal; you've brought me pearls no less than the agreed amount. What else can I say? Good boy!",
	"Admiral, your words warm my heart. Well, what about my share?",
	"Hm. I can't say that I'm pleased. You haven't kept to the agreed plan. I wanted a thousand small and five hundred large pearls. So I'm sorry, but I'm taking everything for myself...",
	"What do you mean, Admiral?! I did the job!",
	"And I don't think so. My information is exceptionally accurate. You've pocketed the pearls. There's only one punishment for that - death. Hey, close that door. I'm going to choke a rat in here...",
	"Henry, what are you?!",
	"Half of the catch is yours, like we agreed. The rest is mine.",
	"Excellent! Well then, Admiral, I think I'll go...",
	"I won't hold you. Come back later. Maybe something else will come around...",
	"Sure thing, Admiral.",
	"You've done a bad job, buddy! I was counting on a totally different haul. And if you let the Tartans slip away, that's coming out of your cut. Anyway, arguing is pointless. I'm taking it all...",
	"Hm. I guess I can't do anything about that. I yield. May I go now?",
	"Why have you come? I don't have any jobs for you now.",
	"You know, I killed a fellow... A good warrior, I should say!",
	"Do you think I'm interested? These modern pirates... Well... Who's this warrior?",
	"Yeah! A good warrior he was! His name was John Avery; he...",
	"John Avery? How did it happen? What was the fight about?",
	"There was no fight, really. I was paid to kill him. A kind of a bounty hunter, I was...",
	"Hm... And who was it that paid you?",
	"Captain Goodley.",
	"Really? Well, maybe you don't know, but John Avery was one of my trusted pirates. I would understand if you had a duel or something, but you just killed a member of the Brotherhood of the Coast, and for money! My revenge for his murder will be bitter.",
	"Damn it! Morgan, I didn't know!",
	"Shut up! You'll speak when I ask you to... So, what was it about Goodley?",
	"It was Goodley's idea! I didn't know...",
	"Shut up... Oliver, bring Goodley here, immediately! We'll deal with it on the spot, so to speak... And as for you, stay away for the moment, daring corsair...",
	"I didn't know at all, Admiral...",
	"Oh, who is coming?! Thanks for your visit. Tell me, Goodley, my friend, what was this task you gave to ",
	"Me?! What a bunch of rubbish, Admiral. I didn't give him any task...",
	"He says you paid him to kill John Avery. Does that ring a bell?",
	"What am I? Nuts? Of course I didn't. He's pulling your leg and trying to set me up...",
	"So, what's the news?",
	"I'm telling the truth, Henry.",
	"Well, it's all clear now. I'm not Lord Almighty to be judging you. You're going to duel - whoever lives must be telling the truth.",
	"Well, I don't see another way out...",
	"Fine then. Get started...",
	"I have to finish some business, first...",
	"Fine, then. We think you're telling the truth. The Lord himself was backing you today.",
	"Yeah, that's true... But I was really telling the truth, Henry. It was Goodley who was pulling your leg...",
	"Look here. Go to Jackmann and tell him everything that happened here.",
	"All right, Admiral. I'll do that right now.",
	"I consider this matter to be extinguished, then...",
	"Got you, Admiral. Thanks for believing me...",
	"Ah, here's ",
	"! I guess it means we're going to run into problems soon...",
	"Sounds like it... You see, Henry, something's happened to me...",
	"If you want to tell me about your double, I know already.",
	"Yeah, strange things are happening all around... What do you think about it all? Jackmann sent me to you.",
	"It's clear that nothing is clear. Something's coming, something really bloody.",
	"So what am I to do?",
	"Try to find out who's in charge of your double and causing these problems. I guess it all boils down to one source...   \nI took some measures to clear everything out. I sent a man to carry out reconnaissance, so to speak. You can find him and learn what he's figured out. Well, at least, you won't have to start from scratch.",
	"Yeah, right. What his name, this man?",
	"Steve Linney. He went to La Vega; he was to stop by every pirate settlement. It will be your task to see if he's really visited them.",
	"Got it. I'm on my way.",
	"Oh, here's our hero again. So, have you learned anything?",
	"You know, I couldn't find Steve Linney in La Vega.",
	"I don't even know what to say. You're slow as a turtle. Steve Linney went missing, and his schooner, the Swallow, was said to have been up for sale at the Santo Domingo shipyard.",
	"Devil!",
	"Exactly. Go to Santo Domingo shipyard and find out all you can about the Swallow. And don't go wasting your time...",
	"All right, Henry. I'll do it as well as I can.",
	"Oh, here's our hero again. So, have you learned anything?",
	"You know, Henry, Steve Linney disappeared without a trace.",
	"How so?",
	"Two strangers in La Vega asked him to go with them. No one has seen him since. And his ship was definitely sold at the Santo Dominigo shipyard.",
	"Well, I guess we won't see Steve again... Pop in from time to time. I might have something for you.",
	"Okay Henry, I will.",
	"Ah, glad to see you! What's new in the world?",
	"Unfortunately, Steve Linney is dead. The pirates from the frigate, Leon, killed him. I sank their ship later.",
	"Ay caramba! Poor Steve...",
	"That's not all, Henry. The captain of this ship was trying to talk me into working for the Admiral of the Brotherhood of the Coast. And guess what - he wasn't talking about you...",
	"Who's this Admiral then, I wonder? Is it Edward Mansfield? I thought we reached an agreement with the old man...",
	"No, Henry. He was talking about Richard Sawkins, head of Puerto Principe.",
	"Hah! Not a big surprise, though! Even the captain of a ship is in danger of receiving a Black Spot from his crew; this includes the Admiral of the Brotherhood of the Coast...",
	"Is everything really so sad? Jackmann was trying to tell me about it; he was babbling about wolves... I don't get a thing, really.",
	"Jackmann is known for his wild metaphors, you know.   \nAh, forget it! We'll win anyway! We'll send all our enemies to feed the sharks! Hah! I guess the fish will have a real feast, soon! We'd better figure out what we're gonna do, since Sawkins started all this.",
	"Let's figure it out, Henry.",
	"Fine then. Rumor has it, Sawkins is planning something. We can't let anything happen, for if it goes well, he'll gain extra authority. He's a lucky guy, you know. I guess we'll have to ruin it for him.",
	"Got you. What're his plans then?",
	"Heh, nothing unusual - busting the Spaniards. Well, in brief, we have to ruin his plans.",
	"How come?",
	"We have to be the first, that's all. Find out what he's up to and do it before he does. Or... Well, think yourself, and act according to the situation. What I care for is good results.",
	"Got it. I'll get started immediately.",
	"Perfect! I'll be waiting for you and the good news.",
	"I'll do it, Henry.",
	"So, how's it going? Did you manage to pull a spoke out of Sawkins' wheel?",
	"Unfortunately not, Henry...",
	"That's bad. Now Sawkins has got more power...",
	"I did all I could.",
	"So, how's it going? Did you manage to pull a spoke out of Sawkins' wheel?",
	"Yeah, I did everything, as I promised...",
	"Great! What was he up to?",
	"He learned about a Spanish war ship that... Well, it had a lot of interesting stuff aboard. As rumor had it.",
	"And?",
	"I sank the Spanish ship!",
	"Did you board it? Did you check the holds?",
	"Hmm, not really, Henry. I couldn't do it...",
	"Damn! That's a pity... I hope you're not trying to pull my leg, are you?",
	"Not in the least, Henry. I'll be damned if I am!",
	"Everything has its time, you know. You can be damned later. For the time being, I need you. And don't you try to lie to me, buddy...",
	"No way, Admiral!",
	"All right, I believe you... You may devote some time to your own business now. If you want to work for another country, I won't say a word. When you're done, though, come to me and we'll continue our cooperation.",
	"What if I don't want to have anything in common with the authorities?",
	"Come back in about a month, then.",
	"Got you, Admiral...",
	"You're right on time! I was about to send someone to fetch you...",
	"At last! What's the deal, Henry?",
	"Well, buddy, rumor has it you got involved with ",
	". I think I made it quite clear, that first you were to finish your business with the authorities and then to come to me, only. What's so difficult to understand?!",
	"Nothing, Henry. I got your message. Sorry...",
	"The deal? Hm, this one is a serious. I'm rounding all the pirates together to pull of a scheme that'll make my name immortal!",
	"Oh my. Sounds scary!",
	"Yeah, you should be scared! You'll have a special part in this mission, my friend. I guess it's about time we got even with our dear friend Sawkins...",
	"Hah! It's high time.",
	"It's for me to decide whether it's high time or not, my dear. Your task is to do exactly as you're told.",
	"Look, Henry, it's true we had some misunderstandings, but I've always been loyal to the Admiral of the Brotherhood of the Coast!",
	"You did the right thing, buddy. I appreciate it... Well, let me brief you on the operation now!",
	"I'm all ears, Henry...",
	"Let's get to the point. I'm going to take over Panama!",
	"You're nuts, Henry! That's impossible!",
	"Why?",
	"It has always held the strongest garrison. I don't think that's changed...",
	"Has it ever occurred to you that the strongest garrison must be guarding the most valuable thing Escorial has in the New World?",
	"Hm, maybe... Look, I heard our Charles signed a treaty with the Spanish queen! You surely won't get a pat on the back for this in London...",
	"You say 'heard' and that's exactly how it was for myself, as well - all rumors, no official announcement. Where is it? I haven't seen it. You can't trust gossip, you know.",
	"Well, yeah... Frankly, I don't really care. You'll be the one who will have to report to the British authorities. Do you really think we can reach Panama through Cape Horn and keep our squadron safe? I don't think so...",
	"Neither do I. That's why our way won't lie through Cape Horn; we'll go on foot across the isthmus!",
	"Hell! This sounds even crazier!",
	"Exactly! That's what the Spaniards won't expect. Heed my words, we'll do it!",
	"Ah, damn it! I'm with you, Admiral! When do we begin?",
	"I'm giving you 20 days to properly get prepared. Find a bigger ship and hire more crew. Mind, you can only have one ship in this march.",
	"Got it. What else should I know?",
	"First, we'll take over Portobelo, so as not to leave any Spanish garrisons at the rear. Then, we'll head to Panama through the jungle. By the way, there's no use attacking Portobelo any earlier, so don't waste your time.",
	"I wasn't going to!",
	"Ha-ho! Don't tell me. We're of the same cloth, you and me... Most importantly, you'll have to tackle our problems in addition to fighting successfully... I'll tell you everything as soon as we're there. You should be ready at all times.",
	"You know me, Henry. I'm always ready!",
	"That's good. Well done! You're a real corsair.",
	"Well thanks, Admiral...",
	"So, in 20 days then... Now go get ready.",
	"All right, Henry.",
	"Aha, here you are! It's a good time for you to come. I take it you're ready...",
	"Yes, Admiral, I am.",
	"Why are you here? I told you to come in 20 days!",
	"Yeah, I remember. Sorry, Henry...",
	"Perfect! So we're ready to start. We have more captains here - Jackmann, John Morris, and our big friend, Richard Sawkins... You'll be in charge of the whole squadron and the attack on Portobelo.",
	"Thanks for trusting me, Admiral. I won't let you down, surely!",
	"Listen... ",
	", I thought I told you in clear English to take one ship only. You were to do as told. What's so difficult to understand?!",
	"Everything's clear, Admiral. I'll do it.",
	"I'm counting on it, buddy, otherwise I'll have to kill you...",
	"Hope you won't have to do it, Henry. I'm ready to take command over the squadron.",
	"Fine. Let's get started then.",
	"I'm ready.",
	"Horrifying",
	"Fortunato",
	"John",
	"Morris",
	"Laguna",
	"Lucky",
	"I entrusted you with the squadron and you're doing God knows what. We've been sailing around the Caribbean for 20 days; it only takes 10 days to get to Portobelo from Port Royal.",
	"Just bad luck, Henry...",
	"I want neither 'bad luck' here, nor you. I hope the Spaniards finish you off real soon, what with that attitude of yours regarding your responsibilities We're leaving. We can do without you, I guess... Farewell. ",
	"Admiral? Maybe...",
	"So long, buddy. Don't make me edgy.",
	"All right, Henry. And sorry for the trouble...",
	"We've nothing to talk about.",
	"You carried out a nice attack. Well done.",
	"We've taken over Portobelo, Admiral, but now we have a serious problem.",
	"What's the problem?",
	"The Spaniards seem to know about our plans. The captured Governor told me about it.",
	"Hell! Who told him about it?",
	"According to him, it was the Spanish Governor-General.",
	"Hm, that's bad... It seems to me it's Richard's doing again! It was most likely he who ratted out our plans to the Spaniards. Now when we reach Panama, they'll be ready to meet us.",
	"Well, yeah, the Panama operation seemed fairly risky; now it's just suicide.",
	"Yeah-yeah, probably... Look, ",
	", it's time we got rid of Sawkins.",
	"We should've done it ages ago!",
	"There is one problem, though - I need his men. If something happens to him, they may leave us, and I need them to attack Panama!",
	"So, Henry, you're not going to give up on this scheme?!",
	"Of course not! I can't remember a time I was afraid of Castilian dons. Don't worry, just keep doing what I tell you to, and everything will be fine.",
	"Henry, you're nuts... And I like it! What should I do?",
	"You rightfully disembarked in the Gulf of Darien. Go there now; get your people and head for Panama. My men and I will head to Panama from Portobelo. We'll meet at the Panama gate and begin an attack from both directions.",
	"Got you, Admiral!",
	"Go to the Gulf of Darien; get your people and head for Panama.  My men and I will head to Panama from Portobelo. We'll meet at the Panama gate and begin an attack from both directions.",
	"Got you, Admiral!",
	"That's not all. Jackmann and Morris will join me; you take Sawkins. The Spaniards know about our plans and these stupid dons are likely to have an ambush set up somewhere in the jungle. I'm guessing there'll be more than one.",
	"I think you're right, Admiral. We'll be ready for them.",
	"You'll just have to fight off the Castilians. And one more thing - get rid of Sawkins during the fight. I don't want to see him near the Panama gates. That Richard is damnably brave and might gain more notoriety from the attack. You can't get rid of a hero that easily. Fame is also a powerful thing in the Brotherhood of the Coast.",
	"I didn't quite get you, Henry. How do you want me to get rid of him?",
	"Very simple. Finish him off quietly during the fight, without anyone seeing, of course. Shoot him in the back; that should be most effective.",
	"Hm, that's not quite fair...",
	"And what he did to you was fair?",
	"Of course not...",
	"So then, do as I tell you. And remember, Sawkins must not show up at Panama.",
	"I got it, Admiral. I'll do it.",
	"Wonderful, then. Take your men and go as I said. You should get there no later than two days.",
	"I'm on my way, Henry.",
	"Don't waste your time. Let's get them in Panama!",
	"Yeah, I got you, Henry.",
	"I saw Sawkins fighting in the last battle. You have failed your mission in the jungle...",
	"Yeah, but he is dead now, meaning the problems with him are over. We can ready a tombstone for his grave.",
	"Well, well, well... You failed to carry out your mission. Our friend is safe and sound here.",
	"I couldn't do anything, Henry. It was too dangerous!",
	"Heh-heh, glad to see you ",
	", safe and sound! I somehow failed to notice Sawkins during the battle...",
	"Henry, I regret telling you that Richard Sawkins is no longer alive. He died as a hero!",
	"Ha-ha-ha! We'll never forget about him... So, tell me, what happened during your crossing in the jungle?",
	"We had to face three attacks before we got to the city walls of Panama. Even Indians jumped us!",
	"We did the same, and it was wonderful, my friend!",
	"What do you mean? We lost many people...",
	"Hm, a la guerre comme a la guerre... The thing is, the Spaniards made a grave tactical mistake. They scattered their forces to ambush us, giving us the chance to deal with them group by group! If they had attacked us all together, surely we would have been bested. Now, there's no one to defend the city. I'm positive Panama is in our hands!",
	"Do you believe there are no soldiers in the city?",
	"I'm sure of it! Now, listen to what you'll have to do. Go straight to the residence of the Governor, and begin interrogating him. I have a bad feeling...",
	"What do you mean, Henry?",
	"It's obvious that the Mayor of Portobelo told us the truth - that they'd be waiting for us here. Which means... All the citizens have left the city with their valuables, and we won't get any profit from this operation. But we still have a chance to get the gold of Escorial and in order to do this, we need the Governor. If he's here in the city, the gold's here too!",
	"Got it. Admiral, you've got a bright mind, you do...",
	"Now go to the Panama residence, and don't waste your time! I have other things to do in the city...",
	"Got you, Henry. I'm on my way.",
	"Go to the residence. Don't waste your time!",
	"Yeah, Henry, I got it...",
	"I bet you did!",
	"Henry, I didn't have a chance. His men were always in the way, covering him.",
	"I got it! So, we'll finish it right here. You can get back to your ship; you are not going to Panama with us. You let me down, and you are no longer a member of the Brotherhood of the Coast. Get lost...",
	"But, Admiral!",
	"Have you found the Governor?",
	"Yes, Admiral, I've found and questioned him.",
	"What did he say?",
	"The gold of Escorial might be in the Governor's office in the residence,but we have no key to the chest; it's locked.",
	"So where's the key, then?",
	"The Commandant has it. I have to take a closer look at the last battleground; I may find the Commandant there. If not, we'll have to look for him in the fort.",
	"Hm, well then, go ahead. I'll handle the Governor. His story seems suspicious to me - the Governor has the chest, the Commandant has the key! Hah, strange...",
	"Maybe, Henry. Well, I'm leaving then!",
	"I see you've manged to carry out the task. You've found the key!",
	"Yes, Henry, I found it. Where's the Governor?",
	"I did him in. It seemed to me he didn't tell you everything; I questioned him to the third-degree. Well, he obviously didn't have the stamina for it...",
	"Hmm... did you at least learn anything new?",
	"Yeah, he knew how much gold there was - 50 million piasters, buddy! But I guess you already know. Go on, loot the barrel!",
	"Here's the money, Morgan... Look, when are we gonna share it?",
	"When we get everything from everyone. I bet our brave pirates have things stashed away in their pockets. I'm gonna make them give it up and put everything together, today. Then, we'll split it according to the laws of the Brotherhood of the Coast.",
	"That's fair, Admiral!",
	"You've already given away all your loot, so you're free from taking part tonight. I've got some work for you in the meantime.",
	"Head to the Panama fort again. There's a chest by the outwall.  You'll find more Escorial gold there. The deceased Governor told me about it...",
	"Hell, I can't believe it! Outside the wall?!",
	"Exactly! The chest is hidden on a steep rock. I'll be waiting for you to bring the gold here, so don't go wasting your time...",
	"All right, Admiral, as you say...",
	"Wow, what an encounter! ",
	", is that really you?!",
	"It's me, in flesh, Admiral. Just want to look you in the eye...",
	"You must be wroth with me. Well, I'm sorry we left you in Panama; I was in a real hurry, you know.",
	"Look, Morgan. You dragged the whole Brotherhood of the Coast to goddamn Panama. In fact, you've destroyed it!",
	"You can say so. You know, life's changing...",
	"What damn life are you talking about?!",
	"Just life, buddy. Do you really intend to board ships and attack cities till the end of your life? Pirates were prosperous only because the great countries were at war. As soon as a treaty is signed and all's peaceful, we'll be history.",
	"Oh, that's already happened! You obviously don't want to be history, do you?",
	"What do you mean?",
	"It's all very simple, you see. You won't be able to do a thing without risking decapitation. I managed to justify the attack on Panama in court, but do you know how it happened?",
	"A good attorney, I'm guessing?",
	"Forget about it! What I did was a big favor to the British Empire. You see, I really cut down on the number of pirates in the Caribbean Sea. Besides, I brought in loads of money to the British treasury!",
	"You what?! Did you take all the money to London?!",
	"Yeah, pal. It was all I could do to save my behind. In fact, I actually paid for my life, your life, and the life of all pirates who want to go on living an ordinary life. Anyway, I'm no longer the Admiral of the Brotherhood of the Coast now. I'm just a plain planter.",
	"So, the position of Admiral is vacant now, is it?",
	"No, you don't get it. There's no longer a Brotherhood of the Coast, and so, there's no longer an Admiral, either. I bought the pardon of the British empire to all the pirates! Those who won't obey will be punished. So you see, life has changed...",
	"It sure has! It's changed completely; everything's turned upside down...",
	"I'd say it's on its feet, buddy... Well anyway, I'm glad to see you safe and sound.",
	"Henry, I'm not going to quit being a privateer!",
	"As you wish. But remember, you're playing with fire!",
	"I'll remember. So long, Henry.",
	"Get the hell outta here!",
	"Out of my office!",
	"Don't mention it...",
	"I'm busy, so please don't distract me with empty pleasantries. Do it again, and I promise you'll really regret it.",
	"I understand, Morgan.",
	"I grow weary of you. Just stop talking.",
	"I don't want to talk to you, so I suggest you don't bother me.",
	"Well, you know...",
	"Hrm, well...",
	"I hope that you'll stop bugging me with empty banter. If you don't, I'll have to kill you, and I admit, I won't feel good about it.",
	"I won't, Morgan.",
};
