string DLG_TEXT_Q [70] = {
	"If you're here for the Admiral, then go a bit farther. He's at the residency now.",
	"Sure, I'll go talk with him.",
	"The admiral's gone to London. He will be here no earlier than a year from now.",
	"Understood...",
	"The admiral's not here. He's gone on business. And don't bother me now. I'm very busy...",
	"If Morgan's not here, then I've got nothing to do in this house.",
	"My name is ",
	". I'm the secretary of Henry Morgan.",
	"My name is ",
	"Listen, I need Morgan - and very quickly.",
	"Monsieur, I would like to speak with Henry Morgan. Where may I find him?",
	"Listen, you handle Morgan's business. Did you ever find any Indian items in captured accounting ledgers?",
	"Oliver, perhaps you'll change your mind about those Indian items that I was telling you about?",
	"Listen, Oliver. I want to ask your help. I need those Indian trinkets, badly. We're talking about three crystal Toltec skulls, and one strange thing that looks like a... well, a doodad.",
	"And who are you, and for what do you need Henry?",
	" My name is ",
	". Edward Mansfield sent me for Morgan.",
	"Dutch? You're Dutch?",
	"What does my nationality matter to you? I've got business for Morgan from Mansfield. What else is unclear to you?",
	"Simmer down, Mynheer. Everything's okay. There are a lot of Dutch among the pirates, but being in Port Royal is not less than dangerous. ",
	"That's why I'll tell you that Morgan's in Antigua, in his house. Be careful there, too. If I see you as Dutch, then that won't be a secret for others. ",
	"And also, it's not easy to get into Morgan's house. Only the exit works. Heh... Look for an underground passage, under Saint John's. That'll take you to Henry.",
	"Thank you, Oliver.",
	"Who are you, sir?",
	"I already answered you...",
	"I repeat, I already answered that question for you.",
	"It's not worth it to annoy me. I won't say anymore.",
	"My name is ",
	". I'm acting under order of the French government.",
	"Yes, correct...",
	"Yes, I remember...",
	"Fine.",
	"And what business does the French government have with Henry Morgan?",
	"Listen, dear, don't you think you're a bit too chatty for a secretary?",
	"Okay, okay, Monsieur... Morgan's located at his house now, on Antigua.",
	"That's great. I'm on my way there!",
	"But, Monsieur, mind you, it's not that easy to enter his house in Saint John's; the door's always locked. You can only enter through the dungeon.",
	"We'll see...",
	"Why all the strange questions?! Maybe I have, but why should I tell you about it?",
	"Calm down. The thing is, I'm looking for three items of the Indian cult. I want to buy them. It's all the same to you, isn't it? You'll either throw it away, or you'll sell it for nothing. I'm ready to give you good money for these things if you have them.",
	"What are they?",
	"An Achcuatsin figurine, a ceremonial knife, and a ceremonial vessel.",
	"Hah, all these things are made of precious metals. We melt them into bars and send them to European jewelers. Such things are in great demand, you know. Bring good money...",
	"I see. I'm ready to give you double the price, but I need them before they're melted... Do you have these items at all? Or is this just idle talk?",
	"I do have them. In fact, I might sell them to you, but you see, double doesn't sound like a serious offer to me. It's too little.",
	"How much do you want?",
	"A million.",
	"What?! Are you mad?!",
	"Not even a little. Do you think I'd really take something from Morgan for double the price?  That's only three thousand. It's you who must be mad here, my friend, if you don't know what the risk is for me. If you don't like my offer, go to the store and try buying them there.",
	"Damn it, Oliver!",
	"All right, enough chit chat. Are you buying them or not?",
	"No way! I can buy the whole of Port Royal with that money!",
	"For a million? You must be kidding. There's no way you can do that.",
	"Fine then. I'll buy them! Wrap them up nicely for me!",
	"I'd buy them, but I don't have the money. I'll go and earn some, I guess...",
	", it's a pleasure to have done business with you. Here are your priceless artifacts! I hope they bring you luck, since you readily paid so much for them...",
	"I hope so as well, Oliver.",
	"I have them. Five million, and you can have them.",
	"Five million?!",
	"Five million... Sounds good!",
	"I have no choice. I'll take them. Here's your money; give it to me, quick!",
	"I really need them, but I don't have the money right now...",
	", it's a pleasure to have done business with you. Here are your priceless artifacts!",
	"Thanks, Oliver! You actually saved my life...",
	"My greetings to Captain ",
	"Listen, Oliver, I'm looking for Morgan!",
	"Er, he isn't here. He's gone to Panama without you. He asked me to tell you that you may enjoy yourself on the beach instead.",
	"Say what?!",
	"That's it! I've explained it to you. You showed up late, and there's no need for you now. Sorry...",
	"Hell! Oh well, it's my fault anyway...",
};
