string DLG_TEXT_Q [220] = {
	"Sorry, I've got nothing to say to you.",
	"Understood.",
	"Hey, buddy! I see you got yourself a ship. You want to make some money?",
	"Maybe I do. What do you need?",
	"Hey, man. Ah, damn! It's too bad that I can't trust you. Too bad...",
	"What's the matter, buddy? I've sullied myself somehow, in the eyes of the Brotherhood of the Coast?",
	"We've got to do a favor for Henry Morgan. If you're interested, come to the Tavern. We'll talk there.",
	"Well, let's go...",
	"Well now, that's not the issue. You're working on a job for Governor-General ",
	". And that's a problem for me, now.",
	"Well, then. A pity...",
	"Listen. Come around later, when your duty's coming to an end. I think I can be more honest with you then.",
	"Sure. All right. I'll keep that in mind.",
	"Hey, buddy... Well, the time's come! Wanna make some money?",
	"What do I have to do?",
	"Aah, so we meet again. But now is not the time. Later...",
	"Aha.",
	"Well, what do you say? Will you help Morgan?",
	"Morgan?! The pirate admiral?! You're asking me?! Of course, I'll do everything I can. Um. That said... what's to be done?",
	"Well, it's simple, really. There's a person who needs to get to Morgan at once. He's been waiting for him too long. You'll crate him to Port Royal. Morgan will meet you there, and he'll pay you.    \n  As you can see, nothing too complicated. And don't forget that you'd be doing Morgan a big favor. Well, you up for it?",
	"Agree! You think I'd decline? A favor to the Admiral! To become the second Morgan is my dream...",
	"Morgan is, of course, a famous pirate, but I've got other concerns, and I don't intend on dropping everything. And anyway, I'm not some longboat courier  cap'n!",
	"That's great! Then John Bolton will be waiting for you at the bay. Don't be flapping your gums around here, though!",
	"I ain't the talkative type. You can count on me. And what, someone's hunting him? Should I be afraid of something?",
	"Danger? Nah. It's just, you know, Morgan has his preferences...",
	"Got it... Well, I'm ready. I'll go meet this John of yours, and I'm gone.",
	"Well, good luck, pal. Fare thee well!",
	"Likewise...",
	"John",
	"Bolton",
	"John's waiting for you in the bay at Puerto Principe. Don't take too long!",
	"Fine...",
	"Hm... Well, that's how it is. Our job is to offer. It's your business to decline. See you...",
	"Farewell.",
	"Good day. Tell me, are you Captain ",
	"Yes, that's me. Are you John Bolton?",
	"Yes, yes. And I need to get to Port Royal, ideally as quickly as possible.",
	"Don't worry. I'll get you there in a flash! Come aboard; we're sailing off right now.",
	"We still haven't reached Port Royal, friend, and I'm in a hurry...",
	"We're getting there. Don't worry.",
	"There's been a tip that you've got the criminal John Bolton on board... Ha! There he is! You're under arrest!",
	"There's been a mistake, officer! I'm carrying that person under the orders of Henry Morgan!",
	"The commandant will sort what's a mistake and what's not... Be so kind as to follow me!",
	"Well, okay...",
	"Are you talking to me, buddy? What do I owe you?",
	"I've brought you a message from Morgan! Give me your hand.",
	"Well. All right. Hang about, what's your name?",
	"You haven't even gotten a bit pale... My name is ",
	"That's why I didn't get pale. I knew you were coming. We've smoothed everything over, Henry and I, so he told me you were coming. So take your message, and go back to Morgan. He's waiting for you.",
	"What do you mean, take it back?",
	"Swift one, aren't you. Anyway. Blow over to Morgan's, and tell him that everything's going according to plan. Got it?",
	"Got it... And what's going to plan?",
	"You don't need to know that... Well, come on, pal. Don't hold me up. Be good!",
	"Same to you...",
	"You're still here?",
	"No, I'm already gone...",
	"Ho! Hey, buddy! I've heard about your adventures! They did a good job on you... Why're you looking at me like that?",
	"Oh, it's nothing... Listen, the owner of the tavern tells me you've been talking to Edward Low.",
	"That's right, I've spoken with him. He's been bitching to me that he's been working on a secret order from Morgan...",
	"You're not the first person Low's taken for a ride... Just what did he want from you?",
	"Well, I just got back from Cumana. Been guarding the galleon there. Low, well, he was interested in the news out there. Looks like he's been planning to go to those parts. And it turns out that you're after him?",
	"Yeah, I'm after him.",
	"Eh, that's a pity. I didn't know a thing about his scummy soul, or, you see, your chase would've ended here.",
	"Yeah, a pity. Well, anyway, it's time to go. Perhaps we'll meet again.",
	"Damn! You've actually found me...",
	"It's you who found me, friend. It had to happen sooner or later. You'll tell me the whole truth now, or I'll introduce your heels to molten steel.",
	"Screw you! Haven't you thought about who you are? A damned lackey! A dog doing tricks for Morgan.",
	"I'm completing an order for the admiral of the Brotherhood of the Coast!",
	"Of course, where would we be without Henry?! Anywhere you spit, you'll hit Morgan...",
	"And what's so bad about that? The pirates chose him as their admiral!",
	"Well, I didn't choose him! There are plenty of people unhappy with Morgan, and our time will come.    \n Anyway, I see no point on shooting the breeze with you. To arms, hairy mongrel!",
	"Before you die, I'll like you to know that the reason for your death is that brig.",
	"What?!",
	"You'll die for stealing that brig from Jackmann.",
	"Ha! I'm imagining Jackmann's mug when he found out that his brig went bye-bye...",
	"Good. Got a nice, solid picture? Well, that's enough for now.",
	"Hey, man! Great that I've found you! If you aren't in a hurry, let's talk! I've got another proposal for you. Help me out, here.",
	"Uh... If you're serious, all right. What's up?",
	"I don't want to beat around the bush. Here's the deal. \n As you understand, I work for Morgan. But aside from that job, I've got another one - my day job, if you will. I'm a head hunter. 'Til now I could let both jobs co-exist, but now, alas, that won't work out. I've received an order from someone who I can't refuse...",
	"Come on. If I can help, lay it on me.",
	"The problem is that I'm needed now at Port Royal, and Morgan doesn't want to let me go. So I can't complete the order at all... Can I prevail upon you to take my order?",
	"And you can't just refuse?",
	"If everything could be solved so easily, I wouldn't have asked you. Make up your mind. You can take the full reward from the client.",
	"Hm. Not a bad bonus. Fine. Consider it a deal. Let's get more details, though. What's the order?",
	"A man named John Ivory needs to be eliminated. He hangs around, shaking out debts for the moneylenders. An insolent mongrel, which, anyhow, doesn't keep him from finding clients. ",
	"He was last seen in Willemstad. I don't know if he's got on the bad side of a client, but he's put up fifteen grand for John's head.",
	"Hot damn! And who's the client?",
	"Sorry, buddy. That, I won't tell you. The client wouldn't like that. Well, have you changed your mind?",
	"I didn't change my mind. Order accepted!",
	"Excellent! I'll be waiting for you at the city. Good luck!",
	"Have a happy time staying here! And I'll meet you soon!",
	"Money! And let's do this nicely, or my dagger will taste your blood!",
	"Ha! Want to take it?! Screw you! I keep what I earn!",
	"Nobody asked you! Get out, while you still can!",
	"I can't. I've got an order for both of you. So you'll die now. Both of you.",
	"Ha! And they say I'm insolent. Well, we'll now see what you're made of...",
	"We'll check...",
	"Who am I seeing, but ",
	"! You're back after all! I'll admit, I've been waiting...",
	"Yeah, the search took a bit longer than I expected. Though everything turned out okay!",
	"Ha! I can't tell you how happy you've made me! It's like a mountain has lifted from my shoulders... I've got your reward here, so here. Take it. 15,000, like I promised. No tricks. You've done well. This deal will add to your popularity among pirates.",
	"Yeah, these are my hopes. To become like Henry, an admiral of the pirates... That is my dream. Ha! I've got to tell Henry about this adventure.",
	"And what's Morgan got to do with this?",
	"Oh, nothing. But you know, I want him to know of what I'm capable!",
	"Ha. Well, well...",
	"Something amuses you?",
	"I'm not laughing. It's just, I still don't understand what Morgan has to do with this.",
	"Oh, nothing at all. Anyway, be well. I'm off!",
	"Greetings, to a member of the Brotherhood of the Coast! To what do I owe the pleasure of seeing you at my deck?",
	"Hello, John. Jackmann sent me to you.",
	"Very well. What's your full name?",
	"Hah! I can't believe it! Who did we block up inside the bay then?",
	"I've no idea. But I really am ",
	". Tell me more details. Who did you block up, then?",
	"It all started when poor Stede Bonnet's schooner was boarded by a corvette, whose captain was a privateer named ",
	". Maybe he was your cousin. I don't really know.",
	"He gave Bonnet away to the Spaniards. They immediately strung him up in Havana's city square. It was a sad end for the pirate; I wouldn't wish it on anyone...",
	"So then what happened to my namesake?",
	"We caught up with him here and sank the corvette, but the crew managed to disembark from the sinking ship.   \nThose devils are armed to the teeth, and there are many of them. It's hard to disembark in the bay. The number of people in the boarding crew wouldn't make a difference.   \nMy men don't want to risk such a thing since Stede is no longer alive. Besides, you can't make money off this operation.",
	"And what do you suggest?",
	"Well, it seems to me you must be the one to deal with the problem. Find out what the hell cousin or brother you have is there, otherwise... You'll see yourself you're gonna have problems, and the further it goes, the more obstacles will arise.",
	"The thing is, there are people in my crew who'd seen you before, and they're pretty sure they saw you on that corvette. That's it, buddy!",
	"Hah! Well, well, well! Maybe you'll give me a hand here?",
	"The only help I can promise is to make sure these men stay if you need to go somewhere.",
	"Fine, then. I guess I'll have to speak to those friends. I'll go and see what everything's about...",
	"Very well. Go on, buddy. I'd really like to know will come of it...",
	"Heh, me too, pal, me too...",
	"You haven't dealt with your 'cousin' yet, and I can't wait here for you forever...",
	"Got you, John...",
	"Hah! So it's you ",
	"! Good to see you, brother",
	"What?! I'm no brother to you!",
	"Well, I was just trying to be friendly...So, have you decided to get rid of me?",
	"Yeah. Go on; tell me everything. Who are you? Where are you from?",
	"Will you let us go, then?",
	"Only to hell, brother!",
	"Then I'll you nothing. No point, see...",
	"Ugh! Well, as you wish...",
	"Glad to see you on my ship.",
	"I'm looking for Steve Linney. They say you're pals; they saw you together in the tavern.",
	"Hm... What do you need him for?",
	"Hm? Oh, the name's ",
	". I'm here on behalf of Morgan. Steve hasn't come back for a while, and since he was gathering information for Morgan, Henry sent me to find him.",
	"A-ah, yeah, I know Steve; he told me about his job. Well, in brief, he couldn't find anything in La Vega. Although... He was to meet a man here who knew something, but you see, the guy never showed up. Steve was heading to another city when two strangers approached him. They talked and he left with them.",
	"It was all fine and dandy to me until I learned yesterday that his schooner, Swallow, was on sale in the Santo Domingo shipyard. You see, Steve really loved his ship. He would never sell it himself. So I figured it wasn't a good idea to stay in La Vega anymore and decided to leave the place. If I wait too long, they might come for me, too...",
	"I see. Maybe he really sold it himself, who knows? Though, it does look strange...",
	"Yeah, that's true. Well, I'm through with this business. I wanted to help Steve, but now I don't even know what to think of all this.",
	"Got you. Thanks for the information, buddy. Good luck.",
	"We've discussed Steve already. I don't know anything else...",
	"Yeah, yeah, sure.",
	"What do you want from me?",
	"Tell me who you work for! What did you do to the Captain of the Swallow?!",
	"The Captain of the Swallow is feeding the fishes now. Curiosity killed him, you see. Ha-ha-ha!",
	"Damn! Tell me, who do you work for?!",
	"I work for the Admiral of the Brotherhood of the Coast. Not that buffoon Morgan, but the true Admiral, OUR Admiral, Richard Sawkins! Join us, buddy! We're in need of men like you.",
	"I have no reason to think that Henry Morgan isn't the Admiral. The Brotherhood of the Coast chose him.",
	"Did you choose him, personally?",
	"No, but...",
	"Keep these 'buts' to yourself, pal! I didn't choose him, either. And by the way, we're both pirates. Morgan is a smart fellow, but he isn't as fair to us as we're made to believe...",
	"I don't give a damn what you think! Morgan is the Admiral! Period!",
	"Idiot! You'll be sorry...",
	"Heh, yeah, sure...",
	"You know, ",
	", I didn't make a mistake when I joined your crew. As a result, you see, I'm still alive and I'm in the occupied Panama! Who would have thought it?",
	"Yeah, we must get a lot of money from this operation.",
	"We're already looking for something to grab!",
	"And you're right.",
	"Oh, it's a pity our captain died! A fine man he was, Richard Sawkins!",
	"D'ja think so?",
	"Sure! I was under his command for more than a year. He was a fair fellow!",
	"Hmm, I see...",
	"I heard you also got into trouble! Morgan and I were heading to Panama from Portobelo.",
	"Well, yeah. The Spaniards set up an ambush everywhere.",
	"It was the same for us. Complete hell...",
	"Well, we handled it, so keep your head up!",
	"What do you want from me?",
	"Hello, respected citizen. As far as I understand, you're the Governor of Panama...",
	"Exactly right.",
	"I want you to give me all of Escorial's gold. I know you have it.",
	"Hmm, well try and find it, then...",
	"You're playing with fire! Henry Morgan took over Panama. The pick of the Caribbean pirates gathered here. Can you imagine what might happen to you?",
	"I can. But I still can't help you.. You see, there's a chest that has something you might be looking for, but I don't have the key to open it... I'm talking about one of the chests in this room.",
	"So where's the key, then?",
	"The Commandant keeps the key at all times. Military authorities guard the chest, not us city heads.",
	"Where's the Commandant now?",
	"No idea. He was managing the city defense as far as I know. He attacked the Ladrones from the fort's side. It was necessary to defend Panama; that's why there was no one left to defend the fort.",
	"So he might be dead or at his fort?",
	"Mind you, your life depends on whether we can open this chest or not.",
	"I understand. But I can only hope and believe in my luck.",
	"I'll go look for the key. As for you, stay put and think of something that may be of use to us...",
	"If I do, you'll be the first to know about it. It's in my interest, too.",
	"Um. Sure, okay.",
	"Damn! Henry cheated us!",
	"Did you hear what Morgan did? It's unbelievable...",
	"We'll all be history here. We have to get out somehow. Everyone's saving their own skin...",
	"Yeah, I heard...",
	"Hell!",
	"May I drop dead!",
	"You're right on time, Captain! It's a pity you were absent earlier...",
	"What happened?",
	"Hah! The news is so joyous, you may go mad with glee!",
	"Go on, cut it short.",
	"Our Admiral, Henry Morgan, gathered all our loot! He lined up the pirates. And he turned out his pockets first, putting everything in the common stock!",
	"So what? I knew about that. What's so great?",
	"Nothing's great about that, but that's not all... We put all our money in the common stock and left to attend to our business, believing Henry was going to split everything according to the Law of the Brotherhood of the Coast. But our brave and honest Admiral quietly boarded a Spanish galleon and sailed away.",
	"What? What about the money?!",
	"Our money sailed away with Morgan! That's what I was saying - Henry took the win and deserted us here, in goddamn Panama!",
	"That can't be true... Just can't be!",
	"Hah! It's a fact, Captain! What shall we do now?",
	"Hmm, damn it... If that's the case, we're all stuck here without any food or money. We're done for.",
	"Oh, if only Sawkins were alive... Nothing like this would have happened, that's for sure! What a captain he was, a real Admiral!   \n Damn... Richard warned us so many times that Morgan would betray us, but we wouldn't believe him. We just wasted our time...",
	"What do you mean 'wasted'?",
	"Exactly what I said! Sawkins wanted to become the Admiral of the Brotherhood of the Coast, but we talked him into waiting a bit for the election and to not raise any questions. Caramba, we were so wrong!",
	"Yeah... And I was no less wrong than you were!",
	"Yeah, you and Morgan appeared to be real pals. I can't believe he's deserted you here, as well...",
	"Well, what's the use of crying now?! We must rally all the pirates who are still alive. We'll gather all food, powder, and bullets, and head east to our ships.",
	"Through the jungle again? No, not again; I won't survive a second time. And by the way, nobody will join you. Everybody knows you as Morgan's pal! If you speak one word of rounding something up, I bet you'd take a bullet to the head!",
	"Ay caramba!",
	"Everyone's saving their own skin, Captain... Well, I don't really have time to chat with you here. I'll go to the tavern. Hope they still have some rum left there.",
	"Go on then.",
};
