string DLG_TEXT_Q [184] = {
	"Happy",
	"",
	" to see you again. Did you want something else?",
	"Oh, you again? We've already talked today. Something changed?",
	"Hm. Perhaps that's enough of bothering me without cause?!",
	"Brr... I'm getting nauseous from your body already...",
	"No, nothing of the sort...",
	"No, everything's normal.",
	"Yes, of course. Sorry...",
	"Hm. That's a shame. I've got a body you can't beat. I'm proud of it!",
	"I don't wish to speak with you. Goodbye.",
	"Heh. I don't need it.",
	"Hello, Captain. Do you want to talk about something that will interest you, without a doubt?",
	"No, not interested. ",
	"And how do you know what might interest me?",
	"Rumors, ",
	". The world is full of them...",
	"Well, come on, then. Let's talk.",
	"I presume that you'll be interested in the location of one item that you really need.",
	"Without a doubt.",
	"Very good. But I must be sure that this item will only enter the hands of one who will use it correctly. I promised that to someone. That's why I'm asking you to answer one question. I need to confirm that you're really the person I need. Agree?",
	"Ho! All right. I agree.",
	"Find someone else to be sure of. I pass.",
	"In that case, listen to the question. ",
	"Correct answer! You're quite the seaman.",
	"Hey, you're telling me! So tell me what you've got for me.",
	"Wrong answer. Have yourself a think, and try again. ",
	"Yeah, I'll give it another shot.",
	"Mm... Nah, I don't know the answer to that question.",
	"It's a decent light blade - a German rapier. But I don't have it, myself. I just know where you can find it. Go to the pirate settlement of La Vega, and take a look to the left of the gate. The weapon is stashed in the ground there. Good luck!",
	"Okay, I got you. Thanks for the help.",
	"Very good! Then I'll repeat the question. ",
	"In that case, I regret to report that I am unable to grant you that which is meant for a great seaman. \n I am, however, prepared to hear your answer at another time, should you look me up. I'll remain in this city for a little more than a week. ",
	"Fine. If I find out the answer, I'll just try again.",
	"Oho! Here you are again. Have you found the answer?",
	"Yeah, I think I'm all clued-in now. ",
	"Hello, Captain. I've got a small matter for you.",
	"I don't want to speak.",
	"You don't say! And what's this mysterious matter?",
	"I'll ask you not to be ironic, sir! I am the widow of a filibuster!",
	"Ah, yes. Forgive me. So what business do you have with me, ",
	"At one time, my husband and I lived at Puerto Principe, yet he left for a prize and disappeared...",
	"That's so sad.",
	"Mm, you don't have to tell me. \n So, well. I still have some of his things with me, and surely one of them will be handy to a captain like you.",
	"Understood, my lady. I'm ready to buy it off you.",
	"No, it's not for sale. It's a memento of my husband! It's just, I don't want it to lay around, gathering dust, I want this item to be useful to a real sailor.",
	"That's why, if you forgive me, I'm offering you a sort of a quiz, to get an idea about you as a specialist.",
	"Hm. Well, all right. Fire away.",
	"Yeah, like I've got nothing better to do. No, dear, somehow I'll manage without.",
	"Very good. Now, captain, here's my question. ",
	"Excellent! That was the right answer!",
	"It can be no other way... Now, to business. What's this item that I'll be needing?",
	"Incorrect. That's the wrong answer to my question. I can let you try again, if you like.",
	"Yeah, I think we'll have to do that.",
	"No, I don't want to play guessing games.",
	"It's a respectable spyglass. I buried it in the ground of our former house, on Puerto Principe, to the left of the residence.",
	"Understood. Well, thank you, and farewell.",
	"Fine. I gather that I have to repeat the question. ",
	"Suit yourself. Farewell, brave Captain...",
	"Goodbye.",
	"I don't get it! What else do you need?",
	"I want to try that riddle of yours again, ",
	"Hello, Captain. I have a proposition for you.",
	"I'll do without your proposition.",
	"I'm listening to you closely, ",
	"You know, it just so happens that I've come into possession of a certain item, that seamen typically seem to need. At least, they'd need it more than a girl! ",
	"And what is it?",
	"I want to give it to you. But not for free, and only if I'm sure that you'll use it correctly, instead of hawking it at the first opportunity. ",
	"Hm. So tell me, ",
	". What is this item? Identify it, and I'll give it to you.",
	"I know that every able seaman needs one of these. \n I'll ask you one question, and if you answer correctly, you'll receive this item.",
	"Damn! What is with these damned pop quizzes all the time? Let me just pay you, and be done with it.",
	"No, Captain. I ask, you reply. Agree?",
	"Well okay, I'll humor you.",
	"No, I'm not interested.",
	"Very good. All right, Captain, here's my question. ",
	"Wonderful, Captain! That's the correct answer!",
	"Of course, I'm no specialist... So what's this item we're discussing? ",
	"Hm, that's not so, Captain. I'm afraid you're mistaken. Shall I repeat the question? ",
	"Noting ventured, nothing gained. Let's try again.",
	"No, dear. That's more than enough. I don't want to play these games anymore.",
	"It's a wonderful medium-weight dagger, by the name of 'Hurricane.' It's hidden in a dead end, in a dungeon beneath Tortuga. You'll have to search yourself.",
	"Sure, I'll take a poke around. Why not. It's worth having a good dagger in battle. Thank you.",
	"Yes? Then here's the question again. ",
	"Oh, no? Well, farewell. Tell me, how does such a hack fare as a captain?",
	"Hey, hey. Easy, now!",
	"What do you need? I think we've discussed everything.",
	"You know, I think I know the right answer.",
	"Greetings Captain. I want to offer you something.",
	"No, that doesn't interest me.",
	"I'm listening to you closely, ",
	"I've got one thing that captains really need, that will, without a doubt, interest you.",
	"I'm listening closely. What're you talking about?",
	"It's a paper I received on a particular occasion with certain conditions. I must present it to a captain who is in need of it and is worthy. And I need to do it as soon as possible.",
	"Really? So, where's this mysterious paper?",
	"I will tell you once you answer my question.",
	"Question? About?",
	"Just a general topic known to all captains. I need to know the man I'm dealing with really well.",
	"Fine then, go on with your question.",
	"I don't wish to answer any stupid question.",
	"Very well. So, Captain, here's my question. ",
	"Perfect, Captain! You're absolutely right!",
	"So... Where's this mysterious paper, then?",
	"No, Captain, you gave me the wrong answer. Think, and try to give me the right one.",
	"Let's try again...",
	"No, I'm fed up with questions.",
	"It's a ",
	" for forty-day's time! I'm happy to give it to you.",
	"Wow, that paper's quite expensive! Well thank you ",
	", for all your help. Goodbye.",
	"Wonderful. I guess I'll have to repeat my question. ",
	"Fed up, you say... Well, goodbye then, Captain...",
	"All the best to you.",
	"I'm listening to closely, Captain. Have you decided to try answering again?",
	"Yeah, I guess I know the right answer.",
	"My greetings to you, Captain! I have something for you. Do you have a minute?",
	"No, I don't.",
	"No problem. Take your time.",
	"Very well. Here's a small deal for you - I have something that might be of interest.",
	"Tell me what it is and set a price.",
	"No, I won't take money for it. You just have to answer one question. If you give me the correct one, it's yours.",
	"Very strange... Hmm. You don't need money?",
	"Heh, everyone needs money, however, only your knowledge will assist you in this bargain. I don't want to explain further, so just tell me yes or no.",
	"Hm, I guess it'll be yes. You've intrigued me.",
	"No, no, no. Goodbye.",
	"Heh, your first answer was right. Now, to the main event of the day for you - listen to my question! ",
	"Great! That's the right answer!",
	"I bet it is... So what am I the happy owner of now?",
	"I'm very sorry, Captain. Really sorry... You gave the wrong answer! Will you try again?",
	"I will!",
	"No, I don't think so...",
	"It's a statue that will give you great opportunity to better fix your ship. It's hidden in a bay near Portobelo. The bay is called Chirico Lagoon. Take a good look there and don't be afraid to wet your feet. Good luck, Captain!",
	"You know, that will be very useful. Thanks!",
	"Well, I'll repeat the question then! ",
	"As you wish. Goodbye, Captain Ignoramus...",
	"Er... What?",
	"What do you want from me?",
	"I want to try answering your question once more.",
	"Good afternoon, Captain. I suppose you're the one I need...",
	"I don't think so.",
	"What's the matter, ",
	"I want to offer you an exchange. The point is, I have something I don't need, but I bet you'd find it useful.",
	"What do you want in return?",
	"Nothing special. I just need to know that it's in good hands.",
	"So you should know then that it surely will be in trustworthy hands. Have no doubt.",
	"I believe you, but regardless, I must make sure. If you answer my question correctly, you may have it.",
	"Go on with your question! I thought it would be more difficult!",
	"Thanks, but no thanks.",
	"Well, the question's rather simple. ",
	"I had no doubt you'd give the right answer.",
	"Sure, what else can I do? What do I own now?",
	"Wrong answer, Captain. I need the right one. Another try?",
	"Yeah, I guess I'll try again!",
	"No, thanks. I don't want to play a guessing game.",
	"It's a heavy marine officer backsword. You'll find it in Portland bay in Jamaica.",
	"Yeah, that'll be useful in a fight. Surely a woman doesn't need it. Thank you.",
	"Fine, I guess I'll have to repeat my question. ",
	"As you wish. Hm, you really looked like a serious captain at first...",
	"What do you mean?",
	"Sorry? I don't quite get what else you want.",
	"I want to try answering your question once more.",
	"Welcome to Santiago, Captain! I have something to talk to you about. Do you mind?",
	"I don't wish to talk.",
	"Go on. I'm listening to you.",
	"Wonderful! Let's get to the point then. I actually have a bargain, or an exchange offer, that is, if you're interested...",
	"I am. I'd like an exchange! Let's do it.",
	"Oh well, let's. I'm offering you something real useful. All I need from you is an answer to my question.",
	"What question?",
	"Oh, it's just a general question in your field. Look, I just need to check your knowledge. It's a very important condition. Are you in?",
	"Hm... Though I don't really get why you need it, I'm in.",
	"Heh, find someone else. Get lost while it's not too late...",
	"Perfect! So here's my question ",
	"Great! That's the right answer! Congratulations.",
	"Thanks. I'm really glad. To make me happier, let's get the point of our bargain...",
	"Hmm, Captain, that isn't the right answer. Please try again...",
	"Of course. I'll try.",
	"No thanks. I'm sick of it.",
	"It's a double barrel pistol! You'll find it in a grotto in Cuba. To get there, you'll have to leave town and journey across the jungle. You should really agree; it's a highly recommended weapon for you.",
	"Yeah, I won't say it's not. Well, I guess I'll have to take this journey. Thank you and all the best.",
	"Wonderful! I'll repeat the question. ",
	"No, you say? You're sick of it?! Hm, but it has to do with your professional field! Oh well, I don't care. Goodbye...",
	"All the best.",
	"How may I help you?",
	"I want to answer your question.",
};
