string DLG_TEXT_Q [16] = {
	"Talk to our captain. I've got nothing to say to you.",
	"Um, sure. Okay.",
	"Talk to our captain. I've got nothing to say to you.",
	"Um, sure. Okay.",
	"Would you look at that, he came himself... Well, since you're here, you might as well talk to the Cap. You can roll around about your sorrowful deals there...",
	"Ha! You're really something, bud! I haven't seen that yet... Go to the Captain. He'll speak with you.",
	"A pity...",
	"Talk to the boss. I've got nothing to say to you.",
	"I'm on duty here. If you have any questions, go see the Commandant of the fort.",
	"Um, sure. Okay.",
	"I'm really busy now. Leave me alone.",
	"Don't bother me. I'm working. We've nothing to talk about.",
	"That's too bad...",
	"Morgan wanted to see you for a few 'nice' words... He's here on the deck somewhere.",
	"Heh, go and find Morgan. There's bad news for you... ",
	"Um, sure. Okay.",
};
