string DLG_TEXT_Q [97] = {
	"Nothing to say.",
	"Okay...",
	"Who are you, Señor?",
	"To hell with talking. I'm going to free you now, and we'll chose an anchor. Or do you enjoy indentured servitude? Pull yourself together, and head to my ship. Don't attract any undue attention. Your goal is to reach my ship alive. In a moment, I'll start a diversion to smooth things over for you. You got all of that? ",
	"The Lord has heard our prayers!",
	"If only you knew how happy we are to see you...",
	"It's all thanks to the Señor Governor-General! He hasn't forgotten about us...",
	"Yes, yes... But I ask you, don't say peep until we bust out of here...",
	"You're bested, you cursed Castilian.",
	"It's very good that you're chosen to surrender. I'm not just here on a whim, but rather with an offer.",
	"What did you want, monsieur? The master is not at home.",
	"Understood...",
	"What did you want, monsieur?",
	"I need your master, Henry d'Estre.",
	"Monsieur, you must hurry!",
	"Yes, I understand.",
	"Dammit, be so kind as to explain yourself at once! Why are you following me?!",
	"I needed to talk to you! I'll ask you to excuse me, monsieur...",
	"Well? What do you say, you Catalonian beast?",
	"Today we finish our long feud with the buccaneers. You will all be destroyed, and Hispaniola will be for Spaniards alone!",
	"Yeah? Whatcha need?!",
	"Oh, nothing special. I just wanted to give you a few coins. Clearly you're suffering, so you'll want to get your health back in shape...",
	"What do you want?",
	"I'm a trusted official of the governor-general of Curacao. I have to speak with you. Let's go to the tavern, have a chat...",
	"I want you to give me that diplomatic correspondence. And let's do it quietly, lest I feel inclined to expose your intestines.",
	"I'm told that a trusted official from Stuyvesant is waiting for me here. Who are you, and what do you need?",
	"Who I am is unimportant. I need your papers.",
	"Dammit, this is no time for politics! I'm being attacked by Ladrones! Help me!",
	"Fine.",
	"Golly, you showed up here just in the nick of time! I don't even know what I would have done without your help. Tell me, to whom do I owe my salvation?",
	"My name is ",
	". And I was sent to save you, actually, by Francisco Oregon y Gaston. He became aware that a squadron of French bandits has been sent after your hide.",
	"We talked, and that's enough...",
	"Agreed...",
	"Out of the way!",
	"Easy, dear. Where are you off to, in such a huff?",
	"Yes, Señor. Thank you, and may God protect you!",
	"Amen! Well, hurry up then...",
	"What's the proposition?",
	"To meet monsignor Antonio de Souza.",
	"I don't know the man. ",
	"He's a very important person in the Holy Inquisition. One of the fat cats. So you're in luck.",
	"Ah, curses. I regret surrendering. It would be better to die in battle than to die suffering...",
	"Possibly. But it's time now, and they can't wait to see you at Santiago.",
	"He's here on the street, right by the house. He was in a real rush somewhere, but a moment ago a familiar filibuster stopped to talk with him. They finished up quickly, and he ran off to tend to his matters. So if you want to reach him, hurry up.",
	"All right, I'm hurrying... ",
	"Fine, I apologize... To whom do I have the honor of speaking?",
	"My name is ",
	". I've come to you to learn the identity of this Doña Anna, who you delivered to Monsieur d'Ogeron. ",
	"You, mister, are sticking your nose somewhere you shouldn't - it's none of your business, and it might end badly for you...",
	"I know. Regardless, I'll repeat my question: is Doña Anna the wife, or I should say the widow now, of Havana Commandant Don José Ramirez de Leiva?",
	"She certainly is. Why?",
	"In that case, mister, I'll have to kill you.",
	"Quite blunt you are, I'd say. But why kill? As far as I know, I haven't done anything to you personally. Don't think that I'm scared or anything. I just need to know the reason you're here.",
	"It's quite simple - the laws of honor. You dared to take something that doesn't belong to you - another man's woman. And you killed five men in the process!",
	"Ooh, you're well informed of my adventures! You even know how many Spanish devils I sent to the world beyond... I'm impressed. So who are you, mister?",
	"I'm a Spanish privateer and I'm here to investigate the murder of the Havana Commandant and the disappearance of his widow. And one more thing - I'm also here on behalf of Havana Governor-General Don Francisco Oregon y Gascon.",
	"Aha, everything's clear now! I can send you to the world beyond without remorse. Defend yourself, mister!",
	"Certainly!",
	"Ugh, you Spanish dog! An old buccaneer won't give up his life easily...",
	"Yeah, it's time to end it...",
	"O-o-oh, it's important! Give me the money...",
	"Do me a favor first, and you'll get your money.",
	"Oh well, I thought... Er, what should I do?",
	"A Dutchman will leave the residence in a short while and head for the port. You need to tell him that I act on behalf of Governor-General Stuyvesant, and that I'm waiting for him in the tavern in the room upstairs.",
	"How much will you give me for this?",
	"Hm, you can count on a hundred at least.",
	"A hundred coins on the barrel now and I'll do everything, otherwise I won't be able to start. I've got a terrible hangover...",
	"Here's your money. Get going. I'll be waiting.",
	"Don't you worry, mister. I'll grab a drink, and everything will be just fine...",
	"Hurry up with your drink or you might miss him, the orderly. And remember, I'll be waiting for the Dutchman upstairs in the tavern!",
	"Hmm, okay. Try then...",
	"Ugh!",
	"If you want to tell me something, spit it out here and now.",
	"You again? I told you I'm not going anywhere!",
	"Enough! I'm fed up with you... Guards, get him! He's a spy!",
	"Let's go to the tavern...",
	"Listen...",
	"Why?!",
	"I'm not going to any tavern. Go on. What is it you want from me?",
	"You know... Er...",
	"I see... I guess I'll report to the people at the port about your strange behavior... I bet it won't be easy for you to leave the city now.",
	"Hmm...",
	"It's diplomatic correspondence; you're running a great risk...",
	"I know, but if you don't give it to me of your own free will, I will remove it from your dead body. The choice is yours: life, or papers?",
	"Both - life and papers! I'm choosing both! I suppose I'll have a look at the color of your blood as well.",
	"Hm, as you wish...",
	"So I owe him the same way I owe you. Very well, then. I'll need a chance to thank him.",
	"Perfect. Well, I suppose I have to make my way to Havana to meet its Governor-General and tell him about my success.",
	"I guess I'll stay a bit longer in these waters. I might get lucky here...",
	"Good luck to you, Manuel. Goodbye.",
	"The British!",
	"What did you say?",
	"I said - there's a squadron of British pirates approaching the city! Damn, we'll have to fight! We've not been preparing in vain...",
	"It seems I'm right in time...",
	"What? Ack! Let me go, Señor... I need to inform the Governor-General...",
	"Go on then, officer.",
};
