string DLG_TEXT_Q [59] = {
	"I've got nothing to say.",
	"Okay...",
	"Are you the man with the assignment from Antonio de Souza?",
	"Yes, I've just come from him.",
	"I give up! You've won!",
	"Joseph Nunes da Fonseca in the flesh, if I'm not mistaken...",
	"What do you need here? Spill it!",
	"Hey, easy! What manners!",
	"Who are you? And how do you know me? Are we familiar? How did you find out where I am?",
	"Stop! Stop, my lord. I'll tell you everything. Just let me free you, first. I don't think you'll be against that?",
	"Monsieur, the head of the port sent me.",
	"Yes, very good. What did he want to pass along to me?",
	"Damn! Everything began so well. We captured Pardal... But now you've shown up...",
	"Hm. Well, I showed up so that your great beginnings wouldn't end too greatly...",
	"Argh! Cursed Spanish dog!",
	"Let us continue, Captain. Let's not get distracted...",
	"I know what the goal of your mission is, and I know how it can end. The Order profits by using merchants to tighten up its financial matters - all the better when it's by someone else's hand.",
	"You think that the whole story?",
	"Possibly not, but you must remember one thing - if you're faced with the question of killing merchants, then I ask you to consider very carefully for what you're taking these people's lives. You don't know them. They could be devout believers and well-behaved citizens.",
	"How can they be devout believers if they're Jansenists?",
	"They believe in the same Lord as you and I. Think about it...",
	"I've taken your words into account. But with whom do I have the honor of socializing?",
	"Francisco de San Augustinio.",
	"Thank you, Francisco. All the best.",
	"That's so... And how do you know me?",
	"A girl told me. Name of Tanneken Clemens. You know her?",
	"Damn! What these girls don't do to get married! Isn't that something, hiring some cutthroat!",
	"She didn't hire me. Our interests merely coincide, at the moment.",
	"Ha! Well, that's some consolation... You know, it's a bit too soon for me to have a family. And what do you need from me?",
	"From you, nothing. I do need something from your father, though. You'll spend some time in my hold, to think about family, kids, unchanging human values... And your pop and me will have a little pow-wow.",
	"Not the worst outcome for me, you see. Thanks for, well, leaving me alive.",
	"Thank Tanneken. She asked me not to touch you, rascal... Well, that's it I guess.",
	"Get lost, I say. Or do you not value your life?!",
	"Hmm, something's wrong here... I'm not going anywhere until you answer my question. What are you doing here? Can it be Rabbi Jacob Lopez da Fonseca you're keeping as a prisoner?",
	"Well, well, well... I think it's time you joined your ancestors, chatterbox...",
	"It's not your duty to set my life span...",
	"Of course it's not. It's just... I'm worried a bit. I do not hope to be set free, you see, and I don't believe in miracles. I heard the thugs discussing my ransom and one of them is probably in Curacao already.",
	"But how did you manage to get here so soon? And, er, you haven't told me your name yet.",
	"Um? Oh, the name's ",
	", at your service. My ship's waiting for us in Portobelo; we can get going.",
	"I don't want to bother you more than I should, but having seen you deal with these people, I realize you must have been in the military. I want to ask you for a favor.",
	"You can do it on the way from here to Curacao. I can't insist, of course. I can only ask that you do it. Our community used to have something in its possession, an ancient Christian relic - the Gospel from Judas.",
	"Used to have, you say?",
	"Yes. It disappeared some 20 years ago along with its keeper, Samuel Coheno.",
	"That name, I've heard it somewhere before...",
	"I don't think so. Not long ago, we found the thief in Bermuda. He wouldn't sell us the relic, so we hired sailors from a tavern. The thief turned out to be quite strong; he even wounded some of the sailors and ran off. They followed him to the shipyard, but once there, it seemed he had simply vanished into thin air.",
	"How so?",
	"He entered the shipyard office and disappeared. It's a complete mystery where he had gone to. The keeper of the shipyard wouldn't tell us anything. So, I'm asking you to help me get this book back. Will you?",
	"What do you think might be the price of this book?",
	"It's priceless! Why are you asking?",
	"I know it's the duty of every Catholic to protect Christian relics... But I haven't made up my mind yet. We'll see.",
	"Thank you!",
	"Nothing to thank me for, yet.",
	"The ship you're waiting for has cast its anchor near Tortuga. The orderly, that Dutch officer, is with d'Ogeron now. You can meet him later at the entrance to the residence.",
	"Great! Thank you for your service.",
	"Don't mention it. Thank the head of the port.",
	"Hm, I'll certainly thank him.",
	"Well, you've succeeded, I must say... We've had our rest. Let's continue now.",
	"With great pleasure...",
};
