string DLG_TEXT_Q [82] = {
	"Decided to take a ride on the quarterdeck, Cap? Well, that's good... enough laying unconscious in your cabin! How you feeling?",
	"Beta Test: Pass, and begin game.",
	"Hm... I think I'm rather healthy. Still, I can't seem to collect my thoughts... What did you call me? 'Cap'?",
	"Well, yeah! Who else?! I guess after that concussion, everything must be mushed around in your head...",
	"Concussion? True, my head is spinning...",
	"Come on, now! When the old Cap, the lucky boy Johan Tomtit - immune as he was to bullets and sabers - was crushed by a mast in that glorious battle where we hit upon a patrol of ",
	", you kept your head and took command into your own hands. And you ordered us to clear out. So the team, or what was left of it anyhow, unanimously elected you the new Cap.",
	"But... Oh! I think I remember that I ordered a maneuver to strategically distance ourselves from the enemy!",
	"That's it, Cap! The sailors fell right in line, and started climbing the shrouds to pull off the maneuver. It's lucky that we picked you up at ",
	", after you came in from Europe. If it weren't for you... Well, without a captain we'd have been feeding the sharks long ago. And you were wounded by a bomb explosion, when we were hit broadside during the retreat.",
	"Yeah? So what's wrong with me? My hands and feet seem to be in place.",
	"Of course they're in place. We don't have a doctor, but the sailor serving as one patched you up as well as he could. Want to check?",
	"Yes, I want to check my health. (Create your type of hero.)",
	"No, I feel fine as I am.",
	"Well then. Everything's in order - as you can see yourself. But that last injury and long downtime may have affected your skills. And we need a Captain who will make us rich! Do you want to practice fencing, and stretch your arms a little?",
	"Yes, thank you. That would be useful.",
	"No, I don't want to. I'm wielding the sword well enough.",
	"We've already arrived at ",
	", and now it's up to you to prove how soon we can be sure it was no mistake we staked our lives on you.",
	"Wonderful. All right, men! I'm going ashore.",
	"A few hints, before I go ashore?",
	"Well then, Cap... You've got to patch up the ship, reinforce the crew, and refill the supplies. And forward, en route to adventure! It's better, of course, to get a privateer license. That way, we wouldn't fall foul of the law, even if we were to become pirates, and we could honestly tell our families that our work was legal. And then you could make a decent career, and give your name glory.",
	"What else should I know?",
	"Wonderful. All right, men! I'm going ashore.",
	"If you want to sell for profit, you need to know the going rates around the archipelago. You can check them out in person by visiting the shops, or you can listen to rumors, or ask merchants that you'll meet at sea.",
	"Go on.",
	"Wonderful. All right, men! I'm going ashore.",
	"If the ship's cannons become inoperable, they'll have to be replaced. It's also possible to remove some of the cannons, to make extra room for cargo. Trading cannons can be a rather profitable sideline. You can buy or sell them at shipyards.",
	"Go on.",
	"Wonderful. All right, men! I'm going ashore.",
	"If we do become privateers, know that although ships captured at sea can only be sold for a low price, but honestly-bought ships can be sold for a good profit. This all goes on at the shipyard, of course.",
	"Go on.",
	"Wonderful. All right, men! I'm going ashore.",
	"It's not worth ruining relations with the smugglers. They bring in a good profit, even if there are some risks...",
	"Go on.",
	"Wonderful. All right, men! I'm going ashore.",
	"We need to hire some officers, cuz we don't got none. If you're not much of a leader, you won't be able to hire many officers. In that case, hire those that can wear two or three hats at once. Three know-it-alls should fill in all our positions well enough.",
	"Go on.",
	"Wonderful. All right, men! I'm going ashore.",
	"Though stealing is not a seemly activity, it may so happen that you'll have the opportunity to clean out a chest in a house, a bank, or a store. Try to wait until the owner turns his back, before you go groping. And remember, if the owner turns around and suddenly notices that his chest is empty, you're in trouble. So clean that chest out as soon as possible!",
	"Go on.",
	"Great. I'm disembarking.",
	"You may also need to head into an enemy city. Don't forget what I'm to tell you now - the soldiers who guard the gates and the port check everyone entering the city, but they leave their posts at night! So if need be, enter enemy cities at night. Then, all you'll have to avoid is getting caught by the patrol. You see, patrol soldiers don't have eyes in the back of their heads, so they can only see ahead of them and to the side. As soon as you get into a city, head to a tavern and spend the night there. Do everything you need to during the day only. While you're in the city, stay away from soldiers.",
	"Go on.",
	"Great. I'm disembarking.",
	"You can also hoist an enemy flag on your ship if you have one and hope you get lucky. The best way to enter an enemy city safely is to buy a license off the International Trade Company. Nobody will stop you if you've got one. But make sure you're sporting the appropriate flag. You see, it's quite stupid to claim you've got a Spanish license if your flag is British.",
	"Go on.",
	"Great. I'm disembarking.",
	"You should also know that prisons are located in forts. Don't try to find them inside cities.",
	"Thanks. It's time to get to shore.",
	"Well, let's start then. I don't know how you fence in Europe, but here, our main goal is to stay alive. To do this, you must have a good blade and be able to work it well. There are three attacking strikes: an ordinary strike, a lunge strike, and a crushing strike. There are also three ways to defend: block, parry and feint, or a deceptive strike. And of course, there's also a pistol to feed an enemy with lead candy from afar.",
	"Everything's clear. What's next?",
	"Any attacking strike will take energy from you, while defending actions won't require any. You can also avoid being struck by leaping backwards and to the side. But by doing so, you may take a bullet if the distance is far enough and your opponent isn't a fool.",
	"Go on.",
	"And what's energy?",
	"Energy is an index of power a character has left in a fight. All attacking actions take energy from you. In other words, a character will get tired during a fight. In order to regain power, he must take a break. ",
	"The upper limit of energy depends on the current value of the character's Reaction setting.",
	"Go on.",
	"Try to avoid having a large number of enemies around you during a fight or you'll be cut into pieces. You can combat two at the same time, but three or more opponents will prove too difficult to handle. When your opponent's energy is low, they will use feints and parry. Be careful, or you'll lose your head.",
	"Go on.",
	"If your opponent was deceived by your feint, he'll lose more energy than when using a piercing strike. If you're deceived by a parry, you may lose your energy completely. They will break your rhythm and it'll all be over.",
	"Go on.",
	"Everyone has different weapons. They may be light, of average weight, or heavy. Energy consumption depends on the weight of the weapon. You can fight with a long light blade, but one circular strike with a heavy axe can kill several enemies at once.",
	"Go on.",
	"Well, let's get in a bit practice now, shall we? Let's stretch our legs. We'll have a real fight, but not to the death. Also, you can regain your life power during a fight with elixirs, potions, and rum, but you'd better save your power for the time being. We'll just practice.",
	"Let's do it and don't beg me for mercy!",
	"No thanks. I've got everything already.",
	"Well... You're a bit weak, Captain. Be more attentive; block and parry more. But be careful, if you're deceived by a feint, your piercing strike will be intercepted and you'll lose your energy.",
	"Don't let them hit you. Intercept an enemy's blow with a piercing strike or parry. But be careful, if you're deceived by a feint, your piercing strike will be intercepted and you'll lose your energy.",
	"If your energy's gone, run away or leap backwards and fool your enemy with a feint. Mind you, you can't easily beat off a strike by feinting, but you can deceive your opponent. If he's deceived by your feint and tries to strike back against your deceptive strike, not only will you defend yourself, he'll take a lot damage as well.",
	" Well, shall we do it once more?",
	"Once more, of course!",
	"No thanks. That's enough. I got everything.",
	"Fine. Well done, I must say! Mind you, I was fighting fairly, but your opponents may have their own elixirs. If so, they won't give up easily. ",
	"Well, let's make it more difficult. Would you like to try two opponents at the same time?",
	"Why not? Hey, Hopkins! Grab your cutlass and head to the deck!",
	"No thanks. I've had enough practice already.",
	"Wow, you're one gifted fellow! We're lucky to have chosen you as our captain. One last piece of advice: the more you fence with one type of weapon, the more skillful you'll get at it. So if you want to be an expert with all weapons, rotate them more often.",
	"Thanks!",
	"Well, not bad. You beat one opponent, but two is different, you see. You need some know-how here. Your enemies may attack you in packs of three or even four! Shall we give it one more go?",
	"Once more, of course!",
	"No thanks. I got everything.",
};
