string DLG_TEXT_Q [27] = {
	"... (The skeleton takes a metallic hand and, with a rustle and a clank, slots it into place on its wrist. The hand begins to move.)",
	"What's this?!",
	"I am a Mk K-102 cyborg, manufactured by Seaweb Industries. Issue year, 2022. I have found you, man from the strange ship.",
	"Who? What? Who the hell is Sy Borg? What year did you say? This is the sixteenth century of our Lord. You... seem to be nothing but metal. That's a little strange. You wouldn't be evil, would you? ",
	"Do not argue with me, biological individual, label ",
	". I am a cyborg, a machine with a biological shell. The covering had a shorter service period than the polymer and metal alloy base. Over 170 years, the biocover has been lost. My resources are at their limit. My nuclear energy source has run down. I am running on reserve power. ",
	"Half a century? I don't get it. So when were you born, then? The twenty-first century, or the fifteenth? ",
	"What?",
	"What's with him? Dear, who are you talking to now? And anyway, I don't often talk with evil monstrosities. I'm making an exception here, and now he's at ti!",
	"System ready... I am a Mk K-102 cyborg, manufactured by Seaweb Industries. Issue year, 2022. ",
	"Yes, so you say. Look, don't start with me, junk-bucket.",
	"My mission was to enter the year 1985. Target: Donna Tyler. Objective: exterminate.",
	"Well, right now it's ",
	", and there ain't no Donna around here.",
	"During the transfer process, the distortions from the weapon and the equipment were not taken into account. Time point failure occurred. I was transferred to the end of the 15th century. My main task was to fulfill the mission. The search beared no results.",
	"Well, what do I have to do with all this?",
	"Part of my framework is a manipulator. The manipulator has a marker; you took it. It was lost during operation 'Temporal Shift', which took place on a strange ship 30 years ago. The inhabitants of the ship were not found in my identification data. They were very aggressive and difficult to annihilate. They appeared to be cyborgs with biological framework. Energy source is unidentified.",
	"Ahh, that must have been the ghost ship! Of course they're difficult to annihilate, they're exactly as you are; there are just more of them. That's why you ran defeated! Yeah, I've also had problems with them more than once.",
	"The manipulator is integrated and now functions correctly. It used to be unavailable due to the water barrier and constant re-deployment.",
	"What is that thing, and what does it do exactly?",
	"It's of no importance.",
	"Ah, I see. Operation 'Temporal Shift' simply means to leg it, doesn't it? Or as I would put it, to retreat from the enemy.",
	"Yes, unit '",
	"ÿ, you are correct. My time is coming to an end - the reserve battery is running low. The mission is impossible. The target was not found. Genetic analysis found no close relatives in the given area.",
	"Yeah, you've had some lousy luck. I suppose it's time you retired. I know now where to attain a good weapon, so if I ever come across this Donna Tyler, I'll definitely kill her in return for such a great gift from descendants.",
	"Thank you for your cooperation. Scanning in process... Complete... I don't need your clothes. Goodbye.",
	"That's it! Do all the good you can and they'll never leave you alone!",
};
