string DLG_TEXT_RUM [333] = {
	"Hm, I see... Any other news?",
	"Thank you. With respect... no.",
	"All the best.",
	"Ah, I understand... What else's new in town?",
	"Thank you. With respect... no.",
	"All the best.",
	" So that's what's happening...",
	" Perhaps, this might amuse you.",
	" And do you, captain, have any news for our colony?",
	"You're telling interesting things, ",
	"So tell me more...",
	"This is very interesting! Oh, here's something else I wanted to ask...",
	"May I ask another question?",
	"There's so much that could happen in the world around us. I'm afraid I don't have any news. ",
	"I'm kind of in a hurry right now, so let's leave that to another time.",
	" We rarely see something happening here. But if something unusual happened, everyone would be talking about it.",
	" So no news at the moment. But maybe ",
	" captain knows something?",
	"Then why don't you tell me...",
	"You don't know anything! All right, here's something else I wanted to ask...",
	"You don't know, you say. All right, tell me then...",
	"Well, you weren't",
	" of much help to me ",
	", but perhaps you know something else?",
	"I don't think I know something that could interest you.",
	"I will tell you something with pleasure, but perhaps another time.",
	"Unfortunately, I know nothing above that, allow me to leave.",
	"You have tired me with your inquiries, please excuse me, but I have things to do.",
	"Thank you. With respect... no.",
	"All the best.",
	"Well... Hic! ",
	"Heh, that's good rum! ",
	"Ri-i-ight... ",
	"For this, I'd drink another cup...",
	"Very well. Let's have another round.",
	"Thanks, but I must leave.",
	"Woo, this rum's got a real kick. Anyway, I gotta run. Enjoy.",
	"Can you imagine, I'm sitting here, bothering no one, and suddenly this Avory guy rushes toward me and smacks me right in the face! And then says 'You owe the fixer money?!' And then says that was a mistake. He's mistaken, and I've lost a tooth! Eh! What d'ya say?! And you won't believe this, a week has passed since, and it still aches. Such pain! Perhaps, a mug of ale?..",
	"Well, of course...",
	"There was this guy sitting next to me, about five days ago, just like you right now. His name was, let me remember... John Avory. The guy told me how he fooled the local usurer, he-he-he. That'll teach him, damned bloodsucker, sitting and swelling on his money, while a working man hasn't even got a snack to bite on...",
	"Oh yes, these usurers are nasty people.",
	"We had a great fight here three days ago! John Avory pinned a card-sharper. The guy's excellent with his blade, I must say. Swing, swing! And the sharper's gone. The place exploded in shouts and bustle. But John's a decent fellow, bought rounds for everyone in the tavern. I respect that!",
	"Oh, really? Neat...",
	" Yes. Can't remember anything else",
	" And now I must return to my deeds.",
	"I already told you that I don't have time for empty chatter!",
	"I am a busy person and I have no time to discuss some gossips!",
	"This is very interesting! But let's get back to business",
	"Thanks, now there's one more thing",
	"Well I'll be dead! You're a good lier. But I have another question.",
	"So let us not waste any more of our precious time and get back to business",
	" One more thing, and I will leave.",
	"You are right, time is money.",
	"You only think about your own benefit. All right, relax.",
	"Please, forgive me. Let's get back to business.",
	"Smell ya later, you old souse.",
	"All the best, ",
	"Caramba! Don't go anywhere. I'll be back.",
	"It was good to see you, ",
	"! Take care!",
	"Cast off!",
	"Goodbye, my good man.",
	"Hey! What are you hiding there? Rum? No?! Well then, I'll go get a drink.",
	"Please excuse me, I have urgent business in the city.",
	"Heh, we'll meet again!",
	"I have to go. Goodbye, ",
	"Don't you talk back to me! I ain't got the time to argue with you!",
	"I should probably go check up on the situation on the ship. Goodbye, ",
	"Hey, buddy, you okay? It's me - ",
	"! Alright, sleep it off, I'll come back later.",
	"I'm afraid your liver will kill you before my next visit.",
	"Count your piasters, you old fox! I'll be back later.",
	"It was nice to see you, ",
	"This is very interesting! Oh, here's something else I wanted to ask...",
	"May I ask another question?",
	"Thank you. With respect... goodbye.",
	"Good bye",
	"Information costs money. For a modest fee of 1000 gold I will tell you all I know.",
	"Somehow I can't remember that. But perhaps 1000 coins will refresh my memory.",
	"I am ready to tell you everything I know. But not for free - 1000 gold, and I don't agree on less.",
	"I have nothing to add. And now please excuse me, because business doesn't wait.",
	"Pay for empty chatter? No thanks, tell that to someone else.",
	"For such money I'll find everything out by myself.",
	"Let us talk about something else.",
	"You will receive it if I get really valuable intelligence.",
	"I will pay, but only provided that you'll tell me something really important.",
	"I don't have such money.",
	"A lot of ships started to disappear recently, and the strange thing is that only courier luggers and sloops are missing. They're talking about some brig appearing in the waters of Cumana... So be cautious!",
	"Only courier luggers, you say? Very interesting... And do you know anything else of interest?",
	"I won't pay for empty gossips, farewell.",
	"Your information is not worth a broken penny - you will receive nothing.",
	"I thank you, here's your gold. Can you remember anything else?",
	"Good, you deserve your money - take it. Is there anything else?",
	"Please understand me correctly, I need to feed a family.",
	"Let us talk about something else.",
	"Thank you. With respect... no.",
	"Good bye",
	"Good-bye.",
	"Yes, this is interesting. There's another question...",
	"Hm, here's what else I wanted to ask...",
	"So, farewell, speculator.",
	"Good bye, friend.",
	"There's nothing to talk about, I've told you everything I know.",
	"I haven't heard any more rumors, sorry...",
	"I understand. Well then, good bye.",
	"I see. Well, take care, friend...",
	"Yes, this is interesting. There's another question...",
	"Hm, here's what else I wanted to ask...",
	"So, farewell, speculator.",
	"Good bye, friend.",
	"There's nothing to talk about, I've told you everything I know.",
	"I haven't heard any more rumors, sorry...",
	"I understand. Well then, good bye.",
	"I see. Well, take care, friend...",
	"Understood...",
	"I see...",
	"There's nothing to talk about, I've told you everything I know.",
	"I've heard nothing more, I'm sorry...",
	"Excuse me, but I already told you everything.",
	"I've heard no more rumors, sorry...",
	"I got it.",
	"So, good bye.",
	"Finances? Hm, speak, I'm listening to you.",
	"Financial questions are always interesting. Speak, I'm listening to you.",
	"Alright, let's talk about finances.",
	"Are you sure that you are asking the right person, ",
	"? My name is ",
	". How can I serve you?",
	"You're asking me about finances, ",
	"?! I'm ",
	". So what business do you have?",
	"I am listening to you, ",
	". What did you want? By the way, my name is ",
	"The usurer sent me to collect his debt! Cash down!",
	"I have a delicate question for you regarding your debt, ",
	"I brought your credit.",
	"Um, perhaps, I was mistaken. I don't have any financial affairs with you.",
	"Excuse me, I don't have any financial questions for you.",
	"Yes, precisely. I was just going to give it all back to him.",
	"Ah, that's very good! Then you'll need to give me ",
	"Excellent, not take it and bring it back yourself!",
	"No! I won't give you anything! And if you persist, I'll call the guards.",
	"Whatever, you need to give me ",
	". Otherwise we'll have to talk in another way.",
	"That's right!",
	"Unfortunately, I don't have the whole sum.",
	"Whatever, you need to give me ",
	". Otherwise we'll have to talk in another way.",
	"And how much do you have?",
	"Here's the whole sum.",
	"Thanks for cooperation!",
	"You have 30 days to report to the employer and return him the money.",
	"I'm glad that we reached an agreement.",
	"Bah, screw you!",
	"You have 30 days to report to the employer about the mission failure.",
	"Guards!! Hooligans are poking my eyes out!",
	"Shut up!",
	"You have 30 days to report to the employer about the mission failure.",
	"Only ",
	" gold.",
	"No. I need the whole sum!",
	"Give me what you have. I'll pay the rest. I'm feeling generous today.",
	"You are very kind! Thank you very much.",
	"Oh, why do I always get into these situations?",
	"You have 30 days to report to the employer and return him the money.",
	"It is all very good, and I accept the gold from you. However, you didn't manage to do this within the agreed terms of delivery. Therefore I am compelled to reduce your fee by ",
	"%. I am sorry, but this isn't a subject for discussion. Please, take this...",
	"Thanks!",
	"Excellent! I was waiting for it for a long time. Here's your reward.",
	"Thanks!",
	"Excellent! But where are all the chests with gold?",
	"Would you accept gold without the chests?",
	"I will come later.",
	"No! Only in chests!",
	"That's bad. The rats have spoiled mine.",
	"Well, will the sum of, say, ",
	" cover the cost of chests?",
	"Yes, it is acceptable",
	"So we have agreed!",
	"Only this is too much for me.",
	"It's good to deal with you!",
	"Thanks!",
	"So, very well. I have a package ready for you, which you should deliver to someone well-known, personally into his arms. Please take this.   \nDon't approach me any more, and don't talk to me, it may cause suspicion. Be careful...",
	"Hm, perfect. I am handing the package over to you, and remember that it should be delivered directly into the specified person's hands.   \nNow good bye, and don't come close to me more, it's dangerous.",
	"I got it. Farewell...",
	"Farewell, and good luck.",
	"Hey, did you come across the mummy powder I asked you to find yet?",
	"No, not yet... Listen, dealers in the streets have it, apparently, but they're muddling for some reason...",
	"No, not yet... But I will continue to look for it.",
	"Hey, did you come across the mummy powder I asked you to find yet?",
	"Yes, found it. So how much will you pay me for it?",
	"Nothing. But I know someone who will buy it from you.",
	"Hm, I was counting on receiving the money right now.",
	"I believe you won't lose out on anything here. Listen carefully.",
	"On Guadeloupe, in Basse-Terre city, there lives one strange character called Ascold.",
	"Strange name...",
	"I know him, had a chance to talk to him. He's one impudent fellow...",
	"What's that? Did you get a chance to meet his stern temper?",
	"Oh yes, he simply kicked me out of the door as if I was some whipper-snapper!",
	"Ascold's a bit harsh, but he's a good, honest person. Rumors say he's a Muscovite, there's this folk living in the north of the Old World, where there's snow all year long, and everywhere around you there are only forests and bears. That's why his character's severe, and enough strength in hands for four huge lads.",
	"Don't really know how and when did he come here, and have no idea about what he's doing here.",
	"But he trusts me since I have some trading affairs with him.",
	"So head over to his place, introduce yourself, and tell him I sent you - and everything will be alright. He will buy this rubbish from you since that's his order.",
	"And what do you gain from all this?",
	"Don't worry about me, I will keep the necessary sum of commission fee from our common cash flow.",
	"I see. Well then, perhaps I will drop by this Ascold when I have a chance.",
	"Perhaps, they're mentioning the Inquisition?",
	"Precisely, they do...",
	"Well what did you expect?.. Here's what I'll tell you, friend - they have the powder. Not all of them, of course, but someone surely has it. Therefore you just have to be more pressing with them - and then you'll achieve what you need.",
	"Heh, well then, thanks for the help.",
	"Let's have a look at this tin can of yours. Eh, no. You just look at it, it's all covered with some strange letters, that's probably sorcery. I advise you to take this thing to the church, they'll decide what to do with it.",
	"Thanks for a good advice.",
	"Right there on the table there are some tools: blow lamp, metal saw, tin cutter and others. Take those and open it yourself, and I don't need any money.",
	"Thank you, ",
	"You have done the right thing, my son. We don't know what is inside, but it seems that tomorrow we will need to consecrate the church anew.",
	"I do not want to ask you where you got this. By the Savior's name I forgive you all of your sins! Go with peace.",
	"Thank you, Father.",
	"Robbery, in broad daylight! What the hell's going on?! Hang about there, buddy...",
	"Heh, what're you digging around there for?! You aren't thinking of robbing me? Well, then you're finished!",
	"Wait, where you reaching into? Oh, turns out you're a thief! Consider yourself finished, pal...",
	"Devil!",
	"?Ay caramba!",
	"Ah, damn!",
	"Oh, captain, it didn't happen, but has been happening for a long time now. We, the merchants of the Caribbean sea, are on the verge of ruin. And it's all because of that damned 'Blue Bird'...",
	"ÿBlue Bird'?",
	"Yes, that devil's xebec, the only ship of that type here, you can't escape it in the sea. It's plundering only the merchant ships. It doesn't bother big caravans guarded by military ships.",
	"So why do you say that the merchants are ruined? After all, the goods are still arriving here with these caravans.",
	"They do, indeed. But the matter is that the turnover in this situation becomes unprofitable. It's better to have your own sloop or fleut, buy the goods in the Old World and carry them here yourself. Now that's what I call trade!   \nBut when we buy the goods from carriers, you're not thinking about the profits, it's a question of pure survival.",
	"I understand. So it's just your ships that are plundered by the xebec...",
	"Rightly so. Almost all of the merchants have already lost their ships, devil take that 'Blue Bird'!",
	"Right, that's sad for you... Well, so what do you want from me?",
	"We want you to destroy this gray-winged muskrat, damn it!!!",
	"And what's in it for me?",
	"I will collect a worthy payment for your work from all my colleagues. I can firmly promise you fifty thousand piasters. The devil's xebec should go to the sea bed!",
	"I won't even wiggle my finger for such money, my friend. Keep searching for a fool!",
	"Hm, I'm interested in this money. I am ready to undertake this task. What are the terms of completion?",
	"You are not restricted in time. I perfectly understand that it's going to be difficult, damn it! To tell you the truth, we already tried to hire assassins for this business, wanted to remove the captain. Without results...",
	"Really? Could you tell me about this in detail?",
	"Well, we each threw in some money and employed someone to find the cap'n of this xebec among the pirates. But it didn't work out, our hired fellow ransacked the Caribbean for about six months, but found nothing. Devil knows, where are they based and how they sell the loot...",
	"Alright, my friend, that's something already. And now listen to my conditions for the deal.",
	"Listening carefully, ",
	"This deal is between you and me, collect the money as you wish, but not a word to nobody about my involvement. And another thing. You say that ALMOST all merchants have lost their ships. What do you mean 'almost'?",
	"One dealer still has a fleut. But he's lucky, never encountered this xebec. He's our only hope to firmly settle here, all of our men already owe him. If he wouldn't support us in this difficult time, we'd all meet our end long ago. He never refused our requests to borrow some money!",
	"I understand. He's almost a saint! So what's his name?",
	"Pascal Vousier. He runs a store on Bermuda in the pirate settlement. So do you accept the job?",
	"And do you accept my condition about silence?",
	"Certainly!",
	"Then I take it. I begin my searches from this day, and hope to finish them soon.",
	"Oh, if only you were right! Well then, you may begin. I very much hope that it will all go as you said.",
	"It will, have no doubt!",
	"Well then, it's a pity. Perhaps, we will look for 'a fool' in other place...",
	"Hmm...",
	"Excellent news, I must say! At last we can freely do our trade... Do you wish to receive your money right now?",
	"Yes, that would be better...",
	"Hm, wait... As far as I know, you managed to overtake the xebec, but you didn't sink her! Now she is in your possession.",
	"Yes, it is so. And what's the problem?",
	"No problems, please receive your reward.",
	"Thanks, that's settled. Wish you all the best... By the way, do you wish to learn who was behind all this?",
	"Hm, that'll be very interesting to know...",
	"It was the very 'saint' merchant of the Caribbean sea - Pascal Vousier.",
	"It can't be!..",
	"It can. Unfortunately, I don't have any proof, but you keep in mind who's lending you your own money.",
	"Hm, all this needs to be checked... Well then, thanks for your work and the information.",
	"Don't mention it, it's paid by you. Farewell.",
	"The problem is that this damned ship is now in your hands. And you're a pirate too, by the way! So who will prevent you from plundering merchants in the same way as its previous owner?",
	"Hm, it's an interesting question, of course... However, I did complete your work!",
	"No, you didn't. We agreed on sinking the 'Blue Bird', not boarding it.",
	"Ah, so that's your answer! Well then, I understood you... All the best to you, send my ardent regards to your colleagues.",
	"I will, without fail! Farewell, and keep your word in full henceforth.",
	"Of course. But I will see you again...",
	"It's a pity. Well, you're not the first one who takes this job and achieves nothing. Too bad, we'll just have to stick with our misery...",
	"I hope all will settle into shape in due course...",
	"That's true. We're living here in vanity, and fondly believe that the earth is spinning around us alone. But no, from the earth we came, to the earth we'll go   \nHeh, I'm feeling lyrical for some reason.",
	"It happens... Well then, farewell.",
	"Oh, you bastard! So our fears appeared to be true!!",
	"I would leave you alone, if you wouldn't cheat me!",
	"Oh, damn! Guards, seize him!! You won't go far, bastard...",
	"You should've given me my money, sly-boots. Let's continue your treatment...",
	"Curse you, bastard! Oh how I regret dealing with you!! Before you came the 'Blue Bird' never gave us SO MUCH problems!..",
	"My friends, you have only yourselves to blame, you should've kept to our agreement.",
	"What agreement, between us and you? We strictly adhered to it! It was you who broke it by not sinking the xebec!",
	"Mon cher, there's no need to shout, it will have a pernicious effect on your vocal chords. What if you suddenly can't speak then? Anyway, I am ready to speak with you, but only if you can remain calm...",
	"Well alright, but calmness has nothing to do with this. It was you who broke the terms of our deal, not we - that's the problem!",
	"Heh! You merchants are masters of such twisty contracts. I know your tricks. Put a comma somewhere, and the meaning of the text is changed.",
	"Why are you mentioning commas? We had a spoken arrangement.",
	"Well, that's figuratively speaking. Thing is, you caught a possibility to keep the money you promised me, and done exactly that. And I'm a pirate, I don't have time to figure out the double meanings of your conditions.",
	"What conditions?",
	"Conditions of our arrangements. The 'Blue Bird' was a trouble for you - I solved this problem. If you would have given me my money, I wouldn't even poke you with a finger. So all your problems are due to your wisdom, so to speak...",
	"Well fine, take your 50 thousand and get out of here!",
	"Not so fast, mon cher. The thing is, I incurred additional financial costs while trying to put your mind on the right track. Let alone the stress I was subjected to. Therefore the sum was increased.",
	"So what is this new sum? Name it.",
	"Increase it four times. 200 thousand, and I will leave you alone. Otherwise I will ruin you. And then kill. At first your family, and then you...",
	"Oh, you're a devil!!",
	"And very, very angry one at that...",
	"Very well. Here's your money. And now be gone! And leave us alone!",
	"Without fail. Now that you paid me in full, the 'Blue Bird' is no longer a threat to you. Farewell, good luck in your commercial affairs...",
	"Quite right. You can get one million piasters within a minute of me receiving the acknowledgment.",
	"I already told you, ",
	", that I have the deposit. I am waiting for the acknowledgment to transfer it.",
	"You don't need to worry. I have the deposit, I am only waiting for the acknowledgment to transfer it.",
	"Hm, it seems to me that you are excessively interested in this deposit. My reputation is faultless, therefore I can only repeat what I said earlier. I have the deposit on your name, and you will be able to receive it after I get the acknowledgment to transfer it.",
	"I understand. Well, that's perfect. I learned what I wanted.",
	"Ah, I see...",
	"I also, don't worry too much.",
	"I understand... Thank you, ",
	"Yes-yes, I received the permission to perform this financial operation. All right to receive, ",
	"Heh, very good...",
	"Perhaps, you will decide to put this money into growth? I am always at your service, my reputation...",
	"I understood you, thanks. I'll think about it.",
	"Ah, here you are, at last...",
	"What's the matter? Why aren't you aboard the corvette yet?... And where's the Mechanic?",
	"I don't know where he is now. When I arrived on 'San Gabriel', he was being led away by the militiamen. Apparently, he is arrested, and only the admiral could do that.",
	"Ay caramba!!! What do we do now?",
	"Can't we manage without the Mechanic?",
	"We need Vedeker. We can get aboard the corvette, but we won't be able to release it without Henrik.",
	"Then we must go to privateer's residence and rescue the Mechanic. Unfortunately, I have to pass on this business - the admiral's gaze alone horrifies me...",
	"Heh, that's obvious... Get to the ship, I will soon be arriving with Vedeker. Apparently, the other crew members are already there.",
	"As you wish, captain.",
	"Don't panic without me over there. Everything will be alright.",
	"Ah, here you are, at last...",
	"What's the matter? Why aren't you aboard the corvette yet?... And where's the Mechanic?",
	"I don't know where he is now. When I arrived on 'San Gabriel', he was being led away by the militiamen. Apparently, he is arrested, and only the admiral could do that.",
	"Ay caramba!!! What do we do now?",
	"Can't we manage without the Mechanic?",
	"We need Vedeker. We can get aboard the corvette, but we won't be able to release it without Henrik.",
	"Then we must go to privateer's residence and rescue the Mechanic. Unfortunately, as a woman I am of no help to you in doing this.",
	"That's for sure... Get to the ship, I will soon be arriving with Vedeker. Apparently, the other crew members are already there.",
	"As you wish, captain.",
	"Don't panic without me over there. Everything will be alright.",
	"agreed to",
	"agreed to",
	"agreed to",
	"agreed to",
};
