string DLG_TEXT_USR [33] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"Hm, let me guess... Nothing important, again?",
	"Listen, I'm here to work finances - not to answer questions!",
	"Never mind. Sorry...",
	"I've got nothing for you. Not now, anyway.",
	"Gar, this memory of mine... ",
	"You're right. Sorry...",
	"I see.",
	"Ozzie sent me. He said you should have something ready for me?",
	"Listen, I need to find Ozzie.",
	"True enough. You've got three million in cash waiting for you, ",
	". Do you want it now?",
	"Yes, the whole caboodle.",
	"Then be my guest, ",
	". Anything else?",
	"No, nothing... Listen, what kind of business is it you got with Ozzie? Just curious...",
	"Sir, curiosity is not a becoming trait around here. Unless you plan on becoming a corpse, that is. Especially if the man you're prodding is Ozzie. Now, if that's all you need, I do have work to do...",
	"Yes, certainly! Thanks for the money. It should be handy!",
	"You're lookin' for Ozzie? Bad idea. I already done told you it'll complicate that breathing habit of yours.",
	"Ah, leave me alone. ",
	"No, that's enough for me...",
	"I'm done. I will say no more.",
	"Well, that's just it. This is life and death. I need him, so if you know how to find him, I'm here imploring you. ",
	"I see...",
	"Too bad...",
	"Well then, I guess you really aren't much use to me...",
	"Well, that's a shame because I ain't got a clue. ",
	"You know, when I took that five million I didn't even think of the consequences. Yeah, I said five. Two was for me; payment for services rendered.",
	"So now, those two million chunks of metal have utterly ruined my life. I won't bore you with the details, but believe me - this is some shady business.",
	"I've always considered myself very acute. But I can't get my mind around why didn't I see this coming.",
	"I understand that... Thanks.",
};
