string DLG_TEXT_USR [21] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"Hm, let me guess... Nothing important, again?",
	"Listen, I'm here to work finances - not to answer questions!",
	"Never mind. Sorry...",
	"I've got nothing for you. Not now, anyway.",
	"Gar, this memory of mine... ",
	"You're right. Sorry...",
	"I see.",
	"They say that Edward Low was looking for you. Well, I'm looking for him.",
	"He came here, asking for money. Didn't give him a red cent. Shady character, he was. Eyes of a snake. It was clear he wasn't coming back. I read people, you see.",
	"I told you all you need to know. You too dumb to work with it, go talk to someone else. ",
	"Again?",
	"Get out!",
	"And where...",
	"I see.",
	"Aha, sorry...",
	"Yeah, I get it. I'm leaving.",
	"Also, I ain't got the slightest idea about where he mighta off and gone. ",
	"I see...",
};
