string DLG_TEXT_USR [30] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"Hm, let me guess... Nothing important, again?",
	"Listen, I'm here to work finances - not to answer questions!",
	"Never mind. Sorry...",
	"I've got nothing for you. Not now, anyway.",
	"Gar, this memory of mine... ",
	"You're right. Sorry...",
	"I see.",
	"I need to talk to you about Morris Williams.",
	"You won't see your partners any more.",
	"What happened to Morris Williams?",
	"You mean you don't know he's in jail?!",
	"Course I know. But what happened? He die or something?",
	"No, not as such. But he's been better. You probably know about his misfortune. Weren't it for that, your debt would have been long paid off.",
	"But it hasn't!",
	"And you're not worried about prison rot? ",
	"My only concern is for own health, so no, sir, I could hardly care less. And that, I believe, is the end of this conversation. ",
	"You won't shake me that easily. We will meet again...",
	"Who are you talking about?",
	"About those smugglers of yours - I've done some decoration with their blood.",
	"Hm... So what do you want?",
	"To begin with, the contracts of Morris Williams. Also, leave the Atterbury family alone. You might recall they were so careless as to borrow money from you a year ago.",
	"You sure you're a pirate? Well, all right. Williams will be released immediately.",
	"That's not all. For my silence in regards to your smuggling operation, you will pay me... Let's say ten thousand a month.",
	"Hwa-ho! I most certainly will not.",
	"What proof have you? It's your word against mine, my fine barnacled friend. ",
	"Still... No good in a scandal, so I will concede you Williams. That is all you get, however. Farewell.",
	"Farewell. And don't you forget our discussion.",
};
