string DLG_TEXT_USR [21] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"Hm, let me guess... Nothing important, again?",
	"Listen, I'm here to work finances - not to answer questions!",
	"Never mind. Sorry...",
	"I've got nothing for you. Not now, anyway.",
	"Gar, this memory of mine... ",
	"Yeah, you guessed it. Sorry...",
	"I see.",
	"Listen, I want to offer you a financial opportunity...",
	"I'll tell you right off, I'm not taking money with interest. But I'll gladly lend you some.",
	"Same deal as last time? ",
	"You got some more money for me, then? ",
	"Let's cut the gab and get down to business.",
	"This is why?",
	"Yes, same deal...",
	"Again...",
	"Let's...",
	"Pierre le Picard laid a pretty nice sum on me, and I'd like to make sure it goes where it can do some good. So... how about you take it?",
	"No, I just wanted to give you money. How does that sound?",
};
