string DLG_TEXT_USR [69] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"Hm, let me guess... Nothing important, again?",
	"Listen, I'm here to work finances - not to answer questions!",
	"Never mind. Sorry...",
	"I've got nothing for you. Not now, anyway.",
	"Gar, this memory of mine... ",
	"You're right. Sorry...",
	"I see.",
	"I would like to ask your help in a certain matter. For your time and effort I will compensate you generously, of course. ",
	"I would be glad to discuss that affair... for a hundred thousand coins.",
	"What do you need?",
	"The Holy Inquisition has deigned to grant you a papal pardon, for but a mere fifty thousand. What's this? No tears of joy in your eyes?",
	"You again! Get out!",
	"I grow tired of you. Silence that hole in your head. Now I set the conditions here, and you will attend carefully, ponder my words, and begin to regret having hitherto ignored them.",
	"What, you've got me some more fairy tales about the Pope's pardon? That's a mercy; I was running out.",
	"All right, Joseph. We will talk again...",
	"What do you expect, you cursed blood-slurping Jesuit stooge?",
	"What feeling, what spirit! Marvelous. Four stars. Well, three and a half.",
	"Hey ol' man, need someone to rattle your debtors a bit?!",
	"Investigation in Curacao",
	"Speak. What do you need?",
	"I need to know the plans of the governor-general of Curacao, vis-a-vis the English. I am willing to pay richly for the information. ",
	"I hope you understand what you're asking for.",
	"I hope you understand that I will be very generous.",
	"Well, a hundred thousand coins, and I tell you all I know.",
	"It's a deal. ",
	"I... don't carry that kind of lucre around with me. Hang on, though. I'll be back.",
	"You dog wretch! Don't you think that's a bit much?",
	"Well then, here's what I can tell you: about an hour ago, in the residence of Governor-General Peter Stuyvesant, a military council was held to discuss exactly the topic of your question - the participation of the Dutch colonies in the merchant war with England. Though I wasn't present at the meeting, I know that after its conclusion, the Governor-General's orderly was sent off somewhere on urgent business. As we speak, a brig is standing by for him on the stead.",
	"You look like a pirate worth your brine; I wager you can take a Dutch brig. So if you're going after it, hurry before it disappears over the horizon. Incidentally... we've never met. Farewell, stranger.",
	"Yeah, here's your money. And I neither know you nor particularly want to. Goodbye.",
	"The brig is in the bay.",
	"Hmm. Look, I'm in no mood for games. Either bring me the money or don't. I'll be waiting. ",
	"Yeah, yeah. I get you.",
	"Go on, I'll be right here.",
	"I'm getting to it.",
	"Found the money yet? Where's my lovely hundred thousand?",
	"Yes, I've got it right here. I'm ready to turn it over, so tell me - what do you have for me? ",
	"Not yet, but I surely will dig it up somewhere. You hang on there.",
	"You pocknose trout! That's ludicrous. How do you expect me to find that much?",
	"Oh you're a cheeky one. Look, I'll ask you nicely. Leave my house, immediately.",
	"Devil take you, you perverted vampire! I'll unleash your guts right here and now! ",
	"Not so fast, diddle-mum. Guards! Get over here!",
	"Blast!",
	"Inquisition",
	"You must have me mistaken. I've nothing to be guilty about! ",
	"That's your opinion. The Order has its own ideas. So fork over.",
	"I will pay you nothing! And if you don't leave my house this instant, I will call my staff!",
	"Aren't we the arrogant one. Well, I have a cure for that...",
	"As you wish, but you'll regret it...",
	"Murderers! Andrew, come here!",
	"Andrew?",
	"Wait, is that a threat? ",
	"Oh, no. Nothing like that. It's fine, Joseph...",
	"So tell me why I should listen to the fruits of your delirium?",
	"It's simple, Joseph: your son is in my hands. Metaphorically. Am I being altogether clear, or would you like some visual aids? I can bring you a finger or an ear, if it would help. What do you think?",
	"You... No... No, I believe you... Um. Pardon me. If I give you the money now, how can I be sure that you won't kill him anyway?",
	"Oh, you can't. That's the point of the thing. You know all those people you've driven to despair? Well, this is your lesson in empathy. Learn the price of grief. But enough talk. Have at you! ",
	"Yes, all right. Take it. But I won't forget this.",
	"Oh, that's all right. I'm used to it. Also, remember that the Order is watching you. And probably will until the day you die. That's nice, isn't it.",
	"No... No, no need to.   \nHeh. You so-called debt collectors are all the same. It's like an army of twins. Avery here, he also spins those words...",
	"John Avery?! Why, he's an old friend of mine. Is he still in the city? Where can I find him?",
	"I have no idea. He's a free man; goes where he pleases. As for his still hanging around Willemstad, I doubt it. There's no more work for him here. As a friend, you should know that all you really need do is follow the rum. Go hit the taverns, if you want him that badly.",
	"Hah! Well, no surprise there. But he didn't give off any hint? I'm not talking about an illustrated diagram of his travel plans...",
	"Said that he was going over to the English. I think he mentioned ",
	", but to be honest I wasn't really paying attention.",
	"And you said you would be no good to me! Well, thank you!",
};
