string SHP_NAMES [76] = {
	"Anfitrita,Concepcion,El Sinor,San Miguel,Los Reyes,Los Ances,Christofor,Christopher",
	"Argonauta,Arrogant,Asia,San Pedro el Grande,Del Coro,Santiago,Atrevida,Santissima,Trinidad",
	"San Daniel,Bahama,San Christobal,de la Nina,del Rosario,Conde de Regla",
	"San Antonio,San Augustin,San Felippe,Apostle,San Fernando,San José,San Justo,San Leandro,Santa Agnes",
	"Cinco Llagas,Esmeralda,del Juncal,Annunciation,Jesus Maria,Feliz,Fenix,San Nicolas",
	"Fuerta,Gailardo,Grune,Santa Catalina Martir,Gloria,Angel Guardia,Santa Teresa,Saetia,Santa Cruz",
	"San Juan,Batista,El Señor,San Miguel,Bien Saceso,Infanta Anna,Purisma,Concepcion",
	"Limeno,San Pedro,de la Fortuna,Aguilla Imperial,Santa Maria,Evangelisto,Milagrosa,Peregrin",
	"San Antonio,San Ignacio,San Francisco,Santa Anna,Santa Isabelle,Jesus Maria,José,De La Antigua",
	"Santiago,De Los Tres Reyes,Baptista,San Gregorio,Salvador del Mundo,Soberano",
	"Galicia,San Antonio,San Augustin,San Lucas,San Bruno,Santa Cristo,Maracaibo,Virgin,Pilhar",
	"San Carlos,San Marcos,San Esteban,San Fermin,San Fiorenzo,Principe,Asturias,San Pedro,El Grande",
	"San Fulgencio,San Gabriel,San Genaro,Los Angelas,Santo Domingo,de Polonia,La Muer,Saint Joachim",
	"San José,De Montegudo,San Jasinto,San Juan Nepomacedo,San Pedro,San Tomas,Agino",
	"San Leandro,La Corona,La Presa,San Pablo La Presa,San Lorenzo,San Salvador,San Pablo,Santo Cristo,Burgos",
	"Alacantara,Martir,San Rafael,San Romon,San Sebastian,San Ignacio",
	"San Vincent,San Isidro,Santa Aqueda,Santa Anna,Santa Brigitta,Santa Catalina,San Jeronimo",
	"Santa Casilda,Santa Cecilia,Santa Clara,La Visitacion,Nuestra Señora,La Saludacion,Virgin",
	"Santa Florentina,San Nicolas,Santa Isabella,Santa Isolcadia,Santa Lucia,Santa Margarita,San Felippe",
	"Santa Maria,Santa Magdalena,Santa Matilda,San Vicente,Ferrer,Almandena",
	"Orfeo,Santa Rosolia,Santa Rufina,Santa Rosa,Carlos II,Santa Teresa,San Cristo,Burgos,San Felippe",
	"San Martin,Puebla,Soberanto,La Natividad,Nuestra,Begona,Don Quixote,Sanche Panso,Dulcinea,Auronic,Ernan Cortes,Columbus",
	"Prince Royal,Rainbow,Constant Reformacion,Saint Andrew,Triumph,Vanguard,Charlese,Henrietta Maria,Paragon,James,Old James,Unicorn",
	"Resolute,Naceby,Royal Charles,Dunbar,Henry,London,Richard,Royal James,Royal Prince,Royal Oak,Royal Catherine,Loyal London,Victory,Charles,Saint George",
	"Ossor,Prince George,Duke,Britain,Albemarl,Blenheim,Princess Ann,Duchess,Castle Windsor,Vanguard,Royal James,Royal William,Royal Ann,Prince",
	"Neptune,Full,Crowning,Arrow,Royal Sovereign,Asia,Queen,Victory,Association,Barfler,Namur,Avenger,Triumph,Prince",
	"Vanguard,Barfleur,Basil,Beagle,Bedford,Belize,Queen Charlotte,Union,Benbow,Berkeley,Berwick,Black Prince,Black Blanche,Blenheim",
	"Bonetta,Garland,Brave,William Mils,Caledonia,Cutty Sark,Bristol,Britain,Dreadnought,Catherine Elizabeth,Howe,Trafalgar,Prince Regent,Royal Adelaide",
	"Cambridge,Camilla,Antelope,Shallow,Leopard,Catherine,Griffin,Lyons,Mary,Speaker,Fortune,Champion,Bonne Aventure,Charlotte,Charon,FairFax,Marlborough",
	"Worcester,Dunkirk,Essex,Treduff,Resolution,Langport,Newbury,Vengeance,Lima,Montague,Gloucester,Bridgewater,Cornwallis,James,American,Bounty,London",
	"Creole,Cressen,Lenox,Corona,Harwich,Resolute,Young Swan,Edgar,Monfaum,Sealark,Defense,Rupert,Warspite,Monk,Dreadnought,Ann",
	"Desperate,Restoration,Hope,Elizabeth,Barford,Grafton,Castle Stirling,Jacob,Discovery,Dolphin,Pendennis,Breda,Prince Frederick's Crusade,Dreadnought",
	"Exeter,Dublin,Kent,Duncan,Edgar,Egmont,Sullfolk,Elephant,Emerald,Sorceress,Endimion,Great Harry,Entrepreunant,Golden Dragon,Torrington",
	"Devonshire,Russel,Norfolk,Hamber,Torbey,Lancaster,Dortshire,Maria Celesta,Endeavor,Fairy,Falcon,Winchester,Favorite,Deer,Yarmouth,Saint George,Manchester",
	"Willpower,Prosperity,Barford,Fury,Kent,Triumph,Vengeance,Orford,Somerset,Journey,Susan Constant,Arc Royal,Castle Stirling,Glasgow",
	"Confidence,Tiger,Adventure,Providence,Harpy,Impetuous,Arrogant,Hawk,Danger,Threatening,Striking,Culloden,Saint Michael",
	"Hero,Centurion,Portsmouth,Judith,Golden Doe,Victory,Illustrious,Implacable,Forbidding,Unbending,Fearless,Indomitable,Antelope",
	"Diamond,Iris,Insuperable,Isis,Jason,Ruby,Catherine,Kent,Resolution,Leopard,Leviathan,Royal Sovereign,King of Seas,Saint Andrew",
	"Freedom,Lightning,Lion,Mary Rose,Sparrow,London,Lire,Pelican,Magnificent,Majestic,Sussex,Jenny,Valiant,Avant-Guard,Wrangler",
	"Bristol,Pegasus,Pelican,Perseverance,Phoenix,Ruthless,Cambridge,Oxford,Protector,Guard,Saint George,Prudent,Marston Moor",
	"Deptford,Dexterous,Pearl,Prince William,Victory,Vigilant,Vindictive,Viper,Fox,Warspite,Wasp,William and Mary,Caledonia,Alexander,Kimberley",
	"Elephant,Resistance,Vengeance,Revenge,Sea Horse,Badger,Lovestow,Sir Francis Drake,Might,Royalist,Snake,Albermarle,Speedwell,Swift,Spencer,Susan,Hornblower",
	"Mayflower,Tigress,Swallow,Swan,Swift,Resolute,Bully,Terrifying,Thames,Winner,Elizabeth,Fearless,Unicorn,Ulysses,Yarmouth,Daring",
	"Achates,Achille,Achilles,Hannibal,Justine,Laton,Laura,Marseillais,Saint-Jean,La Trompez,La Garce,Volontaire,Bourgogne,Brave,Valor,Bucentaure",
	"Artesienne,Astrie,Auguste,Bayonnaise,Belleisle,Bordeaux Trade,Marseilles Trade,Concorda,Trust,Corona,Soleil Royale,Protecteur,La Tactique,Dreadful",
	"Formidable,Duke of Burgundy,La Pomon,Hawk,Fortuna,Foudroyant,Astrolab,La Belle Pulle,Guadeloupe,Militant,Invulnerable,Imperial",
	"Undefeated,Butterfly,Patriot,Poletta,Pegasus,Pearl,Prevoyant,Protecteur,Guardian,Careful,Mighty,Saint-Germaine,Resolia",
	"Saint Esprie,Avenger,Crown,Queen,Brave,Vendom,Victorious,Saint Philip,Delfin Royale,Royal Dolphin,Monarch,Royale Duke,Queen",
	"Saint Michelle,Sena,Revenge,Lily,Paris,Royale Teresa,Henray,Ruler,Sun King,Scepter,Magnanimous,Courageous,Victorious,Marengo,Threatening",
	"Magnificent,Independent,Excellent,Victorious,Valiant,Monarch,Arrogant,Wonderful,Paris Trade,Redoutable,Saint Louis,Oriente",
	"Ambitious,Beautiful,Victor,Wonderful,Ambitious,Triumphant,Hercules,Loyal,Charantou,Rivolie",
	"Bourgogne,Mons,Ocean,Orient,Nation,Monarchy,Imperial,Monte Bello,Hero,Ruler,Beautiful,Unbending,Victorious,Sirene",
	"Jemmapes,Tag,Henry IV,Dugues-Trouin,Turenne,Valmie,Splendid Sun,Duke de Bourgon,Famous,Mighty,Indivisible,Breeze,Saint Louis",
	"Nation,Catone,Orient,Holy Mind,Langedok,Antifederalist,Victoria,Crown,August,Triumphant,Indomitable,Marvelous,Beautiful",
	"Diamond,Ruby,Bourbon,Prince,Marvelous,Frederick,Victorious,Excellent,Valiant,Undefeated,Neptune,Normandie,Princess,Triumphator",
	"Blooming,Vermandua,Eclatante,Parfait,Superbe,Indian,Proud,Fogonne,Saint Michelle,Arrogant,Courageous,Loyal,Crescent,Courtisane,Bright,Laurel",
	"Lavish,Handsome,Henry,Ruby,Martial,Thunderous,Arrogant,Royale Louis,Bretagne,Undefeated",
	"Pluto,Valiant,Hermes,Avenger,Pelican,Pearl,Mocca,Pandora,Snake,Mary Spark,Queen Anne's Revenge,Adventure,Dolphin,Happy William,Golden Doe,Shining,Darkness,Natalie",
	"Pegasus,Swallow,Mayflower,Henry,King Jacques,Dark Vengeance,Lucky Hugh,Bloody Bill,Susan,Libertalia,Hispaniola,Bon Adventure,Arabella,Cloto,Atropos,Lechasis,Waiter,Destiny",
	"Roebuck,Jack's Luck,Lucky Johnny,Angel of the Night,Terror of Man,Sea Urchin,Will of Fate,Phantom,Providence,Devil's Eye,Sentence,Lucky Dolphin,Stormbringer,Shapeshifter",
	"Black Prince,Demon,Demon of the Night,Hugh the Beast,Bloody Feast,Nightmare,Predator,Golden Fortune,Sea Devil,Crown,Jolly Ham,Eye of the Abyss,Vengeance,Furious,Mad Green",
	"Gentleman of Fortune,Jolly Deadman,Coquette Sue,Evil Joke,Black Dog,Bell of Revenge,Hurricane,White Shark,Twister,Omnipresent,Wheel of Fortune,Moloch,Devil's Bride,Modest,Shooter",
	"New World,Bad Girl,Unexpected,Black Baron,Moray,Piranha,Dalila,Sea Demon,Myth,Black Dragon,Sea King,Goodwin,Cobra,Mad Morgan,Ollegon,Glaas,Spider,Blind Pew",
	"Prophet,Gray Angel,Gray,Pigon Dud,Avadon,Shark,Black Diamond,Vassa,Green Stone,Freeze,Scout,Diamant,Sea Fox,Fallen Angel,Star Fish,Wolverine,Warrior,Lexa",
	"Imminent Death,Madcap,Ball Lightning,Luck's Favorite,Mad Bill,Murderer,Soulcatcher,Dos Pirato,Bull,Cortes,Expius,Jerry,Fletcher Lynd,Whisper,Milano,Imp,Warham,Lepur",
	"Kitty,Gorilla,Reverend,Black Jack,King Arthur,Widowmaker,Old One,El Diablo,Encarnado,Grifon,Eduard I,Unbeatable,Woman Hater,Vengeance,Death to America",
	"Moriaans Hoofd,Brig Van Leidjden,Buinvis,Gelderland,Frisland,Hasevint,Dolfin,Seekalf,Prince Mauricio,Prince Villen,Derflinger,Roter Lujv,Vridjit,Vaaksaakheim,Groene Draek,King Villen,William de Eerst",
	"Fallen,Southern Province,Admiral de Ruigte,Admiral Tjerk,Gekrundi Leu,Kampel,Devrajs,Dordreht,Gelderlend,Gelidjheit,Hercules,Hersteller,the Netherlands,Neptunis,Emilia,Lejdjent,Stad en Lande,Honslaarsdijk",
	"Ostrego,Roter Lujv,Emilia,Brederoe,De Seven Provinsien,Amsterdam,Overdjesel,Pluton,Prince Frederik,Prince Maurits,Gauda,Rotterdam,Utrecht,Vestfall,Seland,Meermen,Omlandia,Prinses Luisa,Gorihem,Steenbergen",
	"Prinses Maria Luisa,Admiraal Pit Hein,Alkmaar,Flijgende Hert,Tonijn,Fetis,Salamandra,Overissel,Delft,Erfprins,Glejnthaus,Following,Crown Prince William,Alkmaar,Belft,Beschermeer,Braakel,Landiskron,Kornelia",
	"Rotterdam,Arveprias,Nollande Tuin,Crown Prince William,Derflinger,Roter Lujv,Emilia,Gauda Liju,Frisland,Groen Drek,Medemblik,Neptunus,Belle Antuanette,De Seven Provinsien,West Frisland,Schrikkervekker",
	"Hoop,Prins Hendrik,Sampson,Svaerten Bul,Derflinger,Roter Lujv,Emilia,De Seven Provinsien,Fliegende Draek,Derflinger,Roter Lujv,Emilia,Maaht van Dordrecht,Frederik Hendrik,Alsion,Breda,Deventer",
	"Erfprins Brusvik,Wapen van Zeeland,Sint Laurens,Omland,Middelburg,Groot Kristoffel,Boomel,Sieriksee,Wapen van Nassau,Wapen van Nederlanden,Walcheren,Bellona,Ter Goes,Dofin,Meerminne,Koning David,Gideon,Eendraht",
	"Gekrunde Lijfde,Achilles,Dofin,Utrecht,Thetis,Gulden,Dofin,Maas,Waakzaamheid,Middelburg,Nassau,Vitte Eenhoorn,Wapen van Hoorn,Zutphen,Grot Zutphen,Overissel,Utrecht,Vest Kapelle,Gelderlant,Katarina",
	"Roskam,Rotterdam,Wapen van the Netherlands,Kasteel van Medemblik,Wapen van Medemblik,Monnikendam,Wapen van Monnikendam,Vergulde Zon,Gojes,Groningen,Prinses Rojal Maria,Meermin,Vogelstruis,Zeelandia,Fereenigde Provinsien",
	"Edam,Wapen van Edam,Haarlem,Monnikendam,Gulden Star,Bommel,Brederode,Burcht van Alkmaar,Enkhuizen,Wapen van Enkhuizen,Leevarden,Neimegen,Fasant,Elsvoud,Lejden,Wapen van Lejden,Nord the Netherlands,Domburg,Haas,Admiral Generaal",
};
