string DLG_TEXT_BASE [221] = {
	"English fort",
	"French fort",
	"Spanish fort",
	"Dutch fort",
	"Pirate fort",
	"! I am ",
	", the Captain of this here fleet of ",
	". What brings you aboard?",
	"! I am Captain ",
	". What brings you aboard my ship?",
	"They call me ",
	". I have business with you!",
	"Well, I... just came by to say hello!",
	"Have you not noticed, ",
	", we are engaged in battle? This is no time to fan your gums!",
	"Too true! I'll just be getting back to my ship, then.",
	"I'm all ears, ",
	"What's the word on the archipelago?",
	"Know you not who I am? Methinks it ia apparent that the cannons on this vessel have in them the power to turn your wash-tub to a veritable sieve. But let's us decide this amicable-like. A ransom would surely suffice.",
	"Ah, the sea... and we are all alone... In exchange for your safe passage, what say you to making my boys a bit... happier?",
	"Whence come ye?",
	"Shall we trade?",
	"I'm looking for a pirate ship, operating in these waters. Have you seen anything suspicious?",
	"Do you have time for a game of cards?",
	"I think it is time for me to get under sail.",
	"Who you be wanting is the squadron commander. I be in no position to say. The man's name is ",
	", and ye can find him on the ",
	"Thank you. I'll do just that.",
	"Why not?",
	"Let's go see the merchandise.",
	"Hold on, I've changed my mind.",
	"What do you suggest?",
	"How's about we throw down the cards, for a flat sum?",
	"Why don't we rattle the bones in poker-joker?",
	"Sounds... interesting, but I have duties to attend to.",
	"I'm not gambling with strangers!",
	"As ye wish.",
	"Sounds good! I need a break from all this ship business...",
	"Marvelous.",
	"What rules are we playing by?",
	"Well, shall we begin?",
	"No, this isn't really my thing...",
	"What be your wager?",
	"100 coins sound good?",
	"Feelin' frisky. How about 500 gold?",
	"Actually. It's getting pretty late, isn't it. ",
	"Be ye knave? Ye be skint on me, boy!",
	"It happens.",
	"Better stop there, if I want to pay my my ship's upkeep...",
	"A pity.",
	"Fine. 100 it be...",
	"Begin!",
	"You aren't pulling me leg, boy? Come back when ye may pay the bounty.",
	"I shall!",
	"Nah, this kind of wager never leads to happy endings... ",
	"As ye wish.",
	"Then 500 it be!",
	"Begin!",
	"My mom always told me not to gamble with strangers.",
	"As ye wish.",
	"Sure! A bit of leisure never harmed a man. Only his wallet.",
	"Marvelous.",
	"So what are the house rules? Or. Ship rules, I suppose? ",
	"Nah, that enough for today. Duty calls. And so on.",
	"As ye wish.",
	"Then let us begin!",
	"Nah, that's not my thing.",
	"What be the wager?",
	"How's about 50 coins a die?",
	"Let's go for broke. 200 gold per die.",
	"Whoa, I didn't notice how late it was getting...",
	"Ye be marked as a scallywag and a shark. I'd more well play the bones with Davy Jones himself.",
	"What rot! I don't need to cheat.",
	"Be ye knave? Ye be skint on me, boy!",
	"It happens.",
	"That's as far as she goes. If I don't stop soon, they'll think me a shark and throw me to my kind...",
	"A pity.",
	"Fine, 50 coins it be.",
	"Begin!",
	"Ye be marked as a scallywag and a shark. I'd more well play the bones with Davy Jones himself.",
	"All lies! Who needs to cheat when you're as good as me?",
	"I heard tale of your aptitude. I be a practical man. If I play ye, it shan't be for value. ",
	"How about we lower the stakes.",
	"Sorry, it's getting pretty late.",
	"You aren't pulling me leg, boy? Come back when ye may pay the bounty.",
	"I shall!",
	"Nah, this kind of wager never leads to happy endings... ",
	"As ye wish.",
	"Sounds good. Let's do 200 coins a die.",
	"Begin!",
	"That be me own providence. Why need have ye to know? ",
	"As ye wish.",
	"I set sail from ",
	"I'm wondering, what are the prices like at the store here? ",
	"It's about time I move on, I think. ",
	"I told ye, don't be irking me with your trifles.",
	"Quite right. Later, then.",
	"Here, take my catalog... (Information is saved in the F2 'Trade' menu)",
	"Thanks!",
	"Har har! We have us here a comedian. And I have me more than just this one ship. A pity ye be not so fortunate. Get ready to taste the brine, boy.",
	"It's not how big it is, but how you use it. Or so they tell me.",
	"One Captain to another, 'tis a pity ye chose my ship to work your foul schemes. Still, I'll let ye have your pride. I'll let ye go down with your own ship. ",
	"Oh yeah, well... The sharks have yet to see today's menu!",
	"Aye, I be well aware of your extravagances. Be on your way, but don't think that be the last ye hear from ",
	"!",
	"Splendid. A sum of ",
	" will do me justly, ",
	"Oh, come on. Can't take a joke?",
	"How curious! You know, that reminds me... ",
	"Just one more thing...",
	"Thank you. With respect... no.",
	"All the best.",
	"Get off my ship!",
	"I'm going, I'm going...",
	"We're through here. I've nothing more to tell you, ",
	"I see. Well, 'til next the sea washes us together!",
	"Go on, take it! Then get out!",
	"Splendid!",
	"Stop right there! You know, you could hurt someone with that toy. What do you want from me?",
	"To kill you!",
	"To capture you.",
	"Give us the map, Billy.",
	"We shall see about that!",
	"There's nothing to see...",
	"Fine, you win! Whatever!",
	"You fool! Have you no concept of time?",
	"Just take it!",
	"All right, now surrender.",
	"So let's get this straight. You barge in here, trash the place, deprive me of all my belongings, and now want to enslave me? Are you actively trying to annoy me?",
	"Well, you'll get over it. Here, let me help you!",
	"No, I didn't see anything suspicious. Leastwise, nothing like a pirate ship.",
	"I see.",
	"You bashi-bazouk! Surrender in the name of ",
	"! Your life will be spared for that day in court when you will answer for all those ",
	" ships that you have plundered.",
	"Ha! How about you surrender first!",
	"I'm listening, but don't dawdle. We're in battle with ",
	", and I have to lead my men. So state your purpose. ",
	"Well, that's why I'm here, ",
	"Well, no sense getting underfoot. I shan't take up any more fo your time. Farewell, ",
	"I'm not authorized to discuss these matters. Who you want to talk to is ",
	", our squadron commander. You should find him on the ",
	"Thank you. I'll go look for him.",
	"What are you talking about?",
	"I can help you crush the ",
	" fleet and sack the town. If we succeed, we split the loot.",
	"Actually, never mind. It's but a trifle. Farewell, ",
	"You again? I thought we were settled?",
	"Oh, that's right. So we are.",
	"And pray, what share were you counting on?",
	"Half.",
	"A third.",
	"A quarter.",
	"Well, Captain, as I will take the colony in any case, I fear I shall not require your services - or those of any other brigand!",
	"Bold words, ",
	". Surely no man is immune to misfortune.",
	"In that event, I shan't delay you further, ",
	". Have a good plunder!",
	"On the other hand, battle has done its number on my ships, and reinforcements would certainly not hurt my odds. If you can agree to ",
	", then I believe we may be on the verge of a deal.",
	"Fine by me, ",
	". My crew will take the town by storm, provided you cover us with your ship cannons.",
	"My talents don't come that cheap, ",
	". I beg your pardon, I know you have much better things to do. Farewell.",
	"My squadron has well enough ships to turn this fort to dust; it's just a matter of time. Now please leave my ship, as victory awaits me!",
	"Well, in that case, ",
	", I take my leave. Farewell!",
	"That fort's dang-blasted cannons have badly compromised my ships, and I fear we are now at a great disadvantage. Lest fortune turn against us, I accept your conditions, and your assistance.",
	"Excellent, ",
	"! Then I take upon myself the capture of the fort itself. Your ships will cover my men, under fire of their cannons.",
	"A bold offer, Captain, considering your ",
	" ships, to my own ",
	". I can offer you ",
	", and think it a fair due.",
	"Fair do, ",
	"! Then I take upon myself the capture of the fort itself. Your ships will cover my men, under fire of their cannons.",
	"I fear, ",
	", that I disagree. And I believe that brings our parlay to an end. Farewell.",
	"Straight when the fort is fallen, our assault troops will land and continue the battle on the city streets - where, I hope, we shall meet.",
	"So be it. 'Til next the waves sweep us together, ",
	"I think I will accept your conditions. A joint operation will raise my chances of besting this encounter. If we do pull this off, you will take your ample share.",
	"I'm glad we've met such an amicable accord, ",
	". I shall out my men to the fort, at once!",
	"A bold offer, Captain, considering your ",
	" ships, to my own ",
	". I can offer you ",
	", and think it a fair due.",
	"Fair do, ",
	"! Then I take upon myself the capture of the fort itself. Your ships will cover my men, under fire of their cannons.",
	"I fear, ",
	", that I disagree. And I believe that brings our parlay to an end. Farewell.",
	"Battle has done its number on my ships, and reinforcements would certainly not hurt my odds. If you can agree to ",
	"I'm glad we've met such an amicable accord, ",
	". I will at once my men to the fray, and lead the direct assault.",
	"Hullo, my dear Captain! Fierce as she was, the town crumbled before us. We've taken ",
	" in gold. By our deal, that gives you a full ",
	". Take it, you have to no doubt of mine earned it to the bit. Now excuse me, for I have pressing concerns...",
	"In that case, ",
	", I take my leave. Farewell!",
	"An albatross tells me you aided our squadron in capturing the ",
	" colony - ",
	"! We are in your debt, ",
	"Greetings, Captain! Is there a matter that you'd like to discuss?",
	"Not really, ",
	". Farewell!",
	"I am listening, but speak quickly; I am in a hurry. My mission is both grave and secret. Namely, to sink whatever ships might present our convoy a threat on the open waves.",
	"In that case, I shall delay you no longer. Farewell, ",
	"I'm not authorized to discuss these matters. Who you want to talk to is ",
	", our squadron commander. You should find him on the ",
	"Thank you. I'll do just that.",
	"not a single ship",
	"one ship",
	"two ships",
	"three ships",
	"four ships",
	"five ships",
	"six ships",
	"all of it",
	"half the take",
	"a third of the take",
	"a quarter of the take",
};
