string DLG_TEXT_BASE [231] = {
	"Unfortunately, my son, you will find no shelter here. I bid you, run!",
	"My son, half the garrison is in the streets for you! The church may be open to the suffering, but I'm afraid you will find no shelter here...",
	"My son, you must flee! I implore you to hurry!",
	"You degenerate! What business have you in a place of worship? I insist that you leave immediately, sir. Quick, now, before the soldiers find you and start a bloodbath on God's doorstep!",
	"Leave this place now, heathen! I will not shelter a man such as you!",
	"Leave this place now, heretic! I have enough problems without a murderer under this roof!",
	"Pipe down, Padre...",
	"Yeah, like I need your help...",
	"You'd do well to shut your trap, pops...",
	"Yeah, yeah. I'm not aiming to take root here, Padre...",
	"Welcome to the bosom of the lord, my son.",
	"Hey, Father.",
	"What?! You're not my dad! How dare you speak to me like that!",
	"I must ask you to leave this house of the Lord. We have nothing more to talk about this day.",
	"That's right!",
	"Out, heathen! Get out! You shall not sully the Lord's chamber with your pestilence!",
	"Not like I was planning to move in. ",
	"God bless you and your cause... I trust you've a reason to come to me?",
	"Padre, the tavern's under siege from a mob of drunken merchants. They've got it in their fool heads there's a werewolf camped out in there. I snuck in for a look, and all I found is a traumatized young man. He tells me he wants to confess, so here I am.",
	"Bring this person to me. I'll hear his confession here, under God's roof.",
	"I get you, Padre.",
	"I want to make a donation.",
	"I want to donate to a righteous cause.",
	"I think it's about time for a confession.",
	"I need to confess, ",
	"Padre.",
	"Father.",
	"I've got a problem, ",
	"Padre.",
	"Father.",
	"I'm here on business, ",
	"Padre.",
	"Father.",
	"Sorry, it's about time I got going. ",
	"Of course, my son. How much would you like to contribute?",
	"Uh. Forgive me, Father, but no donation today.",
	"Well. Nothing dramatic. All I can manage is 100 piasters...",
	"How's about 1000 piasters. That should do it.",
	"I'm pretty flush right now. What do you say to 5000 piasters?",
	"Father, I want to make a donation - but not in my own name. I'm just here as a favor. ",
	"Hmm... Well, that's your decision, and you have the right to change it. Just remember your coming judgment, and prepare as you see best.",
	"Yes, well. My appointment with Peter's a way off yet. Mind if we change the subject? ",
	"Sorry, Father. Time's a-wasting.",
	"In the name of the Lord, I thank you, my son, for your generosity.",
	"Got a minute, Father?",
	"Sorry, Father. Time's a-wasting.",
	"In the name of the Lord, I thank you, my son, for your generosity.",
	"Got a minute, Father?",
	"Sorry, Father. Time's a-wasting.",
	"In the name of the Lord, I thank you, my son, for your generosity.",
	"Got a minute, Father?",
	"Sorry, Father. Time's a-wasting.",
	"Of course, my son. I'm here to listen.",
	"On second thought, maybe later. ",
	"I'm such a bad man, Father...",
	"We all have our sins, child.",
	"Not like mine. I... I've sunk and raided ships. I've killed... I don't know how many.",
	"Were any at sail under the banner of ",
	"Well. No, of course not.",
	"Actually... some, yes. ",
	"Then the Lord shall forgive your transgressions.",
	"Thank you, Father. That's... interesting to hear. I guess I'd better get going.",
	"Then I'm afraid there is no hope for you. For such a sin there is no forgiveness.",
	"Well, uh. Thanks for the comfort, Father.",
	"What brings you here today?",
	"I've got just one question for you, Padre...",
	"I wanted to ask you about doing some good in the Lord's service, and in the service of ",
	"How's the parish going? You need any help around here?",
	"Father",
	"Padre",
	", I've got a question for you. It's of a financial nature. ",
	"I'm... not doing too well. ",
	"Father, there's something I want to give you. See this queer tin box?",
	"Father",
	"Padre",
	", I've been sent here by a certain Governor ",
	"cave",
	"cave cleared",
	"grotto",
	"grotto cleared",
	"dungeon",
	"dungeon cleared",
	"Father, ",
	" cave cleared of evil. So there we go, the locals have nothing to fear now. ",
	"Father",
	"Padre",
	", I'm here about that night watchman position. ",
	"I've changed my mind. I've got other things to do.",
	"It gives me pause to discuss this, but it seems I have no choice. You see, if all is part of God's great plan, nothing in life happens by chance. You may well be the tool God has sent us to lift the pestilence on this land.",
	"I don't quite get you, Father. What's got you so riled up? ",
	"Pray continue, Father.",
	"My son, I have a simple task for you. We need a night watchman, but not an old man with a rattle or a hapless nun. Some odd characters have started to come to this church. The thing is, they don't pray. They just look around the place. The brothers are a getting a bit worried...",
	"And what about you, Father? You worried, too?",
	"All is well in the parish, my son. Thank you for the offer.",
	"Well, if everything's in order, I guess I'll be off.",
	"cave",
	"The problem is that the cave near our city has become a haven for evil.",
	"grotto",
	"The problem is that the grotto near our city has become a haven for evil.",
	"dungeon",
	"The problem is that the cavern near our city has become a haven for evil.",
	"There are more and more talk of strange happenings. ",
	" Whence do such nightmares enter God's dominion? The people are scared. Their hearts grow weak with fear...",
	"How may I serve you, Father?",
	"You brave man. In my hands, you shall become the sword of God! Disperse the evil, and all your sins shall be absolved with interest...",
	"Sounds good to me, Padre!",
	"Sorry, Father. Plain can't do it. Maybe next time. ",
	"Oh, my son. That's quite unfortunate. I was counting on your aid...",
	"In time, I think it will all balance out...",
	"Very good. Go forth, my son. And may you find strength!",
	"Leave everything to me, Father.",
	"Excellent, my son! You have done yourself nobly. Know that your relations with ",
	" shall duly improve.",
	"Well. I'm just over the moon, Padre ",
	"I shall pray for you. Go, my son. Be true to yourself, and be honest before God.",
	"Righto, Father.",
	"cave",
	"cave",
	"grotto",
	"dungeon",
	"Father ",
	" says you chased the evil spirits from ",
	", close out of town. A God-pleasing deed, I tell you.... ",
	"Did you hear -- some captain, at the request of our Father, cleansed ",
	" not far from our town, of demons. What a brave soul! ",
	"Captain, was it you who cleansed of demons ",
	" not far from our town. You should know we are very grateful! ",
	"Precisely. And believe me, it's not as simple. When such things happen, it is a sure sign of a coming robbery. It seems that the church plate caught someone's eye... Well, do you agree to spend a few nights in the church? ",
	"No, I'd rather not, Father. Please forgive me.",
	"I agree, in principle. But how many nights would I have to guard the church? It's possible that no one will show up, and your odd characters are just ordinary cutthroats that are too shy to express their religious fervor among people.",
	"That might be, but unlikely. All in all, you'll have to stay here for three nights. If no one comes, we shall take your task to be completed successfully.",
	"All right then, this suits me fine. I agree!",
	"Then start tonight. And remember -- you will have to remain inside the church from midnight to six o'clock in the morning.",
	"I understand, Father. For three nights you won't have to worry about your church plate.",
	"My son, you haven't spent even one night there. Go, fulfill your duty, leave me be....",
	"Very well, Father.",
	"My son, you did not fulfill your contract -- we agreed on three nights....",
	"Yes, I remember.... I'll keep on guarding.",
	"My son, I already know that you have captured the thieves. And even though killing inside a God's temple is a sin, He shall forgive you.",
	"Thank you, Father....",
	"My son, you have admirably completed your nightly service in the church. Did you see anything strange?",
	"No, Father, everything was calm. I didn't see anyone at all.",
	"Hmm...It appears we might have been mistaken. In either case, this is a wonderful outcome! I can't offer you money as a reward, but I can say that your sins before our Lord and ",
	" will be diminished. ",
	"Thank you, Father.",
	"People say you guard our church at night....",
	"Guarding the church at night is a God-pleasing deed. Thank you.",
	"Our Father, ",
	", mentioned that you stood the night watch in our church.",
	"In addition, it's in my power to diminish your sins before ",
	", which is what I'm doing. Besides, I shall pray to your health, and believe you will soon feel the healing power of the praying to our Lord!",
	"Great-many thanks, Father!",
	"People say you've captured thieves in our church! Our gratitude is immense!",
	"You know, all town's residents are grateful that you prevented the plundering of our church. Thank you!",
	"Our Father, ",
	", talks only of how you've rescued our church plate that night....",
	"Your health ",
	", and wounds will heal by themselves. Just avoid bloody skirmishes.",
	"I feel better already, and will try to stay away from violence for a while.",
	"Your health ",
	", and though the wounds will heal, you should try to improve it.",
	"What would I need for that?",
	"And why is my health deteriorating?",
	"It's very simple, my son -- it diminishes when you are wounded. Such events are not without consequence, and with every injury your health deteriorates further, eventually leaving you too weak to fight.... Your crew, seeing the weakness of their leader, would lose their respect for you. This, however, will make you more careful and your defensive skills will improve over time. Timely rest and minimization of injuries will help you always remain full of strength.",
	"Thank you for enlightening me.",
	"Prayer and rejection of violence, my son. Then Lord will give you back what you have lost.",
	"Would you pray for me?",
	"So not a chance? Hmm.... Thank you for giving me hope.",
	"Me? Well, it's possible. You, however, would have to give a donation to the Holy Church.",
	"How much?",
	"With pleasure! How much are we talking about?",
	"I'll manage somehow ....",
	"My son, I'm already praying for your good fortune. Praying will take all of my time 'til the end of the month.",
	"Thank you, ",
	"Padre.",
	"Father.",
	"Hundred thousand in gold would be a sufficient payment for the miracle of healing.",
	"How much?! You are insane. I'll pay such a sum once I rob a few churches.",
	"That's too much for me. Looks like it's true -- money can't buy health.",
	"I agree!",
	"Good. Your health will somewhat improve. However, you should avoid skirmishes and keep yourself safe, otherwise the power of the prayer will dissipate. I will have to spend an entire month in prayer for your mortal body.",
	"Thank you. If something happens, I'll come again in a month.",
	"We have nothing further to discuss.",
	"And there's no need.",
	"Stray soul, don't you want to confess your sins, cleanse your soul and lighten your fate?",
	"And who would you be?",
	"With joy and piety, Padre.",
	"Get lost, hypocrite.",
	"I am the local chaplain. I ease the suffering of prisoners, give the last rites before and perform the burial service after executions or council before the long trip to the mines.",
	"Are there any other options besides hard labor or death by a firing squad?",
	"I'm ready to repent, Padre.",
	"I am completely innocent. I don't need any of this.",
	"Of course, my son -- not all live 'til the announcement of the sentence, to many the dungeon becomes the eternal refuge. Are you ready to confess your sins?",
	"I am ready to repent, Padre.",
	"I am completely innocent. I don't need any of this.",
	"Persistence in heresy and apostasy will not lead you to the Lord's kingdom. Take holy water and repent!",
	"I insist I don't need this. Go away!",
	"I am listening, my son.",
	"I've sinned, Padre, committed many crimes, robbed and killed the innocent, but I did not act alone. Loyal comrades aided me. Would you send them a note from me?",
	"I've changed my mind. Leave me.",
	"So you are a criminal ringleader as well? And you're asking me to pander your devious plans? Never! I will insist on your immediate sentencing.",
	"What a fool you are, even if in a priestly robe.",
	"And who is the good soul that gave this donation?",
	"Hmm.... The madame at the local bordello.",
	"I would prefer not to name names -- a donation can be anonymous!",
	"Yourself a sinner, pleading for another? You should be more concerned about your own soul, as we all will stand before God!",
	"Without a doubt. I hope the Lord will be merciful to me.... So, how about a donation?",
	"Away, Satan! Take your filthy money and leave!",
	"Father, why so?! We came to you with our souls wide open, and you ....",
	"I am glad you are helping sinners to find the path to our Lord. You will be rewarded in Heaven for that!",
	"That would be great! So, how about a donation?",
	"I cannot accept money obtained through sin. Return it to this whore, my son. You can't find a path to God through money.",
	"Pity that you are rejecting her. Pity...",
	"To accept this money, not knowing who it came from....",
	"Yes, Padre, precisely. Accept the donation of a pure heart!",
	"To accept this money, not knowing who it came from? Are you insane?! What if there is blood on it!",
	"Father, there's blood on all money....",
	"I accept it, my son. Go, tell this to the whore.",
	"Okay, Padre. Thanks a bunch.",
	"I accept it, my son. You can go and tell this to whoever offered it.",
	"Okay, Padre. Thanks a bunch.",
	"Leave here, the devil's spawn! And don't you dare to appear before me again!",
	"Huh, fine then.",
	"Such is my decision. Go with peace, my son.",
	"Farewell, Padre.",
	"That's what you think, reprobate! Get out of the temple and don't come before me again!",
	"Oh yeah? Fine, I'm leaving....",
	"My son, the Church rescues the lost. Werewolves, witches and warlocks are counseled to the true path by the Holy Inquisition. Or by the simple town-folk, if God chooses them to be His instruments. Who are we to interfere?",
	"But what if he is truly innocent? It's strange... that I have to appeal to the conscience of a priest!",
	"Don't be hasty, my son. If his soul is innocent, it'll go to the paradise! But if I hear a confession of a devil incarnate.... This, however, can be put to a test. No spawn of Satan can enter the God's temple. Bring him here, and if he is not struck down by the divine punishment, then I, naturally, will not refuse him a confession.",
	"I'll bring him!",
};
