string DLG_TEXT_DUEL [98] = {
	"Cur! You dare insult me?!",
	"Those words shall cost you dearly!",
	"You have tarnished my pride, ",
	"! This cannot go unrepaired.",
	"How dare you! A wise tongue would disclaim those words!",
	"What's that?! I don't even want to mess my saber on you!",
	"I'm always at your service!",
	"I'm not going to pick my words wisely when I'm talking to garbage!",
	"I didn't mean that...",
	"I was hot-tempered...",
	"It was a mistake. I ask your forgiveness.",
	"I mistook you for someone else, ",
	". Please forgive me.",
	"I'll clip your ears!",
	"I'll cut out your heart!",
	"I hope that you'll immediately put forth your apologies, or I won't be responsible for myself!",
	"Do you understand what that means?",
	"I hope your sword is as fast as your tongue!",
	"My dagger will speak for me.",
	"I challenge you to a duel!",
	"This is a matter of honor!",
	"I suppose I am not yet ready to meet the devil!",
	"I think it's not worth getting so hot over it! They're only words!",
	"I just remembered that I'm late. They're all...",
	"Oh! It looks like my ship's leaving.",
	"You'd better deal with rest first and then we'll talk.",
	"We've confirmed everything already.",
	"Oh, how could I forget...",
	"Duel?! You're not worth the time. Get out!",
	"Duel? That's too much honor! Get out!",
	"Okay, okay...",
	"I can wait.",
	"We'll see about that!",
	"You don't say?! I will see the color of your blood now!",
	"A duel, you say? I'm all for it. Shall we use sabers, or pistols?",
	"I'm guessing you don't even know how to hold a saber?",
	"You'll be begging for mercy on your knees.",
	"I'll finish you with these hands, villain!",
	" Or we can go to sea and see who's capable of what?",
	"A duel?! Ha, I'll crush you like a flea! Choose how you'll die!",
	"At sea, I have no equals.",
	"My ship will send your old washtub to the bottom!",
	"I've changed my mind.",
	"I don't see your ship in port, though.",
	"Get lost until you find yourself a washtub!",
	"My mistake...",
	"... Then I'm leaving you.",
	"Well, then. I'll wait for you by the bay exit.",
	"You won't have to wait long.",
	"Ready your blade, that we might see the color of your blood!",
	"Well, if that's how you want to die...",
	"We'd better lose all these witnesses. I know a place outside the city gates; let's meet there in ",
	" hours.",
	"Hang about, friend. We don't want to let the whole town in on this. Meet me by the city entrance, in ",
	" hours.",
	"Well, if you're in such a hurry to die...",
	"Damnation! I shall send you to hell, once and for all!",
	"Sorry, never mind...",
	"We'd better take this outside the city gates. I'll meet you out there in ",
	" hours. And don't be late!",
	"This is no place to settle our... differences. Better we do it outside the city. Wait for me there in ",
	" hours.",
	"Enough with the honor! Defend yourself!",
	"I ain't got the time! Ready your blade!",
	"Sure, I'm up for a walk.",
	"I guess you're right. I'll see you outside the gates.",
	"let's go outside.",
	"Enough with the honor! Defend yourself!",
	"I ain't got the time! Let's settle this right here and now!",
	"Well, if you're in such a hurry to die...",
	"Damnation! I shall send you to hell, once and for all!",
	"Sure, I'm up for a walk.",
	"I guess you're right. I'll see you beyond the gates.",
	"I'll wait for you there.",
	"Don't be late.",
	"Well then, ready to meet your maker?",
	"Sure. Let's see who meets him first!",
	"Hey, uh, actually, I wanted to apologize for losing my head back there...",
	"Listen, I thought about it and... I was wrong. I'm sorry.",
	"Listen, brother, let's forget about it! It was the rum talking!",
	"It's too late now. Now only your blood can bring me proper satisfaction!",
	"Would you like some cheese with that whine? I said out with your steel!",
	"No! I demand satisfaction!",
	"You're a disgrace to your family! Ready your sword!",
	"I guess we both got a bit carried away.",
	"Ah, what the hell. Bygones be bygones, am I right?",
	"I suppose you're right. No good in spilling blood for no reason.",
	"My nobility knows no bounds. Consider yourself forgiven!",
	"All right, g'wan - gedoutta here!",
	"Then scat, 'fore I change my mind.",
	"Well, In that case, I'll let you get back to whatever you were doing.",
	"Then I think you had better leave before I change my mind.",
	"I was just leaving...",
	"Get lost!",
	"Get out of my sight, lest I change my mind.",
	"How may I be of service?",
	"Did you want something?",
	"I'm going.",
};
