string DLG_TEXT_BASE [189] = {
	"The alarm's been raised in the city. Everyone's out looking for you! If I were you, I wouldn't hang around here.",
	"All the city guards are hounding the city for you. I'm not dumb enough to stand around chatting with you.",
	"Run, pal, before the soldiers make mincemeat out of you...",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Filthy murderer! Out of my house! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Heh. The alarm's no problem for me...",
	"They've got nothing to catch me for.",
	"Shut your trap, ",
	", or I'll rip out your rotten tongue!",
	"Heh, ",
	", and still the same - after pirates! I'll tell you what, buddy. Sit quiet, and you'll live...",
	"A broken version of the game.",
	"Hey, Doctor Blood! ",
	"Great to see you, Peter Blood.",
	"It's good that you've come around here, ",
	". How's Colonel Bishop doing these days?",
	"Alas, I am leaving, ",
	". 'Til we meet again.",
	"Greetings, ",
	". I don't think we've met. I am ",
	", the head of the port.",
	"Hail, ",
	". I am ",
	", Captain of the good ship '",
	"Greetings, ",
	". Do you have a matter for me?",
	"Hello, ",
	". I saw your ship come into port and knew that you would come to see me.",
	"Ah, Captain ",
	". What brings you to me?",
	"Hello, ",
	". I want to talk with you.",
	"Wonderful. I am at your service, ",
	"Can a man find work here? Or a contract?",
	"May I leave one of my ships for a time?",
	"I want to take my ship back.",
	"I'm here on financial matters.",
	"I'm here on orders. Man by the name of ",
	" sent me. I must take something...",
	"I'm interested in the Captains who've been noted in the port register.",
	"I have another matter to attend to.",
	"Thank you. Goodbye.",
	"You were to find a Captain named ",
	" and to return the ship journal to him. Have you done so?",
	"No, I have been unable yet...",
	"You've signed up to find the stolen ",
	"ÿ. Until you finish this mission, a new assignment is out of the question.",
	"Hang on, I'm still working on it.",
	"I want to decline from pursuing your mission.",
	"You promised to find me the stolen ",
	"ÿ. Have you done so?",
	"Yes, I found it, at the port on a raid. You can take it.",
	"Hang on, I'm still working on it.",
	"I want to decline from pursuing your mission.",
	"By damn, yes! Have I got a job for you!",
	"Ha! You're just in the nick of time! I have a problem that needs to be solved.",
	"Oh, yeah! 'Course I got work! Problem is, y' know, they've really got me in a pinch...",
	"Tell me the point of the matter, ",
	"The Governor always has work - he just loves to see the city prosper. Then there might be interested merchants in the tavern. Sometimes the store hires Captains for freight.",
	"One more question.",
	"Thank you. Goodbye.",
	"Hm, that's unfortunate. In that case, there can no question of new work.",
	"Understood. I also wanted to say this...",
	"One Captain forgot his logbook. What a ditz! Anyway, I need you to catch up to him and return the lost item.",
	"That's doable... I'll take the job!",
	"No, I don't want to do this. That's his problem, anyway...",
	"One of the ships was stolen off my lot. I need you find it and return it to me.",
	"Hm. Well, then. I'm ready to start the search.",
	"Hm, sorry, but I don't want to search the seas for another man's lost ships.",
	"Excellent. So here's the logbook... Whoo, this takes a load of my shoulders! Losing a ship's log is a horrible thing. I worry about these Captains.",
	"That's for sure! Now, tell me more about this clumsy Captain.",
	"Oh, sure! His name is ",
	". He's the Captain of the ",
	" they call '",
	"ÿ. It left for the sea not too long ago, and went to ",
	"Understood. Well, then. I'll definitely find him! How about the payment?",
	" he'll sort you out. It's in his interest. Just try to find him soon, and everything will be okay.",
	"All clear. So I'm off...",
	" which is in ",
	"Wonderful! You know, the ship's real owner... it's not the last guy who had it. So you see, it's very important to me. I'll play handsomely for the work...",
	"Understood. Please tell me in more detail about the ship, and the circumstances under which it was stolen.",
	" they call '",
	"ÿ was stolen one evening ",
	" ago. The watchman was killed.",
	"Hm, they have probably got a good distance by now. In general, there can be no talk of a hot trail...",
	"Yes, correct. But there was no point in stirring up a panic immediately. If the military catches up to the ship, they'll blow it to pieces. And that's certainly not ideal.",
	"Understood. Well, then. I'll start the search. I hope I'll get lucky.",
	"Hm. Well, then. That's a pity. Though it would have been difficult to hope for the best.",
	"Yes, too much time has passed since it was stolen.",
	"Well, then. Thanks for the help, even though this didn't turn out to be blessed with success.",
	"Oh, not at all...",
	"Excellent! However, I think that isn't exactly the ship that was stolen... Though, well, it doesn't matter! I'll take it from you.",
	"Yes, certainly.",
	"Superb! You've really helped me. I can imagine how difficult it must have been.",
	"Yes, certainly.",
	"I am prepared to pay you a reward, to the sum of ",
	". I am sorry, but I can afford no more than that.",
	"Don't worry, that should suffice. Thanks and take care.",
	"There are a number of registered captains. Who in particular do you want to know about?",
	", Captain of the ",
	"I seem to have no one on my list who would interest you...",
	"I see. Well, thanks for the info.",
	"All right, then. Let's see... Aho, here we are! ",
	"Just a moment... Ah, there she is! ",
	"All right; here goes. ",
	"Captain ",
	" - left our port, bound for ",
	"Thank you. I'd like to see the rest of the list...",
	"That's it. I'm all Captained out. ",
	" which is in ",
	"All right, then. Let's see... Aho, here we are! ",
	"Just a moment... Ah, there she is! ",
	"All right; here goes. ",
	"Captain ",
	" - left our port, bound for ",
	"Thank you. I'd like to see the rest of the list...",
	"That's it. I'm all Captained out. ",
	" which is in ",
	"All right, then. Let's see... Aho, here we are! ",
	"Just a moment... Ah, there she is! ",
	"All right; here goes. ",
	"Captain ",
	" - left our port, bound for ",
	"Thank you. I'd like to see the rest of the list...",
	"That's it. I'm all Captained out. ",
	" which is in ",
	"All right, then. Let's see... Aho, here we are! ",
	"Just a moment... Ah, there she is! ",
	"All right; here goes. ",
	"Captain ",
	" - left our port, bound for ",
	"Thank you. I'd like to see the rest of the list...",
	"That's it. I'm all Captained out. ",
	" which is in ",
	"All right, then. Let's see... Aho, here we are! ",
	"Just a moment... Ah, there she is! ",
	"All right; here goes. ",
	"Captain ",
	" - left our port, bound for ",
	"Thank you. I'd like to see the rest of the list...",
	"That's it. I'm all Captained out. ",
	" which is in ",
	"Generally, yes. But for the moment I cannot accept a ship - there's no room at the docks.",
	"That's too bad.",
	"Which ship specifically do you want to leave?",
	"Thanks, but no need.",
	"Hrm. I don't see your ships in port.",
	"Right, I just wanted to inquire if I might moor my ship in your port?",
	"Let's see what kind of ship it is.",
	"Um. Sure, okay.",
	"Nah, changed my mind.",
	"Let's see what kind of ship it is.",
	"Let's see what kind of ship it is.",
	"Um. Sure, okay.",
	"Let's see what kind of ship it is.",
	"Um. Sure, okay.",
	"Nah, changed my mind.",
	"Let's see what kind of ship it is.",
	"Um. Sure, okay.",
	"Nah, changed my mind.",
	", class ",
	", cost of mooring ",
	"Yeah, I'm okay with that.",
	"Nah, changed my mind.",
	"I'll be as pleased as you are, so long as you cough up the cash.",
	"Oops... I'll come back later.",
	"All right. You can take it whenever you like.",
	"Thank you.",
	"Which ship specifically do you have in mind?",
	"Nah, I changed my mind.",
	"Do you have room for one more ship?",
	"Yes, exactly. Thank you.",
	"Hmm... I don't see your flagship in port. And this is the only place you can pick up your ships.",
	"All right, I'll be back for them later.",
	"You taking something, then?",
	"Yeah.",
	"Nah, changed my mind.",
	"You taking something, then?",
	"Mm.",
	"Nah, changed my mind.",
	"You taking something, then?",
	"Sure am.",
	"Nah, changed my mind.",
	"An absent-minded captain ",
	" and headed for: ",
	"A cap-napper ",
	" came out of ",
	" en route to ",
};
