string DLG_TEXT_BASE [98] = {
	"Spy? Turn in your weapons! Follow me!",
	"Enemy agent! Grab him immediately!",
	"Shut up, deadbeat!",
	"Be that as it may!",
	"Who are you, and what do you want here?",
	"Stop! Who are you? On what basis are you trying to enter the fort?",
	"Officer, I have a ",
	", so I'm here on legal grounds. Please acquaint yourself with...",
	"Pirates in the fort?! Hold him!",
	"That's a pirate. He's sniffing for something around here! Hold him!",
	"Yeah, I'm a pirate. What's it to you? ",
	"Ha! Just try to grab me...",
	"What, you can't see the flag swaying on my mast ",
	"I threw anchor at ",
	" under the flag of ",
	". Something's still unclear to you?",
	"Ah, Captain, how great it was with you, on the sea! How many ships did we sink, under your command? And here...",
	"And here, my friend, charming women, who don't exist at sea, constantly hover over you.",
	"Captain, what's with the punishment?! We aren't land rats!",
	"Calm down, sailor! You're on an important and honored post, so no can do.",
	"How's the sea, Captain? Will we ever see it again?",
	"Of course, sailor! When the watch changes, go to the pier and enjoy the sea for as long as you want.",
	"I rush to inform you, Captain, that we're all aiming to get back to sea. We've had it up to here with this shore duty!",
	"I'm tired of this whining! You've got enough on you to get drunk on land! Serve there, where the Captain put you. Otherwise, I'll have to string someone up as a warning.",
	"I'll tell you a secret, Captain. The new governor is a bribe-taker and treasury-looter. Not that it's any of my business...",
	"You're right, corsair. Your job is to keep your post and maintain order. Stringing up the governor, now, that's my job. Good job!",
	"Thank you for not forgetting about us, Captain! We'd go to hell and back for you!",
	"I know you strangers! You only love gold. There's going to be drinking in the tavern tonight, my treat. Don't forget to stop by.",
	"Argh, Captain! What kind of guardians of order can we corsairs be?! How long has it been since we've had a real mission?!",
	"Don't relax, corsair! Enemy armadas are prowling around our islands, so a bloodbath could happen at any moment.",
	"Captain, they say the king's sending his squadron here?",
	"Of course, corsair. While we live, there will never be peace. Even in hell we'll have to fight devils!",
	"Yo ho ho! What a great drinking party we had yesterday, Captain! It's too bad you weren't there.",
	"It's okay. I'll get my fill yet. And I'm not gonna begrudge you boys.",
	"I'll tell you a secret, Captain. Since you've never done anything bad to us, me and the boys took a sweet little thing down...",
	"Oh, corsair, the noose is waiting for you!",
	"Cap! Free me from this cursed shame! I can't play the keeper of law and order here!",
	"You'd be better to remember that being night watchman on a ship isn't easy either. Duty, bro, is always duty, no matter the place.",
	"There's an important matter!",
	"I have a matter for you.",
	"Don't you see I'm at my post! Don't distract me.",
	"Fine, fine...",
	"You want to report something suspicious to me?",
	"No, nothing of that sort. To add to that, I'm the Captain. I see you aren't listening? Goodbye.",
	"Remember this is a military facility! So behave quietly.",
	"Okay, I'll take that into account.",
	"What fine weather, and I'm forced to stand here. At least the cities have girls. Here, there's nothing around but garrison rats...",
	"I sympathize. But I can't help you. It's your job.",
	"If you want to sob, then find another shoulder. I have to maintain order, so I've got no time to wag my tongue with you.",
	"Nah, it's just that you were standing there like a statue - I wanted to see if you were alive.",
	"You think garrison duty is a joke, do you? Hah! I'll have you know this is a dangerous and very important job. There was this one time, see...",
	"I'm sure it's fascinating, but I'm in a rush. Let me take a rain check, okay?",
	"Hey, buddy, watch yourself! This is a fort, after all.",
	"You got it, my good old soldier fellow.",
	"Ho, friend! You got some water on you? I'm dying from thirst.",
	"Sorry, friend, not on me.",
	"Lord of my loins, is this duty boring. Day in, day out, it's nothing but village dorks like you. Meanwhile the city garrison, they're just living it up...",
	"Is this what you call standing guard? Keep this up, and the city will be crawling with enemy spies.",
	"You look like a hearty fella! How'd you like a spot in the fort's garrison? It's two meals a day, your own spot in our spacious barracks... and free booze!",
	"As enticing as that sounds, I'll have to pass, lest I wind up stabbing my drill sergeant. I don't take orders well.",
	"I can't take this heat anymore... I'd give anything to be back in Europe.",
	"Yeah, you don't seem the type for this latitude...",
	"Hmm... I see. Listen, I wanted to ask you...",
	"I don't think I trust you... Why don't we go see the commandant, and get to the bottom of this...",
	"Hrm. There's something off about you... Here, ",
	", hand over your your weapon and come with me. I need to ask you some questions.",
	"Says you!",
	"Sure, I'll be right behind you... Well, not right behind...",
	"Ah, I see... Well, everything seems to be in order. Move along then, ",
	"Whew, all this guard duty must be wearing on me... All right, all is well, ",
	". Please forgive me.",
	"I thought so!",
	"Your license is expired, and therefore invalid. I'm afraid I must confiscate it. Please hand over your weapon, and follow me. I've some things I need to ask you.",
	"Says you!",
	"Yeah, I'll be right behind you... in hell!",
	"Hrm... Everything seems to be in order. I notice that your license expires today. You can pass for now, but you'll need to get that updated, and soon.",
	"Thank you. I'll see what I can do about that.",
	"Hrm... Everything seems to be in order. I notice that your license is set to expire in just ",
	". You'll want to keep that in mind. ",
	"Oh. Thanks, I'll tend to that as soon as I can.",
	"All right, your license is good for another ",
	". You're free to pass.",
	"I see, ",
	". You may enter the city. Your license is valid for ",
	". Sorry about the trouble.",
	"Everything's in order, ",
	", I won't keep you any longer.",
	"Great. Take care, now.",
	"Thank you, officer.",
	"What in God's name are you doing, running around the city with a bared weapon? Put that away, immediately!",
	"I order you to stow your weapon at once!",
	"Buddy, listen, quit scaring the locals. Just sheathe your weapon, already.",
	"Um. Sure, okay.",
	"All right.",
	"Whatever you say.",
	"You wish!",
	"Keep dreaming...",
	"Sure... when pigs fly!",
};
