string DLG_TEXT_BASE [154] = {
	"I'm the head of the jail. What do you need here?",
	"What do you need? Why have you come to the jail?",
	"Oh, nothing much. Just sightseeing 'round the city, you know. Wandered in here by mistake.",
	"I have business to discuss.",
	"I want to enter the jail.",
	"Listen, will you tell me the crime of an inmate, name of ",
	"Why do you need to know? Believe me, there's nothing worthy of attention. Just thieves and bandits in here.",
	"We've already discussed that wish.",
	"Again about that? We've already talked about that twice.",
	"Hmm. Again...",
	"All the same, I'd like to conduct a tour of your cells. I'm very interested!",
	"Yes, that's so. But I still want to talk about this.",
	"Well. Then, maybe a third time...",
	"The hope of seeing your inmates doesn't leave me...",
	"Well, then. I don't see any reason to deny you. ",
	" - until you leave the jail, you can walk the corridors and talk with the inmates without being disturbed.",
	"I agree! Here are your coins.",
	"That won't work. Too much for pointless corridor-wandering.",
	"No, that's absolutely forbidden by the rulebook. What do you think this is, a circus? Leave, and don't distract me from my duties.",
	"I can't allow outsiders to wander the jail. I ask you, don't get in my way!",
	"Fine. As you say...",
	"Well, then. You can proceed with your, as you say, tour...",
	"Thank you, officer.",
	"For murder.",
	"For banditry and armed robbery.",
	"He was caught stealing.",
	"For minor thievery.",
	"For swindling.",
	"Understood... is there any chance to buy or bail him, or any other way to assist in his release?",
	"Of course not. This joker's on a straight road to hell. He's under strict supervision from the Governor!",
	"Heh. I see...",
	"I don't think so. He's ruined a lot of blood for the residents of our city. So don't even ask.",
	"Heh. Got you.",
	"Rather not. He's a thief and a thief must sit in jail!",
	"Ooh! Well said, Lieutenant...",
	"I don't know, even. This scoundrel stole a frying pan from some lady. I can't release him, but I can't just let him rot in here for such pittance...",
	"Then give him to me, lieutenant. I'll play a reasonable price, of course.",
	"Release? That's quite possible. From my point of view, keeping this little runt here makes no sense.",
	"Then give him to me, Lieutenant. I'll play a reasonable price, of course.",
	"Hmm. Well, okay. ",
	" - on the barrel, and you can take him right now if you want.",
	"Great, I agree.",
	"No, that's a bit steep. I'll decline.",
	"That won't work. I can have an inspection at any moment. I don't want to risk it.",
	"Ooh! Well said, Lieutenant...",
	"We're done here. You can go to his cell and take that ragamuffin.",
	"Thank you.",
	"Well, I won't give you another chance...",
	"I don't need. I made my decision.",
	"You can go on. The chief okayed it...",
	"I've received an order from the head of the jail. You can pass freely.",
	"Well, that's weird.",
	"Going further without permission of the head of the jail is absolutely forbidden!",
	"I'm under command from the head of the jail. If you try to go further without his permission, you're finished!",
	"Understood ",
	"I see",
	", soldier.",
	"I'm at my post. Don't disturb me.",
	"Go on, I can't talk with you.",
	"Fine, soldier.",
	"Ho, ho! What fun!",
	"Cut them, pal. Cut them!",
	"Oh, damn! I didn't think I'd see the body of guard!",
	"Heh!",
	"Argh...",
	"Wait, buddy! Release me!",
	"Listen, pal, be so kind as to open the cell.",
	"Why should I?",
	"They took me in for robbery. They're getting the case ready now...",
	"Mmm, you're a sleek one. If you could be in the cell for a week... Hee hee hee hee...",
	"I'm innocent!",
	"Shut up!",
	"You're no concern of mine...",
	"Wait, buddy! Don't pass by my cell so quickly!",
	"Don't rush, pal! Let's talk.",
	"Why should I?",
	"Listen to me. Ignore what I look like now. I need to get out of here...",
	"Pardon?",
	"You heard me. Get me get out of here! I'll make it worth your while!",
	"Okay, let's just say you've sparked my interest. So who are you, and what can you offer me?",
	"Huh? Oh the name's ",
	". I've got a little something stashed away, in a safe place. Get me out of here, and take me to ",
	". That's where I've got it hid, in one of the caverns there. And boy, is it a beaut! You take me there, we can split it - fifty-fifty!",
	"And what have you got in this trove of yours? How do I know it even exists?",
	"I swear to you, I'm telling the truth! It's everything I've been saving up. Money and jewels and everything, all safe, all waiting for me... ",
	"Sorry, pal. I'm not about to stick my neck out for some jailbird and his dubious fortune...",
	"Hmm, I guess it's worth a risk... All right, here's how it goes. I get rid of the guard, and I take you to my ship. If we pull it off, you don't leave my side until we hit the cavern on ",
	". Deal?",
	"Well, all right. I'll see what I can do. I'll speak with the warden; maybe I get get you off on bail.",
	"Well, okay. I guess I believe you. Here, stand back while I get you out of there. But listen, you don't leave my side until we reach ",
	". You got that?",
	"Curse you, you scoundrel!",
	"Judas priest! May you be torn to gibbons...",
	"Yes, all my love. Goodbye.",
	"May a dog bite your uncle!",
	"Beggars can't be choosers. Deal.",
	"All right. Hang on, while I break the lock. But when you're outta there, we'll have to fight our way out. You ready?",
	"Sure, I'm ready!",
	"Then let's get to it!",
	"Beggars can't be choosers. Deal!",
	"All right. Follow me, fast as you can. We still need to reach my ship. Don't fall behind!",
	"Well, you can try. I'll be pullin' for you! Just don't go and dally. A few days from now, I won't be here no more...",
	"Yeah, hang together. I'll take care of everything.",
	"Well, what have you got for me, friend?",
	"It's all taken care of. I can take you with me.",
	"Man, am I ever happy to hear that! Now let's blow this joint! ",
	"Let me lay it all out. Until we reach the cavern at ",
	", you're not leaving my side. Not even for a minute. You got that?",
	"Yeah, of course! Anyway, it's not like I got too many options.",
	"Then you're free.",
	"murder",
	"armed burglary",
	"theft",
	"Well? Whatcha got for me, friend?",
	"Well, I tried my best. But you're being accused of ",
	". So no bail for you.",
	"Whah... why... Why, that's slander! Agh, dammit. What am I supposed to do now? Just sit and rot?!",
	"Truly sorry, my chap, but there's nothing I can do.",
	"That tears it. The only recourse now is force. Look, I'm gonna have to break your lock. Then you and me, we fight our way out. You up for it?",
	"Goddamn you, you scoundrel!",
	"Judas priest! May squirrels eat your spleen...",
	"Yes, all my love. Goodbye, my old friend...",
	"Hey, friend. What's the news? ",
	"Look, I can't meet the bail. I don't have that kind of money. Looks like I can't help you after all. ",
	"I got it! The loot was all right where I left it. So now, my friend, our lives take their turn for the better...",
	"Ha! Yes, I knew I could trust you. All right, so how do we break this down again?",
	"Listen, I looked everywhere, but my stash... uh, doesn't seem to be where I left it. I don't understand. I guess someone dug it up before we got here. Of all the...",
	"What? You got any idea how that could happen?",
	"It's not that hard. These things happen, you know. Hell, it's already happened to me twice. I'm starting to get used to it.   \nWell... Anyway, you can stay here and keep searchin' if you want, but I gotta go!   \nYou take care, friend! And thanks a bunch for saving me and all. I'll always remember you!",
	"Arf... I don't believe my ears...",
	"Right, friend! Of course, of course... So the total here comes to... let's see... ",
	". And it's fifty-fifty, like we said. I reckon you'd prefer cash, then, ",
	"Naturally!",
	"There you go! Well, all right. I won't hold you any longer. Goodbye, my friend. And thank you!",
	"Yeah, see you... Look, you sure you have to go?",
	"Yeah, positive. Don't worry, this place is a fine piece better than the ",
	" prison. I'll be fine.   \nAnyway. Take care, brother!",
	"Yeah. You do that, too.",
	"They call me ",
	". And I got somewhat of a request for you... Oh, wait. Never mind...",
	"What's up?",
	"I need to get a message to someone on the outside. Can you do that?",
	"Maybe. Why?",
	"Oh, my mates will take good care of you, don't you worry... So, you up for it?",
	"Nah.",
	"I guess... So long as it's not too far out of my way.",
	"Great. So listen 'ere. I got two fellas in the city, waitin' to hear from me. They don't wanna be spotted, so they holed up in a house somewhere. I don't know where exactly; that's up to you to find out.",
	"And how do you suggest I do that?",
	"Just go 'round the city 'til you find the right one. When you get there, the bastards will come right to you. Just don't be takin' your sweet-ass time, 'cause I've only got two more days in 'ere...",
	"I see. Well, what do you want I should tell them? ",
	"Hrm... Actually. Something don't smell right with you. Nah, changed me mind. Keep walkin', punk!",
	"Ha. You're one to talk. All right, whatever...",
	"Here. And thanks, pal!",
	"Sure thing.",
};
