string DLG_TEXT_BASE [185] = {
	"I heard you killed the homeless in other cities. Why would you do that?",
	"I think I know who you are. Why are you killing us?",
	"What do you need from us? What have we ever done to you? Why kill the harmless homeless?",
	"It's all about money...",
	"I was promised a big reward for the job!",
	"That's life...  Nothing personal, my friend. Just business. ",
	"Mm, the townsfolk have gone haywire. It's not my business anyway.",
	"I understand...",
	"You want to finish this matter? Well, as you like. I don't care.",
	"Very good.",
	"Hello. My name is ",
	". I don't think you'd want to get to know me, but perhaps you'll remember my name...",
	"Greetings, ",
	". My name is ",
	"My name is ",
	". Good to meet you.",
	"Greetings!",
	"Hello.",
	"I heard you killed the homeless in other cities. Why would you do that?",
	"I think I know who you are. Why are you killing us?",
	"What do you need from us? What have we ever done to you? Why kill the harmless homeless?",
	"It's all about money...",
	"I was promised a big reward for the job!",
	"That's life...  Nothing personal, my friend. Just business. ",
	"Hmph. You see to what I've been reduced to.",
	"It's not easy living on handouts...",
	"I'd like to get out of being poor!",
	"You again?",
	"I heard you wanted to talk with me.",
	"Listen, I'm very interested. The poor in the city - I hear they're a bunch of throat-slitters?",
	"Listen, I have a very strange matter.",
	"You know, I have a question for you. It might sound a little weird at first...",
	"I want to ask you one question, buddy.",
	"I see. Well, no harm done.",
	"I got that. You want a good time with much ado, come 'ere...",
	"Then you've got to do more than wear out your pants here, and do something about it.",
	"Uh-huh. I've become a bore already?",
	"What do you need?",
	"What do you want?",
	"Will you tell me something interesting?",
	"What's new in the city?",
	"It'd be great to hear the latest gossip...",
	"Listen, I think I've found something interesting in Stuyvesant's residence!",
	"You know, I've managed to untangle this web!",
	"Well, no. Why do you think that? As you can see, I'm not very busy...",
	"Not bored, but definitely worn out. I may be poor, but I'm still a man.",
	"Heh. I see...",
	"Hm, ",
	". Oh there have been some bad rumors about you. But I believe in people like you. Have pity. I ask you to give me money for drink and food.",
	"I ask you, ",
	"! Don't ignore an unfortunate man, please give for food...",
	"I'm not giving you anything.",
	"You'll do without.",
	"Fine. How much money do you need?",
	"From you? Nothing.",
	"I don't need anything, ",
	", thank you.",
	"Hm. Well, okay.",
	"You know, pal, you've got it pretty good.",
	"I won't turn down a wooden nickel, ",
	". How much will your purse and mercy grant me?",
	"It's sinful to laugh at sick people...",
	"Ha ha ha! And what did you think, blessed man? That I was going to give you money?!",
	"Thank you for ",
	". I will buy bread with this money...",
	"Go on, wanderer. Get healthy.",
	"Thank you, ",
	". This is enough money for a week!",
	"Happy to help.",
	"I thank you, ",
	". I will tell all of your kindness!",
	"Oh, that's not necessary...",
	"Thank you, lord ",
	". God protect you...",
	"Yes, the Lord's honor won't hurt me none!",
	"Thank you, lord ",
	". I wish you luck!",
	"Thanks, pal.",
	"Listen, ",
	", are you drunk or are you nuts? You're giving me ",
	"! Somethin' stinks here. I ain't takin' all that. You'd better move off!",
	"Well, you know...",
	"Hee hee... What?!",
	"Well, how can I say it... You're a thorn, to some people here.",
	"I really don't know what to say... I guess you realize, we bums are looked down on.",
	"Enough to want your death?",
	"Death?! Nah, hardly. Listen, what's with the weird talk? It's scaring me.",
	"Heh. It's good that it scares you. From what I gather, you generally don't know who your benefactors may be.",
	"Of course I don't know! You met them.",
	"I met them through... well, a representative, you might say. I'm interested to find out who's behind this. Well, okay, bud. Hang in there. ",
	"Well, I try. Though I don't have many opportunities.",
	"I understand. But be careful. ",
	"Well, come on, tell me the point.",
	"Hmm. I'd be very curious to know who you've managed to piss off so much that he can't stand to look at you?",
	"Can't stand to look at... who? At me?",
	"At all the homeless in the Caribbean.",
	"I don't know what to say... Someone is angry at us? How badly?",
	"Well. Badly enough to want you all dead.",
	"Whoa, are you serious? Well, surely you realize that by and large we're completely harmless... if you can abide the smell and the fleas. If that's enough reason for someone to go around killing us, then life makes even less sense than I thought...",
	"I know, I don't get such a blanket hatred myself.",
	"Sorry, but I know no more than you. I'm completely baffled...",
	"I see. Well, forgive me for distracting you from your work.",
	"It's all right. I wouldn't say I'm all that busy anyway...",
	"Well, still.",
	"Go ahead; I'm all ears.",
	"I've recently run into a really odd phenomenon... It seems there are some parties in the Caribbean who are extraordinarily displeased with your kind.",
	"Oh, it's you! I know who you are!",
	"Hmm... All right, who am I?",
	"You're that Captain who's been going around, asking who it is that supposedly hates us and wants us to die. Rumors spread quickly, even amongst the bums of the world.",
	"Yeah, I guess that's me. But there's nothing supposed about it. This is serious business, as someone is offering a huge hunk of cash to whoever takes the job and wipes you all out.",
	"Well, whatever. I know a guy, wants to talk to you about it.",
	"Oh? Who would that be?",
	"His name is ",
	"; you can find him bumming around ",
	"I see. Well, I guess I'll pay him a visit when I get a chance.",
	"I'm listening.",
	"Who do you think may be interested in seeing the homeless gone?",
	"Oh, I know you. I can't rightly say; you'll need to go to ",
	". You'll find another bum there, name of ",
	". He wanted to talk to you about this very matter.",
	"I see. I guess that's were I'm off to, then.",
	"If you're Captain ",
	", then that's exactly how it is.",
	"Yes, that is my name.",
	"Well, I suppose that's good. From what I've heard, you're trying to find out who it was that we've managed to upset so much that they want to kill us. Is that right?",
	"Pretty much. Except they don't want to do it personally; this is a hired hit, we're talking about. ",
	"Details, details... Who was it that told you this? ",
	"Oliver Trust.",
	"Hm. Don't know the name... Anyway, I have some thoughts on the matter.",
	"Well, Lay 'em on me.",
	"There was a story in Willemstad, Curacao, which I think might sound familiar to you. You see, there was this man, a fellow in our common misfortune, who chose to settle in with the Dutch in Curacao. His name was Teaser Dan.",
	"So anyway, was there for about a month before he was spotted by Governor-General Peter Stuvesant. After that, Teaser got no end of hassle - from the soldiers, the commandant... In the end he got chased out of Willemstad, and that was the last anyone saw of him.",
	"Hmm... All right, so what does that have to do with my issue?",
	"Hang on, I'm still talking. Our folk started looking into Teaser's situation - what happened to him and whatnot - and we learned a little something about Stuvesant. Not many know this, but Stuvesant is the largest supplier of slaves from Africa to the New World!",
	"He works closely with the Dutch West Indian company, and the things they do would make your head spin.",
	"All right, so?",
	"So think about it! Most of our kind are former slaves. What, do you think we're all deadbeats and deserters? Far from it; it's just that an unfortunate train of events forced us through this hell, and to lose our health along the way. Whites are often given their freedom back, seeing as colonists",
	"are in demand, but not every slave that spends several months in the hold of a galleon on the way here will stay healthy enough to plow earth and uproot tree stumps - not by a long shot. And from the looks of things, Stuvesant isn't keen on former slaves that haven't found a useful place in society.",
	"I don't know. That seems a little far-fetched...",
	"Perhaps, but that's the best I can do. I can't think of anyone else that rich and powerful who might hate the homeless to this extent. So if you want to get to the bottom of this, I suggest that you take a look at Willemstad. ",
	"And what do you suggest I look for there?",
	"Documents, my friend. Business correspondence; stuff like that. I admit it all is a bit of a stretch, but it seems to me that there's got to be something more solid lurking behind this Trust fellow... ",
	"You know, that's what I've been thinking too. Considering the magnitude of the plan and the reward he's waving around, we're dealing with something serious. ",
	"Well, I told you what I know. Thanks for listening. If you find anything worthwhile, pray tell me - maybe together we'll piece together some story... And thank you for not doing us even more harm.",
	"Don't mention it. Thank you for the information.",
	"Well, out with it. Let's see what you got...",
	"This is a letter I found in Stuvesant's residence - it's part of his correspondence with the Dutch West Indian company. It clearly shows that this trading company is the one behind the plan to exterminate the homeless.",
	"Uh-huh. As I thought...",
	"It also mentions some island, and luxury goods. And for some reason all of that revolves around vagabonds. Any idea what all this means? ",
	"Hmm... Wish I knew. I guess the island is the mythical Isle of Justice. That's a popular tale on the streets...",
	"Come again?",
	"Well, you realize that vagabonds aren't exactly privileged - crushed hopes, broken lives, and the like. They have no health, no home, no money. Still, in spite of all that, they want something to believe in. Most of our kind believe in the existence of this so-called Isle of Justice, and that faith has saved the life of many a soul.",
	"Tell me more about this isle. What do people say about it?",
	"They say that somewhere not far from here there's an isle, but not of natural origin. Thing is, the principles of law and justice reign supreme on this isle, and the better a man you are, the better that life and fortune smile on you. Personally, I don't believe any of it; nothing I've seen tells me there's justice in this world...",
	"Hm. But this letter says that this isle does exist! Read for yourself: 'It turns out that the rumors about the island are factual...'",
	"Well, I wouldn't know about that...",
	"How did these rumors start in the first place?",
	"It all started with Teaser Dan. He was an odd fella - survivor of more than one shipwreck. Everyone was telling him to stay away from Curacao, but he went and decided to live there anyway... At any rate, he claimed to have lived on that isle for several months. That's how these rumors got started...",
	"Hrm, seems like the Dutch West Indian company thinks they're more than just rumors... So where is Teaser Dan now?",
	"No one knows. We looked for him everywhere, but the man vanished without a trace.",
	"I remember you saying that he got into some kind of trouble in Willemstad. Like he was being run out of town or something...",
	"Yes, yes, exactly. That was after he was spotted by Stuvesant.",
	"Hmm, it looks like I'll have to go back to Curacao...",
	"Well, all I can say is good luck! And thank you for everything, friend.",
	"Take care, buddy.",
	"Great! So, what was that all about?",
	"We already spoke about that.",
	"Hrm. You know, we've already discussed that...",
	"That's enough. Long farewells are for women.",
	"You know, your initial conjecture turned out to be right. The whole thing really was about Teaser Dan and his isle.",
	"Yes, that's correct.",
	"Exactly!",
	"Hmm. You're right...",
	"Please explain!",
	"Well, there's not much I can say at the moment. But I will tell you that the isle that Teaser spoke so much about is no fairy tale. It is real, and I intend to go there!",
	"I can't believe it!",
	"But there's also bad news... Teaser Dan is dead.",
	"Aw, hell. That's a shame...",
	"Even though I've never met Teaser, I'm starting to feel like I knew him well. And you're right, that is a shame...",
	"So you will try and find this Isle? Then I should give you Teaser's key.",
	"His key?",
	"Yeah, I don't know, exactly. Before he left for Curacao, Teaser asked me to take it and keep it safe. He called it 'Diffindur's key,' but I've no idea what that means.",
	"A mysterious key! This is getting more and more interesting...",
	"Teaser told me to give this key to whoever wanted to find the Isle. He said it should solve the problem of the Isle's new resident. Again, no idea; but I'll gladly do as he asked.",
	"Thank you, friend. Thank you and farewell.",
};
