string DLG_TEXT_BASE [354] = {
	"What girls are those, sugarcakes?! Lordy, half the garrison's out for the man's hide, and here he is, seekin' clemency in a brothel!",
	"Well, you ain't hiding here. My momma didn't raise me no fool. The stiffs are poundin' the streets for you, and I'm having none of that in here!",
	"Look, you got no business here. I will kindly ask you to leave my proud establishment.",
	"You lay a finger on one of my girls, I'll skin you alive.",
	"Get outta here, you rat! We don't take kindly to murderers, these parts. What we do is call the... Guards!",
	"Honey, in my line ain't nothing scares me - but I can sure clock a creep when I see one. Ain't no runnin', hot stuff. It's the gibbet for you, sure as I breathe.",
	"Eh, I'm used to alarms by now... ",
	"I'd like to see 'em catch me!",
	"Lady, I'm not here for a monologue. ",
	"I said can it, bitch!",
	"Hey, Doctor Blood! ",
	"Goodness, Doctor Peter Blood. Happy to see you!",
	"It's so good that you came by, ",
	". Pray, how is Colonel Bishop?",
	"Ah! Alas, I am on my way out, ",
	". Next time, perhaps.",
	"You took the money, but you didn't donate a red cent! Anyone asks me the veritable definition of scum, I've now got me a well-befitting point of reference. There's no place for you here. Go on, git out!",
	"Well, darn it all then. Whoopty-doo.",
	"Listen, I know I'm not your favorite person right now. And fair dos, that's my own fault. But I've got something to ask you, and I think it would do you well to answer. ",
	"Git on back to the church and donate that money! I'm holding to to your word, and you only got 'til today!",
	"Yeah, I remember. I'm on it. ",
	"Well? Done any good deeds today?",
	"Yeah, I've done all you asked. The padre said to tell you that the church has graciously accepted your support.",
	"Well? What did they say?",
	"Listen, ",
	", the church didn't take. Here's your money back again. ",
	"Listen, I want to ask you favor... Just this one.",
	"I'm listening.",
	"Ahh, this place is dullsville. Don't suppose a big, strong seaman like yourself would know how to spend a girl's time? ",
	"You bet I do. A sweet dame like you, there's no end to what I could show you. ",
	"Ah, ",
	". I'm running late, sad to say. Maybe next time...",
	"Look, you blew it. Remember last time? I waited for ages in the room up there, and you never showed. Not a foot, not a knuckle. I've got better things to do.",
	"All's the pity...",
	". Welcome to the house of equanimity. My name is ",
	". My purview is all that you may see before you. How can I be of service, ",
	". Greetings, stranger, to my humble establishment. Please allow me to introduce myself. I am ",
	", owner and proprietress to this well-worn refuge of the love-scorned gentleman. How may I serve you today?",
	". How may I help you, ",
	". What can I do for you, ",
	", I'm looking to to spend some time with one of your girls.",
	"I haven't spoiled my boys in a while. Don't suppose I can order in bulk?",
	"I've got a question for you.",
	"Listen, ",
	", I'm on the lookout for a ring, maybe left here by the Governor. He was here not long ago, and now he can't find it.",
	"Just browsing, as they say. I'll get back to you.",
	"Why, we're always rarin' to take on new clientele. Tell me, hon, you already got yourself a favorite? Or is it all the same to you? ",
	"I'm not particular. I just need a girl, pronto. By appearances, one's as good as the next here... ",
	"There's one that's caught my eye, actually...",
	"Well, it ain't gonna be today. We're full-on booked to the brim. Now, you come back tomorrow, and I'll make you up the difference!",
	"And here I was, just getting interested. Ah, well.",
	"Honey, you already bought yourself a girl. So you take good care of her, and keep yourself out of my hair. I've got a business to run!",
	"All right, I'm going.",
	"'Fraid I ain't got no girls free now. Swing back a few days out, and we can set you up proper.",
	"Fine. Whatever.",
	"Well that's just great, you stallion you! I think you'd do well by a dewdrop, name of ",
	". She's got nothing going on. The pleasure is yours for ",
	". Sound like a deal? ",
	"Nah, that's actually a bit out of my range... ",
	"Sounds it and looks it. I'm not one to argue. ",
	"Urf. I don't, uh, carry that much on me...",
	"That's just marvelous, hon. ",
	" should be curled up in a room, first floor up. Go on an get 'er, Randy!",
	"Well, uh. Guess I'm off, then...",
	"Mm. Normally that'd be fine, sugar. Thing is, ",
	" ain't the cheap sort. These days, she don't go for no less'n ",
	". And just a look at you, I can tell you ain't that kind of fancy. Come back when you're on the council, honey...",
	"Ah, it's always the same...",
	"It always sends me aflutter when my girls develop a loyal clientele. You know her name, Casanova?",
	"Huh. That ain't one o' my chickens. You sure you got the name right? ",
	"Um. We just talked a minute ago.",
	"I guess I'd better go make sure. Hang on, I'll be back. ",
	", is that it?",
	"Yeah, that sounds right.",
	"No, that's not it. I think it started with a, uh...",
	"Well, tell me again and maybe I can make some sense out of you. ",
	"All right, I'd better go talk to her again. Save me a place. ",
	"So you decided to let out some of your boys'... steam, eh? The whole kaboodle, you say? Well, I've got a couple of girls specially qualified for that... Though it'll cost you ",
	"All right. That's not too bad, considering.",
	"Ugh. I guess they'll pull through somehow...",
	"Not my place to say, of course, but I'd think it more important to actually pay your team before you go worryin' about morale.",
	"Yeah, you're not wrong...",
	"Say, darlin', where do you think you're headed?! Sakes, to think he felt like a proper Captain. Listen, hon, you're not leaving that easy. They'll bite your toes off. ",
	"Get off me...",
	"Understand, señor, I run me an establishment... I suppose that seems unusual to your sort. ",
	"No, I get it.",
	"Well... That don't mean I ain't concerned about my everlastin' soul. To put a bow on it, I aim to do me some church donatin'. Though I don't right relish the noises outta them parishioners' throats whenever I stride through that door...",
	"I see, all right. Don't worry about it. It's as good as donated. ",
	"Darn tootin' you are. So here's ",
	". Now you go do that today, hear? I don't wanna hear you been slackin' on me, and you don't wanna see me irked.",
	"Yeah, don't fuss yourself. I'll head right on over now. ",
	"Actually, I'm kind of busy today. Sorry, I don't think I do it right off. ",
	"Great! Land by later and lay me out how it all went down!",
	"Um. Sure, okay.",
	"Ah, that's a shame. Downright pity, it is...",
	"Well, world's not ending tomorrow. Another time.",
	"Thank the Lord this wicked soul is not yet without redemption! And thank you too, tripod.",
	"Don't bother to get creative. For you, ",
	", I'd bend over to Nick himself... ",
	"They didn't take it?! What you say to the man, anyway?! Y' didn't tell him who sent you? Damnation, and here's me with my hopes up...",
	"Yeah, sorry about all that... ",
	"Don't know a thing about no ring.",
	"What about your girls?",
	"The girls neither. Anything gets left behind, they know to bring it here, forthwith. No one brung it, no one found it. ",
	"I see what you're saying... but maybe this was an exception? ",
	"That I doubt. The girls know what they can keep. Presents are one thing, but that's all they get. ",
	"Fair enough. Much appreciated, ",
	"Hey, handsome. You fittin' to distract a lady from the doldrums of a ladylike repose? ",
	"Am I ever! Why, all the pirates tremble before the girth of my, uh, authority. When I let it show.",
	"Well, I've got a good eye and strong hands...",
	"Madam, the things I've seen...",
	"Yeah? Well, I've never much been one for authority figures. See ya round, big shot.",
	"Wait, uh... can you explain that better?",
	"Listen, can you talk about something other than yourself? You're a sailor, ain't you? Tell me a dang story!",
	"Oh! A story. I can do that! Well, how about this...",
	"Here, don't you got no notion what a woman's after? Land sakes, talk to me! Preferably about something other than yourself for once! ",
	"Hmm. Well, there's no shortage of topics. Let's see...",
	"Oh, go back and weep in some merchant girl's bodice. And you call yourself a pirate?! Lord, where have all the real men gone?",
	"What? Hey, steady on.",
	"I'm listening.",
	"I've got this one story about a shark's would-be dinner. How's that sound to you?",
	"A while back, see, there was this merchant. Independent type, his own ship. So we take him on, and hey, for all that power he just lets us stroll right in. And by God, you'd think the man had never heard of a bank. It was the mother lode, I swear. The gold, the silver! And good lord, the women. Instead of guards, it's like he had his own harem. All so round and luscious. I tell you, we sure got our fill of...",
	"Ooh, you had a run-in with a shark?! Heavens, how did you ever survive?!",
	"Well, let me start from the beginning. We got ourselves into a real pickle. Dead calm, and heat enough to curdle a man's brains. Since we weren't moving, we figured to go for a swim. Cool down a bit. Days like that, I tell you, there's nothing like a douse of cool water. I was in such heaven, what with my thrashing and diving, I didn't clock when the lookout let out a cry: ",
	", get out of there! Shark! Shark! But then I saw it. I'd just dived down a couple dozen feet, and when I looked up, there was its silhouette above me. It might as well have been a whale, for the size of it! And the moment I saw it, it must have seen me too. 'Cause just then it turned, and came straight for me...",
	"Oh, God. Enough! Get out of my face, you jolly roger. I'm learnin' to get particular in my ways, and your kind don't fit in no more!",
	"Huh? What did I say?",
	"Gracious! So what did you do?! ",
	"Well, I knew I was on my own out there, so I did what any sane man would do. I turned tail and swam with all my might. Back on the ship, my boys are firing away with their muskets, trying to scare off the monster, but there's no budging a force of nature like that. So I'm swimming and I'm kicking, and finally I've only got seven more yards to go, when up behind me surfaces the biggest fin you'd ever see...",
	"Land sakes! So you...",
	"Me, nothing. From there on, the real hero is my cabin boy. Bravest lad on the sea. He saw me struggling and he knew I wouldn't make it, so he up and tossed me a saber.",
	"What?! You don't mean to say you cut down that beast single-handed?!",
	"Well, I... uh, of course! Two swings of my trusty blade, and the horrible monster was reduced to chum before me!",
	"God, no! If you knew the size of it, you'd know that's just crazy talk! Here again, my fate was out of my hands... ",
	"Hah! What a rotten liar! Slaying a monster five times your size, and in the water no less? Pull the other one, while you're down there. You're just a braggart, same all the others! Color me bored. ",
	"Ahem. Well... damn? Ah, I gave it a shot, anyway...",
	"What, then?! However did you escape, sir?!",
	"Well, I reached out and caught the saber, just barely. That was luck in itself. The moment it entered my hand, I spun around and there before me was a pink and black pit, ridged with rows and rows of jagged teeth. It's like it blotted out the sun. Without even thinking, I jammed my blade in between those jaws, thinking, hoping it was strong enough to prop it open in the event I got swallowed whole. And boy, did that have an effect. It was not pleased. It shook and it shook its head until finally it dove away, giving me a good smack with its tail as a going-away present. It hit me so hard, I near-on flew out of the water! By the time the monster righted itself and began to look for round two, I was well on the boat and the rest of the boys were scrambling like hell to get out of the water. Lest I ever forget my fortune, I've been left a few scars to remind me.",
	"Ooh, scars! Do show me!",
	"You know I will! And that's not all I've got to show you! ",
	"What, here? Huh. You know, miss, I can be crude as the next man, but even I hesitate to expose myself in front of a lady, all the more where anyone might just walk in on us. That's not fair to you, if nothing else. ",
	"Ew, didn't your momma ever tell you how to behave in front of a lady? I am sufficiently repulsed, sir, that I reckon I got no further inclination to speak with the likes of you. ",
	"Hang on... back up a bit. Does that mean no?",
	"My, you are the right gentleman! For a moment I even forgot my current career and circumstance. Crude and blunt as maybe, you got yourself something... engrossing about you. And I weren't lying, I'm intrigued to my heels to see them scars of yours. I tell you, poppy, let's us two mosey on upstairs and claim us some privacy. Reckon it's about time I air out those etchings...",
	"Well, you win some, you lose some.",
	"Is that all you mean to show me?",
	"Lead and I shall follow!",
	"Why, whatever could you mean?",
	"I could always see a bit more of you. There's something I'd never get bored of. ",
	"You're on thin ice, buster. ",
	"Well, I like it dangerous. Life's nothing if you don't assert yourself. The minute I laid eyes on you, I knew what I wanted. Good God, that figure! I've never seen the like...",
	"Ha! Just teasing. I'll behave myself, though.",
	"Well, randy pants, I'm afraid this figure don't figure into it. You just missed your chance, Danger Man...",
	"Dash it, what did I do now?",
	"Hm, well I'm all ears...",
	"Though I may be a man of the world, until today I had never seen such refinement in dress and manner, as I see before me now. I've been a child, of childish desire...",
	"Well, no need to be so hard on yourself.",
	"I felt myself drawn to you. I knew what I had to do. ",
	"Oh? What's that, then?",
	"Why, my lady, to invite you upstairs with me!",
	"I've been blind for an age. Without your radiance, the world is bereft and dank as the ocean floor. But in your presence somehow the birds sing sweeter, the shore is softer on the sole, and all the world's beauty comes into stark relief. All these years, I never noticed the glow of dew on a garden, in the early morning sun... ",
	"All right, I've wasted enough time with you. Sorry, buster! You had your chance! ",
	"Agh, to come so far... And yet not at all...",
	"Oh heart-a-flutter, you're the romantic type... But you exaggerate, sir!",
	"Not at all! My words come straight from the heart. If anything, I'm not painting the full picture here. Though that's only because I'm struck near-on speechless, first sight I get of your enormous, quivering...",
	"Yes, go on.",
	"... glistening eyes.",
	"Oh, is that all. Well, sir. Pray, continue.",
	"Though to be completely honest, your eyes aren't all I was thinking about...",
	"Hey, what did you think I meant? Seriously, it's just your eyes. Let's not get ahead of ourselves here.",
	"Oh, really. So what else, then? I'm nigh afraid to speculate.",
	"And your decolletage is wonderful, beyond compare... and I tell you, I'm stuck breathless and dumb when faced with the glory of your bosom!",
	"Bastard.",
	"If I tell you, it's likely you'll just show me the door. But looking at that fabulous dress of yours, I can't stop but imagine what might lie under it. Oh dear, there I go forgetting myself again...",
	"You beast, you rogue...",
	"Yeah, I know. Sorry.",
	"And you complete and utter sweetheart...",
	"So you forgive me?",
	"Maybe... But lawd, is it stuffy in here. I declare, it's much more amenable upstairs... Let's us mosey on up, so's we can continue our... conversation.",
	"You don't have to ask me twice!",
	"Oh honey, I thought you liked my whole package, but there you go fixin' on my eyes. What are you a poet? What, ain't I got nothing else worth an ogle?!",
	"Er. Well, yes. I just meant...",
	"I know what you meant! You think I'm a bug-eyed freak, doncha! That's it, ain't it? Well, who's the freak, you near-sighted pervert! Get outta my sight! Go on, git!",
	"But my dear ",
	", I shouldn't dream of such a thing!",
	"I think you'd better get yourself prepared to high tail it out of our fine establishment!",
	"The guards are searchin' every nook an'  cranny for you! You'd best git; they could be in here for hours...",
	"Think you can hide from your sins in here? Nuh-uh. Not the place, bub!",
	"Get out!",
	"Get outta here, ya filthy pervert! Git! ",
	"Honey, in my line ain't nothing scares me - but I can sure clock a creep when I see one. Ain't no runnin', hot stuff. It's the gibbet for you, sure as I breathe.",
	"Eh, I'm used to alarms by now... ",
	"I'd like to see 'em catch me!",
	"Lady, I'm not here for a monologue. ",
	"I said can it, bitch!",
	"Hello, ",
	". You need to see the madame for that. She handles all the orders.",
	"Oh, it's you. Look, I'm sorry, but you really need to go settle things with the madame. Go on, I ain't goin' nowhere.",
	"Listen, ",
	", nothing wrong with man who knows what he wants, but a man who doesn't know how to listen is another thing. I'll say it again, boyo - go talk to the madame.",
	"Ah, ",
	". I see you're the... assertive sort. That's nice. You need to see the madame for any order you got.",
	"Relax, sweetcheeks. I get the message.",
	"Oh, right...",
	"Don't you worry, princess. I may be as stubborn as a bull, but I'm twice as strong! ",
	"Aw, hell. Musta missed it. Forgive me, darlin'.",
	"And where is she, then?",
	"Gracious, sugar pit, I could just drown in your eyes...",
	"I've never seen a woman as beautiful as you!",
	"Sweet piece, you're as lovely as an autumn flower.",
	"Listen, gorgeous, anyone lose an engagement ring 'round here? This guy I know, says he must have dropped it...",
	"Hey, plump lumps, you seen an engagement ring around?",
	"Oh, my little piglet... I don't suppose you've come across an engagement ring?",
	"A wish from a handsome rogue like you is my command. Any wish at all...",
	"Listen. A little while ago, Jackmann and his crew threw a bash here...",
	"Did you get my thousand?",
	"Here it is. Count it if you want. Now tell me everything.",
	"She's in her office. You can get there either through the door that faces the entrance, or from the street on the other side of the house. Her name is ",
	"Thanks, dear. I get you.",
	"Goodness, you can sweet talk a statue of its feet. Listen, I'm free for the moment. Pick me, and you won't be sorry...",
	"You really think so? My, that's real nice to hear... Listen, darlin', I'm free now. You pick me, I promise to drown you in an ocean of love...",
	"Is that so? Hmm, I won't say I'm not flattered. After all, it's not every day I get to hear words as sweet as these... All right, I'm not busy at the moment, so why don't you go ahead and pick me. I promise you won't regret it...",
	"Sugar, you're the one that I want.",
	"Oh, no, no. That was just a compliment for a lovely lady.",
	"You know what, dearest? I don't need no empty talk. Either get down to business or get out!",
	"I don't know what was knocked into that swashbuckling head of yours, but women don't love with their ears. If you want me, pay the madame. Otherwise, find someone else to beat your gums to.",
	"Oh no, not another romantic... You want me, you gotta pay. And no more of that sentimental drivel!",
	"Oh my! Quite an attitude you've got there!",
	" will take care of the paperwork in her office. Go to her, my love, and tell her my name - ",
	". I'll be waiting...",
	"I'll be back before you know it, darling.",
	"You already paid for your girl. Go upstairs, she's waiting for you.",
	"Like I told ya, she's waitin' upstairs for your sorry behind!",
	"All right. Listen real careful now, 'cuz this is the last time we're doin' this: Go! Up! Stairs!",
	"That is, I declare, the end of it. I relinquish, I throw in my very own towel. I have had, my fine sir, enough of you and your business! And I will have no more!",
	"Yes, I know.",
	"I remember.",
	"Relax, I heard you. I'm just making conversation...",
	"Eh, what are you talking about?",
	"I don't get you. First you throw compliments around like confetti, now you're backpedaling. What gives?",
	"Look, I ain't no muffin, so enough with the butterin' up. You want something, you go see the madame.",
	"You bored yet? The madame's still waitin'.",
	"Honey, I know the customer is always right, but you're asking for it...",
	"It is what it is...",
	"All right, I'll go do that.",
	"Okay, okay. I hear you...",
	"Uh-huh. Sorry 'bout that, gorgeous.",
	"I thank you for the compliment. Now, if you want me, go see the madame. Same as always...",
	"I see.",
	"Sweetie, there's nothing else to say. Now don't make me wait too long...",
	"Listen, handsome, I like the way you work your mouth, but isn't it time we move on to other body parts?",
	"Will you just go and take care of business with the madame already?",
	"I don't even know what to tell you...",
	"No way in hell!",
	"Certainly!",
	"Why, of course!",
	"On my way!",
	"I was waiting, but you never picked me! Can't say I'm happy about all this...",
	"Sorry, dear, that's just how the cookie crumbled...",
	"Ooh, it's you again, my brave corsair! If you need me again, go see the madame - you won't regret it... Oh, of course I recognized you, my darling, it's just that we must give all our clients the standard greeting. Don't take it personal...",
	"Wait for me, sweetheart. I'll be right back and we'll be alone again.",
	"I'm very flattered that you remembered me, but I don't think I can spend another night with you right now.",
	"How about you just get down to business? I'm getting tired of your yapping.",
	"So do you come from a family of parrots, or were you just adopted?",
	"Enough already, eh?",
	"Again with your awkward attempts at charm. Look, if you want to sleep with me - go see the madame, dummy!",
	"Yeah yeah, I heard you...",
	"So that's how it is...",
	"I'll tell you when it's enough...",
	"Watch your mouth, boner breath.",
	"Oh no, you again. And again with your eulogies! Nothing changes in this world... I don't care for your bullcrap; if you want to spend the night with me - pay the madame.",
	"Was there ever a doubt?",
	"Can't say I'm happy to hear it. It's too bad...",
	"I'm sorry...",
	"So good to see you here in the private room. So, what shall we do now?",
	"Come in, don't be shy. Make yourself at home, at least for the next two hours.",
	"I don't suppose we'll get bored...",
	"Come on, baby. Let's have us some fun!",
	"There you are, my handsome buccaneer! I made you a promise and I'm ready to deliver...",
	"Ooh, that sounds so enticing...",
	"Ah, so you're here. Well, let's waste us no more time!",
	"I'm more than game, honey bunny...",
	"So, how you like it?",
	"Well, how was it? You still in one piece?",
	"What's the verdict, cap'n?",
	"If this was my ship, you'd get a raise.",
	"I'm A-Okay, baby doll.",
	"Listen, you've been coming to me for a while now, I've really grown attached to you...",
	"Well, what can I say? I feel the same way...",
	"So, did I deliver on my promise?",
	"Well, darling, how was I?",
	"If I were a smoker, this would call for a Cuban.",
	"Oh yes, it was everything I dreamed of.",
	"Man, that was fun. You were spectacular!",
	"All right then, time's up.",
	"Thank ya, hun! Come again!",
	"All right, later...",
	"'Til next time. And thanks...",
	"Come back anytime, hear?",
	"Take care, now! Don't be a stranger!",
	"Thank ya, hun! Come again!",
	"All right...",
	"Listen, I want to tell you something that you might find useful.",
	"All right, darling, speak up.",
	"I had this one client recently. He was drunk out of his mind and kept saying something about a treasure along the mainland coast. Kept promising to shower me with gold...",
	"Sounds like drunken blather.",
	"Maybe so, but I doubt it. He didn't remember anything afterwards, so it seems that his tongue just betrayed him.",
	"Did he mention a specific location?",
	"the gulf of San Juan del Nore",
	"the bay of Amatica",
	"the gulf of death, right near Belize",
	"He was mumblin' himself somethin' silly 'bout ",
	"Well, thanks for the info. I'll be sure to check it out sometime.",
	"Sorry, handsome, hadn't seen it. Wish I could help...",
	"Sorry, ramrod. Don't believe I've seen it.",
	"A ring? Nuh-uh, I reckon not. ",
	"Ah well... Thanks anyway.",
	"You don't mean the Governor's ring, do you?",
	"That's the one!",
	"Sorry, handsome. Ain't seen it! Wish I could help...",
	"Sorry, bucky-buns. Don't believe I've seen the like.",
	"A ring? No, don't reckon so.",
	"Ah well. Thanks anyway.",
	"Sorry, stiffy, but that ring was a gift. So consequently I ain't plannin' on relinquishin'!",
	"A gift, you say? From whom?",
	"Why, from the Governor, o' course!",
	"Thin is, when he gave it to you he was... shall we say, overly medicated? He doesn't remember a thing...",
	"So? A gift's a gift. Ain't my misery if he weren't himself at the time o' givin'. ",
	"Listen, doll, we're talking about the Governor here. We don't want to make him angry, do we? You understand that this is an engagement ring, right? Just give it back, you don't want trouble over such silly business.",
	"Well, it's not like I've got me a sentimental attachment. But I sure ain't givin' away a rock like this for nothin'! Sure, you can have it - for five thousand piasters.",
	"All right, here's your money. Now can I have the ring, please?",
	"I ain't holdin' you back! Go on. ",
	"No skin off my nose, bluebeard. ",
	"I'm amenable.",
	"Well, that's settled. Thanks a hogshead, sweetloins!",
	"And?",
	"I remember one of the pirates trying to sell some book, the Bible or something like that...",
	"I remember that... Listen, handsome, let's go upstairs and I'll answer all of your questions. And it will only cost you a thousand coins...",
	"I just need some info...",
	"Sure, I'll tell you all you want to know. But let's go upstairs first, this isn't the place to have such discussions.",
	"Damn, I don't have the time for this...",
	"Oh my, a man that's scared of a woman's lovin'!",
	"Here's your money. Now tell me everything you know, right here and right now.",
	"I ain't scared of nothing! I just don't have the cash on me... I'll be back with a thousand real soon!",
	"Loran de Graf was saying that he has some real rare book for sale. I think he said it was called the Bible.",
	"Yeah, and?",
	"They looked it over. The cover did have a crucifix, but otherwise it was impossible to tell what the book was. It was written in some strange language that no one knew.",
	"Well, if it's for sale, I'd like to buy it. Where can I find this corsair?",
	"Go straight to Tortuga, and you can't miss 'im. His name is Loran de Graf, but you already know that. He's a famous Dutch filibuster.",
	"Thanks. I'll head right over there.",
	"So wait, you really think this book's worth somethin'?",
	"Hard to say. I'd need to take a look at it. Did Graf say where he got it, or anything else you can remember?",
	"Not really, but then, weren't no one listenin' real close, y'know? 'Round here, the Bible ain't the first thing on people's minds...",
	"I see. Well, thank you. I guess I'll go look for Graf, then.",
};
