string DLG_TEXT_BASE [131] = {
	"The alarm's been raised in the city! Everyone's out looking for you! If I were you, I wouldn't hang around here.",
	"All the city guards are hounding the city for you. I'm not dumb enough to hang around talking with you.",
	"Run, pal, before the soldiers make mincemeat out of you...",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Dirty murderer! Out of my house! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Heh, the alarm's no problem for me...",
	"They've got nothing to catch me for.",
	"Shut your trap, ",
	", or I'll rip out your rotten tongue!",
	"Heh, ",
	", and still the same - after pirates! I'll tell you what, buddy. Sit quiet, and you'll live...",
	"Hey, Doctor Blood! ",
	"Great to see you, Peter Blood.",
	"It's good that you've come around here, ",
	". How's Colonel Bishop doing these days?",
	"Alas, I am leaving, ",
	". 'Til we meet again.",
	"I'm looking for a captain that'll get me and my friend to Tortuga for the modest amount of 3000 piasters. Do you have anyone in mind?",
	"! Greetings, I am ",
	", the owner of this wharf.",
	"Nice to meet you. I'm Captain ",
	"Listen, I've got an important matter. I hope you'll help me....",
	"Let's hear it. What is it?",
	"Oh, it's you again? Oh come, money doesn't smell.",
	", how can I help you, ",
	"That's it. I pay. You do.",
	"I need to make use of wharf's services.",
	"I need ship cannons.",
	"I just want to talk.",
	"I would like to discuss financial matters with you.",
	"I'm here under orders. Man by the name of Governor ",
	" has sent me. I have to pick something up...",
	"I got this one tin I need opened carefully. Can you do it? I'll pay.",
	"I finished your assignment. A drawing from wharf ",
	" is with me.",
	"I have to go.",
	"Good! I'm happy to meet new clients. My wharf is at your service.",
	"Wonderful, ",
	". Let's see what you can offer me.",
	"I need ship cannons.",
	"I just want to talk.",
	"I would like to discuss financial matters with you.",
	"I'm here under orders. Man by the name of Governor ",
	" has sent me. I have to pick something up...",
	"I got this one tin I need opened carefully. Can you do it? I'll pay.",
	"I must go. Thank you.",
	"Are you trying to play a fast one on me? And where is your ship? It's not at the pier!",
	"I swear to the devil, you're not tricking me! Your ship isn't at the pier!",
	"I don't see your ship at port, Captain. ",
	". I hope this isn't the Flying Dutchman?",
	"Captain, it's easier to load the ship from the pier. Moor the ship and come back.",
	"How unpleasant! All right, old sly-boots, we'll meet again!",
	"I didn't want to trick you, ",
	". The ship is on the other side of the island.",
	"No. My ship's called the Black Pearl. Hey, you've gotten a bit white? Ha, ha! It's a joke!",
	"Thanks for the tip, I'll make sure to use it.",
	"Are you trying to play a fast one on me? And where is your ship? It's not at the pier!",
	"I swear to the devil, you're not tricking me! Your ship isn't at the pier!",
	"I don't see your ship at port, Captain. ",
	". I hope this isn't the Flying Dutchman?",
	"Captain, it's easier to load the ship from the pier. Moor the ship and come back.",
	"How unpleasant! All right, old sly-boots, we'll meet again!",
	"I didn't want to trick you, ",
	". The ship is on the other side of the island.",
	"No. My ship's called the Black Pearl. Hey, you've gotten a bit white? Ha, ha! It's a joke!",
	"Thanks for the tip. I'm sure it I'll make good use of it.",
	"I need to get my hands on some plans. It's very important...",
	"Hmm. What sort of plans? And where?",
	"corvette",
	"flute",
	"frigate",
	"I've heard that at the shipyard in ",
	" they're building a brand new ",
	". I need the plans that they're using to build it.",
	"Do you really. So where do I come into this? ",
	"Bring it to me. Only problem is, the plans are so valuable that the owner of the shipyard never takes his eyes off them. Or, to be more precise, never takes them off his desk.",
	"So what do you propose?",
	"I propose that you bring me the plans. How you do it is none of my concern. I'm prepared to pay generously, provided the plans are of sufficient value.",
	"What do you mean?",
	"If the project involves ideas and concepts I've never seen before, then clearly it's going to be more valuable. And your fee will be ample. If not, then not so much... Listen, do you want the job or not?",
	"Nah, it's not for me. I've got better things to do than screw with a 'pig in a poke'.",
	"I guess one job's as good as another. All right, sign me up!",
	"Hum. Well, that's too bad.",
	"Indeed.",
	"Well then, good luck. I'll be waiting for the results. Don't worry about time. You're free to take however long you need.",
	"Understood...",
	"You little punk! What the hell do you think you're doing?! I'll teach you a lesson! Hey boys, get the axes!",
	"Axes?",
	"Are you threatening me?! Hey boys, grab the axes!",
	"Axes?",
	"Great! Well, let's what we really got here with this braggart ",
	"Please do.",
	"Yes, these plans are rather valuable. I'm willing to pay you ",
	"Splendid!",
	"Hmm... I'm sorry to tell you this, but I see nothing useful here. I believe you must have taken the wrong plans.",
	"You told me to bring you what was on that table, and that's what I did. If you want something else, you should have been more specific.",
	"Well, I'm sorry but this... document is worth nothing to me. I can't pay for it.",
	"Uh-huh. Well, I'll refrain from making a scene here. I must say, however, that I am less than thrilled with your behavior. ",
	"Look, it's your money or your blood. What's it going to be?",
	"Don't get me wrong, it's just that these plans aren't worth the paper they're written on. You could as easily found them in a trash pile. ",
	"I see...",
	"Here you go. Thanks for all your hard work.",
	"Anytime...",
	"Well, Doctor, that depends on the identity of your friend and his business in Tortuga.",
	"My friend, well... he's an honest trader... er. Let's say he deals in antiques.",
	"My dear friend is a filibuster. He lost his vessel long ago, in an attack from a Spanish patrol. ",
	"Perhaps you've heard of him - Captain Jacques Swallow?",
	"A trader? A trader-cum-antique dealer desires entry to Tortuga? You're pulling my leg, Doctor!",
	"I wouldn't dream of it, sir! I'm just, er, trying to help. To help him, I mean. My friend... You see.",
	"And where did this happen?",
	"That was... er... Head like cheese, you know. He did tell me once, though.",
	"Then you mean former Captain... yes?",
	"Um... Well, I suppose so, yes. So do you know him?",
	"All right, I'll believe you. For now. There's a man in the port, name of John Mayner. Speak with him. I just sold him a corvette.",
	"Sundry thanks. ",
	"Yes, I have heard of him. Mind, I don't know how Jacques Swallow lived before he sailed on his treasure hunt to Tortuga... He was captain of the Ebony Oyster, at the time...",
	"What? He never mentioned that.",
	"Seems his tongue is not as loose as it once was. Life taught him well. On the third day, the first mate went to him and said, 'We all agreed we should... cooperate.' Meaning, we all wanna know where we're going. So Jack gave him the map, and then come nighttime...",
	"... There was a mutiny?",
	"No! Don't interrupt me! Come nighttime, I say, the map was gone. The sea wolves had heaps of tobacco but no pipes, so what they did is they used the map for rolling paper! They smoked the whole thing up! By the fourth day, the rum was gone, along with the tobacco, and the treasure was, as they say, a pipe dream. Some jackass got it in his head to blame Jacques, and the crew rallied behind the fool. So the pirates plopped Jacques on some desert island, to die... That is, after going insane from the heat. You know, Peter, normally when you beach a pirate, what you do is you give him a gun and a single bullet. Just the one. Not enough to hunt, or to defend yourself... But not altogether useless. Anyway, they didn't even allow Swallow that. But Jacques made it off, and he's been harboring a grudge ever since. Ten years now, he's been dreaming up a revenge epic and grandiose enough for the Oyster's new captain.",
	"That's quite the story, but what about the Captain and the ship? Got any idea what I should do?",
	"How did Jacques escape?",
	"Find John Mayner. He should be around the port. He's setting to sail his spanking-new corvette straight on to Tortuga.",
	"Many thanks. ",
	"Ah, that's a story in its own right! So there he was on the bank. He just sat there for three days and three nights... Idea was so the local fauna would, uh, get used to him. On the morning of the fourth day, he grabbed two sea turtles, tied 'em together, and had himself a good laugh!",
	"That's... fascinating. But how did he escape?",
	"I was just getting to that! So after three days of sitting on the bank, he spent the whole fourth day pointing laughing at the turtles. I guess the sun must have got to him. Just then, a group smugglers arrived. Turned out they had a stash there. The smugglers just about bust a gut over the turtles, so they took Jack back with them. They needed a laugh, they said.",
	"That's incredible! So... speaking of turtles, how do I get him to Tortuga?",
	"You need Captain Mayner. John Mayner. I just sold him a corvette, so he should still be around somewhere. Go take a look around the port.",
	"Yes, all right. Thanks in the plenty. ",
};
