string DLG_TEXT_BASE [65] = {
	"You dare to arrive at the Governor-General's?! A bold move...",
	"Those lazy fools allowed an enemy to break in here?! Reason fails me...",
	"Yes, um, my security isn't worth much if some bum's running around my residence...",
	"What do you want, scoundrel?! My soldiers are already on your tail! You won't escape, you dirty pirate!",
	"Out of my residence, you filthy murderer! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"The grunts aren't worth much...",
	"They've no chance of catching me.",
	"Shut your trap, buddy, or I'll rip out your rotten tongue!",
	"I'll tell you this, pal - be quiet, and you'll live...",
	"I hear you've been rather persistent in requesting an audience. My name is ",
	". I am the Governor-General of this colony of ",
	", a deputy of the crown of ",
	". Now will you be kind enough to state the purpose of your visit, ",
	"My name is ",
	"Oh, it's you again? For what matter did you need the Governor-General from ",
	" this time?",
	"Again you distract me from important government affairs? What do you want from me, ",
	"I want to talk about working for the glory of ",
	"I need to discuss one matter with you.",
	"Excuse me, but I have matters to attend to.",
	"So, what reason compelled you to come here and distract me from important governmental matters?",
	"I want to talk about working for the glory of ",
	"I have to talk to you about one matter.",
	"This is no more than a courtesy call, ",
	"In that case, I'll ask you to leave my office and not distract me from my work.",
	"Yes, yes. Sorry to have disturbed you.",
	"I don't know you at all, ",
	". Leave my office. I deal only with men in the service of ",
	"Sorry for the disturbance. When I have a license from ",
	", I will return.",
	"It's my pleasure to inform you",
	", your request for service promotion has been signed into effect in the chancellery of ",
	". You are awarded the title of ",
	" of the fleet of ",
	"Thank you! I promise to continue my faithful service to ",
	"Have you questions for me, ",
	"I'm listening, ",
	"Please go on; I'm all ears.",
	", I am happy to see such a dashing ",
	" in the service of ",
	"Got any work for a licensed corsair?",
	"Got any work for a licensed corsair?",
	"I'm here on a matter that directly concerns your missions.",
	"It's about your missions...",
	"Got any work for a licensed corsair?",
	"I want to transfer the settlement that I conquered under the flag of ",
	"Pardon me; I'll come back later.",
	"It's nothing so morbid, ",
	". Just a friendly visit.",
	"Hmm... I hear tales that you have been moonlighting with ",
	". Wherever your leaks are, I suggest you plug them before I entrust you with any of my secrets.",
	"That's too bad.",
	"I hear that you have close ties with the Brotherhood of the Coast. I am therefore cautious of a certain... shall we say, conflict of interest with ",
	"Hm. Well, I'm sorry you feel that way. But whatever.",
	"Fortunately for me, though perhaps not for you, at present I am cursed with no tasks sufficiently dangerous and profitable to be worth the interest of a corsair.",
	"Well... Er, all right. I guess I'll come by later.",
	"What city are we talking about?",
	"Never mind; it's nothing, really.",
	"Splendid news, ",
	"! Your efforts have not gone unnoticed. You are due a reward of ",
	" gold, for your services to ",
	". That said, I ask that you excuse me, as I am profoundly busy at the moment.",
	"Well then, ",
	", I daren't keep you. Do take care.",
};
