string DLG_TEXT_BASE [500] = {
	"You dare to arrive at the Governor-General's?! A bold move...",
	"Those lazy fools allowed an enemy to break in here?! Reason fails me...",
	"Yes, um, my security isn't worth much if some bum's running around my residence...",
	"What do you want, scoundrel?! My soldiers are already on your tail! You won't escape, you dirty pirate!",
	"Out of my residence, you filthy murderer! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"The grunts aren't worth much...",
	"They've no chance of catching me.",
	"Shut your trap, ",
	"or I'll rip out your rotten tongue!",
	"I'll tell you this, pal - be quiet, and you'll live...",
	"A broken version of the game.",
	"I'm busy. We have nothing to talk about.",
	"Well, okay.",
	"Oh, look who's come! Why, it's ",
	". Wasn't too long ago we spent a pretty penny on bounty hunters, to bring you here.",
	"I wanted to iron out the disagreements between us.",
	"Eh... I think it's about time to go.",
	"Disagreements? You jest? This is my city! Or nearly mine, anyway. It won't be long now...",
	" Enemy in the residence! Alarm!",
	"Ah, hell.",
	"I hear you've been rather persistent in requesting an audience. My name is ",
	". I am the Governor of this city, ",
	", under the aegis of ",
	". And now would you be so kind as to inform me of the business of your visit, ",
	"My name is ",
	"So that's it, is it?",
	"Correct. I will hold you no longer.",
	"I must disappoint you, but at the moment I have no time to receive you. As you may already now, our colony is under attack from ",
	". And I must organize the defense of the city.",
	"I was just about to offer my help in defending the city.",
	"Then I won't hold you any longer.",
	"They say you helped us beat back the ",
	" squadron, and defend our colony! We are grateful to you, ",
	"Oh, it's you, ",
	". Happy to see you again. Good news for our colony! We've beaten back the ",
	" invaders. Your merit is in this as well. Here is your reward of ",
	" gold. Please be so kind as to take it.",
	"Thank you, ",
	". Pleasure doing business with you! ",
	"Listen, I have a matter of a, hmm, somewhat unusual nature.",
	"I'm listening to you attentively.",
	"Oh, it's you again? What's the matter this time?",
	"Again you're distracting me from running the city? What do you want, ",
	"I want to talk about working for the glory of ",
	"I need to discuss one matter with you.",
	"I need to turn in a captured Captain to the authorities.",
	"I need to clarify a series of financial matters with you.",
	"I found your ring. Here you go.",
	"Your engagement ring is with me. As it turns out, you gave it to one of the brothel girls.",
	"I would like to find the Governor-General from ",
	"Perhaps you would like to take a break from important matters? May I suggest spending time with a game?",
	"I'll ask you to forgive me, but I have business to attend to.",
	"It's come to my knowledge that you're... how should I put this... a regular at the local brothel. Which is why I came to you for help.  ",
	"Well, I'm ashamed to admit it. But yes, I was there recently...",
	"Hmm, why be ashamed? Everything's in order. Attraction and whatnot...",
	"Heh, that's not what I'm ashamed of. The problem is, I drank a bit much there and lost my engagement ring!",
	"Uh-huh, that is a serious problem. I sympathize.",
	"I don't need your sympathy. I need to find the ring. Find it by midnight. If you're successful, I shall be very generous. If you fail, I'm finished.",
	"I see... And where specifically could you have lost it? Can you say something concrete?",
	"Alas, no. I don't remember anything at all...",
	"I see. Well, then. I'll look.",
	"You know, ",
	", I think I'll pass on this one. Please excuse me.",
	"Very good! But remember you have to find it before midnight.",
	"I'll remember. Wait to hear from me again.",
	"The ring is located in the ",
	", in the ",
	"That's how it is? Hm, I didn't expect it... Well, all the best, Captain.",
	"Farewell.",
	"Excellent, it really is it! You've saved my life!",
	"Oh, come now...",
	"Here is your reward for a job well done. Know that I am very grateful!",
	"Hmm. I'll keep that in mind...",
	"Isn't that something! I need to drink less...",
	"That's for sure! Now, then. here's your ring.",
	"Yes, yes. Thank you so much. I owe you! Here is your reward, for a job well done.",
	"Thank you, ",
	"I think we've discussed everything already.",
	"That's correct. I won't keep you any longer.",
	"I must disappoint you, but at the moment I have no time to receive you. As you may already now, our colony is under attack from ",
	". And I must organize the defense of the city.",
	"I was just about to offer my help in defending the city.",
	"Then I won't hold you any longer.",
	"They say you helped us beat back the ",
	" squadron, and defend our colony! We are grateful to you, ",
	"Oh, it's you, ",
	". Happy to see you again. Good news for our colony! We've beaten back the ",
	" invaders. Your merit is in this as well. Here is your reward of ",
	" gold. Please be so kind as to take it.",
	"Thank you, ",
	". Pleasure doing business with you! ",
	"So what reason compelled you to come here and distract me from important government matters?",
	"I wanted to talk about working for the glory of ",
	"I need to discuss one matter with you.",
	"I need to turn a captured Captain in to the authorities.",
	"I would like to find the Governor-General from ",
	"Perhaps you would like a break from important matters?",
	"This is just a courtesy call and nothing more, ",
	"Hmm, what kind of game do you suggest?",
	"Let's throw down a few cards for big stakes.",
	"Let's throw down the bones in poker-joker.",
	"Excuse me, but I have matters to attend to.",
	"I'm not gambling with strangers!",
	"As you wish.",
	"Come on! A bit of recreation never harmed a man's health... his wallet, maybe!",
	"Wonderful.",
	"What are the house rules?",
	"No, I've had enough for today. I've got matters to attend to.",
	"As you wish.",
	"All right, let's start!",
	"No, this isn't for me...",
	"Let's decide.",
	"You're known as a master swindler. I'm not playing the bones with you at all.",
	"Everyone lies! I don't need it.",
	"Are you joking? You have no money!",
	"You're known as a master swindler. I'm not playing the bones with you at all.",
	"Everyone lies! I don't need it.",
	"Are you joking? ",
	"You have no money!",
	"It happens.",
	"That's it! I need to stop playing, lest they think me an embezzler and throw me overboard...",
	"A pity.",
	"Fine, let's play for 1000 coins.",
	"Begin!",
	"You're known as a master swindler. I'm not playing the bones with at all.",
	"Everyone lies! I don't need it.",
	"I heard you were a good player. I'm not playing you for such big stakes.",
	"Let's play for lower wagers?",
	"Sorry, got to go.",
	"You jest, ",
	"? You don't have 15000 gold!",
	"I will!",
	"No, these wagers won't do the city treasury any good.",
	"As you wish.",
	"Fine, let's play for 5000 coins.",
	"Begin!",
	"I'm not gambling with strangers!",
	"As you wish.",
	"Let's! A little recreation never harmed a man's health... just his wallet.",
	"Wonderful.",
	"What are the house rules?",
	"No, that's enough for me today. Duty calls.",
	"As you wish.",
	"All right, then. Let's begin!",
	"No, that's not for me...",
	"Let's decide the wager.",
	"Let's play for 500 coins a die.",
	"How about 2000 gold for a die.",
	"I think it's getting late.",
	"You're known as a master swindler. I'm not playing the bones with you at all.",
	"Everyone lies! I don't need it.",
	"Are you joking? ",
	"You have no money!",
	"It happens.",
	"That's it! I need to stop playing, lest they think me an embezzler and throw me overboard...",
	"A pity.",
	"Fine, let's play for 500 coins.",
	"Begin!",
	"You're known as a master swindler. I'm not playing the bones with you at all.",
	"Everyone lies! I don't need it.",
	"I heard you were a good player. I'm not playing you for such big stakes.",
	"I'm sorry, it's getting late.",
	"Let's lower the stakes.",
	"I'm sorry, it's getting late. ",
	"Are joking? You don't have 1500 gold!",
	"I will!",
	"No, these wagers won't do the city treasury any good.",
	"As you wish.",
	"Fine, let's play 2000 coins a die.",
	"Begin!",
	"In that case, I'll ask you to leave my office and not distract me from working.",
	"Yes, yes. Sorry have disturbed you.",
	"Open your eyes, you idiot! His ",
	"Grace ",
	"Highness ",
	" the Governor-General from ",
	" is in this very room!",
	"Thank you. I apologize for my lack of tact.",
	"His ",
	"Grace ",
	"Highness ",
	" the Governor-General from ",
	" has left for a visit to Europe.",
	"His ",
	"Grace ",
	"Highness ",
	" the Governor-General from ",
	" is on the continent at the moment, in ",
	" is seeing to important affairs of state on the continent, in ",
	" is on a visit to the continent, in ",
	" in the city of ",
	"His ",
	"Grace ",
	"Highness ",
	" the Governor-General from ",
	" is on the island, in ",
	" is seeing to important affairs of state on the island of ",
	" is on a visit to the island of ",
	" in the city of ",
	"Thank you very much!",
	"Why should I tell you an important government secret? How do I know you're not a spy?",
	"No, please. Please excuse me.",
	"This is a bug. Tell Eddie about its existence.",
	"Sure, pal!",
	" The enemy has been destroyed. The city is saved! Your reward.",
	"Happy to serve you.",
	"Yes, ",
	", quickly! Quickly, save our city! The living dead are battling with the port's defenders. I don't know what to do!",
	", you're just in time! I've been informed that's there a battle at the port. The city's being stormed by pirates. Help us destroy them.",
	"Difficult, but can do!",
	"Oh! This job's just what I needed!",
	"As far as I know, you already have a mission from the governor of ",
	". Until you complete your previous mission, I won't give you a new one.",
	"Hm, aren't you the one from ",
	" who took on a few missions for the local governor? Yes, that's it! Until you finish your duties, I'm not giving you anything new.",
	"Understood...",
	"I understand, ",
	"A mission to find the bandit named ",
	" has already been assigned to you. Do it!",
	"You already have a mission to find the bandit named ",
	". I await your results!",
	"While you're cooling off here in my residence, ",
	" is robbing our colonists! Complete your mission immediately!",
	"Fine, ",
	"I taking care of it, ",
	"Time's up. I recall you were to find and eliminate the bandit. And what do you think has been reported to me? I'll tell you. ",
	" is still alive and healthy! Be so kind as to explain, ",
	"All the deadlines given to you for the elimination of the villain ",
	"have run out. However, I hear that there have been no developments. What's the matter?",
	"I was unable to complete your mission in the given time, ",
	"So now, then. What do you say? Were you able to eliminate the assigned bandit? ",
	" ... is he finally dead?",
	"Tell me just one thing. ",
	" ... is he dead or alive?",
	"Unfortunately, he lives, ",
	". I was able to find him just fine. But when it came down to it, it turned out we were a poor match, so I had to turn tail. I'm really sorry, but this bandit's just out of my league.",
	"So now, then. What do you say? Were you able to eliminate the assigned bandit? ",
	" ... is he finally dead?",
	"Tell me just one thing. ",
	" ... is he dead or alive?",
	"He is dead, ",
	"Your next assignment is to find an enemy scout. Proceed!",
	"You already have a mission to find the enemy spy in the city. I await your results!",
	"While you're cooling off in my residence, the enemy lookout has found out another government secret! Investigate immediately!",
	"Fine, ",
	"I'm handling it, ",
	"Time's up. I recall you were to find an enemy spy. As I understand, there are no results.",
	"All your deadlines have expired. However, I'm told that there is no progress. What's the matter?",
	"I was unable to find the scout, ",
	"Did you find the spy?",
	"Tell me, did you find the enemy agent?",
	"Yes, he was hiding in one of the houses in the city. I found him and ran him through. Simple enough for a corsair like me.",
	"Captain, I assume your friend here is the man we've been looking for?",
	"Uh-huh. Well, it looks like I can safely take your friend here into custody. I assume he is the man we've been looking for, yes?",
	"Yes, this is your man. Credit where it's due, he is a clever rogue; it took all my guile to track him down...",
	"The time allotted you to for delivery has run out. Am I to understand that you were unable to carry out this task?",
	"Your time is up, and I have come to learn that the letter has not been delivered. What is the problem?",
	"I was unable to carry out your task, ",
	"You have already been tasked with the delivery of my letter! Now get it done!",
	"You have already been tasked with the personal delivery of my letter! I need this letter as soon as possible, and I expect results!",
	"While you're cooling off in my residence, the information I need is still in the sender's hands! Proceed with your task, immediately! Get me that letter!",
	"Fine, ",
	"I'll get to it right away, ",
	"Did you have the letter?",
	"Speak quickly - do you have the package?!",
	"Yes, I did everything exactly as we agreed. Personal delivery, for you! ",
	"You have already been tasked with destroying the smugglers. Get to it!",
	"You have already been tasked with destroying the smugglers. I expect results!",
	"While you're cooling your heels in my residence, the smugglers have secreted yet another batch of goods into the city! Carry out your obligations, man! At once! ",
	"Fine, ",
	"I've got it in hand, ",
	"Your time is up. Am I to understand that you were unable to destroy the smugglers?",
	"Your time is up, and I have come to learn that the smugglers are still at large. What is the problem?",
	"I admit, I was unable to do it in the time you gave me. It's true, ",
	"Were you able to curb the smuggling activities?",
	"Tell me, did you destroy the smugglers?",
	"Yes, I caught up to them in the bay of ",
	" and killed them all.",
	"You have already been tasked with finding the pirate ship. Get to it!",
	"You have already been tasked with finding and destroying the pirate vessel. I expect results!",
	"While you're cooling your heels in my residence, the pirates have pillaged yet another merchant ship! Carry out your obligations, man! At once! ",
	"Fine, ",
	"It's all under control, ",
	"The time allotted you to find and destroy the pirate has run out. Am I to understand that you were unable to carry out this task?",
	"Your time is up, and I have come to know that the pirate vessel was not destroyed. What is the problem?",
	"I admit, I was unable to find the ship in the allotted time. It's true, ",
	"Just tell me one thing - is that blasted pirate alive or dead?",
	"Tell me, is that damn pirate still breathing?",
	"Both he and his crew are dead, and their ship is on the bottom of the ocean, ",
	"So, what do you have for me? Did you complete your task? Is that cursed pirate finally dead?",
	"Just tell me one thing - is that pirate alive or dead?",
	"Unfortunately, he lives, ",
	". I was able to find the ship. But when it came down to it, I could not match him, and so I had to retreat. I'm really sorry, but this bandit's just out of my league.",
	"I was informed that you caught up to the pirate and engaged him in battle. So, who was the victor?",
	"I was informed that you engaged in battle with some vessel in the surrounding waters. What was that all about?",
	"I was able to track down the pirate ship, and our vessels faced off against one another. Unfortunately, however, ",
	", the pirates were able to slip away from the place of battle. I am very sorry...",
	"You've done a great deal for my city, ",
	". I can put in a word for you with the General-Governor. I can also award you with your own privateer's license. ",
	"That would be wonderful. I always wanted to receive a license. ",
	"I don't need it. I am already employed by another country!",
	"Thanks, but I'm not at all interested.",
	"Alas, I've no more tasks for today. The last one was completed by ",
	". Drop by tomorrow, I might have something.",
	"Ah, damn it! Just my luck...",
	"At the moment I don't have any work for someone like you. Come by tomorrow, if you want...",
	"I don't have any work for you today. Come by later, maybe in a day or two.",
	"Right now I don't have anything that needs doing. Please come back another day.",
	"I understand, ",
	"Ah, I have a perfect job for you! The jungle near ",
	" has become home to a gang of outlaws. I've been told that their leader goes by the name ",
	". Find him and his thugs - and destroy them.",
	"Is there a time limit for this job?",
	"Yes, I have an important job for you. I've just received information that an enemy spy has infiltrated ",
	". Your task is to find him.",
	"Tell me, ",
	", is your source credible?",
	" which is in ",
	"I have a rather dangerous job for you. I need you to make your way into ",
	", where you will meet with a certain individual, who will give you something to bring back to me.",
	"Hrm, I doubt that the good people of ",
	" will be happy to see me...",
	"I have a job for you - it concerns smugglers. Lately we've noticed a strange phenomenon in the city: the stores are brimming with merchandise, but customs dues somehow elude the city treasury. As you might have guessed, the smugglers are the answer to our little puzzle... And they must be dealt with.",
	"What do you need me to do?",
	"Yes, I have a job for you. I've been informed that a pirate ship has been spotted in the waters near ",
	". Several merchant ships were already pillaged. But what's interesting is that the victims just can't seem to give us any useful information about the pirate ship or its Captain. Scared, I suppose...",
	"So what do you need me to do, ",
	"I'm all out of work to give for today.",
	"There's no more work left for today.",
	"There's no more work to give for today. Come back tomorrow, if you're still interested.",
	"That's too bad...",
	"Hmm, that's a shame, ",
	"Certainly, I sincerely hope for our future collaboration. Now you can visit our governor. He may have more important jobs for you.",
	"Thank you and goodbye, ",
	"Who do you want to release in return for ransom?",
	"Nobody.",
	"All right, this is Captain ",
	" For this citizen I am prepared to pay ",
	" For this criminal I am prepared to pay ",
	". If he is rescued, we will commemorate the occasion with his immediate execution.",
	"Execution? Can I watch?",
	" For this person I am prepared to pay no more than ",
	"Deal. He's all yours. ",
	"No, that won't do.",
	"That's preposterous - of course not!",
	"Well, will a modest donation into your city treasure buy me a ticket to the show?",
	"Then take him and give me my money...",
	"Hrm... An interesting thought. Well, I suppose 3000 gold pieces will buy you an escort into the fort, where the execution will take place. Just keep in mind that your crew may not understand their Captain's actions, and your authority will drop considerably.",
	"I'm still in. Here's your 'donation.'",
	"Hmm, I've changed my mind.",
	"That's swell.",
	"All the best.",
	"You've already taken everything. What else do you want?",
	"Oh, right - wrong city. My fault!",
	"What insolence is this! Just wait until help arrives from the fort - then you'll sing a different tune!",
	"Sorry, but my plans don't involve waiting for their arrival. Just pay me and we'll be on our way.",
	"Fine, you win this time. But know that soon our squadron will be here, and they will surely wipe the floor with you!",
	"Keep talking! This city now belongs to me, and soon I will send your squadron off to the meet the sea devil! Hey boys, take this piggy and lock him up.",
	"This city now belongs to me, and I'll decide how to protect it. Hey boys, get this wannabe out of my sight!",
	"An air assault squadron? Hrm... All right, pay me and we'll leave the city.",
	"A squadron... Hmm... All right, pay me and we'll leave the city.",
	"What insolence is this! How dare you attack a colony that belongs to ",
	"?! You will pay dearly for the blood you've so needlessly spilled and for the damage you've caused our empire!",
	"From this moment on this colony belongs to me, and anyone who dares to doubt it will go straight to hell real soon.",
	"I represent the interests of ",
	" and I formally declare that from this moment on this colony belongs to ",
	"We need to discuss the ransom details. And I suggest you don't be stubborn, lest you want us to turn your beautiful city into a pile of ash, and hang all of you at the town square.",
	"All the ships have been repaired.",
	"Fine, you win this time. But know that soon our squadron will be here, and they will surely wipe the floor with you!",
	"Keep talking! This city now belongs to me, and soon I will send your squadron off to the meet the sea devil! Hey boys, take this piggy and lock him up.",
	"What else do you want from me?",
	"Just checking to see if I got everything...",
	"I've no other choice but to accept your conditions. Take your blood money and leave the waters of our colony at once!",
	"Allow me to take my leave, then.",
	"All right, tell me your conditions...",
	"To the victor go the spoils. So where is my money?",
	"Well then, we submit ourselves to the mercy of the victors.",
	"Since we don't know how the forthcoming changes might affect your health, I suggest that you leave the city sooner than later. Goodbye.",
	"What else do you want from me, villain?",
	"Don't you talk back to me, you blob.",
	"For the resistance you've put up earlier I have decided to execute you via firing squad.",
	"Just wanted to check on how Your Grace is doing. Well, I should go now!",
	"Settle? How do you propose to do that?",
	"I suppose that a sum of ",
	" gold pieces will save my life?",
	"I don't. I've gotta go - do take care.",
	"I think that this way we can settle our incident.",
	"Splendid!",
	"No! There's only one way to atone for your atrocities. Guards! Take him into the fort.",
	"Wait!",
	"Of course you do. Wait, I'll give you an escort. Guards! Get him!",
	"Wait!",
	"You'll have to catch me first!",
	"Naturally. For the completion of this task I give you ",
	", and your reward for a job well done will amount to ",
	"All right, I'll do it.",
	"Hrm... I think I'm going to pass.",
	"Wait, I completely forgot about yesterday's report! The thing is that this gang has already left our island. So I'm canceling the job.",
	"I see. Well, that's too bad.",
	"Wonderful, then! I'll be waiting for you in my residence when the job is done.",
	"I reckon you won't wait long, ",
	"Yes, there are reasons for my trust. For the completion of this task I give you ",
	", and your reward for a job well done will amount to ",
	"All right, I'll do it.",
	"Hrm... I think I'm going to pass.",
	"Wait, I've just remembered that yesterday a suspicious fellow was apprehended in the city. Seems like that's the same spy we've been looking for. Your services are no longer needed. ",
	"I see. Well, that's too bad.",
	"Wonderful, then! I'll be waiting for you in my residence once your search is done.",
	"I reckon you won't wait long, ",
	"I understand. Perhaps a monetary reward of ",
	" might stimulate your interest?",
	"Hmm, that's quite a sum... All right, I'll accept the job.",
	"Hmm... no, I think I'll still pass. It's just too dangerous.",
	"Although, I can't say that you've given me reason to fully trust you... I've changed my mind, I don't want to entrust you with this job.",
	"But, er... Well, all right. That's too bad.",
	"Wonderful! Now let's get down to business. When you get to ",
	" you'll need to find the local ",
	", his name's ",
	". Tell him I sent you and he'll give you a package of documents, which you'll need to deliver to me personally. For the completion of this task I give you ",
	". And remember to keep a low profile. If you are discovered in the city, the agent will not take the risk of contacting you. Are we clear?",
	"Yes, quite clear, ",
	". I will proceed to performing this task at once.",
	"That's not bad. However, you've exceeded the allotted time, so I've no choice but to reduce your reward. Your fee is now ",
	". Kindly accept it.",
	"That's good. However, you've exceeded the allotted time - I was expecting this letter earlier. As a result you've messed up my plans, so I've no choice but to reduce your fee. Still, I'm happy to present you with your reward - ",
	". Kindly accept it.",
	"I can't say I'm ecstatic to hear that, but I can't argue that time wasn't exceeded. So I guess I've no complaints, ",
	"Have you heard? Governor ",
	" is not very happy with the efficiency of a certain Captain ",
	"Governor ",
	" is not very happy with Captain ",
	". The Captain carried out his tasks, but couldn't do it within the allotted time...",
	"Find and destroy the smugglers, obviously. For the completion of this task I give you ",
	", and your fee will amount to ",
	". Will you accept this job?",
	"Yes, ",
	", I accept the job.",
	"No, I think I'll pass...",
	"Wonderful, then. In that case, I'll be waiting for you to bring me the good news.",
	"I reckon that they'll be here soon, ",
	"I need you to track down and destroy that pirate. Drown him or board him - I don't care. All I want is for this damn corsair to stop hunting in these local waters and messing with the commerce of ",
	". For the completion of this task I give you ",
	", and your reward for a job well done will amount to ",
	". So, do you accept this job?",
	"Yes, ",
	", I accept the job.",
	"I think not. Hunting pirates is not my idea of fun...",
	"Wonderful, then. Best of luck.",
	"Thank you, ",
	"You disappoint me!",
	"Forgive me, ",
	", but I cannot accept this job.",
	"Well, what can I say? I counted on you, and all you've done is waste my time. I'm very disappointed.",
	"Haw, I must admit I'm disappointed in you. My residence is always full of people that will jump at the opportunity to perform my tasks, and I've wasted so much time on you...",
	"Forgive me, ",
	", I've done all I could.",
	"Have you heard? Governor ",
	" is very unhappy with Captain ",
	". The Captain wasn't able to carry out his task. Imagine that!",
	"Governor ",
	" is quite irritated that a certain Captain ",
	" accepted a job, but wasn't able to complete it within the allotted time. Not good at all...",
	"I heard that governor ",
	" is very unhappy with you, Captain ",
	", seeing as you were unable to perform his task within the allotted time.",
	"I'm shocked! To find the target but make no provisions to ensure one's superiority is the pinnacle of stupidity. I am beyond disappointed!",
	"Wow, I must admit I'm disappointed in you. Finding one's target is pointless if you can't destroy it. My residence is full of cutthroats who are willing to do these kinds of jobs. Why did I even bother with you?.",
	"Forgive me, ",
	", but I don't want to risk my life so recklessly.",
	"Have you heard? Governor ",
	" is very unhappy with Captain ",
	". And he ended up being a grade A coward. Imagine that!",
	"Governor ",
	" is quite irritated that a certain Captain ",
	" accepted a job, but his own indecisiveness caused him to fail. Where have all the real Captains gone? Hee hee!",
	"I've heard that Governor ",
	" is very unhappy with you, Captain ",
	". People say you're a downright coward...",
	"Wonderful news! Well, we should settle up, then. Your fee amounts to ",
	". Kindly accept it.",
	"Outstanding! That'll be better for everyone... And now I am happy to present you with your due reward - ",
	". Kindly accept it.",
	"Thank you, ",
	"nice to do business with you!",
	"I am pleasantly surprised by the accuracy of our settlements.",
	"Have you heard? Governor ",
	" is singing all kind of praise about a certain Captain ",
	"Governor ",
	" is exalting Captain ",
	" for carrying out his jobs well, and on time. If you ask me, the Governor considers this man irreplaceable...",
	"I have heard that Governor ",
	" is very pleased with you, Captain ",
	". He characterizes you as a thorough and diligent officer. And I'm happy to hear that, Captain...",
	"Well, superb all around. You may return here, if you want in the future and perhaps I will have something else for you to do.",
	"Wonderful, then! I reckon I'd be pleased to be your regular source for this line of work.",
	"Splendid.",
	"Wonderful.",
	"In such difficult times, any help we can get is precious to us. We accept your offer - help us defend the colony, and we will reward you.",
	"Well then! Let's not delay!",
};
