string DLG_TEXT_BASE [137] = {
	"Pirates? In the city?! Oh, boy... hold him!",
	"That's a pirate! Hold him!",
	"Yeah, I'm a pirate. What of it?",
	"Ha! Just try and nab me...",
	"Spy? Turn in your weapons! Follow me!",
	"Enemy agent! Grab him immediately!",
	"Shut up, deadbeat!",
	"Be that as it may!",
	"Who are you, and what do you want here?",
	"Stop! Who are you? On what basis are you trying to enter the fort?",
	"Officer, I have a ",
	". So you see, I'm here on legal grounds. Please acquaint yourself with...",
	"What, can't you see the flag swaying on my mast? ",
	"I threw down anchor at ",
	", under the flag of ",
	". What else remains unclear to you?",
	"Pirates? In the city?! Oh, boy... hold him!",
	"That's a pirate! Hold him!",
	"Yeah, I'm a pirate. What of it?",
	"Ha! Just try and nab me...",
	"What, can't you see the flag swaying on my mast? ",
	"I threw down anchor at ",
	" under the flag of ",
	". What else remains unclear to you?",
	"Ah, Captain. How great it was with you on the sea! How many ships did we sink under your command! And here...",
	"And here, my friend, charming women, who don't exist in the sea, constantly hover around you.",
	"Captain, what's with the punishment?! We aren't land rats!",
	"Calm down, sailor! You're on an important and honored post, so no-can-do.",
	"How's the sea, Captain? Will we ever see it again?",
	"Of course, sailor! When the watch changes, go to the pier and enjoy the sea for as long as you want.",
	"I rush to report, Captain, that we're all aiming to get back to the sea. We've had it up to here with this shore duty!",
	"I'm tired of this whining! You've got enough to get drunk off on land! Serve there, where the Captain put you. Or will I have to string someone up as a warning.",
	"I'll tell you a secret, Captain. The new governor is a bribe-taker and treasury-looter. Not that that's any of my business...",
	"You're right, corsair. Your job is to stand at your post and maintain order. Now, stringing up the Governor... that's my job. Good job!",
	"Thank you for not forgetting about us, Captain! We'd go to hell and back for you!",
	"I know you strangers! You only love gold. There's going to be drinking in the tavern tonight. My treat! Don't forget to stop by.",
	"Aw, Captain! What kind guardians of order can we corsairs be?! How long has it been since we've had a real mission?",
	"Don't relax, corsair! Enemy armadas are hounding around our islands, so a bloodbath can happen at any moment.",
	"Captain, they say the king's sending his squadron here...",
	"Of course, corsair. While we live, there will never be peace. Even in hell we'll have to fight devils!",
	"Yo ho ho! What a great drinking party we had yesterday, Captain! It's too bad you weren't there.",
	"It's okay. I'll get my fill yet. And I certainly won't begrudge you boys.",
	"I'll tell you a secret, Captain. Since you've never done anything bad to us, me and the boys took a sweet little thing down...",
	"Oh, corsair, the noose is waiting for you!",
	"Cap! Free me from this cursed shame! I can't play the keeper of law and order here!",
	"You'd be better to remember that being the night watchman on a ship isn't easy either. Duty, my brother, is duty - wherever it stands. ",
	"There's an important matter!",
	"I have a matter for you.",
	"What do you want? Move along.",
	"Go on, stop blocking the road.",
	"Already left.",
	"You don't have to be rude. Goodbye.",
	"One tiny little question.",
	"A moment of your attention, I'm here on business.",
	"Look at this villain! He dared to show up at ",
	". Hold him!",
	"Ha! I recognized you, scoundrel! Grab him!",
	"Argh!",
	"Well, you asked for it...",
	"Do you see what's going on in the city? Though we aren't getting involved...",
	"Until the troubles turn into massacres, we aren't going to do a blessed thing. Let them riot.",
	"We're acting as if everything in the city is going normally. We can't fall under the influence of the mob, lest the troubles turn into a rebellion!",
	"Understood...",
	"You've gone to the tavern. And what do you say?",
	"Nothing for now...",
	"Don't you see I'm at my post! Don't distract me.",
	"Fine, fine...",
	"You want to report some violations to me?",
	"No, nothing of that sort. To add to that, I'm a captain. And by George, your boots are superb, how do you get them to glisten so? Well, I see you aren't listening. Goodbye.",
	"Look here, no fighting in public! The only reason you have to unsheathe your weapon is in self defense.",
	"Yeah, okay. I'll take that into account.",
	"Would you look at that weather! And here I am, standing here, wasting the day away. Only consolation I got myself is slapping the flies from my face. Which is entertaining, I grant you.",
	"I sympathize. Mostly. But we've all got to do our jobs.",
	"If you're gonna sob, find another shoulder. I need to keep order, so I've got no time to tongue wrestle with you.",
	"Nah, it's just that you were standing there like a statue - I wanted to see if you were real, or just an uncanny likeness.",
	"You think that upholding the law is easy, do you? Hah! I'll have you know that it's as dangerous as it is important. I remember this one time...",
	"Yeah, uh. I'm sure it's all very interesting, but let me take a rain check. I'm in a rush.",
	"Just keep walking. Don't distract me.",
	"You got it, soldier.",
	"Hey, you! Here, bring us a cup of wine from the tavern, will you? I'm dying of thirst.",
	"Yeah... and be hanged for enabling soldiers on duty to drink? Sorry, friend. How about we wait 'til your shift is over, shall we? Then you can booze to your heart's content.",
	"Why-oh-why do I attract all the village idiots? Where are all the pretty girls with the yummy legs? Have they all moved away or something?",
	"What, is this your idea of standing guard? Keep this up and the city will be crawling with troublemakers... like me! Mwa-ha-ha!",
	"You look like a hearty fella! How'd you like to come work for us? You get two meals a day, your own spot in our spacious barracks - and free booze! Off-duty, of course.",
	"Yes. As... enticing as that sounds, I'll have to pass, lest I find myself stabbing my drill sergeant. I'm not used to taking orders, see. ",
	"I can't take this heat... I'd give anything to be back in Europe.",
	"Yeah, you don't seem the Caribbean type...",
	"Hmm... I see. Listen, I wanted to ask you...",
	"Hmm... There's something off about you. How about we go see the commandant and get to the bottom of this...",
	"Hrm. There's something distinctly fishy about you.  Here, ",
	"how about you hand over that weapon, and follow me. I've got some questions for you.",
	"Be that as it may!",
	"Sure, I'll be right behind you... when pigs fly!",
	"Ah, I see... Well, everything seems to be in order. So go on, ",
	"Oh... Good grief, it must be exhaustion. All right, ",
	", all is in order. Please forgive me.",
	"I thought so!",
	"Your license is expired, and therefore invalid. I'm afraid it comes with me. And so will you, once you hand over your weapon. Come on, follow me.",
	"Be that as it may!",
	"I'll be right behind you... in hell!",
	"Hm. Looks like everything is in order. I should mention, though, that your license expires today. I'll let you through this time, but you will need to renew that.",
	"Thank you. I'll get a new one as soon as I can.",
	"Hm. All seems to be in order. I feel I should point out, though, that your license is nearly expired. You only have another ",
	". Please keep that mind. ",
	"Thank you. I'll get a new one as soon as I can.",
	"Very well, your license is valid for another ",
	". You may pass.",
	"I see, ",
	". You may enter the city. Your license is valid for ",
	". Sorry about the trouble.",
	"Everything's in order, ",
	", I won't hold you any longer.",
	"Great. You take care now.",
	"Thank you, officer.",
	"Hey, buddy - watch that you don't break anything in the lighthouse.",
	"A lighthouse is vital to any city. Be careful!",
	"Yeah, yeah. Don't fuss yourself.",
	"Everything will be fine.",
	"Don't get so close to the guns. They are live, you know. This is a military facility!",
	"Munitions handling by unauthorized persons is strictly prohibited!",
	"If I see you hanging around the guns... Well, just don't. That's all I'll say.",
	"I got you.",
	"Okay, I understand.",
	"Yeah, I can vouch for that. ",
	"They do live here.",
	"They are indeed a local.",
	"I see. Thanks for your help.",
	"All right. Thanks for the help.",
	"What in God's name are you doing, running around the city with your blade flapping in the breeze? Slip it away, immediately!",
	"I order you to hide your weapon at once!",
	"Hey, buddy. How about we quit spooking the locals, and sheathe our weapon?",
	"Um. Sure, okay.",
	"All right.",
	"Whatever you say.",
	"You wish!",
	"Keep dreaming.",
	"Sure... when pigs fly!",
};
