string DLG_TEXT_BASE [70] = {
	"Look, I'm just a merchant. I don't want any trouble. That's not the business I'm in. ",
	"Yesss... yet there is unrest in the city.",
	"I don't think the unrest will affect my sales. Now the tavern owner, he's got something to worry about.",
	"I see.",
	"They say you went to the tavern, to the werewolf. How was it in there?",
	"Not much to say, really...",
	"You want to buy the best equipment for yourself and your men, Captain? Then you've come to the right place!",
	"Oh, Captain, I just knew that you were going to come up to me! May I suggest supplies for you and your officers, as well as many other essential items?",
	"Show me what you've got.",
	"I have another matter to attend to.",
	"You wouldn't, perchance, have come across any mummy powder?",
	"Do you sell mummy powder?",
	"Listen, do you know where I can get mummy powder?",
	"Sorry, not interested.",
	"Yes, I can confirm that ",
	"he's really a local resident.",
	"she's really a local resident.",
	"I understand. Thanks for your help.",
	"All clear. Thanks for your help.",
	"Mummy powder? Uh... maybe. What's a mummy?",
	"What powder? Mummy who? If you're looking for make-up...",
	"Mummy powder, huh. How about you describe it to me?",
	"You're asking me about that again?",
	"Again with that...",
	"Again with the powder?",
	"I already answered your question! What more do you want?",
	"I already answered your question! What more do you want?",
	"I already told you what I thought proper. Again with the strange questions?",
	"I already told you what I thought proper. Again with the strange questions?",
	"Again with the strange questions? I don't have anything to add to what I said earlier!",
	"Again?! Again?!",
	"Words fail me! Again?!",
	"Again about that cursed powder?!",
	"It's the embalmed body of an Egyptian, buried thousands of years ago.",
	"Yes, I'm asking. Maybe you've remembered something?",
	"I'm asking again, maybe something has changed...",
	"Yep, I'm asking again.",
	"Hell no. Nothing like that. Never even seen it, to be honest. You're the first to even ask after something so outlandish. Anyway, I doubt the Holy Church would look kindly at me trading that kind of thing. If they found out, I'd be in real hot water...",
	"Nope, never come across nothin' like that. And if'n I did, I sure wouldn't a' bought 'em. Me, I'm a God-fearing, church-going fellow, and I don't think the Inquisition would take kindly to me trading that kind of merchandise.",
	"No, I've never seen the like. And even if I had, I wouldn't stock them. I'm proper lady-parishioner, I am. I don't think the Inquisition would look too well on my trading in that rot.",
	"No, that's outside my realm. And for the best, I reckon. Lord, if my wife found out, she'd drop everything and run straight for the Inquisition... To honor and obey, my foot...",
	"No, never seen the like - and it's probably better that way. If my husband thought I was involved with that nonsense... Lord, the earful I'd get out of him...",
	"Oh? Well, fair enough.",
	"No, no, my memory is just fine. I don't know nothing about no mummies, and I don't wanna know. And I suggest you forget them too, 'less you wanna run afoul of the church...",
	"No, my memory's not at issue. I just don't go in for any of that hocus pocus. And if I were you, I'd forget about it too, lest the church find out and accuse you of witchcraft. It's happened to better men...",
	"My memory's just fine; I just don't want to talk about any mummies. Just wait 'til the Holy Inquisition hears about this...",
	"Oh, mind like a steel trap, me. But I'll tell you, if my wife knew I was mixed up in this stuff, the Holy Inquisition would've pounced me ages ago.",
	"Oh, I remember all right... Hum. I think I better call my husband...",
	"What a queer tongue you have. Enough of that, eh?",
	"Nothing's changed, okay?! Absolutely nothing! I ain't seen no damned Egyptians - neither whole nor comminuted!",
	"Look, I am resolute! I don't deal in corpses, Egyptian, whole powdered, or otherwise! ",
	"Trust me, all is normal - I hain't seen no corpse dust, and I hope to God it stays that way. ",
	"Look, I assure you that nothing has changed. I haven't seen any of your powdered corpses, and for that I am thankful. And if you do not cease these idiotic questions, I shall be forced to call upon my husband...",
	"Changed?! For the last time, I ain't got nothin' to do with no corpses, powdered, stiff, juicy, or otherwise! What the hell is wrong with you?!",
	"Changed?! For the last time, this is not a mortuary! How could I be any clearer?! What is it in that statement that you do not understand?!",
	"Relax, grandpa, I hear you. Careful you don't strain your liver.",
	"Okay, lady, I hear you. Don't get so riled up. I'm fresh out of smelling salts. ",
	"I want no more of your business. ",
	"From now on, your money is no good here. Get out!",
	"Fine, whatever. Looks like you don't need my money.",
	"No big loss...",
	"You're certainly persistent. I guess you're really desperate for that powder.",
	"That I am, that I am. So I ask you again: do you have it? Don't be scared; just be straight with me. This stays between us.",
	"Oh God... All right, I'll serve you, so long as you leave off with all your queer business. I just run a shop here.",
	"Oh, it's you again... Well, so long as you're not here about that horrible corpse business, I suppose one customer is as good as the next...",
	"Great!",
	"Terrific!",
	"I have it, though it's not for anyone's eyes or pocket, as I'm sure you understand. I am, however, willing to part with it. One thousand coins, and it's yours.",
	"Fine, it's all yours.",
	"I, uh, don't usually carry around a sum like that. Let me go check with my accountants...",
};
