string DLG_TEXT_BASE [222] = {
	"What's this, a spy?! Guards!",
	"Watchmen! There's an enemy in the city!",
	"Oh good God. I'm leaving, already. So can it.",
	"I've heard tell, sir, that you own this fine town. ",
	"My, my. The city chief himself, looking to me for answers. I'm over the moon!",
	"No, never mind. It's nothing. Good luck with your business!",
	"Oh, I'm just poking around your city here. See ya 'round.",
	"I have a question for you.",
	"I need information.",
	"You and I need to talk about money.",
	"About those fiduciary concerns...",
	"Staring ain't polite, you know. Move along.",
	"Enough blocking the road. Move it.",
	"Already gone.",
	"Well, no need to be rude. Goodbye, then!",
	"Just one little question.",
	"Please, give me a moment? One little... just a flyspeck of a question.",
	"I need to talk about money. ",
	"About my financial situation...",
	"They call me ",
	"My name is ",
	"Well, you can call me ",
	". What do you need?",
	". I don't think I've ",
	"seen you around before",
	"seen you in here before",
	". Who are you?",
	". Who are you, and why have you come to me?",
	"Magnanimous greetings, fair ",
	". My name is ",
	". And how may I address you? ",
	"Well, slap my ass sideways, ",
	"! They all call me ",
	". So what do they call you to your face?",
	"Yes, ",
	"? Did you want something? Oh, excuse me. My name is ",
	". And you would be?",
	"Well, blow my mizzenmast! ",
	"Fie and a curse for every sin! ",
	"Consarn you! ",
	"Yes I'm Captain ",
	". Have you not heard",
	"",
	" of me, ",
	"you thrice-plucked scalawag?",
	" and the most feared name in these scurvy waters! ",
	" and strike me down cold, if I'm lying! ",
	"I am ",
	", a Captain. ",
	"I'm called ",
	"You can call me Captain ",
	"My name is ",
	", I am a Captain. ",
	"They call me ",
	"You can call me Captain ",
	"I was aiming to learn a few things about your fair town! ",
	"Perhaps you can tell me a bit about this city.",
	"I have a question for you.",
	"I need some information.",
	"Let's talk about money, shall we? ",
	"About those financial arrangements...",
	"Halt! Who goes there?! Be quick, now! There are spies about, and the Governor has personally charged me with their detection. ",
	"Halt! I am acting in the interests of the city of ",
	" under orders from the Governor. I'm searching the city for an enemy agent.",
	"Freeze, pal! Governor ",
	" is determined to find the spy in our midst.",
	"Halt, miss! Who goes there?! Be quick, now! There are spies about, and the Governor has personally charged me with their detection. ",
	"On behalf of the city, miss, I must detain you. ",
	" under orders from the governor. I'm looking for an enemy agent in the city.",
	"Hold it, sweet cakes! Governor ",
	" is determined to find the spy in our midst.",
	"Oh! It's you, ",
	" . You old has-been",
	"Great to see you again, granddad. ",
	"Aho, it's the Captain himself. ",
	"! I had no idea you were kicking!",
	"! Drunk as usual, I gather...",
	"! Still your own man, I see!",
	" So spill it. What do you need?",
	" All right. What is it this time?",
	" Can't you leave a man in peace? ",
	", Captain ",
	"Hello, ",
	"Copious greetings, Captain ",
	". Pray, what could such an esteemed figure want of me?",
	". Why have you come?",
	". What would you like to know this time?",
	"Hello, Captain ",
	"Salutations. Oh, it's you, ",
	"Ah, Captain ",
	". I never expected ",
	"",
	"to clap my eyes on you again,",
	", and I can't say I'm thrilled",
	"",
	"to do so now. But all right, ",
	". It grieves me to see you in such health, ",
	" what do you want from me?",
	" why have you come here?",
	" how can I ",
	"be of service?",
	"get rid of you?",
	", Captain ",
	". What can I do for you?",
	"Ah, our very own Captain ",
	"! What would you like to know this time?",
	"Hello, ",
	". Did you need something?",
	"No, I'm just going now. ",
	"Oh, nothing. Just heading off to the tavern.",
	"All right. Never mind, then! May fortune be with you!",
	"Just taking a nice stroll 'round the city. Alone. Goodbye.",
	"You sure you're being straight with me, ",
	"And what of it, ",
	"I will remember you, ",
	" Tell me... what do you need?",
	"Nice to meet you, Captain ",
	"Happy",
	"",
	" to make your acquaintance, ",
	"Oh no, Captain ",
	". The pleasure is all mine. But surely you're interested in more than just my name, aren't you?",
	"Well, I wanted to learn a few things about this town of yours!",
	"I want to know something about this city.",
	"I have a question for you.",
	"I need information.",
	"I want to discuss financial matters.",
	"Regarding those finances...",
	"Halt! Who goes there?! Quick, now! I'm looking for an enemy spy, by order of the Governor ",
	"Halt, in the name of ",
	". By order of the Governor, I'm searching the city for an enemy agent. ",
	"Freeze, buddy! Governor ",
	" really has his nose out for that spy.",
	"Halt, miss! Who goes there?! Quick, now! I'm looking for an enemy spy, by order of Governor ",
	"I must detain you, miss! I am acting on behalf of the city of ",
	". By order of the Governor, I'm searching the city for an enemy agent. ",
	"Wait, honey! Governor ",
	" really has his nose out for that spy.",
	"Perhaps you misheard me. I'm going.",
	"Oh, that's all right. Just heading off to the tavern.",
	"Well, aren't you busy. All right, good luck!",
	"I'm just poking around the city. Goodbye.",
	"You sure are a sight",
	"",
	" for sore eyes. What can I do you for?",
	"Why, Captain, aren't you a talkative fellow. I suppose I can keep you company... over a bottle of rum.",
	"Yes, ",
	"Well, what else do you want?",
	"I see, dear ",
	", that gum-flapping is your sport of choice? ",
	"Enough with the questions, Captain. Why don't we share a drink, instead?",
	"What would you like to know, ",
	"I'm all ears, Captain.",
	"Let's wrap this up, Captain. I need to leave soon.",
	"Always happy",
	"",
	" to take such great company, ",
	". Please, go ahead.",
	"Yes, ",
	"Why, Captain, aren't you a talkative fellow. I suppose I could do with a bit of company...",
	"What tales have been frolicking on the tongues of the locals? ",
	"What's new in these parts?",
	"How's life on dry land?",
	"Would you give me some directions?",
	"I can't seem to find this place I'm looking for...",
	"I'm looking for directions...",
	"I want to know the local word on a certain individual.",
	"Would you happen to know what people are saying about a certain someone?",
	"I wanted to learn more about the locals.",
	"Tell me about your colony.",
	"I've got an important matter to discuss!",
	"I've got something to discuss with you...",
	"Who, me? I didn't say anything. Later!",
	"Oh, nothing. Just heading off to the tavern.",
	"Okay, never mind then. Good luck to you!",
	"I'm just scoping out the town. Goodbye.",
	"T' be honest, that's not my area of expertise. Still, I can tell you what I know.",
	"What you wanna know about our colony?",
	"Course. What do you want to know?",
	"What is this city?",
	"Tell me about the fort here.",
	"Let's change the subject, shall we?",
	"Wise guy, eh? If you would kindly direct your attention to the right corner of your screen...",
	"Oh. Indeed. Forsooth, even! Ahem.",
	"Reckon I don't know a thing about that.",
	"A pity.",
	"What do you expect me to say about it? I just live here! ",
	"What do you expect me to say about it? I just live here! Frankly, I don't even want to think about it!",
	"Would you leave me alone already? I told you, I'm not a spy!",
	"Look, I already told you I live here! What do you want from me?",
	"Would you just drop it, and let me be? I'm a taxpayer, you know!",
	"Is there no end to your stupid prattle?",
	"What, again?! Now look, I've had just about enough!",
	"Oh my Lord, would you PLEASE leave me alone!",
	"Can anyone corroborate that statement?",
	"Oh, excuse me. I've already asked...",
	"Beg pardon, there are just so many people here...",
	"All right, all right...",
	"Why, just ask anyone! Here, why do you keep on me?! If you've a problem, why don't we just go to the Governor and let him settle it!",
	"Hum. Perhaps it's best we don't bother him. All right, I believe you...",
	"Nigh on anybody in town! Say, ",
	" is an old mate of mine. And look, there ",
	"he",
	"she",
	" is, standing right over there.",
	"Well, let's see... Oh! You see ",
	", over there? Go ask him, why don't you?",
	"Well then. Let's turn our attention, shall we.",
	"Yes, I confirm that ",
	"is a local resident.",
	"currently resides in this settlement.",
	"I... see. Well, thanks for your help.",
	"All... right then. Thanks for your help.",
	"Sir, as a citizen, I must kindly ask that you sheathe your blade.",
	"My good fellow, I beg you - stow your blade, lest you begin to unnerve peaceable townsmen... such as... myself.",
	"Um. Sure, okay.",
	"All right.",
	"Whatever you say.",
	"Whoa, buddy. Watch where you're going with that skewer! You don't want me to start getting nervous...",
	"I get me the willies when I see men stalking around, weapons at the ready...",
	"Point taken.",
	"I'll away it at once!",
};
