string DLG_TEXT_BASE [456] = {
	"The alarm's been raised in the city! Everyone's out looking for you! If I were you, I wouldn't hang around here.",
	"All the city guards are hounding the city for you. I'm not dumb enough to hang around talking with you.",
	"Run, pal, before the soldiers make mincemeat out of you...",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Dirty murderer! Out of my house! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Heh, the alarm's no problem for me...",
	"They've got nothing to catch me for.",
	"Shut your trap, ",
	", or I'll rip out your rotten tongue!",
	"Heh, ",
	", and still the same - after pirates! I'll tell you what, buddy. Sit quiet, and you'll live...",
	"Hey, Doctor Blood! ",
	"Great to see you, Peter Blood.",
	"It's good that you've come around here, ",
	". How's Colonel Bishop doing these days?",
	"Alas, I am leaving, ",
	". 'Til we meet again.",
	"New clients, new gold. ",
	"Money doesn't have a smell. ",
	"Piasters don't have a smell. ",
	"Good deeds alone don't fill the belly. ",
	", at your service!",
	"Happy to meet a new client, ",
	"Always happy for new clients, ",
	"Welcome, ",
	". My name is ",
	". My store is at your service.",
	". I am completely at your beck and call.",
	"Allow me to introduce myself. ",
	"My name is... I ",
	"I ",
	"am captain ",
	"The alarm's been raised in the city! Everyone's out looking for you! If I were you, I wouldn't hang around here.",
	"All the city guards are hounding the city for you. I'm not dumb enough to hang around talking with you.",
	"Run, pal, before the soldiers make mincemeat out of you...",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Dirty murderer! Out of my house! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Heh, the alarm's no problem for me...",
	"They've got nothing to catch me for.",
	"Shut your trap, ",
	", or I'll rip out your rotten tongue!",
	"Heh, ",
	", and still the same - after pirates! I'll tell you what, buddy. Sit quiet, and you'll live...",
	"Lighting strike me down! ",
	"Devil! ",
	"A thousand devils! ",
	" enemy ",
	" opponent ",
	" cursed spy ",
	" in the city! ",
	" right on course! ",
	" in the crew quarters! ",
	"Guards!",
	"Soldiers!",
	"Holy Virgin ",
	"Lord Jesus ",
	"Saint Sebastian ",
	"Watch! ",
	"Help! ",
	"You're a spy! ",
	"Enemies in the city! ",
	"Scouts in the city! ",
	"Betrayal! ",
	"Soldiers, here!",
	"Shut your trap, ",
	"Quiet on the deck!",
	"Shut up!",
	" Or I'll ",
	" rip out your tongue and feed it to the dogs, ",
	" knock out your brains, ",
	" strangle you with your own guts, ",
	"huckster!",
	" huckster!",
	" villain!",
	"For God's sake, ",
	"I ask you, ",
	"Immediately ",
	"shut your mouth!",
	"stop squealing like a butchered pig!",
	"shut up, already!",
	" Or I won't give a farthing for your life!",
	" I'm not here! And never was! Got me?",
	" Or I'll have to kill you on the spot.",
	"Lighting strike me down! ",
	"Devil! ",
	"A thousand devils! ",
	", by the nickname ",
	"Butcher, ",
	"Ham ",
	"Ripper ",
	" in the city! ",
	" right on course! ",
	" from the starboard side! ",
	"Guards!",
	"Soldiers!",
	"Holy Virgin ",
	"Lord Jesus ",
	"Saint Sebastian ",
	"! It's the ",
	"! Catch him ",
	"! Grab him ",
	"! Hold him ",
	"gallows bird! ",
	"thief and murderer! ",
	"escaped convict! ",
	"Soldiers, here!",
	"Shut your trap, ",
	"Quiet on the deck!",
	"Shut up!",
	" or I'll",
	" rip out your tongue, huckster!",
	" beat the brains out of you!",
	" cut your guts out!",
	"For God's sake, shut up!",
	"I ask you, don't scream!",
	"What's with the noise?",
	" I'm already leaving!",
	" I'm not here!",
	" I don't want to kill you!",
	"Captain ",
	"That's me ",
	"Who am I seeing? It's ",
	"They haven't strung you up yet? Ha ha!",
	"They say you've been the guest of the sea devil!",
	"I heard that you were hanged at Port-Royal.",
	" Great to see you!",
	" Welcome!",
	"Hello, ",
	"Welcome, ",
	"Good day, ",
	"Captain",
	". Did you like ",
	". Been enchanted by ",
	" our",
	" island? ",
	" town? ",
	"It's not bad at all, ",
	"Excellent place,",
	"Beautiful girls are here,",
	" isn't that the truth?",
	" don't you think?",
	"Captain ",
	"Oh. It's you again, ",
	"You scared me, ",
	". Mothers already use your name to scare misbehaving children!",
	". I hope that you've had no run-ins with the law?",
	". Your reputation leaves much to be desired.",
	" To what do I owe your visit?",
	" What do you want?",
	" Why have you come?",
	"Welcome, Captain ",
	"! It's a bit stormy, today",
	"! Looks like a storm's brewing",
	"! A strong wind is coming up",
	", don't you think?",
	"You're still alive, ",
	"And I'm happy to see you, ",
	"We've known better times, ",
	"huckster!",
	"pal!",
	"sea wolf!",
	" I thought ",
	"your wife had dulled you with ale!",
	"the termites ate you!",
	"that your old lady has driven you to the grave!",
	"Good day, ",
	"Good health, ",
	"Hi, ",
	". You're right, ",
	". Absolutely right, ",
	"the local mulattoes are simply enchanting",
	"that's hard to argue with",
	"and the local dames will twist the heads of anyone.",
	"To hell with this chit-chat, ",
	"Turn on another tack, ",
	"You're babbling like a parrot!",
	"Don't cloud my head!",
	"Your words are cheaper than a cracker!",
	" I've arrived in the store!",
	" And why are you sitting here?",
	"Good day, ",
	"! Yes, but yesterday ",
	"it was completely calm.",
	"the weather was splendid.",
	"there was no breeze.",
	"Whistle for everyone to the top! ",
	"Hold to be inspected! ",
	"What does a gentleman of fortune need in my store? Heh, heh...",
	"What a delightful surprise for a poor old merchant! Heh, heh...",
	"What wind brought you into my store?",
	"Open the ports!",
	"Hooks to the side!",
	"Steady the course!",
	" In my store you will find ",
	" In my store you will find ",
	" the best prices on the island. ",
	" a great selection of goods. ",
	" goods of the highest quality. ",
	" I am at your service",
	" Whatever you say",
	", Captain!",
	"Any goods for the gentleman of fortune! Heh, heh! So long as he's yet to be hanged out to dry in the sun!",
	"The wind is rustling the chains of those hanged at the port. But piasters don't smell, am I right?! ",
	"Do you wish ",
	" to buy goods of the finest quality from ",
	" to buy or sell cargo",
	" to acquire some profitable freight ",
	"? I'm completely at your service!",
	"? My store is at your service!",
	" Happy to meet you",
	" Get comfortable",
	", Captain!",
	"Here's my tip to you, Cap: be stingy, don't buy too many bullets. It's easier to search the dead!",
	"From first sight, I knew you were a clever runt. ",
	"But now I see that you're a real hero.",
	"You're young, but ",
	" you've got a sharp mind.",
	" you won't be tricked.",
	"I'm ready to buy all of the cargo from your captured prizes. Want to buy silver or gold? It's always in style!",
	"Merchant sailing is a profitable business, Captain ",
	", isn't that so?",
	"Not one of the seventy-five has returned home! They all sank into the abyss of the sea! ",
	"Fifteen men on a dead man's chest!",
	"Drink, and the devil will lead you to the end!",
	" Yo ho ho, and a bottle of rum. ",
	"What do you need, Cap?",
	"What are you out to purchase, Captain?",
	"I see you're no pushover, Captain ",
	". Listen, for a regular like you, I've gotcha some really nice bargains!",
	"All right, Captain ",
	". Out of sheer respect, I am willing to take it on the chin a bit. What is it you would like? ",
	"I swear, you are the most nauseous man I've met. ",
	"Buy some peanuts. The pigs just love 'em! ",
	"What, you're expecting me to shine your boots with rum? ",
	"I know your kind. Rum at dawn, gallows at sundown. ",
	"How in hell did your mother let you out to sea? This is the land of brine, boy! Maybe you'd make a descent tailor...",
	"I had thought, ",
	"I was hoping, ",
	"that you had left our island.",
	"that I had seen the last of you.",
	" Corpses are dragging you down like millstones... ",
	" How many seafarers have you sent to rot amidst the limpets?",
	"Why Captain ",
	", your passion for commerce exceeds even my wildest expectations!",
	" Would you like to take another glance around the shop, before departure?",
	" Would you like to buy something special?",
	"Let's see what you've got, you old sea dog!",
	"I merely want to browse your inventory, my good man.",
	"I swear by the gallows, ",
	", I won't let you make a fool out of me! Out with the merchandise, stat!",
	"Let's see your merchandise, ",
	"You got that right! Corpses don't bite! So, what have you got in that hold of yours?",
	"As for you, dear sir, I would advice you to attend to your business. What goods can you offer me?",
	"Just you watch. Soon you too will become my prize... Just kidding. Never mind. So do you have any daily specials, or what?",
	"Let's talk about business, ",
	"What do I want? I want to buy something!",
	"Boozing will be the end of you, ",
	". Let's have a look at your goods.",
	"Yeah, I know your discounts! Two pounds for the price of three! Out with the merchandise, stat!",
	"That's always nice. Now let's do some business.",
	"Less yapping and more pandering. I'm in a rush.",
	"Hey, now. You could put someone's eye out with that. Anyway, let's get down to business.",
	"Hey, let's talk about something else, shall we?",
	"¡Ay caramba! Look, I'm here about something else entirely!",
	"I have something to discuss with you, ",
	"I've got business with an old pirate. Yes, I mean you!",
	"Let's get down to business, sir!",
	"You old rogue! I swear to the devil, you're not tricking me! I'm here on another matter!",
	"I completely agree, ",
	". I've got other things to discuss with you.",
	"Wait, you're smashed already?! Well, er... Hey, listen. I've got something for you.",
	"No, my chap about town; I am not here to shop. Here, listen up.",
	"You scoundrel, the hell with you and your discounts! Listen, I want to talk with you.",
	"Yes, ",
	", discounts are always nice, but that's not why I'm here.",
	"Clam it, you old souse, and unclog those cauliflower ears of yours.",
	"Presumably that would be the rum, then. Which is not to say I'm thrilled with you, either. So let's get down to business, shall we?",
	"You've already bled me dry, you old rogue! I've got more important business.",
	"Your sarcasm is unseemly. Anyway, that's not why I'm here.",
	"Business before pleasure. There's something I want to know.",
	"Not now. I need some information.",
	"To hell with your prices! First you tell me all I need to know.",
	"Yeah, that's great. There's something I want to know.",
	"Thanks for the tip, you old thug. But here, tell me something.",
	"I have a question for you.",
	"Gold can wait. There's something I want to know.",
	"Sure, that's great. Now, I want to ask you something.",
	"I think you know what I want to ask you.",
	"I hope you've got an answer for what I'm asking. ",
	"Does anything other than price tags ever enter that melon of yours? Well, heh, that's actually what I wanted to talk to you about...",
	"No, it's about something else. I need some information.",
	"Ol' buddy, ol' pal, relax. I just want to ask you something.",
	"Simmer down there, partner. Let's all be cordial-like. Just answer my question, and I'll be on my way.",
	"Look... I never expected you to say something smart, but I know you know something.",
	"I won't keep you long. I just have one question.",
	"To better days, you old souse.",
	"All the best, ",
	"¡Caramba! Look, don't move a muscle. I'll be right back.",
	"It was good to see you, ",
	"! Take care!",
	"Cast off!",
	"Goodbye, my good man.",
	"Hey you, whatcha hidin' there? Rum? No?! Well, all right. I guess I'll go wet this here whistle somewhere else.",
	"Pardon me. I have urgent business in the city.",
	"Ho. Well, we'll meet again.",
	"I have to go. Goodbye, ",
	"Don't you talk back to me! I ain't got the time to argue with you!",
	"I should probably go check up on the ship. Who knows what goes on while I'm away. Goodbye, ",
	"Hey, buddy - you okay? It's me, ",
	"! Okay, sleep it off. I'll come back later.",
	"I'm afraid your liver will get to you before I do...",
	"Count your piasters, you old fox! I'll be back later.",
	"It was nice to see you, ",
	"Excuse me, but I'm busy with other clients. Come back tomorrow.",
	"Oh, really! Fine, I'll come back later.",
	"I have me some nice swords and guns... cannon balls, some very valuable lumber, and oh, all manner of goods! What takes your interest, then?",
	"Would you like to purchase some silver or gold? Or perhaps the valiant sir would fancy a fine blade?",
	"My hold is full of booty! By comparison, piasters ought to smell far sweeter...",
	"My objective is to free my hold of booty and fill it with your gold. Ha-ho!",
	"You'd sell your own mother for a full-weight doubloon! All I need is to replenish my stock.",
	"I need to sell some cargo and replenish my stock.",
	"So what do you have for sale around here?",
	"Show me your cannon balls, bombs, and whatnot.",
	"Show me your swords and guns, and whatever else you've got there.",
	"I wouldn't mind a few new guns... Maybe some ammo, and a nice-looking ring.",
	"I'm interested in jewels and exotic idols. It's... a hobby, you see.",
	"No, no shopping for me today. Later, perhaps.",
	"Let me go wet my whistle first. Don't go anywhere; I'll be right back.",
	"I'm in no mood for shopping. Another time.",
	"Excuse me. I've an urgent matter to attend to. Goodbye!",
	"Are you trying to pull a fast one? Where's your ship? It's not at the pier!",
	"I swear to the devil, you're not tricking me! Your ship ain't at the pier!",
	"I don't see your ship at port, Captain ",
	". I hope it... wouldn't be the Flying Dutchman?",
	"Captain, it's far easier to load the ship from the pier. Moor your vessel and come on back 'ere.",
	"What a bother. All right, old sly-boots. We'll meet again!",
	"No charade, ",
	". I just moored on the other side of the island.",
	"No. My ship's called the Black Pearl. Hey, you're looking a bit peakish. Have you eaten today? Ha, ha! It's a joke! I'm ribbing ya'!",
	"Thanks for the tip. I'll keep it in mind.",
	"Oh Captain! Help us, I beg you!",
	"Captain, on behalf of all the traders, I beg you to come to our aid! ",
	"Oh? What happened?",
	"I had this one gig, but ",
	" agreed to do it for me.",
	"Oh, really! Fine, I'll come back later.",
	"What?! Start from the beginning!",
	"I'm listening. Talk slowly, now.",
	"My ship's hold is plum full of fresh new cargo for your store.",
	"My ship is chartered to deliver cargo to your store. They're unloading the goods as we speak.",
	"Unfortunately, I must withdraw from my commitments. In light of the current political situation, I cannot deliver the cargo.",
	"I would like to propose that you charter my vessel, for transport of fine material goods.",
	"With my fine ship, I can deliver any cargo anywhere in the world.",
	"Would you like to charter my vessel, ",
	"? She's a reliable ship, with an experienced crew.",
	"Man, are these sea legs tired... Listen, friend. The money thing is especially acute.",
	"All right, you old crook. Let's talk about the money.",
	"Here, let's talk about money.",
	"You know what time it is? It's money time.",
	"I'm here on orders. Man by the name of ",
	" sent me. I need to  take something...",
	"Just here to tell you I did as you asked. The Blue Bird will torment merchants no more. So, about that reward...",
	"I regret to inform you that I was unable to sink the Blue Bird. I did all I could, of course. You know how it goes.",
	"How are your colleagues' flutes doing? Everything fine there?",
	"You sure you don't want to give me that money? I have earned it, fair and square. Now, don't answer right off. Stop and think a moment.",
	"Here, fill me in on the latest gossip. I'm bored to death, standing here all day.",
	"Settle down, you old rogue. Here, tell me about life on dry land. How's it treatin' you?",
	"I feel like I've spent an eternity out at sea. Naught but a desert of brine. What's new in your neck of the woods?",
	"You look pretty clued-in. Has anything important happened lately?",
	"Actually, now is not the best time to talk...",
	"Oh, I moored my ship on the other end of the island. I'll just come back later!",
	"Oh, pardon me, ",
	". I'll come back later. My ship has yet to arrive at the pier.",
	"Blast! Those dunderheads forgot to load the ship! Yerrg, I'll be back later!",
	"Pardon, I've got to go and order my ship moved to the pier!",
	"Man, are these sea legs tired... Listen, friend. The money thing is especially acute.",
	"All right, you old crook. Let's talk about the money.",
	"Here, let's talk about money.",
	"You know what time it is? It's money time.",
	"I'm here on orders. Man by the name of ",
	" sent me. I need to  take something...",
	"No, please don't! At least for as long as you're fighting ",
	"In that case, goodbye.",
	"You're ",
	", aren't you? Your name has been associated ",
	"with some truly terrible rumors",
	"with less than savory notions",
	"... I really don't want to get mixed up with you.",
	"Bah... A man makes one false step, and the world spits on his foot.",
	"Ah well. There are better things to do at sea, ",
	"Heck, ",
	", I'm in no mood to charter anything today. Come back tomorrow.",
	"Come back tomorrow. I might have quite the profitable proposition for you. ",
	"All right, then. Tomorrow it is!",
	"Your wretched bucket is too small for the cargo. I've got no deal for you today.",
	"Unfortunately, Captain ",
	", to deliver this cargo I'll need a somewhat more spacious vessel than yours.",
	"Well, otherwise my vessel is quite dandy. But I understand. Goodbye.",
	"I understand. Business first, and all. Farewell.",
	"Oh! I was actually about to ask you about that. Thing is, I need to deliver a cargo of ",
	" in the amount of ",
	", to ",
	". On delivery, you'll receive a reward of ",
	". So how does that sound?",
	"Sounds fine. Sure, why not.",
	"I don't think I can do that.",
	"In light of the current political situation in the archipelago, I cannot be involved in commercial dealings. ",
	" is wrangling with everyone and everything, and I'm the only one left with a store.",
	"Oh! Sorry about that. All the best.",
	"Go on, outta here! I ain't got time for small talk!",
	"Like I already told you, I got nothing for you today.",
	"My good sir, either you improve your tone or I shall be inclined to teach you some manners.",
	"Oh... Well, I'm sorry.",
	"Remembering won't do us much good now, will it. I've been forced to reorder the goods. Now goodbye.",
	"Forgive me; it was unavoidable. How about I cover your losses? Will that salve any wounds in our relationship? ",
	"All the best.",
	"Yes! I've been waiting for it for some time. Your task was to deliver the cargo of ",
	" in the amount of ",
	". In return, you'll get ",
	"Exactly right.",
	"Ah, ",
	" - I beg your forgiveness. The thing is, ",
	"I'm in a bit of a pickle, and at present am unable to pay for your services",
	" I have already bought my cargo elsewhere, for a better price",
	". As payment for your charter, I transfer to your keep all the cargo that you have delivered.",
	"Ha! And to think of all the trouble I went to, to protect this damned cargo. At least two hundreds rats, I killed!",
	"Well, since you've backed me into a corner, I guess I'm obliged to agree.",
	"Your hold is missing cargo. According to the terms of the agreement, ",
	" of the cargo is missing.",
	"So it is. How curious. I suppose I'll have to make up the difference, then. Here, don't go too far.",
	"Those blandished rats ruined the crownfaggled cargo. Here, I'll make up the difference. Don't run off; I'll be back. ",
	"Wonderful! And here is your due, Captain ",
	"Great doing business with you.",
	"All right... Looks like ",
	" will just cover the losses I've suffered, due to your tardiness.",
	"Whoa! Keel back, buddy! If that's how it is, maybe I'd best leave your cargo where it is! There's enough of it at sea already!",
	"Here's your ointment. ",
	"Wonderful. Rest assured, my colleagues will know of your honesty. ",
	"I appreciate it! I won't let you down again.",
	"Hum. I hear you have yet to carry out your prior obligations. And yet here you are, asking for more. You really should deliver that ",
	"Oh, yes! You're right!",
	", you're letting me down here! How about you make an effort to solve this problem, huh?",
	"All right. I'll see what I can do about your cargo.",
	"No, I can't. I'm sorry.",
	"Hold on a second! There's not enough merchandise in the hold! You're missing ",
	" of the cargo!",
	"Hmm... Looks like you're right. I guess I'll need to make up the difference.",
	"The ship rats ruined the cargo. Here, I'll buy back the difference, and return.",
	"Yeah, fine. All right... I accept their return.",
	"I appreciate it! I won't let you down again.",
	"At present, I do not require your services.",
	"That's a shame. Well, then let's talk about something else.",
	"Hey, you're the wandering type. Listen, if you come across any mummy powder, do me a favor and bring it here. I've got a major client on the lookout for it.",
	"Um. Sure, okay.",
};
