string DLG_TEXT_BASE [184] = {
	"The alarm's been raised in the city! Everyone's out looking for you! If I were you, I wouldn't hang around here.",
	"All the city guards are hounding the city for you. I'm not dumb enough to hang around talking with you.",
	"Run, pal, before the soldiers make mincemeat out of you...",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Dirty murderer! Out of my house! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Heh, the alarm's no problem for me...",
	"They've got nothing to catch me for.",
	"Shut your trap, ",
	", or I'll rip out your rotten tongue!",
	"Heh, ",
	", and still the same - after pirates! I'll tell you what, buddy. Sit quiet, and you'll live...",
	"Hey, Doctor Blood! ",
	"Great to see you, Peter Blood.",
	"It's good that you've come around here, ",
	". How's Colonel Bishop doing these days?",
	"Alas, I am leaving, ",
	". 'Til we meet again.",
	"Can you tell me, my dear ",
	", where to find Doctor Whacker?",
	"I need to discuss one matter with you.",
	"I'm interested in a man named Raphael Guinness. How can I find him?",
	"For God's sake, Captain, save me! They'll ruin it! My tavern!",
	"Hey, you're the werewolf?",
	"Captain, you promised to go to the werewolf...",
	"I remember.",
	"Well, what do you say, Captain? Have you found him?",
	"I found him. Now, though, is no time to talk, I'll tell you later...",
	"Captain! Happy to see you!",
	"What's happened with that regular?",
	"Welcome, ",
	". Food, drink and entertainment - all for a reasonable price!",
	"We'll see... I am ",
	"Heh, ",
	"Oh, look at the guests! Happy to see you, ",
	"It's good that you've come around here to see me, ",
	". What will be your order today?",
	"Are there any guys on the island who are ready to set sail?",
	"I hope that you can answer a few questions.",
	"Listen, we've got to talk about financial matters.",
	"Is there a free room in this flea basket?",
	"Do you have a free room? I've wanted to stop here for some time.",
	"Alas, I am leaving, ",
	". 'Til we meet again.",
	"Oh, let me convince you, ",
	". I'm called ",
	". I'm the owner of this tavern.",
	"I need a team, ",
	", let's talk...",
	"Listen, we've got to talk about financial matters.",
	"Is there a free room in this flea basket?",
	"Do you have a free room? I've wanted to stop here for some time.",
	"I think I'll come by later.",
	"What do you need sailors for? I don't see your ship in port.",
	"Right... I docked it somewhere else. ",
	"I forgot to go into port...",
	"Usually my tavern's filled with people thirsting to become sailors. Right now, though, it's too late. They only come around in the morning. Maybe you want to rent a room and wait for them?",
	"Fine. Do you have an open room?",
	"I'm not interested in a room at the moment. 'Til we meet again.",
	"And you think that someone will join you when you're our enemy? Be thankful that I don't call the guards.",
	"Thank you.",
	"Sorry, but there's no one here now. Everyone left with a courageous cap'n. ",
	"Oh, what a pity!",
	"I'm all attention.",
	"I'm looking for work. Will you help me?",
	"Tell me the breaking news.",
	"What's new in these parts?",
	"How's life on land?",
	"I'm on other business.",
	"I'm working under orders from the Governor. Have you noticed anything suspicious in the city recently?",
	"Nothing, thank you. Goodbye.",
	"I don't want to help you. You walk under the flag of ",
	"Though I'm but a simple tavern owner, cooperation with ",
	" is out of the question.",
	"Hmm... Well, that's your right. Okay, bye.",
	"Well, you know...",
	"Work, you say? I can suggest the local merchant. He often needs captains to transport cargo.   \n You can also see if there's a buyer in the tavern. They often need guards for their stands.   \n If you aren't averse to taking passengers, you can ask around in the streets. Maybe someone needs to get to another colony?   \n Only other thing I can suggest is signing up to serve the Governor. He'll definitely give you regular missions.",
	"You know, there are plenty of people in my tavern who need to get to other islands. Thing is, you have a rather... murky reputation. You won't find an idiot that will go on your ship as a passenger.",
	"As a rule, I'm filled with merchants that need an escort. But you're up to your elbows in blood! You seriously think that someone will agree to sail with you?",
	"Oho! The rumors about me are always one step ahead! Heh!",
	"You're right. Everyone's scared of me! Ha, ha!",
	"Often merchants ask to have their ships escorted to an assigned point. Though some prefer to sail with a smaller squadron. You know how it is.",
	"That's right. I forgot about that. Okay; I'll come back later, when the amount of my ships lowers. Ha, ha!",
	"You got me just in time! A merchant was looking for just the right company... Oh, there he is. See the guy who just walked into the tavern? Talk to him.",
	"What do you think? Is he worth dealing with?",
	"Who is he? Do you think I should deal with him?",
	"Usually, I'm filled with merchants who need assistance. No one's here now, though. Maybe you'll get lucky some other day.",
	"All right, there's no answer to no.",
	"Heh. Bad luck, then... All right, see ya 'round.",
	"One guy wanted to find a ship to go somewhere. And there he is!",
	"What do you think? Can we take that person on board?",
	"Who is he? Do you think I should transport him?",
	"Usually I'm drowning in passengers. At the moment, though, as misfortune would have it... I'm plumb dry. Sorry...",
	"Well, what can a man do. Don't worry about it...",
	"Ha. Bad luck, then... All right, see ya 'round.",
	"Look, we've already talked about work. Try mixing it up a bit, will you? ",
	"I've got other things to think about than work...",
	"Dammit, why do you think I keep asking you? I need work!",
	"Thanks for your help. Now let's talk about something else.",
	"I've said my say, and I've nothing to add!",
	"All right, all right, I get it.",
	"Of course, it's totally legit.",
	"If you work out a price that both parties find equitable, then why not?",
	"Thanks. I'll go talk to him right away.",
	"Of course, as passengers go, he's a total straight-arrow.",
	"If you work out a price that both parties find equitable, then why not?",
	"Thanks. I'll go right over and talk with him.",
	"The room is currently taken, ",
	". I'm afraid I cannot help you.",
	"Ah, that's a shame. Downright pity, even...",
	"Now, you've already paid two weeks' advance; I can't accept any more from you. The room is yours! Go on, make yourself at home.",
	"Well, all right. Thanks aplenty, friend.",
	"You want to rent a room? You got it! Just one hundred coins, and I'll whisk you right over. ",
	"Well, all right. Thanks aplenty, friend.",
	"Aha. Well. Perhaps I'll come back later, then...",
	"The room is yours. Go on and make yourself at home.",
	"All right then. Ample be the thankin', friend.",
	"So how long are you planning on staying?",
	"Just 'til morning.",
	"Until this evening.",
	"Until tomorrow morning.",
	"That will be five piasters.",
	"Sure. Here. ",
	"What do you think you're renting, the royal suite? Gosh, if that's what you're asking, I'd rather dust off a chair in the lobby...",
	"Alas, my idea of luxury is more than my wallet can handle. I guess those chairs in the lobby looked comfy enough...",
	"That's lovely, but let's talk about something else.",
	"That will be ten piasters.",
	"Deal. Here.",
	"What do you think you're renting, the royal suite? Gosh, if that's what you're asking, I'd rather dust off a chair in the lobby...",
	"Alas, my idea of luxury is more than my wallet can handle. I guess those chairs in the lobby looked comfy enough...",
	"Yeah, great. How about we change the subject.",
	"That will be five piasters.",
	"Deal. Here's the money.",
	"What do you think you're renting, the royal suite? Gosh, if that's what you're asking, I'd rather dust off a chair in the lobby...",
	"Alas, my idea of luxury is more than my wallet can handle. I guess those chairs in the lobby looked comfy enough...",
	"Not now. Here, let's change the subject. ",
	"Get out my lobby, ya bum! What does this look like, a haven for freeloading rumps?",
	"All right, all right. I'm leaving.",
	"Get out my lobby, ya bum! What does this look like, a haven for freeloading rumps?",
	"Okay, okay. This place isn't my style anyway.",
	"Gentlemen! I ask you to stop at once this outrageous behavior! This is my tavern, and I will call the guards!",
	"All right, all right. I was just leaving.",
	"Hmm, let me think... Come to think of it, there is this one fella who strikes me kind of odd. You look at him, he seems normal enough. But he keeps hanging around here, sometimes turns up in the city, always asking strange questions. Finally yesterday I told him to get lost, so I don't reckon you'll find him here. You want him, you'll want to poke around the city.",
	"We've already talked about that today. I've got nothing more to add.",
	"Again with the questions? Look, I already told you everything.",
	"What are you, a broken record?!",
	"Thanks, friend. I guess I'll go look for the creep.",
	"Hmm. Sorry...",
	"Well, you know...",
	"Sorry, friend.",
	"Suspicious? No, not off the top of my head....",
	"We've already gone over that. I've said my peace. ",
	"Again with the inquisition. Look, I already told you everything.",
	"What are you, a question machine? Swiss, are you? The marvels of modern invention...",
	"Well, thanks anyway.",
	"Hmm. Sorry...",
	"Well, you know...",
	"Sorry, buddy.",
	"Up the stairs. Not that you heard it from me.",
	"Many thanks.",
	"What have you got for me, my dear Doctor?",
	"Nothing special... I wouldn't mind obtaining some cutlasses and a few guns, just in case. My dearest friend, you could swing them for me, could you not? Elsewise, point out an individual who could? As you know, mainstream routes of commerce are a bit out of my league...",
	"Er... Well, yes. Of course.",
	"Out of your league how, exactly? You mean, you would have trouble getting your stuff?",
	"Did I not mention the reward? I am of course willing to pay for the information, and pay well. Shall we say, one thousand piasters? And dear sir, surely you remember how I tended your daughter, how I spared neither time nor sweat?",
	"There's nothing I can do for you, Doctor.",
	"All the best to you.",
	"Why Doctor Blood, of course I've got what you need. In fact, Mr. Griffin, whose bone you so recently tended, is an old weapons dealer by trade. His house is by Governor Steed's estate. Go see him; I'm plumb certain he won't let you down.",
	"Well, all the best.",
	"Yeah, I remember him. Actually... No, maybe that wasn't him... No, don't reckon it was...",
	"What would an even five hundred do for your memory?",
	"So is it him or not?",
	"Why... Yes, of course! I mean, of course it's him! He came by just recently, in fact. Said something about buying a ship... I'm not really sure what ship or from whom.",
	"What are you sure about, then? Seems to me that five hundred piasters ought to dislodge a few more details than 'Oh yeah, he came by!'",
	"No, I'm afraid it's definitely not him. I got mixed up. It happens.",
	"Of all the aggravating...",
	"If you hurry, you should find him at the shipyard.",
	"You have my thanks.",
	"No, no! The guest is upstairs! They say he's a real werewolf!   \nOh brave captain, I beg you! Do something! If those... people, from the streets... If they burst in here, I'm... I daren't imagine what might happen!",
	"I don't know who's more scared - you or the schmucks outside. All right, I'll go have a chat with your rabid guest.",
	"Thank God I'm rid of him! I had no choice but to open the door. Those were my paying clients, out there! A few broken bottles of rum is a small price to pay...",
	"I'm asking about the guest. What happened to him?",
	"You mean the werewolf? They burned him, what do you think? Didn't you see the smoke wafting around? It's carried all the way from the church! The damned things sure can burn...",
	"Hmm... You townsfolk sure got you some itchy fingers. Don't you have any entertainment around here?",
};
