string DLG_TEXT_BASE [72] = {
	"Ooh, damn! I know who you are! Only a complete idiot would board as your passenger. Goodbye!",
	"Aah, I know who you are! What do you take me for, an idiot? I'm not stepping aboard. ",
	"Heh. Scaredy-pants...",
	"Everyone's so scared these days!",
	"! I'm ",
	". I hear you're taking on passengers?",
	"Maybe. Depends on what's in it for me.",
	"I need someone to get me to the tavern in ",
	" which is in ",
	", within ",
	". For that, I can pay you ",
	". What do you say?",
	"I agree.",
	"I don't think I'm interested.",
	" which is in ",
	"Thank you. You've done what I asked. I am at the location. Here is your reward.",
	"I'm grateful.",
	"Some person named ",
	" says that a person can trust Captain ",
	", because he got him without any problems to ",
	"A passenger named ",
	" says that Captain ",
	" can be trusted. He got him to ",
	", safe and sound.",
	"I hear, Captain, that you keep your word to your passengers. A profiteer named ",
	" speaks well of you.",
	"Time's up, Captain. When will I get to ",
	"Captain, how long can you wander in God-knows-where?! When will we get to ",
	"Listen, Captain, it's imperative that I get to ",
	", and I want to get a clear and concise answer on when this will happen!",
	"Captain, this is the second time I bring up your responsibilities. When will we arrive at ",
	"Captain, this is the second time I'm forced to ask as to my arrival. When will we finally see the shores of ",
	"Captain, this is the third time I'm asking you about  when we will arrive at ",
	"Captain, we've lost God-knows how much time! When will you get me to ",
	"Listen, Captain, this crosses every line...",
	"Please forgive me. Stuff... got in the way. In seven days, you'll definitely be at the site.",
	"I quite apologize, ",
	". I've simply had no time to carry out my obligations. But don't fuss yourself. We'll meet our destination inside a week.",
	"I must apologize once again... We'll be at our destination in a week.",
	"Again, please forgive me. We'll be at our destination in a week.",
	"Yet again, I must beg your forgiveness. We'll be at our destination in a week.",
	"Yes, I offer my sincerest apologies. We'll be there in a week, I promise...",
	"I understand, ",
	", but I must ask you for just a bit more patience. Seven days from now you will be where you please!",
	"Er... oh, right. Passenger... Actually, I forgot all about you. Anyway, I think you'd be safer down in the hold. Safer, and quieter. ",
	"Well, would you look at that - strangers, on my ship! Well, I suppose introductions to my hold are in order.",
	"You again? Well, ain't that something. Here, I guess I ought to organize a trip for you. Where, you ask? Yes, that's right! Down into the hold.",
	"What, you again? What is this, the third time? Listen, bud - in all seriousness, quit roaming about my ship and get your ass down in the hold.",
	"You complaining again? I think that someone is at gateway to Tempertown... All right, I have had enough of this foot stomping... Welcome to my hold, ",
	"Yes, fine. But don't expect your full fee.",
	"Hmm... All right, I'll believe you... But mind, I'm docking your fee!",
	"Well, I suppose I have no choice in the matter, do I. Bear in mind, however, that I am cutting your fee...",
	"Deal. ",
	"Well, all right...",
	"Okay, I guess.",
	"I want to believe that this time you will honor our agreement.",
	"I hope that this is the last we shall speak on this... rather unpleasant matter.",
	"Naturally.",
	"What hold? I don't understand!",
	"What's not to understand? You are now my prisoner. Now go on, get into the hold!",
	"Aw, I'm just kidding... We'll reach your city in one week flat.",
	"You'll pay for that yet, you scoundrel!",
	"Yeah, yeah. I've heard it all before. But for some reason they all end up paying me!",
	"You ever hear of a Captain ",
	"? Seems he agreed to transport a passenger... what was his name? Something like ",
	". Thing is, the seadog went back on his deal. Not only that, he actually imprisoned the poor chap! Just goes to show Can't trust anyone these days...",
	"Bah, what's the world coming to?! Captain ",
	" nabbed a poor fellow, name of ",
	" - even though he was entrusted with the man's safety!",
	"Captain, rumors have it that you're quite the bastard. Ever hear of a poor chap named ",
	"? Yeah, you held him prisoner on your ship, didn't you? And that's after you promised to transport him to ",
	". Not the noblest of deeds, I'm sure you'll agree.",
};
