string DLG_TEXT_BASE [26] = {
	"Ooh, damn! I know who you are! Only far-gone cretin would hire you to escort his ship. Farewell!",
	"Aah, I know who you are! Hire you as an escort? What you're looking for is an idiot...",
	"Heh. Scaredy-pants...",
	"Everyone's so scared these days!",
	"! I am a merchant, name of ",
	". I hear you're looking for work?",
	"Something like that. And you, I gather, are looking for a captain who can escort your vessel to a specified location?",
	"Absolutely correct. What's more, I think that you're just what I need in an escort. What do you say?",
	"I'll say that you should toss me a figure and we'll work out an agreement.",
	"I need someone to escort me to ",
	" which is in ",
	", within ",
	". For that, I can pay you ",
	". What do you say?",
	"Okay, fine by me.",
	"I don't think I'm interested.",
	"Wow, thank you! With you as my escort, I've never felt safer! Here, take this.",
	"Much obliged.",
	"A certain merchant captain, name of ",
	", says ",
	" is a good man to escort merchant vessels.",
	"You know that merchant, ",
	"? He's been saying a lot of good stuff about Captain ",
	". Seems the man defended his ship like a champion, on their way to ",
	"I hear that you're a solid man for escorting merchant vessels. A certain merchant I know by the name of ",
	" speaks well of you.",
};
