string DLG_TEXT_BASE [14] = {
	"Get out of here! Don't get in the way of our fun!",
	"Get lost, pal! Keep out of our business. We just want a little fun. No harm in that!",
	"Be on your way, stranger! She'll be thankful later. And you'll be healthier!",
	"No, I'm going to have to get involved.",
	"I won't allow this crime to take place!",
	"Stop this nonsense!",
	"I'll go. Sorry to interrupt.",
	"Sorry to bother you. Goodbye and good luck.",
	"I get you. Take care now!",
	"Then suit yourself! All right, boys. Shall we tickle his ribs with our blades?",
	"Now's a good time to say your prayers!",
	"What, you want in? Smeg off! She's barely enough for us!",
	"Oh, in that case I shan't bother you.",
	"I will not allow this heinous act to take place!",
};
