string DLG_TEXT_BASE [32] = {
	"Oooh, I think that's the villain what's got up the alarm up at ",
	"! Grab him!",
	"Heh, would you look at that! Some ",
	" somehow wound up in conflict with ",
	"! Grab the scoundrel!",
	"Halt, enemy agent! He is here, near ",
	"! Grab him!",
	"Look at that, ",
	" he's strolling a little too close to ",
	"! Grab him immediately!",
	"Try it! It is just you and me, and your soldier dogs...",
	"Heh. Help ain't coming here from no one.",
	"I have the honor of introducing myself! I am the head of the patrol of ",
	". We're looking for an escaped prisoner.",
	"Hello. I'm the head of this patrol. We're looking for someone who escaped from ",
	", a slave.",
	"Copious greetings, ",
	". My unit patrols the territories nigh ",
	"That's swell. What do you want of me, then?",
	"Okay. Do you need something, ",
	"Wonderful. What can do for you?",
	"Have you noticed anything suspicious in the area?",
	"Have you encountered anyone that might qualify as  suspicious, ",
	"No, can't say that I have.",
	"That's a negative, officer. All is nice and calm.",
	"Well, then I won't keep you. Farewell, ",
	"I see. In that case, goodbye.",
	"Best of luck to you.",
	"Please don't distract us from our service.",
	"I shall ask you to not bother us!",
	"Oh... It's you again. Look, just be on your way, and leave us alone.",
	"Er. Yeah, okay.",
};
