string DLG_TEXT_BASE [286] = {
	"My husband forbids me to talk to strangers!",
	"I've got nothing to discuss with you.",
	"And I don't need it",
	"Better yet, why don't you tell me some of the stories going around this area?",
	"Better yet, why don't you tell me what's new in these parts?",
	"Better yet, why don't you tell me about life on land?",
	"Hello, stranger. Allow me to give you a humble piece of advice.",
	"I'll listen to it with pleasure.",
	"I don't need your advice.",
	"Greetings, traveler. Where are you rushing to?",
	"Oh, here and there. Things to see, people to do.",
	"None of your business.",
	"Good day, wanderer. How are things?",
	"Not bad.",
	"I don't have time to talk with you.",
	"Hello. I haven't seen you're here before. You're not a local?",
	"Nah, just passing by.",
	"I don't have time to talk with you.",
	"Greetings, foreigner. Happy to see you in our parts.",
	"Hello.",
	"Sorry, can't talk now.",
	"Hello, sailor. Want to hear a good piece of advice?",
	"Hello. Come on, lay it out.",
	"I have no desire to waste my time.",
	"Hello, foreigner. I've got a few goods that might interest you.",
	"Let's bargain.",
	"I don't have time to talk with you.",
	"Good day, wanderer. You look tired. For only 200 coins I can heal your wounds and brush away your fatigue.",
	"All right, give it here.",
	"I've never believed in miracle cures.",
	"Hello, sailor. I've gotten myself into a difficult position. Will you help me?",
	"Hmm. You got a good reason why I should?",
	"We all got our problems. Solve 'em yourself.",
	"Sir, will you help a poor sufferer? Ease his lot with a few coins?",
	"Of course. The church teaches us to ease the sorrow of others.",
	"G'wan, ya bum! Don't you dare get close to me.",
	"Sir, don't leave a poor man in need! Give a coin so that I don't die of hunger.",
	"Yeah, of course. How about 200 coins?",
	"G'wan, ya bum! Don't you dare get close to me.",
	"Hello, sailor. I see you're a tough young'n. You probably battle a lot?",
	"Yes, of course.",
	"That's my business. Goodbye.",
	"Hello. One doesn't often see such a notable person. I presume you are a captain?",
	"Sure. How can I be of service?",
	"You know, I'm in a hurry. Farewell.",
	"Good day. Are you just out on a stroll, or are you going somewhere?",
	"Actually, sure. I'd be happy to talk with you.",
	"No, I'm busy.",
	"Good day. Are you just out on a stroll, or are you going somewhere?",
	"Actually, sure. I'd be happy to talk with you.",
	"No, I'm busy.",
	"Good day. Are you just out on a stroll, or are you going somewhere?",
	"Actually, sure. I'd be happy to talk with you.",
	"No, I'm busy.",
	"Hello, foreigner. I've got a few goods that might interest you.",
	"Let's bargain.",
	"I don't have time to talk with you.",
	"Hello, sailor. Want to hear a good piece of advice?",
	"Hello. Come on, lay it out.",
	"I have no desire to waste my time.",
	"Hello, stranger. Allow me to give you a humble piece of advice.",
	"I'll listen, with pleasure.",
	"I don't need your advice.",
	"Greetings, traveler. Where are you rushing to?",
	"Oh, here and there. Things to see, people to do.",
	"None of your business.",
	"Listen, stranger, don't come to the jungle at night. Bandits often wander there, and attack without warning.",
	"Thanks for the tip.",
	"If you've got any problems with the law, then it's better not to blunder into a patrol. There are a lot of soldiers here. It'd be better to sail off the island.",
	"Interesting.",
	"I'm not interested in tips like that. Farewell.",
	"Then be ready. The next time you sail here, you'll receive a cold welcome.",
	"All right, I'll keep that in mind. Farewell.",
	"I know a surefire way to restore your health, if something's not in order. You can buy a bottle of it from a merchant in the city.",
	"And besides that?",
	"I have no time to talk.",
	"Well. If you rest at the tavern, that's always a good way to get back some of your vital energy. ",
	"Thank you.",
	"You know, if I need breaking news or any other information, I always go to the tavern owner. He can answer almost any question.",
	"A great piece of advice. I'll use it.",
	"I see you're a military man. And that you have to fight. Remember to take more officers with you. Sometimes, it's impossible to survive without their help.",
	"Yes, of course.",
	"I see by your posture that you're a captain, no less. If you need a ship, buy it at our wharf. If you don't see the ship you want, come back in a few days. Maybe it'll be available for sale.",
	"Not bad advice. Thank you.",
	"Sometimes in these parts, you'll see men who've seen a lot in the world. You can ask them for help, and they can increase your skills in this or that field. I know for sure, their knowledge is priceless.",
	"Not bad advice. Thank you.",
	"Wait, aren't you a plantation slave?",
	"Alas, I'm leaving already, ",
	". 'Til we meet again.",
	"If you give me 200 coins, I'll tell everybody what a wonderful person you are. Ignore my poverty. I  have a lot of friends and everyone will aways be happy to have you here.",
	"Throw money around just so some ragamuffin can tell tall tales about me? I don't think so.",
	"Yeah? All right, no sense denying 200 coins to someone who really needs it. ",
	"Thank you for what you've done. I'll thank you how I can. Drink this potion. It'll restore your life strength.",
	"Thank you too.",
	"Thank you. I have nothing with which to repay you, except... Take this little thing. Perhaps you'll be able to extract some usefulness out of it.",
	"I'll gladly take your gift.",
	"Thank you, kind man.",
	"No need for gratitude. Goodbye.",
	"Captain, take me aboard your ship. I've long dreamed of a sea journey and brutal battles.",
	"No, I don't need any greenhorns.",
	"Pay me, and I'll show you a pair of moves to beat any in hand-to-hand combat. Or do you want to know about defensive moves?",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Show me your attacks.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Show me how you defend.",
	"Thank you. I don't need anything.",
	"I was a sailor too, long ago. A famous explorer. I can tell you quite a few things about how to manage your team on the ship.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Yes, I would like to know more about that.",
	"Thank you. I don't need anything.",
	"I'm a sailor, too. A navigator. For a small fee, I'll tell you all my secrets to better control a ship.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Sure. I would like to know your secrets of maneuvering.",
	"Thank you. I don't need anything.",
	"I'm the cannoneer on a British military ship.  I'll gladly tell you how to correctly calculate the ball trajectory, and how to hit the target with your cannon.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Tell me. I'll pay whatever you ask.",
	"Thank you. I don't need anything.",
	"I'm the cannoneer on a British military ship. I can let you in on my method to quickly reload cannons.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Tell me. I'll pay whatever you ask.",
	"Thank you. I don't need anything.",
	"I'm an officer on a British military ship. I can tell you a few stories about the art of boarding.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Tell me. I'll pay whatever you ask.",
	"Thank you. I don't need anything.",
	"I work on the wharf, and I'm a great expert in building and repairing ships. If you pay me, I can teach your team how to repair your ship quickly.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Tell me. I'll pay whatever you ask.",
	"Thank you. I don't need anything.",
	"I'm a merchant. I can teach you my tricks of the trade, that will increase the profit of your commercial enterprises.",
	"I don't need your advice. I already know everything, and can teach you a lot myself.",
	"Tell me. I'll pay whatever you ask.",
	"Thank you. I don't need anything.",
	"Well, then, pal. Ready to pay me ",
	"I think I don't have enough money.",
	"Yes, I'll pay. Tell me.",
	"No, that's a bit much.",
	"Well, then, pal. Ready to pay me ",
	" for the secrets of hand-to-hand combat?",
	"I think I don't have enough money.",
	"Yes, I'll pay. Tell me.",
	"No, that's a bit much.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for some secret defensive techniques?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for a lesson on controlling the mind of man?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for advice on running a vessel?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for some expert advice on cannoneering?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for some advice on reloading weapons?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for boarding advice?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for advice on ship repair?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Okay, buddy. Ready to fork over ",
	" for some business advice?",
	"I don't think I've got the money...",
	"Sure, I'll pay. Tell me.",
	"Nah, that's a bit rich for me.",
	"Thanks for your help, my good man.",
	"You're quite welcome.",
	"Well? Still in the market for elixirs?",
	"Sure. Better with than without.",
	"No, sorry to bother you.",
	"Well, wanna trade?",
	"Yes, I had something in mind...",
	"No, sorry to bother you.",
	"What do you need? I thought that we covered everything.",
	"Nothing, really.",
	"Awaiting your orders, Captain.",
	"Just hang tight. Nothing for now.",
	"My husband forbids me to talk to strangers!",
	"I've got nothing to discuss with you.",
	"That's fine. I don't need anything",
	"Better yet, why don't you tell me some of the stories going around this area?",
	"Better yet, why don't you tell me what's new in these parts?",
	"Better yet, why don't you tell me about the life of a landlubber? Arr. Avast.",
	"Want some advice?",
	"Sure. Always keen to broaden my perspective.",
	"No, sorry to bother you.",
	"Heed my words, stranger. You lead a righteous lifestyle, people will be happy to see you. Always. You count on it.",
	"Yes. Well. Thanks for the tip.",
	"You got any problems with the law, no good hangin' 'round here. Rife wi' soldiers, 'ere. Best plan is settin' sail, first chance ye get.",
	"Interesting.",
	"That's... not really what I was looking for. So long. ",
	"If something's ailin' you, I know a surefire way to put everything in order. It comes in a bottle, and you can buy it from a merchant in the city.",
	"And besides that?",
	"I have no time to talk.",
	"Y'know, if ever I need the latest news... or near anything else, really... I always go to the barkeep. I reckon he can answer most of your questions.",
	"Yeah. That's good advice, actually. I'll go do that. ",
	"I see you're a military man. And if no stranger to combat, by the looks of it. Remember to always bring officers with you, the more the better. Survival in numbers, and all.",
	"Yes, of course.",
	"I see by your posture that you're a captain, no less. If you need a ship, buy it at our wharf. If you don't see the ship you want, come back in a few days. We get new stock all the time.",
	"Not bad advice. Thank you.",
	"'Round here you'll meet your share of men who've seen their share of life. If you go to them, they can teach you what they know. And trust me, there's no better way to learn than from a master.",
	"Not bad advice. Thank you.",
	"You really are a sight",
	"",
	" for sore eyes. What can I do you for?",
	"Why, Captain, aren't you a talkative fellow. I suppose I can keep you company... over a bottle of rum.",
	"Yes, ",
	"Well, what else do you want?",
	"I see, my dear ",
	", that gum-flapping is your sport of choice? ",
	"Enough with the questions, Captain. Why don't we share a drink, instead?",
	"What would you like to know, ",
	"I'm all ears, Captain.",
	"Let's wrap this up, Captain. I need to leave soon.",
	"Always happy",
	"",
	" to take such great company, ",
	". Please, go ahead.",
	"Yes, ",
	"Why, Captain, aren't you a talkative fellow. I suppose I could do with a bit of company...",
	"What tales have been frolicking on the tongues of the locals? ",
	"What's new in these parts?",
	"How's life on dry land?",
	"You misheard. I'm going.",
	"Nah, I'm just out for a walk.",
	"All right, never mind then. Good luck!",
	"Just stretching my legs. You know how it is. Have a good one.",
	"Sir, as a citizen of this town, I must kindly ask that you sheathe your blade.",
	"Hey mister, how's about you put away your sword and stop scaring the locals? Like me, f'instance?",
	"Um. Sure, okay.",
	"All right.",
	"Whatever you say.",
	"Whoa, buddy. You in for a pillage, or you just happy to see me? Might want to take your hand off your blade, in public...",
	"Me, I get twitchy when I see men walking around with their blades unsheathed...",
	"Point taken.",
	"I'll put it away at once!",
};
