string DLG_TEXT_BASE [65] = {
	"Did you hear that the famed local robber ",
	" has another victim? Some kind of captain. They say this cap was a coward, and bought his way out. They say that he doled out all of ",
	"! Hee hee... ",
	"You know, Captain ",
	" forked out a whole ",
	", to buy his way out from a bandit, name of ",
	", oh, so you're that captain! Well, what can I say. You weren't lucky! Haw haw haw!",
	"Did you hear that some local robbers attacked Captain ",
	"? And he was robbed for a whopping ",
	"Did you hear that some captain totally took down that robber, name of ",
	". He wanted to rob 'im, but ended up soiling himself instead! Hur hur!",
	"You know, Captain ",
	" just took down a band of ruffians, called themselves ",
	", ah, so you're that captain! Splendid work...",
	"Did your hear that a local bandit, name of ",
	", tried to rob Captain ",
	"? So they tried to rob him, but this captain was a tough nut to crack. The bandits ended up running every which way they could!",
	"Stop! Drop your weapons! Drop your cash or lose your head!",
	"Yo, wanderer! Slow down! I wanna see your wallet!",
	"Stop, villain! You wanna pass this way, you pay up!",
	"What are you saying?",
	"What's the problem?",
	"What do you have in mind?",
	"Aha! Robbers! Crime must be stopped at the root. To battle!",
	"I can't stand arrogant bastards, especially when they're unwashed. Prepare to die!",
	"For such arrogance, I'll cut the heart out of your chest!",
	"Oh, he doesn't get it! Dump all the gold you got! Then maybe, I'll let you go!",
	"Didn't your hear? This is a toll road. The toll's pretty strict too. Ya don't part with your gold, you'll part with your head!",
	"I'll explain for flat-headed sailors: put down all the money that you have! I do love pounds and doubloons!",
	"Curses! Villain! I only have ",
	" piasters with me.",
	"I'm not giving up my money without a fight.",
	"Hey. Don't, worry pal! I'm joking! Be on your way!",
	"All right, I changed my mind. No one will rob you today. Now go on, get out of here.",
	"You're one brave fella! See, I like that. And that's why I'm letting you go.",
	"Well, then! Until we meet again!",
	"Hrm... You should really think about a new line of work. Anyway, take care.",
	"I'm happy you've made the wise decision. Good luck!",
	"It's too late. Prepare to meet your maker!",
	"What are you, a pervert? Well, too late now; no way I can let you live!",
	"I'm not going anywhere until I'm finished here.",
	"You could have just left in peace... But now you will leave in pieces!",
	"You'll regret that, scoundrel! Die now! Aha!",
	"Oh yeah?! I'll tear you to pieces! Then cut out your liver and roast it, on a pile of red onions! With gravy!",
	"I'd like to see you try!",
	"All right! Hand 'em over, and get lost. Move it!",
	"Not a hell of a lot, but better than nothing. Always a pleasure to deal with sensible people, for a change. You may go now.",
	"In exchange for your gold, let me offer a piece of advice. If you can't stand the heat, stay out of the jungle! Hwa-ho! Go back to port, find a table in a local tavern, and sip your rum in peace.",
	"Drat you all to heck! Er... that is... Argh! Hate you!",
	"I believe you're trying to make a fool out of me. You want a laugh, I'm sure my blade can give you a little tickle! It might even shake a few prizes off your carcass.",
	"Blast!",
	"You again? Boy, you best put some gunpowder on your heels, 'fore I change my mind about letting you go.",
	"What, so generous? All your gold, for us? Really? Why, how utterly refreshing! Hoo-ha!",
	"Listen, bud, you're beginning to grate on me. Get outta my sight, 'fore I slit your throat and throw you to the sharks. Okay?",
	"Yes, yes. I was just leaving.",
	"I decided to come back and give you what for!",
	"What, aren't you gone yet?",
	"Listen, y' whippersnapper, you just get on with your business and leave me to mine. ¿Se entiende?",
	"I think you best leave, friend. Or are you really that eager to part with your cash?",
	"Yes, yes. I was just leaving.",
	"I've decided to punish you for your evil deeds!",
	"Leave me alone! Get away! I want to live!",
	"He's a maniac! Help! Don't kill me!",
	"Have mercy on me! I'm just a humble bandit! I'm too young to die!",
	"You know, some days you really shouldn't get out of bed. This was one of them. ",
};
