string DLG_TEXT_BASE [137] = {
	"Hey, uh, Captain... You know, half the garrison is hunting you. Now is obviously not the time to join your team!",
	"Looking for help to fight your way back to the ship? No, um. Maybe another time, Cap...",
	"Well, you know...",
	"I wasn't planning on hiring you anyway.",
	"Need an officer, Captain?",
	"Officer? And what are you good for?",
	"No, I've got a full crew.",
	"Today we'll once again set out to sea!",
	"Yes... I'd be happy to.",
	"Let me finish my drink, Captain, and I'll head onboard. Don't worry; I'll make it before you set off.",
	"Fine. If you're late, I'll make you swab the deck!",
	"What do you want, Captain?",
	"I'm ready to speak with you, Captain.",
	"Listen to my order!",
	"You're fired",
	"",
	". I'll get by without your services!",
	"Give me a full report, ",
	"I'm making you the deputy of this city!",
	"Nothing. You're free to go.",
	"Captain, everyone else is living like a human being - falling in love, getting married, sitting home. Meanwhile, we bounce around the sea as if wound up. I want to taste a new life for a bit. Let me go be a human being for a while!",
	"Captain, cruising the seas with you ain't bad, course it ain't... but a man's got to think of himself  too. Buy a house, get him some kids. And you need time to do that. Let me go, please. I want to live like a normal human being.",
	"Sorry, Captain, but I'm kind off tired of wandering the seas all the time. The earth is mysteriously pulling me back. You'll do fine without me, right? No hard feelings?",
	"I'd lose my whole team that way. Everyone would run off. But all right, go on. I'm not going to hold you against your will.",
	"The ship isn't a dungeon and I'm no jailer. Go on, make your history.",
	"You don't love me. I see, I see. All right, go on, but remember that I'm upset.",
	"Sorry, friend, but no. I'm not letting you go. It's out of the question.",
	"You can want what you like. In case you've forgotten, I bought you and took you on. So you can forget about your personal life.",
	"No playing on the side. We've got tough battles ahead and I need every officer at the ready.",
	"But I'm no slave. I'm working for money. Even though there's a lot to keep me here, it's in my rights to choose when to get out!",
	"You're right about that. How about a raise?",
	"I'd lose my whole team that way. Everyone would run off. But all right, go on. I'm not going to hold you against your will.",
	"The ship isn't a dungeon and I'm no jailer. Go on, make your history.",
	"You don't love me. I see, I see. All right, go on, but remember that I'm upset.",
	"Fine, ",
	" gold in my hands right now would suit me fine.",
	"We're in agreement.",
	"Oh, right! How much?! For that money, I could hire two skilled officers!",
	"Eh... Now I'll finally get to start a free life...",
	"Well, good luck on you.",
	"Captain, my patience has burst! We've got totally different concepts of good living. I'm leaving you.",
	"Captain, I thought I was serving a real corsair. But us? What are we doing? I don't want to waste my time, so I'm leaving.",
	"What?! Then you... well, you can just go to hell then!",
	"Yes I'm the best ",
	" in these waters. ",
	"I'm prepared to serve you and sign up for duty.",
	"Well, they say I'm not a bad ",
	"Take me aboard you vessel, Captain. You'll be glad you did.",
	"How much do you want?",
	"And what kind of specialist are you?",
	"Alas, I already have a ",
	"Hey, uh, Captain... You know, half the garrison is hunting you. Now is obviously not the time to join your team!",
	"Offering to fight your way back to the ship? No, um. Maybe another time, Cap...",
	"Well, you know...",
	"I wasn't planning on hiring you anyway.",
	"Have you changed you mind, Captain? Did you decide that a new ",
	" wouldn't get in your way?",
	"I guess. How much do you want?",
	"How will you be, in action?",
	"I've got a full crew. I'm all happy here.",
	"I think we can both agree on ",
	" piasters.",
	"Don't you think you want too much?",
	"I agree. Consider yourself part of the team.",
	"You're not worth that kind of money. Goodbye.",
	"Fine... I'm ready to agree on ",
	" piasters. How's that?",
	"That's better. You're in.",
	"I still think that's a bit much. Goodbye.",
	"Alas, Captain, I am worth exactly the price I ask. If that's not in your budget, then be so kind as to look elsewhere. ",
	"Wait... All right, I'll take you on.",
	"That's exactly what I'll do. See ya.",
	"Thank you, Captain. You will not regret this investment.",
	"I sure hope not.",
	"Wait a second. You don't have enough money! Sorry, Captain. I work for cash, not promises.",
	"Argh, dammit!",
	"Let me finish my grog, Captain, and I'll strut right aboard. Don't worry; I'll be there before you heave off.",
	"Fine. If you're late, I'll make you swab the deck!",
	"The rats are most active in a voyage where ",
	"% of the cargo capacity is filled. For ",
	" sailors (not including slaves) you need ",
	" rations per day.",
	"Thank you.",
	"And what will your orders be?",
	"Stay here!",
	"Follow me, and don't fall behind!",
	"I want you to keep your distance from the target.",
	"Exactly how far, Captain? Say, how many feet? Less than sixty, I hope. ",
	"Why, Captain! What nerve!",
	"Pardon me. My mistake...",
	"Then I'll just stand here, like a statue .Is that it, Captain?",
	"Yeah, that's just right. Stay like that.",
	"Look, isn't that a bit far? Shouldn't I be within, say, sixty feet?",
	"All right, then sixty it is.",
	"Understood. I'll keep to it, then. ",
	"Yeah, sure. Okay.",
	"That's well within your privilege, but please drop me at a city first. Any city will do.",
	"Then that's what we shall do. But for the moment, you're still employed here.",
	"Whatever you say, Captain. But know this. If you let me go now, you'll never see me under you again. So make sure you know what you want...",
	"Hmm... Never mind, then. I guess I still ",
	"need you.",
	"require your services.",
	"Already done. Now get outta here - the farther the better.",
	"Captain, I did warn you that I shall not return to your ship. I have my ",
	"feminine ",
	"pride.",
	"Yeah well, you're not ",
	"needed",
	"needed",
	"Yes, Captain.",
	"At ease.",
	"Yes, Captain.",
	"At ease.",
	"It will be an honor!",
	"Preserve the city's order and prosperity. I will return occasionally, to pick up what taxes you have collected.",
	"Wait, hold on. Changed my mind.",
	"What are your orders? Your last visit was ",
	" ago.",
	"What are your orders?",
	"So how much tax money have you ",
	"collected",
	"raked in",
	" so far?",
	"You are ",
	"needed",
	"needed",
	" on my ship. I'm relieving you of your post here in the city.",
	"All the best.",
	"My skills allow me to collect ",
	" per day. Over ",
	" I collected ",
	" ",
	" ",
	"Whatever tax money there is, I want to take it.",
	"Thanks for your good service!",
	"That's great! In truth, the sea will always be my home.",
	"That's swell.",
};
