string DLG_TEXT_BASE [22] = {
	"Help! Help! These people are following me! Save me!",
	"Aah! Help me, stranger! Save me from these villains!",
	"Be kind! Save me from these scoundrels! I beg of you!",
	"What's happening?",
	"What's the matter?",
	"What's happened?",
	"They... They want to shame me! I beg you, don't allow them that! Save me from them!",
	"Those beasts... They want to do something horrible! Protect me from them, please!",
	"In the name of our Lord, save me from these lustful monsters! They want to dishonor me!",
	"Right, let's do it.",
	"Oh, thank you for your help!",
	"You saved me! I am ever so grateful!",
	"You are a true man. Thank you so much!",
	"There's only one way to deal with scum!",
	"I have some money. Please taken it, as a token of my gratitude!",
	"Thanks. But be more careful next time.",
	"I'll tell everyone that it was you who saved me! I'll let the whole world know what a brave and kind soul you really are!",
	"Right, thanks. I think you'd better go on home now.",
	"I have some money. Please taken it as a token of my gratitude!",
	"Thanks. But be more careful next time.",
	"I'll tell everyone that it was you who saved me! I'll let the whole world know what a brave and kind soul you really are!",
	"Right, thanks. I think you'd better go on home now.",
};
