string DLG_TEXT_BASE [37] = {
	"Lord, how great that I've met you!",
	"Finally,somebody has shown up here!",
	"God, how I'm happy to see you!",
	"What happened, honey?",
	"What's the problem, dearie?",
	"You don't have to worry so much, it's bad for the female body. Tell me quickly, what happened with you?",
	"My friend - she's so fearless, she went into an abandoned well!",
	"My friend climbed into an abandoned well and she's been gone for several hours!",
	"My friend disappeared into an abandoned well!",
	"Why the hell did she go down there?!",
	"Oh, she's not scared of anything! She heard that there was a dungeon done there that had gold, so she went. I'm not dumb like that, so I didn't go...",
	"That's for sure. This is no women's business.",
	"What should I do now? I ask, for all that's holy, help her!",
	"Fine, I'll take care of it. And you, go home. There's no need for you freeze here by yourself.",
	"We all got our problems. Ain't none of my business. Farewell...",
	"I don't want to talk to such a soulless fool. Get out of here!",
	"Heh. Bitch...",
	"God, how happy I am to see you!",
	"What's up, gorgeous?",
	"I got lost here! Dear Lord, am I scared!",
	"There, there. It's all right now. Follow me; I'll lead you out. Once we reach the surface, you'd best head straight on home. And you should hope I don't see you here again!",
	"Whatever you say. ",
	"Um. Sure, okay.",
	"Another soul could be bothered with our underground? I don't believe it!",
	"Hello, gorgeous. And what are you doing here?",
	"Well, that's none of your business, is it.",
	"Why, ain't that a million-taler answer...",
	"Two million, in fact. Now why don't you just keep walking. I've got no time for this.",
	"Neither do I, to be honest. But your girlfriend is pushing all the panic buttons up there...",
	"Oh God, that bimbo... She soils herself over a cockroach, and expects me to do the same. ",
	"Yeah, you don't seem the type. Is that really a skirt you're wearing? ",
	"Easy on the compliments. Anyway, just get out of my face, and we'll leave it at that.",
	"Well, all right. I guess I'm not needed here.",
	"No, you're not.",
	"Fair enough. Take care of yourself, then.",
	"You again? Back for another blow-off?",
	"Uh... Ahem...",
};
