string DLG_TEXT_BASE [24] = {
	"You'll be rich! It'll put you in rags... and into a handkerchief! *hic*",
	"Sit tight. I'll be back in a jiffy.",
	"Psshtt... Listen 'ere. I've got something for you...",
	"What are you talking about?",
	"Thish... Now thish ish drinking! *hic-urrrp*... C'm haff a drink wih me!",
	"Oh, come on. I thought you were serious.",
	"I got a thing... a special thing for you, for a great price.",
	"And what is it?",
	"Come on. I've got no time.",
	"This is a great map. You won't find this in a store. It tells you where to find treasure! I can't get there myself, but the map is authentic. I swear it!",
	"Very interesting. What are you asking for it?",
	"Oh, come on. I don't have the time.",
	"For you, only ",
	" gold.",
	"Deal! Do you gift wrap? ",
	"Too rich for my purse. I pass.",
	"Take it. Now you'll strike it rich for sure!",
	"Thanks!",
	"Hey, c'mere! Let's... *hic* ...have a drink! Whah, thish ish some good rum!",
	"In a hurry!",
	"You sold me a fake.",
	"Whozat? Who... *hic*... I... Oh, gawway... I dunno yeh, 'n I duwanna know... whoa... woh...",
	"Uh-huh.",
	"You sold me a bogus map! Why, I'm gonna...",
};
