string DLG_TEXT_BASE [171] = {
	"This is the menu for the type of drunkard (Beta test)",
	"Let there be a drunk",
	"Card player",
	"Dice player",
	"Choose your drunk",
	"Continue",
	"Card player (30% chance that he'll tell you off after the first round) ",
	"Continue",
	"Dice player (30% chance that he'll tell you off after the first round) ",
	"Continue",
	"I may be be drunk, but I'm still in my right mind. I'll drink with you now, and the soldiers will haul me in! Noooo...",
	"I'm not the enemy of the city in which I live. I'm not drinking with you!",
	"Buddy, it's best that you leave here quietly...",
	"Well, you know...",
	"Heh, it hurts. Gotta wet the eyes! Not the right time. ",
	"Don't block my light. I can't see the flies in the mug!",
	"I'm gone...",
	"*hic-urrrp!* Oh, pal... you look like an old shhhea wolf! Maybe you'll buy me a cup uh rum?",
	"I may be a sea wolf, but that doesn't mean I'll be buying some bum a drink...",
	"I'd be happy to join you, for the companionship.",
	"And why's that?",
	"How's about some cards? A very interesting game!",
	"I'm offering to throw a few cards around. You in?",
	"Why not play a few? Let's do it.",
	"And what are the rules of the game?",
	"Not now.",
	"No, I don't want to play cards with you anymore.",
	"I don't need it anyway.",
	"Let's play the bones. A very interesting game!",
	"Let's rattle the bones a bit? Let's play.",
	"Why not play a few? Let's do it.",
	"And what are the rules of the game?",
	"Not now.",
	"No, I don't want to play the bones with you anymore.",
	"I don't need it anyway.",
	" You cheated!",
	"Get the hell away from my table!",
	" Uh... what? Who's that? *urrrrp* Get out!",
	"Drunkenness damns your sinful soul. Come to your senses!",
	"Don't be rude.",
	"How dare you talk to me that way, vermin! I'll teach you good manners now.",
	"I'll knock you on the head once, and you'll be back in your senses in no time.",
	"Well, then, let's start!",
	"No, that's not for me...",
	"Let's agree on a wager.",
	"Let's play for a hundred coins.",
	"Let's play for five hundred gold.",
	"I think it's getting late.",
	"You're known as a master swindler. I'm not playing cards with you at all.",
	"Everyone lies! I don't need it.",
	"You're broke, pal. Come back when you strike it rich.",
	"Okay.",
	"I've already lost my shirt. Today's not my day.",
	"Okay.",
	"Fine, let's play for a hundred coins.",
	"Fork it over!",
	"You're known as a master swindler. I'm not playing cards with you at all.",
	"Everyone lies! I don't need it.",
	"I've heard you play well. I'm not going to play for big wagers with you.",
	"Then let's go for the lower ones?",
	"I don't need it anyway.",
	"You're broke, pal. Come back when you strike it rich.",
	"Okay.",
	"I've lost too much for such big wagers. This just ain't my day.",
	"A pity.",
	"Fine, let's play for five hundred coins.",
	"Fork it over!",
	"Well, then. Let's start!",
	"No, this isn't for me...",
	"Let's decide a wager.",
	"Let's play fifty coins a die ",
	"Let's do two hundred a die ",
	"I think it's getting late.",
	"You're known as a master swindler. I'm not playing the bones with you at all.",
	"Everyone lies! I don't need it.",
	"You're broke, pal. Come back when you strike it rich.",
	"Okay.",
	"I've already lost my shirt. This just ain't my day.",
	"Okay.",
	"Fine, let's play for fifty coins.",
	"Let's go!",
	"You're known as a master swindler. I'm not playing the bones with you at all.",
	"Everyone lies! I don't need it.",
	"I've heard you play well. I'm not going to play for big wagers with you.",
	"Then how's abouts we go for the lower ones?",
	"I don't need it anyway.",
	"You're broke, pal. Come back when you strike it rich.",
	"Alright.",
	"I've lost too much for such big wagers. This just ain't my day.",
	"A pity.",
	"Alright, let's play for 200 coins.",
	"Let's go!",
	"And why are you so curious? Hiccup! Is you a pirate?",
	"Forget it! 'Twas just your imagination.",
	"I heard that this one ",
	"huckster",
	"merchant",
	" on a ship called '",
	"ÿ under the flag of ",
	" is transporting a hold full of ",
	"Thanks, buddy! Alright, it's about time I get back to the sea.",
	"Umm... hiccup! I saw this real scary ghost ship with a bunch of corpses on board... They say it's been cruisin' the waters since the time of Columbus...",
	"Bah, I bet you're lying!",
	"Me? Lying? Hiccup! I've been drinking for two weeks straight trying to forget what I saw... How it entered the bay under torn black sails...",
	"And how did you stay alive through all this?",
	"I soiled my pants the moment I saw them land! Hiccup! Hey, don't you be laughing now - you woulda soiled 'em yourself! Anyway, I bolted outta there fast as I could...",
	"Wow, I don't know what you're drinking, but you better leave me some of that stuff for my day off.",
	"What's happening? Eh, it's all the same here... But rumors say that the Flying Dutchman sunk yet another gold convoy.",
	"Come again? What Dutchman?",
	"The Flying one! That's right, the ghost ship is back in the archipelago. It seemed to have disappeared for a number of years... Probably gone to hell and back. Everyone on the damn thing is cursed and impervious to bullets.",
	"You mean they cannot be killed?",
	"At times, they stormed whole cities, butchering the fort's garrison like piglets... Didn't matter if there were thousands of soldiers! I heard that some folks figured out how to sink 'em, but what's that to the dead? They'd just drag their ship to some shore, fix it up somehow, and get right back to their raiding ways.",
	"Man, what imagination... 'Drag the ship to some shore' - that's gold! Thanks, buddy, for a very entertaining story.",
	"Yeah, man, the word is that they're planning on robbing another fort. Dunno which one; ask the city administrators. Maybe some of them need some help.",
	"Oh! Alright, thanks. I'm gonna go now.",
	"The Flying Dutchman'? Yes, the ship does indeed exist, although many think it's just a myth.",
	"I saw it with my own eyes! And barely lived as a result. Where can you find it?",
	"Alright-alright, I believe you. Where can I find it?",
	"The local smugglers told me that it entered our bay yesterday.",
	"What, this bay right here? Is it still there?",
	"How should I know? It's probably back out at sea by now. The smugglers ran for it as soon as they saw the ship. Lost all their merchandise...",
	"Well, I'm off to try and catch up to it. Our conversation with him isn't over!",
	"Well, I'm off to try and catch up to it. We'll see what kind of ghost it really is.",
	"Eh, man... hiccup! Everything around the world is coolio... hiccup! And you don't know what's up... hiccup! Just that the rum is kicking in... hiccup! Black Jamaican rum... hiccup!\nBring it here, pour it on!",
	"And then?",
	"Bah, screw you!",
	"Amidst the mugs, the faces, and the heels... hiccup! Till you drop. I drink with everyone, everywhere I go... hiccup! That reminds me, I need a refill over here!",
	"And then?",
	"Bah, screw you!",
	"When the heart's heavy and everything's crap, a few mugs of rum will fix that right up! All the worries and lies, you'll transcend, and then you'll know I'm your very best friend!",
	"Bah, screw you!",
	"Hiccup! That's the stuff! My good fellow, you are the chap of all chaps! Huzzah! So, umm... You got the next round?",
	"Sure, pal! Innkeeper, more rum!",
	"Wow, you're a real friend! Let's drink to us meetin' like this!",
	"Hiccup! Man, this rum is amazing! So, you ready?",
	"To your health and your generosity!",
	"Woo, this rum's got a real kick. Anyway, I gotta run. Enjoy.",
	"Let's drink another round before you go.",
	"Got anything interesting to tell me about 'honest' merchants in these waters?",
	"I feel like I've spent an eternity out at sea. What's new in your neck of the woods?",
	"Listen, man, why don't you tell me some of the rumors around here? Let's put all that rum to good use... ",
	"Buddy, why don't you tell me some of the stories you hear in the local taverns?",
	"Ah! That's a great idea!",
	"Innkeeper! More rum!",
	"Hiccup! Ba... bastard! You wanna get me drunk... hiccup! And steal my money!",
	"Relax there, pal! Did you forget? I'm your one and only friend!",
	"Pipe down, you rat, before I cut your throat!",
	"Hey! You're a g-good man! M-maybe you can h-help me with... with this problem I got?",
	"Nah, I should get going.",
	"Of course! I mean, we're... hiccup... we're friends, after all!",
	"... And then I gr-grabbed his sword by the b-blade and...",
	"... and she's telling me...",
	"To you! Eh, damn it! Who the hell?!",
	"Eh? What? Where? It was probably nothing.",
	"Let's drink another round before you go.",
	"Woo, this rum's got a real kick. Anyway, I gotta run. Enjoy.",
	"What are some of the stories you hear in the local taverns?",
	"Anything interesting happening in these waters?",
	"Tell me, buddy, what do you know about a ghost ship called the Flying Dutchman?",
	"I ain't never refused a drink! So, how 'bout another round?",
	"Pour it!",
	"The thing is that one of your s-soldiers insulted m-me. T-that's right!",
	"S-soldiers? N-nah, I'm gonna pass...",
	"Relax there, pal! Did you forget? I'm your one and only friend!",
	"You? You ain't n-no friend of mine! You wanna... hiccup... you wanna kill me! I know it!",
	"Alright, I see that you've had one too many. Later.",
	"What? I'll prove to you that I don't want to kill you! I'll... hiccup... I'll cut off your hand!",
	"A-a-a! Get him away from me!",
	"Relax, buddy... hiccup... It won't hurt!",
	"Argh! I'll carve you like a pig!",
	"We'll see about that!",
};
