string DLG_TEXT_BASE [113] = {
	"The alarm's gone up in the city. It looks like I've got to pick up my arms too...",
	"Hey, isn't the entire city guard rushing after you? Soldiers! Over here!",
	" You won't find a hiding place here. Though you'll find a few inches of cold steel under your ribs.",
	"What do you want, scoundrel?! The city guards are in already in pursuit of you. You won't go far, dirty pirate!",
	"Dirty murderer! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Looks like you've gotten sick of living...",
	"Heh. They can't live calmly, the peaceful citizens of ",
	"Go to hell!",
	"Heh. You've got a few seconds left to live...",
	"I warned you. And then think if you should get on my nerves or not...",
	"Heh!",
	"What do you want in my house, scoundrel?! I'm giving you ten seconds to get out of here!",
	"Heh. Even here they know me!",
	"My face precedes me...",
	"Hm. Understood.",
	"Happy to greet you in my house. Do you have any business with me?",
	"How may I help you?",
	"Hm. What can I do for you?",
	"Forgive me. If there's nothing you need, I'll ask you not to disturb me...",
	"No, just looking around the city. Getting to know the inhabitants...",
	"Oh, nothing special...",
	"Nothing...",
	"Okay, as you say.",
	"Forgive me, but you've picked the wrong time to show up at my house. The night is nigh. I'll ask you to leave!",
	"I already said it's late now. I'll ask you to leave.",
	"I don't want to seem rude, but I insist that you leave my house immediately!",
	"Dammit, what is this?! Guards, thieves!",
	"Fine, I understand...",
	"Okay. Just one moment...",
	"All right, already. Don't blow a gasket.",
	"Hush my face. You've got thieves in here? ",
	"Ooh, allow me to introduce myself. I'm ",
	". We're happy to see you. The laws of hospitality aren't an empty promise in our city.",
	", it is good to make your acquaintance...",
	"You're the thief! Guards, hold him!",
	"Man, ain't that something! I drop my guard for a moment and you're got your head in my chest immediately! Hold the thief!",
	"Guards! I'm being robbed! Hold the thief!",
	"Aw, hell.",
	"I'm warning you, that my husband will be back soon! You should leave my house...",
	"I don't think you'll get away. And know that my husband will be home soon!",
	"My husband will be home soon. You should leave here immediately!",
	"A pity my husband isn't home... Now leave!",
	"Dirty murderer! Out of my house! Guards!",
	"What a villain.... My husband will be home soon, and he'll see what color your blood is!",
	"While the husband's away, the wife will play...",
	"Heh... You can't scare me with your husband, kitty-cat...",
	"Shut your mouth, or I'll let your guts out...",
	"I'm staying here as long as I please. And you'll sit here quietly, or you'll be worse off...",
	"I warned you. Get out, or it'll be worse for you!",
	"What's wrong with these people...",
	"What do you want in my house, scoundrel?! I'm giving you ten seconds to get out of here, or I'm calling the guards!",
	"What a stupid girl...",
	"I'm happy to see you at our house. My name is ",
	". How can I help you?",
	"You're still here?",
	"Hm. Forgive me, but don't you think you've outstayed you're welcome here?",
	"I ask that you don't presume upon our hospitality.",
	" at your service. I'm not here on any business. Just wanted to get acquainted.",
	"Still here.",
	"Well, how can I put this...",
	"Um. Sure, okay.",
	"My Lord, what are you doing breaking into people's houses at this hour?! You scared the daylights out of me... Please leave. You may come back tomorrow at a more reasonable hour.",
	"I asked you to leave! I'm a married woman!",
	"Please leave our house! This is the last time I'll ask nicely!",
	"What is going on here?!",
	"Don't be afraid, I won't hurt you.",
	"It's alright, don't be scared...",
	"I'm leaving.",
	"What's the problem?",
	"Alright, we're always happy to welcome guests. But I ask that you don't stay too long, seeing as I'm married...",
	"Oh! Yes, of course...",
	"So that's how it is?! I let you into my house as a guest and you start pawing through our chests?! Guards!",
	"Get off me...",
	"I asked you to leave peacefully one too many times... Guards! Help!",
	"Can it, bitch! What are you, nuts?!",
	"The alarm's gone up in the city. It looks like I've got to pick up my arms too...",
	"Hey, isn't the entire city guard rushing after you? Soldiers! Over here!",
	"You won't find a hiding place here. Though... you will find a few inches of cold steel under your ribs.",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Dirty murderer! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Looks like you've gotten sick of living...",
	"Heh. They can't live calmly, the peaceful citizens of ",
	"Go to hell!",
	"Heh. You've got a few seconds left to live...",
	"What do you want here? Wait, I think I know you... Guards, get the bastard!",
	"I'll shut you up for good...",
	"Greetings! My name is ",
	". I'm in charge here, so don't even think about stealing anything...",
	"Behave yourself. Remember: I got my eye on you.",
	"You can stay, as long as you don't go prying into those chests. Ugh, I'm so bored being here all alone...",
	"Man, is this boring or what!",
	"Man, I wish there was something fun to do around here...",
	"Alright-alright, don't worry.",
	"Of course!",
	"I see...",
	"Yeah, you got some problems, buddy...",
	"Listen, pal, I'm going to be frank with you.",
	"Heh! Alright, let's be frank.",
	"I need to get to the shipyard at night when no one's around.",
	"Is that so? Guards, we've got ourselves a thief over here!",
	"Hey, I'm no thief! I just wanted to talk!",
	"Hah! You know, pal, you're something else, coming into a shipyard warehouse with a request like that!",
	"But I don't need the warehouse, I just need the shipyard. I won't even look in this direction, I promise.",
	"What do you need this for?",
	"I just do, alright? And I'm ready to make it worth your while...",
	"Hrm, now it's getting interesting... Alright, here's the deal. Count off ",
	" right here and now, and I'll make sure that the door to the shipyard remains open for the next 24 hours.",
	"I don't have that kind of cash. I guess I'll have to do without...",
	"Deal. Take your money and do as we agreed.",
	"Don't worry, it'll be done.",
	"Alright, I'll trust you...",
};
