string DLG_TEXT_BASE [31] = {
	"We've been monitoring you for a long time. Now you're in our hands.",
	"Who are you, and what do you want from me?",
	" is offering a good price for your head. Doesn't matter if we deliver you dead or alive.",
	"I'm ready to pay you more, if you leave me be.",
	"I think you've made a mistake. I am ",
	", a known trader in these parts.",
	"Well, then. try your luck.",
	"Fine, I'll go with you. I was going to square everything off myself anyway.",
	"Oh, I think we've made a mistake. Forgive us, ",
	"Oh, it happens...",
	"It looks like you're lying!",
	"I'm ready to pay you more, if you leave me be.",
	"Well, then. Try your luck.",
	"I think that ",
	" piasters will satisfy us.",
	"I don't have that kind of money.",
	"Here's your money. Take it and get lost.",
	"That kind of money for scum like you... Nah, I think I'd rather cut your throats instead!",
	"Then consider this conversation over!",
	"You won't take me alive!",
	"Hold on there, pal... Seems to me you got some interesting things on ya. I think it's best if you share some of those treasures with your new friends.",
	"Alright, I'm ready to pay you to leave me alone.",
	"I think you've made a mistake. I am ",
	" , a household name in these parts, and not some treasure hunter!",
	"Well, I think it's time your heads say farewell to your bodies.",
	"Oh, I think we've made a mistake. Forgive us, ",
	"Oh, it happens...",
	"It looks like you're lying!",
	"Then you will listen to the song of my blade!",
	"island ",
	"continent",
};
