string DLG_TEXT_BASE [48] = {
	"Brothers, enemies are in the Inquisition!",
	"Sound the alarm, brothers!",
	"Yeah, the enemies of the Inquisition don't doze off...",
	"What do you want, within the walls of the Holy Inquisition!",
	"Father, I've got a matter for you. Won't you grant a jealous Catholic a minute of your time?",
	"Hello, my son. What fate brings you here?",
	"I'm happy to see you in our house, my son. Why have you come?",
	"My son, we've already talked today. Do you need something else?",
	"My son, the followers of our order are known for their patience. Yet I shall ask you again: do you need something?",
	"It's no good to be in playful mood yourself, if you distract all others from their work. I shan't say another word...",
	"My son, I have no desire for meaningless conversation. I shan't say another word to you.",
	"Oh, I've just stopped by on some business, Father...",
	"It's all business-related, Padre. I'm working like a bee, and I'm all a-buzz with worries...",
	"Oh. No, Father...",
	"Nah, Padre. Just wanted to talk a bit...",
	"Hmm...",
	"Well, you know, pops...",
	"Damn, it's a spy! Grab him!",
	"?Ay caramba!",
	"This is a guarded cell! Entry here is strictly prohibited!",
	"Don't even think about coming in here. It's punishable by death.",
	"One step inside this cell, and you're finished...",
	"Crystal clear, soldier.",
	"Understood...",
	"Ho-ho! It's ever so much fun watching the 'holy' hypocrites go straight to hell!",
	"My God, there was someone brave enough to challenge them!",
	"The torture was too much... I'm a goner... but you really made my day, the last in this life. Thank you...",
	"Heh!",
	"Argh...",
	"Listen, do you know a man called Rock the Brazilian?",
	"Those 'holy' hypocrites lost all the remnants of their humanity. Mark my words, they will burn in hell for torturing us...",
	"Daily torments and tortures! I am completely innocent before the Lord!",
	"My cellmate was tortured on the rack for two days straight. He finally died yesterday... I wonder how long I will last?",
	"Hrm, I don't know...",
	"Ah, I understand...",
	"Listen, do you know a man called Rock the Brazilian?",
	"I do. He's in the end cell by that guard over there. See him? That's a special place...",
	"Thanks!",
	"In the end cell, right of the exit, where the sentry stood before you killed him...",
	"Ah, I see... Thanks.",
	"I'm listening, my son.",
	"I want to tell you about the devil's place, where evil roams at night!",
	"Go on.",
	"It's a city called Des Moines that's in Maracaibo lagoon. You must burn the whole damn thing to the ground!",
	"Uh-huh... We'll get right on that, my son. The Lord thanks you for your loyal service to the church.",
	"Always happy to help!",
	"And to help you remain this helpful in the future, here's a reward of 10,000 piasters for your efforts.",
	"A thousand thanks, your holiness!",
};
