string DLG_TEXT_BASE [44] = {
	"If you're reading this text, looks like there's a pretty big bug in the code! Whoops!",
	"Exit",
	"Time to blow this place, before Cap and the rest of the team return...",
	"The devil?! What's happened here? We've got to find at least one survivor...",
	"Hmm, a strange letter. She was notified of the arrival of a person... And who could have informed her? Someone who would not have attracted the attention of the servants! It could have only been a local resident. I need to find and question a local resident, who informed Dona Anna.",
	"A strange pair, though... A think it's worth tracking where they're off to...",
	"This looks like the servant of Rosette... The Salvatore case is easy to solve; the bodies of the innocent are everywhere. That means we're on the right path.",
	"Aha. And there's obviously an entrance here... to somewhere. But it's sealed off with a plate. I can't enter.",
	"Ah, that's just what I need - a brace, soldering torch, and tin snips... Now to begin the operation...",
	"Use the instruments.",
	"Oh! I hear some noise. I'll stand here and see what happens next...",
	"It was a heavy fight... Now I can call all the cowards who ran away.",
	"Ha! That was easy. And those land rats ran away!",
	"Hm... What would I like to do now?",
	"What to do now?",
	"Rest until morning.",
	"Rest until night.",
	"Rest until the following morning.",
	"Rest until morning.",
	"Rest until night.",
	"Rest until the following morning.",
	"Cash book.",
	"Enlist the slaves as part of the crew.",
	"Commence the capture of the nearest city.",
	"Not now. No time.",
	"No time. Business awaits.",
	"Well, sure we can commence the attack so as to capture, but the ship won't last long under the fort's fire. And we won't have the time to land our troops.",
	"No-no-no, I'm not crazy. This is Panama! It CANNOT be captured! We need to get the hell outta here before I get my very own black spot...",
	"Attack the city of ",
	"To arms!",
	"Avast!",
	"Bah! There's not enough crew. We need at least 500 men.",
	"None of the slaves want to become part of the crew.",
	"Well, fine!",
	"There's no room on the ship for new sailors.",
	"Bah! We need to transfer part of the crew to another ship.",
	"Some slaves want to become part of the crew - ",
	" to be exact. Do you take them?",
	"Yes",
	"No",
	"Now this fine ship is mine, and I'm its captain! Too bad I had to wipe out the whole crew, though.",
	"Time to go ashore...",
	"demon",
	"Azzy",
};
