string DLG_TEXT_BASE [183] = {
	"Money on the table, pal! I'm called ",
	" and I don't take objections lightly.",
	"Show me the contents of your wallet, pal, and fast! I'm called ",
	", and I hope you've heard about me.",
	"Take out anything valuable that you've got. I'm requisitioning the contents of your wallet. And make it snappy, because I'm ",
	" and I'm not very patient. But I'm verrry bloodthirsty!",
	"Heh, so you are the ",
	" who Governor ",
	" spends so much time talking about?",
	"Oh, so you're that bandit that is being hunted by Governor ",
	"Happy to see you, ",
	". Governor, ",
	", spends so much time talking about you...",
	"Yes. I'm, uh, known in these parts... Hang about, aren't you just another dog of the Governor, that he's trying to set on me?",
	"The Governor is a good friend of mine. What's there to hide? Ha! You don't happen to be another hero, sent after my head?",
	"The Governor's friendly disposition toward me is a fact. And how do you know about that? Maybe he sent you after my soul?",
	"It's as you say, villain. Prepare to die!",
	"Oh, aren't you the wise one. Well, then. It's time to move on to the liquidation then. Enough talk...",
	"Yeah, that's me. Draw your weapon, friend! Let's see what color your blood is.",
	"Ah, no. Come on! I don't need these problems...",
	"No, I don't take work like that. Not a hero at all...",
	"No, no! Not a bit! I don't need any problems...",
	"It's better that way, buddy... Now get out!",
	"And that's the right choice. If you only knew how many heroes I've sent to the next world... But enough poetry. Get out, dirtbag!",
	"Good boy! Praise you! A very wise lifestyle. Don't go where you're not asked to. Alright, buddy. Take care.",
	"Goodbye, and I wish you health...",
	"What do you want, ",
	"I need to learn who you are. Immediately state who you are, and what you're doing here.",
	"Well. Who the hell are you yourself, to be asking those questions?",
	"I'm looking for an enemy scout, by order of the Governor!",
	"So what does that have to do with me? ",
	"Maybe nothing at all, but for starters let's jaunt off to the Commandant's office. There we'll straighten everything out...",
	"No, I'm not jaunting anywhere. Consider the scout found. And now try to get out of here alive.",
	"Ha! Well, I'll get out of here somehow...",
	"Ah, It's you, ",
	", the old fox ",
	"Glad to see you, old-timer ",
	"Oh! Why, it's the very real Captain ",
	". I didn't think you were still of this world!",
	". Sloshed as ever, are we? ",
	". And, I still see you're free!",
	" No, what do you need?",
	" What do you need this time?",
	" Bothering me with trifles again?",
	", Captain ",
	"Hello, ",
	"Greetings, Captain ",
	". What does such a renowned personage as you need with me?",
	". Why have you come?",
	". What do you want to know this time?",
	"Hello, Captain ",
	"Greetings! Ah, it's you, ",
	"Ah, Captain ",
	" I thought ",
	"",
	" that we wouldn't meet again ",
	" I can't say I'm happy ",
	"",
	" to see you, but",
	" I see you're still alive - for better or for worse. So ",
	" what do you need from me?",
	" why have you come here?",
	" how can I ",
	" be of use?",
	" make myself useful to you?",
	", Captain ",
	". How can I help?",
	"Oh. It's the real Captain ",
	"! What do you want this time?",
	"Hello, ",
	". You wanted something?",
	"No, you misheard. I said I'm going.",
	"No, nothing, I was on my way to the tavern.",
	"Okay, never mind. Good luck!",
	"Just looking around the city. Bye-bye.",
	"I've got a question for you.",
	"I need information.",
	"Stop! Tell me immediately who you are! I'm looking for an enemy scout, by order of the Governor of ",
	"Stop, immediately! I'm acting on behalf of ",
	", under order of the Governor himself. I'm looking for an enemy agent in the city.",
	"Stop, buddy! Governor ",
	" really wants to find the spy in the city ",
	"Stop, she-woman! Tell me immediately who you are! I'm looking for an enemy scout, by order of the Governor of ",
	"Woman, I must stop you! I'm acting in the interests of ",
	", under order of the Governor himself. I'm looking for an enemy agent in the city.",
	"Hang on there, gorgeous! Governor ",
	" really wants to find an enemy spy in the city...",
	"I wanted to learn something about the town!",
	"I wanted to learn something about the city!",
	"Oh, yeah, I'm happy ",
	"",
	" you as a drunk. Tell me what you'll have.",
	"Why, Captain, aren't you a talkative fellow? I suppose I can keep you company... over a bottle of rum.",
	"Yes, ",
	"Well, what else do you want?",
	"I see, Captain ",
	", that gum-beating is your favorite sport? ",
	"Enough with the questions, Captain. Why don't we share a drink instead?",
	"What would you like to know ",
	"I'm all ears, Captain.",
	"Ask your questions faster, Captain. I need to leave soon.",
	"Always happy",
	"",
	" to be in such great company, ",
	". Please, go ahead.",
	"Yes, ",
	"Why, Captain, aren't you a talkative fellow? I suppose I can keep you company...",
	"What are the rumors on local tongues? ",
	"What's new in these parts?",
	"How's life on dry land?",
	"Can you give me some directions?",
	"I can't seem to find this place I'm looking for...",
	"I'm looking for directions...",
	"Tell me about your colony.",
	"I've got an important matter to discuss!",
	"I've got a matter to discuss with you.",
	"You misheard. I'm going.",
	"Oh, nothing. Just heading off to the tavern.",
	"Alright, nothing. Good luck!",
	"I'm just looking around the city. Goodbye.",
	"To be honest, that's not my area of expertise, but I can tell you what I know.",
	"What would you like to know about our colony?",
	"Of course. What would you like to know?",
	"What is this city?",
	"Tell me about the fort that protects the city.",
	"Let's talk about something else.",
	"A joker, eh? Kindly direct your attention to the upper right corner of your screen.",
	"Oh yeah. My bad.",
	"I don't know anything about that.",
	"A pity.",
	"So what have I got to do with it? I'm just a local resident!",
	"Can anyone corroborate what you say?",
	"Anyone can confirm it; just ask anyone!",
	"Who's anyone? Give me the name of one citizen in ",
	"Eh... Umm... Sec...",
	"Nuff said, pal, you're the one that I need! Now you'll either come with me, or I'll kill you right here and now. Understood?",
	"Damn it! It sure was stupid of me to get into this mess! All right, I'll follow you. I still value my life...",
	"I am taking you to see the Governor. He'd like a chat with you...",
	"Have you heard? Governor ",
	" ordered a certain Captain ",
	" to track down an enemy spy in the city. Believe it or not, he caught him right in the city streets!",
	"Our Governor gave Captain ",
	" a job to find an enemy agent in the city, and this captain arrested the spy right there in broad daylight!",
	"So you decided to come back after all...",
	"Yeah, I forgot something...",
	"Who the hell are you, anyway?!",
	"I'm here for your head, pal. The Governor of ",
	" wants to see it mounted atop the city gates.",
	"Damn, I underestimated you initially.   \nWell, shall we continue?",
	"We shall!",
	"Heh, I see... Well, I'll try my best not to give him the satisfaction!",
	"You do that...",
	"Good to see you on my ship, friend. What brings you here?",
	"I'm acting on behalf of the Governor of ",
	". I'm searching for a pirate that's been active in these waters as of late.",
	"Hmm, I can't say that this is a task worthy of a captain...",
	"And what do you mean by that?!",
	"Exactly what I said. Hunting free corsairs, only to have the local Governor litter the city and its surroundings with their corpses is a task that's unseemly for a captain of a vessel.",
	"So you're the pirates I'm looking for...",
	"You are correct, Governor's rat.   \nI wish I could tell you that you won a prize, but I'm afraid that your situation is far less enviable, being alone on my ship and all...",
	"So what are you going to do?",
	"Hmm, well... I'm a bit too close to the fort. I'd rather not risk it, so I'll just keep you here for a while. And you'll tell your crew that you will take this ship to a place called ",
	", and have them wait for you in ",
	". If you do this, I will let you live. If you don't, my men will disembowel you right here on the deck.   \nSo, how do you like your options?",
	"Not too tempting, to be honest. How do I know that you'll keep your word once you're out of the fort's range?",
	"You know, I think I'll just let you go, Governor's dog. You'll repay my generosity with your cash.   \nGo on, get outta here before I change my mind...",
	"One must be thankful for small mercies. Goodbye...",
	"You know what? I think I'll just cut your throat right now while your men aren't looking...",
	"And then you'll tell your crew that you will take this ship to a place called ",
	", and have them wait for you at ",
	". If you do this, I will let you live. If you don't, my men will disembowel you right here on the deck.   \nSo, how do you like your options?",
	"Not too tempting, to be honest. How do I know that you'll keep your word once I'm left all alone?",
	"Heh, you don't know, but you do have my word. You can always refuse and die right now. If you ask me, the choice should be obvious...",
	"Hrm, alright, I agree. Let's hope that you'll keep your word...",
	"You're right, it is obvious. I choose battle, right here and now. Ready your weapons, dirtbags!",
	"I'll keep it. Don't worry.",
	"I'm ready, then. Let's go.",
	"If I ever see you again, you'll be sleeping with the fishes. Keep that in mind...",
	"Understood...",
	"You're still here? I wouldn't be dallying here if I were you...",
	"I'm leaving.",
	"Ooh, aren't we brave! I respect courage. It's too bad that I'll have to kill you for it...   \nHey you, on the deck! Waste this wannabe while I prepare the ship for combat. But do it quietly!",
	"It's too bad you're leaving us...",
};
