string DLG_TEXT_BASE [139] = {
	"Nothing to say!",
	"Welcome to our business. Happy to see a follower of ",
	". May I ask your name?",
	"I'm called ",
	". I'm the captain of my own ship.",
	"I'm happy to see you again at my house. Are you here on business?",
	"You again? We've already discussed everything, Captain.",
	"Captain, do you still need something else?",
	"Captain, I'll ask you not to distract me!",
	"No, ",
	". Just dropped by...",
	"Oh, of course.",
	"No, ",
	". Forgive me...",
	"Fine...",
	"Tell me, are all the pearl divers in the Caribbean your subordinates?",
	"I'm come here for my reward, Señor.",
	"Yes they are. Why do you ask?",
	"It must be difficult for them, what with all this piracy. A certain captain Sharpe is known among the corsairs...",
	"Oh, he is known among pearl divers as well, my friend. He's a real scourge for us!   \nIt's as if he's got nothing better to do than chase after our tartans! And the bastard always finds out who's working where.",
	"He knows an awful lot about divers, and that's a fact...",
	"We're taking all the necessary precautions, but it's useless. Judging from everything, someone is informing him of our plans.   \nListen, you didn't start this conversation just because. Do you know something about this matter?",
	"Just what I've already said. In the Caribbean Sea, everyone knows Captain Sharpe...",
	"That's clear. Well, then. I'd like to offer you a job, if you're up to date on your misfortunes.",
	"What job? To stop Sharpe?",
	"No, that would be too easy. And ineffective, to boot. Whatever villain has been giving out information about the places where we work will just find himself another Sharpe to sell his information to, and our tartans will be looted again.",
	"That's reasonable.",
	"I want you to find the rat amongst us.",
	"Understood. Now let's discuss compensation...",
	"Hum. So be it. I could offer you gold and pearls, but I think I can suggest something more up your alley.   \nIt's a weapons kit. It includes a Beretta, a Spanish rapier, a poleaxe, and a wonderful gilded cuirass! Believe me, the cuirass alone is most of the value!",
	"Heh. Intriguing...",
	"And add a rat god to that, which I'll give you now as an advance.   \nCome on, agree!",
	"Damn, sure I'll agree! Who wouldn't!",
	"No, I'd rather decline.",
	"Then I await the good news from you, Captain! You can report and get your reward at any of the elders of the two pearl diver settlements. They'll be informed of our agreement.",
	"Understood. I'll begin searching immediately.",
	"Strange. You come to me, start a conversation about Sharpe, and then decline a job. This is all suspicious.   \nI'm afraid I can't let you leave here alive.",
	"What?!",
	"Aha! I know who you are. Well, tell me what you've been able to dig up.",
	"I found a person of yours, what been slipping information about your tartans to Sharpe. It's Emilio Garcia.",
	"Can you prove it?",
	"Yeah. I track him and found him in a cave in the cove of San-Juan del Norte, just as he was talking with a trusted official from Sharpe. I killed them both.",
	"Understood... Well, I believe you. Your reward for the work done is a weapon set. Correct?",
	"That is so, Señor.",
	"Then receive it, please. All of this is yours now.",
	"I'm very happy that I could have been of service to you.",
	"May I ask what you're doing in the middle of nowhere?",
	"I'm scouting the territory. Perhaps this knowledge will do me well in the future.",
	"So you're an explorer. Well, wonderful. I want to bring you up to speed on the way things are here.",
	"I'm listening closely.",
	"Pearl operations, at the moment, belong to ",
	". That's why nobody here can buy or sell a pearl.",
	"Understood.",
	"If you try to get into my chests, punishment will swiftly follow.",
	"I get that too.",
	"Well, then wonderful. Take my assertions as being positively inclined towards you, ",
	"I'm grateful.",
	"Hello! Allow me to introduce myself. My name is ",
	". My goal is to warn the pearl diver settlement about a possible attack. Pirates, you know. And you are?",
	"Greetings, again!",
	"I stand here all day, every day. It's lonely. No one to talk to...",
	"Ah, dammit... There's some good ventilation here!",
	"I'm called ",
	". I'm a captain, checking out these lands.",
	"And I too...",
	"I understand.",
	"Heh...",
	"If you're here to visit our settlement, then welcome.",
	"Thank you, pal.",
	"Alarm! It's a pirate!",
	"Damn it! I should've killed you when I had the chance...",
	"Greetings! My name is ",
	". How may I be of service?",
	"Greetings, again!",
	"Guests are a rarity in these parts...",
	"Oh it's good to see and talk to a new face! I'm so sick of the same ol' mugs around here...",
	"Eh, I don't know if you can...",
	"And I, too...",
	"I understand.",
	"Heh...",
	"Listen, your boss wanted me to do this job for him... Anyhow, do you know if anyone here's been meeting up with pirates?",
	"Hey, buddy, do you know if anyone here has got connections to pirates?",
	"Hey, bud, I've got a question for ya. Have you noticed any of the guys here dealing with pirates?",
	"We're harvesting pearls for ",
	". That's what we do...",
	"Yeah, I know...",
	"Hey, listen, I'd like to buy some of these trinkets wholesale, so to speak. What do you say?",
	"Are you crazy?! They'll feed me to the sharks for stealing even the smallest pearl...",
	"Heh, you guys sure don't have it easy here...",
	"We sure don't. Ain't too many of us here willing to lose our head for a damn rock. But if you want, you can ask the local Indians. They work with us, but they also got spots of their own to hide out in, should the need arise. That kind of thing gives courage to any man...",
	"I understand. Thanks for the tip.",
	"Are you out of your mind? Get the hell outta here, dummy!",
	"What?! Boy, you must be out of your mind! Take your questions and shove 'em!",
	"Are you in your right mind, boychik? Pirates?! Here?! I think that your loony ass had better leave...",
	"No reason to be rude...",
	"Watch the language!",
	"White-faced man wants to talk?",
	"You again, white-faced man.",
	"White man likes to talk. He is like squaw.",
	"The spirits bring me my white-faced brother.",
	"Yes.",
	"Yes, it's me.",
	"That's very poetic.",
	"Nice to see you, too.",
	"Say why you come.",
	"No reason. Just wanted to listen to you...",
	"Do you have pearls for sale?",
	"Listen, my red-skinned friend! I'm looking for a man, one of the pearl divers. Can you help me?",
	"What does white-faced man seek? Tell me...",
	"Well, you see, there's reason to suspect that one of your guys is leaking information to an outside source. Information about where in the Caribbean you'll be working.",
	"I know what white-faced man wants...",
	"Say what?",
	"Listen to me, my white-faced brother, I won't speak much. There is a man here, named Emilio Garcia. He was seen in a cavern of one bay.",
	"Which bay?",
	"You call it gulf of San Juan del Norte. Emilio often goes there at night. There he speaks with a white man. No one knows the white man's name, but his gaze is like a rattlesnake.",
	"Why doesn't anyone know his name?",
	"Because he never spoke it.",
	"Ahh, I see. Well, thank you for everything, my red-skinned brother.",
	"May the trail on your path be straight.",
	"And for that. Farewell.",
	"Why must I loosen my tongue before a white man? I will not.",
	"You won't tell me? Fine...",
	"I have tears of Gods. And white-faced man barks like a dog. Everyone hears, wants to kick in the arse. I'm leaving...",
	"Umm, what?",
	"I have tears of Gods. Come to great water close by; I will be there before first moon.",
	"I got it. You want me to be at the closest bay before midnight. I'll be there.",
	"You came...",
	"Sure did, and what's the price?",
	"Ten for big tear. Five for small.",
	"I'll take them. How many have you got?",
	"Never mind, I'm not going to buy anything.",
	" big, ",
	" small.",
	"Deal. I'll take them all!",
	"Spirits smiled at me. I am happy...",
	"Later, bud...",
	"You owe me ",
	" in cash. You have no money, I have no tears of Gods. Goodbye.",
	"All's the pity...",
};
