string DLG_TEXT_BASE [418] = {
	"Hey, this text you're reading? It means you're seeing a bug... report it at AT, for Navy.",
	"Of course.",
	"Listen, get out of here! If you ruin the deal, I'll rip your heart out!",
	"You dare to threaten me, dog?",
	"You'll choke on those words, scoundrel!",
	"Ah, I know how it is. Business is business. 'Til we meet again.",
	"Good day. I'm called ",
	", and you are?",
	"... Only I and the Devil know this place, and the last man standing takes all the plenty for his own!",
	"... And Meinard answered: 'I won't ask quarter from you, and you won't see it from me either!'",
	"... Once at the sea, being somewhat drunk, he suggested: Let's make ourselves our own hell here, and see who stands the longest.",
	" And here's another pirate!",
	" Sirs, there is what appears to be a gentleman of fortune at our table.",
	" It's begun to smell of blood and gunpowder. Filibuster starboard!",
	" It's rare to meet an honest captain in these seas.",
	" Honor isn't in fashion, in our time.",
	" And here's the honest captain. No match for you head-slashers! Heh, heh!",
	"And I'm ",
	"Pour one for everyone! I'm Captain ",
	"I'm the captain of the washtub '",
	"ÿ and a few hundred genuine devils! Heh, heh! My name is ",
	"Gentlemen, allow me to introduce myself. I am Captain ",
	"I don't have the honor of having been introduced. I'm the captain of the ship '",
	"ÿ under the flag of ",
	". My name is ",
	"Now, everyone here knows me! I'm ",
	". Good to meet you! How may I help you?",
	"One more deal!",
	"I've got something I wanted to discuss...",
	"Now, everyone here knows me! I'm ",
	", Captain of the ",
	"I've been thinking, here. Do you want to join me? With two ships, we could do some great stuff.",
	"Do you want to come aboard my ship, as an officer?",
	"I think an officer like you could keep from underfoot. What do you say?",
	"(Beta-Test) Quests.",
	"(Beta-Test) Duels.",
	"Nothing.",
	"Listen, get out of here! If you ruin the deal, I'll rip your heart out!",
	"You dare to threaten me, dog?",
	"You'll choke on those words, scoundrel!",
	"Ah, I know how it is. Business is business. 'Til we meet again.",
	"I've said my peace for the day!",
	"Oh, yeah...",
	"What do you want ",
	"Who's that? Oh, it's you... Get out. I'm not in the mood...",
	"What about a deal?",
	"I've got a conversation with you...",
	"Who's that I see?! Why, it's ",
	". What's new?",
	"How's life? May I be of service somehow?",
	"... Only I and the Devil know this place, and the last man standing takes all the plenty for his own!",
	"... And Meinard answered: 'I won't ask quarter from you, and you won't see it from me either!'",
	"... Once at the sea, being somewhat drunk, he suggested: Let's make ourselves our own hell here, and see who stands the longest.",
	" It's rare to meet an honest captain in these seas.",
	" Honor isn't in fashion, in our time.",
	" And here's the honest captain. No match for you head-slashers! Heh, heh!",
	" Any news?",
	" And here's another pirate!",
	" Sirs, there is what appears to be a gentleman of fortune at our table.",
	" It's begun to smell of blood and gunpowder. Filibuster starboard!",
	" What's new on the archipelago?",
	"I've been thinking, here. Do you want to join me? With two ships, we could do some great stuff.",
	"Listen, you look like an experienced captain. Do you want sail under my command?",
	"Oh, woe is me. Pain and misery! My ship has gone to the bottom!",
	"Who am I seeing?! What winds have brought you hereabouts? And here I am, left without a ship...",
	"A pity... Maybe I'll see more luck soon.",
	"Ain't that something... Well, I've got to go. Goodbye.",
	"Do you want to come aboard my ship, as an officer?",
	"I think an officer like you could keep from underfoot. What do you say?",
	"Hear anything new?",
	"It's that face. I just want to do a job on it.",
	"Ah, our beloved scoundrel. Do you desire a few extra holes in your chest?",
	"Never mind.",
	"I already told you, I'm not interested.",
	"I thought we'd already discussed everything.",
	"How could I forget!",
	"That's the truth. Come around.",
	"Hm... Rather not. I have no wish for a second go 'round.",
	"You think I'll get hooked into this twice?!",
	"Well, as you want it...",
	"Well, then. Have a happy time, staying here...",
	"Hm... Rather not.",
	"No, I'm a captain. I don't want to be an officer.",
	"Well, as you have it...",
	"Well, then. Have a happy time, staying here...",
	"You've got a full crew already.",
	"I don't think you're ready to command me.",
	"A pity...",
	"It's not meant to be.",
	"And that's what I need! Our daggers will choke on the blood of our enemies! One little problem: I need ",
	" piasters to pay off my debts.",
	"You look like a real sea wolf. And if you're ready to pay ",
	" piasters, then I think we can work together.",
	"Your offer is very flattering to me. I'll agree to the fairly reasonable sum of ",
	" piasters ",
	"Hm... You look like an experienced Sea Wolf. I think I should accept your offer - providing you're willing to pay me ",
	" piasters.",
	"I think we can work together, Captain. Just ",
	" piasters and my hand is yours to shake.",
	"I'll agree to that. But I hope that's not your daily rate! ",
	"That damned expensive, but I think you're worth it.",
	"I agree. Consider yourself part of the team.",
	"Hm... I think I'm prepared to part with that sum.",
	"It looks like you're worth the money. Here, take it!",
	"You're hardly worth that much. See you...",
	"That's damned expensive. I'm not ready to throw around that kind of money.",
	"Yeah, well... who ever said greed was a vice?",
	"Are you laughing at me? I could buy ten of your like, for that kind of money.",
	"Seaway robbery... Where do suggest I find that kind of money?",
	"Hm... and what are you so good at?",
	"It looks like you've got cash problems, Captain.",
	"Ah... that is so.",
	"That's great, then!",
	"I didn't doubt you, Captain.",
	"Don't be late for when we sail off.",
	"If you're reading this, you've caught a bug :-0 Report this to Navy, in as much detail as you can manage! :D",
	"Absolutely!",
	"I already told you that I'm not interested.",
	"Oh? I thought we were done here. ",
	"How could I forget!",
	"That's the truth. Come around.",
	"Sail? With you!? Grow up, first!",
	"I don't think I'm interested!",
	"Well, as you want it...",
	"Well, then. Have a happy time sitting on your ass.",
	"Hum. Rather not, 'm afraid. ",
	"No, thank you. I don't like sailing under another man's command.",
	"Well, as you wish...",
	"Well, then. Have fun in your tiny, dingy room. ",
	"I like you! Let's shake on it! I can already hear the rattling of piasters in our pockets.",
	"Aw, you're not such a bad kid... I think we'll do fine!",
	"I like your offer. I ag-",
	"ree ",
	"ree ",
	"That's interesting. We should do more together!",
	"I think this could be amusing. Let's shake on it.",
	"Excellent! I'll see you at sea!",
	"Let's shake on it! We'll be a great team.",
	"I think you've got enough companions already.",
	"You've got a lot of ships already. Why do you need another?",
	"Yes... Maybe you're right.",
	"I'm sick of you! I'm leaving the squadron!",
	"My patience has burst! I'm sailing off.",
	"I'm tired of your outbursts, Admiral... Allow me to take my leave.",
	"I've had enough of your idea of command. I'm leaving the squadron.",
	"Don't let the door hit your ass on the way out.",
	"You go to hell.",
	"I won't hold you.",
	"Freedom to the free. And wind in the sails for the journeyman.",
	"Hum... What about the big bonus?",
	"?Caramba! Perhaps you'll stay? I'm prepared to pay a bonus to your team!",
	"Sad to part... Maybe a small bonus will resolve our differences?",
	"How about a raise of wages?",
	"One time was enough. I don't believe your promises any more!",
	"You won't seduce me with money. My mind is made up!",
	"Well, then. All the best.",
	"Then get out, and see to it that I don't see you again!",
	"Bonus? Excellent! A sum of ",
	" piasters would suit me just fine.",
	"Well, if you pay my team ",
	" piasters, I'll talk them into staying.",
	"Fine! I'm prepared to stay for a modest bonus of ",
	" piasters!",
	" piasters would suit my team, for the time being.",
	"You've got to be kidding me! Get the hell out of here.",
	"Hah! I'd rather spend that money on something more useful!",
	"Oh no. I'm not that rich!",
	"Farewell. I don't desire to pay that much.",
	"That's great! Take the bonus!",
	"I had no doubt that the matter was just about money!",
	"Wonderful! I'm happy that you're staying!",
	"Here's the promised bonus. And now we're together again.",
	"Choose your template!",
	"Quest Template 1 - naval.",
	"Quest Template 1 - land.",
	"CHOSEN! Quest Template 1 - naval.",
	"Oh yeah...",
	"CHOSEN! Quest 1 B4533 - land.",
	"Oh yeah...",
	"I've told you everything already!",
	"Oh yeah...",
	"Whash goan on?. *hic* Don' ya shee we's restin' wiff friendzz!? *hic*",
	"Urm... No business, today!",
	"Understood...",
	"What's this talk? At least you're in time. Business, or a deal. We're always up for that!",
	"Hmm. What are you talking about?",
	"There's been a test offer by GG himself.",
	"... Only I and the Devil know this place, and the last man standing takes all the plenty for his own!",
	"... And Meinard answered: 'I won't ask quarter from you, and you won't see it from me either!'",
	"... Once at the sea, being somewhat drunk, he suggested: Let's make ourselves our own hell here, and see who stands the longest.",
	"And here's another pirate!",
	"Sirs, there is what appears to be a gentleman of fortune at our table.",
	"It's begun to smell of blood and gunpowder. Filibuster starboard!",
	"It's rare to meet an honest captain in these seas.",
	"Honor isn't in fashion, in our time.",
	"And here's the honest captain. No match for you head-slashers! Heh, heh!",
	"I'm not yelling! I'm saying there's business! Profitable!",
	"More careful? Bah! I know you, you're ",
	". I've heard all about you.",
	"I'm Captain ",
	"I'm the captain of the washtub '",
	"ÿ and a few hundred genuine devils! Heh, heh! My name is ",
	" I don't remember you.",
	"Allow me to introduce myself, gentlemen. I'm Captain ",
	"I don't have the honor of having been introduced. I'm the captain of the ship '",
	"ÿ under the flag of ",
	". My name is ",
	" . My name is ",
	"Hmm. And you... I seem to remember you.",
	"Hi, ",
	". What's up?",
	"I, ",
	", Captain of the ",
	". The most notorious corsair in all of Spain.",
	" A simple sailor.",
	"Yep, now I'll remember you.",
	"I've got a business proposition for you, friend. Now, I know that I can trust you, but I can't risk talking about it in a tavern - too many ears around. I'll be waiting for you on my ship. In case you forgot, my washtub's called '",
	"Spit it out now. I ain't got time for friendly visits.",
	"I've got a job that's got you and your cutthroats' names written all over it.",
	"Let's join forces and get ourselves a nice chunk of change! Naturally, we'll have to do some killing for it. He-he.",
	"I have a business proposition for you, Captain.",
	"Captain, you are a man of great renown. That is why I want to offer you a part in a rather alluring venture.",
	"This is just between us. Let's talk about the details in my chief-cabin on '",
	"ÿ over a keg of fine ale. Today.",
	"This isn't the best place to talk. Let's do it on my vessel, '",
	"ÿ away from prying eyes and ears. Don't be long now.",
	"To hell with the heel-dragging! I like my good news fast, and my bad news faster!",
	"No reason to put it off! There's a room in the tavern; we'll talk there!",
	"Why don't we discuss your proposition right now, in a tavern room?",
	"I'm afraid I'm not too keen on visiting your ship. If you want something, you better spit it out now!",
	"Uh... A tavern is not the place to talk business - too many prying ears around. I'll wait for you on my ship, '",
	"ÿ. We'll talk there.",
	"I ain't got time to run around, and even if I did, I still wouldn't do it.",
	"Alright, I'll come. But if you're just wasting my time, I swear I'll cut out your tongue!",
	"Alright, wait for me there. For your sake, I hope that the job's worth it and you're not just pulling my chain!",
	"I'll gladly accept your invitation, Captain.",
	"You've intrigued me. Of course I'll come.",
	"Boy, did the sea make you nauseous or what?! Go find yourself a teat to suck on!",
	"Did you soil yourself yet, boy?! Get the hell outta here! You're no match for me.",
	"Suit yourself. If gold doesn't interest you, I won't press.",
	"It's either my way or no way at all. You decide. Gold enthusiasts won't be hard to come by.",
	"Hah! What do you know, you got a pair! Alright, I'll come.",
	"You drive a hard bargain, Captain. Alright, wait for me.",
	"Very well. I agree.",
	"You're very persuasive. I'm prepared to talk business on your ship.",
	"Hah! You think you can lure me onto your ship and kill me? Fat chance!",
	"Your words ain't worth a dented penny! I got no reason to trust you!",
	"A dubious offer that I've no choice but to decline.",
	"Twas nice meeting you, Captain ",
	". Goodbye.",
	"More rum here! And you! Get out of my sight!",
	"This conversation's over, ain't it?",
	"Keep walking, buster; I'm busy.",
	"I reckon we've nothing else to discuss.",
	"I already told you that I'll be waiting for you on my ship!",
	"Oh... right...",
	"No-no-no... This won't fly with me... You ain't got enough ships, pal?",
	"Hah! Good luck keeping a secret with so many people around! Now get lost.",
	"Suit yourself!",
	"Well, not that I wanted to, anyway...",
	"That's better! Now I can be sure that we're away from prying ears; my sailors already know. So, my proposition is we claim ourselves a share of some unclaimed goodies!",
	"What's so difficult about that? Why are you sharing this with me?",
	"Welcome aboard, Captain!",
	"That's better! Now I can be sure that we're away from prying ears; my sailors already know.",
	" So, my proposition is we claim ourselves a share of some unclaimed goodies!",
	"What's so difficult about that? Why are you sharing this with me?",
	"Unclaimed? Surely you're joking?",
	"That's better! Now I can be sure that we're away from prying ears. Alright, talk!",
	"My proposition is we claim ourselves a share of some unclaimed goodies.",
	"Well, there are people who consider it theirs and need to be convinced otherwise.",
	"Naturally, we'll have to do some killing for it. But that won't be a problem now, will it?!",
	"Get to the point!",
	"I smell a good ol' blood bath! So where are these people?",
	"I'd like to know the details of your proposition.",
	"What exactly do you want from me?",
	"There's something you're not saying. I want no part of this!",
	"Sounds simple, but I don't believe you! You're keen on reaping the benefits while others do the work? Well, I won't do it!",
	"A tempting offer, but I must refuse.",
	"Nah, I'll pass. I've been raised not to take from others. I prefer gifts.",
	"What's so difficult about that? Why are you sharing this with me?",
	"Well, there are people who consider it theirs and need to be convinced otherwise.",
	"The caravan belonging to ",
	" and carrying ",
	"slaves",
	"slaves",
	", has stopped not far from ",
	" at the bay of ",
	" so as to restock their supplies.",
	", has gotten into a storm not far from ",
	" and carrying and sunk. However, the crew was able to save part of the cargo and landed at the bay of ",
	" Now they're waiting on the arrival of their squadron.",
	"Don't spin it out, spit it out!",
	"I was right about you. So, what else do you know?",
	"Very interesting. Do go on.",
	"I'm all ears!",
	"Sounds like a sweet deal, but I'll have to refuse. Messing with ",
	" wouldn't be a wise move on my part.",
	"Caravan? Unclaimed?? Those wagons will have a thousand soldiers guarding them! Sorry, but I'm out.",
	"Nah, I'm not fighting ",
	", this job ain't for me.",
	"My answer is no. I'm not about to mar relations with ",
	"Hmm... I smell a good ol' blood bath. Details?",
	"We have only ",
	" to intercept them.",
	"In ",
	" the caravan will leave, and then we'll never catch them.",
	"We have exactly ",
	" days to catch them, kill them, and get the booty!",
	"We have ",
	" days for the entire operation.",
	"We had better hurry, ",
	". We have only ",
	"We'll make it! We shall set sail today.",
	"Let's not delay. Give the order to set sail today.",
	"Very interesting, do continue...",
	"We have only ",
	" to intercept them.",
	"Let's not delay! Onward we go!",
	"Onward we go!",
	"You've disappointed me, Captain. Did you think I was inviting you to ",
	"the Sunday mass?!",
	"a school play?!",
	"That's your business, but the decision is mine.",
	"I don't feel like drying in the sun for a few piasters.",
	"My decision is final, Captain.",
	"This conversation is over.",
	"You worry too much! I bet everything goes smoothly, we kill 'em all, and no one suspects a thing!",
	"What, now that you know everything, you want to pull it off yourself? Think again!",
	"Where are you off to in such a hurry, Captain? Not to the authorities, I hope?",
	"It's rather foolish to crawl into a tiger's lair, thinking that crawling out will be just as easy.",
	"Off to the sea devil with you! I'm Captain ",
	" and you can't tell me what to do! I'm leaving!",
	"You're getting on my last nerve...",
	"I am not interested in your offer, which means we've nothing else to talk about. Goodbye.",
	"I reckon we've nothing else to discuss. Now, I must attend to my business.",
	"Seize him! Tie him to a cannon! Let's see what color his guts are!",
	"Hey, Johnny! Henderson! Grab the bastard! Don't let him near that lifeboat! ",
	"That's a shame, Captain. Well, I hope that you'll find our hold cozy. We'll figure out what to do with you later.",
	"White slaves don't live long, Captain. So you decide: either Henderson shoots you in the head with a musket, or you spend the rest of your days in quarries.",
	"I'll make you eat your putrid entrails, ",
	"Out of my way! Bastards! I'll crack your skulls like rotten pumpkins!",
	"Your proposition is unacceptable... And if I may add, quite imprudent!",
	"You could use a lesson in hospitality... Out of my way!",
	"Hmm, ",
	", I probably shouldn't have gotten mixed up with you. The booty slipped through my fingers like water. Goodbye!",
	"Bloody hell! We're late! And it's all because of you lazy oafs! There ain't no spoils to split now, ",
	". Raise the jib! Pay out the top easy! ",
	"Hmm, ",
	", I probably shouldn't have gotten mixed up with you. The booty slipped through my fingers like water. Goodbye!",
	"They're gone! And all because of your sluggish arses! This is where we part, ",
	"We can start drying our oars, 'cause we sure as hell ain't gonna catch that caravan now. Man, why did I even bother with you! Goodbye...",
	"To hell with the caravan, then! Pearl divers aren't any worse, and there's no risk involved!",
	"Luck is on our side - this isn't over! The sea bristles with miserly hucksters who can't wait to share their riches with us!",
	"A shame indeed that such a brilliant operation ended up a complete washout! Goodbye!",
	"Man proposes, but God disposes... Goodbye!",
	"Crap, why did I even bother with you... You ruined everything! Now you gotta pay me a forfeit of ",
	"You bloodthirsty mongrel! It's all at the sea bottom now with the sea devil! ",
	" piasters on the table, and I never want to see your mug again!",
	"Who the hell do you think you are, Admiral Nelson?! You sunk all the loot, you moron! Now pony up ",
	" and get lost!",
	"You've decided to wage a real war here! That won't do, no-no! But, I guess we can forget all about it if you pay us ",
	"",
	"Your methods don't work in situations like these! You've ruined the whole venture! Immediately pay us our share of ",
	" piasters and get lost! Where? I don't care! ",
	"You'd be feeding crabs with your flesh if it weren't for me, you greedy scum!",
	"I'd rather have a flagship board your old washtub. Then, you'd already be dangling from the sailyard instead of fouling up the air! ",
	"Your demands are unacceptable, and your insinuations are insulting!",
	"We never agreed to any kind of forfeit. That means I'm not going to pay anything!",
	"You know that I cannot give you battle here... Here are your piasters... Choke on them!",
	"Piasters! Well, luck's not on my side this day. I agree.",
	"Your demands are infuriating, but I guess I've no choice.",
	"Your appetite is excessive; unfortunately, I've no choice but to agree.",
	"Crap, why did I even bother with you... You ruined everything! If you don't know what you're doing, leave it for someone who does instead of dragging in others.",
	"Bah! It just wasn't meant to be. You saw it yourself.",
	"Alright, so the booty amounted to ",
	". Let's get to the splitting. ",
	"Woo, a nice score! The booty amounted to ",
	"Great work, Captain! The booty amounted to ",
	" My share is ",
	"The share for my vessel is ",
	" Your share is ",
	"No arguments here! They're loading the boats already!",
	"Yep, everything is correct... A bargain is a bargain.",
	"Your calculations are correct. I agree.",
	"My friend, you split flawlessly.",
	"You have the balls to actually demand your share? Man, I ought to string you up from the sailyard and think nothing of it!",
	"Your share? Heh, around here, it's every man for himself. If there's nothing left for you, that's your problem!",
	"I don't think that you have a valid claim for anything really.",
	"My answer is no! I'm not about to start sharing my loot with freeloaders!",
	"Well, I guess no means no. I won't argue! Goodbye!",
	"Let's not spill blood. That will only aggravate our failure! We'll have better luck next time!",
	"Well then, Captain, a man in my position can't afford to insist. I guess this is goodbye...",
	"The damage done and losses sustained by my ship and crew make it impossible for me to demand that the matter be settled fairly. Hence, I shall leave it on your conscience, Captain.",
	"Fair wind to you!",
	"And fair seas back atcha!",
	"Farewell! I trust that the fresh sea air will do you good!",
	"I hope that your failures don't make you more insufferable than you already are! Goodbye.",
	"You didn't get it! You could've bought your life with this! Grab the bastard!",
	"What, you think we're joking? Let's see if your tongue loosens up after we keelhaul you!",
	"I guess we'll have to shorten your life some, Captain. If you don't wanna do it the easy way, say hi to Saint Martin for me!",
	"You don't leave me much choice, ",
	"! I'll take what's mine, and I don't give a rat's ass about what you want!",
	"I swear to the devil, you'll pay for this!",
	"Ho-ho! Go ahead and take me, Captain ",
	"The cut will be long and deep! ",
	"You want to die now or suffer a bit first?",
	"I want nothing more to do with you!",
	"Then don't.",
	"Nice doing business with you. Best of luck!",
	"To you as well.",
	"Man, that was some battle. Too bad we didn't have any broads with us! The booty amounted to ",
	"Not bad, Captain, not bad at all! The booty amounted to ",
	" My share is ",
	" Your share is ",
	"Well, I'll be damned - it's all fair and square!",
	"Well, I'll be damned - everything's correct!",
	"Your calculations are correct. I agree.",
	"My friend, you split flawlessly.",
};
