string DLG_TEXT_BASE [53] = {
	"To be certain, ",
	", I am your captive. But I should tell you that ",
	" never ransoms his men - it's every man for himself.",
	"Uh-huh... Hmm. Well, let's see. You're no profit to me. I guess I could turn you over as a criminal in some port. I could get a few coins out of that. On the other hand, I could do with a new officer...",
	"I am your captive, but ",
	" will pay a good ransom for my freedom.",
	"We're nearing ",
	". I could land you here, if you like.",
	"I've been thinking, and decided to show you mercy. You're off the hook, ",
	"; you may go where you wish. Just so long as you're off my ship.",
	"I don't need captives - I need good slaves!",
	"Did I ask you to speak? Did I? Then shut it!",
	"I am aware of that!",
	"But, er... ",
	", I surrendered on your mercy in the heat of battle. Surely I am worthy of a better fate?",
	"What's that?! Why, your fate is in my hands now! And my hands make you a slave! ",
	"Er... Well, that's fine. Just go stay in the hold, for now.",
	"No! No! Better I kill myself right here and now, than become a slave!",
	"As you were! That's an order! Hey, someone get this pile of filth out from under my nose...",
	"Well, boys, let's show our proud owner here who this ship really belongs to! ",
	"What?! Mutiny?! As you were!",
	"I prefer to die in battle!",
	"Then I will gladly give you that opportunity!",
	"Very well. This is wretched, but there's nothing for it - I am your slave!",
	"There we are, then. Welcome onboard, my walking cargo.",
	"But, er... ",
	", we're in the middle of the ocean! Where do you expect I should go?",
	"That's no concern of mine. I told you, you're a free man. Now get out of my sight!",
	"Oh, well... That's true. How about you just stay in the hold for now.",
	"What, you intend to throw me to the sharks? This is no better than execution! ",
	"A strong man could reach the coast. It's none of my concern if you're too lily-livered to fight. Get off my ship!",
	"Perhaps you are right. You may stay, for a time.",
	"No! No! I'd rather kill myself here and now than be torn limb from limb!",
	"As you were! That's an order! Hey, someone get this pile of filth out from under my nose...",
	"Well, boys, let's show our proud owner here who this ship really belongs to! ",
	"What's this, mutiny?! As you were!",
	"I prefer to die in battle!",
	"Then I will gladly give you that opportunity!",
	"Very well, I will go. Know this, however: if we should meet again, I will have my revenge.",
	"Well, well. Perhaps I underestimated your backstroke?",
	"Oh, ",
	"... You mean to say you're letting me go without a ransom?",
	"That I am. You are free, ",
	"Hmm... Yes, good point. I'm not generous enough to throw away live money. You stay in the hold, while I mull this over.",
	"Thank you, ",
	"All right, begone - afore'n I change me mind, arr and blazes and whatnot.",
	"A criminal? You must be joking, ",
	"! Serve you? Why, I should rather feed the sharks!",
	"Well, keep your yappin', and you may just get the chance!",
	"An officer, ",
	"? Perhaps I should agree, as it seems I have little other choice!",
	"Done! Start your duties immediately.",
	"What do I need with you? I've got a full set already.",
};
