string DLG_TEXT_BASE [113] = {
	"Glad to see you again.",
	"I require your services once again.",
	"I'm already gone.",
	"I have a question for you concerning the Dutch West-Indian company.",
	"Hm, excuse me for my forgetfulness. It's about the Dutch West-Indian company again.",
	"Allow me to introduce myself, I am the person who can pass the right word about you  to the desired governor. For a payment, naturally, but believe me, my services are of the highest quality, and you won't regret taking advantage of my talents.",
	"Very interesting, do continue...",
	"Perhaps, another time.",
	"Let's see how can I help you.",
	"I wish to reconcile with England.",
	"I wish to reconcile with France.",
	"I wish to reconcile with Spain.",
	"I wish to reconcile with Holland.",
	"I wish to reconcile with the smugglers.",
	"I need a privateer patent.",
	"Have you got any trading licenses?",
	"I've a question concerning the governance of settlements.",
	"You know what, I think I'll manage this on my own.",
	"Always available, for various terms. What trading license are you interested in?",
	"England",
	"France",
	"Spain",
	"Holland",
	"You know what, I think I'll manage this on my own.",
	"For what term?",
	"30 days",
	"60 days",
	"90 days",
	"Hold on, I've changed my mind.",
	"So, a trading license from ",
	" for the period of ",
	" days, the price is ",
	"Suits me.",
	"Hold on, I've changed my mind.",
	"Here's your document. You must sail into ports under a friendly flag. Remember, a patrol may check if the license is expired.",
	"Thank you.",
	"Excellent! Let me know when you will be in possession of the necessary sum.",
	"Um. Sure, okay.",
	"Magnificent! For this you must prove your devotion to the country",
	" with faultless service. Go see any governor",
	" and complete a number of his tasks. After that he will grant you a patent.",
	"Tell me, ",
	", is it possible to somehow bypass this formality? ",
	"Farewell, ",
	"You mean to bribe an official!? You want me to personally give you a patent?",
	"Precisely!",
	"No. Good bye, ",
	"At present I have no connections that would let me to obtain a blank form for a patent with all the seals and signatures.",
	"It's a pity. Farewell, ",
	"Very well, I can arrange that. What patent do you need?",
	"England",
	"France",
	"Spain",
	"Holland",
	"You know what, I think I'll manage this on my own.",
	"An obvious bug, if seen - inform ALexusB",
	"A rather good prospect. I agree to your terms!",
	"Holland is an almost peaceful country, you will have many friends and few enemies. And the patent itself will cost you only ",
	" piasters.",
	"A rather good prospect. I agree to your terms!",
	"The friends and enemies of France will become yours. You will be able to sink the ships of enemies. And the patent itself will cost you only ",
	" piasters.",
	"An excellent prospect! I don't give a damn whom to serve! Might as well be the French!",
	"Spain has a lot of enemies, and they will become yours straight away! The Spanish are a nation of sea warriors. The patent will cost you only ",
	" piasters.",
	"You're the only one who's offering me something worthwhile! Take these pity pennies for the spirit of bloody fights and new tasks of high-ranking people!",
	"To be fair, the governor general of England fills his pocket this way. And the patent itself will cost you only ",
	" piasters. ",
	"I don't mind giving him my own money that was obtained from smuggling and piracy!!",
	"No, that's not for me!",
	"I am glad that we reached an agreement. It's a deal.",
	"Farewell, ",
	"Very well. This will cost you ",
	" piasters.",
	"I agree.",
	"I think I've changed my mind.",
	"Excellent, I will make sure it's all done. They will deal with you.",
	"Thank you.",
	"Hmm... I don't really know what to say. I certainly can satisfy your request for reconciliation with ",
	", but it will cost you ",
	"I probably don't have a choice, anyway. So here's your money.",
	"No, that's too big a sum. Farewell.",
	"Excellent! It is surprisingly easy to do business with you. Be assured, no later than 15 days from now your issues will be resolved.",
	"Um. Sure, okay.",
	"A petition for you has already gone forward. You must wait, business isn't done that fast.",
	"Thank you.",
	"The governance of which settlement do you wish to discuss?",
	"No. Nothing.",
	"The city of ",
	", belonged to ",
	", the ransom to stop the attempts to recapture the settlement will be ",
	"Yes, this suits me.",
	"No, thanks. Not interested.",
	"Very well, the information about our deal has gone away. The attempts to recapture the city of ",
	" will stop.",
	"Thanks. Good bye.",
	"One more question.",
	"Hmm, I say... Captain, why on earth are you interested in this office?",
	"I am carrying out an order for them, and there are questions.",
	"And why do you think that I know where they are?",
	"All right, quit playing around! Where do you get the licenses of this company?",
	"From a representative of the company here in Caribbean sea. By the way, what is his name? If you do business with him, you should know.",
	"oliver",
	"trust",
	"Hm, indeed... Fine, then - you can find him on San Martin, in Marigo. He has a room there in a two-storey house. But please don't tell him it was me who sent you. Just in case, you know...",
	"No problems.",
	"Oliver",
	"Trust",
	"You don't know anybody, so get out!",
	"Damn, I can't remember it...",
	"Well, what do you want from me this time?",
	"I remembered the name of the Dutch West-Indian company representative!",
	"Oh?! Well, so what is his name?",
};
