string DLG_TEXT_BASE [39] = {
	"You'd better go away from here, ",
	". There's nothing for the likes of you in the governor's house...",
	"Leave, you bandit! How did you ever get in here?..",
	"Oh, what awful times have come. Such scum wandering around the house of the governor of ",
	"Watch it, foolish woman...",
	"Mind your language...",
	"Hello. I serve the governor. My name is ",
	"I am cleaning this room, ",
	"You know, ",
	", our governor is a good man, and he pays his servants rather well...",
	"Very good.",
	"Hm, marvelous..",
	"Oh, what's this here?! And I'm walking around like a fool without noticing... Guards!",
	"Get off me...",
	"Get out of here, you bastard!",
	"Be gone from the governor's house immediately, you rascal!",
	"I don't care what you need in the house of the governor of ",
	". But I'll give you an advice - get out now!",
	"Easy there, sweetie...",
	"Be careful not to choke on your words!",
	"Hello. I am a servant of the governor. My name is ",
	"I keep everything in order here, ",
	"You know, ",
	", our governor is a good man, and he pays his servants rather well...",
	"Very good.",
	"Hm, marvelous..",
	"Thinking about robbing the governor, aren't ya?! Guards, seize the thief!!",
	"Shut your mouth...",
	"You'd better be leaving this place, pal...",
	"Get lost!",
	"Did you enter the wrong door? This is the house of the governor of ",
	". You'd better leave!",
	"I will leave when I want to!",
	"Don't poke your nose into other people's business...",
	"I've been put on duty to the governor today. Nice place here...",
	"I am guarding the governor's house, ",
	"My task is to protect the governor's house.",
	"That's good.",
	"Hmm, I see...",
};
