string DLG_TEXT_BASE [120] = {
	"Hey, you lost something here, pal?",
	"What do you want here?!",
	"Relax, lad, I brought the goods!",
	"Lost your eyes? I delivered the goods!",
	"I'm here under the orders of the governor of ",
	"! I order you to lay down your arms and follow me, you're arrested!",
	"Ah, at last!!! Here you are, we've been getting worried about you. Let's go, we're sailing away.",
	"Hurry up, there're patrols everywhere. We must get out of here fast!",
	"I'm here under the orders of the governor of ",
	"! I order you to lay down your arms and follow me, you're arrested!",
	"And who're you? We agreed to deliver one passenger, not a crowd.",
	"Oops...",
	"Who're you? We agreed to deliver a passenger, not a captain.",
	"Get out! Don't come back till you get rid of your ship.",
	"Ah, damn...",
	"A patrol! We don't know you, you don't know us.",
	"Yeah, well...",
	"Thanks for the help. We won't forget it. Let's move out.",
	"Well done! You fought well. Let's go.",
	"I'm already gone.",
	"It has been ",
	" days have passed.",
	"Smugglers' ship deck.",
	"A patrol! We don't know you, you don't know us!",
	"Exactly!",
	"Hey, get away from here! You ruin our deal, and we'll let your guts out!",
	"You dare to threaten me, dog?",
	"You'll choke on those words, scoundrel!",
	"Ah, I know how it is. Business is business. 'Til we meet again.",
	"On your back, right? Where's your ship?",
	"First I wanted to make sure there'll be no dirty tricks.",
	"Didn't want to risk the ship. I prefer to have a look with my own eyes first.",
	"The deal is cancelled!",
	"We're honest people, and don't live by deception. Bring your ship, but be careful - make sure you don't bring a coastal patrol with you.",
	"Very well. Wait for me here.",
	"Cancelled? Are you kidding me?",
	"I'm absolutely serious.",
	"Well fine, then. We've done some good business even without you.",
	"Exactly!",
	"Scumbag! You can't fool us like that! For this you'll pay with your head!",
	"I don't think so!",
	"You won't get away with this!",
	"Go and bark somewhere else, dogs!",
	"You'll regret that!",
	"Well-well!",
	"metro",
	"Now you'll pay for trying to fool us!",
	"Then you all die. I have precise orders - in case of resistance, don't take anyone alive!",
	"Well what are  you doing here? You've got nothing for sale! Everything you have in your hold is available in the city!",
	"Bad luck.",
	"Well-well... perhaps, we will take your goods free of charge. I don't think you'll run to the authorities with your complains.",
	"Well, try!",
	"So, what cargo did you wish to sell?",
	"What're you selling?",
	"I think I've changed my mind.",
	"I think I've had enough.",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"? The price is ",
	" gold for ",
	" unit. Let's have a look at how much cargo you've got.",
	"Let's look.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"Cargo: ",
	"ÿ Amount: ",
	" units. The price is ",
	" for ",
	" unit. How many are you selling?",
	"All I've got.",
	"Let's say half.",
	"A tenth.",
	"No. Perhaps, I will look for another buyer. The deal is cancelled!",
	"In total: ",
	" units for ",
	" gold. Deal?",
	"Yes, of course.",
	"No. The deal is cancelled!",
	"In total: ",
	" units for ",
	" gold. Deal?",
	"Yes, of course.",
	"No. The deal is cancelled!",
	"In total: ",
	" units for ",
	" gold. Deal?",
	"Excellent!",
	"I don't like the sum! The deal is cancelled!",
	"Bad luck? You agree to a meeting, and then simply say 'bad luck'? Get out of here. I'm not sure we'll want to deal with you in the future!",
	"We'll see if I will want to deal with you!",
	"Money's yours, goods are ours! Selling anything else?",
	"Yes, let's have a look.",
	"No. Thanks, that'll be enough.",
};
