string DLG_TEXT_BASE [25] = {
	"Wake up, ",
	"! We've finally reached ",
	" after all these storms!",
	" What're you going to do? I mean, you haven't got a ship anymore.",
	"Not the first time! Luck tends to change a lot.",
	"Are you offering me work, Abraham?",
	"I hope you'll have more luck than with 'Mercury'. Farewell.",
	"No doubt about it. Farewell, captain!",
	", I'm a smuggler, not a city mayor. What work do you expect from me?",
	" Drop by the tavern to see Ines. She knows everyone on this island.",
	" Go see Jurkens, he's kind of like a pirate governor here. But first talk to ordinary pirates.",
	" Borrow some money, sell something. I'm not to teach you what to do.",
	"All right, thanks for the advice. Farewell.",
	"You know, Abraham, perhaps I shall requisition your ship. I liked it very much!",
	"You're jokes are bad, pal.",
	"Don't take in close to heart, old man. Farewell!",
	"Who says I'm joking? You'll tell the crew that you sold the vessel to me. And I will spare your life. Deal?",
	"They were saying you killed your teacher Malcolm Hatcher for a lousy saber. Didn't believe it, seems I've been wrong. Today you will feed the fishes. You don't have a chance, pal.",
	"Really?!",
	"Oops...",
	"We were thinking here, perhaps it's worth selling you to the mines. Hah... Some more money never hurts.",
	"What're you saying?",
	"We've arrived to the destination, farewell.",
	"Bye.",
	"I was thinking here, I like your ship. I'd like to have it for myself.",
};
