string DLG_TEXT_BASE [35] = {
	"It seems to me there's something illegal going on here.",
	"In the name of ",
	", stop breaking the law now!!!",
	"Oh no, officer. We're just relaxing by the sea with friends.",
	"I'm giving away gold. Would you consider this illegal?",
	"Be gone, martinet. It's none of your business!",
	"Don't try to fool us, captain ",
	"! And who would've thought that a positive and respected person such as yourself would be smuggling!",
	"Alas, we all make mistakes. But I already repent it!",
	"I'll cut your head off right now!",
	"Since I only heard good things about you, I'm letting you go this time. But we'll take these bastards with us!",
	"I thank you, officer. Good bye to you!",
	"What are you telling me! I'm not blind! Follow us, you're arrested and the goods are confiscated!",
	"I'd rather let your guts out!",
	"Really? Well of course, this is absolutely legal... If we get our share, that is. So how much are you giving in one hands?",
	"I think ",
	" piasters will be enough.",
	"How about ",
	" piasters?",
	"For you, officer, I'm ready to part with ",
	" piasters!",
	"Aha, offering a bribe? Oh no, I value my dignity above money! Please, follow us!",
	"Curses! I don't want to disappoint you, but you'll hardly go anywhere right now!",
	"I'll accept your donation with pleasure. Since you're being so charitable.",
	"Always at your service.",
	"I'll accept your donation with pleasure. Since you're being so charitable.",
	"Always at your service.",
	"I'll accept your donation with pleasure. Since you're being so charitable.",
	"Always at your service.",
	"But... Oh, devil... I should arrest you!",
	"Arrgh! You still here? Bored of living, aren't you?",
	"I... I will complain! I won't leave it like this...",
	"Pff!",
	"Alright, you dog! Now you're really getting it. You'll die on this coast!",
	"Try proving your words, windbag!",
};
