string DLG_TEXT_BASE [65] = {
	"What do you want, captain? I don't know your name and can't tell you mine.",
	"I'm Captain ",
	"What've you brought this time, captain?",
	"Say what you want, pal, and make it fast? Cause, you know, somebody's chasing you!",
	"Don't hesitate, state your business right now! With soldiers on your tail, it's not a good time for long conversations, you know...",
	"I brought some goods for sale.",
	"About the trip...",
	"I need to get somewhere.",
	"Nothing. See you again.",
	"What can I do for you, captain?",
	"I wish to sell something.",
	"I need to get somewhere.",
	"Nothing. Good luck!",
	"Hm... Why me? You probably came into the wrong door, captain. Go to the shop - they'll happily buy whatever you brought.",
	"I'm afraid it's you I need.",
	"Thanks for your advice. Good bye.",
	"What for?",
	"I wish to sell something that no merchant on this island would buy.",
	"Sorry, lad, we've got some business already. Come back in a couple of days.",
	"That's too bad...",
	"Perhaps you should finish one task before taking another one?",
	"Perhaps, you are right.",
	"I know, you're a trustworthy fellow. We'll be waiting for you in a place called ",
	"Hm... Perhaps, we could find a buyer. We'll be waiting for you in a place called ",
	"Very well. See you again.",
	"No more deals today. Come back tomorrow.",
	"Um. Sure, okay.",
	"And after all this you think that someone will want to work with you? You should be glad we haven't sent assassins for your head yet. Beat it!",
	"Oh well... it seems I'm not destined to become a smuggler.",
	"No more deals today. Come back tomorrow.",
	"Um. Sure, okay.",
	"Sorry, lad, we've got some business already. Come back in a couple of days.",
	"That's too bad...",
	"I thought we reached an agreement already?",
	"Yes, precisely!",
	"You brought the money?",
	"Yes.",
	"I changed my mind....",
	"Not yet.",
	"I already told you everything.",
	"Precisely.",
	"I changed my mind....",
	"Can't help you today. Come back in a couple of days, I might have something.",
	"A pity.",
	"Well then, we can bring you to a place called ",
	" near ",
	" for ",
	" gold. Bring the money in ",
	". The ship will be waiting for you in a place called ",
	" for exactly one day.",
	"Very well, that suits me.",
	"No, thanks.",
	"Can't help you today. Come back in a couple of days, I might have something.",
	"A pity.",
	"And after all this you think that someone will want to work with you? You should be glad we haven't sent assassins for your head yet. Beat it!",
	"Oh well... I guess I'm missing out this time.",
	"No, we won't take you.",
	" Not that I really needed it!",
	"Why do you need your ship, then? No, we're not doing this.",
	"I guess I'm missing out on this one...",
	"Well, as you have it...",
	"Pleasure to do business with you. The ship awaits, don't be late.",
	"I'll try not to.",
	"It seems you're down on cash.",
	"A pity, I'll come back later.",
};
