string DLG_TEXT_BASE [313] = {
	"The alarm has been raised, all through the city. Everyone's out looking for you! I really wouldn't hang around here.",
	"Look, the city guards are out in force for your hide. I'm not about to stand around flapping my gums with you.",
	"Better run, buddy, 'fore the soldiers make mincemeat out of you...",
	"What do you want, scoundrel?! The city guards are already on your tail. You won't escape, you dirty pirate!",
	"Filthy murderer! Out of my house! Guards!",
	"I'm not scared of you, villain! You'll be hanging at the fort soon! You won't get far...",
	"Eh, I'm used to alarms by now... ",
	"I'd like to see 'em catch me!",
	"Shut your trap, ",
	"or I'll rip out your rotten tongue!",
	"Heh. It never changes, does it. ",
	", and still after pirates! Here, bud, tell you what. You sit real quiet, and I'll let you live...",
	"G'day, Doctor Blood. Would you mind helping me in a particular affair? Of course, you will be compensated generously for your time. ",
	"What kind of affair is that, then?",
	"Hey, Doctor Blood! ",
	"Great to see you, Peter Blood.",
	"It's good that you've come around to see me, ",
	". Pray, how is Colonel Bishop?",
	"Ah! Alas, ",
	", I am on my way out. Next time, perhaps.",
	"I have some business for you.",
	"Have you brought me my fifty thousand?",
	"Not yet. I'm working on it. Keep your shirt on.",
	"I'm afraid I can't help you in this affair. Consider this my refusal.",
	"Yes, I've got your fifty thousand. That's why I'm standing here. ",
	"What ho, you are just in time! I have a task for you.",
	"I'm listening. What's the matter?",
	"Hello, ",
	". How may I help you?",
	"Oh, you again? Welcome back, ",
	" What do you want this time?",
	"Hm. Back again, ",
	"... Well, the umpteenth time is nearly as fond as the first. What do you want?",
	"Ah, my dear ",
	". You couldn't possibly imagine how obtrusive some of my clients can be. Some of them barely give me time to think. Pray, what is it that you need?",
	"Nothing much. I just swung by for a chat and a look around. ",
	"Yeah, here I am again. I just wanted to talk about something.",
	"Ho! Yes, it is I once more - here to while away the hours and regale you with my company.",
	"Indeed, the life of a moneylender is a hard one... Oh, I don't need anything; just wanted a chat...",
	"I will get to the point quickly, let's talk about money...",
	"I need some information... I mean, I've got a question for you.",
	"Listen, you should have received a deposit in my name.",
	"I need to withdraw a deposit of one million piasters.",
	"I'm here on orders. Man by the name of ",
	" sent me. I need to take something...",
	"I've heard that you hired John Avery.",
	"Listen, did you hire John Avery?",
	"Rumors has it, you and John Avery had some problems...",
	"Listen, did you take on John Avery for some tasks?",
	"I'm looking for John Avery. Did he come by here?",
	"I heard of your misfortune. Perhaps I might help you?",
	"I tracked down your ",
	". Here you go.",
	"I did, and he's done the task admirably. However (ho ho), they say the tavern got him so wet that he mistook a local drunk for my debtor.",
	"Did he say where he was going? Perhaps to some other lender in need?",
	"Not my place to know. I've no interest in the problems of others.",
	"No, of course not. But perhaps he mentioned something in passing?",
	"I think he was going to head for the Spanish, north of the mainland. Where exactly, you've got me. Though hang about, he did say something about ",
	". You understand, I can't promise reliability.",
	"Yes, I get you. Thanks all the same.",
	"Ih... Not problems, as such...",
	"Hm. So you hired him?",
	"That I did. He did his job, and I got the debt in full. Thing is.. afterward, in the tavern, he started to blow his gob about how he pulled something over on me. He said my debtor gave him far more than he should have, and he was ever so proud for keeping his mouth shut around me.",
	"Personally, I don't understand where the deceit is supposed to be - or why everyone seems so amused by this story! Of course, I do have my regrets. Had I known earlier that the debtor was so well-off... ",
	"Anyway, when John Avery sailed far away, I graced him with a sigh of relief. I hoped and assumed that would be the last I heard of him!",
	"I see. And I guess you have no idea about where he went...",
	"I think that scumbag went over to the French. I managed to overhear him in a brothel. I was there on business, mind, not for the services...",
	"My good man, I don't care what you did there. But thank you for the dish on Avery.",
	"John handles some orders for me, time to time. In fact, he just did one recently...",
	"And where might he be now?",
	"Oh, God knows. See, John's a good hand, but he's got the poorest temper. Recently he killed a poor bugger in our tavern, may God have mercy. So I don't ask John what I don't need to know. ",
	"Understandable. But do you have any notion where he might go?",
	"Well, if you want my opinion, he probably made off for ",
	"Hm. Are you basing that on anything in particular?",
	"Well, thing is, not long ago some wonder schmuck robbed the moneylender in ",
	".",
	"Oho, I see! Well, gargantuan thanks to you.",
	"No, no, thank you. I don't need any more help. I hired John Avery only yesterday - the best in this business, don't you know! Oh, don't take offense; you're one of the best, too. It's just, first come, first serve, you know? You.... Uh. Sorry, you said your name was?",
	"Yes, yes, I've heard of you. I... think. Er... So what was I saying? Ah, yes. Well, can you imagine, this thug rushes in, puts a knife to my throat, and starts to rob me! Me, a gentleman! In broad daylight, even...",
	"Sorry to interrupt, but who are you talking about?",
	"... never have I lost so much - what? The robber, of course! Ah, my money! My poor money... Well, John Avery will show him - just you wait! Avery is strength! Power! Oh, and he had the gall to suggest my arm was too short to reach him on Bermuda...",
	"Who, Avery?",
	"What's wrong with you? Why Avery all the time? The robber, of course! My good man, why do you keep interrupting me?!",
	"I'm sorry. And if I, instead of he, bring you what was stolen? Would that upset you much?",
	"Well, er... Um... Frankly, I don't care where the money comes from - but mind, you deal with Avery yourself. Whatever goes on between you is none of my business.",
	"No problem. I won't drag you into my quarrel with John. So what kind of sum are we talking about?",
	"Fifty thousand! If you bring it all back, your reward will be one-tenth of that - five thousand.",
	"What's the bandit's name?",
	"You think he introduced himself?! Have you know a thief to be so polite? You know, John never asked me questions like that.",
	"Swell. It's a deal! You wait here; I'll be quick!",
	"That's no good. I am very disappointed with you. I sense you're holding back on me... Well, be that as it may.",
	"Indeed! Everything is quite fine, my friend.",
	"Damnation, what a mercy! Tell me, what happened to robber bastard?",
	"No less than he deserved. He won't bother you again.",
	"Excellent! Well, then I am ready to count my money. Let us begin, shall we...",
	"There you go.",
	"Excellent! Simply marvelous! Everything is perfect. Here is your five thousand, just as we agreed.",
	"Thank you...",
	"Well, I am always glad to entertain you. Also, I must say that I shall tell everyone of your swashbuckling honor and valor. You've proved that impudent Avery fellow no match for you. Clearly you're the better man...",
	"Oh, now you're making me blush... Well, sounds good. Farewell!",
	"Let's discuss this. I shall attend carefully.",
	"Have you any affairs in need of... external aid?",
	"It's about the debtor.",
	"It's about the credit delivery.",
	"Here's your credit.",
	"I owe you ",
	". I am ready to repay the debt.",
	". And now I am ready to repay you.",
	". And the time has come to pay it all off.",
	"I wish to borrow some funds.",
	"Look, I need some money...",
	"How about a small line of credit?",
	"Mind if I leave some gold with you, for a rainy day?",
	"Will you hold some pirate loot for me?",
	"Mind if I leave some gold with you, for a rainy day?",
	"I want to withdraw my investment.",
	"It's time to make a withdrawal. ",
	"I need my gold, and whatever interest has built up.",
	"I know I took some credit with you, but I'm not ready to repay it yet...",
	"I know that I owe you, but I don't have anything on me right now. Oh, I'll be back. Don't worry...",
	"Look, I know that I owe you, but I don't have enough money right now. I'll get to it, don't worry. ",
	"Whoops, my mistake. I've got no business with you. Farewell.",
	"You're ",
	", aren't you? Your name is associated ",
	"with some truly awful rumors",
	"with some less than pleasant things",
	". Me, I want naught to do with you.",
	"Yeah, that's right... Stumble just once, and suddenly people start with the spitting.",
	"Fine!",
	"No, fortunately I'm fine.",
	" which is in ",
	"Yes, you're just in time. I've got a delicate issue that needs addressing. ",
	", who lives in ",
	", owes me ",
	". Bring me the sum in full, and the interest is yours. Right now, that will come to ",
	"I'll do it!",
	" which is in ",
	"I need a trustworthy man, for a vital mission. I need to deliver credit - ",
	" chests of gold - to ",
	" - for a person called ",
	". He's the local ",
	". For the effort, I can offer you ",
	". Mind, this needs to be done within ",
	"I am ready!",
	"I told you all there is.",
	"Sorry, it's getting pretty late.",
	"Excellent. Be fleet of... fleet? Hmm. Well, be on your way.",
	"I won't fail you!",
	" which is in ",
	"I'm all ears.",
	"The task... is done!",
	"I found your debtor, but couldn't shake anything out of him.",
	"I found your nut, but couldn't crack 'im.",
	"I decided this debtor business ain't for me. So never mind! ",
	"No. Nothing.",
	"That's good!",
	"Please!",
	"Excellent! But where is my money? The clock is ticking, sir!",
	"I'm working on it!",
	"Bad show, I must say! When I hire you, I expect you to do the job you're assigned!",
	"This person really was destitute, but you are right. That is my job.",
	"Don't you try to fool me! I know you spoke to him. Hand over my money!",
	"Whoop. Yes, so I did. And here it is. Happy? ",
	"But he totally refused to pay!",
	"I don't have the time now. I'll swing back later.",
	"Poor show. You know I was counting on you.",
	"Yes, you're right. But hey, what can you do.",
	"You have already shown your fickle relationship with the truth. Return my money!",
	"Yes, quite right. Here you are. ",
	"Hmm. Is that so?",
	"Of course!",
	"Truly, I am counting on you.",
	"I won't fail you!",
	" which is in ",
	"Lay it on me.",
	"Look, I'm not really cut out for this delivery gig. I quit. ",
	"No. Nothing.",
	"Bad show. I was counting on you.",
	"Yeah, well. Such is life.",
	"Perhaps I may let you off the hook, if you return me all the chests.",
	"I'll be back, then.",
	"No, can't help you there. In such a cauldron as this, all I can offer is banking services.",
	"All right, how much are we talking about?",
	"I have no interest in that.",
	"You're ",
	", aren't you? I've heard your name linked with some ",
	"truly awful deeds",
	"rather unpleasant rumors",
	". I want no business of yours.",
	"Yeah, that's right... Stumble just once, and suddenly people start with the spitting.",
	"Fine!",
	"Oh, any time. What sum do you require?",
	"A pittance, really.",
	"You might want to hold your breath.",
	"The more the merrier. As they say.",
	"Excellent. Smaller sums are far less of a bother. I can offer you ",
	"Sounds good. What kind of interest are we looking at?",
	"Hum. That's not quite what I'm looking for. Can we do this again? ",
	"Actually, I'm better off without any debt right now. Goodbye.",
	"Not a problem. I hope that ",
	" will help while away your problems. It is quite a handsome sum.",
	"Sounds good. What kind of interest are we looking at?",
	"Hum. That's no good. Can we change it? ",
	"Actually, I think I'd rather not go into debt. See ya 'round.",
	"Well... It gives me some pause, but all right. I am willing to grant you ",
	". As you understand, Captain, this is a lot of money. I ask that you be quite serious in this deal.",
	"Fine, of course. What kind of interest are we looking at?",
	"Hum. That's no good. Can we do this again?",
	"No, I don't need any debt right now. Thanks, though. ",
	"% each month. From what I gather about you, that's the best I can offer you at the moment.",
	"That suits me just fine. Now we just need to discuss the terms.",
	"I think I'd rather not get into debt. Goodbye.",
	"Judging by what I know about you, ",
	", I will await your return in ",
	". After that, as you understand, I will take whatever necessary measures.",
	"Fine. I am pleased to accept your conditions... And your money.",
	"Ah. Well, a shame we couldn't come to an agreement. Goodbye.",
	"Well, I am sincerely pleased. But I must warn you, I've been in this business for a long time. I know how to get a return on my investments. So if you have even the slightest thought of defaulting on me, think again.\nOf course, I don't wish to offend you. I just need to make myself clear. ",
	"Hm... All right, then. Goodbye.",
	"As you wish... But mind, the interest is compounding. And your time draws near. ",
	"Don't worry. See you soon.",
	"Oh, that's simply wonderful! If ever again you need some money, I am at your service.",
	"I thank you. It pleases me to do business with a serious man, who may actually repay me in time. Oh, the life of a businessman...",
	"Oh. I see I was right to put my confidence in you, ",
	"! I hope this is not the last time we shall do business together!",
	"I wish to borrow some money.",
	"Look, I need some money...",
	"How about a small line of credit?",
	"Mind if I leave some gold with you, for a rainy day?",
	"Would you be a dear and hang onto some loot for me?",
	"Mind if I leave some gold with you, for a rainy day?",
	"Goodbye, ",
	"Ho! A man of reason, I see! So how much are you prepared to invest?",
	"Good. Believe me, your nest egg will be waiting for you, safe and sound, when you return. With interest, even... Oh, incidentally, how much are we talking about? ",
	"I see you grasp how this life works. How much do you wish to entrust to me?",
	"Surely you jest?",
	"Whoop, sorry. My mistake...",
	"Hum. Let's not play games here. I can't accept phantom funds. ",
	"Hm... Fine, then.",
	"Good. For such a sum, I am prepared to offer a rate of... er, let's say... ",
	"%. Per month, of course.",
	"Suits me.",
	"Hmm. Perhaps I'd best make an amendment, then.",
	"Actually, I'm kind of loath to part with my cash right now. Nothing personal. See ya!",
	"Unfortunately, I can't guarantee the safety of such a large sum. I already have ",
	" of your money, so the most I can take from you is ",
	"A pity. I'll have to ask some other moneylender.",
	"Now you can be assured that even the most callous of storms won't leave you destitute. You may choose to withdraw the deposit at any time.",
	"Good. Bye, then.",
	"Going by our agreed-upon rate, and accounting for the time that has elapsed, I appear to owe you... ",
	". Are you sure that you want to withdraw all of this?",
	"Absolutely. Hand it over.",
	"You know, you're right. Might as well let it mulch a little longer. See ya later, booksome!",
	"Oh... I'm kind of disappointed to part with it. Somehow I had already got used to its company. Well, nonetheless, come back some time.",
	"If I need to, I will. Keep dry!",
	"You're still alive? I must assume you want to return my money? Well, I'll tell you where you can deposit it! Thanks to you, I've lost such a sum that you won't see in a lifetime! I shan't find peace until I see your lifeless cadaver, spread before me on a plinth!",
	"I was just about to settle our affairs peaceably. ",
	"Well, let's see what you have for me! Keep in mind that I have no compunctions toward you. ",
	"Is that a threat? Really? Well, let's see what you can do!",
	"Good lord, there are more important things in life than money. There's no use killing yourself over it. Or me, for that matter.",
	"Get out of my house! Get out of my sight! Get out of my life!",
	"Oh, really. What do you propose?",
	"As of today, I owe you all of ",
	". And here it is. ",
	"Just to patch things up, I'm prepared to return you the whole ",
	"That's more like it! You are not such an impossible cause, after all.",
	"Thanks. I don't plan to cause you any more problems, believe me. ",
	"diamond",
	"ruby",
	"emerald",
	"sapphire",
	"You know, I've been hit with a disaster of the highest order. I have lost a ",
	" of the finest quality. That would be bad enough, but my real problem is that the stone is not mine!",
	"Well, so what? Just buy another ",
	", and be done with it.",
	"If it only were so simple! The problem is that this ",
	" is... shall we say, unique. I was entrusted this stone for setting in a ring, and I simply cannot find a stone of like size and brilliance...",
	"Oh, I'm beginning to see your problem. So where do I come in? ",
	"Find the ",
	", of course!",
	"All right... Um. Where did you see it last? ",
	"In the jungle, right outside the city. Sometimes I like to go for a stroll there. The silence calms my nerves...",
	"You know, I'm not a tracker or a footman. I've got better things to do than hunt down everything you've mislaid.",
	"Hm. Well, I am prepared to take a look. What are you offering, for my time?",
	"Oh. Well, that's a pity. Perhaps I was mistaken about you. I do beg your pardon...",
	"No skin off my nose.",
	"If you do find the ",
	", believe me, I will pay you generously! Note that time is not a particular factor here.",
	"Oh, that's something at least. All right, I'll go take a look. Don't go too far. ",
	"The stone is in the location ",
	"Marvelous! Yes, yes, this is it. It's the very same ",
	"! Well... Well! Well, I am happy. Very happy. Here, I said I would pay you well, and pay you I shall. ",
	"That's nice to hear.",
	"Thank you once again. You are welcome to come to me any time of day. I will always be happy to listen to you.",
	"Thanks, really...",
	"I give nothing, sir, to the Colonel's live property.",
	"Nevertheless, you have done so.",
	"What? What are you talking about?",
	"Steady on. I brought you your loan from the old gunner Ogle. Exactly five thousand.",
	"I'm talking about the loan you gave to the old gunner, Ogle. Exactly five thousand. I am prepared to pay his debt.",
	"Ah... Oh. I, er, thank you, sir.",
	"All the best.",
	"You brought me money for Ogle?",
	"Quite right.",
	"Unfortunately, no. But soon!",
	"Early this morning, a certain townsman took out a loan with me. Nothing unusual there. The problem is... he deceived me. He gave his name as Raphael Guinness, a man who quite often comes here. To his credit, he was a fair likeness. I gave him a loan of thirty thousand piasters, and thought no more of it - but then Raphael himself stopped in...",
	"So you want me to hunt down this imposter? What makes you think he's still around here? ",
	"Oh, he is in the city, I assure you. No ships have sailed yet today. I can offer you ten percent, as a reward. That's three thousand piasters. What do you say?",
	"You know, perhaps I will help you.",
	"Don't count on me, mac.",
	"Well, did you succeed?",
	"Yes, here's your money - minus my ten percent, of course.",
	"Not yet, I fear. Hang on, though. I will, presently!",
};
