string DLG_TEXT_BASE [53] = {
	"I asked you to wait for me upstairs. You shouldn't lurk around here. Don't go attracting attention to yourself...",
	"All right. Don't mean to compromise you...",
	"I'm new here, so please don't give me too much strife. I ain't yet accustomed to the new establishment...",
	"Where's the girl that used to work here? ",
	", I reckon...",
	"Come again, darlin'. Time allowin', we'll have us more of a right rumpus...",
	"Certainly! Rumpus it is.",
	"I don't know you. Get out of my face...",
	"Where's my money?!",
	"Sorry, handsome, I'm a busy lady. A good day for the bar ain't always a good day for the gob!",
	"Hang about, Captain. Don't go startin' no uproars in here! I ain't aiming to clean up after you!",
	"I... ahem... I didn't really intend to.",
	"Oh, Captain! How's today for a right big squeeze? I don't fully like to brag, but...",
	"Alas, I am in a hurry now! Another time!",
	"I'll keep 'em warm, gorgeous!",
	"You mean t' order somethin', go hit the owner. Over at the bar.",
	"Yeah... Thanks for the tip.",
	"You want a decent rest and get your muscles back where God means 'em, you go rent yourself a room. Won't do you no good, hanging around the hall all night. ",
	"I'll consider it. Thanks.",
	"Hey, scrumptious - tell me, you seen anyone queer hanging about lately?",
	"I want to ask you a couple things. ",
	"Then listen up. Get yourself a room upstairs. You go wait there, and when no one's lookin', I'll slip up after you. Might take a while...",
	"Hah! Whatever you say, my jampot! I'll be waiting!",
	"Don't work here no more. Just up and left. 'Scuse me, I've got work to do.",
	"Er. All right...",
	"Listen here, horndog. I don't know where your frickin' money is! And if you keep ridin' my ass, I'll scream bloody murder and you'll be in a piss-stained cell before the day is out!",
	"All right, no need for all that. So I'm an idiot, okay?",
	"Damn straight you are! Didn't your momma lean you no respect? Lord alive, the men that come in here...",
	"Oh well. I do my best...",
	"You awake?",
	"Mrmn...",
	"How's your head, sunshine? ",
	"Mrahm... Dammit... The hell am I? Nghh...",
	"Y' don't remember? You were robbed, you know that? ",
	"What?! Ahk... my head... Whuh... Who'd do a fool thing like...",
	"How the hell should I know? They marched in here like God on fire, wavin' their things around. They stuck their hands in your pants, then ran off. None of my business, of course...",
	"Well, what's gone is gone.",
	"Dunno, really... Queer sort. Though, wait, there was this one guy... Looked like your average townie, but was a real twerp with his questions. I ain't seen him afore. You won't hardly find him here, but might catch scent a' him around town...",
	"I already told you all I can! What more you want?",
	"What you think you gonna get, milkin' me like this? ",
	"Look, is there something else you need? ",
	"Thanks aplenty, sugar pie. I'm off to repay some lumps. ",
	"Really? Well, er... All right, then...",
	"Well, you know...",
	"Sorry, lambchop...",
	"Odd's a relative thing 'round her. But no, ain't seen no one I'd call real special. ",
	"Oh. Well, I already done told you what I could. And I can't likely say more than that!",
	"I already told you all I can! What more you want?",
	"What you expect me to say now? Look, is there something else you need? ",
	"Thanks a bundle, trundlelumps. I'm off to look for a man.",
	"Really? Well, er... All right, then...",
	"Well, you know...",
	"Sorry, muffin...",
};
