@set allusersprofile=c:\programdata
@set appdata=c:\users\espkk\appdata\roaming
@set asl.log=destination=file
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=desktop-58hr99p
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set dxsdk_dir=c:\program files (x86)\microsoft directx sdk (june 2010)\
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\espkk
@set include=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\include;c:\program files (x86)\windows kits\10\include\10.0.17763.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.17763.0\shared;c:\program files (x86)\windows kits\10\include\10.0.17763.0\um;c:\program files (x86)\windows kits\10\include\10.0.17763.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.17763.0\cppwinrt
@set lib=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\lib\x86;c:\program files (x86)\windows kits\10\lib\10.0.17763.0\ucrt\x86;c:\program files (x86)\windows kits\10\lib\10.0.17763.0\um\x86
@set libpath=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\atlmfc\lib\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\lib\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.17763.0;c:\program files (x86)\windows kits\10\references\10.0.17763.0;c:\windows\microsoft.net\framework\v4.0.30319
@set localappdata=c:\users\espkk\appdata\local
@set logonserver=\\desktop-58hr99p
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set number_of_processors=6
@set onedrive=c:\users\espkk\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\bin\hostx86\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\enterprise\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\enterprise\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\windows kits\10\bin\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\\msbuild\current\bin;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\bin\hostx86\x86;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\tools;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide;c:\program files (x86)\html help workshop;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\windows\syswow64;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\nvidia corporation\nvidia nvdlisr;c:\program files\git\cmd;c:\@data\@exec\mingw64\bin;c:\program files\putty\;c:\users\espkk\appdata\local\microsoft\windowsapps;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\commonextensions\microsoft\cmake\ninja
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\espkk\appdata\local\temp\dev1906.tmp
@set platform=x86
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 158 stepping 12, genuineintel
@set processor_level=6
@set processor_revision=9e0c
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules;c:\program files\intel\wired networking\
@set public=c:\users\public
@set pvsbuildtools_extensionspath_vs2017=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\enterprise\msbuild
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\enterprise
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\espkk\appdata\local\temp
@set threadedwaitdialogdpicontext=-2
@set tmp=c:\users\espkk\appdata\local\temp
@set ucrtversion=10.0.17763.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=desktop-58hr99p
@set userdomain_roamingprofile=desktop-58hr99p
@set username=espkk
@set userprofile=c:\users\espkk
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\redist\msvc\14.21.27702\
@set vctoolsversion=14.21.27702
@set visualstudiodir=c:\users\espkk\documents\visual studio 2019
@set visualstudioedition=microsoft visual studio enterprise 2019
@set visualstudioversion=16.0
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x86
@set vscmd_arg_tgt_arch=x86
@set vscmd_ver=16.1.3
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\enterprise\
@set vslang=1033
@set vsskuedition=enterprise
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.17763.0;c:\program files (x86)\windows kits\10\references\10.0.17763.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.17763.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.17763.0\
@set windowssdkversion=10.0.17763.0\
@set __dotnet_add_32bit=1
@set __dotnet_preferred_bitness=32
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\enterprise\vc\tools\msvc\14.21.27702\bin\hostx86\x86;c:\program files (x86)\windows kits\10\bin\10.0.17763.0\x86;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\tools;c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide;c:\program files (x86)\html help workshop;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\windows\syswow64;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\nvidia corporation\nvidia nvdlisr;c:\program files\git\cmd;c:\@data\@exec\mingw64\bin;c:\program files\putty\;c:\users\espkk\appdata\local\microsoft\windowsapps

@call "cl.exe" @"C:\Users\espkk\source\repos\stormengine\ENGINE\InfoHandler.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1