string DLG_TEXT_MR [30] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"I'm listening to you, captain.",
	"Sir, the governor-general of Tortuga has ordered me to escort the ship-of-the-line Soleil Royal to island of Dominique. The squadron of Guadalupe should have been waiting for me there, but it wasn't in place. Can you somehow clarify the situation?",
	"The thing is, I received the order to move out the squadron to Dominique only yesterday. The courier was very late. That's why I was unable to prepare the squadron in time. I believe that you've come from Dominique...",
	"Correct. I had to battle with a Spanish squadron led by a certain Juan Galeno. He tracked, and tried to capture, the Soleil Royal.",
	"And where is this Juan Galeno and his squadron now?",
	"At the sea bottom, Monsieur...",
	"Ha-ha, excellent work! Well, you've completed your task - managing to bring Soleil Royal to its destination and get out of a real difficult situation with your honor intact. Again, excellent work, Captain. I hereby transfer the command of Soleil Royal from you to me.",
	"Wonderful to hear, sir. I won't keep you longer then. I've got business to attend to... Goodbye, Monsieur.",
	"But you were unable to save Soleil Royal! That's bad, sir, very bad... Now you must go to the Governor-General of Tortuga and report to him about your mission's failure. Farewell.",
	"Farewell, Monsieur...",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"A-a-a-a!",
	"Shut up, dumbass. I won't hurt you. I'm here on business.",
	"A talking mummy! A-a-a-a!",
	"Listen to me, you wretched coward. I know that you have the following four things: three crystal Toltec skulls of different colors and a strange Indian object that looks like a rattle. Hand them over right now and we'll be out of the city before you know it.",
	"They're in a closet to my left, in one of the shut drawers. Here's the key; you can take anything you want... ",
	"Hah, as if I need your permission, worm...",
};
