string DLG_TEXT_MR [26] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"You've taken everything. What else do you need?",
	"Is it possible that there's still something here that you didn't take?",
	"I'm taking one last look around...",
	"Just checking to see if I forgot anything...",
	"Damnation! What do you want, you cursed Ladrone?!",
	"You got three guesses.",
	"Gold...",
	"So you know what we want, after all. Alright, here's the deal: we're taking the gold and setting off on our merry way. And we're letting you live... on one condition.",
	"What condition?",
	"You're telling us where the gold that's to be transported to Spain is hidden.",
	"And if I don't tell you?",
	"Well, first, you'll be very scared. That feeling will be followed by pain. A lot of pain. And then you'll tell us everything anyway. The only difference is, you won't live too long after that - the injuries to your body will be too great...",
	"I don't doubt your words for a second. I've heard enough stories...",
	"The gold is in the fort. Give it a thorough search and you'll find it easily.",
	"Congratulations, you have just saved your own life and health. May you live long and prosper, Señor.",
	"The Spanish gold has been reloaded into the ships' holds.",
};
