string DLG_TEXT_MR [34] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"Señor, all are grateful to you for their lives. If it weren't for you, it's difficult to imagine what would have happened...",
	"The whole city was watching the battle. t was a great fight. We are very grateful to you, for saving us from the dirty pirates.",
	"Well, then. You don't expect quarter from Ladrones...",
	"These Ladrones must be eliminated everywhere...",
	"You've taken everything. What else do you need?",
	"Is it possible that there's still something here that you didn't take?",
	"I'm taking one last look around...",
	"Just checking to see if I forgot anything...",
	"All right, we've ceased all resistance. The city is yours. What will happen now?",
	"By the power vested in me by the Governor-General of Jamaica, I hereby declare this city property of Karl II Stuart.",
	"M'kay...",
	"From hereon, the city of Cumana is a British protectorate. The population is to pay all the tax levies, sales duties and the like, to the new British administration.",
	"Our city has fallen... I am ready to listen to your demands.",
	"It has come to our attention that there's some 200,000 reals right here in Cumana... That's what we're here for.",
	"Hmm, I see... And if I don't tell you where the money is?",
	"Señor, I trust you've heard the name Francois Olone?",
	"Yes, I've heard of that devil's spawn...",
	"Alright then. Well, Olone is my partner; we took the city together. Believe me when I say that any act of stubbornness on your part will cause half of your citizens to lose their heads. And Olone will do the cutting personally, with everyone watching. How do you like that scenario?",
	"I've heard my share of stories. This wouldn't be the first time he has done this... Well, I'm going to play the hero, especially since it will only cause the deaths of completely innocent people... All the reals are in the writing cabinet in the next room. Take them and be damned!",
	"You best watch your mouth, sir. I may not be Olone, but I'd still be delighted to cut out your rotten tongue...",
	"I've heard that he has done it before, and I've no doubt that he's capable of such acts, but there's no money here, and that's the truth. A squadron came and took it only five days ago. The money is now on its way to the New World.",
	"Then we will torture the citizens...",
	"Señor, it is obvious that we are at your mercy. As the Governor of this city, I have a very clear grasp on the severity of our situation. You can take anything you like, but you won't find the money that you came here for. You're late. It's no longer here...",
	"Caramba! Alright, I'll have a chat with my partners to decide the fate of the city.",
};
