string DLG_TEXT_MR [58] = {
	"Got business with me? No? Then get out of here!",
	"I thought I made myself clear...",
	"Even though I made myself clear, you continue to distract me!",
	"Hm. And you're bit swinish, mon cher...",
	"I'm already gone.",
	"Yes, ",
	", absolutely clear.",
	"I'm sorry, ",
	"Aye-aye...",
	"I'm listening to you, Captain.",
	"I'm come here by order of Governor-General Sir Thomas Modyford of Jamaica.",
	"I'm listening closely.",
	"Sir Thomas Modyford is asking you to assemble and pilot a privateer squadron to the Caribbean, and attack the Dutch city of Curacao.",
	"Hmm... and what's the reason for such a decision? I'll admit that it looks strange. The English don't attack the Dutch. Yes, the governments may have their disputes in the expansion of trade, but that's all about the Indian Ocean. Here it's the New World.",
	"Sir, Holland and England are in the midst of another trade war. Moreover, a British war fleet has attacked the Dutch on the shores of Europe. It was beaten back, of course. Still...",
	"I understand. Thanks for the info. I didn't know that.",
	"Now, then. I'm waiting for your cooperation on this expedition.",
	"My friend, I can't give you a positive answer for the governor-general of Jamaica.",
	"Now I am beginning to think you're answer is quite strange.",
	"Nothing strange about it. My real name is Edward Mansvelt. I'm Dutch.",
	"But you're an English privateer under the patronage of Sir Thomas Modyford. I think it's unreasonable to deny his request outright.",
	"You can think whatever you want. I really do have an English privateer's patent, but that doesn't mean that I'll slit the throats of my countrymen. I've given my answer. I have nothing more to say. Farewell.",
	"Well, then. If you've nothing more to say, then farewell.",
	"Good day. My name is Alistair Good. Since Mansfield's death, I've been selected as the head of the buccaneers.",
	"Good to meet you. ",
	"I have no time to talk to you now. Come back later.",
	"I'm already gone.",
	"What brought you to me?",
	"I've come here by order of Governor-General Peter Stuyvesant, of Curacao.",
	"Very good. What does Governor-General Stuyvesant need of me?",
	"Edward, the British have attacked the Netherlands. A new trade war has started.",
	"Sad news, indeed. I have business in Port Royal...",
	"Here's a package from Stuyvesant. Please look it over.",
	"Well, alright, let's have a look here... Hmm, he wants me to inform him of Modyford's plans in regards to his participation in the war.",
	"Absolutely right. This knowledge is crucial for the Dutch settlements.",
	"The problem is that I know nothing of Modyford's plans in regards to the war. He and I do business of a different kind - one that has nothing to do with politics.",
	"So how am I to answer Stuyvesant? That you know nothing and are unable to help your homeland in this difficult hour?",
	"Lose the pompous expressions, young man. I know who I am. I really don't know anything about Modyford's plans, though. However, there's one thing I can tell you.",
	"Just this past week, a messenger from Modyford turned up in my residence trying to convince me to organize an expedition to Curacao. Naturally, I refused. Morgan, Jackman, and John Morris refused as well.",
	"What's shaping up is the following: Thomas Modyford, the old fox, is trying to goad the pirates into armed hostilities against the Netherlands. A sly plan, indeed...",
	"So Modyford plans to attack Curacao?",
	"He can plan to attack Curacao all he wants, but I'd like to see him actually do it. He's not strong enough for an operation of that magnitude. He wasn't trying to engage the corsairs just for the fun of it.",
	"And anyway, Port Royal's best protection against the Spanish is continual presence of a certain number of pirates in Jamaican waters. So no, he definitely cannot crack Curacao.",
	"Well then, at least we don't have to fear an attack from him...",
	"I wouldn't be so categorical about the matter. His attempts to engage the corsairs tell us that he did actually receive an order to commence military operations. So whatever way the cookie crumbles, there'll be no peace between England and Holland.",
	"Here's what I suggest you do - set out immediately for Port Royal to see Henry Morgan.",
	"The Henry Morgan? The corsair admiral?",
	"That's the one. Don't worry, I had a little something to do with him becoming an admiral. To be more precise, I was the one who awarded him the title in the first place. Ask him for help on my behalf.",
	"Will he help?",
	"Whatever he can do, he will do.",
	"Edward, could you write a letter for me to give to Morgan so that he'd believe my words?",
	"No, that's not necessary. No man in his right mind would dare to yank Morgan's chain, and if someone does, he won't last long. Morgan will believe you.",
	"Edward Mansfield, you're a true son of your Homeland. Thanks for your help!",
	"Get the hell outta here!",
	"Get out of my house!",
	"Ooo, I'm scared...",
	"Don't test me, if you know what's good for you.",
	"I understand, Edward. I won't do it again...",
};
