string DLG_TEXT_MR [18] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"I came here by order of Peter Stuyvesant. You have a shipment of goods for Curacao that I was ordered to purchase and deliver. Please have a look at the following documents - they entitle me to special pricing.",
	"Alright, let's have a look... Well, your papers are in order. Go ahead and take the entire shipment from the local store. I'll give the order to have it handed over to you right away.",
	"The shipment contains coffee, ebony, mahogany, and sandalwood. The total weight of merchandise prepared for delivery amounts to 6,800 centners. You can start loading as soon as you pay - that you do in the store.",
	"Very good.",
	"Am I happy to see you or what!",
	"I'm here on Stuyvesant's order. Looks like we made it just in time...",
	"Hell's bells! Forget 'just in time' - you saved our hides! Fort Orange thanks you from the bottom of our hearts! Please send my regards to Peter Stuyvesant.",
	"I certainly will. Take care.",
};
