string DLG_TEXT_MR [190] = {
	"Got business with me? No? Then get out of here!",
	"I thought I made myself clear...",
	"Even though I made myself clear, you continue to distract me!",
	"Oh, now this is starting to get rude, and it's tired me out.",
	"I'm already gone.",
	"Of course, Jackmann...",
	"I'm sorry, Jackmann...",
	"Hey...",
	"Listen, Jackmann, here's the deal. Did a xebec called the Blue Bird dock at your port?",
	"Imagine that. Blue Bird! Yeah, I caught that xebec. ",
	"Listen, there are rumors going around about the operations of pearl divers in the Caribbean Sea. Did you hear anything about that?",
	"Jackmann, I'm looking for some work...",
	"I'm looking for my friend, Edward Low. Alexis said that you've got him.",
	"What do you want?! I'm in no mood to answer your questions!",
	"I think we've got a matter in common. Edward Low.",
	"You're back! Not empty-handed I presume?",
	"I'm happy to report that Edward Low died with horror in is eyes, and your name in his ears.",
	"Ah. Happy to see you, ",
	". Well, what do you say?",
	"Do you about what Morgan did in Panama?",
	"Listen, Jackmann, do you know anything about a corsair they call The Arrow? Or maybe he sails on a ship by that name? ",
	", happy to see you! What brings you here this time?",
	"What else do you want?",
	"How long will this go on for? If you've nothing to do, don't distract others!",
	"You're a good privateer, so live for now. But I don't want to talk or socialize with you any longer.",
	"Well, I just wanted to stop by and say hello. Nothing business-related.",
	"Nothing, just 'cause....",
	"Fine, Jackmann. Sorry...",
	"That's it, damn it! You've gone and done it!",
	"Listen, Jackmann. Did a xebec called the Blue Bird dock at your port?",
	"Imagine that. Blue Bird! Yeah, I caught that xebec. ",
	"Listen, there are rumors going around about the operations of pearl divers in the Caribbean Sea. Did you hear anything about that?",
	"I'm looking for my friend, Edward Low. Alexis said that you've got him.",
	"What do you want?! I'm in no mood to answer your questions!",
	"I think we've got a matter in common. Edward Low.",
	"You're back! Not empty-handed, I presume!",
	"I'm happy to report that Edward Low died with horror in is eyes, and your name in his ears.",
	"Ah! Happy to see you, ",
	". Well, what do you have to say for yourself?",
	"Do you know what Morgan did in Panama?",
	"I've got no work. But if you aren't busy with anything, go on to Puerto Principe. Find Captain Goodly there. He was asking for help, not too long ago.",
	"Help with what?",
	"I don't know! Ask him yourself.",
	"Understood...",
	"Friend?! Ho! You've come to right place, pal. Hey, guys! Get him!",
	"I don't get it...",
	"Low?! What kind of business do you have with Low?",
	"I'm looking for him as a task for Morgan. Low vexed Morgan, and I'm looking for him to let his blood flow.",
	"Hm. So he's had time to screw over Morgan as well. I can't say that I'm very saddened by that fact. But that rogue stole my brig!",
	"Yes, I know. Your master on the dock told me.",
	"Yes, still the louse! His brains have been shaved into chips, to think I'm going to write him letters! From my residency to his hole, it'd take a turtle a half an hour to crawl. And he trudged along the next day, to get his money for letting the brig go. Oh, yeah, right.   \n I told that chipper, when my boys were tossing him out the door, If the 'Sea Wolf' ain't found, I'll skin you alive and wrap the money with it! So it'd be easier to carry...",
	"Aha. You were pretty rough with him.",
	"Oh, I just got a little steamed. I won't touch him. No one in his right mind would throw around such a master. I'm just furious that my ship's been stolen! And Alexis should shiver a bit. He'll be smarter, next time.",
	"So you want to kill Edward Low. As you can understand, I want that too. Although paying you for his death would be the height of stupidity on my part, there is one caveat. I want the thief to know what he's dying for.",
	"So that he would know that you don't leave Jackmann without punishment! So that everyone knows it! Everyone! If Low knows in his dying moment that death comes from me - not Morgan, but ME - then I'll reward you.",
	"Fine. That shouldn't be difficult. But, Jackmann - answer one question for me.",
	"What?",
	"Why weren't you upset about Morgan getting screwed over? I always thought you were friends.",
	"Hm. Friends... I'll answer that, if you can understand. Shore Brotherhood, Gentlemen of Fortune; treasure, women, glory! Familiar sentiments, yes? When we're young, the romance of these words draws us like a moth to a flame, and we just obediently fly into its glow.",
	"But not moths are the same. Some of us circle closely, not daring to draw nearer; some get burned and fly away; some just burn. And some get reborn in the flame, and carry on indomitable, on steel wings",
	"Hm... I see that you aren't getting what I mean. Have you heard the proverb, man is a wolf to man? So we're all a wolf pack. A pack will take a much bigger haul than a lone wolf.",
	"A pack is led by a chief, who gets a bigger piece of the catch and his pick of the wolf maidens. All the wolves listen to him and wait, until... well, until he makes a mistake. Because every wolf wants a bigger piece of the catch, and a sweeter bitch.",
	"Well, thanks for the theory. I get the wolf part. And to be honest, I like being a wolf more than some damned moth.",
	"Hwahaha-haha-haha! Then run, wolf! Run! And come back with your catch!",
	"Yeah. You just wait there. I'll be back soon.",
	"I was waiting for those words. I see you've managed to secure my brig as well! Excellent. You tell me you're a Wolf? Well, then I can let go of my Sea Wolf with a clean heart. You've earned the right to it! I'd like a guy like you in my pack!",
	"I'm a free captain, Jackmann. But your words are a great honor for me!",
	"I was waiting for those words. Well, then. Thanks anyway, pal. To reward your labor, I'm giving you 20,000 piasters!",
	"Thank you, Jackmann. This money will come in handy.",
	"Ooh, who am I seeing?! I can't believe my eyes!",
	"Morgan sent me here to tell you that Captain Goodly is dead.",
	"Is that so... The news isn't pleasant. And how did it happen?",
	"I killed him in Morgan's residency. Understand, I took down John Ivory upon his order - but he turned out to be a trusted official of Morgan...",
	"Ivory is dead as well?",
	"That is so... Anyway, there was a confrontation with Morgan. And in the end, Goodly wouldn't admit that he hired me to get Ivory. Everything was decided in a duel. That's all I had to tell you.",
	"Ha, ain't that something! And surely you're aware, my friend, that you also have captured one of my own captains, Stede Bonnet, and handed him over to the Spanish?",
	"Me?!",
	"Yes, those are the rumors going around. That's why I was slightly flabbergasted when I saw you here.",
	"Hot damn! So what should I do?",
	"Be off to Cozumel Bay, north of Belize. There at the shore, on the frigate Antwerpen, you'll find John Leeds. He's got some problems with his team. I think you'll be interested in visiting him...",
	"Fine, Jackmann. I'll do that.",
	"Antwerpen",
	"John",
	"Leeds",
	"John's already told me about your operation with the twin. Were you able to take him alive? Did you discover anything specific?",
	"I was just able to talk. He didn't tell me anything...",
	"That's bad. You've got some unlucky streak to you, my friend - pocked like a leopard. Luck is on your side for now, but things can change one day. And then you're finished!",
	"I understand. My twin knew something, but didn't say it. I need to find out who's behind all of this...",
	"Correct. Well, then. Good that you've dropped by here. It has... cleared up a few important details, so to say. Now be off to Morgan, and tell him about your twin.",
	"I'll do that. Thank you, Jackmann, for believing me.",
	"I didn't believe you; I just knew that Leeds locked you at Santa Catalina's. You were just lucky.",
	"Understood. Yes, it looks as if luck really is on my side.",
	"I heard about that, but I know nothing about it. The man who specializes in such a business is our beloved and respected Captain Sharpe! He's a big lover of pearls. Ha-ha!",
	"And where can he be found, this Sharpe?",
	"I don't know. Captain Sharpe is one hard-to-catch Joe. Still, needs must.\nAnyway, it's best to look for him in brothels.",
	"Thanks, Jackman.",
	"Haw, that washtub's become famous. Who woulda thought... Why do you need that xebec, anyway?",
	"We already spoke about that xebec.",
	"Again with that?",
	"Say what?! Again?! Nah, I've had just about enough...",
	"You see, it's become something of interest to this group of friends...",
	"That's right, Jackman.",
	"Hrm, pardon, I messed up my notes...",
	"Ooh!",
	"They wouldn't be traders by any chance, would they? He-he. 'Cause I heard that they're getting it left and right from this Blue Bird.",
	"You're right, it's the traders that are interested in the xebec. But you know, I'm also dying to see this birdie from which no one seems to escape. It sounds like a perfect sailer!",
	"Heh, you got that right! You ain't the first from the Brotherhood of the Coast to set your sights on that ship, but no one has caught it yet. I don't care much for the birdie personally. It's a bit too small for any serious operations.",
	"Jackman, do you know where to find the xebec?",
	"Of course I don't. I mean, I saw it in the surrounding waters once or twice, but it never entered the port.",
	"You have any idea where to start looking?",
	"Nah, never even thought about it. Nothing comes to mind.",
	"I see. Well, thanks anyway bud.",
	"Whoa, congratulations! Great job, man!",
	"Congratulations once again.",
	"I already heard that...",
	"Hah! Boy, I swear you're the biggest braggart the Caribbean's ever seen!",
	"Thanks, Jackman. A little sympathy goes a long way.",
	"Thanks again, Jackman.",
	"Ah, don't mention it...",
	"I'm proud of it!",
	"Always happy to see an English privateer on my island. How can I be of help?",
	"I have a job for you. The customer is the Governor-General of Jamaica.",
	"Hmm, interesting. Go on...",
	"Modyford is looking to attack Curacao, and we could really use the riches of its merchants. Curacao is currently full of protestant traders that refused the good ol' 'Spanish boot' of the Inquisition and fled Spain and Portugal to Holland. And wherever there are traders, there's gold. Lots of gold. I suggest we mix business with pleasure, just this once.",
	"Heh... sounds tempting, but I'll have to refuse.",
	"And why would you do that?",
	"Because in addition to merchants with their gold, Curacao is also crawling with Dutch soldiers armed with muskets and cannons in the fort's firing slits.",
	"Hmm, you don't seem so scared of Spanish soldiers...",
	"What I'm scared of is the condition of my liver. You see, disemboweling a Spanish is holy, but finding volunteers to spill Dutch blood won't be easy. So you'll have to manage without me.",
	"Maybe you'll think about it?",
	"I've made up my mind. Send Modyford my regards.",
	"Fine, it's up to you. See ya.",
	"Good to see you. What brought you to Bermuda?",
	"I'm here on business. Morgan and I are going to attack Belize. Care to join us?",
	"Heh, my corvette is off the harbor and my crew is fully equipped. Count me in.",
	"Great! We set out immediately!",
	"You've got a good set going already. You don't need me.",
	"Well, up to you. Take it easy.",
	"Damn it! Time is working against us!",
	"Let's hurry!",
	"You saw everything - those dirty Spanish sunk my corvette! But that's alright. Almost my entire crew made it ashore in one piece, and we continued fighting on land.",
	"Gold will reward us for our efforts. Heh, those stupid Spaniards tried to hide it from us. But you were right - the gold was here, all three plus tons of it. And it's all ours!",
	"My mouth is speaking, but my soul is singing. These are the only words I want to be speaking for the rest of my life.",
	"Those stupid Spaniards tried to hide the gold. But you were right - the gold was here, all three plus tons of it. And it's all ours!",
	"My mouth is speaking, but my soul is singing. These are the only words I want to be speaking for the rest of my life.",
	"And those are the words I want to be hearing for the rest of my life!",
	"Ha-ha... You're a fine corsair, ",
	". I wish you luck, my friend.",
	"My cutthroats can't wait to get home after a hard day's work. Remember that you'll always be a welcome guest on Bermuda.",
	"See ya soon!",
	"I'm listening. Why have you come here? ",
	"I came here on business. I'm looking for a pirate that was trying to sell some strange version of the Bible...",
	"Damn, there was something... I can't remember the details, but I definitely remember some cat bragging about a rare book - a Christian one, supposedly...",
	"And?",
	"And nothing. He just mentioned it. I don't remember much else... We were carousing in a brothel at the time. As you can imagine, the Bible was the last thing on our minds!",
	"Hmm, which brothel?",
	"The one in Fort-de-France.",
	"I see... Well, thanks, Jackman.",
	"Well, what do you know, it's Captain ",
	" himself! It's good to see you! Alright, out with it! I can smell that you can't wait to tell me something interesting.",
	"Well, I probably don't have anything of interest to say to you, if you don't count one tiny suggestion. You should refrain from participating in the impending war between England and Holland.",
	"You're right, you don't have anything of interest to say, especially since I wasn't planning on meddling anyway. Only a complete idiot would start up conflicts with the Dutch. You can go back and tell your patrons that they made you take a needless detour.",
	"Far from needless. At least I found out about your neutrality from you personally, and not from a third party.",
	"You're just wasting your time on my ship. We need to hit Portobelo, like yesterday!",
	"Yeah, I remember...",
	"Just wasting more time. I don't get you, man...",
	"It's all right, Jackman. Relax and trust me.",
	"Yeah, yeah...",
	"What have you got to say about that?",
	"Not much except that I'm done with privateering, so don't be coming 'round with that kind of business anymore.",
	"Damn, but why?!",
	"Cause I said so! Anyway, I told you all I wanted to say!",
	"Hrm, I see...",
	"Hmm, yeah, I know that cat. Runs a brig called 'Arrow.' Not a bad sailer, actually.",
	"I see. Can you tell me where to find him?",
	"No, I can't. The man keeps to himself. Never entered into the Coastal Brotherhood, never enters any ports, including this one. His strategy is to always be on the prowl; he boards his quarry and retreats to some secluded bay. Even the pirates don't really know him.",
	"Hmm... Well, I need him. What do you suggest I do?",
	"Just keep an eye out for him while out at sea. Look carefully at every ship you pass - this brig you shouldn't miss...",
	"Got it. Well, thanks, Jackman.",
	"Get the hell outta here!",
	"Get out of my house!",
	"Don't mention it...",
	"I'm busy, so you shouldn't distract me with empty pleasantries. Do it again and I promise you'll really regret it.",
	"I understand, Morgan.",
	"I grow weary of you. Just stop talking.",
	"I don't want to talk to you, so I suggest that you don't bother me.",
	"Well, you know...",
	"Hrm, well...",
	"I hope that you'll stop bugging me with empty banter. If you don't, I'm going to have to kill you, and I admit, I won't feel good about it.",
	"That's a very convincing argument, Jackman. I'll stop.",
};
