string DLG_TEXT_MR [40] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"I'm listening to you...",
	"Señor, I've arrived here to carry out an order to defend Maracaibo from external threats. I am sent into your service by Governor Francisco Oregon y Gascon of Havana.",
	"Well! You're just in the nick of time. We didn't even set up and distribute the team into the city. Welcome to the battle!",
	"Duly noted!",
	"You're still here? I think it's time for you to be off to battle.",
	"Right, right... I'm not going to make the Ladrones wait...",
	"Excellent work, my friend. Don Francisco has sent me a gallant and experienced captain!",
	"Thank you, Señor.",
	"You've taken everything. What else do you need?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"Alright, we've ceased all resistance. The city is yours. What will happen now?",
	"From hereon, this city belongs to the Republic of United Provinces. It is placed under Dutch control and shall be governed by Dutch laws and regulations.",
	"This time, you were stronger. We'll see what happens in the future. I take it you aren't much bothered by Portugal's activity in the Indian Ocean, otherwise you would never have dared a move as brash as this.",
	"This move was nothing but a logical response to the attack by the Spanish squadrons.",
	"Which would never have happened if you didn't supply France with money!",
	"It's too late to argue about this, anyway. The city is now Dutch, but we'll see what happens in the future.",
	"Excellent! My request to reinforce the squadron and the garrison was satisfied!",
	"Yes, that is so, but could you please tell me what brought forth these concerns?",
	"Certainly, Captain. It was brought to my attention that at their latest concourse, the English bandits decided to capture Maracaibo. Although my sources cannot be fully trusted, I thought it would be prudent to request help from Señor Francisco Oregon y Gascon.",
	"I see. And what do you want me to do?",
	"Nothing, really. Just be ready for combat at any time.",
	"My crew and I are always ready... Well, if you don't need me, I'm going to head for the city and attend to my own business.",
	"I must ask that you get on with your mission at once. We must destroy the English pirate squadron!",
	"Fine. Certainly.",
	"For the successful rebuff of the English attack, the city is prepared to pay you 70,000 in gold. Please be so kind as to accept it, Captain.",
	"Very good.",
	"Your job here is done; I dare not keep you longer. Please send my warmest regards and sincerest gratitude to Governor-General Oregon y Gascon.",
	"Certainly, Señor. Farewell.",
};
