string DLG_TEXT_MR [20] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"Why did Spain attack the Dutch settlements? We're not at war!",
	"By helping France out with money, de facto you are fighting this war on their side.",
	"Do you have proof?",
	"We don't need proof. You will need a long while to regain your trading supremacy in the Caribbean. Feel free to continue lending money to Louis, that is, if you find any idle funds...",
	"Spain be damned...",
	"Watch your tongue, lest you want me to cut it out, mister Dutch Mynheer...",
};
