string DLG_TEXT_MR [20] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"Captain, the entire city owes you to the grave! You saved us...",
	"Baron, sir. I am a baron, not a mere captain! But yeah, you're right. I did save you, and I'm kind of glad I did...",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"We give up, you cursed Castilian...",
	"Good! You've just saved your lives.",
	"This is a French colony! What the hell...",
	"And now it is a Spanish colony - you best remember that. As for you, Monsieur former Governor, I won't keep you...",
};
