string DLG_TEXT_MR [40] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"Who are you, and what do you need?",
	"My name is ",
	", and I'll ask you to familiarize yourself with this document - this letter of credentials on my name, behind the signature of Governor-General Francisco Oregon y Gascon.",
	"Now, Captain - glad to see you! What have you to say?",
	"I'm about the mission. Are you ready to give me control of the galleons I mentioned?",
	"Ah, I see. Very good. I've been waiting for you for a long time. Are you aware as to the goal of your visit here?",
	"In general, I... kind of have to escort some ships...",
	"Hm. That's about the thick of it. I'm giving you four galleons, loaded with gold. Your have to deliver them safe and sound to an uninhabited Cayman island. Is everything clear?",
	"Not everything... If you'll allow me, I'll tell you my opinion on this matter.",
	"Yes, of course.",
	"I'd understand if the galleons needed to be delivered into a fortified city, under the protection of a powerful fort, but bringing them to a deserted island...",
	"That's the place of gathering for a big squadron that will set out for the Old World. A powerful Spanish fleet will be waiting for you there after arriving from Belize. As you can see, there's no reason to worry. This is our new strategic ploy in our struggle with the Ladrones, seeing as they're always guarding the approaches to Belize. This time around, the only ships leaving from there will be fortified war galleons - a tough nut to crack even for pirates.",
	"Now do you understand?",
	"Almost. Where are these galleons? Where are their captains?",
	"You will assume command over the captains as soon as you get rid of all the extra ships in your squadron. The only ship you'll need for this mission is your own.",
	"I see. I'll come back later then, as soon as I figure my squadron out.",
	"The galleons are anchored at Portobelo, and the captains are hereby yours to command. Basically, you may proceed to your mission immediately.",
	"Very well. Am I limited by time in any way?",
	"No. Just make sure that all the galleons reach Cayman safe and sound, without losing any contents in their hold. And by contents, I mean gold. Currently, there's 5,000 gold in the ships' holds - 10,000 centners in weight.",
	"I understand. And I shall set out at once.",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"Damnation! How did you capture the city so fast?!",
	"Hah! I understand you're amazed, but this is only the beginning...",
	"We knew that the pirates were planning to attack Panama. You were able to capture my city, yes, but Panama... Trust me, Señor, the jungle will be the end of you.",
	"It won't be easy, but we'll manage, Señor Governor. Don't worry about us. By the way, how did you find out about our campaign?",
	"Me? From the Governor-General. No idea how he found out, though.",
	"I see. Now it's getting interesting...",
};
