string DLG_TEXT_MR [34] = {
	"Got business with me? No? Then get out of here!",
	"I'm already gone.",
	"Richard, I heard you're collecting people for a mission against the Spanish. I'd like to participate.",
	"State your name.",
	"Hee hee. You wouldn't you be one of Morgan's stooges, my chum?",
	"I work for Henry. What this about stooges?",
	"Well, it's just that you won't work out for me. Hey, on watch! Everyone, over here now! Get this lackey out of here...",
	"Why are you being like this?",
	"Why the hell are you here without an invitation?! Ahh, I think I know you... Hey, on watch! Everyone, over here now! Get this lackey out of here...",
	"Hey, what's the big deal?!",
	"How could Morgan put such a klutz in charge of a squadron? It boggles the mind...",
	"Hm. It's a pity you did that, Richard.",
	"Oh. You again. That's what I'm talking about!",
	"Don't worry about me.",
	"What are you doing on my deck, again? You think just because you successfully led the assault on Portobelo. you can strut around here like a peacock?",
	"What do peacocks have to do with this?",
	"Listen, get out of here... I've got nothing to say to you. Everything will be decided in Panama. Let everyone show his stuff there.",
	"What are you talking about?",
	"You ain't my boss or my father. I don't have to tell you shit. So why don't you just go to hell in a hand basket.",
	"I can see that you're not in a talkative mood. Fine, I'll go...",
	"I don't wanna talk to you!",
	"Ain't that obvious...",
	"Well, we've made it to the gulf. Now we need to get through the jungle. My people and I are ready and can set out right away.",
	"Very well; I got you.",
	"What are we waiting for? Come on, move your ass to Panama!",
	"Hrm, that's obvious...",
	"What do you need?",
	"Listen, I realize what I'm going to tell you now will sound unpleasant, but Morgan gave me an order to kill you as we hike through the jungle.",
	"And you think I'd believe you?",
	"You don't have to believe me, but it's the truth.",
	"This isn't the first time you stick your nose in my business or ruin my plans. You were always Morgan's rat. So what, now you wanna get something on me to rat about?",
	"Go to hell, Richard... Idiot!",
	"Actually, I think I'll go to Panama instead... But you will not enter the city, so get the hell outta here while you're still standing...",
	"Damn it!",
};
