string DLG_TEXT_MR [26] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"Señor Governor, I am Captain ",
	". It was I who was wed in the city church, with widow Isabella Olevarez (born de Valdez).",
	"You're just in time, Captain! I already sent the commandant for you.",
	"Well, since you're already here, for the love of God, won't you tell us why you've put on such a terrible massacre in our church!",
	"Señor ",
	", I was simply defending my life, my honor, and Isabella, my wife...",
	"That sounds quite noble, Captain, but I'm still waiting on the details of the event that shook the whole city!",
	"Señor Governor, the deceased husband of Isabella, Salvatore Olevares, was grade A scum. He has a long history of abhorrent crimes, many of them murders...",
	"I am aware of that. When Isabella arrived from her cousin's, Fernandez in Belize, she visited me and told me all about it. So, I take it that you are her savior?",
	"Yes, Señor Governor. I trust there's nothing surprising in the fact that Isabella and I decided to get married as soon as we got the chance. However, before his death, that bastard Salvatore hired a whole gang of truly detestable rabble from all over the Caribbean to destroy us.",
	"And the people in the church were the assassins?",
	"Exactly right, Señor Governor. I reckon I've done a lot of good for the whole region by destroying so many bandits at once...",
	"No doubt about it, Captain, you have. Well, now the situation is quite clear. We will most likely use the public fund to consecrate the church.",
	"Señor Governor, thank you so much for understanding the situation...",
	"It is my duty to know what's what in such matters, Captain! Anyhow, I wish all the best to you and your spouse. Please accept my congratulations.",
	"Thank you, Señor Governor!",
};
