string DLG_TEXT_MR [19] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"You win... What will happen now? Ransom?",
	"No, Señor. I, ",
	", hereby declare this city property of the French crown. We consider this an adequate response to your attempt to capture Port-au-Prince.",
	"You'll never hold the city...",
	"Don't worry about us holding the city, Señor... There will be changes, that's for sure. Oh, by the way, you are under arrest.",
};
