string DLG_TEXT_MR [20] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"This attack is the second attack of late! The French are in dire risk of drawing the wrath of Escorial on their heads.",
	"Heh, my goodness! Let the Queen Mother rage all she wants; we've got a war on our hands, my friend.",
	"So what are you going to do?",
	"I am going to depose you, have the citizens swear an oath to Louis XIV, and transfer the control of the city to a French administration. You don't mind, do you?",
	"Señor, by right of victor, you can mock me all you want, but remember: things change fast here in the Caribbean...",
	"And I'm here to make sure that these changes benefit France, Señor. Well, my job here is done...",
};
