string DLG_TEXT_MR [44] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"I'm listening to you, Señor. Go on.",
	"I've been sent into your service by the governor-general of Havana.",
	"What do you say, officer?",
	"Everything's been done in the best fashion. The buccaneer settlement on La Vega has been destroyed. Its leader, Mansfield, has been killed by me personally.",
	"You've taken everything. What else do you need?",
	"Is it possible that there's still something here that you didn't take?",
	"I dunno! I'm taking one last poke around...",
	"I'll check. I'm always forgetting something...",
	"You've won, Ladron!",
	"Ahem. Señor, I don't like when I'm called that. I'd prefer if you called me a privateer.",
	"You'll do without, English pig.",
	"I'm afraid not, Señor. I'll tell you, we're not leaving alone. You will accompany us on our trip, to the shores of Jamaica. Sir Thomas Modyford is eager to meet you.",
	"What?! By what right?!",
	"By right of victor, Señor. And since, by force of circumstances, we will be spending some quality time together, I will insist that you start calling me 'privateer' instead of 'Ladrone.'",
	"Manuel Rivero Pardal is already on his way to help me. You won't get far...",
	"It wouldn't be the first time I've met a Spaniard at sea, and trust me, it won't be the last. Let Pardal come. Meanwhile, get your things, venerable Señor. And fast!",
	"Gregorio Florido",
	"de Balboa",
	"José Sánchez",
	"Jiménez",
	"Yes, it's very good that you're here. Are you ready to commence military operations on land?",
	"Always ready.",
	"Wonderful. Then listen carefully to what you have to do.",
	"I'm all ears.",
	"You need to attack and destroy La Vega, the buccaneer settlement on Hispaniola. The man in charge over there is a certain Edward Mansfield, a veteran Ladrone. This settlement must be razed to the ground. Anything you find there is yours to keep. Hispaniola must become entirely Spanish, and the first obstacle in our path is La Vega. I'm expecting a new group of colonists. They need space to live and work.",
	"I understand. May I begin?",
	"Of course, and the sooner the better. I want to emphasize the fact that the settlement must be completely destroyed. You must leave no survivors. Hispaniola is our island - there's no place on it for their riffraff.",
	"I understand. I shall commence the mission at once.",
	"Terrific! Don Francisco recommended you as a very capable and resourceful military officer. I'll be expecting you with good news.",
	"I assure you, Señor, La Vega's days are numbered.",
	"Excellent, Señor! Simply marvelous! Don Francisco Oregon y Gascon should be rightfully proud of having officers like yourself in his employ.",
	"Buccaneers are a worthy adversary. I'm happy that I was able to complete the task set before me... Señor, and what about my reward?",
	"Oh, right... The city of Santiago believes that execution of such a difficult operation commands a reward of 100,000 piasters. Please be so kind as to accept it.",
	"Wonderful. It was great doing business with you, Señor Jimenez. Farewell.",
};
