string DLG_TEXT_MR [18] = {
	"What did you want? Out with it.",
	"I'm listening to you. What's your question?",
	"This is the second time today you've tried to ask a question...",
	"This is the third time today you've tried to ask a question...",
	"When will this end?! I've got matters that deal with managing the city, and you're trying to ask questions here!",
	"I've changed my mind...",
	"Not now. This is neither the time nor the place...",
	"Yes, that's right. But not now. Later.",
	"I'll ask, I'll ask... Eventually.",
	"I'm sorry, ",
	"You've already taken everything. What else do you want?",
	"Is it possible that there's still something here that you didn't take?",
	"Just taking one last look...",
	"Just checking to see if I forgot anything...",
	"To hell with those damn Spanish! You've pillaged the city!",
	"Consider it punishment.",
	"Punishment for what?",
	"For your secret assistance to France in the devolutionary war. Let this be a lesson to you...",
};
