string DLG_TEXT_QB [143] = {
	"Well, well, old timer! So how are you my good friend? It is good to see you, ",
	"Attila! How are you, you old sea devil!",
	"Look at you, dressed up all funny like a dandy! I bet the wind's not whistling in your pockets! Won't you offer a drink to an old pal?",
	"I'm damn happy to see you, but I can't now, buddy. Another time...",
	"Haw haw hah! It wouldn't be a sin to knock back a mug of good Jamaican rum, for a meeting like this!",
	"Pop my gut, we've got to have a drink for this meeting! Straight to the tavern...",
	"Agreed! To the tavern!",
	"Dammit, ",
	"! We pulled a glorious deal in Caracas, didn't we! Blow me down!",
	"Yeah... You sent quite a few Catalonian devils to their forefathers in that battle. For such inspired butchery, they gave you the nickname - Attila... Since then, I see, luck hasn't often smiled upon you.",
	"Argh! I tell you, never trust those Catalonian dons! I was with one of them. We took some French tub. There was a jeweler among the passengers. I didn't care about his papers - some documents -- but I know something about trinkets. Holy Mother, they were enough to buy half of Hispaniola and a governor's house - with the governor himself in tow! We divided everything honestly, then we found five kegs of rum in the hold. So of course, we drank ourselves silly from happiness...",
	"Heh, as always...",
	"So it was. And the morning after, it turns out our pal wasn't an honest decent scoundrel. Got his stuff together, grabbed all the trinkets, and was off.",
	"And you let that go? May a shark swallow me! I'd have...",
	"What would you have done, greenhorn?! He ran off to a Spanish island. And my path isn't open, there. To hell with him. He could've slit my throat, me dead drunk and all, and nobody would've said a word.",
	"Hm. You've become a tad too melancholy, buddy.",
	"Time goes on, and I'm getting older. It's not that easy to send a person to the next world... And Salvatore, they say, had a sweet wedding on my money. He lives in San Juan now...",
	"Damn me to hell! Attila, my friend, maybe I should pay a visit to this quiet family nest? Maybe you'll find your trinkets in the wife's jewelry box, eh?",
	"Har! Methinks you wouldn't be climbing into her bedroom for some trinkets! Oh no, buddy. I let the prize slip out of my hands once. It was meant to be... Live and let live. If God sees to it, we'll meet again.",
	"Farewell, Attila.",
	"I'll finish my drink, and head to the ship...",
	"I won't get in the way.",
	"Oh, who am I seeing? ",
	", in the flesh!",
	"Hey, Attila! Things are looking up, I see! You bought a house...",
	"Some dough's come in, so I wanted to invest in real estate. Though to be honest, a house here is a far cry from a house on Tortuga...",
	"Well, it's still a roof.",
	"Hm. Right you are! But tell me, why have you come here?",
	"Well, there's this matter. It's a long story... Anyhow, I paid a visit to your buddy Salvatore Olevarez.",
	"Har, that's news! How's the old fox living? Is it true he's married?",
	"Yeah, it's true. His wife, Isabella, is a very beautiful woman... And honest, to boot.",
	"Heh, how do you figure? Women are crafty people. Behind outside beauty, there can hide a big evil.",
	"Evil that's Salvatore! I didn't tell you about what happened, so listen.",
	"With pleasure.",
	"Anyhow, I showed up in San Juan after our talk, and started putting the pieces together. A lot of things happened there, but in the end it turned out that Salvatore robbed his wife and killed her brother - right in front of my eyes!",
	"Yeah, he's been going a bit too far, the villain...",
	"He framed me, and they tried to arrest me... By the time I was able to sort out the situation, Salvatore had vanished. And Isabella locked herself inside her house, not letting anyone in...",
	"Well, friend... Thanks for trying to bring about justice. What do you plan to do next?",
	"I'm thinking about finding Salvatore and gutting him. And I need to resolve things with Isabella... She still thinks I killed her brother.",
	"Uh, pal. Not to butt in, but does it make a difference to you?",
	"No, Attila. Not anymore...",
	"What?",
	"It's French... Everything's in order..",
	"And where do you intend to look? ",
	"I don't know, I can't wrap my head around it.",
	"Listen, you've smoked Salvatore out of San Juan - and that's very good! Now I can join in the search.",
	"And you'll be able to find him?",
	"I think so. You're not the only one who respects Attila. This pirate still has a few friends...",
	"Well, then. That would be great. And what should I do?",
	"Focus on your business, for now. And I'll focus on my search. You try to help, you'll just get in the way. Let's meet again here in two months, at my house. Then I'll tell you what I'd discovered.",
	"Fine, Attila. Well, good luck to you.",
	"And here you are, ",
	". Go on, happy to see you.",
	"Attila, how are things going? Did you find anything new about our good friend?",
	"Of course I did, ",
	"! What did you expect?! In general, you've really stirred Salvatore up... He never sits still, he's always moving.",
	"So how are we going to catch him, then?",
	"We need to think about it...",
	"Listen, did you find out anything out about Isabella?",
	"I did, pal. It looks like Salvatore has lured her out of San Juan. He sent the pirate brig Rapturous to pick her up. Then, rumor has it, he plotted a course for Portobelo.",
	"And what does he need her for? He defrauded her...",
	"Probably to put all the loose ends in the water, buddy. She won't live, your Isabella, if she falls into Salvatore's hands.",
	"Argh. When did the brig leave San Juan? I must intercept it in time!",
	"If you want to see Isabella alive, then yes. The brig left San Juan about three days ago. By my calculations, it'll be at Portobelo in fifteen to sixteen days. No more than that ",
	"That means that I must hurry... Thank you, Attila!",
	"Buddy, don't forget a very, very small detail... Somewhere in Porto Belle, Salvatore himself is located. He's waiting for Isabella there.",
	"Ha! That's right... Attila, I must rush. If everything goes well, then I'll return the jewels you lost.",
	"Good, ",
	". Good luck!",
	"Thank you, Attila.",
	"Well, how are things?",
	"Nothing yet...",
	"Well, tell me. How are things?",
	"None too good... I didn't catch that brig. Didn't even catch a glimpse of its stern... ",
	"I see. Then it would seem Isabella is already dead... ",
	"My heart breaks to think of it... But you are probably right.",
	"Why torture yourself? Tears won't help anyone. So this adventure is over for you. But life goes on.",
	"You're right, Attila. Thank you for your support. Goodbye... ",
	"I will go to sea soon. must earn a living somehow... ",
	"Best of luck to you, Attila.",
	"Well, friend, what's news?",
	"Noting good. I caught up with the brig at Puerto Bello, but was unable to take it... ",
	"Yes, that is bad... Isabella is probably dead by now... ",
	"God, so it would seem... Oh, my heart... I can't think of it without... without... ",
	"Well, tell me. How are things?",
	"Not too well... I caught up the brig at Puerto Bello, but failed to board it. During the battle, well... she sank. With all hands on board... ",
	"My friend, that is terrible! I envy no man who loses a woman he likes... but like that! ",
	"I can't speak of it... My heart begins to crumble, and I... ",
	"Well, tell me. How are things?",
	"Not too wonderful. I... I caught up the brig at Puerto Bello, and I boarded it.",
	"Well, was your Isabella aboard?",
	"She was, but she wouldn't listen. I couldn't get her off the ship, and it sank, with her on board. So... That's how things are, Attila... ",
	"Who's that I see? Why, it's ",
	", in the flesh! ",
	"Hello, Attila! How are you, old chum?",
	"All right. Everything's all right. How are things?",
	"Mixed. I can't find Salvatore, only catch his minions.",
	"Uh-huh... ",
	"Listen, have you heard anything about him? ",
	"Not especially. He goes around dives, hiring various lowlifes. He pays them up-front, then he disappears. A hard man to catch.",
	"You can say that again. How can I outsmart him?",
	"Go to Belize, and look for him there.",
	"Why Belize?",
	"Because that's where he went, last I heard. That's literally just a couple of days ago.",
	"I... took Isabella to Belize... ",
	"Uh-oh. I see what's happening. I wouldn't waste time if I was you... ",
	"No. I... Goodbye, Attila. Thank you.",
	"Oh, Captain ",
	". How you doing?",
	"Attila, I lost Isabella... ",
	"What happened?",
	"I killed Salvatore, and was about to wed Isabella in San Juan. Then during the ceremony, a mob of cutthroats burst into the church and killed her... Salvatore hired them before he died... ",
	"That's awful. My condolences. But, well, what can you do. You have to go on living... ",
	"Yes, Attila, that's... you're right... ",
	"Oh, Attila, it's been so hard... ",
	"I understand, my friend... ",
	"Greetings, my friend! How's life?",
	"Life is great, Attila! Everything is wonderful! Isabella and I got married! I am now, what you call, a family man! ",
	"Congratulations. That's great. A pirate's life is rarely long, so it's good you can put that aside... ",
	"That is true. Isabella agreed to marry me only on the condition that I quit piracy.",
	"Maybe it's for the better, my friend... ",
	"Yeah... I guess so. 'Bye, Attila... ",
	"Attila, thing is... I'd like to thank you for everything you've done for me.",
	"Again, Captain ",
	" is before me. What does the Captain want with Attila?",
	"Nothing in particular, my friend, just visiting... ",
	"For what in general, then?",
	"Well, for your help, and for all those times you pulled me out of hot water! And it's thanks to you that I met Isabella... ",
	"Ha! That I won't deny, my friend... ",
	"Well, since I've got you on a roll, then accept a thousand of coins, Attila! ",
	"I'm sure you won't deny seventy thousand coins, either... ",
	"I've got a hundred fifty thousand coins for you.",
	"I have here three hundred thousand coins. They're yours.",
	"Well, ",
	"... That, I did not expect. Well, thank you. I suppose I should ask no further about this... ",
	"That's nothing, my friend! Be well... ",
	"Splendid! I'm grateful to you, ",
	"All is well, Attila. See you... ",
	"Wow! I really didn't do much... ",
	"Attila, you may not have broken a sweat, but I couldn't have done it without you. Goodbye... ",
	"Lord of my loins, are you sure? That's so much money! ",
	"Thank you, my friend. This is a wonderful thing. I will buy myself a better corner... No, on further thought I will return to the Old World. I have been here for too long.",
	"Do you as you please, my friend! Goodbye... ",
};
