string DLG_TEXT_QB [199] = {
	"Buenas Dias, Señor. So, tell me... Wouldn't you be the captain of the ship that's standing for the raid?",
	"And you are the captain of the Five Holy Wounds of Christ?",
	"No, that's not me.",
	"The same, Señor. Arr, cursed storm! My brig won't be out to sea for awhile. ?Caramba! And, just to spite me, I took a passenger. And Holy mother, he's really complaining...",
	"He's promising to skin me alive, but it's not like I can seal every crack at the bottom with my ass. He really needs to get to San Juan, and not one ship's sailing there. The man is a respected noble. I'd be happy to serve him, but I just can't!",
	"Your passenger doesn't happen to be Don Miguel de Valdez? I would be able to transport him to San Juan.",
	"Yes, precisely! In the flesh! Don Miguel de Valdez! Oh, lord. God bless you!",
	"Then rouse him, and quickly send him to my ship. I'll be waiting for him at port.",
	"Oh, dear. May God bless you!",
	"Stuff happens. We'll be square one day.",
	"Good day! You're Captain ",
	"? I'm Don Miguel de Valdez. I'm heading to San Juan.",
	"Welcome aboard, Don Miguel. Yes, I'm Captain ",
	". I hope the journey will be pleasant for you.",
	"Thanks for the help!",
	"Believe me, it's no hassle at all.",
	"Thank you. And now let's go visit my sister.",
	"Please. Of course.",
	"Captain, huge thanks for the favor. How great that you turned up at Cumana. I can't count on any help from Salvatore...",
	"Don't think too much about it, Miguel. Everything's okay. The important thing is for your sister to be happy...",
	"We'll be happy to see you this evening, Captain.",
	"I'll surely come, Miguel.",
	"Swindler! It was you that stole my sister's money, using fake promissory notes! Thief and murderer!",
	"Yes, it was me! I damn well needed the money! And you hold your tongue, you pup, or I'll clip it for you! That goes for your sister, too...",
	"Only if they don't string you up first, scoundrel! There are no formalities for your kind! You'll be behind bars tomorrow!",
	"You yourself chose your fate, pup!",
	"Captain?! Sorry, but we received a report that there's a murderer here!",
	"Relax. The killer left just now. If only you hadn't held me up...",
	"Captain ",
	", in the name of the law, you're under arrest!",
	"Officer, that scoundrel Salvatore Olevarez is the real killer. He bankrupted his wife, using fake promissory notes!",
	"Do you have evidence? Where are these promissory notes?",
	"I have them, officer!",
	"Miguel was talking about them. I heard it myself...",
	"Fine, we'll resolve it. I presume they'll be examined. For now, turn in your weapons and follow me!",
	"Surrender into your mercy?! No, I've got some serious doubts whether everything will be examined properly.",
	"In that case, Captain, I'll be forced to use force.",
	"And in that case, I will be forced to use resistance against an illegal arrest.",
	"Captain, the commandant will listen to your statement. So now, turn over your weapons and follow me!",
	"Caramba, and I think my lot's bad... I've got nothing besides my word!",
	"The court will decide that... Turn your weapons over immediately!",
	"Hm... Well, no, officer, I'll prefer to leave. And I'll recommend against stopping me.",
	"Forgive me. I couldn't have known that it was you. Again, I empathize...",
	"It's okay, I'll try to catch up to that scoundrel. And you're free!",
	"Oh, oh... It looks like we're in time...",
	"You're in time for me? And with whom do I have the honor of speaking?",
	"We're in time for you, bro. You...",
	"It feels so nice when someone's waiting for you...",
	"Curses! Why the hell did you attack my ship?!",
	"You've got two problems, Captain: you messed with the wrong person, and you took the wrong person aboard.",
	"Be clearer...",
	"I'm taking Isabella Olevarez, and you'll tell me where Salvatore is. If you do that, you'll remain alive.",
	"And otherwise?",
	"Otherwise, I'll finish you here and now, scoundrel!",
	"We'll see who finishes whom...",
	"Hm. That last battle wasn't enough for you? Well, we'll see...",
	"Finally! We were starting to get bored of waiting! Allow me to introduce the captain of the brig, Rapturous. And where's the lady?",
	"Isabella?",
	"Yeah, Isabella.",
	"On my ship.",
	"Then bring her over here... Or, wait. Don't, actually. Let's go to the ship ourselves, and quietly choke her. There's no need for her to be walking the city streets.",
	"What was the point of dragging her from San Juan?",
	"That's not your concern, pal...",
	"Hm. Right you are. That's Salvatore's business. And where's Salvatore himself? Doesn't he wish to say goodbye to his wife?",
	"He's not here. He's out on business. So we just handle our business, and we're free.",
	"Understood... And where does Salvatore do his business? How can I find him?",
	"Salvatore finds who he needs, himself. Only Salvatore himself knows where Salvatore is... Hey, you're a bit too curious for your own good!",
	"Correct, since I'm not the captain off the brig Rapturous, but rather the captain that sent the brig Rapturous to the bottom...",
	"How could they have messed up this badly?! Well, buddy, it's time for you to go to next world...",
	"Thank you, but I think I'd rather stay a bit longer...",
	"Welcome to my home, Señor. Now, then: who are you?",
	"Hello there, Señora. My name is Captain ",
	", though I imagine that means nothing to you?",
	"Yes, I'm not familiar with it. So to what do I owe the honor of seeing you in my house?",
	"Well, Señora, I'm acting under an order from your cousin Isabella Olevarez.",
	"Pray, continue.",
	"Señora, Isabella has shown a desire to come to you, and I've completed her wish with pleasure.",
	"God, Captain. Can it be that you're really brought Isabella here alive and  unharmed?!",
	"It's as you say, Señora. She is on my ship, and is readying to step ashore.",
	"Oh, Señor! I don't even know how to thank you! A chain of tragic misfortunes has fallen on Isabella. She lost her father and brother, and now her husband has disappeared! You couldn't possibly imagine...",
	"Not at all, Señora. I know about all of that. Say, has Salvatore Olevarez appeared at your place?",
	"No, he hasn't. He's disappeared without a trace. Why are you asking me, Captain?",
	"I think it would be better if Isabella were to tell us everything herself. I'm convinced that your house is safe for Isabella, so we'll send her to you for now. Take her, Señora. She's had it pretty rough recently...",
	"Thank you for everything that you've done for Isabella, Señor ",
	". I will pray for you...",
	"Fine, Señora Rosita. I couldn't complain about that. God be with you!",
	"Captain ",
	"! I'm happy to see you.",
	"Likewise, Señora.",
	"Oh, it's you, Captain ",
	". What good timing! Thank God for sending you!",
	"What's happened, Rosita? Has Salvatore been here?",
	"No, I haven't seen Salvatore. But something's happened to Isabella! She's disappeared!",
	"What do you mean, disappeared? When?",
	"Yesterday morning, she went off to the market with her servant. Sine then, no one's seen a trace of her!",
	"Señora Rosita, I'll go and search at once!",
	"May Saint Francis help you!",
	"Fine....",
	"Have you found Isabella?",
	"Not yet, Señora. I am looking...",
	"Captain, did you find Isabella?",
	"Yes, Rosita, I did. But on our way to the city, we were attacked... And... Isabella was killed.",
	"I can't believe it... She put such trust in you! Lord rest her soul... ",
	"Rosita, I'm dying from grief! ",
	"Captain, I don't want to see you. Farewell.",
	"Farewell, Rosita... ",
	"Isabella! ",
	"Rosita! ",
	"You're all right! Thank God! ",
	"Now, in days to come, and to the end of time... ",
	"What happened? Where have you been? And where is Conchita?",
	"Rosita, Salvatore kidnapped me. Conchita is dead, killed by my husband... ",
	"Bastard! We must let the Governor know, such that he may arrests Salvatore immediately! ",
	"Salvatore is also dead. I was found and rescued by my guardian angel... Salvatore attacked him, but was killed in front of me.",
	"Isabella, is this nightmare really over?",
	"Yes, Rosita, it's finished... ",
	"And your loyal knight has again resolved all your problems... Isabella, you are lucky to have such an admirer! ",
	"Oh, cousin, that is true! Rosita, a bit later I'll tell you some more news, but for now let's not delay my rescuer.",
	"You are a real man, Captain! ",
	"Hmm, thank you for the compliment, Rosita... ",
	"Greetings from Salvatore, Captain! ",
	"Simmer down, now. Salvatore is dead.",
	"Unfortunately, this party was paid for in advance - and only the client can cancel his order... ",
	"Look, genius, I told you - Salvatore is dead! Do you hold nothing sacred? This is a wedding, man. We are in the house of God! ",
	"No time to talk... ",
	"Argh! ",
	"Captain ",
	", good to see you. What's news? Did you and Isabella get yourselves hitched, then?",
	"The worst news possible, Rosita... Isabella is dead, killed at the altar, right beside me... They... There were just too many of them... ",
	"Oh God, poor Isabella! She suffered so much, was so unlucky in marriage... ",
	"But then you appeared, and I thought that her life would finally change for the better. But it seems a woman cannot escape her fate... ",
	"Oh, Rosita... I've been destitute... ",
	"I understand, Captain... Excuse me, I must let our family know - we must dress for mourning... ",
	"Yes, Rosita, I understand... ",
	"What do you want, Captain?",
	"Nothing, Rosita. I just wanted to visit the cousin of my Isabella... ",
	"Señor ",
	", I'm glad to see you! We are relatives now! ",
	"Yes, Señora Rosita. Isabella and I got married... ",
	"This is wonderful! Isabella deserves so much more than that bastard Salvatore! ",
	"I completely agree. I don't even want to think about Salvatore - I sent him to hell, and and am quite glad that I did... ",
	"Señor ",
	", you are a real knight! Take care of Isabella... By the way, if there's ever any trouble, like if you and her have a fight, you are always welcome here. I'll be glad to help.",
	"Very well, my new cousin... ",
	"I'm glad to see you, cousin ",
	"Same here, Señora Rosita.",
	"Hello, cousin. I'm so glad to see you! How is Isabella?",
	"Back already, cousin? We just saw each other... ",
	"What, again?! You'll hear nothing new from me, I can assure you! ",
	"Listen, Captain. If you are this much of a bore at home, I pity my poor Isabella! ",
	"Hello, cousin Rosita. Isabella is well.",
	"Oh. So we did. Right you are. Sorry, Rosita, I shan't distract you further... ",
	"Yes? All right then... ",
	"No, Rosita. At home I am an angel, I swear... ",
	"Did you want to ask me something, Captain?",
	"Not really, Rosita. Just came by to visit.",
	"Rosita... I don't even know where to begin. Isabella... well, she locked me out. ",
	"Rosita... I don't even know where to begin. Isabella... well, she locked me out. ",
	"You know, Rosita, I had some money problems recently, and Isabella is mighty mad at me... ",
	"Rosita... If you can imagine it, Isabella somehow learned that I never quite quit piracy, as I promised before the wedding... ",
	"Thing is, Rosita... Isabella won't talk with me. ",
	"I see... You must have been a bad boy, Captain. Did you not come home for a long time, or something?",
	"Hmm, what can I say... Basically, the thing is... yes. But I am a sailor, Rosita! My job keeps me at sea most of the time.",
	"I understand, Captain... Well, I can probably resolve this. Go on home. Everything will be all right... ",
	"Rosita, you are a miracle! ",
	"Stow the flattery, ",
	", and smarten up. A woman needs to see her man, time to time.",
	"I'll definitely keep that in mind, cousin. Goodbye... ",
	"What, you mean like debt?",
	"Yes, exactly. Isabella asked me several times to pay off the debt, but at the time I just didn't have the money.",
	"Hmm, that's bad... All right, I'll tell you what to do. Make her a gift of emeralds - a ring, a necklace, and a solitaire. If emeralds won't melt her resolve, I don't know what will... ",
	"I guess that's what I'll do! Thank you, Rosita! Goodbye.",
	"Um, cousin... Forgive me for asking, but what do you mean by 'not quite?'",
	"Well, I may be a civilian now, but that doesn't mean I'm going to just lie down. When I'm attacked, I'm going to defend myself. That's reasonable, isn't it?",
	"Hm, in theory... So I take it you haven't been provoking them? ",
	"Not at all! I just take what comes to me. ",
	"I see... Well, then the only advice I can give you is to appease her.",
	"Gladly, but how? ",
	"Stones. A rainbow in a bucket. If I were you, I'd look at a sapphire, a diamond, a ruby, a large pearl... a big golden ring with a ruby wouldn't hurt, either. ",
	"Hmm, there's a thought... Thank you, Rosita. You've given me some ideas. Goodbye... ",
	"What happened?",
	"Nothing in particular... I wanted to buy her a present, but can't find anything suitable.",
	"Hm. That's no problem, then... on the surface. Is there something you're not telling me?",
	"Well. Sort of. It's just that I've been so busy that I forgot I had already promised her a gift... So I promised her again. Which... makes four times, in all... ",
	"Captain... You know you're really pressing your luck, buddy. How she can tolerate you is beyond me... ",
	"I know, I know. I screwed up. But what do I do?",
	"It's not that hard, Copernicus. Give her a present, already. And a good one. Say, three gold nuggets and five silver ingots? That would put her over the moon, I wager.",
	"Oh, Rosita, what would I do without you! I'll go scrounge for that right now. Farewell... ",
	"Yes, I am aware of this. And to you, Captain, I'll say this - your marriage has been dissolved, unilaterally.",
	"What is going on? Did the Pope himself dissolve it?",
	"The annulment is de facto. You will never see Isabella again.",
	"I don't understand. What the hell is going on?",
	"You really don't know. Then I'll tell you.",
	"Please do! ",
	"You should have spent less time in the bordellos, my dear! Isabella can forgive you much, but adultery - never! ",
	"What the hell? Who gave her that bright idea? That's slander! ",
	"Oh hush up. The information is more than genuine, and you know it. Best of luck, Captain... ",
	"Well... Farewell, Rosita... ",
	"I have no more desire to speak with you.",
};
