string DLG_TEXT_QB [56] = {
	"Hm. Don't you think you're taking a few liberties, walking into the owner's bedroom without knocking?",
	"Sorry, pal. I just wandered in...",
	"Why the hell are you walking in my house? Protect yourself, villain!",
	"Well, okay...",
	"Greetings stranger! May I inquire as to what I owe the honor of seeing you in my home?",
	"My name is ",
	". I'm a captain.",
	"I'll ask you to forgive me. I think I'm at the wrong address.",
	"A captain... Or, more likely, a corsair? Judging from your appearance, I'd put my bets on the latter. Well, then. In our time, not one don worthy of esteem has claimed a decent estate by that method. And I'm no the exception.",
	"You were a corsair?!",
	"I'll ask you forgive me. Business, and all!",
	"And what's weird about that? It's a very quick and dependable way of getting rich. But after getting married, I thought about settling down. I wish you as much luck.",
	"Understood. Thanks for the tip. I'll definitely follow it, have I the chance...",
	"It's pleasant to see you again. What's brought you to me this time?",
	"Nothing in particular. I just came by to visit.",
	"Oh, ",
	" is here again. Well, then. it's good to see you again. Why have you come?",
	"Salvatore, I want to want to talk with your wife. Can I?",
	"Don't you think you've become a bit too much of a regular visitor to my wife, buddy?",
	"Everything's okay, friend Salvatore. I'm an acquaintance of her relatives. So don't worry.",
	"Did you pass everything that was needed?",
	"Yes, Salvatore. Everything's okay.",
	"All of that is good, but from now on be so kind as to ask my permission to see her. Let's just pretend this is a respectable household, shall we?",
	"Fine, Salvatore. As you say.",
	"And why?",
	"I want to deliver her a note from her relatives.",
	"Okay, I'll allow it.",
	"Thanks, Salvatore. I'll be quick.",
	"Oh, please! Come in! You are a friend of the family now, what with your help to Miguel in Cumana... ",
	"Hm... I see, Salvatore. Thank you.",
	", have you met my wife? ",
	", if you have no objection, I shall return to my work. I'll wait for you downstairs... ",
	"Oh yes... Now I see your advice in a different light.",
	"What are you doing, in... my wife's bedroom?",
	"Oh, is that what this is? I'm sorry, this is a big house... Believe me, the thought never crossed my mind... ",
	"Defend yourself, fool, for you are about to die! ",
	"Oh? Well, we'll see about that! ",
	"My wife and I will be glad to see you this evening, Captain.",
	"I'll be there, Salvatore.",
	"Ho! Your timing is perfect, ",
	"... Kill this filthy pig. Let everyone think the two of them killed each other.",
	"Ah! There you are.",
	"Officer, this man killed poor Don Miguel de Valdez! And now, he means to to kill my wife and me! Look at his hands! The blood! ",
	"You fink! You're the one who killed Don Miguel! ",
	"Wow, look at them bill and coo! Am I interrupting?",
	"On the contrary, Salvatore. You 're just in time! If only you knew how glad I am to see you! ",
	"Really?",
	"Yes, yes, and no mistake. I have been searching the whole Caribbean for you... Tell me, did you bring a grill?",
	"I'm afraid this is not the time... ",
	"Oh come now. It's always time for barbecue. And this is the last chance you'll have. For tonight, Señora Isabella becomes a widow.",
	"Why, aren't you the noble hero.",
	"Aye, Salvatore. Aye... ",
	"Then let us begin! Good luck in hell, ",
	"You first! Let me know how it is. Incidentally, Salvatore, your wife is a fox. I don't think black suits her... maybe she'll have to mourn in white. In a church, next to me. With a new ring on her finger. ",
	"Grahhh! When I'm done with you, I'll send that bitch into the abyss after you! ",
	"No, now. Is that any way to talk about your wife? ",
};
