string DLG_TEXT_QB [608] = {
	"How did you get in here? If you don't leave my bedroom immediately, I'll call my husband.",
	"I'm ",
	". May I know the name of such a wonderful Señorita?",
	"I'll ask you to forgive me. I'm already leaving...",
	"Señora, not Señorita. I'm the lady of this house, ",
	". Why have you crept into my quarters?",
	"Calm down, Señora. I'm your husband's associate. He suggested that I tour your new home, and there are so many rooms here that getting lost was quite easy.",
	"Just curiosity! I'm already leaving.",
	"You're still here? Leave me alone!",
	"May I inquire about something?",
	"Sorry...",
	"What do you want from me? Talk with my husband. I don't want to talk to you now.",
	"Fine. I'll do that.",
	"Yes, we did buy this house recently. And what common interests do you have with my husband?",
	"Our interests intersect in the commercial sphere of influence of the Spanish crown.",
	"We're old friends, me an' him.",
	"I must be off. Forgive me.",
	"Oh. Well, I'm a bit distant from... influential commercial... er... insects... So, um. How do you like our house? I decorated it myself!",
	"Absolutely one-of-a-kind! You've got such exquisite taste!",
	"To be honest, it doesn't do much for me. I've seen something similar in an English colony.",
	"Friends? I didn't think that my husband could have friends like this. ",
	"Wait! I'll explain everything...",
	"I don't like you. I think it would be best if I called my husband. ",
	"Wait! I'll explain everything...",
	"I'm flattered. You know how to bring a woman to your side, Señor.",
	"I merely told the truth. And now allow me to bow out. I won't get in your way...",
	"To me, you're just an uncouth fool!",
	"Well... Some think otherwise...",
	"Happy to meet you again. By what fate?",
	"I just came to greet you, my dearest ",
	"Leave me, you filthy murderer!",
	"Captain ",
	"Señora! What a pleasant meeting!",
	"For the sake of God, Captain, leave him!",
	"Not before this scoundrel asks for forgiveness!",
	"This is just a small misunderstanding.",
	"Then tell me what's gone down!",
	"I came to find out why today's groceries failed to arrive as usual. I was sure that my spouse paid Señor ",
	". But it looks like he forgot. It turns out that we have been running a tab for the last month, and I didn't have the 1200 gold on me. I said that I would bring it later, but Señor ",
	" got it into his head that I would not pay at all.",
	"Take your money, you worthless huckster!",
	"Now he'll believe you, won't he?",
	"I feel a bit awkward, Captain. I'll return the money to you at once. But it's time for me to go.",
	"It's nothing, Señora Isabella. It's reward enough to have had the joy of seeing you again.",
	"I thank you. But it's time for me to go. Goodbye.",
	"It's nothing, Señora Isabella. It's reward enough to have had the joy of seeing you again.",
	"Señor Captain, I'm happy to see you. Tell me, are you the captain of the brig they call the Five Holy Wounds of Christ?",
	"The Five Holy Wounds of Christ? Gracious, a sinner like me would never have thought to call his tub by such a devout name. Still, for the sake of the wonderful Señora, I'd be ready to change not just my ship's name but my very own!",
	"Forgive me, Captain. I've made a mistake.",
	"Wait, Señora! What are you so sorrowful? Who is this lucky captain, whose fate so worries you? Is it possible that I may have heard of him, and may help you?",
	"I remember. You're a captain too, right? There's a brig called the Five Holy Wounds of Christ, that should have dropped anchor at San Juan harbor. Maybe that recent storm reached them, on the way from Cumana?",
	"Alas, Señora, I know nothing about the fate of this brig, yet I am prepared to search out your courageous captain - if you would but grant me a single smile.",
	"Oh, Señor. It's not the captain I want, may God preserve him. He has a passenger - my brother, Miguel de Valdez. I promise you a smile, if you can provide me good news about that ship.",
	"I'm leaving for Cumana immediately, charming Señora!",
	"I'll wait anxiously for news of my brother. Do you remember where my house is located?",
	"Yes, of course. All the best.",
	"Is there any news?",
	"I'll report when I learn the fate of the Five Holy Wounds of Christ. 'Til we meet again, ",
	"Miguel! How happy I am to see you! I was worried about you! It's been so long since I've heard from you! How is Father?",
	"Isabella! Were it not for this courageous captain, I might never have reached San Juan. Terrible storms raged like demons around Cumana. I bring horrible news. Our father is dead, Isabella! He was forced to sell the family estate, to pay off your promissory notes. This was a real tragedy for him, and his heart couldn't bear it!",
	"But Miguel! I didn't give out any promissory notes! This is some kind of tragic misunderstanding!",
	"Sister, you have yet to thank our remarkable captain for performing such a valiant favor. I think we can resolve our family questions later.",
	"Oh, Captain ",
	"! I'm grateful from the bottom of my heart! Forgive me! I was so shocked by my father's death that I forgot all about you! I'll be happy to see you at our house this evening!",
	"Señora Isabella! I'm always at your service. I'll ask you to excuse me now. I must take my leave.",
	"Oh, my courageous captain! I'll be waiting for you at dinner tonight!",
	"I'll certainly be there, Señora Isabella.",
	"IT'S YOU!! You murderer! You merciless hypocrite! You thief! You pirate!",
	"Señora, though I may not be without sin, I will not allow even you to sully my honor!",
	"Don't feign your innocence! Salvatore told me personally how you foully killed my brother, Miguel! Yes! Murderer!",
	"And you believed him? Señora! After all I'm prepared to do for your sake, still you presume that I would kill your brother? Señora...",
	"My brother's dead, and you ran from him! I don't want to hear your excuses!",
	"I've nothing to excuse, for I saw how Salvatore stabbed your brother. Miguel learned that it was Salvatore who forged those promissory notes that killed your father. He was going to report this to the authorities, when Salvatore killed him. I found the fake promissory notes on your brother's body. They're soaked in the blood of Don Miguel, but still readable. Here they are. Take a look...",
	"I've nothing to excuse, for I saw how Salvatore cut down your brother. Your brother learned that it was Salvatore who forged those promissory notes that killed your father. Don Miguel was going to report this to the Governor, when Salvatore killed him. He tried to kill me as well, to hide his crime. You wouldn't have believed me anyway, so I decided to leave the city for a time.",
	"You, Captain, aren't just a bloody murderer, but also a dirty liar! With what can you prove the truth of your words?",
	"Señora, I heard with my own ears how your brother bravely accused Salvatore of forging promissory notes, right to his face. And then saw with my own eyes how Salvatore and his two thugs stabbed poor Miguel! Unfortunately, I was not in time to help...",
	"You want me to believe your words? And where are these forged promissory notes for which my brother died?! Show them to me!",
	"I don't have them, Señora...",
	"There's truly no end to how low humanity can sink. Listen, Captain! I hate and deeply despise you...",
	"Señora Isabella, we have no time for talk. The ship will soon go to the bottom. I offer to continue this conversation on my ship.",
	"Listen, you foul pirate! No force in the world could force me to go with you. If I'm fated to die, then let it be here and now. As for you, Captain, I curse you for all the misfortune you've brought upon our family!",
	"Dammit, Isabella...",
	"Farewell! I won't say another word...",
	"WHAT?! Salvatore?! What underhanded lies! Promissory notes! Salvatore loves me, the villain! But that letter... this ship... I'm completely mixed up. How I want for this to be merely a dream, Captain ",
	"Letter? Ship? What are you talking about?",
	"The captain of this ship showed up at my house, with a letter written in Salvatore's hand. My husband wrote of threat toward me. He asked me to flee San Juan in the ship of the captain who delivered the letter. But as soon as the ship left the harbor in San Juan, I was locked in the cabin. Only now I understand that I've been caught in a trap!",
	"And where is Salvatore now? I think it's time to talk to him.",
	"I don't know where my husband is... God, this is just unbearable! To lose one's father and brother, and then to learn that one's husband is responsible for all of these misfortunes... ",
	"May I ask a favor,Captain?",
	"I'll be happy to serve you, Señora Isabella.",
	"Could you transport me to my cousin Rosita Fernandez, in Belize?",
	"Of course, Señora. But first allow me to visit Portobelo, since we're right nearby. I'll try to find Salvatore, since he is waiting for your arrival.",
	"Fine, Captain. But afterwards, be so kind as to bring me to Rosita...",
	"Everything will be done, Señora.",
	"Rosita",
	"Fernandez",
	"Señor ",
	", I went ashore to find out you were doing.",
	"Señora Isabella,  that is a rather impulsive action...",
	"Oh God, what's happened here?!",
	"Oh, Isabella, you weren't very lucky in marriage. These two bandits are who Salvatore hired to kill you.",
	"My murder?!",
	"That's it. As one of these guys said, Choke her quietly. They got me mixed up with the captain of the brig that took you out of San Juan, and laid everything out to me. Señora, I can't tell you how glad I am that I learned about this, and could intercept you in time...",
	"That's the truth, Captain. That really is so. There is no doubt that I owe you my life...",
	"It's nothing, Isabella. When I see you so scared and defenseless, a hitherto unseen feeling awakes in my soul...",
	"Ah, Señor ",
	". Now is neither the time nor the place for this conversation. Forgive me, dear Captain. ",
	"Let's leave this awful place!",
	"Oh, it is you who must forgive me, Señora Isabella. You're right, my timing is pretty dreadful. Anyway, let's get going.",
	"Well, here we are. What do you say, Señor ",
	"Señora, I've completed your request. I've let Rosita know about your arrival, and she is waiting for you. Beyond that, I've checked the house and learned that they have not yet arrived in the area.",
	"Captain, you certainly are my guardian angel...",
	"Say, Isabella... I don't suppose now I may speak more freely of my feelings?",
	"Go ahead, Señor...",
	"Isabella, you know that I am a privateer - an occupation unworthy of a lady such as yourself. But I love you, Isabella, and want you to know that!",
	"Captain ",
	", you are a noble man. A real knight. I owe you my life, but I want to say flat-out that my feelings for you are limited to gratitude for my rescue...",
	"Señora, if I've understood you correctly... May I hope that one day you will say yes to me?",
	"You've understand everything correctly, my guardian angel.",
	"Hot damn, I'm so happy I could just pop! I feel like a young boy! Oh... Forgive me, Señora, for my roughness. These things burst out sometimes...",
	"It's all right, Captain. I'll try to soften your manner, if I'm ever given such an opportunity.",
	"Isabella, I'm yours - from my brain to my bones. But we've still got one matter to attend to: Salvatore.",
	"And what do you plan to do?",
	"I don't know. There are no particular leads, Salvatore's always moving. But I have one acquaintance in common with him - a pirate named Attila. Salvatore owes him big...",
	"Okay, Captain. Well, I've got to rest a little bit after what's happened. I'll be waiting for you with the good news here, at my cousin's.",
	"Goodbye, Isabella.",
	"Captain, what news do you have?",
	"Nothing yet, Isabella.",
	"Oh! Here you are, ",
	"! I've finally seen you again!",
	"Isabella, you're alive! Thank the Lord! In the jungle, I found a girl that looked exactly like the girl with whom you left Rosita's house yesterday.",
	"Poor Cancita, Salvatore killed her!",
	"The villain! Tell me quickly, Isabella. What happened?",
	", my husband is hellspawn! I must admit that I made myself more conspicuous than I should have. Every day, I took a stroll around the city. Yesterday, Salvatore attacked me with another bandit. Without a pause or a thought, that second man stabbed Cancita with a knife. My God!",
	"Calm down, Isabella... What happened next?",
	"Next, they dragged me here. Salvatore tried to get me to sign over a warrant, giving him control of poor Miguel's estate. Going by the will, you see, everything was passed on to me.",
	"So that's why he didn't kill you at once! Isabella, it's quite the unexpected bit of luck that Salvatore found out about Miguel's will.",
	"I understood that the minute I signed these papers I would be dead. I collected all of my strength and refused to sign them, no matter what he threatened to do. I was just hoping that Rosita would report my disappearance, and that you would be able to find me...",
	"Well, Isabella, I'm to blame too! I left you alone in Belize with no protection! But I should have realized the danger...",
	"Don't diminish yourself, ",
	". After all, you did save me again.",
	"Isabella, I've dealt with your jailers. But where is Salvatore himself?",
	"He went to the city, and promised to bring a brazier back soon.",
	"What brazier?",
	"A brazier with pliers, to burn the soles of my feet.",
	"Damn! That really was good timing, on my part...",
	"It's all over!",
	"Finally, Isabella...",
	"Señor ",
	", I ask of you - please escort me to Rosita's house.",
	"Señora Isabella... Now that all is said and done, and that I have rendered you a widow, permit me to offer you my hand... and my heart.",
	", I accept your offer.",
	"Excellent! And in the meantime I'll try to find what Salvatore stole from you.",
	"Do as you wish, Señor. I want to just forget what happened. ",
	"Let's do this, then. I'll spent a few days at Rosita's, and then go to San Juan by myself, since nothing is threatening me now.",
	"Yes, Isabella. I expect no danger for you anymore.",
	"I'll get my things in order in San Juan, reclaim my maiden name - de Valdez - and in a month or so, we can get married in a church in the city.",
	"Very reasonable, Isabella...",
	"But you must promise me that you'll put down your life as a privateer.",
	"Señora, that would be a serious step for me. This is how I earn my living. But for your sake, Isabella, I'm ready to try anything. So... All right. I agree!",
	"Very good, ",
	". And now I'll ask you to escort me to my cousin's. I can't remain here any longer...",
	"Fine, Isabella.",
	"Captain ",
	", I'll wait for you at San Juan, in one month...",
	"Fine, Isabella. But are you sure that you can find your way there on your own, without any problems?",
	"I'll be in San Juan in a month. Be sure of that...",
	"Fine, Isabella.",
	"Señor ",
	"! You've arrived...",
	"Yes, Señora Isabella. Is everything all right?",
	"Yes, everything is fine. Now, my guardian angel, are you ready for a quiet family life?",
	"Yes, Isabella. I've had enough blood.",
	"And you still love me?",
	"Isabella, dear, how can you ask that?! I'm mad about you!",
	"Fine, ",
	". Then I'll tell you that everything is ready for the wedding ceremony. Tomorrow morning, I'll be waiting for you at the altar...",
	"Isabella... Our fates will be joined in the morning!",
	"Yes. As for tonight, however... I must ask you to leave. You've got no place here, until the wedding...",
	"Fine, Isabella. 'Til tomorrow...",
	"You've got no place here, until the wedding...",
	"Señor, be reasonable! Not until we're married! ",
	"No! No! And once again, no!",
	"Señor, my beloved, I'm asking you to leave immediately!",
	"Ah, Isabella, how can I stand it?! I want to see you know...",
	"Isabella, this is some kind of curse. I'll go mad before tomorrow!",
	"?Caramba! What can I do? Though I'm happy that, for my fiancee at least, the laws of honor do not ring hollow... ",
	"Ahh, Isabella, I am forced to yield...",
	"How dare you not turn up at the church?! I gave you my love, and you trampled it! How could you be so cruel, so ungrateful?!",
	"Isabella...",
	"That's it! I've had enough! Leave, now!",
	"Oh, Isabella..",
	"Hello, ",
	"Hello, Isabella... I've never seen you so wonderful...",
	"Thank you, ",
	". Are you ready now? May we begin?",
	"Of course!",
	"You may begin, Padre...",
	"What's happening? ",
	", I'm scared!",
	"Isabella, move aside!",
	"Were those Salvatore's people? But how can that be? You killed him before my eyes!",
	"He must have hired them before I finished him off.",
	"Oh, Lord. Can it be that I'll continue to live in fear?",
	"No, Isabella. It's over. Salvatore is gone, as are all his hired goons. ",
	"I really hope you're right... ",
	", I want to go home, as quickly as possible!",
	"Go, my dear. I'll hold out for a short while, but I'll be home soon.",
	"Dear, you need to go to the Governor and personally tell him about this incident. After something like this, we need to receive official approval to live in this city.",
	"Don't worry yourself, Isabella. I own this city - lock, stock, and barrel.",
	"Fine, Isabella. I'll do everything...",
	"Oh, dearest. How good that you've finally come home! Did you straighten out all the questions regarding the incident in the church?",
	"Oh, dearest. How good that you've finally come home! Is everything okay?",
	"Yes, dear, everything is okay...",
	"Oh, dearest. How good that you've finally come home! Did you straighten out all the questions regarding the incident in the church?",
	"Yes, dear. I had an audience with the Governor. Everything's in order. He congratulates us, even.",
	"Well, then. That's very good. Now, if you don't mind, let's discuss the principles of joint living.",
	"What principles can there be, Isabella? I love you! That's the basic principle!",
	"And I too, dear. But a family is not just love, but a combined way of life. In that way, apart from mutual love, there are at leas two principles by which this family must live.",
	"Isabella, I'm in awe of your prudence! But, maybe for now we'll just tackle that first principle... and bring it to life, right here and now?",
	"Everything has its time, dear. Don't be so persistent. Let's discuss the other two, if you're not against it?",
	"For you, dear, anything at all. All right, let's discuss the other two principles.",
	"Honey, I adore you... Now then, principle number two: finances. We must decide the family budget. Your home was your ship, but now your home is here - and you must understand that owning real estate is a particular financial burden, meaning city taxes. ",
	"Apart from that, providing for our daily necessities also means certain expenses...",
	"Isabella, I'm prepared to turn over everything that I have!",
	"Very good, but let's start with the small things... So let's add things up. On a monthly basis, you must bring into the house at least ",
	"As you say, Isabella. Anything for you! And what is the third principle?",
	"The third principle is your promise to stop privateering. Support the family in another area. Don't sink ships, or capture cities. The Lord won't forgive us that...",
	"Well, then. I'll remember my promises very well. I agree with these conditions, dear.",
	"Hell, dear!",
	"Greetings, my husband.",
	"Happy to see my spouse.",
	"Hello, Isabella!",
	"Greetings, my dear....",
	"Hello, dear! And now please explain where you were for ",
	"Greetings, my husband... Who has been who-knows where, for ",
	". Perhaps you'll tell me, dear?",
	"Isabella, dear, all this time I've been taking care of affairs.",
	"Dear, everything sort of fell on me all at once...",
	"Hello, loving husband. I've opened the door to you only because my cousin Rosita asked me to.",
	"Isabella, I see what you're saying. But please understand me, too: I'm a sailor!",
	"Listen. Of course I understand that you're a captain. That's your work, rushing to and fro across the sea. But you should understand me, as well. I'm not going to sit at home alone, for months at a time! And note, if you ever intend to leave me here for so long again, I just won't open the door to you!",
	"I get you, Isabella... Well, I am sorry that I had to leave you alone for so long.",
	"Forgive me, that you had to remain alone for so long. I see how you must have felt...",
	"I want you to understand just one thing - the interests of our family. If you think that you can just show up here from time to time, then you're deeply mistaken. We must have a family, not a farce.",
	"Fine, Isabella. I'll try not to leave you for too long...",
	"Dear, we have a problem. We are in debt, up to the gills. We have to deposit ",
	", so as to regulate our tax problems.",
	"This is the second time today that I've told you about our financial problems. We need to pay off ",
	"Look, this is third time I've told you about our debts. We owe ",
	"How many times do I have to remind you you of the bigger picture? Our debt comes to all of ",
	"?Caramba! How could I have let this go?!",
	"Wow, things have really been going to seed around the house...",
	"Is this the second time? Oh. That's unfortunate. ",
	"The third time now?! Oh, man...",
	"Yes, Isabella. I remember...",
	"Listen, everyone keeps saying that you looted some city. Is this true?",
	"Listen. I keep hearing rumors that you're back to your old ways, and looted some city. Is this true?",
	"Oh, please, dear. That's slander!",
	"My dear, I have done nothing of the sort.",
	"No, my dear. That is definitely a lie. I did promise, didn't I?",
	"Listen, everyone keeps saying that you captured some city. Is this true?",
	"Listen. I keep hearing rumors that you're back to your old ways, and captured some city. Is this true?",
	"Oh, please, dear. That's slander!",
	"My dear, I have done nothing of the sort.",
	"No, my dear. That is definitely a lie. I did promise, didn't I?",
	"Listen, everyone keeps saying that you captured some fort. Is this true?",
	"Listen. I keep hearing rumors that you're back to your old ways, and captured some fort. Is this true?",
	"Oh, please, dear. That's slander!",
	"My dear, I have done nothing of the sort.",
	"No, my dear. That is definitely a lie. I did promise, didn't I?",
	"Listen, everyone keeps saying that you boarded someone else's ships. Is this true?",
	"Listen. I keep hearing rumors that you're back to your old ways, and boarded someone else's ships. Is this true?",
	"Oh, please, dear. That's slander!",
	"My dear, I have done nothing of the sort.",
	"No, my dear. That is definitely a lie. I did promise, didn't I?",
	"Listen, everyone keeps saying that you sunk some ships. Is this true?",
	"Listen. I keep hearing rumors that you're back to your old ways, and sunk some ships. Is this true?",
	"Oh, please, dear. That's slander!",
	"My dear, I have done nothing of the sort.",
	"No, my dear. That is definitely a lie. I did promise, didn't I?",
	"Yes, dear. I'm listening...",
	"What does my dear husband want?",
	"Señor ",
	", your dearest wife is rapt with attention...",
	"Oh, I just wanted to talk... Missed you, and all...",
	"Let's see what shape our family budget is in...",
	"Dear, I've brought you a present.",
	"Listen, dear. About the family debts...",
	"I want to sleep. Have no strength...",
	"No debts, dear, but money has run out...",
	"It seems that there are no debts, and it's not like the bailiff is bursting at the door... But all the money's run out.",
	"No debts for now, but money's running out. I still have ",
	"Well. When the time comes, we'll decide...",
	"That's not my concern, right now. Spend what there is.",
	"Well, then. Let me throw you a piaster, rich girl!",
	"We need to immediately replenish the budget. Let's focus on that!",
	"No problems, dear. I've still got ",
	". Surely that's enough?",
	"Everything is normal, dear. We have enough money. Last I looked, there was ",
	"Well, then. That cheers a man up.",
	"Wonderful, dear. Very good!",
	"I want to leave you more money, so that you won't be in need.",
	"Okay, dear. How much money do you want to leave me?",
	"But you've already left me something today... I don't... Never mind, how much do you intend?",
	"Are you playing a game? This is your third time today. Can't you just save up and pay me all at once? ",
	"That's it. You're driving me insane. I shan't be speaking with you any more! ",
	"Fifty thousand.",
	"Hm... I want to leave fifty thousand.",
	"Hm... I want to leave you fifty thousand.",
	"A hundred thousand.",
	"A hundred thousand... ",
	"Two hundred thousand.",
	"Two hundred thousand... ",
	"Five hundred thousand.",
	"Five hundred thousand... ",
	"Ha... So far nothing, Isabella. Money is tight.",
	"That's how it worked out, dear... Sorry, there's no money.",
	"It didn't happen on the first try, Isabella... There's no money.",
	"Isabella, why is it so? ",
	"Fine, ",
	" thank you. ",
	"It's my duty, Isabella... ",
	"All right, dear. Thank you. A hundred thousand, that's no small change. ",
	"Oh, my pleasure, sweetheart... ",
	"Very well, dear. Two hundred thousand is a fine addition to the family coffer.",
	"I am glad that you are happy, Isabella... ",
	"So much! Where did you find so much money?",
	"Why, I earned it. Where else?",
	"Then why give it to me? ",
	"What are you talking about? ",
	"What are you trying to say, dear?",
	"Nothing, dear. It's my mistake. I am sorry... ",
	"I am sorry, dear. My memory is playing tricks on me... ",
	"My head is all wound up... ",
	"True, Captain ",
	", you have ignored this thing for way too long! So now, pay up! ",
	"You were supposed to find money to pay off your debt! ",
	"Captain, how many times do I must ask you to pay off our tax debt! ",
	"Captain, I am sick and tired of repeating myself. I keep talking and talking, but our financial burden remains. Listen to me, you little man. I can handle the problems by myself! And you don't dare show your face to me again! ",
	"All right, dear. I'm ready to pay off the debt.",
	"I found it, Isabella! I'm ready to cover our debts! ",
	"Isabella, dear, I remember quite well. I've found our money, and am ready to pay off our debts.",
	"Isabella, now... ",
	"Of course you understand, Isabella, at the moment I'm flat broke... ",
	"Darling, dear, listen... At the moment, I have no ",
	"I had to find it, but I didn't... ",
	"Isabella, I have no money right now! ",
	"Is that so... ",
	"So go find it! I have no intention to go to a debtor's prison because of you! ",
	"Listen to me, you little man! I don't want a bailiff to come by my home every other day, pestering me for payment! Come up with the money! You're the man of the house, aren't you? ",
	"Fine, Isabella. As you say... ",
	"I understand, Isabella. I'll do my best... ",
	"Well, splendid! I am so happy that my husband is a responsible man.",
	"Wonderful, dear! You are a true man... ",
	"Yeah, well... ",
	"Yeah, you bet! ",
	"Hm... I believe you, ",
	"Well, I'd rather believe you than some rumor! ",
	"I'd like to believe you, ",
	", and not some idle speculation... ",
	"That's great, dear.",
	"How wonderful! We cleared that mess in no time flat! ",
	"You know, dear, I am forced to listen to all this rumor and speculation. Yes as I can prove nothing, consider this your first warning.",
	"Sorry, I don't believe you. There is to much talk around the city about that. Consider this your second warning.",
	"Well, listen, I don't understand, do you think I am dumb? The whole city is talking, and he stands here, denying! It looks like you aren't keeping your own word. This is your last warning, ",
	"That's it, Captain ",
	". There's no more trusting you. You've been cheating me! I don't want to talk to you any more! ",
	"Fine, dear. I consider this my first warning.",
	"Fine, dear. I consider this warning number two.",
	"Mmm... Sure thing, Isabella. Consider me totally warned. ",
	"Oh, Isabella...",
	"What's up, sailor? Been at sea too long?",
	"Er... something like that... ",
	"What are you talking about?",
	"Oh... I think I see what you mean... ",
	"In debt? And what do you think I owe you?",
	"Hmm, I don't understand... ",
	"It's all about love, Isabella, love... ",
	"Yes, dear, about love... ",
	"I'm talking about the debt of love, dear... ",
	"Isabella, dear, I'm talking about love... ",
	"If I were you, dear, I wouldn't stay away so long.",
	"Why is that?",
	"Because you have a beautiful wife, in case you haven't noticed. And because not only women live in San Juan, but also many interesting caballeros...",
	"What the hell, Isabella... What are you on about?",
	"I'm just saying, you would do to spend more time at home, dear! ",
	"All right, Isabella, I understand... Let's not fight... ",
	"Okay... I'm going to the bedroom... ",
	"And I'm coming right after you! ",
	"Fine, dear, we won't fight. But today I have a headache, so nothing will happen. I am sorry... ",
	"Yergh... what timing. ",
	"You know what, buster... You blew it. I'm not going to wait for you here forever, primed and ready for your return.",
	"Well, Isabella? What about you?",
	"Mm... I like such conversations... ",
	"About love? All right then. Go on, dear... ",
	"Love sounds interesting... So what about it?",
	"Ah, love... I have been known to dally, from time to time! ",
	"Isabella, I am burning with passion! ",
	"Isabella, I am burning with desire to share my bed with you! ",
	"Isabella, the desire to have you is stronger than me.",
	"Isabella, what kind of nonsense is this?! Let's go to the bedroom quickly, dear... ",
	"Love shouldn't be the subject of frequent conversation, dear. I'm sorry, but nothing will come out of this... ",
	"No, dear, frequent conversation about love bring harm to the soul and body. Or so the padre says... ",
	"Oh dear, I don't want to discuss this topic too much. Let's not tire me, hmm? In a few days, dear... ",
	"Hrm... Hmm... A pity... ",
	"Well, that blows my evening.",
	"Then I'll wait for you in the bedroom, dear! ",
	"Isabella, I'm following you... ",
	"To share my bed? Well, fine. I'm going to the bedroom... ",
	"Oh, Isabella... ",
	"I have a headache, dear. Not today... ",
	"Oh, dear. I'm not feeling very well. Not today... ",
	"Dear, I feel ill... let's postpone this, shall we? Later, perhaps... ",
	"Urgh... Just at the wrong moment... ",
	"The devil! Oh... Oh forgive me, Isabella. It just shot out... ",
	"Desire... Mmm, fine. I'll wait for you in the bedroom, dear... ",
	"In a moment, Isabella! ",
	"I have a headache, dear. Not today... ",
	"Oh, dear. I'm not feeling very well. Not today... ",
	"Dear, I feel ill... let's postpone this, shall we? Later, perhaps... ",
	"Urgh... Just at the wrong moment... ",
	"The devil! Oh... Forgive me, Isabella. It just came out... ",
	"Dear, you are such a brute! Fine, you've convinced me... ",
	"Isabella... ",
	"That's it, we're not going anywhere. And in the future, I'll thank you to stem the tide of such vulgar ejaculations!",
	"I... heh... Ahem. I'm sorry, Isabella... ",
	"Mmm... dear, that was... wonderful! ",
	"So, how are you, sweetheart? Feel good?",
	"You seem out of shape today... ",
	"Oh... Love, it is grand... ",
	"Thank you, darling... ",
	"Wonderful, darling. You were simply amazing! ",
	"Hmm... Forgive me, darling. It just didn't happen... ",
	"I fully agree with you, darling.",
	"When would you like me to wake you up, dear?",
	"In the morning, if you can... ",
	"I'll have to get up at night, Isabella.",
	"I want to get a good sleep. Wake me up tomorrow morning.",
	"All right, I'll wake you up tomorrow.",
	"Great. Then I'm going to the bedroom... ",
	"You know, I've changed my mind. I'm going to stay awake for a while.",
	"All right, I'll wake you up after midnight.",
	"Great, my dear. Then I'm going to the bedroom... ",
	"You know, I changed my mind. I'd better spend this time on my feet.",
	"Listen, I heard you treated your friend Attila badly. People say you gave him very little money; I know he did so much for us... I am simply shocked! ",
	"Dear, it's all in the past. We mustn't dwell...",
	"Dear, I heard you thanked your friend Attila. This is a noble act, and I'm happy my husband is a real man; a man of dignity! ",
	"Isabella, how could it be otherwise?",
	"Dear, you never mentioned, but I've learned that you gave your friend Attila a very large amount of money. I suppose this is in gratitude for all that he did for us. Dear, you've given me yet more proof that you are the best man in the world!",
	"Isabella, What're you talking about? It's not a big deal, really. All I did was pay off a debt... ",
	"Oh, dear, I am so flattered to have your attention... ",
	", you're a true knight... ",
	"Oh God, I'm so fortunate you've sent me such a man as ",
	"Yes, dear. You're pretty swell yourself. ",
	"You know, Isabella, I often think how wonderful it is that we chose to entangle our fates... ",
	"Dear, did you know that the Governor was asking up about us?",
	"The Governor asked me recently how things are with you, dear.",
	"Yesterday I met the Governor in the street, and we talked. He was asking how things are with you.",
	"Ah, yes. Next time you see him, you can tell him I'm fine.",
	"The Governor seems to be paying a lot of attention to you...",
	"And what do you want to give me, dear?",
	"Come on, what's my present? Oh, I can't bear the suspense! ",
	"And what do you want to give me, dear?",
	"Oh, another present? Hmm... What is it?",
	", what is this? Why are you taunting me with these presents? What is it this time?",
	"You moron! That's it, I'm sick and tired of you! Don't you talk to me anymore! ",
	"Nothing of the sort... ",
	"I'm sorry. I've nothing worthy of my wonderful wife's attention... Save myself, perhaps.",
	"Isabella, forgive me. Again I failed to find anything suitable for you...",
	"Isabella, I'm sorry! ",
	"Thank you, darling. You're too kind. I do so like sapphires...",
	"Whee, see how it sparkles in the sun! Oh, thank you, my dearest... ",
	"What an amazing gem! Thank you, my dear... ",
	"Not at all, darling... ",
	"I want you to be the most beautiful woman on the world! ",
	"It's all for you, sweetheart... ",
	"Oh, a diamond... I'm going to lose my mind! Sweetheart, let's go upstairs! ",
	"With pleasure, sweetheart.",
	"Thank you, dear. You're too good to me. I've always been fond of diamonds...",
	"Whee, see how it sparkles in the sun! Oh, thank you, my dearest... ",
	"What an amazing gem! Thank you, my dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on the world! ",
	"It's all for you, sweetheart... ",
	"Oh, a ruby! I do so love their color... like blood! Dear, you made very happy. Let's go upstairs, you and I...",
	"That's just what I was thinking, missus me...",
	"Thank you, dear, you're very kind. I have always been fond of rubies.",
	"Whee, see how it sparkles in the sun! Oh, thank you, my dearest... ",
	"What an amazing gem! Thank you, my dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on the world! ",
	"It's all for you, sweetheart... ",
	"An emerald! Oh, this is my favorite stone... You're spoiling me, sweetheart... How about we go upstairs and I spoil you about, hmm? ",
	"Darling, you can destroy me if you like! ",
	"Thank you, dear, you're very kind. I have always been fond of emeralds.",
	"Whee, see how it sparkles in the sun! Oh, thank you, my dearest... ",
	"What an amazing gem! Thank you, my dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on the world! ",
	"It's all for you, my dearest... ",
	"Mm, gold! A very good present. Thank you, dear.",
	"Whee, look at the size of this nugget! Thank you, dear.",
	"What a wonderful nugget! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the richest lass in the Caribbean! ",
	"It's all for you, my dearest... ",
	"Thank you, dear, you're so kind. Sapphires look so well on me...",
	"Oh, how great this sapphire looks in a silver setting! Thank you, sweetheart... ",
	"What an extraordinary ring! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Oh, a ring - with my favorite emerald! You're spoiling me, sweetheart... Hey, my big old rogue, how'd you like to take your woman upstairs? ",
	"Why, you saucy little wench!",
	"Thank you, dear. You're too kind. Emerald rings do so become me! ",
	"Oh, see how the sun glints off its gold setting! Thank you, sweetheart... ",
	"An amazing stone, in a noble setting! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Thank you, dear, you're so kind. Sapphires look so well on me...",
	"Oh, how well this sapphire looks in a gold setting! Thank you, sweetheart... ",
	"What an extraordinary ring! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Thank you, dear. You are too good to me. Such a huge pearl it is! ",
	"Oh, a pearl... I see that business is booming on the Coast. Thank you, dear.",
	"What a magnificent pearl! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Thank you, dear. You're too kind... ",
	"Oh, a pearl... I see that business is booming on the Coast. Thank you, dear.",
	"What a magnificent pearl! Thank you, dear... ",
	"Ha...",
	"Hm...",
	"Oh... What a precious little thing, this cameo... Thank you, dear.",
	"What a precious little thing, dear. Thank you... ",
	"A fine piece of jewelry! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Oh my. Oh dear, this brooch is worthy of a queen! I insist we go upstairs and try it out!",
	"No argument here, your highness...",
	"Thank you, dear. You are too kind. This gold brooch is quite beautiful... ",
	"Oh, how it sparkles in the light! Thank you, dear... ",
	"Magnificent stones, in a fine setting! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Oh dear, this pendant... I am just crazy about you. I insist we go upstairs right this moment... ",
	"Why? What's up there? Oh... Oh, you sacy lady you!",
	"Thank you, dear. You are very kind. These pendants look just fine on me... ",
	"Oh, how these emeralds sparkle in the light! Thank you, sweetheart... ",
	"Magnificent stones, in a fine setting! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"Er... That's all right, dear. You can keep it...",
	"Hrm. You seriously think I'd wear that? ",
	"Oh Lord, dear! What taste! You must have been raised in a barn if you think I'd ever wear that for you! ",
	"Oh? Oh... well... okay then... ",
	"Whoops...",
	"Ah, silver! Well, fine. I'll take it. It may come in handy...",
	"Silver! Fine, give it here... ",
	"A silver nugget? Why would... well, hmm... Silver is quite valuable, in big enough quantities. Fine, I'll take it... ",
	"Not at all, darling...",
	"I want you to be the richest lady in the Caribbean! ",
	"Emeralds and rubies - my two favorite stones! This ringlet is simply superb! You are spoiling me, dear... Hey, since you're here, let's you and I head upstairs...",
	"Well, if you insist...",
	"Thank you, dear. You are too kind. This ring is very pretty, with the ruby and all... ",
	"Oh, the gold setting does suit that ruby... Thank you, dear.",
	"Magnificent stones, in a fine setting! Thank you, dear... ",
	"Not at all, darling...",
	"I want you to be the most beautiful woman on Earth! ",
	"It's all for you, my dearest... ",
	"I have no desire to talk with such a bore! As if silk and gold ringlets and sapphire settings will melt my heart... ",
	"I don't wish to talk. I am mad at you, you cheap bore! I want silver and gold and sapphire rings... ",
	"Oh, Isabella...",
	"Oh, fine, my sweet husband. I can't stay mad at you. Just let's not be so cheap, hmm? And also, let's not spend money we don't have, all right? ",
	"All right, Isabella. I'll do my best... ",
	"Oh, this is just what I wanted - a gold and silver ring, with sapphires! Hmm... You do know how to please me... Well, all right. We are on speaking terms again...",
	"Well, that's a mercy!",
	"Listen, my little man, you are incapable of supporting your wife. I had to deal with our financial problems myself. That just won't do! ",
	"If you think about it, I have to deal with all our family problems myself! I am amazed with your inability to support your family! ",
	"Signora Isabella, it's beyond my control...",
	"All right, I'll forgive you this time - but make sure you repay the debt in full! And watch out for that interest!",
	"Fine, Isabella. Whatever you say, Isabella.",
	"You bastard, you know how much I like emeralds! Well... well, all right... I forgive you, but... But you make sure you repay the debt in full! And watch out for that interest!",
	"All right, Isabella. All right... ",
	"You broke your promise to me before the wedding! I have no more desire to see you...",
	"You promised you'd be done privateering and yet you didn't even think to stop spilling innocent blood!",
	"Now, Isabella. It's not like I meant for this to happen...",
	"Look, my husband... if I forgive you, you must agree to hold to your promise!",
	"All right, Isabella. I'll do whatever you want me to. No more buccaneering, dear... ",
	"Oh, ",
	", you do know how to placate me... But remember your promise! I'm going to hold you to it! No more piracy! ",
	"Oh, Isabella. Think no more of it. I can't live without you... ",
	"No, it's simply impossible to live with such a man! And why must you so liberally shower me with these phantom gifts? For you, there are no words...",
	"You dolt! You insufferable moron! I don't want to talk with such a... such a brute! Thanks for all those empty boxes, dear. Empty boxes and empty promises! ",
	"Come on, Isabella. Be fair, won't you...",
	"Why are you angry? It wasn't deliberate...",
	"Okay... all right, I forgive you. But stop making me promises you can't keep, you idiot!",
	"Okay, my bunny. I'll be more careful...",
	"It's... it's incredible! And so you bring me the one thing I actually want right now - ingots, of gold and silver! Well... well, okay. We are on speaking terms again. But stop being so callous with your promises, won't you! There's only so much disappointment the heart can take!",
	"Yes, Isabella. Whatever you say, Isabella...",
};
