string DLG_TEXT_CZ [19] = {
	"Can I help you?",
	"What do you need?",
	"I've changed my mind...",
	"Maybe later.",
	"wounds",
	"I'm listening.",
	"You know if a ship called The Wounds of Christ has docked here?",
	"wounds",
	"Oh, yes, Señor, it's come back. They hit a storm and lost their mainmast. They're lucky they got back okay.",
	"And where might I find the Captain?",
	"I reckon he slipped out to a tavern, not long since...",
	"Thank you.",
	"wounds",
	"What? Do I look like I work with the Secret Intelligence Agency of ",
	"Well, okay... See you later.",
	"Okay... How about this, then...",
	"What am I, a librarian? How the bloody newt should I know?",
	"You... you are an idiot. Good bye!",
	"Well, how about another question...",
};
