string DLG_TEXT_PRS [17] = {
	"Speak. I'm listening.",
	"I'm mistaken. Farewell.",
	"Lieutenant, I'm not going to beat around the bush. I want the imprisoned Morris Williams to be freed.",
	"Officer, I know that you're holding three Spanish men. I think that Morgan captured them.",
	"Hm... Well, I value your candor. I'll admit that I'm also not one to be for arresting and keeping a man under watch.",
	"But I am a military man, and won't go against my orders in any circumstance. I'll ask you to make a request of the Governor-General, and wish you luck.",
	"Why the Governor-General?",
	"Because Morris Williams was arrested under his written order.",
	"I understand... Say, lieutenant, would I be able to speak with Williams?",
	"I should think you would. But now, not later. And choose your words well.",
	"Thank you, Lieutenant",
	"And?",
	"And nothing. I just want to give them freedom.",
	"This matter is beyond my ability.",
	"I, on the other hand, believe that you should express quite a deal of interest. If you value your life.",
	"Why, I've never seen such insolence! Take the fool away, will you... ",
	"Well, you asked for it. Tell me if you didn't.",
};
