string DLG_TEXT_BR [25] = {
	"Questions, dearie?",
	"What do you want, handsome? Don't be shy. ",
	"Still not satisfied?",
	"Hehe, third time today. You're sure the inquisitive one. ",
	"Hmm, I'm getting a good feeling about you. How's about you pick out one of these beauties for yourself?",
	"Sorry, never mind...",
	"Hm. Well, all right...",
	"Nah, got nothing to ask this time.",
	"Yeah, um. Well, you seem like a good person to ask... ",
	"Um. Maybe later?",
	"Listen... ",
	", I'm looking for Sharpe. Have you seen him around?",
	"Far's I know, Sharpe took off for ",
	"Heh! Many thanks, ",
	". I owe you one!",
	" which is in ",
	"the brig called the Sharpnose",
	"Sharpnose operates out of ",
	" in the town ",
	"I do indeed. He's resting here, in my establishment. I can call him, if it's urgent.",
	"Do me a favor, ",
	"I don't know. Haven't seen him in a long time.",
	"I see... Well, you have my thanks, ",
	"Bartholomew, my dear boy! Come inside; you have a visitor!",
	"Oho. I see that Sharpe's a popular man around here...",
};
