string DLG_TEXT_BR [38] = {
	"Questions, dearie?",
	"What do you want, handsome? Don't be shy. ",
	"Still not satisfied?",
	"Hehe, third time today. You're sure the inquisitive one. ",
	"Hmm, I'm getting a good feeling about you. How's about you pick out one of these beauties for yourself?",
	"Sorry, never mind...",
	"Hm. Well, all right...",
	"Nah, got nothing to ask this time.",
	"Yeah, um. Well, you seem like a good person to ask... ",
	"Um. Maybe later?",
	"Listen, a while back a certain Jackmann... uh, slept here, with a company of corsairs...",
	"Listen... ",
	", I'm looking for Sharpe. Have you seen him around?",
	"Watch your tongue, boy. Men come here for the company of ladies, not for each other. There are other places for that...",
	"Yeah. Um. I mean they were all together, in the same party. ",
	"Yeah, I remember that night. I don't know how much of a party it was, though. I've been trying to repress it, tell you the truth. ",
	"Why's that? If I may ask.",
	"They took over the whole place! Every girl, all night! It was horrible.",
	"I get you. So, okay. Did you hear about someone trying to sell a book, something like the Bible?",
	"No, that doesn't ring a bell.",
	"Maybe your girls know?",
	"Maybe they do, maybe they don't - I don't care. Go ask them yourself.",
	"Who should I ask? Who was there that night?",
	"They all were! You're going to have to ask them all. Who knows - maybe one of them will remember something...",
	"Thanks. I guess I had better get started...",
	"Far's I know, Sharpe took off for ",
	"Heh! Many thanks, ",
	". I owe you one!",
	" which is in ",
	"a brig called The Sharpnose",
	"Sharpnose operates out of ",
	" in the town ",
	"I know. He's resting in my establishment. I can call him if this is urgent.",
	"Do me a favor, ",
	"I don't know, haven't seen him in a long time.",
	"I see... Well, you have my thanks, ",
	"Bartholomew, my dear boy! Come inside, you have a visitor!",
	"Heh, I see that Sharpe's in favor here...",
};
