string DLG_TEXT_BR [122] = {
	"Questions, dearie?",
	"What do you want, handsome? Don't be shy. ",
	"Still not satisfied?",
	"Hehe, third time today. You're sure the inquisitive one. ",
	"Hmm, I'm getting a good feeling about you. How's about you pick out one of these beauties for yourself?",
	"Sorry, never mind...",
	"Hm. Well, all right...",
	"Nah, got nothing to ask this time.",
	"Yeah, um. Well, you seem like a good person to ask... ",
	"Um. Maybe later?",
	"Listen, I'm looking for a certain Pierre Picardie. He wouldn't be here, would he?",
	"So what're you in the mood for, handsome?",
	"Azzy sent me. He told me...",
	"So what're you in the mood for, handsome?",
	"You again?",
	"Gosh, you're like a broken record.",
	"You got anything else?",
	"Listen, I need to find Azzy immediately!",
	"Yes, me again. Seriously, I need to find Azzy.",
	"Gosh, you're like a broken record.",
	"Yeah, I know. I still need Azzy.",
	"Oh, who's this I see?!",
	"It's me, Margarita. But this time I've come with a hard offer.",
	"You again?",
	"Me again. How's about fetching Azzy for me?",
	"Listen, ",
	", I'm looking for Sharpe. Have you seen him around?",
	"He's not in, but you can bet he'll be by today.",
	"Pierre? You just asked me about 'im. Answer's still the same.",
	"Again with the Pierre?",
	"Listen, sweetie, enough with Pierre. Take a nice browse. Enjoy yourself.",
	"And how do you know that?",
	"Yeah, that's for sure...",
	"Hmm, again...",
	"Be glad to... some other time. ",
	"Dearie, how don't I know! Since he got back, I ain't had a day free of him! And every day, it's a new girl. I've taken to charging him double just for the distraction. If you're so hot to find him, sugar, just stick around.",
	"Thanks, but I've got stuff to do. I'll be back. ",
	"Sorry to interrupt... Name, please?",
	"Hm? Oh, the name's ",
	"Been waitin' for you, handsome. Azzy's been telling me you've got somethin' you need me doin'. ",
	"That's about right. Thing is, I don't even know how to describe what I need... ",
	"So what's with the cock-up out there? You know Azzy. You're expecting me...",
	"Azzy tells me you're a witch.",
	"And here you just thought I was wicked. And who might you be, for Azzy to be worryin' his little behind about you? ",
	"Just an associate...",
	"Uh-huh. I see... And here I thought you was some kinda big shot in our ranks. But you're just dancin' on the water, ain't you.",
	"Well, all under the bridge. Let's get down to business, handsome. Azzy says I should redress your body to fulfill your especial desiderata. What are your desiderata, son?",
	"Well, for starters, how's about you and me swing by the tavern for a drink. You free tonight?",
	"Look, you can stop right there. I'm just gonna tell you the once, I ain't interested. The day I settle my affairs with good old Azzy, it'll be in person.",
	"So okay, maybe I wasn't specific enough. What I can do is I can make you stronger, smarter, more agile. I can build up that endurance, help you concentrate. And I can do wonders with that charisma of yours.",
	"So, what would you like to change?",
	"Yeah, that sounds good. Stronger, smarter, more charming, more alert... yeah, I'll take the works. ",
	"Well, you ain't gettin' 'em.",
	"Excuse me? Look, I don't mind some rejection, but I didn't come here to get gypped. Azzy said...",
	"Listen careful, son. I'm gonna use small words and I'm gonna stay nice. You wanna be stronger, it's gonna take a bunch of big, new muscles on you.",
	"You wanna be nimble, I gotta swap your tendons for ones with more elasticity.",
	"You want more stamina, I'll have to change up your ligaments.",
	"And you can go on down the list. You take everything, you wind up with nothing. The queer one is luck. By which I mean departing an unprovidential situation with a modicum of dignity. That one takes a precise balance of the humors.",
	"So don't be an idiot. Make up your mind, while I'm still feeling gracious.",
	"I see. So I have to make a choice?",
	"Yes you do. So what's it gonna be? ",
	"Power",
	"Insight",
	"Reaction",
	"Authority",
	"Talent",
	"Endurance",
	"Success",
	"Power, always a fine choice. Well then, let's prepare the muscles and start replacin'. There ain't no time like the present, so let's get to it.",
	"Get to what, exactly?",
	"Insight, very good. Well then, let's prepare the new sensory organs and start replacin'. There ain't no time like the present, so let's get to it.",
	"Get to what, exactly?",
	"Endurance, good. Well then, let's prepare the ultrastrong ligaments and start replacin'. There ain't no time like the present, so let's get to it.",
	"Get to what, exactly?",
	"Authority? You got it, pretty boy! Well then, let's prepare a cutie pie mug with masculine features and start replacin'. There ain't no time like the present, so let's get to it.",
	"Get to what, exactly?",
	"Talent, good choice. Well then, let's prepare new and improved brain matter and start replacin'. Don't worry, your memory will remain with you. Now, there ain't no time like the present, so let's get to it.",
	"Get to what, exactly?",
	"Reaction, very good. Well then, let's prepare ultraelastic ligaments and start replacin'. There ain't no time like the present, so let's get to it.",
	"Get to what, exactly?",
	"So you wanna be a successful and lucky pirate, eh? A wise choice. Well then, let's prepare new... everything! New muscles, new ligaments, new eyes and ears, everything new! None will boast especially brilliant attributes, but all will be pretty solid. Now, there ain't no time like the present, so let's get to it. ",
	"Get to what, exactly?",
	"What do you mean? To the operation, of course! We'll be cuttin' you open, boy! Ha-ha-ha!!",
	"Umm, I don't know if I like the sound of that...",
	"Relax, guy, you won't feel a thing! First we'll replace your liver real quick, then trim your folds and valves... ",
	"And I'm supposed to just sit back and watch you do it?!",
	"Heh, you've sent countless men to their deaths but can't handle the sight of your own blood? What kind of corsair are you?! ",
	"Watch your tongue, witch, I ain't afraid of nothing! I just want to keep my sanity through it all. Watching a show like that is a sure way to knock a screw loose.",
	"Alright-alright, we'll use an anaesthetic. You big baby, ha-ha! Here, drink this, it'll knock you out cold. You'll wake up in exactly two days with the job already done. But know that once you wake - I don't know you and I don't wanna know you.",
	"Heh, don't worry, I'll manage. Now hand over that poison of yours. And be careful with my organs - I plan on using 'em for a while longer...",
	"Alright, let's have a look here... Nah, sonny, I don't have a proper replacement for that. Sorry, but my stock isn't exactly infinite, and you really shouldn't be complaining about what you've already got... Pick something else.",
	"Stop it, I'm blushing... Anyway, can you give me a minute to consider my options?",
	"I don't know who you're talking about.",
	"You think this is a joke?! I need Azzy! Now where can I find him?",
	"Sir, the whole city can hear you! Azzy cannot be found, I personally will only get a chance to see him on Walpurgis Night. I cannot help you.",
	"Damn you, hag!",
	"Hmm, that's interesting.",
	"How about you summon Azzy using three crystal Toltec skulls?",
	"Hrm, I heard about those things. Toltecs use them for various mystical rituals. But to summon a demon I would need one more thing, a strange object...",
	"I know all about it. So, are you willing to perform the ritual?",
	"Bring me the necessary ingredients and I'll do it. But keep in mind that I will keep the objects as payment for my services. And another thing - demons don't like being bothered for no reason. So think long and hard, lest you find yourself in the world beyond...",
	"Don't worry about Azzy, I have his word that he won't touch me if I summon him. And I agree to let you have the objects as payment.",
	"I'm ready to perform the ritual. Do you have the ingredients?",
	"Yes, here they are. I want you to begin right away!",
	"No, I'm still looking for 'em.",
	"Come back when you find them.",
	"Got it, I'll keep looking.",
	"Then begin I shall! Ha-ha-ha! (casts spell)",
	"Whoa, that's some weird language...",
	"Far's I know, Sharpe took off for ",
	"Heh! Many thanks, ",
	". I owe you one!",
	" which is in ",
	"a brig called The Sharpnose",
	"Sharpnose operates out of ",
	" in the town ",
	"I know. He's resting in my establishment. I can call him if this is urgent.",
	"Do me a favor, ",
	"I don't know, haven't seen him in a long time.",
	"I see... Well, you have my thanks, ",
	"Bartholomew, my dear boy! Come inside, you have a visitor!",
	"Heh, I see that Sharpe's in favor here...",
};
