string FOOD_TEXT [24] = {
	"Rats on the ",
	" have spoiled ",
	" have devoured ",
	" have destroyed ",
	" units of ",
	"On the ",
	", disease has killed ",
	"On the ",
	", medicine supplies are low",
	"On the ",
	", disease has killed ",
	"On the ",
	" all the rum has been drunk",
	"On the ",
	" there is sufficient rations for ",
	"We urgently need to replenish our stores!",
	"The slaves have instigated a revolt!",
	"On the ",
	" the crew is starving and morale is dwindling!",
	"The sailors are dying of hunger",
	"The slaves are dying of hunger",
	"Mutiny on the ",
	"Mutiny on the ",
	"The ship has left the squadron",
};
