string DEFAULT_TEXT [30] = {
	"Once or twice a year, a caravan of some dozens of merchant vessels leaves Portobelo, guarded from all sides by battleships. They call it the 'Golden Fleet'. It always follows the same route: from Portobelo, it heads north to Havana, then across the Atlantic to Europe. It goes without saying that the Fleet carries treasures beyond imagination or tally.",
	"Did you know that when you see someone's fleet attacking a colony, you can help in taking it? What you need to do is sail up to the flagman of the attacking squadron, send a boat out to it, and discuss the terms with the admiral.",
	"It turns out that if a fleet attacks a colony, you can help in the city's defense. To do that, you need to press through the jungle, enter the city, and discuss terms with its governor.",
	"Sometimes you can get valuable information at the tavern, from either the staff or the customers - given that every newly-arrived person heads to the tavern first thing.",
	"To get into an enemy city, you can land at the nearest bay and make your way through the jungle the city gates. It's better to do this under cover of night.",
	"Hey, Captain - just a note. If you've taken an enemy captain prisoner, don't be too quick to finish him off! See, a rich prisoner can fetch a handsome ransom. Otherwise, you can just set him down on some desert island. That can be fun.",
	"The climate here is hot and humid, but from April to October the rainy season kicks off, with tropical downpours and bitter storms. I don't wish for anybody to end up in a storm like that, on the open sea!",
	"To profitably trade, you need to know the juicy trade routes, to have an informed grasp on the market, and to hold good relations with storeowners. A good treasurer also does wonders for bookkeeping.",
	"Remember, Captain, in sea battles the most frightening attack is the broadside. So try to attack the enemy using the side cannons. While you're at it, try to avoid setting yourself up for an enemy broadside.",
	"When faced with a stronger opponent at sea, it's often better to turn tail than butt heads. But to escape, you need to be pretty fast. When the situation is hopeless and your only option looks like retreat, it's better to jettison your cargo, to lighten the vessel. That should give you at least a small speed boost. With luck, it'll be enough.",
	"Those who have decided to work in piracy can hear valuable information about rich merchants in the taverns. But the regulars won't spill their info to just anyone. Only a man with a dark past may hope for such a favor. Though gold, of course, opens all doors.",
	"To gain the favor of a country's governor-general, and claim yourself a privateer's license, generally you need prove your service with exemplary duty to the governor of one of that country's colonies. That said, it's not unheard of for famous pirates to have become privateers by buying a patent from unscrupulous agents.",
	"For the head of an arrogant pirate or a clever bandit, the colonial powers often put up huge rewards. And then adventurers from the entire New World set out after him, by land and by sea.",
	"The life of a pirate is pretty risky business, which is why they often hide treasure in out-of-the-way places, drafting up maps so they can find their way back again. Today, maps like these are pretty common around the archipelago, and can be bought from all manner of shady characters.",
	"To control a ship well, you need an experienced crew. A good team is truly rare, which is why it's important to conserve your men in hot sea battles. A skilled doctor can keep your crew losses to a minimum, and keeping a stock of medicine on board can't hurt. ",
	"On medium and large ships, there is, apart from your cabin, a wardroom - an excellent place to issue officers their respective instructions.",
	"Buccaneers were renowned as skillful hunters and marksmen. The secret to their success is that they always keep their arms in excellent form. So don't forget to buy bullets for your pistol, and to carry a fine quality of gun with you. ",
	"Remember that everything you do influences your reputation. The world is awash with rumor, and you're no more immune than anyone! A bad reputation can put a big kink in your commercial dealings, but it can help to intimidate your opponents. They may even surrender without a fight! ",
	"Keep a close eye on your crew's morale. When it dips, your men are on the verge of mutiny. Such a crew can be calmed with money... or with rum, of course. An unprofitable move is better than mutiny.",
	"They say 'round these waters, you could encounter a ship queer for this sea - a xebec they call the Bluebird. It's quite the skipper, just as good near the wind as down it!",
	"No one knows who owns the famous Bluebird. Some pirate; that's all she said...",
	"If you meet the Bluebird at sea, consider your hold empty. It's fruitless to fly; she will catch you, and mop you dry...",
	"The Bluebird is a real curse to merchants. God forbid you meet her at sea...",
	"It's not just on the West Coast that you find pearl divers. They're here too! They just try to keep a low profile...",
	"They say Bartholomew Sharp is pretty bent on robbing pearl divers. What's his deal, I wonder?",
	"Talk to the merchant! I hear he's looking to employ a brave captain. Decent pay, too!",
	"They say the Bluebird has begun to itch the local merchants. So now they're looking for a captain to relieve them of these problems...",
	"You know, there's a queer story - about three years ago, a pirate captain, name o' Chad Capper, sailed off to sea and vanished. What could have happened to him?",
	"They say that somewhere on the continent lies the city of Tenochtitlan. 'Course, the Spanish long since killed all the Aztecs, so the city lays in ruins now.",
	"You know, they say back in the day of the conquistadors, the Spanish razed an Indian civilization. Aztecs, was it? So now their capital sits deserted...",
};
string NO_RUMOUR_LSC_TEXT [5] = {
	"News? What news? Nothing ever happens here...",
	"Gossip? Ha. 'Til the next storm blows, it's gonna calm as a graveyard 'round here.",
	"Nothing much. I wouldn't get my hopes up.",
	"New? You do know where you are, right? No amnesia?",
	"No news, no gossip. Until the next storm, of course.",
};
string NO_RUMOUR_TEXT [5] = {
	"Nothing lately. Life is tranquil here. Just lie back and soak in the wonder of it all...",
	"This is a land of peace and harmony. Ships come infrequently, so since your arrival no truly important events have happened.",
	"The arrival of your ship - that's the latest buzz around here!",
	"Somehow I can't rightly recall an event worth a mention. Even bar brawls are rare 'round these parts...",
	"Oh, hardly. Ain't heard nothin' for a long while now...",
};
string POOR_RUMOUR_TEXT [10] = {
	"They say somewhere in the Caribbean there is the queerest island. He who sets foot there never lifts it again...",
	"Ah, me... There is no justice in the Caribbean. Yet I hear there is one island where the lowest become lords - an island that rests not on the sea floor...",
	"Ah, lady justice - the dream of the oppressed and downtrodden. They say there is an island in the Caribbean where justice prevails!",
	"The Island! The Island of Justice! It's no fairy tale, I tell you - it's truth!.The Island exists!",
	"Ah, the Island of Justice... so inaccessible. Yet not wholly so! 'Course once there, I doubt you could leave... but personally, I'd just like to get in...",
	"Ah, me... In this city, I am nobody. But my time will come, and fate will smile upon me. I but need to reach the Island...",
	"Men tend to aspire to perfection. So I too wish to go to the land where justice reigns. Mind you, I'll find my way for sure! ",
	"In all fairness, I must admit drink is my true foe. Now my only remaining course is to the Island of Justice. Oh, if only...",
	"Don't think for a moment these legends are just that. They're all true! It's just, no one knows the way there...",
	"If only I could find a course to the Island. I'd set sail the same day!",
};
