string SIEGE_TEXT [67] = {
	"They say some local fishermen saw a powerful ",
	" squadron in the waters near here.",
	"They say the ",
	" squadron that plundered our city is still in the nearby waters. Oh, if only a brave Captain were to dare strike back for us...",
	" squadron of military vessels",
	"What, haven't you heard? We're under attack! The ",
	" fleet is in our harbor! The fort might fall at any moment! And if it does... Surely that's the beginning of the end!",
	"Ah, what a glorious day for ",
	"! In ",
	", we sure bagged ourselves a big one! The whole ",
	" garrison is eliminated, we've got the fort occupied. Fortification is already at full!",
	"I hear that after some sieging, the ",
	" squadron has captured the ",
	" colony of ",
	". Now ",
	" colony!",
	"I hear the ",
	" have launched a villainous attack on ",
	"! The city is now in their hands!",
	"Have you heard the news? Our valorous fleet has relieved the ",
	" of the prosperous colony of ",
	"Sad news for the ",
	" - we failed to defend our own colony! The fort was demolished by the ",
	" ships, and the city was plundered. Don't even talk about the women! Then the enemy just sailed off, tail raised, leaving us in the dust...",
	"I hear that after some sieging, the ",
	" squadron has captured the ",
	" colony of ",
	". After they plundered whatever wasn't nailed down, the ",
	" squadron tore off, out of colonial waters altogether.",
	"They say the ",
	" suddenly attacked ",
	", then plundered the place before reinforcements could arrive! Then the ",
	" scurried away with their ill-gotten gain.",
	"Have you heard the news? It's about our squadron. They were on a short siege of the ",
	" colony of ",
	", see. Well, turns out they've broken the resistance, and supped on the city's rich teat! Of course, after all that they had to pick up and run. But still, the loot! Oh, the loot...",
	"Today we celebrate a victory over our ",
	" aggressors. Our colony is safe! The enemy squadron is sunk, and naught remains to threaten the wellbeing of our fair city! ",
	"They say the ",
	" squadron suffered a defeat during its campaign against the ",
	" colony of ",
	". The home team seemed to be the stronger.",
	"They say the ",
	" have suddenly attacked our colony of ",
	"! Don't worry, though - reinforcements arrived just in time! All the ",
	" ships are now decorating Davy Jones's locker. .",
	"Rumor has it, after a long siege of the ",
	" colony of ",
	", our squadron was sunk by the fort! Well, maybe better luck next time?",
	"English",
	"French",
	"Spanish",
	"Dutch",
	" days",
	" days",
	"several hours",
	"They say the ",
	" have attacked the ",
	" colony of ",
	". The home guard are holding their ground, but if they don't receive any support within about ",
	", the garrison may begin to shudder.",
	"Rumor has it, our indestructible fleet has attacked the ",
	" colony of ",
	". The enemy is defending it rather valiantly, yet we should know the outcome in the next ",
	"They say the ",
	" have attacked ",
	"! The home guard is doing its best, but surely their food and medicine can't last more than another ",
};
