string DLG_TEXT_LSC [146] = {
	"Welcome to the city of Lost Shops, captain. I am ",
	". Well, how do you like the weather? Cheery, isn't it?!",
	"That's not the word I would have chosen, no. ",
	" at your service, monsieur ",
	". And this often happens to you?",
	"Welcome to the city of Lost Shops, captain. I am ",
	" at your service, monsieur ",
	". Where are you from?",
	"What did you want, monsieur?",
	"Listen, I'm looking for someone. You wouldn't know where he is now?",
	"I want to ask you a question.",
	"Can you tell me something interesting?",
	"What new in the city?",
	"I wouldn't mind hearing some of the latest gossip...",
	"Nothing...",
	"Buddy, how are things? How's life?",
	"It happens, monsieur... At first, I almost died on days like this. Now, I'm used to it.",
	"Understood... Say, where are you from?",
	"In my time, I was an apprentice of a shipyard owner in Tortuga. Then I served as a carpenter on a frigate called the Andromeda. Unfortunately, we ended up at the wrong place at the wrong time.",
	"What happened?",
	"Many things, monsieur. Many things. And all at once, if you can imagine! First the slaves rose in revolt. Ten, at the very height of its suppression, we were attacked by head hunters, because it seemed we had aboard a particular... individual, who they desired. ",
	"After a feverish boarding fight, we were hit by a storm, as if we had ended up in some kind of storm zone. Then finally our frigate struck a cliff or a reef, filled up, and shot to the bottom. I managed to lash myself to a small barrel, and was carried here.",
	"Not bad...",
	"You do really want to get out of here? Isn't that so?",
	"Do you think that's possible?",
	"I don't know. I haven't heard about that. If I had half a chance to whip something together, then I would definitely try. But that's forbidden by law...",
	"Maybe we should try together?",
	"No, buddy. I'll pass. With our admiral, you'd end up at the bottom faster than you could raise anchor.",
	"Well, all right. Anyway. Nice to meet you, ",
	". All the best.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please.",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"I see.",
	"That's too bad... ",
	"He is here, on the ship. Search more carefully.",
	"Ha! So he's here, on this ship! ",
	"He's right here on this ship. It's queer you haven't seen him yet.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"So he's here, at ",
	". Search more carefully.",
	"So he's here, among us! ",
	"Where are you looking? He is hanging out here.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"Aha! I see. Thank you.",
	"Thank you! ",
	"She is here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship! ",
	"She's right here on this ship; it's odd you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even spoke a little.",
	"As far as I know, she's now at ",
	"So she's here, at ",
	". Search more carefully.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even chatted a bit.",
	"As far as I know, she's now at ",
	"A-ha, I see. Thank you, ",
	"Thank you! ",
	"I'm all ears, buddy.",
	"Listen, what would hold these ships together during a storm?",
	"Why does no one rise against these so-called laws?",
	"Listen, you wouldn't by any chance know how this city came to be?",
	"I don't suppose a ship or squadron could get here without previously sinking?",
	"Can it be that high-ranking people, officers, never make it here?",
	"No questions. Excuse me... ",
	"I have no idea. And I advise you to avoid this line of questioning - too dangerous.",
	"Dangerous? How so?",
	"To answer that, you'd have to dive under the ships. And those who have, they ain't never come back... ",
	"Now I see...",
	"Untie, you say? Sure, give it a shot. Let the wind blow into your hunched back. I... Well, we all love executions. We like watching the shadows of fools like you slowly melting in the deep.",
	"Well, I'm not burning with the desire to meet Davy Jones firsthand.",
	"Devil knows! Me, I'm a simple carpenter. Ain't got no kind o' head for that natural philosophy bunk...",
	"Well, do you at least have an opinion?",
	"In a roundabout way. I reckon there's got to be reefs under there, that hold all these ships in place. First one got stuck, then it snagged another, and so on until you got this mess. ",
	"Oho! An interesting theory... ",
	"I remember nothing of the sort.",
	"But is it possible?",
	"Only in the event of a miracle. Work it out - we've got cliffs and reefs all around... ",
	"Hmm. Good point.",
	"I guess they have nowhere to go.",
	"And?",
	"And what? The man is a pirate! ",
	"He kills them?",
	"Not always. If they get it into their heads where they are, and what privileges they're still allowed, and do it quick enough, they're spared.",
	"I can tell I'm going to love it here. ",
	"Everything's just fine.",
	"Listen, would you be able to build some flotation device? A raft, or a small boat... ",
	"Ha! Don't you know the law, son? Verboten, that is! ",
	"Don't give me the run-around. I know you helped Teaser Dan, so you can help me.",
	"Teaser Dan? Wo-ho! Now there's a surprise, friend. Teaser Dan, well - he's dead.",
	"Certainly he is now... but that's only recently. If you get what I'm saying.",
	"Hmm... something ain't right here. Y'know, let's take this somewhere quieter. You know that corvette, the Protector? Ask around, if you don't. Go find a cabin, and wait for me. I'll follow in a bit, so's no one sees us together.",
	"Good mind. What I've got to tell you - well, I'm sure it will make you quite happy. So don't make me wait long.",
	"Ain't nothing under the sun gonna keep me, my friend! ",
	"Fine. I'll see you on the Protector, then.",
};
