string DLG_TEXT_LSC [315] = {
	"I don't want to talk to you! You attacked my countrymen!",
	"You know...",
	"It was your ship that crashed last? Well, then! Welcome! I run a tavern here. My name is ",
	". You were pretty lucky, buddy!",
	"Yeah, fatally lucky! My name is ",
	". I was a captain...",
	"Oh, so it was your ship that last crashed? Well, then! Welcome! I run a tavern here. My name is ",
	". So stop in, if something's up...",
	"Fine, ",
	". Nice to meet you, and so on... And I'm called ",
	"Oh, and here you are!",
	"That's so! Now, I'd like to listen to you.",
	"I'm listening to you closely.",
	"What the Devil are you doing here? And where is Brunner?",
	"I'm listening to you closely.",
	"Mmm... Yeah, Hill really is dead...",
	"Armo has been killed. First Hill Brunner, and now Armo. This tavern is an awful place.",
	"You couldn't do anything to stop it?",
	"Hey, ",
	"Oho! Happy to see a new side of our city...",
	"Happy to see you at my tavern. Why have you come?",
	"I hope you'll be able to answer a few questions.",
	"I need to spend the night.",
	"Will you tell me something interesting?",
	"What's new in the city?",
	"I wouldn't turn away from a little of the latest gossip...",
	"Alas. I am already leaving, ",
	". 'Til we meet again.",
	"Pal, we agreed that you'd spill your brains about Teaser Dan...",
	"Listen, I didn't find you in your wine cellar...",
	"I searched the Diffindur, and turned up Teaser's chest. In it, among other things, there was a very interesting letter...",
	"Listen, there's this matter...",
	"I did as you said. The narwhal ring's is with me.",
	"You know, it all worked out!",
	"Well, how are things? Did you find it? What are you planning?",
	"Listen, I couldn't be at your cellar at midnight. So I didn't see anything and didn't hear anything.",
	"You know, I was at your cellar at midnight sharp. The admiral and some other type were about to talk, then they noticed me and left. So I didn't hear anything.",
	"Buddy, were you able to learn something about our matter?",
	"You know, your cellar is really a great place to listen in on conversations. I waited for Chad.",
	"Listen, I'm looking for a few items.",
	"Listen there's a serious talk. I'm gathering a team.",
	"You're a really lucky boy, Captain. You just don't get it yet. If you'd come to the city five hours ago, then you'd never have gotten out of the water.",
	"I'm a sailor. I swim well enough.",
	"That doesn't mean a thing, if we're talking about city waters! The storm started slinking away, and it was that which gave you a chance.",
	"Understood...",
	"I think that sleeping right now wouldn't be for the best. Believe me...",
	"Okay.",
	"You can sleep on the bed on the upper tier. When do you want to be woken?",
	"In the morning.",
	"At night.",
	"The following morning.",
	"I've changed my mind. I'll go without sleeping",
	"I'm listening to you closely, buddy.",
	"Of course, the weather here is just amazing!",
	"Listen, what's this island?",
	"How did it happen that I got here?",
	"And do you mean that it's really impossible to get out of here? With so many ships around, are you telling me that it's really impossible to throw something together?",
	"How do you live here, damn it?",
	"Listen, did you ever know a person named Teaser Dan?",
	"Listen, does the word Diffindur mean anything to you?",
	"What clans live here, in the city?",
	"Listen, all the locks need keys here. Where do I get at least one?",
	"And who is Augusto Brahms?",
	"I can't get used to the city. Isn't there a map or something?",
	"Listen, you wouldn't know a Leyton Dexter?",
	"No questions. Sorry, buddy...",
	"It's not even that bad! It's often far worse. Storms here are a regular concern.",
	"Understood...",
	"This storm will end tomorrow, closer to evening. We're supposed to get noted at the Admiral's upon coming in, so if you don't come to him before the end of the storm, he'll find you himself.",
	"Admiral?",
	"Chad Capper, buddy. Don't mess around with this business. That's my advice to you!",
	"Okey dokey.",
	"This is the city of Abandoned Ships, pal. If you've ended up here, forget everything about what you lived for. You can't bust out of here, unfortunately...",
	"Well, damn.",
	"I don't know. I need to ask you, how did you wind up swimming in here? You're a captain. You were in command of your own ship. Me, I don't know. I was sitting in my cabin, then there was this screaming. And then the planking shattered. And that was it.",
	"And you didn't see anything?",
	"Later, I sure did. There was , this seaside scene, so to say. But how our cap managed to steer us in here, I have no idea. He died. Actually, few people end up saved after crashing, so you were lucky.",
	"Yeah, sure...",
	"Ha! And where did such a smart guy come from? There were attempts - all unsuccessful, it turns out. People just take materials, to little end other than wasting them. The city ends up seriously suffering because of it, since it lowers its stability. If you remove one of the ships, then the island begins moving. All the passageways break, and all the cabins shift around. \n It turns out silly. So now it's forbidden by law. And has been for a considerable time, now!",
	"I see...",
	"Yeah it's surely normal. Still, I'm sick to death of it all... In general, the city lives on the basis of the law - the main tenets of which... Well, you'd better ask Admiral Capper.",
	"Who is this Admiral?",
	"He, my friend, is what you might call the head of state. Chad Capper's the name. They say he was a pirate before, so it isn't worth annoying him unless you've got a reason.",
	"Never said I was planning to. So... What? You have elections, and the citizens choose the admiral?",
	"Well, there were elections before, but that's not the way it works now. Chad excellently handles his responsibilities, so nobody wants to change him. Not anymore, anyway.",
	"What do you mean?",
	"Used to be there were citizens who thought of being the admiral. But they aren't with us anymore.",
	"They sailed out of here?",
	"You can say that. Sailed to the bottom...",
	"Aha.",
	"I knew him. He was living with us for a few months, then died. A pity. He was a good guy.",
	"That ain't so!",
	"What, he wasn't a good guy?",
	"I'm not talking about that! It looks like he got out somehow...",
	"Jesus! No, that can't be...",
	"It can. Not that it did him any good, in the end. He turned out a bit of a pauper...",
	"Hell! Hell! Hell!! Is it really possible?",
	"What are you talking about?",
	"Okay, my friend, I'll tell you what - don't blab about this to anyone! If the admiral finds out about this, that someone broke a law, and even made it out... Well, the messenger won't be feeling very good.",
	"Hm. Can you elaborate?",
	"You'll get it later. For now, for your sake, do as I say. Don't mention the name Teaser! Understand?",
	"Yeah, I got it.",
	"Fine. And as for me, I'll just spend a time wrapping my brain around this news...",
	"Well, I'll leave you to that then.",
	"That flute, Fernando Diffindur, is a hopeless point.",
	"Be so kind as to explain?",
	"In theory, that Flute should have gone to the bottom. It was literally split in two. Yet somehow, it's still hanging on to the surface. Caught up on a reef, I guess. Basically, that ship stands alone. No one lives there, and no one will.",
	"Why?",
	"Ships like that, when they go to the bottom, vanish in just a few seconds. So you've got to crazy to spend any time there.",
	"Oh. I see what you're saying.",
	"Yeah, we've got some of those here. You know, there are always a few who can't live in peace. So they form clans...",
	"Hm. Go on...",
	"Well, the pirates and the prisoners - all these criminal elements, the dregs of society - they band together...",
	"So I'm the dregs of society, huh? You do realize I'm a pirate, right?",
	"Well, no. You're not just a pirate, you're a pirate captain. Tell me, in your time at the helm, weren't there enough scoundrels of all types on your team?",
	"To be honest... yeah, I had my share.",
	"So there we go. In general, they gave them two ships, so they could frolic and not get in the way of the rest of the citizens. The Admiral keeps them in check with his militia, else it would be a complete nightmare here.",
	"Well, okay. Are there conflicts with them?",
	"There were, of course, but everything is quiet now. But bear in mind that it isn't worth going into their ships!",
	"Understood. Well, then. Thanks for the information.",
	"Take it where you can. That's the personal business of every person, No one's going to help you in that.",
	"Mm. Yeah, you summed it up well. I'm speechless...",
	"Well, what can I say? All the chests have locks of three degrees of difficulty. If a regular key can be found, even on the street, it's going to be a lot harder with the rest of them. See, the chests with the good locks are where people hide truly valuable things. ",
	"Bear in mind, even if you manage to find the keys, you're not the only one who's got 'em. If you want to hide something well, then it's better to look for chests farther away, beyond the city.",
	"All right. It's all a bit clearer now. Thank you.",
	"Ha! Buddy, if I knew who August Brahms was... No, actually I don't want to know that.",
	"Explain, please.",
	"Hm. Even how he got here, no one knows. And you want me to explain something? He lends money, but it's better to keep away from him, friend.",
	"I really don't get it. But all right.",
	"Ask Eric Yost, in the store. He must have one of those.",
	"Thanks, buddy.",
	"How should I know? Why do you need that?",
	"Hm. Just interested...",
	"You shouldn't dig into this stuff, buddy. You believe me.",
	"Tell me, buddy. Then we'll see if it's worth it or not.",
	"Well, okay.... Anyway, before ending up in the city, Dexter was a pirate. The same as Capper, actually. And they immediately couldn't get along. Soon Dexter disappeared. That's all I can tell you.",
	"Yes, not too thick... In any case, thank you, ",
	"Yes, yes... I let myself go a bit. But I can't talk about this here. Let's meet at my wine cellar, after midnight.",
	"And where is this cellar located?",
	"Well, I call it a cellar by habit, but it's one of the cabins here. You need to go to the main deck of the Flenon. From there, walk onto the quarterdeck.",
	"Understood. Well, then, we're agreed.",
	"Don't be late, I won't wait long for you.",
	"Understood. I'll be there, for sure.",
	"I know about that, since I was waiting for you for a good hour! Damn it, you can't be so frivolous in such a serious matter!",
	"What kind of serious matter?",
	"I told you, I can't talk about this matter in public! That would be crazy!",
	"Okay, don't flip out. Let's try meeting again, if it's essential.",
	"Well, okay. I'll wait for you at the cellar after midnight. This time be kind enough to show up.",
	"Okay. I'll be there, for sure.",
	"You haven't told anyone else about Teaser Dan, for the time being?",
	"No, it's all as we agreed.",
	"That's good. Now, let me tell you the results of my thoughts on this matter.",
	"I'll hear them out, with pleasure.",
	"You are probably already aware that the city Law forbids building anything that would allow a person to sail out of here. So I can't wrap my head around how Teaser Dan could build some washtub in secret and use it to successfully reach the mainland.",
	"Unfortunately, I didn't personally meet Teaser. If I had, I would have learned all the specifics on this matter.",
	"Yes, that is a pity... Still, let's look at what we have. And what we have is a riddle, that we must solve as soon as possible. Before doing anything, we must understand, in component terms, how Teaser could have gotten out of here.",
	"And then what?",
	"If the citizens discover that Teaser has gotten to the mainland, then there's no doubt that many will want to follow his example. Only, before we talk about Teaser Dan, we need proof of your statements.",
	"But I... ",
	"I need more than your word, my friend.\nHere's what I'm thinking. You need to go to the Fernando Diffindur. And it'll be dangerous - broken in twain, though by some miracle it ain't sunk yet. Anyway, that's where Teaser Dan wiled away his hours. I reckon, any sign of his secret, that's where it's got to be.",
	"And how would I get there?",
	"You swim, don't you? There's no direct link to the city, I'm afraid. The Ceres Smithy or the San Gabriel, they're as close as you get. You can take a leap from the catwalk between 'em.\n Mind, steer clear o' the San Gabriel - that's where all the Caspers congregate! ",
	"Understood. Listen, can you at least give me a broad idea what we're looking for on the Diffindur?",
	"If only I knew! Whatever might prove that poor Teaser reached the mainland.",
	"Hmm... You know, I've already been on the Diffindur and found Teaser's chest. There were a bunch of interesting things in it, but amongst them was this letter...",
	"You know, I have a key that a friend of Teaser's gave me on the mainland. Teaser had asked that this key be given to a man who seeks the Island of Justice. That being this place. Apparently.",
	"Interesting... Very interesting, in fact. Not that it proves anything. Capper would hear you out, then shoot you in public, for disturbing the peace. And no one would say a thing in your defense. Key, schmee. There are plenty around here. One for practically every chest.",
	"True enough...",
	"Still, it's a start. What did Teaser's friend have to say about it?",
	"Just that it's the 'Diffindur key'.",
	"Well, see there! We are on the right track! \nGo on to the 'Diffindur, ' There's got to be something there that goes with that key. I've always thought Teaser was a queer one; now, looks like he was craftier than he let on... ",
	"Could well be. He was definitely a good man, though. That's a fact.",
	"I agree! But let's not waste time. I'll wait here for your return.",
	"Won't be two shakes. Don't fall asleep, now.",
	"What letter?",
	"See for yourself.",
	"Fascinating... He says, 'As we prepared thoroughly, and at length...' Unless that's the royal 'we', sounds like he had help.",
	"Seems the thick of it. ",
	"Hee hee, there is no doubt! I knew Teaser well, and he couldn't build a raft to save his life. Far too clumsy, him. So if he made it all the way to the mainland, he had to have a real hand at his side, if you follow.   \nAnd... that could only be our carpenter, Andre Labor. Listen now, friend. You go to him. Talk to him quiet-like, tell him about Teaser. He probably hasn't heard word one about that bum since he sent him on his way.",
	"Is that really necessary? Isn't Teaser's letter proof enough of what I'm saying?",
	"Oh, it's plenty. Still, we don't really know how Teaser pulled off this scheme. If we're going to face down the law, helps to have all the eggs in our basket. We got Andre, we've got a scheme already laid out for us.",
	"What good is that? Soon as we repeal the ban, the building will kick right off anyway. We can figure out what we're doing then.",
	"It's not so simple, friend. People need something concrete to latch onto, 'specially if they've had all the hope kicked out of 'em. Otherwise, all you get is chaos. Every man for himself, running through the streets. Best we get 'em all together on one job.",
	"I guess that makes sense... ",
	"'Sides that, the Admiral ain't hardly gonna sit in the sidelines, listening to you like a word from on high. Ain't no small thing to tell Capper to change his tune, 'specially after all the noise he's made about this law of his. We need to convince the Admiral that we're right. 'Course, it's easy to say...",
	"Apparently. But it won't be so easy to do?",
	"Well, how can I put this... Sometimes I catch myself thinking the Admiral, he ain't too keen to leave this place.",
	"Hm. Interesting... ",
	"Course, that's just a pet theory of mine, and we'll come back to it later. For now, let's you go find Andre Labor and prod out everything he knows about Teaser.",
	"All right. I'll do that.",
	"So? How'd it go?",
	"Well...I talked with the carpenter, Andre Labor, and he asked me to wait in the cabin on board the corvette 'Protector.' I get there. I'm sitting, waiting for him, not suspecting anything...and this Andre brought a militia man to talk to me. I was forced to take them both out.",
	"The devil! Didn't see that one coming. Well, now you 're done for... Look, don't suppose you could keep my name out of this? There's a good lad. You're dead already, but I've got some vinegar in me yet...",
	"Oh, grow up. Nobody's coming after me. Nobody knows I was there. No one left there alive.",
	"You sure about that?",
	"Andre's friend told me so himself.",
	"That's better, but I don't see no good in calming down. The Admiral ain't hardly a fool, you know. He'll see through you. ",
	"So what do you propose?",
	"Well, I guess we've gotta pin it on one of the clans.",
	"Which one?",
	"The Narwhals could do with some thinning.",
	"And how do you propose we do that? I suppose I should just walk up to Chad and say 'Look, you know those murders? It wasn't me, I swear. It was the Narwhals!'?",
	"Don't be flip, son. All clan members got an amulet, what shows a reverse star. Find one, and take it to the admiral. Tell him you found it where the murders happened.",
	"Where would I get one?",
	"There's a cabin on the Velasco, where the Narwhals keep all their trinkets. It's something like a shed. Wait 'til some Narwhal shows up, and kill him.",
	"Got it. Well, that's what I'll do.",
	"Excellent! Now rush to the admiral and tell him what you found in the cabin on board the 'Protector.'",
	"I get you. Best show that to the admiral, not me.",
	"Listen, enough kidding around. Get off to the admiral! ",
	"I'm startin' to suspect you're more of a fool than I took you for.",
	"Point taken.",
	"Yes, of course!.",
	"Nuh-huh. For sure! ",
	"Yeah, guess I was born that way. Some kind of compulsion I got. I keep doing the same thing over and over again, like a man sitting in a chair, pressing a switch for hours on end, always expecting this time, this is the time It'll all make sense. This time will make it all worth it. What I really think I'm accomplishing... well, I couldn't say...",
	"Fine! ",
	"Precisely! With the help of the amulet, I managed to prove to Capper that the militia man was murdered by the Narwhals. The admiral bought that, and sent me to kill off all the whole clan. Which I did.",
	"Impressive... Well, brother, I guess you deserve a medal. Though... on second thought, maybe you've done us all more harm than good.",
	"What do you mean?",
	"You know, up until your heroic deed, there was a balance of power around here. Whatever bad the Caspers did, they were set off by the Narwhals. But that's all over, now.",
	"Yee hee hee... Oh dear. Your whole plan was to let the Narwhals take the fall for you, but now you're complaining!",
	"No, it ain't that. I'm pleased enough. I'm just thinkin' out out here. Though I admit I did get a bit spooked...",
	"So I see.",
	"So, what are you going to do now - now that you're a hero and all?",
	"Dunno. Looks like I won Capper's respect, anyway. You know, this place isn't so bad at that. Maybe I'll sign up for the militia... ",
	"Okay, pal, you have your fun - but don't forget to visit me. I'll see what else I can dig up for you.",
	"Like what?",
	"Early days yet. Hold yer horses.",
	"Fine, I'll be stopping by.",
	"You know, all kinds of queer stuff takes place at my tavern. Sometimes I think nothing's really as it seems around here... ",
	"Come again?",
	"Nothing. I've just become a philosopher of sorts... Look, I'm offering to carry out an operation. Do you remember my wine cellar?",
	"'Course.",
	"Then be there today, before midnight. Wait behind the column, and make sure your shoulders don't stick out. You may well overhear a very interesting conversation, that may help you decide your future course of action.",
	"What kind of conversation?",
	"Between the admiral and another individual. They've been holding secret trysts for a while. I've been quite curious myself what they get up to in there, but I don't think I could keep myself still through all that... You go do that, and I wager it will open your eyes. May change your way of thinking!",
	"I'm not sure that I'm ready for that. But all right, fine. Whatever.",
	"Heh, not much to be excited about... Well, now you're free to go wherever you want and do whatever you please. Enjoy.",
	"I see... And who is the admiral meeting?",
	"Heh, not much to be excited about... Well, now you're free to go wherever you want and do whatever you please. Enjoy.",
	"I see... And who is the admiral meeting?",
	"It's Casper Longmann, chief of the Casper clan.",
	"Oho! There's a shocker.",
	"I chanced into them talking by the grate of the wine cellar. Rose my eyebrow. When I followed up, I realized they were meeting like that fairly often. I'd like to know what they're doing together, wouldn't you?",
	"Well, maybe it's not too late? We'll just wait 'til they meet again.",
	"Of course we'll wait, but this time I'll handle it myself. It should prove fun to hear them now, with their Narwhals buried in the damp. Won't be long now... ",
	"Hmm, yes. So how long do they go on for? ",
	"We'll just have to see, won't we.",
	"All right. Well, I'll check in on you. ",
	"Not yet, but I'm trying. Hang on.",
	"Look, I told you to wait. Nothing doing, yet. ",
	"I keep telling you, keep your pants on...",
	"You bored yet?",
	"Um. Sure, okay.",
	"Sure, I got it.",
	"I understand. I'll wait.",
	"Yeah, I'm that tenacious.",
	"Keep it down, clompy... I've got the admiral hanging around...  So, what did you hear?",
	"Did you hear anything?",
	"I did. It turns out the admiral himself is preparing to flee the city! ",
	"That can't be! It was his own law that said no one can leave here!",
	"Well, he doesn't have a ship yet. So far it's just talk.",
	"But how could he keep something like that secret? It's impossible!",
	"It's not all that secret. He's working with the Caspers. So to sum it all up, we don't need to prove our case - Teaser Dan did it.",
	"He did do it, didn't he... Didn't I tell you this will be important! ",
	"Indeed, it was of the utmost importance... Listen, the Admiral mentioned some Mechanic or other. Who is he?",
	"Hmm... Dunno.",
	"Leave off. Listen, you know everyone. How long have you lived here? ",
	"What makes you so set on this mechanic? You sure you heard the man right?",
	"Well, maybe not... But listen, is there anyone who's been around here longer than you?",
	"Hard to say... No, no one alive, I don't think... ",
	"Sure about that? Think harder.",
	"All right, I'll mull it over. But later. I've got to work now, so come back tomorrow.",
	"Deal. ",
	"What, you haven't heard? Brunner, he's gone... ",
	"Gone? Gone how?",
	"Dead and gone, in the tavern's wine cellar. You know the cabin on the prow, with the casks? Sprawled out, right there... ",
	"Really? Did anyone see it happen? Did they find the killer?",
	"Nope, nothing. Armo, just stumbled on him. She went to check on him, thought he'd been there too long - and, well, there she had it.",
	"Blimminy. So I guess the tavern's yours now?",
	"You got it. When the news hit, the Admiral paged me and asked me to take over Brunner's business. You see, without a tavern, there's no community. And without community...",
	"Yes, I know. Well, good luck with it all. Better luck than Brunner, anyway.",
	"He couldn't be deader, bud.",
	"How did it happen?",
	"He was found dead in the tavern's wine cellar. You know this cabin on the prow, with the wine barrels? That's where he lay...",
	"Did anybody see it happen? Did they find the murderer?",
	"Not bloody likely! No one knows what happened, really. She went out back of the tavern, where her bed is, to gather her things. Then there was this scream and a gurgle... And that's that.",
	"What happened then?",
	"We all ran there, and saw her lying in a puddle, her throat cut open. Weren't nothin' we could do but gawp.",
	"No, can't think of much. But didn't you see the guy? It's got to be one of the Caspers...",
	"So they've gone wild after all. Figures. What did they want with her, though?",
	"It was my fault. I... I didn't foresee this. God Dammit, I'll never forgive myself.",
	"What do you mean?",
	"You already asked about that.",
	"Already asked... ",
	"You already asked me about 'em. I told you, I dunno!",
	"I need bombs, knippels, provisions, gunpowder, weapons, medicine... ",
	"Yes... Sorry, quite right.",
	"Oh, yes.",
	"I see.",
	"Sorry, ",
	"I see. Thank you.",
	"What crew?",
	"We've already gone over this.",
	"Not gonna repeat myself, friend.",
	"That's enough. I'm not in the mood for this...",
	"The ship. I'm leaving the city.",
	"Yes... Sorry, forgot.",
	"You know... ",
	"Fine.",
	"What, there's a ship?",
	"That's what I'm saying. Wouldn't bother you otherwise.",
	"You know what? I'll say no. I'll wait for an official pass... ",
	"You don't know the risk if you stay. There's a huge storm bearing in...",
	"And not for the first time.",
	"Hmm... All right, I tried. Do as you will. ",
};
