string DLG_TEXT_LSC [52] = {
	"Hey, pal! Come on, get out of here! Clear the square.",
	"What's the matter?",
	"I'm waiting for someone here, and a third one would be a hassle. Got it?",
	"You waiting for Armo? I'm here in her place.",
	"Oh, I see. Okay then...",
	"What?!",
	"You don't get it? Well, okay. You'll understand now...",
	"Listen, I think I expressed myself clearly. Get out of here, pal...",
	"You wouldn't be waiting for Armo, would you? If so, she's not coming. I'm here in her place.",
	"Okay, okay...",
	"What?!",
	"You don't get it? Well, okay. You'll understand now...",
	"Okay, you've gone and done it. Looks like this won't work out nicely...",
	"Man, you are persistent...",
	"Pal, shouldn't you be getting out of here?",
	"What's the matter?",
	"Well, see, I've got a date here. So your presence here is undesirable, to put it mildly.",
	"You wouldn't be waiting for Armo?",
	"Fine, pal.",
	"And how would you know that?",
	"She ain't coming, I'm here in her place.",
	"Friend, I'm asking you - don't be rude.",
	"Rude? Hee hee... Okay, that's enough. Armo won't be coming. I'm here in her place.",
	"Fine.",
	"How might I understand that?",
	"Any way you want to...",
	"I warned you, buddy. You only got yourself to blame now!",
	"Blame, what? Hang on, I didn't hear you... ",
	"Hey, get lost while you're still in one piece! ",
	"Hmm? Why, what do you mean?",
	"I mean I'm meeting someone here - and it's a private meeting, if you get me.",
	"You're meeting Armo, then? Good luck to that... ",
	"Aha. Got it... ",
	"That's right. How did you...",
	"Armo's not coming. It's me you you want, then.",
	"Listen, I already told you to get lost! ",
	"If you're waiting for Armo, she's not coming. Your meeting is with me now.",
	"All right, I'm going... ",
	"What's that?!",
	"Idiot",
	"All right, that's enough talk...",
	"Yes, I must concur.",
	"My nose for trouble served me well again. Too many of our people have disappeared... ",
	"Wow... what're you on about now?",
	"I'm talking about that bitch Armo. And you too, of course. What the hell are you doing, you swine?",
	"I don't even know how to put it...  Well, you could say that I've been killing you Caspers, one by one. ",
	"I see... Well, then I didn't bleed Armo for nothing. ",
	"Come again? ",
	"Yes, my friend. First Hill Brunner, then his whore of a waitress. It's a special bond they share - with my blade...",
	"I see. Well, you're really going to die now.",
	"Do you take me for an idiot? I had my suspicions last night, and now I am not alone. ",
	"Lot of good that'll do you.",
};
