string DLG_TEXT_LSC [207] = {
	"My regards to the newly-arrived. This is just the time. I am ",
	". But around here they call me Happy.",
	"Well, hello, ",
	". My name is ",
	". let's get acquainted. And what do you mean the time?",
	"My regards to the newly-arrived. I am ",
	". But around here they call me Happy.",
	"Well, hello, ",
	". My name is ",
	". Let's get acquainted.",
	"Hey, buddy, I've got this matter for you.",
	"Lay it out.",
	"What did you want, sir?",
	"Listen, I'm looking for someone. Don't suppose you'd know where he is?",
	"I want to ask you a question.",
	"Can you tell me something I don't know?",
	"What's new in town?",
	"I wouldn't say no to a little of the local gossip...",
	"You know, I passed along that bottle of wine from you to Thomas Boyle.",
	"My friend, haven't you been flirting with Armo Dulin, lately?",
	"Yes, yes. I smoothed everything out with Thomas Boyle.",
	"Listen, I'm looking for a few supplies.",
	"You know, I'm building a team to get out of here. I'm wondering if you want to come with me.",
	"Nothing...",
	"The storm's dying down, and all the lucky boys are crawling out of the water.",
	"Understood. But you're in their number, too!",
	"That's correct, but I'm a lucky gander. Thing is, my ship broke at the very peak of this storm!",
	"Oh, that's something! Tell me, please.",
	"Well, then. Very pleasant.",
	"So, uh. Why so happy, Happy?",
	"Oh, I've my share of reasons. I saved myself after a shipwreck, like most of the locals, but my crash was special...",
	"And what was so special about it?",
	"Ha! It was the damned Devil's own crash, confound it! Our frigate was hit by lightning, and instantly it was all ablaze - which soon made its way to the powder cellar... ",
	"Now, you just imagine! From beginning to end, the ship turned into a heap of smoldering toothpicks in just a matter of minutes - and yet, I wasn't even burned! Moreover, I was standing next to the hold and when I arrived at the city, my hands were filled with jewels, money, and rare artifacts...",
	"And the admiral didn't confiscate all of that?",
	"The Admiral is a rare type of of clever, greedy villain - yet I can out-swindle any swindler. I was warned about the upcoming meeting with Capper beforehand, and I was able to take... measures, as they say. Still, why I ever needed all that junk here, I don't know myself...",
	"Hm... Listen, what measures did you take? I'd be interested to know.....",
	"I'm not saying, buddy. Sorry. My happiness is my own. I'm scared of loosing it. I'm superstitious.",
	"Yeah, fair enough. And what do you do here?",
	"Oh, nothing! There's no way back, so I don't want to look for anything. I just live day-to-day... and I like it, by damn!",
	"Well that's one way to go about things. Thanks for the talk. Listen, if you ever change your mind and feel like telling me about those measures of yours...",
	"Sorry, pal. Impossible. The best hint I can give you it that everything had to be stashed somewhere before meeting Chad... Which you could have figured out on your own, I wager.",
	"Understood... Well, thanks for that, anyway.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please.",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it?",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him recently in ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, he's currently ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"She is here, on this ship. Look more carefully.",
	"Ha! So she's here, on this ship! ",
	"She's right here on this ship; it's odd you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even spoke a little.",
	"As far as I know, she's now at ",
	"So she's here, at ",
	". Take another look around.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even chatted a bit.",
	"As far as I know, she's now at ",
	"Aha! I see. Thank you.",
	"Thank you! ",
	"I'm all ears, buddy.",
	"It looks like storms are pretty common around here.",
	"And how about here?",
	"How do people resolve their personal problems in the city? Surely there must be brawls or civil disorder of some sort?",
	"Is there a place to swim to safety... anywhere?",
	"How long have you been stuck there?",
	"Sorry, my mistake. Never mind!",
	"I wouldn't say. Just every storm is pure hell! Everything creaks, sways... quite scary.",
	"I see.",
	"You can do whatever isn't banned. You can... but cautiously.",
	"I'll keep that in mind. ",
	"Anything might happen, of course... Chad and his cronies can silence whoever they want. Someone's declared insane, and that's that.",
	"A fun scheme... Wait, do people really get their marbles blown out?",
	"It happens... ",
	"Okay. And how do the other people communicate with each other?",
	"Covertly. Someone disappears without a trace, they blame it on the clans... As a rule, if you're not caught red-handed, you're good to go.",
	"Ugh... okay.",
	"They sure do, my friend! Straight to hell! ",
	"Many thanks.",
	"Well, to be honest, for some a year here is eternity... ",
	"You've lived here a whole year already?",
	"Longer, actually. It's a metaphor, mate.",
	"I understand. Has Hill Brunner been here?",
	"Sure has. Too bad Brunner had to die. He was a good barkeep. Any time of day, he had just what you wanted. Yep, a real pity... ",
	"All right, be well.",
	"What kind of goods?",
	"You already asked about that.",
	"Already asked... ",
	"Look, I told you I don't know anything about that stuff.",
	"I need cannon balls, bombs, knippels, provisions, medicine, gunpowder, weapons... ",
	"Yes... Sorry, forgot.",
	"Ah, well, yes.",
	"I get you, I get you...",
	"You can ask the house mistresses for a canister. They've got a ton of this stuff, don't belong to no one. For medicinal provisions, I recommend our holy father. As far as weapons and gunpowder, they're the admiral's domain.",
	"What do you mean?",
	"He collects weapons and gunpowder as the ships come in. Must have a pretty good stock by now.",
	"I see. Thank you.",
	"Argh... I didn't expect that... ",
	"I understand. Please, make up you mind quickly. If you agree, we must head for my ship right now.",
	"Immediately?",
	"Yes. The city is in the path of a storm that will most probably destroy the island. We must hurry up.",
	"He he, lucky again! I agree.",
	"Perfect. Go to 'San Gabriel' now and the Mechanic will ferry you over to the corvette.",
	"Great. I'll just go get some of my things...",
	"Don't be late.",
	"I have this friend, a jail warden. Name's Thomas Boyle. He spends all his days on that damned Tartarus, as if he's behind bars himself.\nI want to make him a pleasant surprise.",
	"Excellent. How can I help?",
	"Find somewhere a bottle of wine and take it to him on my behalf. Thomas will be surprised! ",
	"Hey, buddy, did you go nuts? What do you think I am, your errand boy?",
	"Fine, I'll do it.",
	"Don't get so worked up. You don't want to do it, no problem...",
	"And in the future don't bother me any more with such idiotic proposals.",
	"Thanks, buddy... Thomas will be very happy.",
	"I hope so.",
	"Excellent! I can imagine how happy he was... ",
	"He liked the wine, but he asked me to tell you that he'll still cut your ears off. Your... ears, was it? Yes, ears.",
	"My ears? What for?",
	"No idea. I guess he's mad at you.",
	"That's new!    \nCan you ask you to go back to him? Please, find out what happened! ",
	"Find out yourself, why don't you!",
	"Damn, I'm scared. I think he'll start throwing punches before asking any questions. Go, ask what's the matter, I beg you! ",
	"Fine, I'll go ask.",
	"It'll never happen! What am I, your errand boy! ",
	"Thanks, buddy! I swear I have no idea at all what the matter is.",
	"I believe you.",
	"Well, I talked to her recently. There was no flirting going on. As if I don't know whose lady she is. ",
	"And whose lady is she?",
	"Thomas Boyle's, of course. I'm not such an idiot as to make passes at my friend's girl, right under his nose! ",
	"I suppose not. That would've been really too much.",
	"Buddy, do me one more favor.",
	"Oy, again?",
	"Well... yes? Go visit Thomas again, and convince him that someone's trying to slander me.",
	"And who might that be, then?",
	"Oh, anyone in the tavern. Doesn't matter. When I talked to Arno, half the city was in there.",
	"Hum... All right, I'll do my best.",
	"Thank you, my friend! ",
	"Sure thing.",
	"Excellent! What did he say?",
	"He apologizes to you for his disrespectful behavior.",
	"That's my Thomas. I recognize my friend again.   \nBuddy, I am so grateful to you! ",
	"Listen, your unending gratitude warms my heart and all, but I don't suppose we could warm my pocket instead?",
	"Oh. Well, I don't even know what I could give you.   \nWait, I've got something here... Here, this is a key to some chests. Who knows, it may come in handy.",
	"I hope so.",
	"Well, this is great! One more time, thanks! ",
	"No problem... ",
};
