string DLG_TEXT_LSC [168] = {
	"Hello, sir. I'm very happy that you were able to save yourself from that horrible catastrophe. Still, what can I say, we've all gone through that. You know, soon this storm ends, your mood will surely improve. Oh, my name is ",
	", at your service, miss... Tell me, do you met get reinforcements after every storm?",
	"Hello, sir. I'm very happy that you were able to save yourself from that horrible catastrophe. Still, what can I say, we've all gone through that. You know, soon this storm ends, your mood will surely improve. Oh, my name is ",
	", at your service, miss...",
	"What do you want?",
	"You know, I'm looking for somebody. You wouldn't be able to help me?",
	"I want to ask you a question.",
	"Can you tell me something I don't know?",
	"What's new in town?",
	"Any salient rumors, of late?",
	"I hear you're looking for help in some matter...",
	"I was sent to you by your husband, Maxim Taylor.",
	"Elis, the Admiral will free your husband.",
	"Listen, I'm looking for some stuff.",
	"You know, I'm collecting a team to get out of here. How's about you go with me to the mainland?",
	"No, that's okay...",
	"Far from it, unfortunately. We get a lot of ships coming in, but living people are rare. I don't know why... And, also, that's Missus.",
	"Oho! Then forgive me...",
	"Missus. I'm married.",
	"Oho! Then forgive me...",
	"Also, if you haven't seen him yet, then you'd better hurry and talk to our Admiral Chad Capper. Otherwise he'll come after you himself.",
	"Hm. I see...",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it?",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him recently in ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, he's currently ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Look more carefully.",
	"Ha! So she's here, on this ship! ",
	"She's right here on this ship; it's odd you haven't seen her yet.",
	"I saw her just recently at ",
	"You know, I recently saw her at ",
	". So you might want to look for her there.",
	"As far as I know, she is now at ",
	"Excuse me, but she's right here, at ",
	". Take another look around.",
	"So she's here, among us! ",
	"Not very observant, are we? She's got to be around somewhere...",
	"Oh, I saw her recently. It was around ",
	"I met her not long ago at ",
	". So you'll see her there.",
	"As far as I know, she's currently at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"Listen, what island is this?",
	"Are you from England?",
	"Have you lived here long?",
	"I have no questions for you. Excuse me.",
	"What, you don't know yet? This is the City of Abandoned Ships. And all of us here are lost people...Ay, how tired I am of all this!",
	"I see... ",
	"Yes, why do you ask?",
	"Are there a lot of English here?",
	"A few. I haven't taken a head count. You know what, national identity doesn't mean a jot here. No one cares, and it doesn't affect anything.",
	"Understood... ",
	"Yes, I am from England. And why are you asking?",
	"Are there a lot of English here?",
	"Not that long, half a year.",
	"I see.",
	"What kind, exactly?",
	"You already asked me about that.",
	"You already asked... ",
	"Look, you already asked me about that junk. I'm sorry, I can't help you! ",
	"I'm looking for cannon balls, bombs, canister, knippels, provisions, medicine... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah. Well... Yes.",
	"I get you, I get you...",
	"Well, I've got no provisions, no medicine... Cannon balls, we have in spades. Don't do anyone any good here. How many do you need?",
	"A hundred centners would be enough.",
	"That's fine, you can have a hundred.",
	"Thanks! Could you suggest someone who can move them to 'San Gabriel?'",
	"Hm, don't know... Ask Felix Mendoza.",
	"Great, I'll do that. Thank you! ",
	"Actually... why should I believe you?",
	"You owe me nothing. But if you don't leave with me now, you'll probably die. Thing is, the oncoming storm will destroy the city.",
	"How would you know that?",
	"Mechanic calculated the odds.",
	"Oh, I do believe Vedeker. Evidently, it will happen.   \nAll right, I agree.",
	"Good. Now head for the San Gabriel. Henrik Vedeker will ferry you to my ship.",
	"Deal. ",
	"Just make sure you don't get delayed somewhere! ",
	"That's right, Sir. My husband, the cretin Maxim, got himself behind bars again. I want to help him, one last time.",
	"I understand. So you want to free him from jail?",
	"I do. Please do that, and I'll repay your kindness.",
	"Allow me to ask how?",
	"Well, you're the new city resident. I can provide you with one quite necessary item.",
	"Like what?",
	"It's a skeleton key. It'll unlock any chest in the city.",
	"Oh. Well. I... can see how that could come in handy...",
	"Sorry, I don't need it.",
	"Well, then I'm so sorry. I'll ask someone else for help.",
	"Good luck.",
	"Very well. Then I'll wait for my husband.",
	"I'll do my best. Wait for him.",
	"And what does this scoundrel want?",
	"As far as I know, he wants to be released from jail.",
	"I am so tired of him! ",
	"Do you want to get him out or not? If you need me, I can help.",
	"Thank you. Then I accept! Release him, and I've got something I'm sure will pique your interest...",
	"Hm... And what would that be, if I may ask?",
	"It's a skeleton key. It'll unlock any chest in the city.",
	"Yeeh... er. Hm. Yes, I can see how that could come in handy...",
	"Sorry, I don't need it.",
	"My Lord! I can't believe it! How did you manage to do it?",
	"Well, I had a chat with the Admiral. Straightened a few things out with him. Chad agreed to give your husband one more chance to steady down.",
	"Excellent! I think that after this scare he won't be drinking so much.",
	"I sure hope not.",
	"Everyone else kept his word, so I will keep mine. Please, take the key.",
	"Thank you. I've got a notion how to use this already...",
	"Keep in mind that you should steer clear of other people's property. You get caught, there's no hope for you.",
	"I understand. Thank you.",
};
