string DLG_TEXT_LSC [157] = {
	"That storm was quite severe, Señor. You're very lucky that you were able to get out to us... My name is ",
	". I run this house.",
	"That storm was quite severe, Señor. You're very lucky that you were able to get out to us... My name is ",
	", at your service, Señora... Tell me, how long do these storms last?",
	"Hello! As I understand it, you were the last one to have saved yourself.",
	", at you're your service, Señora. Yes, that's me.",
	"What do you need in my house, Señor?",
	"I'm listening to you, Señor.",
	"You know, I'm looking for someone. You wouldn't be able to help me?",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately?",
	"You know, I'm looking for some goods. Won't you help me?",
	"I'm all about the bombs.",
	"You know, I'm building a team to get out of here. Come with me, to the mainland.",
	"Nothing...",
	"Somewhere around a week, I can't be more accurate. You know, when something like that's going on, you lose track of time.",
	"Yes, I understand.",
	"By the way, everyone who ends up in the city must register himself at admiral Chad Capper's, and get his citizenship. If you haven't done that, then I'll advise you to hurry.",
	"And where is he located, this Chad Capper?",
	"In the city residence, on the warship San Augustine.",
	"Thank you.",
	"And my name is ",
	". I run this cabin. House. Whatever you want to call it ",
	"Home works. ",
	"Yeah, that's good enough. So, then. Welcome to my home.",
	"Thank you.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it?",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's at ",
	"He's here, at ",
	". Take another look around.",
	"He's here, among us! ",
	"Where have you been looking? He's hanging around right here.",
	"Oh, I saw him recently. It was around ",
	"I believe I met him recently at ",
	". So you might want to try there.",
	"As far as I know, lately he's at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Might want take another sweep of the place.",
	"Hmm, so she's now on this ship... ",
	"She on this ship. Funny you haven't met her yet.",
	"Oh, I saw her recently. It was around ",
	"You know, I recently met her at ",
	". So look for her there.",
	"As far as I know, she's currently at ",
	"Excuse me, but she's right here, at ",
	". Take another look around.",
	"Hmm... She's here, among us! ",
	"If you were to have searched more carefully, surely you would have seen her... ",
	"Oh, I saw her recently. It was around ",
	"I believe I met her recently at ",
	". So you'll see her there.",
	"As far as I know, she's currently at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"Listen, what island is this?",
	"We frequently have storms.",
	"Have you lived here long?",
	"Oh, excuse me. It's nothing...",
	"This island is called The City of Abandoned Ships. And the name fits perfectly.",
	"I see.",
	"Quite often. It is quite scary, of course, but we have gotten used to them... ",
	"Of course. Where are we gonna go?",
	"Quite long. About three years! Why do you ask?",
	"No reason really. And was the late Hill Brunner already here when you arrived?",
	"Yes, of course. He was an old name here. Too bad he died... ",
	"Yes, a pity... ",
	"If I can help...",
	"You've already asked about that. ",
	"Already asked about that... ",
	"Look, you already asked me about that junk. I'm sorry, I can't help you! ",
	"I'm looking for cannon balls, bombs, canister, knippels, provisions, medicine... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah. Well... Yes.",
	"I get you, I get you...",
	"Bombs? Oh... I think I do have some... Yes, I do! How much do you want, then?",
	"A hundred centners will be more than enough.",
	"I've got that much. In return for some favors, of course.",
	"Yes, of course. Always at your service.",
	"Bring me ten bunches of grapes... three bottles of wine... Oh, and a lute! Yes, this is going to be a fine day. I'll be singing and learning to play the lute!",
	"You don't... have a teacher, do you?",
	"Why, are you nominating yourself? Sorry, the position is taken... ",
	"No, I'm not... Look, after all those grapes and wine, are you sure you'll be able to play much of anything?",
	"I don't see how that's any of your business. Bring me what I asked, and I'll give you your bombs. That's the end of it!",
	"Yessir, ma'am! As you'll have it.",
	"Did you bring me what I requested?",
	"Yes, it's all here. Please, take it. It's heavy.",
	"Not yet. Still looking. You sure you're still in the mood for lute lessons?",
	"No... ",
	"I see.",
	"Good. You can take your bombs.",
	"Thanks. Could you deliver it to the San Gabriel? I beg of you...",
	"The San Gabriel? Well, okay, good-lookin'. Just for you, since you've been so energetic already. I'll ask my fiancé. He'll do anything for me.",
	"Excellent! Thank you and your fiancé. He's... quite the lucky man...",
	"Thanks... You could make a career at flattery, it seems to me! ",
	"I've thought about it... Good luck!",
	"So direct! And you're so easily breaking the law?",
	"I have no other choice; it's that or my life. I can save yours, too.",
	"Please, explain.",
	"The thing is, there is a high probability that the upcoming storm will destroy the city. The mechanic calculated the odds.",
	"I see... Well, then I guess I'll have to come with you. What do I must do?",
	"Go to  the San Gabriel. Henrik Vedeker will transfer you to my ship. Don't hesitate! ",
	"OK, I'll soon be on 'San Gabriel.'",
	"I beg you, faster... ",
};
