string DLG_TEXT_LSC [146] = {
	"Welcome to the City of Abandoned Ships, Captain ",
	". How do you like the setup in your new place of residence? Is the weather to your liking?",
	"I'm a sailor! Any weather is to my liking, if I can be at sea. Hang about, how do you know me?",
	"Welcome to the City of Abandoned Ships, Captain. ",
	"Do you know me?",
	"Can I help you with something, Señor?",
	"Listen, I'm looking for someone. You wouldn't be able to help me?",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately?",
	"Listen, buddy, I need to move something to the wooden barge, San Gabriel. Won't you help me with that?",
	"You know, I'm collecting a team to get out of here. Would you like to come with me?",
	"Nothing...",
	"How can I not know, Señor. They call me ",
	", and I've never been your match in battle.",
	"We've fought each other?",
	"Here, the past has no no more meaning than rank or national loyalty. While we're here, I don't consider you my enemy. I recommend the same to you. My brig dropped into the abyss of eternity, as did all of my people, and I started a new life here.",
	"Have you been here long?",
	"Half a year? A year, maybe?",
	"And you haven't tried sailing off?",
	"Ha. Those who have never tried, I wouldn't accuse of cowardice. It's no use trying. That's not bravery; it's madness.",
	"Why? Nothing is impossible.",
	"Mm... You think? It seems like you know more of this place than I do, eh?",
	"Rumors have filtered their way to the mainland. If nobody has ever left here, then where did the rumors come from?",
	"Believe me, my friend, pure coincidence. And don't fill your head with useless hopes.",
	"Thanks for the advice.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please.",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it?",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Ha! So he's here, on this ship! ",
	"He's on this ship. It's strange you haven't seen him yet.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"So he's here, in ",
	". Search more carefully.",
	"So he's here, among us! ",
	"Where are you looking? He is hanging out here.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"Aha! I see. Thank you.",
	"Thank you! ",
	"She is here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship! ",
	"She is on this ship; it's strange you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"So she's here, in ",
	". Search more carefully.",
	"So she's here, among us! ",
	"Where have you been looking? She's around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"A-ha, I see. Thank you, ",
	"Thank you! ",
	"I'm all ears, buddy.",
	"Do you frequently have storms here?",
	"How did you make peace with the ways here?",
	"Are people rushing somewhere, or is it just me?",
	"How long have you lived here?",
	"No questions. Excuse me... ",
	"Yes, we do. Especially when you're out at sea, as we are here.",
	"Aren't you tired of it?",
	"Where would I go? There's nowhere to go, my friend! ",
	"Yeah... that's sad... ",
	"I had to make peace. Like many others, I too tried to resist something, though I didn't take it to the extreme.",
	"To the extreme?",
	"In other words, to my own death.",
	"Hmm... ",
	"This is not the first time I've heard this question... Yep, hee hee hee. We had one joker here, Bert. He made several people believe that life on this damned island goes faster... ",
	"So what happened?",
	"Well, he meant it as a joke, but the dummies believed him. Not only that, but they also started to spread this 'theory' of his. It got so the believers are all in a constant rush so they don't waste time.",
	"Very interesting! ",
	"Well, a couple of years perhaps. Can't say for sure.",
	"Hill Brunner was already here when you came?",
	"Yes, of course. Hill Brunner was one of the old residents. Too bad he got killed.",
	"Yes, it's a pity.",
	"Ha! For what reason?",
	"All decided.",
	"I'll do everything.",
	"My.You're, uh, tenacious.",
	"Alice Taylor told me to come address you.",
	"Excellent! ",
	"Ah, well, yes.",
	"Aha.",
	"I see. Well, this changes everything. I am in debt to her. What is it that needs to be moved? From and to where?",
	"A hundred centners of cannonballs from the Ceres Smithy must be delivered to the San Gabriel.",
	"Will do. No problem!",
	"Thank you, my friend! ",
	"Is that really possible?",
	"Sure it is. I'm expecting an answer.",
	"I agree. What do I must do?",
	"Right now, you go to 'San Gabriel', there the Mechanic will arrange the transfer to the corvette.",
	"Good. I'll be on 'San Gabriel' within an hour.",
	"Well, 'bye then! Don't be late.",
};
