string DLG_TEXT_LSC [177] = {
	", Captain ",
	". I congratulate you with arriving in the city! The storm will soon subside, and then you'd best get established here.",
	"And why do think it'll subside soon?",
	", Captain ",
	"You know me?",
	"Can I help you with something, Señor?",
	"Listen, I'm looking for someone. You wouldn't be able to help me?",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for certain supplies.",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me?",
	"Nothing...",
	"Hm, this isn't the first storm we've had here. So I can tell you with some measure of precision that it'll subside by evening. ",
	", at your service!",
	"Thank you. If it's no secret, buddy, tell me how you got here.",
	"Oh, not at all. But I've had no chance to hear about you.",
	"But I haven't had a chance of hearing about you.",
	"Not at all amazing! ",
	", at your service. How can I help you?",
	"Well, I'm meeting with people, adapting... Finding out about the city.",
	"About the city. Hm... And what do you think of the city?",
	"Well, the city's rather... interesting.",
	"That's not the word, Captain! This city is unique.",
	"And how did you get here?",
	"My story is, I gather, the most boring of all. Maybe it's because I'm too lazy to ornament it. To add to that, no one believes me.",
	"How'd that happen?",
	"I literally came here myself. That's it.",
	"Yourself? You purposefully came here?! Then you and I are colleagues! And what brought you here?",
	"There was a rumor going around, Captain. I was the first to realize that it wasn't just a drunken fairy tale, and decided to come here. I hired a captain and collected all the information, got a questionable map... But in the end, everything was a lot simpler than planned. ",
	"At night, without any real reason, without storm or whirlwind, the wind sped us up to twenty knots, if I correctly recall the words of our captain. Mind, I'm no  seaman. We were happy for some time, and then we crashed into this city at full speed...",
	"Crashed?!",
	"Yes, just like that. Our ship isn't too far from here. It became a part of this city. A lot of people also survived, which happens rarely. You can't imagine how Capper looked at us. I swear to God, that little shake-up made even him jump up and piss his pantaloons.",
	"I wouldn't call that story boring.",
	"To each his own. I'd have a preferred a storm. Something less mundane, anyway, than a simple crash.",
	"Well, then. I was happy to meet you. Thanks for the story.",
	"Think nothing of it, Captain. We'll be acquainted.",
	"All the best.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it?",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"So he's here, in ",
	". Search more carefully.",
	"So he's here, among us! ",
	"Where are you looking? He's hanging out here.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now is at ",
	"Aha! I see. Thank you.",
	"Thank you! ",
	"She's here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship! ",
	"She is on this ship; it's strange you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"So she's here, in ",
	". Search more carefully.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"A-ha, I see. Thank you, ",
	"Thank you! ",
	"I'm all ears, buddy.",
	"What's the weather like here?",
	"Why is this place ignored by the national authorities? Does it not belong to any country?",
	"Could you by any chance tell me where I could store these goods for a while?",
	"Everyone knows and obeys the law. ",
	"Have you been here long?",
	"No questions. Excuse me... ",
	"Normal. Storms are pretty rare; the weather is usually sunny and calm.",
	"I am glad.",
	"Funny, isn't it? In actuality... it belongs to nobody.",
	"And no one has tried to invade?",
	"No, of course not. No one on outside knows of us. Well, no one of consequence. Only the poor spread rumors of their Island of Justice... But is there anyone willing to take them up on their story?",
	"True, true...",
	"Trunks, my friend. Trunks... We're big on trunks here. Mind, don't poke your nose into other people's trunks, because the penalties are stiff. Only open the public ones... if you can, that is.",
	"What do you mean?",
	"Everything needs a key here, friend. Mind, lots of people have the same keys. So if you want a reliable hiding place, you'd best look for a trunk outside the city, only accessible from the sea.",
	"Urgh. Okay, I get you.",
	"Hee hee! Ignorance is no defense. Whether they know the law or not, they break it, Capper slams the book on 'em!",
	"Right, that's what I expected.",
	"Quite well, as they say.",
	"How many?",
	"About five years.",
	"Aha, aren't you an old timer! I bet you were here even before old Hill Brunner. ",
	"Not before him, no.",
	"That's fine... What other old-timers do you know?",
	"Why do you want to know?",
	"Well, no reason. I'm new here. I'm interested, is all. ",
	"Okay, don't feel like you gotta answer. You answered your own question. Keep on looking, then...",
	"What do you mean?",
	"You can take it however you like.",
	"Hmm... All right. Thanks anyway.",
	"I'm sorry, I don't understand. What are we talking about?",
	"You've already asked that.",
	"Yes, we've gone over this.",
	"Look, you already asked me about that junk. I'm sorry, I can't help you! ",
	"I'm looking for cannon balls, bombs, canister, knippels, provisions, medicine... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah. Well... Yes.",
	"I get you, I get you...",
	"Ugh, I understand! I cannot be of any help at all. Even though... ",
	"Yeah, I know. Sorry.",
	"You can ask the house mistresses for bombs and canisters. Not much use for them around here...",
	"I see. Thank you.",
	"To accompany you? What an offer! ",
	"We've already gone over this.",
	"We have discussed this already. There's no need to do i again.",
	"Gosh, you're a bore...",
	"I'm still waiting for an answer.",
	"Yes... Sorry, of course.",
	"You know... ",
	"Well, all right... ",
	"I think I'd rather pass. I like it here.",
	"You bored yet?",
	"Nah, I don't get tired. I've got everything I need here, and it's all in easy reach.",
	"Well, maybe the storm that's coming will knock some sense into you. Problem is, it'll destroy the city.",
	"And how could you possibly know that?",
	"I've got my sources. You can trust me.",
	"Well, I don't. I'm sorry, but that's just silly.",
	"Well, as you like it.",
};
