string DLG_TEXT_LSC [197] = {
	"New faces! This makes me happy, since there's no other entertainment than these horrible stores. My name is ",
	", and I'm happy to be the first to welcome you to the city!",
	"Thanks for the warm welcome, though my arrival has turned out a bit soggy! My name is Captain ",
	"What did you want, monsieur?",
	"Listen, I'm looking for someone. You wouldn't be able to help me?",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some equipment.",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me?",
	"Nothing...",
	"Captain, it looks like you're the only survivor of this storm. I feel a strong pity...",
	"Me too... What is this place, buddy?",
	"This is the City of Abandoned Ships.",
	"And not the Island of Justice?",
	"Hm. Not exactly... They say it was called that once. But that was before my time.",
	"Understood...",
	"Well, then. I consider it my duty, so to say, to educate you in regards to our city.",
	"I'll gratefully and gladly listen to everything that you say.",
	"The first thing you must do after arriving here is get your citizenship. For that, you must go to the admiral of the city, Chad Capper.",
	"Chad Capper? That name seems familiar...",
	"You'll remember it later... Chad Capper is the head of the city. It's an elected position, so he came to power, so to say, the democratic way. Among his responsibilities is making sure the law gets put into action...",
	"... collecting taxes...",
	"Taxes? No taxes here. No one pays him anything, aside from the initial deposit.",
	"No taxes?! That's something, all right! This is truly the Island of Justice...",
	"Well, maybe so... If I may continue? You need to register with the admiral, as soon as possible. There's a storm now, so there are few people on the decks. But as soon as it ends... well, Capper will find you himself in any case. I don't suggest putting off the registration, so make haste!",
	"Okay, I understand. And when, in your opinion, will this storm end?",
	"Everything will calm down by tomorrow evening, for sure. The storm has already begun to subside.",
	"All clear. What else do I need to know?",
	"Th Admiral will tell you in detail about the law by which we all live, but I can briefly describe its basic tenets.",
	"Please do!",
	"So. It's forbidden to kill citizens, steal, or take ships apart so as to build something to sail away from here.",
	"Hold on a minute... So that means I can't leave this place?!",
	"Of course not! That's forbidden by the law! I don't want to get deeper into these topics, this isn't my business, go to the admiral... He'll tell you everything.",
	"And where is he located?",
	"On the warship San Augustine. That's pretty far from here. A bridge leads to the warship... Sorry, it's hard to explain if you don't know the landmarks. Look for the San Augustine!",
	"Understood... Listen, did you know a person named Teaser Dan?",
	"No, I'm not familiar with that name.",
	"Okay... Well, then. Thank you for the information.",
	"Think nothing of it. I'm always at your service, sir... Wait, I almost forgot some crucial information!",
	"Very comforting to hear that.",
	"Don't go inside the wooden barge San Gabriel, or the galleon Velasco! The Velasco is the ship we're standing on now...",
	"Why?",
	"You'll be killed. Those ships belong to the Narwhal and Casper clans. You can walk atop them, but you can't go into them!",
	"Hm. Well, then. understood. I'll keep that in mind. Thanks again for the kind greeting.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's ",
	"He's here, ",
	". Search more carefully.",
	"So he's here, among us! ",
	"Where are you looking? He's hanging out here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"Aha! I see. Thank you.",
	"Thank you! ",
	"She's here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship! ",
	"She's here on this ship; how queer that you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even talked a little.",
	"As far as I know, she's now at ",
	"So she's here, in ",
	". Search more carefully.",
	"So she's here, among us! ",
	"Why, where have you been looking? She's traipsing 'round here somewhere.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even chatted a bit.",
	"As far as I know, she's now at ",
	"A-ha, I see. Thank you, ",
	"Thank you! ",
	"I'm all ears, buddy.",
	"This city... Where did it come from?",
	"Have you lived here long?",
	"Do many people die here?",
	"Don't you know what the Diffindur is?",
	"Are there any interesting sights around here? Besides the residence of Chad Capper, of course... ",
	"How can I find my way there?",
	"No questions. Excuse me... ",
	"Some say that it's a natural formation that mysteriously attracts the ships. Others say that the place is cursed, and it'll keep growing at the cost of unending wreckage. With so much gossip and high fantasy it's hard to say what's right. ",
	"And what do you think?",
	"Does it matter? No more or less than anyone else's opinion.",
	"Regardless?",
	"Look around. Listen carefully. That noise, it's the wails of unknown thousands of doomed sailors, reverberating through your body, through each and every one of us. As you walk the deck, you'll pick up these sounds - just barely, but if you strain, you'll realize that all of this, it's naught but the echoes of those days when the ships plowed the seas.",
	"Okay. In a nutshell?",
	"The city holds not only us, Captain. Not just this scattered salvage. It has seized our souls, and even time itself. And through that, it can cheat eternity.",
	"Forgive my stupidity. I thought it was Chad Capper who was holding us here... ",
	"No, about three months. There was a night fight with pirates who'd seized a huge military ship. Our Captain was one of those desperate lunatics who will run at a dragon with a hunting knife. So we lost before we began. The battleship's first salvo swept away any stragglers from our deck, including the Captain himself and half his officers.\n",
	"I'd never experienced anything close to this. I threw myself to the deck, and just managed to force my way through the splintered spar and shreds of tack... The spectacle, Captain - it was without compare. As you can probably imagine. ",
	"So, I wasn't about to stick around for the next volley. I jumped ship, leaving my shipmates and board behind. I swam through the debris, picked the sturdiest chunk, and clung like a dead man. That's the last I remember. Next thing I saw was the sunrise, over this island.",
	"Fascinating... ",
	"Isn't it! I nearly soiled my pants, from surprise... But that's all history now. And I really like it here. It's calm, quiet... and you can't deny it's interesting.",
	"Not an uncommon sentiment, I see.",
	"Well, sure. Why resist? Of course, you show up and it looks like all the world's against you. All you want to do is get as far away as possible. And yet... this place, it grows on you. It gets into your soul. You'll get used, like we all do.",
	"I'm not sure I like the sound of that.",
	"And I'm not sure that anyone will ask for your opinion. I'm sure I'm not the first person to say this, and I won't be the last: your past is past. Forget about it! Start a new life! You'll see, it's not so bad here.",
	"I'll think about it. Thanks for the advice, Mister ",
	"More than. Recently they've been arriving in even larger numbers.",
	"Why, recently?",
	"I don't know exactly, but it looks like the city's fame has spread to the outside world.",
	"Hmm. This is not the first rumor I've heard of some Island of Justice. Maybe they were talking about the city... ",
	"Maybe. But if that's true, then how did the rumors get out?",
	"Hee hee... I don't know, but I'd love to find out... ",
	"Diffindur? Hmm... Perhaps that's one of the local ships, the Fernando Diffindur?",
	"What's this ship like?",
	"It's a half-sunk flute, that's about to break in twain, and is only clinging to the reef by some miracle. Nobody lives there - it's to dangerous.",
	"Where is it?",
	"All the way on the other side of the city. You want to talk to the tavern owner; he knows all about it.",
	"What? You've got a tavern here, too?",
	"We've got a tavern, a church, and a store! It's just like any other city. There's also a moneylender, name of Augusto Brahms, but, well... Steer clear of him. ",
	"Lovely. Can't escape them, can you.",
	"Here we have all the usual services - a church, a tavern, a store. We've also got a man who lends money. Though I tell you, that's about the most pointless enterprise of the lot.",
	"Why's that?",
	"There's so much gold here that it has no real value. You pull up some weeds, money falls out. You blow your nose, you get a handful of gold dust. People still collect it, of course. Force of habit.",
	"I don't understand. Nobody needs money here? Then what do they call it?",
	"I don't follow. Is that a joke? Money's still money; it's just not so important here. You'll get the idea soon enough.",
	"Hmm, yes. This is a little beyond me. I guess I'll keep an open mind...",
	"Oh, it's hard at first, I know. But it doesn't take long to get the hang of things.",
	"Hmm... Sounds promising. Is there a map of the place?",
	"There is indeed. I've seen one first-hand.",
	"Great! Where?",
	"In Eric Yost's store, on the Esmeralda.",
	"I see. Thank you.",
	"And what precisely, if I may ask?",
	"You've already asked about it. ",
	"Gosh, don't you have anyone else to bother?",
	"Look, you already asked me about that junk. I'm sorry, I can't help you! ",
	"I'm looking for cannon balls, bombs, canister, knippels, provisions, medicine... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah. Well... Yes.",
	"I get you, I get you...",
	"This is clear. What's unclear is why you need me. All right then.   \nIt's best to ask the ship mistresses for canisters and bombs; they have a ton of that stuff. Ask the admiral for weapons and gunpowder.",
	"What, and he'll just give it to me?",
	"I don't know. Ask him.",
	"Fine. I appreciate that. Thanks.",
	"Is the crew on board?",
	"Yes.",
	"So, do you have any available?",
	"I do.",
	"Interesting news... I agree! ",
	"Excellent! Then immediately go to the San Gabriel. Henrik Vedeker will transfer you to my corvette. ",
	"All right, I'll do precisely that. I'll just quickly gather my stuff and I'll be ready to sail.",
	"Don't be late.",
};
