string DLG_TEXT_LSC [169] = {
	"Greetings, mynheer. You can wait out the storm in my house. My name is ",
	"Greetings, mynheer. My name is ",
	"And I'm Captain ",
	". Wait out the storm, you say?",
	"Greetings, mynheer, to my home. My name is ",
	"Greetings, mynheer. My name is ",
	"And I'm Captain ",
	". For the sake of fairness, my former captain...",
	"May I help you with anything, mynheer?",
	"Actually, I'm looking for a certain individual. I don't suppose you can help me?",
	"I want to ask you a question.",
	"Can you tell me anything interesting?",
	"What's new in the city?",
	"Well, I would love an earful of the latest rumors...",
	"Lea, I heard that you know something about Leyton Dexter...",
	"Listen, I'm looking for a few trinkets.",
	"I'm about the grapeshot.",
	"You know, I'm collecting a team to haul out of here. I'm offering you to come with me, to the mainland.",
	"Nothing...",
	"Oh, you can stay here for as long as you wish. The law states that every homeowner in the city must give shelter to those in need, during natural disasters. Now is just such a time.",
	"Yeah, tell me about it... Well, then. The greatest of thanks to you. ",
	"I understand that it isn't easy to lose everything you've got. But you've saved yourself!",
	"Yes, yes. Of course...",
	"Listen, you shouldn't lose hope. I suggest you get hooked into our lifestyle quickly. Things here aren't so bad as they might seem at first glance.",
	"Thank you for the support.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please.",
	"Hm. Let me throw that by you again, then.",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it?",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him recently in ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, he's currently ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Keep your eye out.",
	"Hmm, so now she's on this ship... ",
	"She on this ship. Funny you haven't met her yet.",
	"Oh, I saw her recently. It was around ",
	"You know, I recently met her at ",
	". So look for her there.",
	"As far as I know, she's currently at ",
	"Excuse me, but she's right here, at ",
	". Take another look around.",
	"Hmm? She is here, among us! ",
	"If you were to look around more carefully, surely you would see her... ",
	"Oh, I saw her recently. It was around ",
	"I believe I met her recently at ",
	". So you'll see her there.",
	"As far as I know, she's currently at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"Why in the world do you want to be the mistress in this house?",
	"Have you lived in this house for a long time?",
	"Oh, pardon. Never mind me...",
	"Quite well. All is under control; my home is my fortress.",
	"This is excellent.",
	"And don't you even think to take something from me; I am watching you very closely.",
	"Certainly not!",
	"No, only for a year.",
	"I understand. You don't, by any chance, know anyone who's been here for a particularly long time?",
	"I knew one - Hill Brunner.",
	"Er, yes. Aside from him? He's not saying much now, unfortunately...",
	"Yes, a terrible story! The thing that really gets me is that it just doesn't make any sense!",
	"Too true... All right, Lea. All the best to you!",
	"And how can I help you?",
	"You've already asked about that. ",
	"Yes, we've gone over this.",
	"Look, you already asked me about that junk. I'm sorry, I can't help you! ",
	"I'm looking for cannon balls, bombs, canister, knippels, provisions, medicine... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah. Well... Yes.",
	"I get you, I get you...",
	"I have canisters on board. How much are you looking at?",
	"A hundred centners will be more than enough.",
	"All right, I'll give it to you. But before I do, I want you to bring me ten bags of salt.",
	"Excuse me?",
	"Ten bags of salt, I said. What part don't you understand? You want the canisters, son, you'd best hop to it.",
	"Okay... you'll, uh, get your salt, then.",
	"So you bring it?",
	"Yes, I have your salt. ",
	"Not yet. I'm having some trouble finding it... Don't suppose you'd like something else?",
	"Don't even dream of it! ",
	"Hrm. I see... ",
	"Excellent! Well, go ahead and take your canisters.",
	"Thank you. Only, how am I to deliver it to 'St. Gabriel?'",
	"Hmm...All right, you put some effort in for me, now I'll lend you a hand. I myself will arrange the delivery to 'San Gabriel.' I know plenty of men here.",
	"Excellent! I don't even know how to thank you! ",
	"Oh, don't worry about that. It's all right.",
	"All the best.",
	"Really? You're serious?",
	"Of course.",
	"You know, this place is already wearing on me. So if you say you're serious, then all right. I agree.",
	"I can assure you that you've made the right choice.",
	"I do so hope so. What do I must do now?",
	"Go to the the San Gabriel. Henrik Vedeker will transfer you to my ship. Don't dally! ",
	"OK, I'll soon be on the 'San Gabriel.'",
	"Faster than that, I beg of you... ",
	"Hmm, and why do you ask?",
	"Well, how can I put it? I've an inquiring mind.",
	"I'd advise you to divest yourself of that, if you plan to live here much longer.",
	"Do elaborate?",
	"Tangle with the Admiral, and you'll end up like poor Layton.",
	"So who is he? What happened to him?",
	"Do you really want to know? ",
	"Absolutely.",
	"All right... Since you're new, I'll tell you.\nYou may already know that Dexter was a pirate, just like Capper. At the start, the two were fast friends. When Chad became admiral, he immediately appointed Layton to head the Tartarus. That's the prison, I hope you know?",
	"Hmm... Yes, hard to avoid it...",
	"But then, well... I once chanced to visit Maxim Taylor, who was in one of his regular stints behind bars. It was already evening, and I hung around until midnight.   \nWhen I returned to the deck, I heard two voices - Chad's and Layton's. They were arguing about money... ",
	"I see... So what happened?",
	"Next, the argument was interrupted by a husky, gurgling moan. I am not a fool and quickly left the 'Tartarus.' That's all I know, but since then nobody has seen Layton Dexter.",
	"So you're saying Chad did him in.",
	"Can't say for sure, but it sure looks like it.",
	"All right... So this all happened on the Tartarus?",
	"Apparently, yes.",
	"All right. Thank you for being honest with me. It's refreshing!",
};
