string DLG_TEXT_LSC [94] = {
	"Greetings, my noble friend. How may I help you?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Nothing...",
	"And who are you looking for?",
	"I don't know who you're talking about. I need to know the person's first and last names.",
	"Understood. Let me try with the name again.",
	"Thank you, but I'd better look myself.",
	"But that's me!",
	"Wow, I came right upon you!",
	", are you talking about him?",
	"Yes, yes, it's definitely him.",
	"No, not him. Let do this over again.",
	", are you talking about her?",
	"Yes, definitely her.",
	"No, not her. Listen, let me give you the name again.",
	"You know, I don't want to ask about anyone anymore. Goodbye.",
	"Then give me the name again - first and last ",
	"I don't know, haven't seen him in awhile.",
	"Devil knows where he is...",
	"I haven't seen him in a decent while, so I don't know.",
	"Got it.",
	"A pity...",
	"I haven't seen her in a good while, My sympathies.",
	"I have no clue where she is now.",
	"Hm. I don't know where she could be now.",
	"Got it.",
	"A pity...",
	"He's here on this ship. Look closer.",
	"Ha! He's here, on this ship!",
	"He's on this ship. Strange that you haven't seen him yet.",
	"I saw him recently in ",
	"I met him recently in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where are you looking? He's hanging out here.",
	"I saw him recently in ",
	"I met him recently in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"Aha, got it. Thank you, buddy.",
	"Thanks! ",
	"She's here, on this ship. Take another look around.",
	"Ha! So she's here, on this ship! ",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". We even talked a bit.",
	"As far as I know, she's now at ",
	"So she's here, at ",
	". Take another look around.",
	"So she's here, among us! ",
	"Where are you looking? She's wandering around here somewhere.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"I'm all ears, buddy.",
	"Well, how are things after your stint in the slammer?",
	"Sorry, my mistake. Never mind!",
	"Currently, I am my wife's errand boy. I gave her my word I won't drink any more.",
	"You did the right thing.",
	"Hey, friend! Will you help me?",
	"And how can I help you?",
	"Tell my wife I got in trouble again.",
	"And who is your wife?",
	"Alice Taylor, my friend. She is the 'Ceres Smithy' fleut's owner. And my name is Maxim Taylor.",
	"Nice to meet you, Maxim.",
	"Likewise! Well, will you help me?",
	"If I see your wife, I'll definitely let her know.",
	"My friend, at the moment you're my only hope. Please, find Alice as soon as possible.",
	"All right.",
	"What do you need, my friend?",
	"Want to know something else, buddy?",
	"I remember nothing; it's all dark in my mind.",
	"My friend, can you get me out of here sooner? ",
	"Your wife wants to get you out of here. Can you tell me what you did that landed you in jail?",
	"No.",
	"Yeah, well... ",
	"You'll have be patient.",
	"I don't remember a thing.",
	"How's that? Nothing at all?",
	"Nada. I was already pickled, in the tavern. People say I went to the residence and ran into the Admiral himself. What a nightmare...",
	"Yep, you shouldn't drink that much. ",
	"I shouldn't, but now there's no way...",
	"Hee hee. Good show!",
};
