string DLG_TEXT_LSC [278] = {
	"What did you want? Don't hold me up with trifles. I'm busy.",
	"Sorry. Just popped in to say hi.",
	"When I'm not at my own residency, then, in principle, I'm not against talking... What did you want?",
	"Oh, nothing. Just wanted to know if everything's okay in the city.",
	"Aha! Here you are. It's good that you came here yourself. I don't like it when people run away from me, especially in this storm...",
	"I don't plan on running from anyone. My name is ",
	"Aha! Here you are. I was wondering when you'd show up here.",
	"Greetings. My name is ",
	"Admiral, I have important information for you. Hm, as I understand...",
	"I did everything. The Narwhal clan has been eliminated. I cut everything down to the root. No one left!",
	"Admiral, I wanted to talk about the murder of Hill Brunner.",
	"Admiral, I wanted to talk to you.",
	"Admiral. Tell me, please, what Maxim Taylor did here.",
	"Admiral, I want to help Maxim Taylor.",
	"Admiral, I found something out here abut the circumstances surrounding that matter with Taylor.",
	"Admiral, I have a small question for you about Leyton Dexter.",
	"Listen, I'm looking for some items here. Can't you bail me out here?",
	"Admiral, a storm is approaching...",
	"Yes, everything's fine. I'm happy that our city worries you so. You're a good citizen.",
	"Happy to try, Admiral!",
	"Very pleased, buddy, just remarkable... And I'm ",
	", admiral of this City of Abandoned Ships!",
	"Ha! I've heard about you! You're that pirate captain who came out for the prize on the Horror of the Main! So this is where you've gotten to!",
	"Yes, they still remember me in the Caribbean Sea... You see what happened. We spent two days pursuing a Spanish galleon, and on the night of the third day we ended up here. All my damned team went to the bottom. Only I, Workman, and Fore were able to climb out.",
	"My sympathies...",
	"To tell you the truth, our team was a whole lot of crap back then. So you don't need to be too sorrowful. And anyway, it's all in the past... Now this isn't the time for that!",
	"Say what you need. I'm listening closely. ",
	"Now then! From the moment you came out of the sea and climbed out onto the deck of our island, you were a citizen of the city, and so you must yield to its law. Do you understand that?",
	"Quite. And what is this law? How might one become familiarized with it?",
	"I'm introducing you to the law right now.  It's not set in tablets, since we've been running low on rocks! Ha, ha... And the Law basically amounts to the following points. ",
	"All the citizens of the City of Abandoned Ships have a right to life. This right provides for a militia garrison, in the service of the admiral, meaning in my service... By the way, do you want to sign up for the militia?",
	"We'll see later. I need to get used to things first. Get set up here and everything. Then I can decide those questions.",
	"You don't look like a weak guy. Who were you, in the wider world?",
	"Oh no where in particular. I just, you know, wandered around... Was a free captain. Same as you, basically.",
	"I see... But now, in any case, it doesn't matter to me. You could've been a Spaniard or a Frenchman, an angel or a bald devil. Everyone's equal here. You're now a citizen of the city, with his own rights - the most important of which is the right to life! Heh. I wrapped that up nicely!",
	"Yeah, not bad. Universal justice. By the way, in the Caribbean there are rumors about some Island of Justice. I guess that would be your city?",
	"No, that can't be. The way out of here is forbidden... Let's continue. Now, that's it about the law. Now, about your responsibilities First. you can't try to take the lives of the citizens of the city. If you kill someone, then I'll kill you. Is that clear?",
	"Hm. Clear enough...",
	"One small nuance. There are two societies in our city, the so-called Narwhal and Casper clans. In general, there you've got people who consider the life of a decent person a bone in their collective throat. We've issued them two ships as their permanent place of dislocation - that's the wooden barge, San Gabriel and the galleon, Velasco. The ships stand on the outskirts by themselves, so they don't get in the way of the city life. ",
	"Now, it's not worth going into those ships for the citizens. It's dangerous for your life. The insides of these two vessels have been remade into the possessions of the clans, and on that territory their laws rule. So if you go there, blame yourself. Got it?",
	"Got it.",
	"Let's go further. Second up, it's forbidden to build ships, rafts or other flotation devices. It impossible to get out of here anyway, and you can't destroy the city.",
	"I got that.",
	"Third, the death penalty is customary for stealing. If you're found digging in someone's chest, you'll automatically be stripped of citizenship and you become beyond the law. And that means that you forfeit your right to life...",
	"Sounds intriguing... Well, everything's clear. What's next?",
	"Fourth and finally, all the material objects that come into the city belong to the city.",
	"Hm. More details on that point, please.",
	"Heh, what's confusing here? Here, for example, you're a physical being that's come into the city. And notice, you've instantly become its citizen. \n Now your belongings, as material means, become the property of the city. So now everything that yours is now ours!",
	"Hold it! I don't agree with such a deal!",
	"What a weirdo! We don't need your consent. We just take it, and that's it.... But I have good news. You, as a full citizen, are entitled to 1/50th of it!",
	"From my own belongings!",
	"No one's asking for your consent. Actually, the law demands that we include the former owner of the goods to be included into the list of share recipients. But since you broke the law, and I mean you didn't come to me on time after arriving in the city, that point of the Law is no longer effective for you. Meaning you don't get anything.",
	"I don't like this at all!",
	"That's it! You're starting to get it... Ultimately, you don't need all that junk, and it'll be pleasant for us...",
	"I don't like this at all!",
	"You're not the first who didn't like this place. But believe me, this is all in your best interest. The faster you get rid of all that ties you to the wider world, the quicker you'll flow into our even life. \n Or you can go crazy, which also happens. And I'll tell you that we don't put on airs. It's just a weight on your neck, and to the bottom!",
	"Yeah, there's enough justice to just get high off of...",
	"For that rudeness I'm stripping you of your weapon, and, well, cleaning out your pockets! And keep in mind, the next time, if I don't like you, I'll just finish you off.",
	"Well... Then, I'll have to submit. It looks like I have no way out.",
	"That's true. And I don't suggest you go looking for it either. It's forbidden by the law!",
	"I'll remember...",
	"Well, that's excellent... And now you're free to move around the city in any capacity. Do what you want, and enjoy the life of the city.",
	"I'll do that, Chad.",
	"Aha. So, you're the one who survived through the last storm. Tell me, pal, why the hell should I be looking for you all over the city? What, don't you know our rules?",
	"Hi there. What rules?",
	"You want to tell me that you didn't know about how you have to go to me as soon as you arrive in the city?",
	"How was I supposed to know that? ",
	"Ignorance of the law is no excuse! Now, tell me your name.",
	"Well. Sorry if I was late or something. I don't know the way things work around here, yet. I'll see what I can do about that in the future. I'm called ",
	"Say.",
	"I walked into the cabin of this corvette, and totally by accident I stumbled on an interesting object...",
	"What object? Out with it, man.",
	"It's a ring. Here it is, have a look.",
	"Ho-ho! This is the Narwhal amulet! Now, where did you find it again?",
	"In the cabin of the Protector.",
	"And did you know that's where carpenter and militiaman Andre Labor was killed?",
	"I heard...",
	"Mm-yeah, your find obviously shows who did that... Are you familiar with the Narwhals?",
	"No, Chad. They don't let anyone in. A little of anything, and they attack without saying a word.",
	"Yeah, that's the truth. They can do whatever they want, on their territory. They have their own laws there. And do you know how it happened that the clans were formed?",
	"Oh, tell me, please. I'm just bursting to know.",
	"Well, okay... The thing is, along with normal people, a lot of trash ends up here. They can't live with the rest of the world, so it was decided to give these people two ships to have. By that time, two groups of head-cutters had called the Narwhal and Casper clans.",
	"Understood... What do you do know? Since it turns out that the Narwhals are involved with murdering an official representative of authority!",
	"It's time to get rid of the Narwhal gang. I've gotten sick of their braindead qualities.",
	"A correct decision, Admiral!",
	"Without a doubt! I'm turning this over to you.",
	"Hm. Turning what over?",
	"Eliminating the Narwhals, pal. Moreover, who but you can get on this case? Since it's thanks to you that we know the truth!",
	"Damn! I kind of wasn't counting on this turn of events...",
	"What, slinking out? You're a pirate captain! What's with you?!",
	"There's a lot of them. I may have been a pirate captain, but I'm not into suicide.",
	"Aha! Well, we can arrange something. I'll give you three of my people to help.",
	"Well, then that changes things. I agree.",
	"Excellent! Go to the Velasco immediately, and sort things out there. My people will be waiting for you on the Velasco.",
	"Sure, Chad. I'll do everything in the best form.",
	"Well that's good. And how are my people there?",
	"All dead, unfortunately. I really pity them...",
	"Ah, everything's fine. Everyone's alive and well. I'm returning them to you safe and sound.",
	"There are losses, but not everyone died. I'm returning those still alive.",
	"Mm, yes. A pity. Still, the mission is accomplished. The Narwhals have been eliminated, and that's the  most important thing. So everything's in order.",
	"Yeah, everything's going smoothly.",
	"Well, then. Excellent. I'm not holding you any more. You can go.",
	"Hm... Well, thanks, Admiral...",
	"Excellent! For a job well done, I'll throw you a little cash, I think. A hundred thousand gold! Take it. It's yours.",
	"Hm. I don't need money here yet, but thanks anyway.",
	"Think nothing of it! Well, I'm not holding you any longer, so you can go about your business calmly.",
	"Hm... Good.",
	"Mm. Yeah, that's somewhat uncomfortable... Well, okay. It was a butchering, after all, and not a easy stroll on deck. In general, I'm happy that everything ended well. I want to throw you a little cash for your work. Ten thousand gold!",
	"Well, I don't really need any money... But thanks anyway.",
	"Happy to see you, admiral.",
	"How are things going for the Casper clan?",
	"Happy to see you, admiral.",
	"Quiet... I think there's someone behind the grating. Let's talk somewhere else.",
	"Not bad. Especially in light of how you crushed their competitors.",
	"Hee, hee... And you know, everything happened by itself. I pointed them out to that idiot...",
	"What idiot?",
	"That new citizen. Name of ",
	". You probably heard that our carpenter and one militiaman were killed. So that new citizen brought me the Narwhal amulet, and said that he found it at the murder site. Even though it was sewn with white thread, I didn't spend too much time figuring out this case, since I wouldn't have such a nice chance to carry out my long-planned action without drawing suspicion to myself. I sent that hero to sort things out, and also gave him some people from the militia as backup.",
	"Well, that he worked for you is wonderful. But I hope you didn't let him into our plans?",
	"No, I don't trust him. He was a privateer captain on the mainland, and one needs to be wary of such people. It's one thing to use them in our interests, another to hook them into our business.",
	"Now, about our business. There's been a lot collected, and my boys can't wait to throw away their shares in the brothels of the Caribbean Sea. When will we start our preparations to sail off from this damn place?",
	"It's still early. I haven't collected enough money.",
	"?Caramba! My chests are cracking under the money and jewels! And it's still not enough for you?!",
	"Don't raise your voice to me, or I'll rip out your throat!",
	"Sorry, Admiral. Won't happen again...",
	"Look at me closely! And now listen closely. Maybe there's enough money to visit brothels and buy all sorts of junk, but I have totally different plans for the mainland. I want to become a governor, and to do that I have to go to London and hand money out right and left without counting! Now do you understand?",
	"I got it. But understand us. We've been working so long with you, collecting the jewels and diamonds, and we haven't even begun building a ship! I'm having a difficult time controlling the people.",
	"And we can't start building because our carpenter's been killed. You can say that to your people.",
	"Mm, Yeah, they're collecting ship drawings, tools for building... And what to do? Maybe, force the Mechanic?",
	"I'm against it. That madman isn't reliable. With his babbling speeches, he'll throw the dust in everyone's eyes. Do your people, by the way, socialize with him?",
	"No, I monitor that closely. The mechanic won't be coming out of his rathole.",
	"Good... Now, you'll tell you people that we'll begin building a ship as soon as a new carpenter turns up. Hee, hee... The next wood-cutter's gonna be real lucky...",
	"You'll leave him his life?",
	"Of course, that's the law! Haw, haw! Well, then. I think we've smoothed over the current problems.",
	"I think everything will be okay.",
	"Excellent. Go back to the clan, and keep your hand on the pulse.",
	"Say.",
	"I think that an investigation should be conducted.",
	"Hm. Good thought. Maybe you'll go the murder site and find something that might reveal the criminal's identity? Do you want to?",
	"Maybe I do! ",
	"Go and search, my friend, and do it right. Only this time, I won't be so credulous... if you get what I'm saying?",
	"Hmm... Not quite... ",
	"Now, rather than simply decide on a punishment, I shall run my own personal investigation.",
	"Oh, I see now. I am focusing on the investigation myself. Will you keep me up to date on your findings?",
	"Hardly. And frankly, I find your zeal hard to comprehend. Were you friends with Hill? What was your relationship based on?",
	"Nothing special. We would talk, sometimes.",
	"If that is true, then don't meddle. Here in the city, you are a nobody. Don't take too much upon yourself, or the strain may become unbearable.",
	"Crystal clear, Admiral.",
	"What a coincidence! Well, talk! What happened on board the St. Gabriel?",
	"Do you remember how you advised me to launch my own investigation into the murder of Hill Brunner?",
	"Did I say that? Have you lost your mind? ",
	"Well, not exactly. But you didn't forbid it. So I went on board the St. Gabriel, looking for evidence...",
	"Idiot! Didn't I tell you not to go there?",
	"No, you said that they have their own laws on 'St. Gabriel.' I had no idea the laws are so bloodthirsty. In a nutsell, they jumped me and I had to defend myself...",
	"And?",
	"I defended myself. Result is, it seems the Casper clan is no more. Just like the Narwhal clan. The City is now free of rogues of all stripes.",
	"I find that hard to believe... ",
	"Well, you don't have to take my word for it...",
	"You're not human, are you? You're a devil. Slaughtered two whole clans! ",
	"If I may, one of those was on your direct order...",
	"Mmm... Well, did you find anyone else on the St. Gabriel? Aside from the Caspers?",
	"Yep. A man by named Henrik Vedeker sends you his greetings.",
	"So, the mechanic is alive... ",
	"Shouldn't he be? He didn't attack me, anyway. So I had no reason to touch him... ",
	"Hmm, no. Didn't touch him... You know what, my jousting jester? Your escapades have begun to wear on me. I am beginning to wonder if I'd be best tying a weight around your neck and letting the flounder play backgammon with your ribs.",
	"It won't happen again, Admiral! ",
	"Shut up, moron! \nThe only reason I'm keeping you around is that I want to end this string of murders. And yet... I no longer want to pursue this investigation. Whoever is behind them, let's just allow the Caspers to take the blame, and put it all behind us. Are we both clear on this?",
	"Yes, Admiral! ",
	"Good. You must understand that I will grant no more exceptions in the City. The clans no longer exist, therefore there are no territories that are not subject to City Law. Is that clear?",
	"Yes, Admiral!",
	"So if you even lay a finger on anybody... ",
	"Admiral, I know the Law. Right to life for every citizen - it's all quite proper, if I do say so.",
	"Look at me, closely. Tell Vedeker to stay on the St. Gabriel, and stay mum. If he staggers around the city, scaring the folk with his ramblings, I'll throw him behind bars! \nActually... I may as well just send some men to get him. All right, you're free to go.",
	"Thank you, Admiral! You have my most supreme word, ",
	"Get out! ",
	"Goodbye, Chad.",
	"We'll see. What cargo are we talking about?",
	"You already asked about that.",
	"Yes, we've done this already.",
	"You already asked me about that stuff. I told you, I can't help you!",
	"I need gunpowder and weapons.",
	"Oh, yes... Sorry, this short-term memory...",
	"Ah, well, yes.",
	"I get you, I get you...",
	"What for?",
	"It's crucial, Admiral... ",
	"These pranks of yours and Vedeker's - they'll come to no good. Around here, you must follow the rule of law.",
	"Am I not? The law says nothing about collecting weapons or gunpowder...",
	"I seize all the weapons and gunpowder from the ships that turn up. It's all stored away in my mansion.",
	"You're not interested in sharing, then?",
	"For what reason? When I asked you why you need it, you didn't answer. Why this sudden burning need for explosives? Who or what do you want to blow up?",
	"What are you saying, Admiral? I'm not crazy! ",
	"It's for the sake of the city that I seize these things. One explosion could tear the place apart. You'll receive nothing from me.",
	"Yes, that's clear.",
	"You know, you've gained some popularity among the citizenry. If not for this circumstance, I'd have fed you to the very creatures that swarm under the city.",
	"Have you seen them, these creatures?",
	"No one has. And those who have, did it for the last time in their lives.",
	"I've seen them, Admiral... ",
	"You? Where?",
	"On the bottom.",
	"Mmm, yes... Now I am positive that you should be kept away from gunpowder. The mechanic has a destructive effect on your psychological well-being.\nI'll be watching you. Remember that if you make the slightest mistake, I'll send you to Tartarus - to prison. Is that clear?",
	"Clear, Admiral.",
	"You're free to go now.",
	"All right, Chad. Doesn't sound nice... ",
	"And?",
	"We've already gone over this.",
	"Don't want to hear a word about that! ",
	"Get lost! ",
	"There are reasons to assume that this storm will be very strong, Admiral The city is under the threat of destruction.",
	"Yes... Sorry, forgot.",
	"You know... ",
	"Very well... ",
	"Mmm, yes, you have lost your mind, indeed... ",
	"My mind is rather sound, Chad. And it is you who must open your eyes and admit, first to yourself, that the circumstances are dire.",
	"What?! ",
	"You, better than most, know what a city needs to be. And this one is hanging by a hair. You are risking people's lives by preventing them from sailing away.",
	"Keep talking about the city! The mechanic may be an educated man, but he is a coward and scare-monger. Had you seen the storms we've seen here, you'd understand what a joke his theories are. I told him to keep his thoughts to himself.",
	"Which he does... Listen to me, Chad. The storm that's coming is no ordinary storm; it's going to be monumental.",
	"How do you know?",
	"Henrik told me. He has a device that predicts storms.",
	"I've had enough listening to that mechanic's ravings. Listen, my friend - carefully, now! And you'd best remember this well, because this is my last warning to you.   \nSo long as I am admiral here, I decide to evacuate the city. And no one else. Understood?",
	"Chad, I've no interest in taking your place. To be honest, I did have some thought of that, early on... But now this is a question of life or death.",
	"So you admit your ambitions, eh? Hmm, I knew it. You'll never rest... ",
	"Admiral, let's not change the subject. We must save our own hides, and there is a way! All your plans will come to naught, if Vedeker proves to be right.",
	"Hmm... Do tell me more about my plans!    \nWell, thank you for this educational conversation. You may go now. And don't even think of scaring the citizens, lest I rip your head off! Remember, I don't intend to tolerate you any more.",
	"All right then, I've done all that I can to convince you. It's a pity that you won't listen to me... ",
	"Your time has come. Are you ready to die?",
	"Hmm, well I haven't made any special preparations... ",
	"Then you have two seconds.",
	"Where's Vedeker?",
	"You used them incorrectly.",
	"All's the pity... ",
	"What's it to you?",
	"I've said it all.",
	"I thought we cleared all that up.",
	"You're such a moron, buddy! ",
	"Hmm, I want to know.",
	"Right, right, I remember.",
	"Of course.",
	"Yep, sure am. As to why I's asking the same exact thing - I have no idea... ",
	"Well, don't ask any more. It's none of your business.",
	"Well, I am a citizen of this city, so to speak... ",
	"That's all. I don't want to discuss this cretin any further. ",
	"All right, Admiral. As you wish.",
	"Here, take him a bottle of wine... ",
	"Ha! That'll work, too. It's just that I want to help free him... ",
	"Sorry, friend. That won't happen! Enough, the whole city has tired of him. He'll rot in his cage.",
	"So, wait. Have you made up your mind to kill him?",
	"That is within my bounds!    \nBut, no, he'll get a life sentence.",
	"Gosh, Admiral, what did he do to deserve that? Come on, tell me? Please?",
	"Well... okay, I'll tell you. Though I really don't understand your curiosity.    \nThis brave soul put a knife to my throat, and demanded that I let him go home to Plymouth, right then and there.",
	"I can see how that would rankle you, but listen, he was drunk. He doesn't remember a thing. Haven't you ever been in that position? Can't you forgive him?",
	"The man shouldn't get his hopes up. That is, incidentally, what I told his wife, Alice. Jail is simply the best place for a drunken reprobate. That toothpick he was waving in my face - that doesn't bother me. ",
	"Hmm. I agree, that knife would be little more than a mosquito bite to you.",
	"I must say, I am quite puzzled with his complete loss of control when drunk. What happens if tomorrow he goes to the pub and then decides to put some ship on fire? For the sake of everyone, Taylor needs to be set apart from society.",
	"Damn... you may be right, at that.",
	"I've had enough of you... ",
	"Listen, Gilles Barou sent Taylor your way, so you can have a heart-to-heart conversation. ",
	"What do you mean?",
	"Aha. Gilles Barou promised me he'll talk to you and apologize for the lame joke.",
	"Well, that changes things a bit.   \nPlease, let Taylor know he has one more chance to settle down.",
	"Admiral, I think this decision is very appropriate.",
	"I will send a militiaman to Gabriel on the 'Tartarus', and you can visit Ellis and tell her that I'm letting Maxim go. ",
	"Excellent! I'll do that. Thank you, Admiral... ",
	"On whose behalf?! ",
	"Layton Dexter's.",
	"Hmm... Fine, ask your question.",
	"What happened to him? Nobody knows. And since you were friends... ",
	"All right, I 'll tell you.   \nLayton Dexter turned out to be a very greedy man. He bit off more than he could chew. And was punished for it.",
	"Punished how? Where is he now?",
	"He is guarding his money.",
	"That's punishment?",
	"In a way.   \nHave I satisfied your curiosity?",
	"Hmm... Somewhat.",
	"Good. Now you can return the favor. Why are you asking me about Layton?",
	"No particular reason, Admiral. I'm just trying to make sense of the place. I'm settling down now, getting to know people... ",
	"I see. As far as Dexter is concerned, I hope you now understand that he is occupied, so there is no point in seeking his acquaintance.",
	"All right, Admiral. As you wish. Thank you for the conversation.",
};
