string DLG_TEXT_LSC [223] = {
	"Hello! So you're the hero who's been able to get to me?",
	"Yes, that's me.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Good, very good... Be so kind as to name yourself, my esteemed friend.",
	"My name is Captain ",
	". And you are, as far as I can judge, Henrick Vedeker. The man they call the Mechanic.",
	"Correct! And how to do you know me?",
	"Oh, don't ask. Long story.",
	"Well, I'd hear it out. You have to understand, I've been deprived of contact with normal people for a long time. The Caspers tried to avoid socializing with me. By the way, about the Casper clan. Did you put them all away?",
	"To the man. And before that, I put the Narwhals under the knife.",
	"Hee, hee... So the city is free of bandits? Mm. Yeah, I take off my hat, as they say. \n Now tell me, please, for what sake did you perform such inspiring heroic acts?",
	"How can I put it... Understand, I came to this island by my own initiative, investigating the murder of Teaser Dan. Now I want to get the hell out of here.",
	"Teaser Dan? You knew Teaser?",
	"We didn't have a chance to meet, but I can say that he safely got to the mainland. Unfortunately, he was killed by agents of the Dutch East India Company.",
	"A pity. You know, I built the raft he used to leave here into the ocean.",
	"Really?! And how did he get to you past the Caspers?",
	"He often swam on the Fernando Diffundur. During one of these swimming sessions, I was on my platform, getting ready to immerse...",
	"Immerse?",
	"Yeah... I'll explain later. So we met, we talked, and I did everything for him to swim out of here and tell people about this island.",
	"Even though he made it to the goal, it was the stories about the city that became the reason for his death. The Dutch East India Company presumes there are these huge riches concentrated in the city, and that its sudden emergence on the market might ruin prices. In that case, commerce would go straight to hell.",
	"Interesting. That's means that Teaser Dan kept his promise to me after all, despite the risk to his life. Damn it, what a pity that he's perished!",
	"It is a pity, of course. You know, so many good people have been dying lately that I'm tired of pitying...",
	"Well, let's not focus on the sorrow. Do you think that this Dutch company of yours is right about the riches in the city? There's nothing that isn't here. And there's even more underwater...",
	"Seriously? How do you know?",
	"I've got eyes... But again, that's for later. Now tell me, my friend, what's going on in the city? Why have you come to me?",
	"The city's lorded over by Admiral Chad Capper. The citizens of the city live in accordance with the law, one of which forbids constructing any means of sailing. Well, I found out accidentally about the mechanic, and decided to have a talk you with you at any cost. That's it, pretty much...",
	"Chad Capper firmly holds the reins of the city, as before...",
	"Well, I wouldn't say firmly. Two clans eliminated, one after the other; citizens are murdered. People are unhappy with the Admiral and his militia, since ensuring their safety is part of their responsibilities!",
	"You know, my friend, I wouldn't be surprised at all if the Admiral were behind everything that happens in the city.",
	"Well, not quite. I'm playing my own game now. And the proof of that is the absence of the Casper clan on the San Gabriel.",
	"Hm, the Caspers operated in league with Capper, so I'm willing to agree there with you... Well, thanks to you, life in the city has seriously changed...",
	"Correct! And now I'm offering to hold an Admiral's election. I want to nominate my own candidacy for this role.",
	"What elections, my friend! You need to save your life before it's too late...",
	"What are you talking about?",
	"You know why they call me the Mechanic?",
	"I know. You came up with the system of linking the ships of the city with each other And, in general, I hear that whipping together something like that wouldn't be a problem for you.",
	"Fine. You, presumably, understand that I know more about the city than any other resident. Moreover, I'm not making any presumptions. I'm saying everything with absolute accuracy, since I studied the structure of the city underwater.",
	"Underwater?",
	"Yes. A few years ago I put together a suit for breathing underwater. In this suit, I sank underwater many times, while there was still such an opportunity. And here's what I'll tell you - the city will most likely be destroyed by the next strong storm.",
	"As far as I know, storms aren't a rarity around here...",
	"Not you, too! Don't argue with me! This is a question of life and death!",
	"Fine, fine... So what were you saying about breathing underwater?",
	"I went underwater and studied the reefs. So now, the city is standing only on three ships which became entangled into the reefs. The rest of the ships are merely linked with those three! Do you realize what this means?",
	"Mmm... Yeah, that's not too reassuring to think about. And what will happen if the city breaks off? We'll heave to?",
	"Nothing of the sort! Everything will go to the bottom, since the ships of the city aren't actually floating. No one will survive, since the destruction of the city will happen during a storm - a very big one, I add.",
	"That's some kind of apocalypse... And when will this happen?",
	"I don't know. I'm a scientist, not a medium! \n And, anyway, it could happen in any storm.",
	"Hm... What is to be done, then?",
	"I can help you, if you help me.",
	"An interesting offer. Tell me more, please.",
	"The thing is, I have a ship afloat. A few years ago, a ship docked to the city that had a small crack in the bottom, and I was able to fix it up while I still had the chance...",
	"You've been suggesting some lost opportunity a few times over, now...",
	"Ahh... Wel,l that was the opportunity to sink underwater in my suit. The thing is, some horrible creatures emerged there, that swim at the bottom and eat everything in sight. Now I'm not risking going underwater. I'm a scientist, not a fighter...",
	"Understood. So what should I do?",
	"First off, you have to buy a corvette off me. Then get something from the bottom, without which we won't be able to remove the corvette from the ships squeezing it in.",
	"Buy?! Hmm... So you're not really that interested in getting out of here and saving your skin? In the case of the apocalypse that you're predicting, you'll die as well!",
	"Well, I don't know exactly when the catastrophe will happen. Moreover, I see that you're an active and brave person, and it's within your strength to carry out my conditions. Moreover, I'm not asking a lot. Just a million and a half for the corvette, and the opportunity to dive into the water alone.",
	"A million and a half?! Have I misheard?",
	"No, everything's correct.",
	"But I don't have that kind of money!",
	"Well, money isn't a problem here, my friend. Search, and I imagine you'll find the sum I'm seeking without much effort, since the city is literally stuffed with treasures. Moreover, you can borrow it from Augusto Brahms. He willingly lends up to a million coins.",
	"Heh. There are a lot of bad rumors about him, going around... They say he's a warlock.",
	"Oh, not you too now. Listen, I'm a scientist, and this obscurantism is alien to me... And, anyhow, I'll give you a chance to go underwater. And there's a whole lot more money down there!",
	"Yeah, and there's also some kind of creature down there!",
	"Well, you handled the Caspers. So you'll deal with that problem... What are you being timid for? It's like you weren't the one that just took down an entire horde of head-cutters... ",
	"Okay, I agree.",
	"Well, then. That's great! I'll wait for you with the money, my friend, and that's the first question. Now you have to go before Chad Capper, and tell him that I've been freed... But no elections! Or he'll kill you.",
	"I understand that the elections aren't worth it.",
	"They just won't happen, that's all... In general, pass my greetings along to Chad, and inform him of the destruction of the Caspers. I don't think that will cheer him up, but it has to be done.",
	"Why?",
	"He'll find out anyway, if he hasn't already. So it's better for the man responsible for this party to inform him of it. You have to be very careful with Chad, or...",
	"Or?",
	"Or he'll finish you off, my friend. It's not worth getting the admiral angry, and you've done it. Chad had deals with the Caspers, and I've heard talks of him planning to sail out of the city with them.",
	"Interesting... And why not let anyone else out?",
	"So that nobody should find out about the city earlier than the timetable that Chad has in store.",
	"Understood... Well, then. I've got everything here. I'm off to handle these matters.",
	"So, how's it going with my money?",
	"I haven't got anything yet.",
	"I've got a little. I'm ready to give you a little sum.",
	"Well, try. I think everything will work out okay for you.",
	"I think so, too.",
	"How much?",
	"Are you jesting?",
	"Hm, sorry. There was a mistake...",
	"Hm. You don't have that kind of money on you. Let's not kid around...",
	"Hm... Fine.",
	"Oh, excellent! You've given me ",
	", and so far you've brought me ",
	". You still have to find ",
	"I'll continue the search.",
	"Okay, the job's done. I've gotten the sum I required, and now the corvette is yours.",
	"Very good. What's next?",
	"Now we must liberate the corvette. You see, it is stuck on the outer rim of the island's shipwreck junk ring, and is held by blocks on all sides.",
	"And how are we going to do this?",
	"I've already got everything ready. I tied the blocks around the corvette to a winch on my platform. All we have to do is activate the mechanism - and voilà, the corvette is free! ",
	"Sounds great. What's the catch?",
	"Smart one, aren't we! There actually is a catch. I dropped a gearwheel from the winch's mechanism into the water. Somebody needs to go down there and retrieve it. ",
	"Uh-huh... If I recall, you mentioned a suit for breathing underwater? I assume that's what you mean to shove me into?",
	"Exactly. I would have done it myself, but my mother didn't raise no fool. The creatures that live down there...",
	"Have you seen them?",
	"Yes... And to be honest, I wet myself from fear... I can't begin to describe them. Still, doesn't much surprise me that they'd gather here...",
	"Maybe they're harmless? How do you know they're man-eaters?",
	"They live on what the City residents throw down to them! That's the only reason they settled here.",
	"I see... all right, then. I'm ready.",
	"Let me tell you how to use the suit. I managed to compress about six minutes' worth of air into it, which you'll be breathing. Any longer than that, you'll be done for. You get that? Be back in six minutes, or else. Don't turn back in six minutes; be back.",
	"Okay, I get the time limit. That's all I understand, though.",
	"Then you got the important thing. Go on to the platform; the suit is waiting there. It's good for one dive, as it is now. I guess you don't need me to dress you. Remember, best you only dive during the day, between ten in the morning and seven at night. When you're done, leave the suit where you found it. Say hi to Davy Jones for me.",
	"Thank you... ",
	"The dog of war",
	"You know, there's now some kind of mechanic in the city... People are saying he's the oldest citizen! Must be some kinda mistake... ",
	"You ever heard of Henrik Vedeker? Unbelievable! It turns out he was kept locked up on the San Gabriel for many years.",
	"Rumor has it our new old timer, Vedeker, is a very capable man.",
	"I don't reckon this mechanic is so important here. We've lived without him 'til now. Won't miss him if he keels over.",
	"Well, how are things going?",
	"I'm preparing for the dive. I'll let you know when I'm back.",
	"I need to go down again. There are still a couple things I want to do down there...",
	"I found the gearwheel. Here it is.",
	"Won't stop you. The suit is at your disposal... at a price. Put thirty thousand piasters on the table, and you're as golden as it is.",
	"What, again? I've already brought you a million and a half.",
	"Sure, that was for the corvette and for one dive. I never said I'd sell you the suit; that belongs to me. I am leasing you the suit. Equipment wear and tear, and all... ",
	"What wear and tear?",
	"What, you never hear of miscellaneous expenses? Well, it's pointless to argue. Thirty thousand, and you get your rendezvous with the sea devil. No money, no dive.",
	"Hmm... Yeah, okay...",
	"Look, you got no cause to complain. What I'm selling you is the opportunity to make back far more than you're paying. With so much treasure lineing the seafloor... 'Course, if you're just diving for pleasure, then excuse me... What I'm sayin' is, if you're goin' down, keep your eye out. ",
	"I see... ",
	"Well, how are things going?",
	"I'm gathering strength for my next dive.",
	"I want to dive to the bottom one more time.",
	"I found the gearwheel. Here it is.",
	"That's it. I'm done diving. I'm no longer interested in the underwater kingdom.",
	"Did you have the money ready?",
	"Yes, I'm ready to pay.",
	"Not yet... I'll have it, don't you worry. ",
	"Come tomorrow. I'll get the suit ready for action.",
	"Um. Sure, okay.",
	"Everything's in order. The suit functions properly, and is supplied with air. I'd wish you good luck, if I did that sort of thing.",
	"Thank you.",
	"The suit ain't ready yet. Come back tomorrow.",
	"Um. Sure, okay.",
	"Excellent! Give it to me faster.",
	"Yes, of course.",
	"Well, now I should be able to rebuild the winch mechanism. Tell me, do you have any other dives scheduled?",
	"I do. I intend to study the bottom more thoroughly.",
	"No, I don't. The underwater kingdom doesn't interest me any more.",
	"Well, that's a fine thought. You know my conditions - thirty thousand per dive. Best of luck to you.",
	"Um. Sure, okay.",
	"Okay then, it's your decision. Then I will pack the suit away.",
	"As you say.",
	"Now that I got all I need, I'll start in on rebuilding the winch for your corvette. It'll take a while, mind. For the time being, no sense resting on you laurels. You'll want to start planning for your trip.",
	"What sort of plans?",
	"For starters, you'll wanna stock your ship. Food, ammo, weapons... You know the drill better than I. Whatever you find, you bring it to the St. Gabriel. From there, I'll get it moved to the corvette.",
	"I see; I'll see what I can pull together.",
	"Hey there. So how you doing with the cargo bay?",
	" cannon balls, ",
	" grape shot, ",
	" chain shot, ",
	" exploding shot, ",
	" sailcloth, ",
	" boards, ",
	" gunpowder, ",
	" provisions, ",
	" weapons, ",
	" medicine, ",
	"Haven't got a thing yet, but I'm working on it.",
	"I've got some things... ",
	"I still need ",
	"I've got all I need in the hold. Now it's just a matter of time.",
	"All right then. I wish you all the best. And try not to take too long.",
	"This suits my interests.",
	"Well, that's just peachy! Whatever you've dug up, I've already got it moved to your cargo bay. Next up, you'll need a crew. You should know that the two of us aren't enough to handle a corvette. ",
	"Oh. You couldn't have mentioned that earlier, could you? Here I've been, running all over the city, talking to people...",
	"Well, first, I doubt the Admiral would appreciate it. Second, I didn't see the rush. But now... things are getting problematic.",
	"What do you mean?",
	"You see, all the years I've lived here, I've been waiting for the the storm that would wipe the place out. I've been waiting so long, I got sick of just waiting, so a little while ago I tossed together a weather-predicting machine. I call it the 'storm-o-meter! ' The principle is actually really simple... ",
	"I'm sure it is. So, what's this doom you're hinting at? ",
	"Ah, yes, yes... You see, my storm-o-meter indicates that what approaches is not just a storm, but a hurricane. I can't even tell how powerful - the indicator goes off the scale.",
	"So. This is the time of reckoning? ",
	"That's right, my friend. I can say with a good dose of certainty that this time, the city will be destroyed. So, best get crackin'.",
	"I intend to. By the way, how'd you do with the corvette?",
	"Not yet, but I tested the winch, and it is in full ready mode. Go contract people, let them come this way and I will ferry them over to the ship. We need at least 15 men to set sail. As soon as you gather enough men, immediately head back here. Once you 're back on 'St. Gabriel' we'll activate the winch and free the corvette.",
	"All right, I got it. I'll start drawing up the contracts...",
	"You haven't got enough men for the voyage. I've only seen ",
	". Keep going. And hurry it up, will you?",
	"You need men for your crew. Hurry up! ",
	"Um. Sure, okay.",
	"Ah, here you are! ",
	"Exactly. I came to help.",
	"Well, thank you. I didn't expect that... But it's all for naught.",
	"What do you mean?",
	"Well, I'm locked away here, and my escort took the key to the Admiral. The order went to the prison warden himself. Ain't no way I'll get out in time...",
	"The Admiral is no more; I've dealt with him. But I didn't see any key... I'll go back and take another look! ",
	"It's too late, my friend. The hurricane is gathering strength.",
	"I'll be fast!",
	"Not fast enough. Anyway, there's no point in risking the corvette and lives of all those people already on it. You're a captain. Go on, and take charge. ",
	"Henrik, believe me. I'll free you.",
	"Nah, I decided a while back I'd stay. See, I'm a scientist. And I'm old. I've been working on this theory for so long, doesn't seem right not to be here and watch.    \nAnyway, I could be wrong. Maybe the city will survive the elements. Then anyone left behind can start a new life, without the clans, without the Admiral.",
	"Are you sure?",
	"Yes, I made up my mind. Now, listen up. Here's how to find your corvette.",
	"I'm listening.",
	"Go to the Fernando Diffindur, the main mast. The ship's nearby. Before they locked me up, I managed to pry away the ships around the corvette. Now you can leave the city, no problem.\nThe storm is gaining strength, so I'm afraid it'll be a rough ride... Once you clear the Tartarus, make sure you keel right, lest you want to perish in the chaos. Like I said, go towards the main mast of the Fernando Diffindur. Got it?",
	"I do. Thank you... Maybe I should try to open this damned cage anyway?",
	"Farewell. It was pleasure doing business with you. Now my fate is no longer your concern.",
	"Farewell, Henrik Vedeker. Good luck riding this out. I hope you survive!",
};
