string DLG_TEXT_LSC [192] = {
	"Ha, a new citizen! I imagine the storm won't get in the way of our introductions. I'm ",
	". I'm in the local militia.",
	"So you are the only survivor from the last ship in this storm? Well, then. welcome to the city. My name is ",
	". I work in the militia.",
	"I see a new citizen in the city! Welcome, as the saying goes, and you can ignore the storm. My name is ",
	". I'm a member of the local militia.",
	"Hello, I'm ",
	". What's this militia?",
	"Greetings. My name is ",
	". And what's this militia?",
	"Ha, a new citizen! Well, hello and let's introduce ourselves. I'm ",
	". I'm in the local militia.",
	"So you are the only survivor from the last ship? Well, then, welcome to the city. My name is ",
	". I work in the militia.",
	"I see a new citizen in the city! Welcome, as they say. My name is ",
	"I'm a member of the local militia.",
	"Hello, I'm ",
	". What's this militia?",
	"Greetings. My name is ",
	". And what's this militia?",
	"There's been a crime somewhere?",
	"What's the matter? There's trouble in the city?",
	"Something happened?",
	"Listen. I'm looking for someone. Do you where he might be now?",
	"I need to find somebody. Have you seen him nearby?",
	"I want to ask you a question.",
	"I have a question for you.",
	"Listen, I really need gunpowder and weapons. The Admiral doesn't want to give anything to me, but I really need it...",
	"Greetings, buddy. Well, the time has come. We're off.",
	"Well, how are things?",
	"Well now, buddy, it looks like the time has come.",
	"Buddy, you and I have talked before about how you want to leave this cursed island with me.",
	"No, everything's normal.",
	"The militia provides order of the law for the citizens of the city.",
	"The militia watches everything that happens. In general, it's the authority in the city...",
	"Well, in an ordinary city you've got your governor and your garrison of soldiers. Here, our governor is the Admiral and our garrison - that's us, the militia.",
	"Understood...",
	"Now it's clear. Thanks for clearing it up.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him recently in ",
	"I believe I met him recently in ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"She's here, on this ship. Take another look around.",
	"Ha! So she's here, on this ship! ",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"So she's here, in ",
	". Take another look around.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"I'm all ears, buddy.",
	"Go on, spill it. I'm listening.",
	"I'm all ears.",
	"Listen, what is this place?",
	"What's this funny island?",
	"Hey, buddy, what's the deal with this island, here?",
	"Have you ever tried to get away from here?",
	"You know of a good way to stroll out of here?",
	"Have you tried sailing away?",
	"No problem. Sorry, buddy... ",
	"Ah, slipped my mind. Forgot... ",
	"This is the City of Abandoned Ships. And you're its citizen now.",
	"Quite a funny place, isn't it? The island is the City of Abandoned Ships. Now there's no way for you outta here.",
	"This is the City of Abandoned Ships. It's all a heap of ships the devil brought here.",
	"I see.",
	"I see... ",
	"What for? I see no reason to complain about the food here... ",
	"It's illegal, you know. Anyway, I'm not interested. Pretty happy here.",
	"See, buddy, I've got everything I need to be happy. Why would I look for somewhere better?",
	"I see.",
	"I see... ",
	"We're ready to attack. Lead the way.",
	"I've been waiting for you... Go on, don't hesitate.",
	"Let's send these Narwhals to hell! ",
	"All right! ",
	"We did it! ",
	"Ho ho! the Admiral will be pleased... ",
	"We did it. The Narwhal clan is now history! ",
	"I've no intention to hold you any longer.",
	"Whyja need powder and weapons? They ain't no use here.",
	"All decided.",
	"I'll do everything.",
	"My, you're tenacious.",
	"Maybe they're not - here. But you never know... They do have their uses.",
	"Excellent! ",
	"Ah, well, yes.",
	"Aha.",
	"At sea, you mean?",
	"Hm... Could be.",
	"Right... You know, I'll give you a hand here, if you take me with you.",
	"Deal. You picked just the right time, at that.",
	"Okay I guess, I can pinch from the warehouse, while nobody's looking... How much powder you need? How many weapons, and where should I send all of this?",
	" I need two hundred hundredweights of powder, and fifty weapons. The delivery point is San Gabriel barque.",
	"All right, I'll see it done. Don't you forget to come back for me, mind! ",
	"I certainly don't intend to, friend.",
	"Great! So when will it happen?",
	"Right now, I'm just pulling a crew together. So, welcome aboard. Get off to the San Gabriel. Henrik Vedeker is there, and he'll send you to my corvette.",
	"Yeah, that would be nice. But you know, I guess I'd better wait here.",
	"What for?",
	"The Admiral is proper irked about you. I guess he's thinking about offing you. So I'd better stay here and keep watch. If you have problems with Chad, I can cover for you.",
	"That would be a help. You know, buddy, when this is all over, I'll be glad to have you as an officer at my corvette. Monthly wage, guaranteed.",
	"Sounds interesting. I may well agree. But first things first.",
	"Exactly! Well, you keep here and wait for me.",
	"It's quiet now, but you'd best be on guard! Mind, if there's a stir, I'll come to the rescue.",
	"Perfect! Thanks a lot.",
	"I'm ready. Get to the town hall. I'll follow you later.",
	"Settled! ",
	"Yes, that's right. So what do you think?",
	"If you give me a hand now, I'll take you on as an officer, with a decent monthly wage. We're leaving, and I need your help right now.",
	"All right. What can I do?",
	"Looks like there's about to be a big old ruckus in the town hall. If you fight as one of my men, then it's a deal!",
	"Hmm... the Admiral isn't some sissy boy. But what's life without risk?",
	"Great! Then the plan is, wait here. If you hear a commotion, you come running. ",
	"All right. I won't let you down, Captain.",
	"That's a pleasing thing to hear! ",
	"Looks like we beat them off.",
	"It does... Thanks, pal. You proved as good as your word. I owe you one.",
	"No big deal. I'm ready to join your crew. What's your offer?",
	"This is no time to wrangle. Give me a pitch, and we'll see... ",
	"Okay. As you say... ",
	"Look, the Admiral caught the mechanic. Have you any idea where he might be?",
	"Behind bars, of course. He'll have been sent to the Tartarus.",
	"Thanks. You've been a big help. Now head to the San Gabriel. From there, you should be able to find me corvette. All the men I've roped in, they're there already. You wait there for Vedeker and me.",
	"Sure thing, Captain. I'll just take one last look around here... ",
	"Fine. Just don't miss the ship",
};
