string DLG_TEXT_LSC [130] = {
	"Hello! I'm happy to see you. It looks like you're the only one to survive this horrible storm... Oh! Forgive me, sir. My name is ",
	", at your service. Happy to greet hospitable owners.",
	"Hello! I'm happy to see you. It looks like you're the only one to survive this horrible storm... Oh! Forgive me, sir. My name is ",
	", at your service. Happy to greet hospitable owners.",
	"Do you need something, sir?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"You can't imagine what a greedy and selfish person that Eric Yost is!",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me?",
	"Nothing...",
	"You know, giving shelter in case of a storm is our responsibility. However, I always do it with a great amount of pleasure.",
	"That's very remarkable.",
	"You know, in the city we're like in a cage. That's why I'm happy to meet new people.",
	"I too am happy to meet a pleasant person to socialize with. As I understand it, the city's underpopulated.",
	"You know, the weather's good now. But I'm sometimes even happy when there's a storm and the people stuck on the Velasco stay at my place to pass the bad weather. There's someone to talk to...",
	"Yeah, it sure is underpopulated.",
	"What's there to say? Melancholy can be fatal... So anyway, how did you end up here? Tell me, please.",
	"My ship crashed, and I lost my whole team. Unfortunately... Then again, on the other hand, I did get lucky.",
	"Hm... It may sound blasphemous, but you really were lucky.",
	"Yes, I understand that.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"I see.",
	"I see... Well, then thank you.",
	"He's here on this ship. Take a closer look.",
	"Hm... But he's here on this ship, right now... ",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him at ",
	". So look for him there.",
	"As far as I know, lately he's at ",
	"He's here, in ",
	". Take another look around.",
	"He's here, among us! ",
	"Were you more attentive, surely you would have seen him by now... ",
	"Oh, I saw him recently. It was around ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, lately he's at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Please look carefully.",
	"Hmm, so she's now on this ship... ",
	"She's on this ship. Funny you haven't met yet.",
	"Oh, I saw her recently. It was around ",
	"You know, I recently met her at ",
	". So look for her there.",
	"As far as I know, she's currently at ",
	"Excuse me, but she's right here, ",
	". Take another look around.",
	"Hmm, she is here, among us! ",
	"Were you more attentive, surely you would have seen her by now... ",
	"Oh, I saw her recently. It was around ",
	"I believe I met her recently in ",
	". So you'll see her there.",
	"As far as I know, she's currently at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"Listen, what island is this?",
	"How long have you been here?",
	"Pardon. I've no questions for you, sorry.",
	"Welcome to the City of Abandoned Ships, that's what we call this island.",
	"I see.",
	"Not that long ago, but I'm already bored to death here.",
	"I see... ",
	"Good gracious, am I dreaming?",
	"No, you're not... ",
	"Good Lord, it finally happened! Can I leave this place?",
	"Yes, if you hurry up.",
	"I'm ready for anything. What should I do?",
	"Go to the San Gabriel. Henrik Vedeker will transfer you to my ship. Don't hesitate! ",
	"OK, I'll soon be on the 'San Gabriel.'",
	"I beg you, faster... ",
	"What's going on with you?",
	"You see, he wants to rob me! ",
	"That's impossible! ",
	"Well, not literally. But this Eric Yost character, he wants to sell me a map for an unthinkable price! I've never heard of such a swindle! ",
	"It's only natural. If you have something to sell, you can charge any price. Eric has as much right to it as any.",
	"Quite a right it is... ",
	"And why do you need this map so badly? Have you no sense of direction?",
	"Something like that...",
	"Fine, I'll help you. For our Lord wants us to show mercy to our fellow creatures.    \nPop in to Eric tomorrow. I'll tell him to dock the price for you. ",
	"Will he listen to you?",
	"I have no doubt.",
	"Many thanks to you.",
};
