string DLG_TEXT_LSC [156] = {
	"Tell me, is it true that you tried to save Cecil Galard?",
	"Yes, that's so. Unfortunately, it didn't work out...",
	"My God, what a storm! Hello, my name is ",
	". I'm the owner of this home.",
	"My God, what a storm! Hello, my name is ",
	"Very pleased. I'm Captain ",
	". More accurately, Former Captain. And all because of this damned storm!",
	"Hello, my name is ",
	". I'm the owner of this home.",
	"Hello, my name is ",
	"Very pleased. I'm Captain ",
	". More accurately, Former Captain.",
	"What do you need, monsieur?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some equipment.",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me?",
	"Nothing...",
	"Don't mention the unclean, or he'll appear! And, in my home, be so kind as not to curse!",
	"Ooh, forgive me...",
	"Well, you shouldn't worry so much. In the end you're alive, and that's not bad at all!",
	"Yes, you're right. I'll ask forgiveness for a minute of weakness unworthy of a man...",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"Excuse me, but he's right here, ",
	". Take another look around.",
	"He's here, among us! ",
	"Were you more attentive, surely you would have seen him by now... ",
	"Oh, I saw him recently. It was around ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, lately he's at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Please look carefully.",
	"Hmm, so she's now on this ship... ",
	"She on this ship. Funny you haven't meet her yet.",
	"Oh, I saw her recently. It was around ",
	"You know, I recently met her at ",
	". So look for her there.",
	"As far as I know, she's currently ",
	"Excuse me, but she's right here, at ",
	". Take another look around.",
	"Hmm, she is here, among us! ",
	"Were you more attentive, surely you would have seen her by now... ",
	"Oh, I saw her recently. It was around ",
	"I believe I met her recently in ",
	". So you'll see her there.",
	"As far as I know, she's currently at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"Have you been here long?",
	"Are you bored?",
	"Tell me, were you here before Hill Brunner?",
	"I have no questions for you. Excuse me.",
	"Me... Hum, don't really remember. If you want to know how old this city is... well, it really is very old. Very.",
	"I see.",
	"In the home country? Of course... I have to put up with the situation, though. One can adjust. That's what we have to do.",
	"I'm not exactly eager.",
	"No, he's long been the host of the tavern.",
	"I see... Listen, does the nickname 'the mechanic' ring any bells?",
	"Hmm... Sorry, not really. You know, I'm rather busy at the moment. Sorry again.",
	"All right. Thanks anyway.",
	"Cecil was the oldest citizen in the city. Any ideas why she was killed?",
	"Not a hint, but as with Hill Brunner I was looking for someone who could answer me this question. I'm guessing she could have.",
	"What question?",
	"Who is 'the mechanic'?",
	"Oh, I know who that is. Didn't want to say earlier. Figure it wasn't safe. But Cecil's death made me change my mind.",
	"Go on, I'm all ears.",
	"That's got to be Henrik Vedeker. Most people in the city have no clue about him. I haven't seen him since the Caspers got themselves a foothold on the San Gabriel.",
	"And you, have you been here long?",
	"Not as long as Cecil, but sure, I'm an old hand. I've met the mechanic.",
	"So you say this Henrik must be on the San Gabriel?",
	"Must be. I think the Admiral keeps him secret. That's why he gave the San Gabriel away to the Caspers. Y'see, the mechanic is a veritable Renaissance man. No one can beat his handiwork. He used to tell us about some kind of imminent danger. Said we had to leave the city, before it was too late",
	"And, y'know, everyone just laughed. Nobody takes these weirdos seriously. And then came the law banning ship construction, and Caspers moved in on the San Gabriel. So no one spoke about our weirdo anymore. They all felt uneasy-like about the whole business. Anyway, it wasn't really safe.",
	"Are you sure Henrik is still alive?",
	"Pretty sure. Thing is, he was the one who figured out how to work ships into the island. The Admiral needs him. When he's gone, there'll be nobody to maintain the island.",
	"Ah, I see! Well, many thanks to you, Orelie. I reckon I'll have to find the mechanic, and have a good chat with him.",
	"Give it a try. Good luck to you.",
	"Thank you.",
	"What exactly are you looking for?",
	"You've already asked about that. ",
	"We've discussed this...",
	"Look, you already asked me about that junk. I'm sorry, I can't help you! ",
	"I'm looking for cannon balls, bombs, canister, knippels, provisions, medicine... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah. Well... Yes.",
	"I get you, I get you...",
	"I can help you with chain shot, though it's beyond me why you'd need all this junk.",
	"Just a project I'm working on. I guess a hundred  hundredweights should be quite enough.",
	"Fine, take it.",
	"Good Lord, I can't carry it on my own! Do you know anyone who can deliver it to the San Gabriel?",
	"Ask Pablo Barades. Tell him I sent you. He must be good for something...",
	"All right, I'll do exactly that. Thank you! ",
	"Really? Hmm, interesting... Do you really have a ship?",
	"Yes.",
	"Is it seaworthy? Could it get to the continent?",
	"Of course.",
	"Then it's a deal!",
	"All right. Now get to the San Gabriel, as quick as you can. Henrik Vedeker will send you to my ship.",
	"I got it. I'll do everything you said.",
	"Faster, I beg you... ",
};
