string DLG_TEXT_LSC [136] = {
	"Hi! We aren't acquainted yet. I don't think we have to wait for the end of the storm to get acquainted, so I'll introduce myself. My name is ",
	"And I'm ",
	"Hi! We aren't acquainted yet. My name is ",
	"And I'm ",
	"What did you want, buddy?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I've got to move something to a wooden barge called the San Gabriel. I wanted to ask you to help me.",
	"You know, I'm assembling a team to get out of here. ",
	"Nothing...",
	"How's your mood?",
	"Regular. The storm doesn't scare me anymore. So everything's in order. Getting settled in, bit by bit.",
	"Now then, I've seen you to. How's your mood, anyway, after that?",
	"What do you mean that?",
	"After the crash, of course. I remember that I couldn't snap back into myself for awhile...",
	"I've got no time to swing around. I have to get settled in here.",
	"And that's right, buddy. You can't let your sorrow take hold of your reason, or you won't make it far! Some lose their heads - and that would be fine if they were just harming themselves, but they harm the city as well. You understand, yourself. We don't even know what we're holding on by here, and then the ships start moving and... it's just horrible. Squeaking, cracking, the decks dancing under your feet...",
	"Yeah... And that happens too?",
	"What I'm saying is that our city is alive. You can't touch it. If you start taking it apart, building new ships to sail out of here, then it starts to take vengeance. That's how it is!",
	"Yeah, that's rough...",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Take a closer look.",
	"Ha! So he's here, on this ship! ",
	"He's on this ship. Strange that you haven't met him yet.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"So he's here, in ",
	". Take another look around.",
	"So he's here, among us! ",
	"Where have you been looking? He's hanging around right here.",
	"I saw him just recently at ",
	"I recently met him at ",
	". So look for him there.",
	"As far as I know, he's now at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"She's here, on this ship. Take another look around.",
	"Ha! So she's here, on this ship! ",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"So she's here, in ",
	". Take another look around.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"Go on, ask your question. If I can answer it, I will.",
	"Listen, what is this island?",
	"Listen, buddy, have you been stuck here long?",
	"Sorry, buddy. No questions.",
	"This is the City of Abandoned Ships, pal. Mind you, the city's alive. Some don't believe it, but you be sure it's true!",
	"As you say, I will.",
	"No, not really. About two years.",
	"I see. So Hill Brunner was already here.",
	"Yes, of course.",
	"I see, thank you.",
	"And why should I care?",
	"All decided.",
	"I'll do everything.",
	"My, you're tenacious.",
	"Orelie Burton asked you to help me.",
	"Excellent! ",
	"Ah, well, yes.",
	"Aha.",
	"Yeah, Orelie... Fine then, I'll help you. I respect the old bird, you see. What should I do?",
	"You should go to the Fury and grab a hundred hundredweights of chain shot, then bring them to the San Gabriel.",
	"Very well. I'll see it done.",
	"Thank you, my friend! ",
	"What is your command?",
	"A crew for my ship. My offer to you is to leave the city with me.",
	"Well, uh, that's quite an offer! I'll have to think it over... ",
	"No time to muse. You must decide here and now.",
	"Why such a hurry?",
	"Some say an upcoming storm might destroy the city.",
	"Hmm, sounds plausible. Every time there's a storm, the place near about falls to pieces. ",
	"And this is no ordinary storm. Anyway, time is getting short.",
	"All right then, I agree. I'll join your crew as a sailor.",
	"Perfect! Head off to the San Gabriel, right now. The mechanic there will help you to the ship.",
	"Okay, I'll just grab some things.",
	"Don't be late! ",
};
