string DLG_TEXT_LSC [178] = {
	"Ah, so it was you that came out of that storm? Well, then. Excellent! Let's introduce ourselves. My name is ",
	". And you are?",
	"My name is ",
	"Ah, so you're from the last batch of replacements? Understood... Well, then let's introduce ourselves. My name is ",
	". And you are?",
	"My name is ",
	"Buddy, do you want to pull off a little scheme?",
	"What kind of a scheme?",
	"Did you want something?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Well, now I'm ready to step through that imposing door.",
	"Listen, I'm looking for some supplies here.",
	"You know, I'm assembling a team to get out of here. How'd you like to come along, as a sailor?",
	"Nothing...",
	"Very pleased. Don't pay attention to the storm. It'll end soon. The people here are friendly, so become a citizen and everything will be all right. Overall, just welcome to the city!",
	"Thank you.",
	"Very pleased. Well then, get settled in here, bit by bit. The people who live here are nice and friendly, so, as they say, welcome to the city...",
	"Thank you.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, lately he's ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him recently in ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, he's currently ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thank you!",
	"She's here, on this ship. Look closer.",
	"Hm. But she's here, on this ship!",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her recently in ",
	"I met her recently in ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"So she's here, in ",
	". Take another look around.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks! ",
	"I'm all ears. Ask whatever there is on your mind.",
	"Damned storm! Do you often go through this?",
	"What is this island?",
	"What's worth seeing around here?",
	"And you, how did you get here?",
	"Back on the continent, more than once I heard of a certain Justice Island. That wouldn't be your city, would it?",
	"Look, have you lived here long?",
	"Sorry, my mistake. Never mind!",
	"I admit, it happens. By the way, if you haven't yet, I guess you should talk to the Admiral, Chad Capper.",
	"I see.",
	"This is the City of Abandoned Ships. Those who survived a ship wreck live here. Now you're one of us as well.",
	"Yeah, I am... now... Listen, why does all this stuff happen here? Does anyone know the reason for all these wrecks?",
	"They say ships bump into reefs... Some current brings them there... But it's all just guesswork. Nobody knows for sure.",
	"Well, has anyone at least tried to find out?",
	"Sure they have. But I wouldn't call it the brightest idea - the biggest noses tend to get chopped off, around here. I'd mind my own business, if I were you. You don't die, you're liable to go crazy. ",
	"Well, nothing like being optimistic...",
	"Since you're stuck here, my advice is to just accept it, and live like everyone else does. ",
	"Right, well. Thanks for your advice.",
	"First of all, you should pay a visit to the Admiral, if you haven't yet. Then you can go to the tavern and the store. Might pop by the church as well.",
	"Aha...",
	"Same as all the others. You were in a shipwreck, friend.",
	"I see.",
	"Don't know... Anyway, friend, it's not just our city. It's yours too, now.",
	"Splendid. I was always thinking of breaking into real estate.",
	"Not more than a year and a half.",
	"I see... ",
	"There is one place with piles of money... ",
	"And?",
	"My plan is to get in there and grab them, then split it later, fifty-fifty.",
	"Well, I'm in. Where's the place?",
	"The Esmeralda. That's where the store is, but I'm talking about the other side of the ship. If we get there during the day, Yost, the owner, will be away, and I can crack it.",
	"Well, if the owner is away and you can crack the place on your own, why take me with you? Or are you in the habit of givin half your proceeds to charity?",
	"It's not that simple. Eric's got himself three thugs, and they never budge from the place. I can't handle them myself, but you can.",
	"Aha. Now I'm getting the picture...",
	"So, are you in?",
	"Well, it's worth a shot. I can do with some extra money... Okay, let's get on with it. ",
	"Nah, not my style. I'm not really into looting.",
	"Well, as you wish, friend... ",
	"Yeah, see you.",
	"Great! So, here's the plan. You're free until the afternoon. When you're ready, run straight to the Esmeralda. I'll be waiting for you on the quarterdeck, next to the door with a skull over it. Then we'll see what to do next... ",
	"Deal. ",
	"All right! So you want I should open it?",
	"Yeah, go on.",
	"The door's open. Go on in.",
	"Great. So what are you gonna do?",
	"I'll wait for you outside.",
	"Fine, stay here and wait.",
	"So. We did it.",
	"Yeah, we beat the hell out of those two thugs.",
	"I wasn't hoping for anything otherwise. One can see at once you're a decent warrior... Now's the time to split the loot, friend.",
	"Look, I haven't found a red cent here. Not a penny. I looked everywhere. There's no money.",
	"All I found was ",
	". Half of it is yours, so take it.",
	"Well, I really didn't expect this... Ah, never mind. There's plenty of money around. I'll just get it somewhere else... ",
	"Yeah, you're right.",
	"Well, fine then! Glad it all worked out so well... Anyway. See you around, buddy. Any problems, just call on me.",
	"Certainly.",
	"What kind of goods?",
	"You already asked about that.",
	"We've gone over that.",
	"You already asked me about this stuff. I really can't help you!",
	"I need cannonballs, bombs, knippels, provisions, medicine, gunpowder, weapons... ",
	"Oh, right. Yes, sorry. I forgot.",
	"Ah, well, yes.",
	"Yes, yes...",
	"Why do you need it?",
	"You know. Never can be too safe. ",
	"Well, you can get bombs, cannonballs, and other munitions from the ship hostesses. There's plenty of that stuff around. For powder and weapons, though, you'll have to see the Admiral.",
	"I see. Well, thanks to you.",
	"Well well well! You're behind the times, I see.",
	"I'm waiting for my answer.",
	"Hey, buddy. Do you really have a ship to take you away from here?",
	"Yes.",
	"Then there's nothing to think about! I agree.",
	"Wonderful! Head off to San Gabriel immediately. The mechanic will help see you to my corvette.",
	"All right, I'll just grab my things. Won't be a moment.",
	"Hurry up! ",
};
