string DLG_TEXT_LSC [177] = {
	"Praise our Lord, Jesus Christ, for saving you! While the storm hasn't passed...",
	"Praise, Padre, and I'm grateful too for his giving me the honor of prolonging my pitiful life on this mortal plane... My name is ",
	"Let us praise our Lord!",
	"Praise, Padre, and I'm grateful too for his giving me the honor of prolonging my pitiful life on this mortal plane... My name is ",
	"What do you need, my son?",
	"I want to donate to the parish of the Lord, Father.",
	"I give a donation to the parish of the Lord, Father.",
	"Padre, I need to find one citizen. Do you know where he is now?",
	"I want to ask you a question, Father.",
	"Padre, may I help your parish with something?",
	"Padre, I want to return the candles to you.",
	"Father, I want to ask, can't I acquire a few items from you?",
	"Father, I want to ask, can't I acquire a few items from you?",
	"Father, I want to ask you for some medicine.",
	"Father, I have a serious offer for you.",
	"Nothing...",
	"I see, my son, that your soul is not calm. For one can't shift one's blame onto the Lord...",
	"Father, now, tell me one simple thing. For every successful turn in our lives, we praise our Lord, and for all the misses we have no right to blame him. How is that so, Padre?",
	"My son, are you without sin?",
	"There is no person without sin!",
	"Correct. Our shepherd leads the flock over many toils. Tell me, do you follow his commandments?",
	"Hm. I wouldn't say so...",
	"Then why are you resentful towards the Lord, if He tells you, do that, and you don't do it? If he implores, don't do that, and you do it? ",
	"His flock is like small children who don't follow their father's will. Everyone thinks that he knows everything and about everything. Praise the Lord for the gifts that he has bestowed upon you!",
	"You're right, Father. I am grateful to the Lord for my salvation.",
	"Good. And don't blaspheme, from now on!",
	"I won't, Padre.",
	"Oh you're a thief! Breaking the Law of the city!",
	"Isn't that something! I look away for a second, and you're shoving your head into the chest! He's broken the Law!",
	"Militia! I'm being robbed! Grab him! He's broken the Law!",
	"Ah, damn...",
	"Oh, so that's how it's going to be?! Thought you'd raiding some chests, did you?! Now the citizens and the militia will rip you apart like an old rag!",
	"Oh, you stupid broad... ",
	"Put away your weapon, my son. You're creeping me out a bit...",
	"You know, it's not accepted to wave your sword around here. Put away the weapon.",
	"Put away your weapon. It does not reflect well on a gentleman...",
	"Okay.",
	"Fine.",
	"As you say...",
	"And who are you looking for?",
	"I don't understand who you're speaking about. I need to know the person's first and last names. ",
	"Understood. Let my try to find out.",
	"Thank you, but I'd better look myself.",
	"But that's me!",
	"Wow, I came right upon you!",
	", are you talking about him?",
	"Yes, yes, it's definitely him.",
	"No, not him. Let do this over again.",
	", are you talking about her?",
	"Yeah, that's her.",
	"No, not her. Listen, let me give you the name again. ",
	"You know, I don't want to ask about anyone anymore. Goodbye.",
	"Then say the name again - first and last. ",
	"I don't know. Haven't seen him in awhile.",
	"Devil knows where he is...",
	"I haven't seen him in a decent while, so I don't know.",
	"Got it.",
	"A pity...",
	"I haven't seen her in a long time. My sympathies.",
	"I have no clue where she is now.",
	"Hm. I don't know where she might be now.",
	"Okay.",
	"A pity...",
	"He's here on this ship. Look closer.",
	"Ha! He's here, on this ship!",
	"He's on this ship. Strange that you haven't seen him yet.",
	"I saw him recently in ",
	"I met him recently in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where are you looking? He's hanging out here.",
	"I saw him recently in ",
	"I met him recently in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"Aha, got it. Thank you, Father.",
	"Thank you, Padre!",
	"She's here, on this ship. Look closer.",
	"Hm. But she's here, on this ship!",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her recently in ",
	"I met her recently in ",
	". We've already talked.",
	"As far as I know, she's currently ",
	"But she's here, ",
	". Look closer.",
	"So she's here, among us! ",
	"Where are you looking? She's walking around here someplace.",
	"I saw her just recently at ",
	"I recently met her at ",
	". Even talked, a bit.",
	"As far as I know, she's now at ",
	"Ah, I see. Thank you, father.",
	"Thank you, padre! ",
	"I'm listening, my son.",
	"Listen, what island is this?",
	"Tell me, padre, how did you happen to end up here?",
	"Tell me, padre, have you been here long?",
	"Sorry, padre. False alarm...",
	"This is the City of Abandoned Ships. I'm the only clergyman here. My missions is to set the citizens to the right path.",
	"I see.",
	"I was on my way to from the Old World to the new continent, to teach its pagans the higher laws. But it seems the Lord has his own ideas... ",
	"So you were shipwrecked too?",
	"Alas, it is true. No man may know our Lord's plans...",
	"That's very true.",
	"No, not horribly long.",
	"I see... Listen, er... You wouldn't happen to know anyone who has been here for a really long time?",
	"It doesn't really matter to me how any man found his way to this parish. What matters is that everyone here is my charge.",
	"I see... ",
	"Of course, my son. What sort of a donation do you figure, to atone to your sins?",
	"Sorry, father. Turns out I'm broke. See how impulsive I am...",
	"Well. Nothing dramatic. All I can manage is a hundred piasters... ",
	"How about a thousand piasters? That should do it.",
	"I'm pretty flush right now. What do you say to five thousand piasters?",
	"Hmm, the city parishioners won't be cheering in the streets... but all right.",
	"Sorry, padre. Never mind. Time to go.",
	"On behalf of our parish, I bless you for your kindness, my son.",
	"Any time... ",
	"On behalf of our parish, I bless you for your kindness, my son.",
	"Any time... ",
	"On behalf of your parish, I bless you for your generous donation, my son.",
	"Any time... ",
	"Yes, my son. The parish is in need of candles. The city has run out of them, of late. Perhaps you might help us, and fetch four hundred?",
	"Where do I find them?",
	"If I knew that, my son, I would do it myself. Do your best.",
	"Hum... Okay then, father. I'll try... ",
	"Look carefully, my son, for the reward will be ample.",
	"All right, padre. I'll do it.",
	"Okay, let's see. How many is this now? That's ",
	" candles, for a total of ",
	". So we still need another ",
	"Got it, padre. I'll continue my search.",
	"Wonderful, my son. I see you've finally found your way. We have enough candles for many services ahead.",
	"Well, just glad to help. So what about that reward?",
	"Of course, my son, as I promised... Well, I think you'll see your life changing here soon. Go in peace, my son.",
	"Thank you, padre. Though... er, I'm not exactly sure what for... ",
	"What is it, my son?",
	"You have already asked about this, my son.",
	"Yes, my son. We have discussed this.",
	"Really, my son. That is enough, along this line of inquiry.",
	"I need cannonballs, knippels, powder, guns, food, and medicaments... ",
	"Yes... Excuse me, it slipped my mind.",
	"Ah, well, yes.",
	"Yes, yes...",
	"Medicaments, you say? Something ails you?",
	"No, father... It's not for me. I need them for others, many medicaments",
	"Hmm. I do have medicaments, but first, my son, will you do me a favor? It's a simple task - I need some candles.",
	"Candles?",
	"How many do you need?",
	"You already asked about that.",
	"My son, we have discussed this.",
	"That will be quite enough, my son.",
	"I believe that fifty hundredweights will be just right.",
	"Oh, yes... Excuse me, it slipped my mind.",
	"Ah, well, yes.",
	"Yes, yes...",
	"My son, why do you need all of this?",
	"It's a project I'm working on. I'm afraid I can't really tell you yet, father.",
	"Well then. Not that I'm curious, for curiosity is a sin... You can take what medicaments you need. You have done me a favor, and this is my debt to you.",
	"Thank you, padre! I might be asking for too much, but is there any chance you could deliver these medicaments to the San Gabriel?",
	"I will see it done. Go in peace, my son.",
	"Many thanks to you, father! ",
	"What is the matter, my son?",
	"We have discuss this already, my son.",
	"I repeat, my son, it is all decided.",
	"Oh, my son, you are becoming such a nuisance...",
	"I'm forming a crew for my ship. Would you like to join it?",
	"Oh! Right... Yes, excuse me. It slipped my mind.",
	"As you wish... ",
	"Well, all right... ",
	"Oh? Well, I do thank you for your offer, but I cannot leave my  flock.",
	"Father, the city will soon be lying in ruins. You won't have any flock to watch over.",
	"If that is God's will, then so be it. I will stay.",
	"As you wish, father.",
};
