string DLG_TEXT_LSC [121] = {
	"Hello. As I understand it, you're the last arriving citizen?",
	"That's so. My name is ",
	"Hello. What do you need in this jail?",
	"Nothing much. Just hopped in.",
	"And do you know who was the head of the jail before you?",
	"Won't you tell me for what Maxim Taylor got put in here?",
	"Listen, isn't there some way to assist in the freeing of that drunken debaucher, Maxim Taylor?",
	"Listen, isn't there some way to assist in the freeing of that drunken debaucher, Maxim Taylor?",
	"Listen, there's been some serious talk. I'm putting a team together.",
	"Well, then receive my congratulations. I'm the head of the city's jail, subordinate directly to the admiral. I'm not against friendly relations with anyone at all, but note that if you end up behind bars, the friendship is over.",
	"Yes, yes, I understand. And a lot of people go by you?",
	"No. Unfortunately, there hasn't been anyone in a while. The clans live their lives, and prefer not to stick out. And the citizens prefer not to lower themselves.",
	"Clear. Well, then. Good luck in your uneasy job of not doing anything.",
	"You're telling me! At times, I'm ready to weep at the moon from boredom...",
	"I understand... Well, all the best.",
	"Greetings. I'm happy that you've survived, and are now among us. I'm the jailer. My name is ",
	"Very pleased. I'm Captain ",
	"If you're here on business, I'll ask you to speak to the head.",
	"Listen, are you aware of who Leyton Dexter is?",
	"Pal, I've brought you a bottle of wine from your pal Dominic Legro. Have a drink! Relax! Since you're sitting here without coming out...",
	"Pal, it's me again. And again about Dominic Legro.",
	"Buddy, it looks like Dominic didn't do anything questionable, with regards to Armo.",
	"Armo",
	"Buddy, do you know that Armo has been killed?",
	"Fine, I understand.",
	"Well, then. We've met, then. If you're here on business, then you must speak with my chief.",
	"Clear.",
	"What team?",
	"We've already discussed that.",
	"That's been discussed. This is the second time I'm repeating it.",
	"Enough. You've worn me out...",
	"Team on ship. I'm leaving the city.",
	"Yeah... Sorry, I let it slip my mind.",
	"You know...",
	"Well, okay...",
	"Have you lost your mind? Don't know the laws of the city?",
	"I'm saving my life, is all. I'm offering you to save yours, as well. The matter is that the city will be destroyed by this storm.",
	"I don't believe you.",
	"A pity, then.",
	"Oh, what a soothsayer. I've got the jitters! I'll recommend that you die, scum.",
	"Well, it's my business to suggest...",
	"You wouldn't believe it! That cretin got wasted at the tavern, and went to the Admiral's residency to whine about his rights.",
	"I've already answered that question.",
	"We've already discussed that.",
	"Listen, stop immediately!",
	"Oh-ho-ho... And what demands was he trying to present?",
	"Yes, yes, I remember.",
	"Fine.",
	"Good, good...",
	"Oh, who knows. Anyway, Maxim is a real regular, but this is the first time he's got tangled up with Capper. And very unfortunately, I'll tell you. Having come here, he got off pretty easy, I'd say...",
	"And what could have happened in the worst case scenario?",
	"Well, history doesn't stand for hypotheticals.",
	"Okay. It's clear, all in all...",
	"I'll ask you to consult the Admiral about this question. He's the one who put him here. Let him make the decision about his fate.",
	"We've already discussed that topic.",
	"One more time, let me repeat, we've already discussed that topic.",
	"Are you an idiot?",
	"And can't I make a deal with you?",
	"Yeah, I forgot...",
	"Forgot again.",
	"This looks a lot like...",
	"You must be nuts! Look, If I were you I'd go see Capper.",
	"Thanks for your advice.",
	"Nope, no idea. And I wouldn't stick my nose into it, if I were you.",
	"Explain?",
	"You figure it out. If I were you, I wouldn't want to know who was the warden here before me.",
	"Leyton Dexter, perhaps?",
	"Might be... Why so nosy? ",
	"Well, it is a big nose I have...",
	"Well, I wouldn't show it off in public. Curiosity killed the cat, you know.",
	"Hum... Yeah, so it would seem.",
	"Ex-chief on the Tartarus.",
	"Where is he now?",
	"Ha, ha... Rrrright behind that door; right row, last cage to the left. But, hush, not a word to anybody!",
	"Never!",
	"A bottle of fine wine from Dominic Legro?!   \nSure, I'll take the wine. Just tell this crook, I'll get even with him anyway!",
	"Sorry? Don't quite follow you.",
	"You don't have to. Just tell him I'll kick his little arse, next I see him...",
	"All right, I'll tell him... Dominic just thought you'd be glad.",
	"Well, I am! That is... oh, never mind. This is no place for idle gossip. Thanks for the wine, and be sure to give my regards to Dominic...",
	"Okay, I will.",
	"What's new?",
	"Well, I told him all you said. He was all surprised and incredulous. Swears he hadn't a clue about anything.",
	"Really?",
	"Well, that's what he said. ",
	"And while he was swearing, he didn't didn't by any chance mention Armo Dulin, the waitress from the tavern?",
	"I really don't know...",
	"Is that so? Hmm... Well, then maybe we should make up.",
	"Dominic wasn't exactly at odds with you.",
	"So, you go ask him.",
	"All right...",
	"How so?",
	"He told me, he was just chatting with Arno. He doesn't even fancy her. ",
	"But I heard...",
	"Well, you know the way people talk. I wouldn't put too much faith in rumor, especially if it's about your friends.",
	"Yeah... I guess you're right.   \nTell Dominic I believe him. Tell him, I'm sorry. I was being a real prick.",
	"Yeah, sounds like it.",
	"Thank you, my friend, for minding our business - both Dominic's and mine.",
	"Glad to be at your disposal.",
	"You're right, I guess... Tell Dominic everything's fine. I'm not angry at him anymore.",
	"Great! Well, I'll be leaving then...",
	"Yes, I'm aware of it.",
	"Do you know who did it?",
	"I'm trying to find out. When I find him, I'll cut his unworthy heart out of his dirty body!",
	"Juan Kobo did it. He's one of the Caspers.",
	"You're certainly clued-in.",
	"He blurted it out to me himself. Don't worry, though, I got rid of him. ",
	"Ah. A shame...",
	"I wouldn't say so.",
	"What do you have in mind?",
	"Don't let's get personal; we need to go after the whole clan. Kobo was just following orders. You know better than I, their boss has ultimate authority. They don't fart unless he says.",
	"That's true...",
	"I'm going to break into the San Gabriel. You can join me.",
	"I'm ready.",
	"Let's go, then. No sense putting it off.",
	"Well... Looks like we did it.",
	"Looks that way! Thanks for the help, friend. Listen, would you be interested in joining me, on my future swashbuckling adventures?",
	"No, thanks. This wasn't any kind of fun for me; it was revenge, pure and simple. Now... I think I'll just go and get wasted. I miss Armo...",
	"What about the prison?",
	"Oh, I don't give a damn about the prison. Or the Admiral, or this Goddamned city! Oh, I see no reason to go on without Armo...",
	"Sorry, pal.",
};
