string DLG_TEXT_LSC [156] = {
	"Ignoring the continuing storm, Captain, accept my congratulations.",
	"Congratulations?",
	"My congratulations, Captain.",
	"Congratulations?",
	"What did you want, sir?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some goods.",
	"You know, I'm assembling a team to get out of here. ",
	"Nothing...",
	"Well of course! You've lived through a crash, and have ended up here instead of kicking the bucket. Isn't that worth congratulating? And the storm will pass by tomorrow evening, and it doesn't threaten you anymore.",
	"Agreed...",
	"Well of course! You've lived through a crash, and have ended up here instead of kicking the bucket. Isn't that worth congratulating?",
	"You see better than I,sir...",
	", sir.",
	"Please to meet you, Roger. My name is Captain ",
	"Likewise, Captain. How can I help you?",
	"Have you been in the city long?",
	"Very long, my dear Captain. I won't say that I've been here the longest, but...",
	"Were you here before Capper?",
	"I... Hm. What difference does that make?",
	"Why can't anyone leave the city?",
	"There are special reasons, Captain. I'd suggest you stay out of that business.",
	"Why?",
	"Because in that case, my congratulations would be worth nothing. You would no longer be... a survivor.",
	"You mean that?",
	"With all due respect, Captain, I've seen quite a few courageous guys in my time, but those that I've met in this city have long gone to the Sea Devil.",
	"Probably, a meeting with him won't do me hard... No matter how it is around here, Capper has friends, doesn't he? A right hand, helpers?",
	"He's got a whole militia of right hands! But I insist, Captain, that you don't put yourself at risk. I've told the same thing to too many who, like you now, I saw courage in... But they're all dead.",
	"Capper isn't immortal, right?",
	"Who knows. Who knows...",
	"Well, then. Thanks for the concern.",
	"Protect yourself, Captain.",
	"Of course.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"I see.",
	"That's too bad...",
	"He is here, on the ship. Search more carefully.",
	"Ha! So he's here, on this ship!",
	"He is on this ship, it's strange you haven't seen him yet.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"So he's here, ",
	". Search more carefully.",
	"So he's here, among us!",
	"Where are you looking? He is hanging out here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"A-ha, I see. Thank you.",
	"Thank you!",
	"She is here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship!",
	"She is on this ship; it's strange you haven't seen her yet.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation.",
	"As far as I know, she now is at ",
	"So she's here, ",
	". Search more carefully.",
	"So she's here, among us!",
	"Where're you looking? She's walking around here someplace.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation with her.",
	"As far as I know, she now is at ",
	"A-ha, I see. Thank you, ",
	"Thank you!",
	"I'm all ears, buddy.",
	"How long can a storm last?",
	"Don't you feel somewhat uneasy here?",
	"Where are all the goods in your stores from? Any contacts with the outer world?",
	"Have you been here long?",
	"No questions. Excuse me...",
	"It depends. The last one lasted for one week and was quite something. To tell the truth, everytime the waves hit the ships of the city, we all have our hearts in our mouths.",
	"Does this happen too?",
	"Course, it does! But since the city is still standing, we haveno reason to worry. Well, at least, that's what I think...",
	"I quite agree.",
	"No way I'd feel at ease here!No, this is place is no worse and no better that any other, but you sure won't find any peace here.",
	"Hmm, I'm not exactly looking for it.",
	"Why would we need any contacts? Ships end up here for good regularly... lower holds bursting with goods and gold meant for the colonies in the New World. We've got plenty of everything.",
	"Interesting.",
	"Yes, quite long.",
	"How long?",
	"For about two years now.",
	"I see. So Hill Brunner was already here, when you got to the island.",
	"Yeah, that's right.",
	"I see, thank you.",
	"What kind of goods?",
	"You have already asked about it. ",
	"Already asked about that...",
	"You already asked me about these goods. I don't know anything!",
	"I need cannon balls, knipples, bombs, powder, weapon, canister, food, and medicaments...",
	"Yes ....Excuse me, it slipped my mind.",
	"Ah, well, yes.",
	"Understood, I understood...",
	"Alright, alright, no need to go on. I know nothing about it.",
	"Nothing at all?",
	"Absolutely nothing. All the best.",
	"Alright, bye...",
	"What crew?",
	"A crew for my ship. What about joining it as a sailor?",
	"Are you kidding?",
	"Nope. I do have a fine corvette, ready to set sail. I'm waiting for your decision.",
	"Damn, of course I agree! I'm sick of this place.",
	"Excellent! Then immediately go to the 'San Gabriel.' Henrik Vedecker will transfer you to my corvette. ",
	"Alright, I'll do so. I'll just quickly gather my things and will be ready to sail.",
	"Hurry up.",
};
