string DLG_TEXT_LSC [154] = {
	"Good day! How are you doing there? A beautiful city, isn't it? And during stormy weather, it's just wonderful!",
	"Without a doubt! I'm the only one who's gotten out of this storm?",
	"Good day! How do you like it here? A beautiful city, isn't it?",
	"Without a doubt. My name is ",
	". I was...",
	"What did you want, mynheer?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some goods here.",
	"You know, I'm assembling a team to get out of here. ",
	"Nothing...",
	"It looks like that. A pity...",
	"That's life... Yes, allow me to introduce myself. My name is ",
	", and I was...",
	"It doesn't matter who you were. I'll recommend the following construction here. I don't use the word city. Well then, a new life has begun for you, and there's no return. By the way, I'm ",
	"And why are you so sure, mynheer ",
	", that there's no return?",
	"Because in my three years of being here, I've seen not once where those that try to return end up. Believe me, it's cold and wet for them there, and they'll be sticking out for an eternity. I mean purgatory...",
	"I got that. Hm. And who helps them reach nirvana? It wouldn't be Capper?",
	"Hee hee hee... Chad Capper - he's our everything, and he's also our nothing at the same time. Be that as it may, you're going to have to follow his orders. So be more careful in your conversations.",
	"Careful? And what if I don't want to be careful?!",
	"Well, then. I'd pray for the peace of your soul, in that case. Without any doubt, the fate of Leyton Dexter awaits you.",
	"Hm, and what happened to this Dexter?",
	"I don't want to talk about that. If you want to know anything about that, better to ask Lea Toors.",
	"Okay... You know, hope is a nice thing, mynheer ",
	". Convincing yourself of the hopelessness of a position, you yourself make your own bed.",
	"Maybe. Anything's possible. But it isn't that bad here. We've got the law, we have our own lives. It's interesting here. I'd even say that I like it here.",
	"But you're a prisoner!",
	"Well, so what? In my view, this situation is really pretty good. By the way, I heartily recommend the same to you.",
	"All right. Luck to you, mynheer ",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"That's too bad...",
	"He is here, on the ship. Search more carefully.",
	"Ha! So he's here, on this ship!",
	"He is on this ship, it's strange you haven't seen him yet.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"So he's here, ",
	". Search more carefully.",
	"So he's here, among us!",
	"Where are you looking? He is hanging out here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"A-ha, I see. Thank you.",
	"Thank you!",
	"She is here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship!",
	"She is on this ship; it's strange you haven't seen her yet.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation.",
	"As far as I know, she now is at ",
	"So she's here, ",
	". Search more carefully.",
	"So she's here, among us!",
	"Where're you looking? She's walking around here someplace.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation with her.",
	"As far as I know, she now is at ",
	"A-ha, I see. Thank you, ",
	"Thank you!",
	"I'm all ears, buddy.",
	"This Law... Can you evade it anyhow?",
	"Is there only one kind of authority in the city? Does the Admiral have...eh, enemies?",
	"Is there anywhere around to spend a nice evening?",
	"Say, have you been here long? Aren't you fed up?",
	"No questions. Excuse me...",
	"One can evade anything, buddy. What's more important is where it might lead you. I'm sure you're speaking about sailing away...",
	"Exactly!",
	"Well, it's possible...",
	"I'm all ears.",
	"...in grave, ha-ha-ha!",
	"You're a funny mynheer, you know...",
	"As many as you like. All that's left from them is either under the boards and at the bottom... We have clans, but they live in peace with the Admiral and the citizens. At least, as long as you don't enter their ships.",
	"And what if you do enter them?",
	"No doubt, they'll kill you.",
	"Understood...",
	"Spend a nice evening? Did you drag your bottom here to have a good time?",
	"Hmm, why not?",
	"You'll do it after you get out of here! Oops, almost forgot: you never will! Ha-ha-ha!",
	"I see.",
	"Sure, I'm fed up. But what can I do?.. Nothing, exactly.",
	"Well yeah... And Hill Brunner, was he at this place when you got here?",
	"Yes, at that time he was already playing the leading tune in his tavern. Feel sorry for him, a good tavern-keeper he was...",
	"That's true...",
	"Very well. What can I do for you?",
	"You already asked about this.",
	"Already asked....",
	"You already asked me about these goods. I don't know anything!",
	"I need bombs, powder, weapon, canister, food, and medicaments...",
	"Yeah... Sorry, I let it slip my mind.",
	"Ah, well, yes.",
	"Understood, I understood...",
	"I see. You should ask the Admiral for powder and weapon. The hostess of any house can give you boms, canister and other munition. And the medicaments, as the priest for them.",
	"Got it. Thanks a lot to you.",
	"Sorry?",
	"I'm offering you to join my corvette crew as a sailor. I'm sailing away pretty soon.",
	"Wow!.. How did you manage pull it off? The Law, you know...",
	"Sorry, I don't have a lot of time. Do you agree?",
	"Of course, I do. It's not being discussed!..",
	"Fine! Head straight for San Gabriel then. Mechanic will help you get to my corvette.",
	"Alright, I'll do it. I just need to pack up some things.",
	"O.K., but don't take long.",
};
