string DLG_TEXT_LSC [142] = {
	"Hello, Señor. Are you the new citizen, who was able to save himself from the last crash?",
	"Yes, that's me. ",
	" at your service, Señora...",
	"Hello, Señor. Are you the new citizen, who was able to save himself from the last crash?",
	"Yes, that's me. ",
	" at your service, Señora...",
	"What do you need, Señor?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"You can't imagine what a greedy and selfish person that Eric Yost is!",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me to the mainland?",
	"Nothing...",
	"You're the only one to survive that storm. You know, you were very lucky in that you crashed on the reefs after the storm had already lost its strength. By the way, my name is ",
	"Let's get acquainted, Señora.",
	"Very pleased! My name is ",
	"Let's get acquainted, Señora.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"Oh, I saw him recently. It was around ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, lately he's ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Please look carefully.",
	"Hmm, so she's now on this ship....",
	"She on this ship. Funny you haven't meet yet.",
	"Oh, I saw her recently. It was around ",
	"You know, I recently met her ",
	". So look for her there.",
	"As far as I know, she's currently ",
	"Excuse me, but she's right here, ",
	". Look closer.",
	"Hmm, she is here, among us!",
	"If you looked around more carefully, you'd surely have seen her ....",
	"Oh, I saw her recently. It was around ",
	"I believe I met her recently in ",
	". So you'll see her there.",
	"As far as I know, she's currently ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"Tell me, does it often storm here?",
	"Listen, what island is this?",
	"Would you mind telling me ",
	", what is worth visiting in the city?",
	"This Admiral, what kind of person is he?",
	"Say, did you get here before Hill Brunner?",
	"I have no questions for you, excuse me.",
	"No, no, really seldom. You know, when it storms, many of our machos are scared shitless, but it's nothing to me. I'm not scared of storms!",
	"Would one think you're such a brave Spanish lady!",
	"I am, Señor, I am!",
	"Well, may your courage never abandon you, Señora.",
	"This is the City of Abandoned Ships. We're all separated from the rest of the world here, it's like a damn cage with no hope of ever getting away...",
	"Is it really so sad? I'm the only survivor, lucky, you know. I guess, I can call you lucky too.",
	"On the one hand, it's true, you're right. But if you knew how sick I am of all this place! Nothing new in here, the same death and wrecks around. It's a vicious circle and we're its captives! What a misfortune!",
	"Well, yeah...",
	"I believe, first, you should pop into the tavern. There's also a church and a store... By the way, if you haven't met the Admiral yet, I think, it's high time you went there!",
	"Alright, I'll do as you say. Thanks.",
	"Chad Capper is a serious man, you wouldn't want to mess with him. They say, he used to be a pirates' Captain! He got here three years ago and immediately took over the place. He's been the Admiral of the city since then.",
	"I see...",
	"Before Hill Brunner? Do I look that old?",
	"No, by no means! Sorry...",
	"Anyway, you came as a surprise...",
	"Why so, Señora?",
	"You broke the Law and don't give a damn about it, as if you do it everyday.",
	"I'm saving my life, have no better choice. If you care to join me, might save your own bacon.",
	"Save it from what?",
	"The upcoming storm, of course. It'll leave the city lying in ruins. It's not just a vaporous conjecture, believe me.",
	"You know, I do believe you. Besides, I'm sick of this place, so I'm in with you, Captain.",
	"Perfect! Now go straight to San Gabriel, make it as quick as you can. Henrick Vedeker will help you get to my ship.",
	"I got it. I'll do everything you said.",
	"I beg you, faster ....",
	"What's going down with you?",
	"You see, he surely wants to rob me!",
	"That's impossible!",
	"Well, not exactly with a knife at my throat. This Eric Yost wants to sell the City map for an unthinkable price! It's a sure rip off!",
	"It's only natural. If you have something to sell, you can charge any price. Eric has the right to do it as well.",
	"Quite a right it is...",
	"Do you really need this map so badly? Lost without it completely?",
	"Yeah, quite...",
	"Fine, I'll help you, for our Lord wants us to show mercy to our fellow creatures    \nPop in to Eric tomorrow, I'll tell him to make it a fair price.",
	"What, will he listen to you?",
	"No doubt.",
	"Many thanks to you.",
};
