string DLG_TEXT_LSC [176] = {
	"You killed them! Thank you!",
	"Hm. And who are these people?",
	"Greetings to my humble abode, Captain. How did you find your way here, through the storm?",
	"Greetings, Captain. How did you find your way through the storm?",
	"Not without problems, but thanks for the concern. My name is ",
	"Greetings at my humble abode, Captain. No problems finding your way? ",
	"Greetings Captain. Did you find your way okay?",
	"I had my share of problems, but never mind. Thanks for the concern. My name is ",
	"What do you need, again?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"You know, I'm putting together a team to get out of here. How's about you sail with me to the mainland?",
	"Nothing...",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	", Captain. Glad to meet you.",
	"What are you doing in this weather?",
	"With all due respect, Captain, that's none of your business.",
	"I understand. We've all got something to hide, isn't that so?",
	"I'll ask you to leave my house!",
	"But does the law allow you to do that?",
	"If the visitor is a swinish goblin, then certainly!",
	"Oh, thank you for the compliment...",
	", Captain. Happy to meet you.",
	"What are you doing in this weather?",
	"With all due respect, Captain, that's none of your business.",
	"I understand. We've all got something to hide. Isn't that right?",
	"I'll ask you to leave my house!",
	"Don't lose your temper. I'm just getting settled in.",
	"Get settled somewhere else. ",
	"Hm. I'm not disturbing you.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"Forgive me, but he's right here, ",
	". You need to pay more attention.",
	"Hmm. But he's here, among us!",
	"If you'd have looked closer, you would have seen him already...",
	"Oh, I saw him recently. It was around ",
	"I believe I met him recently in ",
	". So you might want to try there.",
	"As far as I know, lately he's ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"She's here, on this ship. Please look carefully.",
	"Hmm, so she's now on this ship....",
	"She on this ship. Funny you haven't meet yet.",
	"Oh, I saw her recently. It was around ",
	"You know, I recently met her ",
	". So look for her there.",
	"As far as I know, she's currently ",
	"Excuse me, but she's right here, ",
	". Look closer.",
	"Hmm, she is here, among us!",
	"If you looked around more carefully, you'd surely have seen her ....",
	"Oh, I saw her recently. It was around ",
	"I believe I met her recently in ",
	". So you'll see her there.",
	"As far as I know, she's currently ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Many thanks to you.",
	"I'm all ears.",
	"What can you get down to here, but walk back and forth all sorry for yourself?",
	"How's the life going on here? Do people work?",
	"I have no questions for you, excuse me.",
	"You're an arrogant fool! You'd better forget all about your glory and power at sea and on land. It's all gone now! You're nobody here, as we all are, you should start a new life and gain the sympathies of the people of the city. Golly, what must you be thinking about?...",
	"I didn't mean to offend you, ma'am. Just give me a hint, what can I busy myself with here? Anything exciting to take up a spare evening?",
	"Exciting, you say? You must be a dare devil, I take it. A lucky fellow, aren't you? Well, try paying a visit to the Narvals...",
	"It's the Narval clan you must be talking about, isn't it?",
	"Sure it is, my dear. You'll get lots of excitement, take my word for it.",
	"Hah, you're an optimistic lady, I see...",
	"Hah, wish it made any sense here... or were an aim The thing is you can't set any aims here. You can't live a real life after you get away from here, you'll just drag on a miserable existence, as we all do...",
	"Sounds encouraging...",
	"Good Lord, help me!! Don't let them kill me!!",
	"What's the matter?..",
	"Later... Protect me, I beg you!",
	"Hmm, I can't see anyone to protect you from.",
	"It's the Caspers...",
	"Have they took over this ship too?",
	"Gosh, no! They just came to finish me off.",
	"That simple, you think? They've broken the Law of the city, giving any citizen the right to live!",
	"My dear boy, I'll tell you this... I'm probably the oldest citizen in this city, and what I've seen during my lifetime you wouldn't believe...",
	"Did you live here before Brunner ended up in the city?",
	"I've been stuck here for ten years now. When I found myself on teh island, there were five people onlym and no Hill Brunner among those.",
	"Good Lord... You know, right before he died, Hill Brunner was looking for anybody who arrived at the island earlier than he did.",
	"Do you happen to know what for?",
	"It appears, he wanted to ask about Mechanic.",
	"Hum, sakes... You know, sisce he was locked up somewhere, you're the second person I'm talking about him to. Tizer Dan was the first.",
	"Tizer Dan?! Damn it, do you know what happened to him?",
	"They say he's drowned.",
	"Rubbish! He got to the Big Land!",
	"So, he's alive then?!",
	"Er, not really,no... The agents of the Dutch East Indies Company killed him in Willemstad.",
	"Ah, what a pity! His dream came true, he sailed away from this goddamned place, and still couldn't keep his skin safe. Ironic...",
	"Yeah, it's a pity... Look, who's this Mechanic you're talking about?",
	"Oh, he's quite a legend! His name's Henrick Vedeker. Most people in the city have no clue he's among us. Since the Caspers took over San Gabriel, I haven't met him myself.",
	"You said he was locked up, kinda isolated...",
	"No other name for it, I guess. I think the Admiral keeps him secret on purpose. You see, Mechanic is a person of manifold gifts. No one can compete with him in handcrafts. He used to tell us about some imminent danger. Said we had to leave the city, while it wasn't too late",
	"You know, nobody takes such weirdos seriosly, so we just laughed at his tales. And then the law banning ship construction was issued, and the Caspers occupied San Gabriel barque right after that. So no one spoke about our weirdo anymore, they all felt quite uneasy, besides it wasn't really safe.",
	"What do you mean 'not really safe'?",
	"People, who knew Henrick personally, started disappearing. I would be among them too now, but for you...",
	"You mean it was an assault?",
	"Exactly. It's not a big deal to hush up a murder nowadays. The thing is some eerie creatures live in the depths beneath. If you throw a body into the water, you won't ever see it come up to the surface.",
	"Good Lord... And why was Mechanic locked up? Maybe he's already dead, killed, you know?",
	"No, don't think so. He's alive, he's too indispensable. It was him who invented the way to fix the ships together. When I came here, there were only four ships and they were really unsteady. Henrick found the way to keep them together tight.",
	"Ah, that explains it...",
	"Chad isolated him only because he started to panic. He babbled on we all had to leave the place, while there was still a chance...",
	"I see. I suppose I have to get to your Henrick the genious and have a word with him.",
	"Well, give it a try. Good luck!",
	"Thank you.",
	"An interesting offer...",
	"We've already gone over this.",
	"We have discussed this already, there is no need to repeat it...",
	"Cut it, I've had enough of you...",
	"Yeah, and besides it's right in time. The city if facing a great storm. ",
	"Yes ....Excuse me, it slipped my mind.",
	"As you wish...",
	"Well, okay...",
	"Really? Who told you about it?",
	"Who would it be but your good acquaintance Henrick Vedeker.",
	"Hum... Guess I'll run the risk and stay here. I'm too old for a long journey.",
	"Is it your last word? I didn't save you from the Caspers to let you risk your life like this now.",
	"You should admit, Captain, I have my right.",
	"Certainly.",
	"It's my final decision then.",
	"Well, it's a pity, but...",
};
