string DLG_TEXT_LSC [150] = {
	"Oh, a new captain! It seems like you've arrived last after that storm.",
	"Good day. My name is ",
	". Before this cursed storm, I was indeed a captain...",
	"Oh, new captain! I think you were the one that arrived last.",
	"Good day. My name is ",
	". Before the crash I was indeed a captain...",
	"Did you want something from me?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some goods.",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me to the mainland?",
	"Nothing...",
	"Hm, I think I'm familiar with that name, you know. Captain... Oh who cares. I'm Stefan Klein, a local... resident.",
	"Have you been here long, Tom?",
	"Five years now, God give me memory. I got used to it, got used to everything. Now I live, and don't even complain. Meet the newbies.",
	"And how did you get here?",
	"That's a long story, Captain...",
	"Tell me. I'm interested.",
	"Alas, I don't have time for long stories.",
	"Well, fine. One clear April morning, a galleon called the Leader stepped out of Belize with a big cargo of wood, sailcloth, and mahogany, but by midday there formed a storm so horrible that even our fearless captain - may good keep his soul - gave up trying to control the ship.",
	"The Leader went off course, pushed on by the wind, and snagged a reef not far from here at such a speed that the rock, lightly piercing the hull, passed through the entire length of the ship, not leaving us a chance for salvation. If I weren't an experienced sailor, I was scared most of all - and I really didn't want to die like that, among the sea... And I jumped overboard before the galleon went into the void. ",
	"I swam, swam, swam, until the blood in my veins boiled and turned into acid... Then I swam a bit more, but I, of course, didn't know where I was heading. the waves took me. ",
	"Seeing this place in the distance, I thought this was a mirage, but then I lost my strength and... After that, I woke up here.",
	"Was it easy to get settled in?",
	"It was tough at first, of course. I thought a lot about those that died that day... That's hard, isn't it, to be the only survivor? But time heals...",
	"Well, then. Thanks for the talk, Stefan. I'm happy to make your acquaintance",
	"I'm very happy as well, Captain ",
	"All the best.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"That's too bad...",
	"He's here on this ship. Look closer, please.",
	"Ha! So he's here, on this ship!",
	"He's on this ship. Strange that you haven't met him yet.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"So he's here, ",
	". Look closer.",
	"So he's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks!",
	"She's here, on this ship. Look closer.",
	"Ha! So she's here, on this ship!",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation.",
	"As far as I know, she now is at ",
	"So she's here, ",
	". Look closer.",
	"So she's here, among us!",
	"Where're you looking? She's walking around here someplace.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation with her.",
	"As far as I know, she now is at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks!",
	"I'm listening to you closely, buddy.",
	"Does it often storm here?",
	"Look, what's this place?",
	"So what do you do here?",
	"Hey, buddy, have you been on this island long?",
	"No questions. Sorry, buddy...",
	"This is the City of Abandoned Ships. Now you're stuck here for good. Welcome!",
	"Ay caramba!",
	"What do you think people usually do in restricted space, Captain? We just exist.",
	"Sounds like quite a life. Should try it too, I guess.",
	"From time to time, it's hard to say how often. Some think it is, others think it's not...",
	"What do you mean?",
	"If you aren't keen on storms, you would think they come too often. Though if you don't care...well, you know...",
	"Yeah, I do.",
	"Well, er, quite long. Two years, I'd say...",
	"Wow, that's long! And as for now deceased Hill Brunner, was he in the city at the time when you arrived?",
	"He sure was.",
	"I see...",
	"What goods?",
	"You already asked about this.",
	"Already asked....",
	"You already asked me about these goods. I don't know anything!",
	"I need cannon balls, knipples, food, and medicaments...",
	"Yeah... Sorry, I let it slip my mind.",
	"Ah, well, yes.",
	"Understood, I understood...",
	"Er, I guess, you can buy food in the store. As for medicaments, you can ask the priest for them.",
	"Our priest, you mean?",
	"Sure, you'll find no other priests here. It's not our souls only he heals...",
	"Thanks, mate.",
	"Hmm, I'm in lost for words...",
	"Well, is it positive or negative?",
	"You know, I took quite a fancy to this city, it'll be a pity to leave it...",
	"If you don't leave with me, you're sure to die. The upcoming storm's gonna ruin the city.",
	"You sure?",
	"Yeah. That's what Mechanic told me.",
	"I'll be damned if I don't believe him... Well, er, I guess, I'm with you then.",
	"You made the right decision, my congratulations. Now hurry to San Gabriel. Mechanic will help you get to my corvette.",
	"Alright, I'll just grab some of my things.",
	"Make it quick. Don't get stuck anywhere else!",
};
