string DLG_TEXT_LSC [150] = {
	"Greetings to the new citizen of the city! We're very happy to see you. Sorry, I forgot to introduce myself. My name is ",
	". I live here.",
	"I got that. But I'm ",
	". Listen, do you live in constant storms here?",
	"Greetings to the new citizen of the city! We're very happy to see you. Sorry, I forgot to introduce myself. My name is ",
	". I live here.",
	"I got that. But I'm ",
	"What did you want?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some goods.",
	"You know, I'm assembling a team to get out of here. How'd you like to come with me to the mainland?",
	"Nothing...",
	"Oh, you know, by evening tomorrow everything will get bottled up. By the way, if you haven't been at the admiral's yet, then I'll ask you to hurry. He's located on the warship San Augustin. You need to get to him before the storm ends.",
	"Okay, got it.",
	"If you haven't been at the admiral's yet,I'll ask you to hurry. He's located on the warship San Augustin.",
	"Okay, got it.",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"He's here, ",
	". Look closer.",
	"He's here, among us!",
	"Where have you been looking? He's hanging around right here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks!",
	"She's here, on this ship. Look closer.",
	"Ha! So she's here, on this ship!",
	"She's on this ship. Strange that you haven't seen her yet.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation.",
	"As far as I know, she now is at ",
	"So she's here, ",
	". Look closer.",
	"So she's here, among us!",
	"Where're you looking? She's walking around here someplace.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation with her.",
	"As far as I know, she now is at ",
	"Uh-huh. Got it. Thanks, buddy.",
	"Thanks!",
	"I'm listening to you closely, buddy.",
	"Listen, what's this island?",
	"Look, pal, any idea why there're so many ships in this place? It's extraordinarily, you know! Why are they still afloat?",
	"This Admiral, what kind of person is he?",
	"Anything exciting around here?",
	"How long've you been here?",
	"No questions. Sorry, buddy...",
	"This is the City of Abandoned Ships, pal. If you've ended up here, forget everything about what you lived for. You can't bust out of here, unfortunately...",
	"Devil!",
	"Well, no one knows for sure. People say there's some current, a really strong one, that drifts all ships here. Some algae as well...",
	"Algae? Hum, maybe there's some shallow water beneath, some reefs, hey?",
	"No idea, would't advise you to go investigate about it. You can swim on the surface safely, but the ones who tried diving, well, haven't seen them since then.",
	"And the dead bodies, they should've come to the surface, shouldn't they?",
	"No, not a glimpse of them after they drowned.",
	"Damn, it's eerie..",
	"Not a big deal, you'll get used to it.",
	"Er, not really in the mood to get used to this stuff, you know...",
	"I know, but you'll have to. You can't settle down here - you'll go nuts. And then you'll be history, that's the Law!",
	"Say what?!",
	"You'll go feed the fish with a load of trash around your neck. That's it!",
	"Golly, these laws you have are something...",
	"The Admiral's the governor of the city. To tell you the truth, we used to elect the admiral, but Chad Capper deosn't seem to like this idea anymore...",
	"What makes you think so?",
	"It's because the admiral elections are a taboo topic in the city. We don't raise it... You'd better keep your mouth shut about it too.",
	"Hm. I see.",
	"Exciting, you say? Well, don't know what's exciting for you... We have a tavern, a store, a church, and, well, a residence, of course.",
	"I see.",
	"It'll be a year and a half already...",
	"I see. As for Hill Brunner, did he run the tavern at that time?",
	"Yeah, he did.",
	"Hm, I see then...",
	"What's this you're looking for?",
	"You already asked about this.",
	"Already asked....",
	"You already asked me about these goods. I don't know anything!",
	"I need cannon balls, canister, knipples, powder, weapon, food, and medicaments...",
	"Yeah... Sorry, I let it slip my mind.",
	"Ah, well, yes.",
	"Understood, I understood...",
	"Weapon? But you do have your weapon.",
	"I need a lot of weapon.",
	"Got you. You should go to the Admiral, then. He's the only one who has powder and weapon.",
	"I see...",
	"Are you kidding, buddy?",
	"Not in the slightest. I have a ship and I offer you to join my crew.",
	"Damn it! Pinch me... I must be dreaming...",
	"I've no time, buddy. I need you answer now.",
	"Thanks for your invitation! Of course, I agree.",
	"Great! Now go straight to San Gabriel. Mechanic will help you get to my corvette.",
	"I'm on my way. I'll just pick up some things.",
	"Make it quick. Don't get stuck anywhere else!",
};
