string DLG_TEXT_LSC [99] = {
	"Status: ",
	"Damned storm! Though it's calming down... As I understand it, you're a new citizen of the city.",
	"Captain ",
	", in the flesh. The storm's not a tragedy!",
	"And now you've come my way. As I understand, you're a new citizen of the city.",
	"Captain ",
	", in the flesh.",
	"Do you want to sell or buy something?",
	"Show me what you got there.",
	"Buddy, I hear here that you have a map of the city. You know, at the moment, it would come in really handy. Since I'm running around here like a blind kitten, haven't gotten settled in...",
	"Buddy, have you lost it? That kind of money for a ragged bunch of paper, proudly calling itself a map of the city?",
	"Listen, buddy, ",
	" asked me to talk to you again about the map of the city.",
	"Thank you. Not interested.",
	"Listen, I want to buy something special from you.",
	"I'm about buying those items that you promised me.",
	"Listen, there's been some serious talk. I'm putting a team together.",
	"And how do you know what's a tragedy or not? Anyway, it looks like you're in a mood today. My name is ",
	". I'm the owner of this store. Let's get acquainted.",
	"Let's.",
	"Excellent! And my name is ",
	". I'm the owner of this store. Let's get acquainted.",
	"Let's.",
	"Why the hell are you going into my chest! Don't know the Law of the city? Well, it's okay. You'll know now...",
	"Hey, citizen, where are you going? The law forbids you to do that! I'm going to punish you...",
	"Hey, what are you sticking your neck into? We've got a thief in the city! Well, hold on now...",
	"Damn!",
	"?Caramba!",
	"Ah, damn...",
	"Oh, so that's how it's going to be?! Thought you'd raid some chests, eh?!Now the citizens and the militia will rip you apart like an old newspaper!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Always at your service, pal. Order!",
	"Listen, I haven't seen such products in your inventory before. These bombs, knipfel, rations, sailcloth... This wood, this medicine...",
	"Well, among the stuff that you mentioned, only rations and sailcloth, wood and medicine are valued here. Nobody needs the rest.",
	"And do you have anything else?",
	"I can provide you with food, but it's not cheap.",
	"I need two hundred hundredweights. How much will it be?",
	"Thirty-five thousand coins.",
	"You must be kidding! Can I get a break here?",
	"Sorry, bud. No discounts. I can give you sailcloth and planks in tow; that'll be five thousand extra. So if you're interested, you're looking at about forty thousand.",
	"I'm ready to pay.",
	"I don't have that kind of money.",
	"Well, I'll see you when you do.",
	"Um. Sure, okay.",
	"Perfect, my good man! Where shall I deliver all this?",
	"Listen, send it to the San Gabriel. As you should know, the Caspers are cleared out of there...",
	"Yea, I know. I'll do as you say.",
	"Thanks a lot, pal.",
	"Got the money?",
	"Yes, I'm ready to pay.",
	"No, not yet...",
	"What is your command?",
	"We've already gone over this.",
	"We've discussed this already. Do we really need to repeat ourselves?",
	"Look, I'm getting tired of this...",
	"To my ship. I'm leaving the city.",
	"Yeah... Sorry. Head like swiss, you know. ",
	"As you will...",
	"Well, okay...",
	"Ha! Ambition and bravado, to boot... You do know you're breaking the law of the city?",
	"I know. But it's my life either way. You see, there's a big storm coming. The city's gonna be destroyed.",
	"Well, I say! Who needs a fortune teller, with you around?",
	"You don't believe me, do you.",
	"No, I don't. And I'm not really interested in discussing it. ",
	"Hm... As you wish.",
	"Yeah, I get you. They're always like this at first...",
	"So, do you have the map?",
	"I do. You came to the right place.",
	"You know, I really need it.",
	"Well, then buy it from me! I have all manner of goods for sale.",
	"Oh. Right.",
	"No, you didn't. It's not for the paper, but for what is painted on it. \nAnyway, if you don't like it, don't buy it. Any problems with that?",
	"Look, can't you see I need this map? I can't pay that much!",
	"I don't bargain, dearie. Want to run around the city like headless cock, that's your prerogative. When you're done with that, I'll still be waiting to sell.   \nThat's my final word.",
	"But I really need this map! Please, couldn't you cut me a break?",
	"Buddy, if its charity you're after, swing by the church. This is a place of business. So don't waste my time.",
	"Good grief...",
	"All right, I'll make an exception. Just this once, and just for you...",
	"Thanks a lot, friend! So what's the price then?",
	"No idea. ",
	" hasn't told me a thing yet.",
	"Maybe she hasn't managed to yet. I'll pop in later and we'll have a word.",
	"Let's follow the standard mercantile procedure here. I'm not much for improvisation. ",
	"Fine. Whatever.",
};
