string DLG_TEXT_LSC [143] = {
	"Hello, esteemed new citizen of the city. Ignoring the storm, I don't think we should delay in introducing ourselves. Now then, I'm called ",
	"Very pleased. My name is ",
	". Devilish storm!",
	"Hello, esteemed new citizen of the city. We haven't had the pleasure of socializing with you yet. Now then, my name is ",
	"Very pleased. My name is ",
	"Did you need something, Señor?",
	"Listen, I'm looking for someone. You wouldn't be able to help me? ",
	"I want to ask you a question.",
	"Can you tell me something interesting, Señora?",
	"What's new in town?",
	"Tell me, is there any interesting gossip lately? ",
	"Listen, I'm looking for some goods.",
	"You know, I'm assembling a team to get out of here. ",
	"Nothing...",
	"Oh, now. You don't know where it hasn't been! You were actually very lucky. You crashed at the tail end of the storm, when the strength was already winding down. A bit earlier, and you wouldn't been able to get to us...",
	"A pity about the people, the ship... A misery, all in all.",
	"Very happy to meet you. How do you like our city, at first glance?",
	"I haven't had the chance to get settled in yet.",
	"Oh, that's no big deal. Everything will come around for you. We all went through this phase. So I wish you luck. Don't start pitying yourself, now!",
	"Not in the least!",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers, like d'Artagnan? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he's currently ",
	"So he's here, ",
	". Search more carefully.",
	"So he's here, among us!",
	"Where are you looking? He is hanging out here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"A-ha, I see. Thank you.",
	"Thank you!",
	"She is here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship!",
	"She is on this ship; it's strange you haven't seen her yet.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation.",
	"As far as I know, she now is at ",
	"So she's here, ",
	". Search more carefully.",
	"So she's here, among us!",
	"Where're you looking? She's walking around here someplace.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation with her.",
	"As far as I know, she now is at ",
	"A-ha, I see. Thank you, ",
	"Thank you!",
	"I'm all ears, buddy.",
	"Tell me, do people end up in the city only after storms?",
	"Listen, what is this island?",
	"What do you think of the Admiral of the city?",
	"Look, Have you been here long? I mean, when exactly did you find yourself on the island?",
	"No questions. Sorry ...",
	"Yes, only this way. When the weather is fine, it's impossible to reach our place. I guess, it's because of the algae. You see, the raging storming sea spread this algae-obstacle somehow for a while.",
	"How very interesting!",
	"Yeah, it is interesting, indeed. To be fair, I should admit that my theory isn't unquestionable truth. Though many citizens would accept it.",
	"I think I might accept it too.",
	"This is the City of Abandoned Ships, Señor. We all ended up here not of our own free will, but, you see, it's not the worst place on land... And at sea.",
	"Ha! You must be saying you like it here!",
	"I'm an optimist, you know. I tend to live here and now, not looking for anything better. The grief of loosing my friends in the ship wreck haunted me, of course. But the show must go on, you know. Life doesn't end here and it seems to me one should live it working and hoping for the best, not whining in grief.",
	"You know, I respect the way you think.",
	"Thank you for your words... So my advice to you in not to give up.",
	"I'll follow it with great pleasure. Thank you a lot.",
	"The Admiral is quite an interesting personality. He used to be the pirate Captain, you know!",
	"Yes, I'm aware of this fact.",
	"Then you must understand he's a real leader with a strong character. If I were you, I wouldn't stand in his way. It's just a small piece of advice for you, for the future...",
	"Yes, I understand. And what was it about the admiral elections?",
	"That's waht my advice was about, you no...",
	"Hum, I see.",
	"About a year ago.",
	"I see...",
	"What goods?",
	"You have already asked about it. ",
	"Already asked about that...",
	"You already asked me about these goods. I don't know anything!",
	"I need bombs, powder, guns, canister, food, and medicaments...",
	"Yes ....Excuse me, it slipped my mind.",
	"Ah, well, yes.",
	"Understood, I understood...",
	"Don't know, don't know...",
	"You don't know what?",
	"I don't know where to get it from.",
	"Ah, I see.",
	"A crew? Do you mean a crew for your ship?",
	"Exactly right.",
	"Do you really have a ship afloat?",
	"Yes, I have a corvette ready to sail away.",
	"I would like to sail away with you. What should I do?",
	"Go straight to San Gabriel, now. Henrick Vedeker will help you get to the ship..",
	"I'll just pack the things and I'm there, on San Gabriel.",
	"Fine, but don't get stuck anywhere else.",
};
