string DLG_TEXT_LSC [70] = {
	"Oh, so you're from the last replenishment of citizens? Well, then. Welcome.",
	"Thank you. My name is ",
	"Hello. Did you want something?",
	"I need money.",
	"No, just hopped in to see you.",
	"Listen, there's been some serious talk. I'm putting a team together.",
	"Very pleased. I'm Augusto Brahms. Let's get acquainted.",
	"Fine.",
	"If you need money, come to me. I can bail you out.",
	"Excellent. I'll remember that...",
	"You don't know who you've messed with, buddy! You're finished...",
	"Aw, hell.",
	"Oh, so that's how it's going to be?! Thought you'd raid the chests, did you?! Now the citizens and the militia will rip you apart like a newspaper!",
	"Oh, you dumb broad...",
	"Hm. Funny. Put down the weapon.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"I know.",
	"We've already discussed that.",
	"That's been discussed. This is the second time I'm repeating it.",
	"Enough, you've worn me out...",
	"You know? From where?",
	"Yes... Sorry, slipped my mind.",
	"You know...",
	"Well, okay...",
	"I know a lot... Do you want me to join you?",
	"Yes. Would you like to join my crew?",
	"No. I'm staying here 'til the end.",
	"Which isn't so far away, incidentally. The city is facing a terrible storm.",
	"I know, but I'm staying anyway. I'm safe here.",
	"What a strange man you are. As you wish, though.",
	"You're almost in the red. Your line of credit is closed.",
	"I see.",
	"I'm ready to consider your request.",
	"Excellent!",
	"Okay. Do you know my conditions for loans?",
	"Not yet, but I hope you'll enlighten me on this matter.",
	"Certainly. So, my limit is one million piasters. You can borrow any sum less that this.",
	"Got it. And what's the annual interest rate?",
	"No interest as such. You just have to pay me back five times the sum you borrow, the moment I or my authorized representative demand it.",
	"What?",
	"Problems with your ears?",
	"No, I, er... I was just, you know, caught by surprise...",
	"I have no other conditions, and give no preference to anybody. It's a very fair deal.",
	"Hmm, I see...",
	"So what sum do you wish to borrow?",
	"I, er... I'd rather not. At the moment. I'll... maybe be back.",
	"That's more than I am willing to loan. I can only give you ",
	"; not a bit more.",
	"I see...",
	"You think you're funny, don't you? Don't play games with me, friend.",
	"Hum. Yes, all right. ",
	"Fine. I'm only glad to give you the money you're asking for.",
	"Wonderful! You really helped me out, friend.",
	"I'm very glad! I hope you remember the conditions of our deal when I call on you. Don't forget, you'll have to return five times more than your current sum. That will be ",
	"Yes, how could I forget? Listen, what happens if I can't give you the whole sum, all at once?",
	"Well, you'd better find a way, friend. The alternative is very unpleasant, for both of us.",
	"I see. Well,  I'll do my best.",
	"As you wish. You still have time to think it over more carefully, in case you change your mind.",
	"Yes, of course ...",
};
