string DLG_TEXT_LSC [195] = {
	"I don't wish to talk to you! You attacked the citizens!",
	"You know...",
	"Ah, monsieur Captain. You know about our misfortune already?",
	"What misfortune? What's happened?",
	"Ah, monsieur Captain. What a nightmare! What horror!",
	"Yes, Armo, I'm up on It. A pity, Hill. A great pity...",
	"Yes, yes, I know you! That storm doomed your ship. Well, then. That's your fate. And now it's joined with ours! We're all imprisoned on this island...",
	"Yes, I noticed already...",
	"Yes, yes, I know you! Your ship sank last. Well, then. That's your fate, and now it's joined with ours! We're all imprisoned on this island...",
	"Yes, I noticed already...",
	"What did you want, monsieur Captain?",
	"I want to ask you a few questions. ",
	"Oh. Nothing, really...",
	"Listen, Armo. I've got a few thought about Hill's death.",
	"Armo, do you have any news about the first date?",
	"Armo, I want to report that my first date was a success...",
	"Armo, is there any news about a second date?",
	"Armo, a second is ready.",
	"Armo, is there any news about a third date?",
	"Armo, excuse me, but I was late to the date.",
	"Armo, this happened here...",
	"Listen, Armo, I've got some financial problems...",
	"Listen, ",
	", do you remember the night Maxim Taylor was drinking here?",
	"Listen, do you know where I can find some equipment?",
	"Listen, there's been some serious talk. I'm putting a team together.",
	"Well, then. let's introduce ourselves. My name is ",
	". And you are?",
	"My name is ",
	". I'm a captain... Or, well. Former captain.",
	"So you're the captain of that ship that sank?! I can imagine how your conscience must be troubling you, about the death of your men. Oh, a real pity. Forgive me...",
	"No problem. Really...",
	"I will call you Monsieur Captain! Are you not against it?",
	"Not against it, ",
	". Call me whatever you like...",
	"Ask, Captain.",
	"It's kind off uncomfortable, don't you think? And it's storming around here...",
	"And how did you get here?",
	"Don't you want to get out of here?",
	"Listen, what kind of clans are thriving here? I mean, I know of the Narwhals and the Caspers...",
	"Listen, I can't get used to the city. Is there a map, or something?",
	"Listen, ",
	", do you know anything about Leyton Dexter?",
	"I heard that you're going out with Thomas Boyle.",
	"You know, I forget what I was going to ask. Sorry to distract you...",
	"Yeah, it sure is stormin'. You're a sailor. You're used to it.",
	"That's true. Still... it's kind of gloomy here.",
	"Don't lose hope. That happens to everyone when they first come here. Everything will come around. Just don't do anything stupid.",
	"Stupid?",
	"Don't argue with the Admiral. Follow the law. Then everything will be fine.",
	"Understood. Thanks for the support.",
	"The same as everyone here. Our ship sank, and I could swim out. Actually, few people get out of ships that are going to the bottom. There's a strange current there... I don't know much about it, but the fact remains.",
	"Gotcha...",
	"Heh. Everyone wants to get out of here. But it's impossible.",
	"Are you sure?",
	"Yes, unfortunately. The ships just come in. No one gets out. And building new ships is forbidden by the law.",
	"Understood.",
	"Hm... I'll tell you a simple thing, and I hope you'll remember it well. Don't mess with them!",
	"And what's the matter?",
	"The deal is, you'll just be killed. This has happened to newbies many times over, so don't repeat the mistakes of your predecessors. It'll be very unpleasant to see your corpse floating overboard.",
	"Thanks. I'll keep that image in mind.",
	"A map? Eric Yost has a map! He's the guy who owns the store.",
	"Where's this store?",
	"On the Esmeralda, Monsieur Captain.",
	"Got it. Thanks a bundle. ",
	"Monsieur Captain, I don't know a thing about Leyton Dexter. And I don't want to.",
	"Well, hum. Sorry then...",
	"Yes, it's true. Why are you asking, Captain?",
	"Just asking... I'm glad for you!",
	"Hill Brunner is dead!",
	"What? You're kidding me!",
	"Not at all. It's true! Good Lord, I shall have nightmares for months...",
	"Armo, tell me what happened.",
	"Ah, good gracious... I've been working for him for such a long time! He's a good man! He... was...",
	"Yes, that's true... Armo, tell me how it happened...",
	"Oh, it was terrible! Just thinking... I can't help but shudder...",
	"Armo, please. Be a good girl, and pull yourself together. Tell me everything.",
	"Okay, hold on... All right. Well.... Hill went off to the cellar around midnight. I waited two hours for him, and when he didn't come back, I went there to kick his ass. We still had a bunch of clients to serve, see? And then... I found him...",
	"Are you sure he was dead?",
	"Pretty sure, yes... His skull was split wide open. Oh Lord, the image won't leave my mind...",
	"Listen, did you see anybody around the place? Leaving the cellar, for instance...",
	"No, nobody.",
	"Damn it! Oh, this is frustrating... Look, he maybe told you something before he died? Something unusual? Think, was there any kind of peculiar detail? Something that maybe... didn't make sense at the moment, and you put it out of your mind? Anything?",
	"Hmm... I don't know if it'll be of any use to you, but he asked me if  I knew somebody in the city who came here before him.",
	"What did you say?",
	"I said I didn't. And then he asked me if I heard any of our clients mention some mechanic...",
	"What did you say?",
	"I said I didn't.",
	"Is that really true?",
	"Sure it is! Would I lie to my boss?!",
	"Yes, you got me there... Well, er. Thanks a lot, Armo.",
	"What for?",
	"Why, for being such a sweetie pie.",
	"Hum... You know, Monsieur Captain, I'm not really in the mood to joke around.",
	"It's no joke... Steady on, Armo. No need to cry. People die, you know. It's all a part of life. Heck, death is what we all aspire toward.",
	"It is, if we die peacefully in bed! Monsieur Captain, you must promise me that if you learn something new about this... er... business, you will let me know.",
	"I promise, Armo.",
	"Thank you. I would really like to know who did it. This bastard doesn't have the right to live!",
	"Yes, yes, I quite agree...",
	"Go on, Monsieur Captain.",
	"It seems to me that the Casper clan has something to do with it.",
	"Are you sure?",
	"Absolutely. I've been to the Admiral, asked him all kinds of questions about Hill's murder. I wanted to help, but he told me straight out to keep my nose out of it.",
	"And how does that implicate the Caspers?",
	"Well, turns out they're tight with Admiral. Really tight... So it would appear that the Admiral is covering them up.",
	"I see... I want payback for Hill.",
	"I'm going to fight the Casper clan.",
	"You gonna do that alone?",
	"Well, yeah. The Admiral isn't going to help me, you know.",
	"They'll kill you, Monsieur Captain.",
	"Well... We'll see.",
	"Look, I know how I can help you. The thing is, I bring food to these bastards - at the San Gabriel, you know. I've got lots of admirers there. What I can do is, ask them each for a date. Then you can deal with them one at a time. ",
	"Good grief! Now there's... an original idea.",
	"Where would you like to meet them?",
	"Hmm. Dunno. Fact is, I don't really care where I meet with a man...",
	"Hee hee... That just came out wrong, didn't it? Let's meet here tomorrow, and I'll tell you the time of the date.",
	"All right, Armo. Thank you.",
	"Tonight, at midnight, a certain Denis Hopfer will be awaiting my sympathies on the quarterdeck of the Ceres Smithy. Be careful, Monsieur Captain. If you hit Hopfer too close to San Gabriel, other bandits might the fight. And then you'll be in real trouble.",
	"I got your message, Armo.",
	"Not now; don't wait.",
	"Point taken.",
	"I beg you not to be late for our date. It would be so unkind of you...",
	"Hee hee! Right you are. I'll be there at midnight sharp!",
	"Wonderful, Monsieur Captain. Well, shall we continue?",
	"Of course, Armo!",
	"Come back here tomorrow, then. I might lure somebody else in here.",
	"I got you.",
	"I got it! One more Casper, Serge Shambon, will come. Same place, same time. And what a fop he is! He's been making passes at me for a long time now.",
	"Hah! He won't bother you for long, I promise.",
	"Not yet, Monsieur Captain. Be patient.",
	"I see.",
	"All right, that's fine. So, Monsieur Captain. Quarterdeck of the Ceres Smithy. Don't be late. No sense in disappointing Serge.",
	"Not in the least, Armo.",
	"Very well, then, Monsieur Captain. Shall we try this again?",
	"If possible, Armo.",
	"It is. Come here tomorrow. I'll try to lure out somebody else.",
	"All right, Armo. Thank you.",
	"Yes, of course. The same place, the same time. You know the drill. Phelipe Armas will come to meet me. And what a right bastard he is!",
	"Well, let's deal with him...",
	"Not yet, Monsieur Captain. Be patient.",
	"I see.",
	"Great! Well, Monsieur Captain, good luck to you.",
	"Thanks. I guess I'll need it.",
	"You know, Monsieur Captain, I'm risking my life here. It is unkind of you to be so reckless with your promises. I fear I am in no place to help you anymore. Sorry.",
	"All's the pity...",
	"Yes, I know. If the whole clan attacked you, they must have heard that you fight. It's great you could handle them. I'm glad for you, Monsieur Captain.",
	"Thanks, Armo.",
	"Hello. I know you. You're the new guy, aren't you? Armo's friend...",
	"Yes, that's so.",
	"Ah, Armo. Such a pity. Nobody knows who killed her. The people in the tavern just heard her crying upstairs. As misfortune would have it, there was nobody there at the time. When everybody got upstairs, she was already dead, her throat slashed, lying in a pool of her own blood...",
	"Armo was killed because of me. I'm sure of it!",
	"Well, crying won't help, you know... In memory of Arno, I think I'll call you Monsieur Captain. That's what she called you, isn't it? Do you mind?",
	"No, not at all.",
	"You need money, Monsieur Captain? But why?",
	"It's a matter of life and death, for the whole city!",
	"I believe you, Monsieur Captain. I can give you all my savings. After all, not much good they'll do me now.",
	"I'll be very obliged to you, Armo.",
	"How about one hundred thousand? That's all I can give you...",
	"Excellent!",
	"Take it, then. And good luck!",
	"Thanks, Armo.",
	"What goods are you talking about, Monsieur Captain?",
	"You've already asked about that. ",
	"Yes, you've asked me already...",
	"Look, I've told you all I can about this stuff.",
	"I want a bomb, gunpowder, guns...",
	"Yes... Sorry, slipped my mind.",
	"Ah, well, yes.",
	"Understood. I understand...",
	"You can get bombs form the ship hostesses - Alice Taylor, Oreli Bertin, Lea Toors, Elise Calvo. As for the other stuff, can't help you there.",
	"I see... Thank you.",
	"And?",
	"We've been over it already.",
	"We have discussed this already. Let's not go over it again...",
	"Enough, already. You've tired me out...",
	"I want to ask you to join my crew.",
	"Yes... Sorry, slipped my mind.",
	"You know...",
	"Well, all right...",
	"No, Monsieur Captain. Tomas and I, we're staying in the city.",
	"It's not about your Tomas, you know! Staying here, you're risking your own life.",
	"No, Monsieur Captain. I'm staying here, in my tavern.",
	"Staying here, you're risking your life.",
	"Why?",
	"The upcoming storm is likely to destroy the city.",
	"Storms are nothing new here. We can stand one more.",
	"All for nothing... Well, er, it's your choice.",
	"I remember, Monsieur Captain.",
	"Tell me, please, how it all happened.",
	"Well. Nothing to tell you, really. Taylor spent about three hours here, and then as usual he left a broken man.",
	"I see... Did he leave alone?",
	"Arm-in-arm with Zil Baru.",
	"Wait a minute. Zil Baru was the one to see him to his house, wasn't he?",
	"Well, yeah, he was.",
	"Ah! Thank you, dear.",
};
