string DLG_TEXT_LSC [145] = {
	"My greetings to you! As far as I understand you're the survivor of the last storm. Let me introduce myself, my name's ",
	"Glad to meet you. And I'm ",
	"My greetings to you! As far as I understand you're the survivor of the last storm. Let me introduce myself, my name's ",
	"Glad to meet you. And I'm ",
	"What did you want, monsieur?",
	"Listen, I'm looking for someone. You wouldn't know where he is now?",
	"I want to ask you a question.",
	"Can you tell me something interesting?",
	"What new in the city?",
	"It'd be great to hear the latest gossip...",
	"I need to talk to you about Maxim Taylor.",
	"You know, I'm assembling a team to get out of here. ",
	"Nothing...",
	"So how do you like our city, all at nature's mercy, so to say?",
	"You know, I'm not exactly adequate now, have lost everyone and everything, you know. So my vision of the world isn't exactly bright now.",
	"Well, of course, it's quite clear! Sorry for my lack of tact... The storm will end soon, you know.",
	"I know, thanks.",
	"You know, it's very nice  our city got such a pleasant new citizen as you are. It's really nice. At last someone to talk to.",
	"Why do you think I'm nice to talk to?",
	"Hmm... Er, it seemed to me so.",
	"If I were you, I wouldn't trust anything which only seems, you know. Is it clear?",
	"It's really clear, really!",
	"Well, fine then...",
	"Oh, you thief! Don't you know that's against the law?!",
	"Isn't that something! I look away for one second, and there you are, shoving your head into a chest! That's illegal, that is!",
	"Militia! I'm being robbed! Thief! Grab him! I've got a criminal here!",
	"Good grief! ",
	"Oh, so that's how it's going to be?! You you'd just waltz in here and raid the chests, eh?! Well, now I get to watch my neighbors and the militia tear you up like an old rag!",
	"Oh, you dumb broad...",
	"Listen, you'd better sheath your weapon already. You're creeping me out, a little...",
	"You know, it's not acceptable to wave your sword around here. Put away the weapon.",
	"Listen. Why are you running around, swinging your saber like the Three Musketeers? Put away your weapon. Such behavior does not befit a gentleman.",
	"Okay.",
	"Fine.",
	"As you say...",
	"Listen. As a citizen of this city, could I ask you to please not waltz around with an exposed dagger?",
	"You know, speaking as a resident here, I'd really prefer it if you wouldn't run around town with a drawn dagger. It really lowers the tone of the place.",
	"Fine.",
	"Okay.",
	"As you say...",
	"Whoa, buddy. Careful on those turns. Especially when you're running around with an exposed weapon. Enough to make a guy nervous...",
	"I don't like it when I see guys walking around with weapons at the ready. It's really unnerving, you know?",
	"Got it.",
	"Putting it away.",
	"Glad to help where I can. And who are you looking for?",
	"I don't know who you mean. If I'm going to help you, I need the person's name. Both family and Christian, if you please. ",
	"Hm. Let me throw that by you again, then. ",
	"Thank you. I think I'd be better off looking on my own.",
	"Hm. Pardon me, but the person you're looking for... That's me!",
	"You don't say!",
	", is that who you've got in mind?",
	"Definitely him.",
	"No, that's not it. Let try it again.",
	", that wouldn't be her, would it? ",
	"Yeah, that's definitely her.",
	"Nope, not her. Maybe it'll ring a bell if I say it again?",
	"You know. Thanks for all the help and all, but I'm kind of tired of going over this...",
	"Then you'll have to give me the name again. First and last.",
	"I have no idea where he might be.",
	"I haven't the foggiest notion where he is now.",
	"I haven't seen him in a decent while... so I dunno.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"Golly. Haven't seen her in a long time. My sympathies.",
	"No... No clue where she is now.",
	"Haven't seen her in a while. So I wouldn't know.",
	"Got it.",
	"I see... Well, then. Thank you.",
	"He's here on this ship. Look closer, please.",
	"Hm... But he's here on this ship, right now...",
	"He's on this ship. Strange that you haven't met him yet.",
	"Oh, I saw him recently. It was around ",
	"Hey, you know, I recently met him in ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"So he's here, ",
	". Search more carefully.",
	"So he's here, among us!",
	"Where are you looking? He is hanging out here.",
	"I saw him just recently ",
	"I recently met him ",
	". So look for him there.",
	"As far as I know, he now is at ",
	"A-ha, I see. Thank you.",
	"Thank you!",
	"She is here, on this ship. Search more carefully.",
	"Ha! So she's here, on this ship!",
	"She is on this ship; it's strange you haven't seen her yet.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation.",
	"As far as I know, she now is at ",
	"So she's here, ",
	". Search more carefully.",
	"So she's here, among us!",
	"Where're you looking? She's walking around here someplace.",
	"I saw her just recently ",
	"I recently met her ",
	". We even had a conversation with her.",
	"As far as I know, she now is at ",
	"A-ha, I see. Thank you, ",
	"Thank you!",
	"I'm all ears, buddy.",
	"Listen, what island is this?",
	"Do you know why such a city was formed, any ideas?",
	"Look, how long have you been hanging around here?",
	"No questions. Excuse me...",
	"This is the City of Abandoned Ships, buddy. Everything's a bit different from the Big Lnad here...",
	"What do you mean?",
	"I mean, it's a different life with its Law! In fact, the laws aren't bad here, quite fair, I'd say. So, I suppose, you'll like it here.",
	"Hum, I hope so.",
	"No, and nobody knows. They say there's either some really strong current or some algae, or maybe, some coral reefs, but no one knows for sure.",
	"Has anyone tried to find out?",
	"They say, some tried, but they failed really soon and the failures were really sad, really...",
	"Hm. Understood.",
	"Hanging around? Not a bad word choice... I've been wearing out the seat of my pants for three years here now",
	"It's been a long time. Aren't you fed up with it?",
	"Maybe I am, maybe not...",
	"As for Hill Brunner, was he here when you came?",
	"Of course, he was. He knew everyone in the city. Poor Hill, he was a very good man...",
	"I agree.",
	"Sorry, I didn't get you. What did you say?",
	"I'm offering you to sail away from the city to the Big Land as one of my corvette crew.",
	"That's quite an offer! Do you really have a corvette afloat?",
	"Yea, I do.",
	"Well, nothing to think about, really. I'm leaving with you.",
	"Perfect. Now make your way to San Gabriel. Henrick Vedeker will help you get to my ship.",
	"I'll just grab my things and will be right there.",
	"Excellent!",
	"I'm listening to you.",
	"I learnt that you left the tavern together with Taylor on the day he was arressted. What happened? How did he end uo at the residence of the Admiral?",
	"Sorry, but what's your business here?",
	"The matter is Maxim Taylor is going to spend the rest of his life in a cage at Tartarus. The Admiral gave him a life sentence as a punishment.",
	"Good Lord!..",
	"That's it. I'm worrying about the Taylors, that's why I want to know what happened.",
	"Damn, I didn't expect it to happen this way...",
	"Can you explain yourself, please.",
	"Oh, well, to start with... Well, I just played a joke on the Admiral. He really got us with all his laws...",
	"What does it have to to with Taylor?",
	"Well, nothing, really. It's just on the night we were having a couple of drinks with him in the tavern, we were discussing this. And after that, when we left, I led him to San Augustin and offered him to say about his discontent right to the Admiral, And so he did.",
	"Ho-ho, not a bad idea... I wouldn't say, though, that it was very decent of you.",
	"I know I didn't exactly do the right thing. So I guess I'll go to the Admiral and tell him we were just joking around.",
	"Well, great then. I'll go to Capper too and do my best to get Taylor as soon as possible.",
	"Let's do it then. I hope the Admiral doesn't kill me.",
	"It's very unlikely.",
};
