string DLG_TEXT_GUB [323] = {
	"What questions?",
	"What do you want?",
	"I've changed my mind...",
	"I have nothing to talk about.",
	"You're an English privateer, and must keep your word to me! I ask that you immediately begin the task to which you are assigned!",
	"Until you finish your assignment, we have nothing to talk about.",
	"I await the report of your finished assignment, not empty conversation!",
	"Proceeding immediately.",
	"I'm already in the process of completing it...",
	"I don't have any special assignments for you for now. Stop by here from time to time.",
	"Not now! I'm too busy!",
	"At the moment, my friend, I do not require your cleverness and courage. Focus on your privateering.",
	"Yes, sir.",
	"I have an assignment for you.",
	"I'm ready, sir.",
	"Drop by in two days. I'm got a matter brewing for you.",
	"Yes, sir.",
	"I've got a matter for you: a reconnaissance mission. I need to know what the Dutch are planning, in regards to the trade war. Get into Curacao, and try to get as much information as you can about what's going on there. I'm interested in everything that's going on in the city, right down to the smallest details.",
	"I'm ready, sir.",
	"And here you are. I was waiting for you.",
	"At your service.",
	"Privateer frigate Captain Morris Williams asks to join me in the raid on the Port Royal.",
	"I'm familiar with Captain Williams.",
	"We great regret, I inform you that the order of the British government to return the cargo captured by Morris Williams to its Spanish owner has led to grave consequences for Jamaica.",
	"Hmm... I don't seem to follow, sir...",
	"I need you again, my friend. I need to send a dependable man to head the settlement of the La Vegas buccaneers, on Hispaniola. You remember Edward Mansfield? You met him during one of my assignments.",
	"I remember, sir. I was trying to convince him to mount an attack on Curacao.",
	"Are you ready to undertake the serious business of storming a Spanish city?",
	"Yes, I'm ready enough.",
	"No, sir. I don't have enough ships for such a serious undertaking. I'll get prepared properly, and return later.",
	"The government of Spain has assembled seven battleships, under the command of admirals de Bustosa and del Campo y Espinoza, against the Jamaican corsairs. They've come close to Jamaica. The finest moment is at hand. You saw yourself, at the Port Royal raid, that there were no other corsairs beside us. All were with Morgan, on another round of Spanish hunting. You must repel the attack. I'm handing you command of the guard ships; that's all I can do to help. Forward, and may God help you!",
	"Fine, sir. I think we can make it.",
	"You're just in the nick of time! I have an important assignment for you.",
	"I'm listening to you, sir.",
	"My friend, I have a somewhat strange assignment for you...",
	"I'm listening to you closely.",
	"I've very happy to see you here. And you're just in time, sir.",
	"Sir?",
	"I have a very important errand for you. You're new here, and I don't know if it's worth it to trust you. Still, it looks as if I have no choice.",
	"I'd be delighted to handle this errand.",
	"I'm sorry, but I'm working on an another mission right now.",
	"In the letter you delivered, Duke Albermal gives you a rather flattering appraisal. The Duke is my relative. I owe him this position. If it weren't for his active and timely action in England, then I don't know how my governance on Barbados would have ended...",
	"You've brilliantly handled the assigned task. Your promised reward amounts to 50,000. You've earned this fee, as well as my gratitude.",
	"A recommendation from Duke Albermal... That's the best reference I can imagine. If you're prepared to cooperate further with England, then I'll ask you to stop by me from time to time.",
	"Thank you, sir. You can count on me in the future.",
	"You heard that Captain ",
	" was much praised by our Governor-General? He was allegedly able to secretly transport his London uncle and patron, Duke Albermal, from the island. You don't know Albermal?! I'll tell you a secret. It's only thanks to him that Sir Thomas Maddyford is acting Governor-General of Jamaica. Otherwise, he wouldn't be up to it...",
	"Well, then. In the letter you delivered to me, Albermal informs me of his successful arrival to Saint-Johns Though you beat back an attack by a Spanish brig, you were unable to deliver the Duke to the destination in time. Your reward amounts to 20,000. I can't say I'm fully pleased with you.",
	"Sir, I ask that you forgive my tardiness. I was held up by circumstances beyond my control. May I hope to receive special assignments in the future?",
	"You've gained the support of pirates? When's Mansfield planning to act?",
	"Unfortunately, sir, I was unable to make arrangements with any of the pirates that you noted. I've received denials everywhere for the attack on Curacao. The reasons for which the corsairs have declined to attack are varied.",
	"Report your discoveries. ",
	"Unfortunately, I was unable to capture the ship on which I was supposed to find the necessary papers. I was unable to find out anything useful.",
	"Report your discoveries. ",
	"Here is the document that I found on the captured Dutch brig. It's an order for the commandant of the Fort Orange to immediately fortify the city.",
	"Report your discoveries. ",
	"I've received information about the Dutch courier brig. Though I was able to board the brig, I was unable to find any documents.",
	"Report your discoveries. ",
	"Unfortunately, I was captured and locked in prison. Though I was able to escape, I was unable to learn a thing.",
	"Report your discoveries. ",
	"Unfortunately, in the process of conducting my mission I was discovered. There was a fight and I was barely able to get out of the city. There can be no thought now about my returning to Curacao.  I was unable to learn anything of interest to you.",
	"You're covered in blood.",
	"Yes, well... It's Dutch blood. We did it. Fort Orange has been looted. My team has made out pretty well for itself. Mission accomplished.",
	"So, what do you say. ",
	"Sir, your assignment is complete. Morris Williams is coming into port.",
	"Ah. Here you are again, ",
	". I'm listening to you closely.",
	"The Devil! What's happening?",
	"Ah, here you are again, ",
	". What brings you to me this time?",
	"Sir, I need to talk to you.",
	"Ahh, my friend. What, you've already blown through your five thousand? In need of work again so soon?",
	"No, I came to discuss an unrelated topic.",
	"I have nothing more to say to you. Politics determine the fate of entire governments. There's no time to fuss over the fate of individual privateers...",
	"A real pity, sir.",
	"Now, then. my friend, have you calmed down about Williams? My advice to you is to leave that case alone. The poor man was unlucky; that's life. Somebody has to be the loser...",
	"Sir, I greatly value your kind advice. I shall try to follow it...",
	"I heard you boarded and took a Spanish pinas, right next to San Juan. And under fire from the fort and guard ship-of-the-lines?! I must say, a risky operation...",
	"All's well that ends well, sir...",
	"I heard you boarded and took a Spanish pinas, right next to San Juan?! Tell me, was the risk justified?",
	"No, sir. Nothing useful in the hold...",
	"I heard you sank a Spanish pinas, right next to San Juan. Was there a need to attract fire from the fort and the ship's guard?",
	"It turned out that way, sir.",
	"The head of the port reports to me that you went after a Spanish pinas. Pray tell me, my friend, of your inevitable triumph! ",
	"None to report, sir. A wasted effort...",
	"Have you found gold?",
	"Not yet, but I'm ceaselessly searching. The mission's not simple...",
	"I've got something.",
	"You know, Governor-General, I'm sick to death of this. I no longer want to rush around the Caribbean and search for your gold.",
	"Have you brought the gold from Mansfield?",
	"Sir, the buccaneer settlement was attacked by the Spanish. Mansfield was killed; the gold's been captured. The admiral of the Spanish squadron was, it appears, Manuel Rivero Pardal.",
	"Have you brought the gold from Mansfield?",
	"Sir , La Vega has been attacked by the Spanish. Mansfield's been killed; the gold's been captured. The admiral of the Spanish squadron was Manuel Rivero Pardal. Sir, I cleared everything up to Santiago, but didn't meet the Spanish who attacked.",
	"You couldn't intercept the Spanish?",
	"No, sir. I was unable to do it. Again, I checked everything up to Santiago, but I was unable to meet any galleons.",
	"Have you brought the gold from Mansfield?",
	"Sir, La Vega has been attacked by the Spanish. Mansfield has been killed; the gold's been captured. The admiral in charge of the Spanish squadron was one Manuel Rivero Pardal. I was able to intercept one of the three attacking galleons, board it, and take it. There was no gold on it, but in the captain's quarters I found Pardal's letter to Governor Jiménez of Santiago. Here is is.",
	"Were you able to intercept the Spanish?",
	"I was able to board and take a Spanish galleon off Santiago, which took part in the attack on the buccaneers. There was no gold on it, but a letter from Pardal to Jiménez, the governor of Santiago, was found in the captain's quarters. Here it is.",
	"Have you brought the gold from Mansfield?",
	"Sir, La Vega has been attacked by the Spanish. Mansfield has been killed; the gold's been captured. The admiral in charge of the Spanish squadron was Manuel Rivero Pardal. I was able to intercept one of the three attacking galleons, board it, and take it. I found no gold on it. It looks like the gold was kept on another ship. I don't know where the other ships went.",
	"Were you able to intercept the Spanish?",
	"I was able to take and board a Spanish galleon off Santiago, one of those that took part in the attack on the buccaneers. I was unable to find any gold on it. It looks like it was located on another ship. I don't know where the other two galleons went.",
	"Have you brought the gold from Mansfield?",
	"Sir, La Vega has been attacked by the Spanish. Mansfield has been killed, the gold's been captured. The admiral in charge of the Spanish squadron was Manuel Rivero Pardal. I was able to intercept one of the three attacking galleons and sink it. I don't know where the other two galleons went.",
	"Were you able to intercept the Spanish?",
	"I was able to take and board a Spanish galleon off Santiago; one of those that took part in the attack on the buccaneers. I was able to intercept, and sink, one of the three attacking galleons. I don't know where the other two galleons went.",
	"Have you brought the gold from Mansfield?",
	"Sir, when I arrived at La Vega, it turned out to be empty! Not a single living soul. I searched the surrounding area, but found nothing.",
	"I already know of your heroic deeds. This is a brilliant victory, my friend.",
	"Thank you, sir. I think you'll be happy to know that the governor of Santiago is my prisoner, and is currently aboard my ship.",
	"God damn it, you've literally saved all of us! The city of Port Royal owes you its life!",
	"Yeah, the Spanish mustered such strength that even I couldn't have imagined it...",
	"You have yet to capture Cumana, or Caracas. All the shores of Mein are still under the control of the Spanish...",
	"Sir, I'm handling it. This is goal that requires serious preparation. When the attack will be carried out depends on our preparations.",
	"You've captured Caracas! This is wonderful, my friend. But Cumana has yet to captured. Hurry!",
	"Yes, sir.",
	"Cumana belongs to England, and this is your achievement! Excellent, my friend! Though I also await the capture of Caracas from you, my friend!",
	"Everything shall be done, sir.",
	"Cumana and Caracas are captured! Now this shore of Mein belongs to England!",
	"Yes, sir. We've done it.",
	"Tell me what you've learned. What's happening at Saint John's?",
	"Sir. In the residency of the governor of Saint John's, I met Colonel Thomas Lynch.",
	"You've accomplished the assigned goal. Maddyford has been arrested and placed in jail. They're beginning a thorough investigation of his activities during his post as the governor-general of Jamaica. I would very much like to see you again in about a month.",
	"Yes, sir.",
	"I don't deal with people who break their word. I have nothing more to say to you.",
	"Sir, I trust your view on the situation in the Caribbean sea. That's why you have full freedom to act in the interests of England.",
	"I understand, sir. Thank you for your trust.",
	"I've a guest at the moment, in the person of Duke Albermal. His mission here is finished, and I must immediately escort him to Britain. On the island of Antigua, in Saint John's, a frigate of the Royal Navy is waiting for the Duke. Get the Duke to Saint John's, to the residency of the governor.",
	"Leave immediately, and be careful. They've already caught two Spanish spies in Port Royal, and I'm absolutely sure that the city still has agents. I must take for granted that the Spanish know of the presence of such an eminent figure on this island. Also, I've received reports of strange activity by Spanish warships around Jamaica.",
	"Hm, If that's so, it's best to expect the worst.",
	"Exactly at this moment, I need a captain with a vessel that won't attract attention. My calculations are based upon surprise. Nobody knows you or your sails. You pose the least risk in getting Duke Albermal to Antigua.",
	"I think you're right, sir.",
	"Do this within two weeks, and you'll be handsomely rewarded. Your head's on the line, in regards to Duke Albermal. He's currently in my residency, in a private cabinet. Go, as soon as you're ready, and don't hesitate or take too long.",
	"I understand you, sir.",
	"Duke",
	"Albermal.",
	"I think, yes. Though from now on, be more thorough in completing my assignments. You're an English privateer. The interests of England are above all else!",
	"You're right, sir. You can surely count on my being more industrious in the future.",
	"You know, Captain ",
	" was able to accomplish Maddyford's complex mission. He had to deliver Duke Albermal to a safe place... You don't know Alberma?! Confidentially, it's only because of him that Sir Thomas Maddyford is the acting governor of Jamaica... Only the Captain didn't make the deadline in time.",
	"In Europe, there's a trade war going on with Holland. The Anglo-French fleet made it to the shores of Holland, but, to great surprise, was destroyed. Now, by order of the English government, I have to organize an attack on the Dutch colony of Curacao.",
	"However, at the moment I don't have the resources to deal with a fortress like Willemstaad. I'll interest English privateers in the attack. In fact, it's quite efficient for me to have an improvised pirate fleet at Port Royal - good protection, and absolutely free for the Crown! Ha!",
	"What is the essence of my mission?",
	"I need you to find Edward Mansfield, in the buccaneer settlement of La Vega on Hispaniola; Henry Morgan, presently at Saint John's; Jackmann, in the Bermuda pirate settlement; and John Morris, in Trinidad. You must reach an agreement with these pirates to conduct an attack, commanded by Mansfield, on Curacao. Complete this as soon as possible. I'm counting on you.",
	"I'll begin immediately, sir.",
	"I would like to speak separately about Morgan. The thing is, his house on Antigua is a real fortress. It's not easy to get in there. You are to enter the house through an underground passage, located under Saint John's.",
	"I understand, sir. Thank you for the warning. I presume I'll figure out what's what.",
	"John",
	"Morris",
	"Laguna",
	"What do you think? Can something be changed in the future?",
	"It's hard to say, sir, but I don't so. None of the four will be talked into this, for sure.",
	"Hm. Understood. Well, then. Despite the negative result of the mission, I'm pleased with your promptness and industriousness. You're entitled to a reward of 15,000. I hope that I'll be able to use your services in the future?",
	"Of course, sir. I would be delighted to help you.",
	"I'm very disappointed that the order of the English government will not be completed. This is bad, and to add to that you weren't prompt enough in completing this mission. You frittered away ",
	" days! The payment will reflect this. That is, it will be low.",
	"Well, then. you see clearer.",
	"You know, Captain ",
	" worked as a errand boy at Maddyford's - rushing from end to end across the entire Caribbean Sea, even ending up at Morgan's...",
	"To ease the completion of this mission, I'm giving you a twenty-day license from the Dutch East India Company, which will allow you to easily enter the city. Begin immediately.",
	"Yes, sir.",
	"Oh, that's no good at all... Really, I must say I'm disappointed in you. Still, you may return later, once I have scraped together my information from more reliable sources...",
	"Of course, sir. I apologize for being of such limited use this time around.",
	"I understand that you bungled a simple recon mission on Curacao. That... surprises me.",
	"So you got the document?! Brilliant! I knew I was right about you.",
	"However, the Dutch are onto us... I need some time to think. Please, come back in a little while. Oh, yes - and here's a flat hundred thousand for a job very well done.",
	"Sir, to meet my objective I had to bribe a loan shark in Willemstad. As it happens, the bribe amounted to exactly one hundred thousand. Though generous, this reward merely compensates me for my expenses.",
	"Hmm. All right, I'll tell them to divvy out an extra ten thousand. Now I must ask you to leave. Come back to see me in a few days.",
	"A thousand thanks, sir. I'll see you then.",
	"Rumors say you were able to infiltrate Willemstad and spy out all the Dutch secrets. I reckon this will help a great deal in our preparations for the upcoming war...",
	"I don't care if you've been in a Dutch prison or a Turkish bath. I need information, and you do not have it. What more can I say? You disappoint me. Now I need to turn to other routes to gather the information. This will take some thought, so so please let me be. Come back later, if you must.",
	"Of course, sir. I apologize for being unable to help this time.",
	"I hear you managed to wind up in a Dutch prison. So how was it - any rats?",
	"You've certainly proved yourself a fighter. Yet when the situation required guile, you fell short. You have failed me. ",
	"I'll need to scrape up my information elsewhere. Once I do, who knows... Maybe you'll still be of some use to me.",
	"I understand, sir. I'm sorry I couldn't help you.",
	"People say you've caused quite a stir in Willemstad...",
	"Well, we now have information that the Dutch are making hurried reinforcements to their Fort Orange settlement on Jamaica. To be honest, I wasn't particularly bothered by their settling on the other end of the island, but now that the trade war has begun...",
	"A Dutch settlement on British territory - well, you see the problem there! It's my duty to bring it to ruin. And this mission, I entrust to you.",
	"Any spoils that Fort Orange has to offer are yours to keep. Now get to it. ",
	"Very well, sir.",
	"Ha! I dread to imagine the state of that fort, once you're done with it... I wager your appearance alone will make them soil themselves. I declare, you are the devil incarnate!",
	"I've nothing but respect for the noble quester - he who does quails not at the spil of crimson ichor... To the glory of our heroes!",
	"I hope to see more of you, my good friend.",
	"I have no doubt, sir, you will see me regularly. I am, as you say, an adventurer - and the friendship of Sir Thomas Modyford is quite to my advantage. On that note, I shall take my leave - for I have much business to attend.",
	"Ah, I understand... Yes, all pity to the maiden who writhes in your absence... Don't make her wait too long! Hwaha-hurr.",
	"Have a good - no, check that. Have a great time, my friend. May it be productive just as it is... ahem, pleasant. You truly are the model of a renaissance man.",
	"Well, I won't keep you any longer. 'Til we need again...",
	"Yes. Until then, sir.",
	"I'm quite impressed by your work at Fort Orange. My, my. Those poor Dutchmen...",
	"Well, that's good. Okay, so he's just coming off a successful Spanish raid, and his hold is laden with mahogany, silver and indigo... ",
	"So he's looking to sell his trophies, preferably in a British colony. To that end, I will let him enter Port Royal. Please give him my personal permission to sell the booty here.",
	"Yes, and be sure to tell Williams - but make sure there are no witnesses when you do so.",
	"Nothing could be simpler.",
	"Yes, so I heard. Here's five thousand for your efforts.",
	"I wish I could say it did involve effort, but refusing money is poor policy.",
	"What's going on? Where are your manners?",
	"You confiscated cargo belonging to to Morris Williams! And who do you think invited him to Port Royal? That's right, I did!",
	"No you didn't. I invited him into Port Royal; you were merely my messenger. As for the cargo, it was returned to its Spanish owner.",
	"I don't believe my ears! Why?!",
	"Relations between Britain and Spain are taking a turn for the better. This is a gesture of good will.",
	"I see, my friend, that politics are not your strongest suit - so I suggest that you leave them to the professionals. Goodbye now.",
	"I'm... speechless. Well, goodbye... sir.",
	"Captain, was it really you who set up poor Williams like that?! I would never have expected such a thing from you...",
	"Settle down, my friend. Tell me what happened.",
	"Morris Williams is rotting in prison, and it's my fault! I won't rest until I free him.",
	"Hmm... I see that you are an honorable man. To be honest with you, I don't enjoy keeping an honest seaman under guard myself. But what can I do? The law is the law.",
	"I'd suggest you visit the local loan shark. Morris owed him money, and failed to pay back his loan - that is why he's in prison now.",
	"Thanks for the tip.",
	"The thing is, British corsairs have stopped coming in here with their Spanish plunder. Nowadays they only stop to make repairs, and spend as little money as possible.",
	"And I hope I don't need to explain to you just how much Britain loses each month over the ten percent tax that corsairs must pay on all captured cargo. I'm scared to even imagine what the Jamaican merchants are going through!",
	"Nowadays corsairs either stash their cargo in secluded island hideaways, hump their goods to Portsmouth in vain hope to offload it, or try to fence the booty through their French contacts on Tortuga.",
	"Anyway, the situation is painfully clear: the Spanish are still being raided, but what are we getting from it? Zilch!",
	"The Jamaican Council has decided to resume its distribution of patents for our corsairs. Your next mission is rather delicate: it has come to my attention that as many as seven famous corsairs hid away their gold in caves all over the region.",
	"Though I can't be more specific, I can tell you generally where the treasures are kept:",
	"1. Thomas Whitson - near Cartagena",
	"2. Adrian Swart - on the island of Trinidad",
	"3. Captain Gay - on the island of Turks",
	"4. Captain Cooper - on the island of Dominica",
	"5. George Branningham - on the Cayman Islands",
	"6. Captain Goodley - on Cuba",
	"7. Abraham Blauvelt - on Guadeloupe",
	"Find all of these, and bring them to me. I trust I need not tell you that this mission is confidential. Consider this a binding non-disclosure agreement...",
	"I understand. Sir, I reckon I can settle this matter for you.",
	"Sir, I'm confused as to the exact nature of my mission. The corsairs' treasures are their own business. Where do I come in?",
	"Hmm, I must say I'm rather puzzled by your behavior...",
	"I'm sorry, sir, but I cannot help you.",
	"You know, Captain ",
	" refused to accept Modyford's mission to search for secret pirate hordes...",
	"Brought together, I believe the seven treasures should equal twenty-one hundred gold bars! Bring me all of them...",
	"Understood, sir. It shall be done.",
	"All right, let's have a lookie here...",
	"Sir, currently I have ",
	" gold bars. Here, let me pass it over. ",
	"Sir, on my person I have ",
	" gold bars. But this gold I have acquired through activities unrelated to your mission. Therefore, I will keep it.",
	"Very well; I hereby accept ",
	" gold bars from you. So far you've handed over ",
	" bars. That means that you still need to find and bring me ",
	" bars.",
	"Understood, sir. I shall resume my search immediately.",
	"You have completed the task set before you. You have delivered a total of twenty-one hundred gold bars, exactly as I calculated. So then, your ten percent comes to seventy thousand.",
	"Thank you, sir.",
	"Wow, you found more gold than I expected! At this time you have ",
	" gold bars. Previously, you handed in ",
	" bars. Therefore, our little scheme has exceeded itself by ",
	" bars.",
	"Sir, the excess you speak of is from my personal cache, which is not related to this particular task in any way.",
	"Well, I must say that I am extremely pleased with you. Our collaboration has left a pleasant impression on my mind. You remain a welcome guest in my home. ",
	"Thank you, sir. I shall check back regularly.",
	"There are unconfirmed rumors going around that a certain captain helped Modyford sweep the area of secret pirate troves. Mind, it was Modyford's own fault that the brigands started to stash away their spoils in the first place...",
	"Then why the hell are you jiggling it before me?",
	"From now on, I ask that you refer to it as MY gold.",
	"Sir, you asked me a question, and I gave an honest answer. Please forgive me.",
	"Hrm, I recommend that you refrain from expressing yourself in that manner. I am disappointed in you... and I believe I shall impose a fine!   \nI shan't keep you longer. You may go now.",
	"I'm sorry to have caused you any inconvenience, sir.",
	"Exactly! Well, all the better, I say.",
	"Mansfield has prepared a batch of gold bars. Taken together, they add up to a hefty sum. I need this gold delivered to Port Royal, and you are the only one I can trust with this job.",
	"Very well, sir. Is there any sort of time limit? ",
	"Well, there is no particular rush, but I don't advise you to dawdle.",
	"I see. I'll set sail as soon as I finish my preparations.",
	"The buccaneers' fort is empty and burning.",
	"Damn it! Were you able to learn anything? ",
	"Looks like the Spanish retreated to Santiago. I'll try to intercept them.",
	"Very well. Please do your very best to find them.",
	"I understand, sir.",
	"I need to think. Come back in... let's say, about ten days.",
	"Yes, sir.",
	"Alistair",
	"Good",
	"There are rumors going around that the buccaneer settlement on Hispaniola was ravaged by the Spanish...",
	"With a bit of research, I was able to learn with absolute certainty who was behind the attack at La Vega.",
	"Well, who was it?",
	"I want to bring to your attention that the carnage at La Vega was a result of an attack carried out by the Spanish.",
	"I understand, sir.",
	"Thanks to the letter you found on the Spanish galleon, we now have a clear idea as to who was behind the attack at La Vega.",
	"Yes, sir. I've read that letter.",
	"Task received.",
	"This attack was organized by Governor José Sánchez Jiménez, of Santiago. His right arm in the operation was Manuel Rivero Pardal, the only Spanish pirate in these waters.",
	"What do I need to do?",
	"You need to attack Santiago and bring me Governor Jiménez. All I want is Jiménez, so do with the city what you will.",
	"I understand, sir.",
	"Well I'll be damned, you truly are irreplaceable, ",
	". Mansfield is avenged, and then some!",
	"What should I do with Jiménez?",
	"Hand him over to the officer on duty. I'm in too good of a mood to deal with him today, so I'll save the pleasure for tomorrow.",
	"I suppose that after such grand and mighty exploits, you need some rest to regain your strength. I dare not keep you from it, but please do come and visit any time you like.",
	"Oh, and another thing... Drop by to see Morgan. I think he will be pleased to know that Edward Mansfield was avenged so soon, and so... effectively. Mansfield was like a father to Morgan...",
	"Very well, sir. I will certainly let him know.",
	"Captain, all you hear about here is how you captured the Spanish governor and brought him to Port Royal. Captain, you are a true hero...",
	"The Spanish decided to just finish us off, once and for all. And they pulled together a veritable armada to do it! But we made swift work of them anyway!",
	"Yes, sir. Though by no stretch of the imagination was it a simple task, the citizens can now breathe more easily. As far as the Spanish are concerned, I doubt they will recover from such a blow...",
	"I agree with you, my good friend. I venture that eighty thousand shall suffice, to repair your ships and replace your crew? Britain needs you, my friend - and Britain shall not forget you!",
	"Excuse me, but right now I need to think about retaliatory measures... Please come back to me in a week.",
	"Very well, sir. I'll be back to see you then.",
	"Captain, you have saved us all! The townsfolk are all incalculably grateful to you, for this heroic deed.",
	"Our response to the Spanish attack on Port Royal shall be an attack on the Spanish cities.",
	"There are two Spanish cities on the continent, near Trinidad: Cumana and Caracas. Capture those cities, and have their population swear an oath of fealty to His Majesty Charles II.",
	"Assist in appointment of a new government - so as to normalize city administration and begin the collection of duties and taxes - sooner, rather than later.",
	"I understand, sir. I shall get right onto it, as soon as I have finished my preparations.",
	"Excellent, my friend. Simply brilliant! Any booty you capture on the island is rightfully yours!",
	"Please come back to my residence in a month. I should have another job for you then.",
	"Yes, sir.",
	"Captain, it looks you'll have a new nickname soon - ",
	" the Conqueror!",
	"Something strange is happening in Saint John's. I am no longer receiving routine updates from the Governor on the city's state of affairs.",
	"As my confidant, I'm asking you to pay a visit to the Governor residence at Saint John's, and shed some light on the situation.",
	"Yessir. I doubt there's anything to worry about, but I'll find out for sure.",
	"Hrm... So?",
	"Sir, by the order of the British government, you are under arrest...",
	"Not so fast! Officer, help!",
	"Damnation!",
	"Have you heard?! Governor Modyford has been arrested and put in prison by one of his own trusted agents! Who would have thought...",
	"Nothing to be surprised by. But tell me everything, from the beginning.",
	"It brings me great pleasure to inform you that your exceptional service to your country is duly recognized.",
	"I have the honor of informing you that you have been promoted to knighthood. From this moment, any address put forth to you shall be preceded by the title of 'Sir'.",
	"Moreover, after a full investigation into Modyford's business affairs, a rather enormous investment has been recovered. Part of this money belongs to you, good sir. To be more precise, three hundred thousand in gold. Please be so kind as to accept it. ",
	"Thank you very much. I hope to continue being of use to His Majesty in the future.",
	"I'm counting on it.",
	"My good captain, with your help, I hope to see the Caribbean more British. Still, let us not forget that Spain is no enemy of ours. At least for now...",
	"I understand, sir. I will put my best effort toward ensuring the prosperity of the British presence  in the Caribbean.",
	"Sir ",
};
