string DLG_TEXT_GUB [352] = {
	"What questions?",
	"What do you want?",
	"I've changed my mind...",
	"I've got nothing to say now. ",
	"Monsieur, I've been trusted to deliver a diplomatic dispatch to you from Governor-General Peter Stuyvesant, of Curacao. Please receive it.",
	"Monsieur Governor-General, I have arrived.",
	"You've arrived too early. I told you, two hours!",
	"Forgive me, monsieur. I rushed a bit.",
	"Monsieur Governor-General, it's me again!",
	"You are in the service of France! I ask that you immediately begin completion of your assignment!",
	"I won't hide that a lot is riding on the success of your actions. That's why you should begin completing the responsibilities that you took upon yourself!",
	"I'm waiting for your report of what I ordered, not empty tittle-tattle.",
	"I'll begin immediately, monsieur Governor-General.",
	"I'm in the process of completing it...",
	"At the moment, I have no crucial tasks for you. You may show up at my residency later...",
	"I'll ask you to excuse me. I'm very busy at the moment!",
	"Work on your own business. I have no tasks for you now.",
	"Yes, monsieur Governor-General.",
	"It's imperative that you deliver this letter as soon as possible to Governor-General Peter Stuyvesant of Curacao. The faster you do, the higher your reward will be.",
	"Yes, monsieur Governor-General, I shall do so. Give me the letter.",
	"Sir, I have a task of the most delicate nature for you. You're honest, and you know how to keep your word, which you've proved not once. I want to entrust to you the honor of a person dear to me...",
	"Monsieur, let's get closer to the point...",
	"Sir, you've proved your loyalty and honor, and that's why I'm trusting you with a most important and secret matter.",
	"It still has something to do with the sea, I hope?",
	"Sir, I once again have a task of a delicate nature. I have reason to fear for the life of the Dona de Leiva. Visit her, please. She is in my residency, in the neighboring room. The Señora will fill you in on the details.",
	"I will do so at once.",
	"Anna Ramirez",
	"de Leiva",
	"Sir, immediately deliver this packet to monsieur Jean David, who is now in Guadalupe. Only - ha ha - don't try to look for Jean David, there! He is better known as Francua Olone.",
	"The famous filibuster?",
	"It's wonderful that you've come. I was just about to order someone to find you. I have a task for you that won't stand for delay.",
	"Then let's get to it!",
	"Sir, I've received an order to send a sharp, industrious, loyal and competent filibuster into the disposal of the naval quartermaster of France Marquis Bonrepaux, in Guadalupe. I consider your candidacy to be worthy of this.",
	"My gratitude, for the trust. But what is the essence of my mission?",
	"Baron, I've been ordered to appoint you the commander of a special punitive naval corps and to issue you the well-known ship-of-the-line Soleil Royal. Your following tasks will consist of military actions against Spain, in the War of Devolution. The first goal is to beat back the attack of a Spanish squadron, at Port-au-Prince.",
	"Hm. It seems the Spanish want to rule Hispaniola alone...",
	"Oh, Baron, I'm so glad to see you. You're just in the nick of time!",
	"I'm listening to you, sir.",
	"Now, then. Baron, France awaits new achievements from you. The military operation this time is very similar to the previous one.",
	"Capturing the city, monsieur?",
	"Baron, the War of Devolution has ended in the stunning victory of beloved Sun King Louis XIV!",
	"Viva Monsieur Governor-General!",
	"Sir, do you know Pierre Lagrange? Recently, on just a lugger he captured a Spanish military galleon, if you can believe it, filled with wonderful treasure. The ship and the cargo have been sold. The ransom for the Spanish has been received, and the sum sent to the Royal treasury. Lagrange has become a wealthy man, and wants to return to France. And, well. I respect his decision.",
	"And he would rather do so quietly?",
	"Monsieur Lagrange has managed to inform me that everything is okay with him. In fact, he was quite flattering in his appraisal of you. I'm happy that I wasn't mistaken in my choice of an honest and dependable person.",
	"Thank you for the praise, monsieur...",
	"Ahh, it's you... What do you say?",
	"I completed your task. Everything is in order. Moreover, I helped Lagrange deal with some bandits who were trying to rob him.",
	"Ahh, it's you... What do you say?",
	"Lord Governor-General, it's unpleasant for me to report this, but there was an ambush waiting for us on Martinique. Lagrange and I entered battle. Unfortunately, Lagrange perished in the fight...",
	"So, Captain. What do you have for us?",
	"Your letter has been delivered to the addressee, monsieur.",
	"So, Captain, what do you have for us?",
	"I tell you, Monsieur d'Ogeron, I've gotten myself into a jolly mess...",
	"I've been waiting for you. What do you say, monsieur?",
	"I was unable to bring Dona Anna across. A pity that things turned out this way...",
	"Sir, I don't even know how to thank you!",
	"It wasn't that difficult, monsieur...",
	"Sir, report of the completion of the mission.",
	"Monsieur Governor-General, I didn't find the French squadron next to Dominique. Instead, I was attacked by Juan Galeno's Spanish squadron. I couldn't repulse them. I had to leave the field of battle...",
	"Sir, I report the completion of the mission.",
	"Monsieur Governor-General, I didn't find the French squadron next to Dominique. Instead, I was attacked by Juan Galeno's Spanish squadron. Though I repulsed the attack, I regret to report that the Soleil Royal was sunk as a result. ",
	"Sir, I report the completion of the mission.",
	"Everything is in order, monsieur, though not without problem. I repulsed an attack by a Spanish squadron of that Juan Galeno. I didn't find the French squadron next to Dominique, which is why I had to leave the Soleil Royal in Basse-Terre.",
	"Sir, I'm beginning to think that there isn't a task that you can't accomplish. Here is your reward, and Dona de Leiva would like to thank you personally.",
	"Thank you, monsieur Governor-General...",
	"What do you say, Captain? Everything went well.",
	"The letter's been delivered. Only, there was a small problem with Olone....",
	"What do you say, Captain? Everything went well.",
	"Yes, sir. Everything's in order. To add to that, we've managed to capture Cumana, and took a pretty good prize.",
	"What do you say, Captain? Everything went well.",
	"Yes, monsieur, the letter was personally delivered into the addressee's hands. Everything is in order..",
	"Now, Captain. Tell me the results of your mission to save Rock the Brazilian.",
	"I have been unable to find him yet, but I will continue my search...",
	"I looked everywhere for him, sir, but I was unable to find him. I must admit that it was all for nothing.",
	"No, Captain, I was waiting for you. Is there any news of the Brazilian?",
	"There's news, monsieur Governor-General. However, it's not pleasant. Rock the Brazilian died, while trying to escape from the torture chambers of the Inquisition...",
	"I see, Captain, that everything is in order. Rock has already told me what he had to live through in the Inquisition, and how you got him out of there. I am astonished!",
	"Monsieur, it was a completely routine task...",
	"Now, then. Captain, I was waiting for you. Is there any news of the Brazilian?",
	"There is news, monsieur Governor-General, though it's not pleasant. The Inquisition has tortured Rock the Brazilian to death. His spirit left him in my arms...",
	"Now, Sir ",
	", I'm happy to congratulate you with your title of Baron! Believe me, it's rare that anyone gains such an honor.",
	"To be frank, sir, I don't really understand why I need it. Especially considering it didn't come cheap...",
	"Sir, you've lost the Soleil Royal!",
	"I saved Port-au-Prince and sent a mighty Spanish squadron to the bottom of the sea.",
	"Baron, I'm already familiar with your victory. What can I say? Wonderful, my friend! Just wonderful!",
	"The first military operation has been completed, monsieur Governor-General...",
	"Sir, you've lost the Soleil Royal!",
	"I saved Port-au-Prince and sent a mighty Spanish squadron to the bottom of the sea.",
	"Sir, you were unable to defend Port-au-Prince! What was the matter?!",
	"Monsieur Governor-General, the Spaniards have managed to collect a squadron of unprecedented force! I had to recede...",
	"Sir, you were unable to defend Port-au-Prince! What was the matter?!",
	"I wasn't in time, monsieur Governor-General. When I reached the city, it was already Spanish...",
	"What do you say, Baron? How did the operation go?",
	"I captured Santo Domingo. Now this city belongs to France! Though not everything went smoothly...",
	"I captured Santo Domingo. Now this city belongs to France!",
	"Baron, I'm waiting for your report on how successful the operation to capture Santa Catalina was.",
	"Santa Catalina was been captured, and is now under the oath of Louis XIV. That's the good news. The bad news is that I lost the Soleil Royal.",
	"Santa Catalina was been captured and is now under the oath of Louis XIV.",
	"I don't deal with people who break their word. I have nothing more to say to you.",
	"Act independently in the interests of France, and don't forget about the filibusters. The war's over. Time to get your life together, Baron...",
	"Yes, sir.",
	"Wonderful.",
	"With that, allow me to depart...",
	"Wait. Come back here in two hours. I must familiarize myself with the contents of this document. Perhaps there will be an answer.",
	"I understand. I'll be at your residence in two hours, monsieur.",
	"Yes, good. Now, then. I've familiarized myself with the contents of the dispatch. I have an answer for Stuyvesant. I'll ask you to deliver this packet to Curacao.",
	"Yes, monsieur. May I leave now?",
	"Yes, of course. Good luck on the way back. Ever since the start of the War of Devolution, the Spanish have become seriously active. So be very careful. If any of our correspondence ends up with the Spanish, then it may prove our coordinated actions against Spain. The young Republic of the United Provinces would not be helped, in that case.",
	"I understand, monsieur. Farewell, and good luck to you as well.",
	"I see. And why are you still here? It looks like you aren't in much of a hurry!",
	"Monsieur, the dispatch you wrote has been captured. I was hit on the head and I was unconscious this entire time!",
	"Immediately go to the head of the port, with my order to show you which vessels left Tortuga in the past two hours. Find the ship, catch up to it, board it, and find the packet!",
	"I understand, monsieur. Thank you for your help!",
	"You've caught on well. Monsieur Lagrange needs to secretly enter Martinique. From there, he'll charter a ship to Dieppe. But he's sitting on a pile of gold, and everyone knows this. This is why there are some serous misgivings about his safe return to the Old World.",
	"Go off to the tavern. There, you'll find Lagrange. Your goal is to deliver him to the bay of Le Maren, in Martinique. Pierre will take care of thanking you, sir.",
	"Fine, monsieur. I will everything as you've said.",
	"Pierre",
	"Lagrange",
	"Well, then. I won't hold you at the moment, but I'll ask you not to disappear for too long out of my sight. I often have work for a filibuster.",
	"Fine, monsieur Governor-General. I'll drop by from time to time.",
	"Hmm. All of this is wonderful, but here's the rub: Lagrange himself is missing. Before leaving Fort de France, he was supposed to notify me, but there's been no letter and he himself has vanished into thin air. What do you think about this?",
	"I'm not up to date, monsieur...",
	"It's all so strange... All right then, sir, I don't want to deal with you any longer. Moreover, if I ever discover that you killed Lagrange... Well, I'd be at a loss for words to describe what would happen to you.",
	"I'm not holding you!",
	"I understand, monsieur...",
	"Did you hear? Captain ",
	" was thrown out of the residency of our governor-general due to some dark story dealing with Lagrange... He's no longer good for service.",
	"Yes, I'm familiar with that sad event. What a pity that Lagrange was unable to go back to living normally after all. What a pity...",
	"I knew him very little, but he seemed like a good kid to me.",
	"It really is so, monsieur ",
	". Now, then. It's sad that it turned out this way, but I'm grateful for your assistance. Which is why I'll ask you to come back from time to time. It's possible that there will be work for an filibuster.",
	"Fine, monsieur d'Ogeron. I'll come by your residency.",
	"One minute, sir! Return the money that Lagrange had on him. It doesn't belong to you.",
	"Hmm, monsieur...",
	"I'll never believe that you didn't take it. So return 1,200,000 coins to me, and I'll continue cooperating with you.",
	"Why so much? 1,200,000?",
	"Because I know how much money Lagrange had on him.",
	"And what should I do now?",
	"Until you return Lagrange's money in full, you'll have nothing to do in my residence.",
	"Fine, monsieur. Take it...",
	"I don't have that kind of money now. But I'll get it and bring it to you.",
	"Now, then. we're square. You can come by here, and I'll give you work from time to time, sir.",
	"Very well, Governor-General, sir.",
	"You know, Captain ",
	" was hired by the Governor-General to escort the glorious corsair Lagrange. And he's carried out this order with honor!",
	"Governor-General Peter Stuyvesant of Curacao is a personal friend, and a friend of the Republic of the United Provinces. So don't think about doing something funny over there. Otherwise, when you arrive at Tortuga, I'll skin you alive.",
	"Monsieur Bertan. I may be a filibuster, but do I look like the irresponsible type? Everything will be done in the best manner. Don't worry yourself.",
	"Well, then. Very good. Be on your way, sir.",
	"Goodbye, monsieur.",
	"Everything went well, without a hitch?",
	"Well, how can I put this... Not really. I was first arrested for some unknown reason, and then released...",
	"And for what could you have been arrested?",
	"I have no clue. I think because of my appearance. Though everything ended well, monsieur. So there's no cause for concern.",
	"Mmm, this is strange... Oh, well. I don't have any work for you at the moment, but drop by my residence from time to time.",
	"Fine, monsieur Governor-General.",
	"Did you hear? Captain ",
	" was carrying out the duties of the orderly of our Governor-General. And something strange, very strange, happened to him at Willemstaad...",
	"What happened, sir?",
	"Oh, monsieur, let's do this in order. First I was thrown into jail and they wanted to hang me, but I was freed on the morning of the next day.",
	"What did you do, that they should want to hang you? You were my orderly!",
	"They thought I was a bandit scout, living by robbing Dutch ships off Curacao. In the end, I found the band in question and finished them. They turned out to be Spanish privateers. How's that?!",
	"Spanish privateers?! Ha ha, that sounds verrrry convincing.",
	"It's good that you could show yourself at Willimstaad. I'm happy that I trusted my orders to such a meticulous filibuster.",
	"I won't dare to hold you any longer. Get some rest. But I'll ask you to show up in a week or two at my residency. I'll get some more work for you.",
	"Excellent, monsieur Governor-General. I'll be back without fail.",
	"Did you hear? Captain ",
	" was carrying out the duties of the orderly of our Governor-General. And something strange happened to him at Willemstaad. He was arrested! Though to the honor of France, he made it out. d'Ogeron is obviously pleased.",
	"There's a rumor going on about you, that you're a courageous bounty hunter. I know that, for you, the word honor is not an empty sound. I'll admit that it's not easy to trust you, but it appears that it would be the best course... My life is in your hands, and it's your choice to trade it for gold or to prove that you're a real knight!",
	"Damn it, anybody can say that I know how to slit throats, but not one would dare say that I'm a swine and traitor! I'm listening to you.",
	"You're probably aware that I ordered that girlfriends be delivered for our courageous filibusters. Now Tortuga is a haven for pirates, the fluids of love are everywhere, female laughter making the head spin... But alas, not everyone is tasting heaven's seeds.",
	"Amour has chosen not just the buccaneers as his target?",
	"I'm not at fault here. There's a lady who would be happy to breathe the free air of our colony, but is forced to sit controlled, lock-and-key, by a brutal spouse... To free her from the dungeon in which she sits is a job worthy of a cavalier!",
	"Thank the creator, you've finally gotten to the point. Who do I have to save?",
	"So you'll take this job? Excellent! The lady who I'm speaking about is the spouse of the commandant of Havana, Don Jose Ramirez de Leiva. You're to sneak into the city and find a way to get her out of there.",
	"To complete this task, I will give you a sixty-day Escorial Spanish trading license. With it, you may dock at Spanish ports and visit Spanish cities. Oh, and remember to make sure that your vessel hoists only a Spain-friendly flag.",
	"Here, take this ring. By it, Doña Anna Ramirez de Leiva will know that you are my trusted confidant. And remember that the honor of this noble lady is in your hands. ",
	"I understand perfectly, monsieur. I admit that this kind of task is new to me, but I am grateful for your trust and confidence... Fear not, I will not disappoint you.",
	"Blasting caps! I was counting on your knack and guile. What happened?",
	"Well, monsieur, that's just it: not much. I just couldn't get close to her. She is the wife of the commandant, after all...",
	"Hmm, that's too bad... Well, as this was my personal request to you, you still remain in good standing with France.",
	"Please come back and see me again. I may have more work for you.",
	"Understood, monsieur Governor-General.",
	"Rumor has it, Captain ",
	" failed a very important mission of love, from d'Ogeron...",
	"Nevertheless, please accept this modest reward.",
	"And for now... Just leave me the hell alone... if you could be so kind. I'm in no mood for administrative matters. Come back later...",
	"Understood, monsieur Governor-General. I'll be back...",
	"Rumor has it, Captain ",
	" gave a startling show of bravery and resourcefulness in returning to d'Ogeron his Spanish flame, Doña Anna...",
	"I know that you're a man of the sea, and no lover of bedroom gossip. But let me assure you, this task is right up your alley. Recently the motherland set afloat the most powerful and beautiful ship in the world - the Soleil Royal. His Majesty is very much interested in the safety of French colonies in the West Indies, and so, to our great honor, this ship was instructed to sail straight here.",
	"When will it arrive?",
	"It's already here, moored and anchored. Now it needs to sail to Dominica. And you are to escort that vessel there.",
	"I am to protect France's finest vessel? With my ship? Kind of strange, isn't it?",
	"Not at all. Two ships are always better than one, and you are a brave and capable seaman. Moreover, I have reason to believe that the Spanish are planning on hunting down the Soleil Royal. Even the strongest vessel may not withstand three or four well-equipped galleons and their boarding parties.",
	"Moreover, I know for a fact that these galleons are under the command of a certain captain Juan Galeno, and are currently at full combat readiness. You must do whatever it takes to ensure that our flagship does not fall into Escorial's hands. To your last breath, if need be. Bring me good news, or don't come back at all.",
	"A mortal charge... Look, I'm no coward, sir, but that doesn't sound too appealing!",
	"Point taken, Captain. I trust that a promise of a generous reward for a job well done will return some luster to the proposition?",
	"But why escort the ship to Dominica? I mean, it's just a desert island... ",
	"At Dominica, you are to meet with a squadron from Guadeloupe, provided by the Governor-General of Basse-Terre. ",
	"I see. Well, then I accept this mission.",
	"Excellent. All right, from here on, the Soleil Royal is under your command. Please go to the head of the port at once; he will register the captain of the Soleil Royal as your partner.",
	"We are about to set out, monsieur.",
	"I can't believe it... You deserted the Soleil Royal to save your own skin?!",
	"I had no other choice, monsieur...",
	"It's all perfectly clear. You, sir, are a coward of the first rank. I will ask you to leave my sight immediately. Perhaps in time you may regain my favor, but not, I fear, very soon!",
	"Very well, monsieur. I understand.",
	"I hear our Governor-General tossed you out of his residence for deserting the Soleil Royal in battle. Good riddance, you ask me...",
	"You weren't able to protect the Soleil Royal? Oh my, that is a catastrophe...",
	"Monsieur Governor-General, I did my best...",
	"Well, since you were unable to fulfill the simple task that was your charge, your best was obviously not good enough. You drown Spaniards by the dozens, but a job such as this is beyond you?! I am profoundly disappointed in you, and want no more sight of you!",
	"Now leave me!",
	"Very well, monsieur...",
	"I hear our Governor-General tossed you out of his residence for deserting the Soleil Royal in battle. Good riddance, you ask me...",
	"Hrm, those are unusual circumstances... Well, I must say that you made a wise decision. I congratulate you on yet another job well done. Here is twenty-eight thousand gold; please accept it as your reward.",
	"Thank you, monsieur Governor-General...",
	"Come see me in my residence, in a week or two. I may have more work for you then.",
	"Yes, sir. I'll be there.",
	"I hear that while in escort of the Soleil Royal, you were attacked by the Spanish. Allow me to express my sincerest admiration! You are a fine seaman, and a true warrior!",
	"That's the man. And mind, under no circumstances can this letter turn up in the wrong hands. At the slightest hint of trouble, you are to destroy the package. Don't even think of dying before you achieve its destruction. ",
	"You think there are people out to claim the letter?",
	"There are always strangers nosing around. You must go there immediately; Monsieur David himself will give you your reward.",
	"Very well, Monsieur Governor-General. I trust the reward will reflect the job.",
	"Bloody demon",
	"Francois",
	"Olone",
	"What happened?",
	"Monsieur Governor-General, Olone and I decided to take Cumana. That is... well, we took it, but then we had ourselves a little disagreement. One thing led to another, and, well... Sir, Olone is dead.",
	"Good grief... And who is this hero that dared to challenge Francois Olone?",
	"Your humble servant, monsieur...",
	"Oh my! Your hide must be wrought iron! Even the toughest of pirates consider Olone the devil incarnate.",
	"I can't say I'm thrilled about his death, but I won't cry over him either. Especially since disagreements like this aren't exactly rare within the Brotherhood.",
	"You got that right, Monsieur Governor-General.",
	"Well then, I shan't keep you. Right now I have no other work for you, but please stop in from time to time. ",
	"Yessir. That's exactly what I'll do.",
	"Rumor has it you disposed of Olone! Francis Olone himself! Land alive, what bravado! Or is it madness? Either way, it's sure something! ",
	"That's excellent news. Essentially the taking of Cumana; that was exactly what I wanted. What can I say but great work, my friend! I am very pleased with your efficiency.",
	"I thank you for the kind words, sir. And now, respectfully, I will take my leave...",
	"Yes, of course, I won't hold you from your affairs, Captain. But please, stop by my residence time to time.",
	"Yes, Monsieur Governor-General. ",
	"Word's going around that you and Francois Olone gave Cumana a real good pillaging. I guess the Spanish dons will be in he market for a load of new pants! That is, to replace the ones they've soiled... You see. ",
	"How did Olone react to the letter?",
	"He suggested a raid on Cumana. Unfortunately, I had to refuse. But with three ships in his squadron, I reckon he should be fine without me.",
	"Well, let's hope that my plan works out... I dare not hold you longer, sir. But remember to drop by every once in a while. I may need you again.",
	"Yes, Monsieur Governor-General. ",
	"The Spanish managed to capture a famous filibuster, name of Rock the Brazilian. Seeing as he plucked many a Spanish feather over his career, he should expect little mercy. However, before they introduce Rock to their gallows, they will surely try to extract from him where he hid all his Spanish plunder. But that's not the important part - ",
	"More important than gold?! Whatever could it be?!",
	"... Yes, well. The Holy Fathers of the Inquisition know how to loosen prisoners' tongues, and I'm afraid that the Brazilian will tell them not only of the gold...",
	"... but of the letters that are delivered, by your instruction, to Jean David...",
	"You're absolutely right. So we're in agreement: we need to act without delay. I've been informed that Rock was sent to a prison in Havana. You must find a way in there, and break him out as soon as possible, by any means necessary. I want the Brazilian before me, preferably in one piece.",
	"And if he should die...",
	"Then the Spanish will learn nothing... but then, neither will we. And if he lives, I have reason to believe that Rock will be quite willing to part with a grand share of his treasure, in gratitude for his rescue...",
	"A dicey proposition. But then, that's how I like 'em. I'll set out at once.",
	"Very well. Oh, and another thing - your operations in the city must be invisible and discreet. To this end, I will once again furnish you with a letter of credence from a Spanish trading company.",
	"Many thanks, Monsieur Governor-General.",
	"Rock",
	"the Brazilian",
	"It may be of no good to you, monsieur, but please don't speak for the entire New World.",
	"Ah, it's shame... A damned shame that you failed me, sir... I reckon I will no longer need your services. Still, you're welcome to drop by my residence, if you want. Who knows - maybe I'll have some work for you, after all...",
	"Yes, Monsieur Governor-General. ",
	"They say that Captain ",
	" failed to save Rock the Brazilian from the Spanish torture chambers. What a shame... The Brazilian was such a fine man...",
	"That's a shame... He was a fine captain, and a real man. A shame indeed...",
	"Oh well. I suppose you did all you could to save him. Anyway, please drop by my residence in a few weeks. I should have more work for you then.",
	"Yessir. I'll be there.",
	"They say that Captain ",
	" failed to save Rock the Brazilian from the Spanish torture chambers. What a shame... The Brazilian was such a fine man...",
	"Don't be so modest, Captain. Your fee for a job well done amounts to thirty thousand coins. Kindly accept it.",
	"Thank you, Monsieur Governor-General... ",
	"As always, I ask that you come by my residence from time to time. I expect that I will need your services before long. ",
	"Very well, sir. I will definitely visit you soon.",
	"They say that Captain ",
	" saved Rock the Brazilian from the Spanish torture chambers. What grand news! Rock is such a fine  man...",
	"For now, just go see the Marquis, at your earliest convenience. I don't know the details, but it looks like the job will be of the discreet variety.",
	"Well, it wouldn't be the first time. Fine, then; I'll be right there...",
	"Marquis",
	"Bonrepaux",
	"Captain, there's more to life than gold. Gold can never buy your honor, or grace, or the respect of men.",
	"That is true, monsieur...",
	"Well, I have no other burning request for you, but I shall be pleased if you visit me from time to time. Perhaps we will collaborate again in the future.",
	"Yes, sir. As a French noble, a baron, I will make it a priority to visit your residence more often.",
	"They say that Captain ",
	" is now a titled man. A baron, even! Ain't that something.",
	"Yes, baron. They have already attacked the buccaneer settlement of La Vega. And it looks like their next target is Port-au-Prince. ",
	"I see, sir. I guess I shall be off, then? ",
	"By all means. But before you do, I want to inform you that Soleil Royal has been placed under your command, in effort to strengthen your squadron.",
	"Under no circumstances, Captain, can you afford to lose this ship. Its demise will amount to abject failure of your charge. Moreover, you will never work for the French government again.",
	"Hrm, all right. I'll do wha I can to ensure that the magnificent Soleil Royal suffers no ill fate.",
	"Soleil Royal",
	"That's right, Baron, and it was brilliant. Now, the French government made some monetary provisions for repairs and replenishment. Here is five thousand gold. Please accept it, in the name of France...",
	"Just five thousand? ¡Caramba! That's less than nothing!",
	"Baron, this war is taking its toll and our resources are stretched beyond thin. Please understand our situation - our deficit is disastrous. I must therefore ask that you accept the situation for what it is.",
	"I dare not hold you longer - you must prepare for more combat. But remember that France needs you!",
	"Ho! Well, if France needs me, then she will have me. Sir, I will return to your residence as soon as I settle my own affairs. Until then, farewell.",
	"They say that Captain ",
	" saved the citizens of Port-au-Prince from the Spanish!",
	"But Captain, you lost the Soleil Royal! That is absolutely inexcusable!",
	"I've done all that was in my power...",
	"Yet clearly that was not enough! Sir, losing that vessel leaves France with no choice but to reject your services altogether. Goodbye.",
	"After all I've done for France?! Well then, sir, I guess farewells truly are in order. I'm rather sick of working for you myself...",
	"Rumors say that our Governor-General threw you out of his residence for managing to let Soleil Royal drown in battle. Well deserved, if you ask me...",
	"Bloody hell! You, sir, are a grade A coward! I want nothing to do with you. Goodbye, Baron...",
	"Farewell, sir. Please send my warmest regards to Marquis Bonrepaux...",
	"Rumors say that our Governor-General threw you out of his residence for deserting Soleil Royal in battle. Well deserved, if you ask me...",
	"What the hell?! But it's only two days' travel from here! Alright, listen, I want nothing to do with you. Goodbye, Baron...",
	"Farewell, sir. Please send my warmest regards to Marquis Bonrepaux...",
	"Rumors say that our Governor-General threw you out of his residence because you failed to make it to Port-au-Prince in time to help the city defend against the Spanish attack. As a result, the city was badly pillaged. If you ask me, you deserved it!",
	"It's high time we give a proper response to the attempt to capture Port-au-Prince. In my opinion, the optimal response will be the realization of the Spanish plan to capture Hispaniola - the plan's mirror image...",
	"Monsieur Governor-General, could you take the gaudiness down a notch and be out with it?",
	"Very well, Baron, if you insist. I want you to capture Santo-Domingo! Then all of Hispaniola will be controlled by a single empire, and that empire will be France, not Spain. Now do you understand me?",
	"I do, sir. Now, about financing for such a large military operation... I hope you realize that I can't maintain Soleil Royal and wage a war all at my own expense!",
	"Yes, I realize that. Your question is easily answered. After capturing Santo-Domingo, you shall receive a rather hefty reward.",
	"If you say so, sir, I will trust you on that. Alright, I will commence the operation at once. Wait for me and news of success.",
	"You lost Soleil Royal!",
	"The battle was intense, Monsieur Governor-General. That magnificent ship was sunk as a result. I truly am sorry...",
	"Your apologies are worthless. Losing this ship is a terrible tragedy for France. Hence, I no longer want to do business with you, nor will the French government ever trust you with another task. Goodbye.",
	"Hrm. Well, sir, that's your decision.",
	"Rumors say that our Governor-General threw you out of his residence for managing to let Soleil Royal drown in battle. Well deserved, if you ask me...",
	"Excellent, my good friend, simply magnificent!",
	"Now let's talk about something that's of some importance to you - your reward. To  finance your expedition, I was able to beat out an unprecedented chunk of change from the war budget - 40,000 gold... They're yours, Baron!",
	"Excellent, Monsieur Governor-General. Now we're talking!",
	"I'm happy that you're happy... Well then, I dare not keep you longer. Please attend to your preparations. Bring your squadron back in working order and come back to see me in about a month, Baron.",
	"Yes sir, Monsieur Governor-General. I'll be there.",
	"They say you captured Santo-Domingo! Excellent work, Captain, simply magnificent!",
	"That's right, sir.",
	"I see... So which city is next in line to become property of France?",
	"Santa-Catalina on Mein. That city controls the pearl trade on the western coast of the New World. The French government reckons that a healthy slice of the pearl trade can do wonders for our economy...",
	"I completely agree with the French government, and am prepared to undertake this operation. I shall set out immediately.",
	"Damn it! That's terrible news. Losing that ship makes any future collaboration between us impossible.",
	"Is it really so precious to you?",
	"It's not even about me. Soleil Royal was the pride of the French royal fleet. It was the masterpiece of naval architecture, and we trusted you with it, counting on your talent and experience as a sea captain. You did not justify our trust, and that is why I must refuse any future collaboration between us.",
	"Well, if that's how it is... To be honest, I'm pretty tired of jobs without any sort of budget myself. Goodbye, sir.",
	"Rumors say that our Governor-General threw you out of his residence for managing to let Soleil Royal drown in battle. Well deserved, if you ask me...",
	"Brilliant! Yet again, you have more than justified our trust in you and your abilities.",
	"Monsieur Governor-General, what about financing the operation?",
	"All trophies captured in Santa Catalina shall be yours by right.",
	"Monsieur, I wanted to talk about my role in the development of the pearl trade...",
	"Sir, that's impossible. This matter is managed by Jean-Baptiste Colbert, the Prime Minister of France! And Baron, it is rather unseemly to think about financial gain when all of France is going above and beyond the call of duty in a time of war.",
	"Hmm, I guess you're right, sir...",
	"I'm very happy that we understand one another. Baron, I dare not keep you longer. Please bring your squadron in working order and be ready for new feats of heroism for the good of France and our beloved Sun-King!",
	"Monsieur Governor-General, your request shall be completed. Until we meet again.",
	"Rumors say that you've captured Santa Catalina, and then tried to get yourself a slice of the pearl trade from d'Ogeron. As if that'll ever happen...",
	"You played an important role in this victory. Essentially, it was you who brought about the decisive collapse of the Spanish forces in the Caribbean Sea.",
	"Jean-Baptiste Colbert recognized your achievements in his report in the Louvre. Now Louis XIV himself knows your name!",
	"That makes me very happy. Tell me, Monsieur, are there any monetary bonuses for being on the winning side of the war?",
	"I don't know anything about that, but Marquis Bonrepaux can answer for you. Coincidentally, your next mission is to get to Basse-Terre on Guadeloupe and meet with the Marquis. He's waiting for you.",
	"Excellent, Monsieur! I shall not waste this chance... I'll set out immediately.",
	"Don't forget to bring Soleil Royal back in working order - it needs ",
	"Yes, sir.",
	"Marquis",
	"Bonrepaux",
};
