string DLG_TEXT_GUB [407] = {
	"What questions?",
	"What do you want?",
	"I've changed my mind...",
	"I've got nothing to say now.",
	"I'm listening to you.",
	"Lord Governor-General, I've been ordered to deliver this letter to you.",
	"You again? Another packet from Tortuga?",
	"Not this time, Monsieur Governor-General. I have good news for you.",
	"I want to ask about one person. Be so kind as to answer me.",
	"You're on duty for the Republic of the United Provinces! I ask you to immediately carry out the task that you've been assigned!",
	"I won't hide that a lot is riding on the success of your actions. So carry out the duty that you took upon yourself!",
	"I'm waiting for your report of the task with which I entrusted you, not incoherent prattle.",
	"I'll begin immediately, Mynheer.",
	"I'm in the process of completing it...",
	"At the moment, I don't have any crucial tasks for you. You may show up at my residency later...",
	"I'll ask you to excuse me. I'm very busy at the moment!",
	"Focus on your privateering tasks. I've got no missions for you now.",
	"Fine, Mynheer.",
	"I've got a new task for you. It's imperative that you go to Fort Orange and buy a lot of coffee and wood - ebony and mahogany, and sandalwood meant for Curacao. Leave immediately. Here are the required papers for this job; give them to the commandant of Fort Orange.",
	"Buy, you say? ",
	"I must inform you that we're in a state of war with England. Another trade war has started.",
	"So that's how it is...",
	"We've gained valuable information. Modyford doesn't have enough strength to give us any serious trouble in Curacao. Yet the poorly defended Fort Orange, located right next to their Jamaica - they want to destroy it.",
	"Yes, Mynheer, I'm aware of that.",
	"You're were unable to properly execute the previous task. Instead of you, this task was handled by more clever fellows. I'm giving you a chance to make up for it now. As a result of the information we've gained, I've come to the conclusion that Modyford doesn't have enough strength to give us any serious trouble in Curacao. Yet the poorly defended Fort Orange, located right next to their Jamaica - they want to destroy it.",
	"Understood...",
	"Now, then. You've got the following task: escort three loaded freights in the buccaneer's settlement of La Vega to Edward Mansfield.",
	"I understand, mynheer.",
	"Here you are. I've been waiting for you.",
	"At your service, mynheer.",
	"I've got a serious mission for you. I've got to get this dispatch to Governor-General Bertran d'Ogeron of Tortuga. This is connected to our plans in the War of Devolution, between France and Spain. This correspondence is top secret, so you must understand how much I trust you. This correspondence must go to the Governor-General of Tortuga, and no one else. This is imperative!",
	"I understand, Mynheer. It shall be done just as you ask - Monsieur d'Ogeron will receive this dispatch personally.",
	"I've got personal favor to ask. My friend, the head of the Jansenist society on Curacao, who you've brought to the island, asks me to send him an able officer. I have no one in mind before you as a candidate. His request is tied to searching for something that he needs very much. In general, Aaron will tell you everything himself. He's at his house now. Visit him.",
	"I understand, Mynheer. I'll be off to him immediately.",
	"We've been experiencing some serious difficulties, building line ships with high displacement on our European shipyards. Shallow harbors, you know... I was mulling over this sad fact yesterday, when a genius thought popped into my head!",
	"And what was that, Mynheer?",
	"Damn it, ",
	", you were right. You suggested that we leave the squadron we acquired here, in the Caribbean...",
	"What's happened, Mynheer?",
	"Here you are! I was awaiting your arrival at the residency.",
	"What's happened, Mynheer?",
	"I'll hurry to tell you the Spanish city that will be attacked. It's Maracaibo. The inhabitants of the city must swear loyalty to the Republic of the United Provinces! ",
	"A good choice, Mynheer.",
	"Well, then. I've got a rather important mission for you in the city. I think you'll be up to the task.",
	"Here's the deal: there's been a lot of Protestants arriving from Europe to Curacao, mostly from Flanders and Burgundy, where the Inquisition is raging. The followers of Jansen have also arrived recently. To lead the Jansenist society, Aron Mendes Chumaceiro, an influential Jansenist, has arrived on San Martin, on a French shuttle coming from Holland.",
	"He's a known merchant, and an old acquaintance and great friend. Be off  to Marigo, and bring him to me. The local Jansenist community really needs him.",
	"Allow me to ask, who are the Jansenists?",
	"Well, then. Aaron has told me everything. Good work, Mynheer. Stop by me now and again. I think I'll be using your services from now on.",
	"Yes, Mynheer.",
	"Did you know that our Governor-General Stuyvesant hired Captain ",
	" to bring his friend from Marigo here, to Willemstaad? And, you know, the task was successfully completed.",
	"Now, then. Captain, what brings you to Curacao?",
	"I'm carrying out your order to bring cargo from Fort Orange, Mynheer.",
	"I asked you to bring the whole lot in 60 days. You didn't make it...",
	"Right, I couldn't make it in time. There were some serious problems with the wind...",
	"Here you are at last! Tell me immediately what you've discovered.",
	"Mansfield doesn't know a thing about Modyford's plans. But I've discovered that Modyford tried to get corsairs to attack Curacao. In that case, it's possible to presume that the order to begin military operations against the Netherlands in the Caribbean Sea has been received.",
	"Here you are at last! Tell me immediately what you've discovered.",
	"Mansfield doesn't know a thing about Modyford's plans. Corsair admiral Henry Morgan presumes that there's been an order to attack Dutch settlements.",
	"What have you discovered?",
	"Modyford's readying an attack against Fort Orange. There are preparations for attack going on by the garrison at Port Royal. Modyford tried to talk the corsairs into attacking Curacao, but nothing came as a result. So Modyford doesn't have the strength for a bigger operation than the storm of Fort Orange.",
	"Report, what's going on with Fort Orange?",
	"Mynheer, I couldn't come to the help of Fort Orange. The luckless inhabitants have been slaughtered. The Dutch settlement of Fort Orange no longer exists...",
	"Report. What's going on with Fort Orange?",
	"Mynheer, I couldn't come to the help of Fort Orange. We gave battle, but the English turned out stronger. We had to save ourselves and run... Unfortunately, the Dutch settlement of Fort Orange no longer exists...",
	"Report. What's going on with Fort Orange?",
	"Mission accomplished, Mynheer. All the English ships and landing craft have been destroyed in their attempt to break into the city. Nothing threatens it any longer.",
	"Report, what's going on with Fort Orange?",
	"Mynheer, I was able to destroy the English ships at sea. But, unfortunately, I was unable to resist the land forces of the British. Fort Orange is destroyed...",
	"I've already heard that you were unable to save the fleets entrusted to you. Moreover, you've fled the field of battle!",
	"Mynheer, at the shores of Hispaniola I was attacked by an entire Spanish squadron! Our forces were no match for them...",
	"Report, what's happened with you?",
	"Mynheer, at the shores of Hispaniola I was attacked by an entire Spanish squadron! But I was able to retain the ships entrusted to me.",
	"I've already heard that you were unable to retain the fleets entrusted to you. This is very bad.",
	"Mynheer, at the shores of Hispaniola I was attacked by an entire Spanish squadron!",
	"I'm so glad to see you. What news? What can you tell me?",
	"Well, what can I say? I wouldn't envy the city of Santiago and its governor!",
	"Report the results of your mission.",
	"I successfully delivered your dispatch to d'Ogeron.",
	"Report the results of your mission.",
	"I successfully delivered your dispatch to d'Ogeron.",
	"Well, then. We're very much in luck. d'Ogeron, the clever fox, was smart enough to encode the letter in a method known only to me. So the Spanish can't prove anything directly.",
	"Thank the Lord!",
	"I haven't received news from d'Ogeron yet. Come back later.",
	"Yes, Mynheer.",
	"Chumaceiro brings word that you were unable to complete his order.",
	"Well, yeah. I did what I could.",
	"My friend Aaron and his society are in religious ecstasy. He's told me that you've managed to do something very important for him. Tell me, what was it?",
	"I just found him a lost item. Some old book. An ancient Christian tract.",
	"Sooo, what do say about your mission? How's the capturing of ships?",
	"As of yet, I haven't captured anything worthy of your attention. But I'm working on it, Mynheer...",
	"Not bad, Mynheer. I'm ready to turn over ",
	" ships.",
	"Not bad, Mynheer. I'm ready to turn over a ship.",
	"Wonderful, Mynheer. The mission is completely finished.",
	"I saw everything! It's was simply wonderful!",
	"Thank you. My participation in the battle was certainly humble...",
	"Report. Were you able to protect San Martin?",
	"Mynheer, I did everything I could, but I was too late... Marigo is now a Spanish city.",
	"Report, were you able to protect San Martin?",
	"I did it, Mynheer. The siege of the Spanish fleet of the city of San Martin has been lifted. The Spanish have been vanquished.",
	"I've already been informed of your brilliant victory, my friend!",
	"Mynheer, I was able to capture Maracaibo. Now it's a Dutch colony.",
	"I don't deal with men who break their word. I've got nothing more to say to you.",
	"Act independently, in the interests of the Netherlands. I'm counting on your sound reason.",
	"Fine, Mynheer.",
	"An offshoot Christian movement, if you're interested.",
	"It began with a theological tract about Augustine, that Jansen wrote in 1640. The Jesuits underline the closeness of the Jansenist doctrine to that of the Protestant dogmas, and persecute the followers of this religious movement. Louis XIV has also declared the Jansenists illegal.",
	"The establishment of the society here, under my watch, is a rather big step for developing Dutch colonies in the Caribbean. The thing is that the majority of them are nobles, officers, bourgeoisie and big merchants. People like that will not be a burden in the least.",
	"Well, then. If you're ready, I'll ask to begin this mission immediately.",
	"I'm ready, Mynheer. Wait for me. I'll soon return.",
	"I'm sorry, but I'm very busy at the moment. I'll be ready to carry out your mission later.",
	"Aaron Mendes",
	"Chumaceiro",
	"That's right, purchase. Orange is giving us very good prices for these purchases. As soon as you give my trusted deed to the governor of the fort, you'll get the reduced prices.",
	"The lot ready for you contains 400 units of every designation. The prices for you will be ten times below market value.",
	"In line with my calculations, I am issuing you 17700 gold for the purchases. Please receive it.",
	"If you've been calculating this operation, then won't you tell me how much everything will be in metric centners? I need to plan the shipping.",
	"Of course I'll tell you. All in all, the weight of the entire shipment will be 5600 metric centners.",
	"Hmm. That's not a little. You know, Mynheer, I'm a free captain. And this transportation business just isn't my cup of tea...",
	"Because you're, as they say, a free captain, I'm asking you to complete this mission. I need everything safe and sound, and it seems to me that only a free captain can guarantee it safe and sound.",
	"There are Spanish darting around. The English aren't showing us any friendly feelings. Pirates are all over the place... So I ask that you understand me correctly...",
	"I won't accept your refusal of this mission. Begin! And remember that I need the whole lot - all 6800 metric centners - here, in Willemstaad, in no later than two months.",
	"Hmm. Ah well... All right, Mynheer. I'll do everything. You don't leave me much choice.",
	"I'm very happy that you've agreed to it. Well, then. I'm waiting for you to show up with the cargo.",
	"Goodbye, Mynheer.",
	"Mynheer, I've brought the following items.",
	" Ebony - ",
	" units",
	" Coffee - ",
	" units",
	" Mahogany - ",
	" units",
	" Sandalwood - ",
	" units",
	"Tell me what, and how much, you've brought from Fort Orange.",
	"Mynheer, I've brought the following items.",
	"Mynheer, I'm in the process of carrying out the work. I have brought nothing yet. I'll ask you to excuse me...",
	"Now, then. Let's add everything up.",
	" You have completely finished transporting the shipment of ebony.",
	" I'm taking from you ",
	" units of ebony.",
	" You've delivered the full lot of coffee.",
	" I'm taking from you ",
	" units of coffee.",
	" You've delivered the full lot of mahogany.",
	" I'm taking from you ",
	" units of mahogany",
	" You've delivered the full lot of sandalwood.",
	" I'm taking from you ",
	" units of sandalwood.",
	"Very good, Mynheer.",
	"You've completely finished the deliveries. That's good. However, my task required you to deliver the entire shipment within two months. You have been unable to do that.",
	"Mynheer, the task was not a simple one. I didn't have enough ships with enough room to transport things quickly enough...",
	"You've finished the shipment. Moreover, you've accomplished it in the alloted time! I'll let you know that receiving this shipment in time was quite important for Curacao.",
	"I'm glad that I was able to complete this mission in the best way.",
	"I'll ask you to finish what you start. I need the entire lot from Fort Orange, up to the last centner.",
	"Fine, Mynheer. Everything will be delivered to Willemstaad.",
	"completed",
	"completed",
	"completed",
	"completed",
	"I understand, and you must understand as well, that I'm working on global plans and I absolutely need my plans to be carried out to the letter./n",
	"Due to the above-noted reason, the size of your reward for the finished merchant operation has been greatly reduced.",
	"I couldn't possibly issue you more than 15000 gold.",
	"Hmm. Heh. Mm... Well, then. Thanks for that, anyway...",
	"Always at your service, Captain. Stop by from time to time. It's always possible I'll have work for you.",
	"Fine, Mynheer.",
	"You heard? Captain ",
	" took on a merchant mission, delivering items from Fort Orange. He finished the mission, but not in time.",
	"Now, then. The reward for successfully completing this mission will 75000 gold. You'll agree that this is a reasonable reward.",
	"Of course, Mynheer...",
	"Wonderful, then! I'll ask you to leave me now. Business and all... Come back and visit me in a few days.",
	"Fine, Mynheer. I'll try.",
	"Did you hear? Captain ",
	" took on a merchant operation, delivering items from Fort Orange. He completed the mission, and did it fast to boot!",
	"The epicenter of the war is on the shores of Europe and in the Indian Ocean. But even here, in the Caribbean Sea, this war will have an influence. ",
	"I require accurate and completely authoritative information about the English plans. On the island of Hispaniola, there's a buccaneer settlement, filled mostly with Frenchmen - though there's a sizable number of Dutch as well. Now, then. The head of the buccaneers is Edward Mansfield.  \n",
	"He's Dutch; his name been redone in the English manner. His real name is Edward Mansvelt. Edward is the trusted man of Governor-General Sir Thomas Modyford in matters relating to the robbery of the Spanish.",
	"Hm. Interesting...",
	"Your mission is as follows: deliver this letter to Mansfield. The letter contains a request for help. Convince him to tell you what he knows about the English plans. We must know what they plan on doing.",
	"I understand, Mynheer. I will carry it out now.",
	"Report.",
	"Well, there really isn't much more to report. That's it.",
	"So it turns out that all you have is speculation. Nothing concrete. Did you learn anything about the exact plans of the English?",
	"No, Mynheer. I was unable to learn anything concrete. ",
	"You weren't up to the mission. I'll have to get other, more meticulous people to finish this mission. All I have now is lost time. I'm very disappointed in you.",
	"Mynheer, I ask that you give me a chance to redeem myself.",
	"Not on this case; too much time has been lost. Still, stop by from time to time. I may have something that fits you.",
	"Thank you, Mynheer.",
	"There are rumors going around that Captain ",
	" ruined some secret mission for Stuyvesant, dealing with big politics...",
	"Wonderful! Now I know everything I needed to know. Come back in a few days, and I'll decide what measures I should take to counteract this threat from the English... You've worked well. Your reward consists of 50,000.",
	"Thank you, Mynheer.",
	"There are rumors that Captain ",
	" was able to discover the English plans for a new war.",
	"Immediately go to Fort Orange. You must be in time to intercept an English expeditionary force, or our settlement is finished. They'll destroy the fort, and imprison everyone. Leave right this minute. You must know that a lot is riding on your promptness.",
	"I understand, Mynheer. I'll be off to him immediately.",
	"I understand, Mynheer. Thank you for the confidence. Be sure that I won't let you down this time! I'll be off immediately.",
	"Damn it! You were unable to protect the citizens of the Republic of the United Provinces from the bloodthirsty English. This is very bad. Our already meager presence in the Caribbean region has been completely weakened.",
	"I'm very sorry. I did all that I could...",
	"Well, then. Be that as it may, I'll ask you to stop by from time to time. It's possible that I'll have some task for you.",
	"Yes, Mynheer. I'll definitely come and see you.",
	"They say that they couldn't protect the luckless inhabitants of Fort Orange from the English. Mmm... Yes, such a pity...",
	"Splendid! I am very happy that you've proven yourself so well in such a dangerous situation. Your reward for this job is 100,000 coins. Oh, and please come back to see me a little later. I should have another job for you.",
	"Very well, Mynheer. I'll be back in your residence a month from now at the latest.",
	"People say it was you who defended the residents of Fort Orange from the British. Allow me to express my sincerest admiration!",
	"Ah, damn it! Half the job was already done - you only needed a little bit more to save those poor residents of the fort!",
	"That is true, Mynheer. I had no strength left for a ground assault. I'm sorry...",
	"Yeah, that's a real shame... Those poor residents of Fort Orange...   \nWell, despite the regretful outcome of this mission, I appreciate your effort, so don't worry - I'll continue giving you work.",
	"I understand, Mynheer. And I appreciate it.",
	"People say you crushed the British squadron by Fort Orange, but they bested you on the ground. That's a real pity...",
	"That's not all. You are promoted to squadron commander. Your competence now includes selling cargo at the filibuster store and buying provisions from them. Their carcasses are prepared in bulk; nonetheless, they are still pretty good quality. Naturally, in order for the deal to end up favorable to us, you need to make sure that all the flutes reach the shores of Hispaniola safe and sound.",
	"I understand perfectly.",
	"Get moving then. But don't rush - it's best to act carefully. Remember, you need to deliver 7,000 centners of supplies to me. The head of the port will transfer the flutes over to you.",
	"Fine, Mynheer.",
	"I can't deal with a captain that ended up being such a coward! Leave my sight at once. I am extremely disappointed in you.",
	"Very well, Mynheer. But I just want to say that I'm very sorry...",
	"Rumors say that our Governor-General threw you out of his residence for being a coward!",
	"Splendid! I expected nothing less. Now tell me, did you bring me the 7,000 centners of supplies that I needed?",
	"Yes, Mynheer, it has been done.",
	"Mynheer, I wasn't unable to do it. I delivered a total of ",
	" centners of supplies.",
	"Not only are you a good fighter, you're an assiduous manager as well. I am grateful to you for successful execution of such a dangerous operation. Your reward amounts to 60,000 coins - please take it. And please hand in the delivered supplies.",
	"Thank you, Mynheer.",
	"Well then, I'm expecting you in several days.",
	"I understand, Mynheer. Before I go I must apologize for being the bearer of bad news - Edward Mansfield was killed during the Spanish attack on the buccaneer settlement.",
	"Damn it, what terrible news! Well, thanks for letting me know, my friend. Too bad about Mansfield though...",
	"Yes, Mynheer. He was a good man... I will take my leave now.",
	"Well, you're a good fighter, no doubt about it.  But you're not a very assiduous manager. Still, I'm grateful to you for a generally successful operation. Your reward amounts to 20,000 coins - please take it. In return, I shall seize the delivered supplies. ",
	"Fine, Mynheer.",
	"Are you joking? Where's the rest of the supplies? I see that I'm dealing with a scam artist! Well, you can forget about your reward.",
	"No, Mynheer, I did all I could to complete the task properly! This is all I was able to bring back...",
	"Is that even an excuse? I trusted you with Dutch ships and a simple task, which you were unable to complete. Leave my sight and never come back!",
	"Very well, Mynheer. I will leave, but I don't feel that this is in any way my fault.",
	"You've probably tried your best. Who knows... Maybe I will find a job for you eventually, but not right now...",
	"I understand, Mynheer. Before I go, I must apologize for being the bearer of bad news - Edward Mansfield was killed during the Spanish attack on the buccaneer settlement.",
	"Bloody hell! Haven't I had enough bad news for one day?! Still, thank you for letting me know. It's a shame about Mansfield...",
	"Yes, Mynheer. He was a good man... I will take my leave now.",
	"People say you brought news of Edward Mansfield's death. The old man's passing is a real shame...",
	"The Spanish attack on the buccaneer settlement, together with Mansfield's death, will have a crucial effect on the balance of power in the Caribbean. I'm not certain as to what we can or should do about it.",
	"It won't surprise me if the Coastal Brotherhood decides to take matters into their own hands and avenge the death of such a respected filibuster. Hell, it wouldn't be the first time they did it. Therefore, we need to coordinate our actions.",
	"Pay a visit to Henry Morgan and find out what their plans are. If Morgan decides that he wants to use you in their operation of retribution, you have my permission to assist them.",
	"Very well, Mynheer. I will gladly aid such a noble cause.",
	"Okay... Continue.",
	"Morgan asked me to conduct a recon mission. As a result, I discovered that Governor Jimenez will be in the city in the near future. Santiago's fate is sealed.",
	"That's good, but... Morgan didn't want to use you in the assault on the city?",
	"No, only the British will participate in the direct assault, seeing as we cannot join our squadrons for obvious reasons.",
	"That is true. Well, it's all for the best, as they say. The important thing is that Mansfield will be avenged - he was a good man and a worthy citizen of his country.",
	"I agree completely, Mynheer.",
	"For the successful completion of this task, you will be given a reward in the amount of 20,000 coins. Please come back to see me in my residence some time later. I should have more work for you then.",
	"Fine, Mynheer.",
	"Rumors say that you carried out a successful reconnaissance mission on the Spanish... My congratulations to you. ",
	"If you find yourself under attack, you must destroy this package immediately, irregardless of the battle's presumptive outcome.",
	"Very well, Mynheer. I shall set out at once.",
	"Excellent! I'm quite happy with the situation's pleasant outcome.",
	"Hrm, it may not be quite so pleasant, Mynheer. The thing is, Monsieur d'Ogeron responded to your dispatch with one of his.",
	"And what's so unpleasant about that? It's alright. Give it here.",
	"Umm... Well, the thing is... It was stolen from me at Tortuga.",
	" I chased after the thieves' brig, but was unable to retrieve the dispatch.",
	" I chased after the thieves' brig and sunk it, but was unable to retrieve the dispatch. Where it is now, I can only guess.",
	" I chased after the thieves' brig and boarded it. Once we captured it, the brig's captain told me that the attack was orchestrated by the Spanish. The dispatch itself was no longer on the brig - it has already been passed into the hands of the Spanish.",
	" I chased after the thieves' brig and boarded it. Once we captured it, the brig's captain told me that the attack was orchestrated by the Spanish. I went after the Spanish galleon that was heading in the direction of Santa-Catalina. I was able to catch up to the galleon and sink it, but I could not find the dispatch. Where it is now, I can only guess.",
	"What?!",
	"I'm very sorry, Mynheer...",
	"Do you realize what you've done?!",
	"I think so, Mynheer...",
	"Alright, now you listen carefully. You are not to even come near my residence until I find out the contents of d'Ogeron's dispatch. And you better pray that it doesn't contain any... 'privileged' information.",
	"I understand, Mynheer. Once again, I am truly sorry...",
	"Get out of my sight!",
	"Fine, Mynheer.",
	"I hear that Captain ",
	" was practically thrown out of Governor-General's residence...",
	"And that's God's honest truth! Now, I will ask you to leave me as I've nothing else for you. Perhaps I'll have some work for you in the future, but not right now.",
	"Very well, Mynheer. And thank you.",
	"Excellent! I'm quite happy with the situation's pleasant outcome.",
	"Yep, more than that even. The Spanish attacked me right at Tortuga - can you imagine?!",
	"Whoa, really?! And what happened?",
	"They were after d'Ogeron's dispatch that he sent in response to yours.",
	"Do you still have it?",
	"Why, of course, Mynheer. Here it is, safe and sound.",
	"My gratitude and appreciation, for your bravery and skill knows no bounds. You have quite possibly prevented a major political crisis in Europe.",
	"Monsieur d'Ogeron outlined the situation for me, I understand your meaning.",
	"I am happy to inform you that your reward for successfully completing the mission amounts to 150,000.",
	"That's wonderful, Mynheer! Thank you.",
	"I'm expecting you soon. I reckon there'll be plenty of work for an officer such as yourself.",
	"Certainly. I will visit you periodically.",
	"I hear that Captain ",
	", acting as of Stuyvesant's courier, found himself a lot of trouble. The Spanish suddenly attacked him right in Tortuga, and he still came out victorious from the battle!",
	"But it wasn't enough. I am shocked by your failure - you couldn't perform the simplest of tasks! Anyway... You can come by to see me from time to time, if you want. Maybe I'll find something that you may actually be able to do.",
	"Fine, Mynheer.",
	"I hear that Captain ",
	" accepted a rather strange mission - the search for some mysterious Biblical treatise. Well, he accepted the job, but couldn't get it done...",
	"Ahh, I see... Well, that's great. I trust he thanked you properly?",
	"As proper as it gets, Mynheer.",
	"Wonderful. Well, that's that. I don't need you for now, so you can attend to your business. Please come see me in a few weeks. I should have more work for you then.",
	"Always at your service, Mynheer.",
	"I hear that Captain ",
	" accepted a rather strange mission - the search for some mysterious Biblical treatise. They say he found it, too!",
	"If we can't build large vessels, we'll capture them!",
	"Brilliant and simple, like all that's genius...",
	"Hmm, you're right... Alright, I want you to provide at least four first-class ships at the disposal of the Dutch fleet. Of course, I'm talking about man-o'-wars.",
	"Hmm... not bad, I should think.",
	"I think so, too. Capture at least four ships, bring them into Willemstad's port on Curacao, and hand them over to me personally. For each ship that you hand over, we will pay you 50,000 coins. Do you think you can handle this job?",
	"I think so.",
	"Let's not delay, then. Begin immediately.",
	"Very well, Mynheer. I shall set out at once.",
	"Excellent, but the task is not yet fully complete. You still need to provide the fleet with ",
	" ships. Don't delay; I'll be waiting for you to bring me the good news.",
	"Excellent, but the task is not yet fully complete. You still need to provide the fleet with one ship. Don't delay; I'll be waiting for you to bring me the good news.",
	"Understood, Mynheer; I'll do exactly as you say.",
	"Great! I'll give an immediate order to send the captured ships to the Indian Ocean.",
	"Why there, Mynheer, if I may be so bold to ask?",
	"Because in that very region, our interests are opposed by Portugal, and the Portuguese have been gaining momentum recently. I reckon that this squadron will help restore some much-needed parity.",
	"Well, that's your decision, of course. But personally, I wouldn't be too ecstatic about the current situation here in the Caribbean either.",
	"What do you mean?",
	"Don't you think that the ships may be more useful here? To provide additional protection to the Dutch settlements, for instance.",
	"What? Heh, don't you worry about Dutch settlements - they'll be just fine. There's no threat in the Caribbean we can't handle.",
	"Very well, Mynheer. Though to me, this kind of peace seems deceptive. After all, Holland is still in a state of war with England, is it not?",
	"The active phase of military operations has passed. Plus, with the current English-Spanish conflict, we're the last thing on their mind right now. At any rate, who died and made you an expert on political science?",
	"I merely expressed my opinion...",
	"Which I will certainly take into account. And now I will ask you to leave me, but be sure to come see me soon.",
	"Fine, Mynheer.",
	"Captain, you've captured so many battleships that it's making my head spin!",
	"I was informed that a large Spanish squadron is approaching Curacao. I don't know whether we can withstand their attack... I wish I knew how Spain was able to amass such a force in the Caribbean waters, and in such a short time to boot!",
	"Anyway, we'll have time to think about that later if we manage to survive. Meanwhile, I will ask you to apply all of your knowledge and skills to helping the fort and the defending squadron repel the attack. There's no doubt in my mind that without your help we'll be crushed.",
	"I'll do all I can to prevent that from happening. Don't worry, sir, we'll live to fight another day.",
	"Well then, I'm counting on you!",
	"See you after the battle.",
	"I have a very different opinion on the matter - that your role in the battle was decisive! And while I'm sure that money isn't your primary concern, please accept this reward of 200,000 coins and our eternal gratitude for saving our city.",
	"Oh my, that's... Mynheer, I don't know if I deserve such a...",
	"I don't want to hear another word! The Netherlands knows how to thank its heroes and encourage them to perform more heroic deeds. Not another word! But this isn't over - now we need to gather information as to why the Spanish attacked Curacao. Please come and see me in a few days. ",
	"Very well, Mynheer. I'll be back when you ask.",
	"You saved us, Captain! You had to be brilliant to repel such a powerful attack, and you were!",
	"So it finally happened. Looks like our game of 'help the French' played us into a corner...",
	"What do you mean by that, Mynheer?",
	"I'm sure you are aware that Louis XIV is fighting a devolutionary war with Spain for his so-called 'Spanish heritage' - Flanders and Burgundy. And though these territories aren't part of the Republic of United Provinces, they are nonetheless culturally and ethnically related to Holland. For this reason, we have been helping the French in this war any way that we can - I'm talking about the financial aspect of it, naturally.",
	"And it looks like Spain has decided to rid the equation of the golden goose, thanks to which, Louis has been able to cover a good portion of the war's expenses. A calibrated move, I must say, seeing as without our money, France's dire financial state will hardly allow Louis to continue paying for this war.",
	"I found out today that Curacao isn't the only Dutch colony to have been attacked. Saint Martin is also currently under siege.",
	"Damn...",
	"Please gather all your forces and set out to Saint Martin immediately. You must help save the sieged city and its residents from destruction.",
	"I will do all I can, Mynheer. You can count on me.",
	" Yeah, looks like I don't have much choice.",
	"I shall set out at once.",
	"That's bad news. Oh well, what can you do. Such is life...",
	"I'm very sorry...",
	"You've done all you could. It's my fault. I should've called you in earlier. But enough about that! Please come back to see me in my residence in about a month. Don't just go wasting your time now - repair your ships, replace your crew, and restock your ammunition. Basically, prepare yourself for retaliatory measures. I reckon that the time has come for the Netherlands to increase the number of its colonies in the Caribbean.",
	"Which soon-to-be-Dutch city did you have in mind?",
	"I don't know yet. It all depends on the information I will receive shortly.",
	"I understand, Mynheer. I'll be back in a month.",
	"Wonderful, my friend, just wonderful. I never doubted you for a second.",
	"That's good to hear, Mynheer.",
	"Your reward for saving Saint Martin is 200,000 coins. Please be so kind as to accept it.",
	"Thank you, Mynheer.",
	"They say you saved Saint Martin from destruction. Excellent work, Captain!",
	"Also, please come back to see me in my residence in about a month. But don't just go wasting your time now - repair your ships, replace your crew, and restock your ammunition. Basically, prepare yourself for retaliatory measures. The Spanish are weak, and the time is high for the Netherlands to increase the number of its colonies in the Caribbean.",
	"Which soon-to-be-Dutch city did you have in mind?",
	"I agree. You may begin immediately.",
	"I am ready for the operation. The city of Maracaibo will soon be ours!",
	"From your lips to God's ears!",
	"I shall set out at once, Mynheer.",
	"I have already sent a report of this acquisition to the mother country. Our country, our young nation, is thirsty for conquest! And we shall do all that we can for the prosperity of the Republic of United Provinces.",
	"You've done well. I don't have any work for you at this time, but I sincerely hope that your future actions in the Caribbean region will be just as effective and carry just as much flare.",
	"I reckon you can count on me, Mynheer. I hold the good of the Netherlands as my highest priority!",
	"Those are the words of a great fighter and a true patriot! And now I ask that you accept this sum of 300,000 coins as payment for your loyal service.",
	"Thank you, Mynheer.",
	"Now tell me, what are your plans?",
	"To catch up on some sleep, Mynheer. Then we'll see.",
	"Well, I dare not keep you then.",
	"Farewell, Mynheer.",
	"Captain, they say you managed to capture Venezuela. That's amazing...",
	"Yes-yes, thank you... And you say Governor-General d'Ogeron gave you this letter himself?",
	"Of course! I have the honor of being employed by the king of France and wholly trusted by the Governor-General.",
	"But you're not an officer. Did d'Ogeron run out of soldiers or something? Hmm, you know what I think? I think that you're employed by the Brotherhood of the Coast... You intercepted this letter and decided to come here to do some spying! Guards, arrest him!",
	"Listen to me, Monsieur...",
	"I'm all ears.",
	"We already spoke about that...",
	"Here we go again...",
	"Stop this!",
	"Monsieur Governor-General, it has come to my attention that pirates have been extremely active in the region of Curacao. They've sunk over twenty ships.",
	"Yeah, that's for sure...",
	"No, sorry...",
	"Pardon...",
	"That is correct. So?",
	"I was able to track down the bandits in the city. By following them, I managed to discover the galleon that has been hunting Dutch vessels. The bandits turned out to be Spanish privateers.",
	"And where is this galleon?",
	"At the bottom of the sea, close to the Palms Shore. I boarded it and slaughtered the crew. I questioned the captain before executing him, and there's no question about it - it was the same galleon that kept giving us all that trouble.",
	"Well, what can I say? This is simply excellent news! You've done a great service to the city. I must admit, I thought this was the work of the Brotherhood of the Coast...",
	"I thought as much, Monsieur, and that's why I started my search. You see, filibusters just don't attack Dutch vessels.",
	"It's a good thing I didn't hang you... Well, I reckon your actions deserve a reward. I'm prepared to pay you 20,000 gold coins for sinking that pirate galleon. I trust that will suffice?",
	"Absolutely, sir, that will do nicely. And now allow me to take my leave. I must be heading back. Farewell.",
	"If I know such a person, I will surely give you an answer, Captain.",
	"I want to know about Teaser Dan.",
	"I find it strange that you're interested in some hobo who's also a convict and a former slave!",
	"A convict?",
	"Oh yes! After being convicted of rioting, this fellow had his Dutch citizenship revoked and was sent to a penal colony. The ship that was transporting him got captured by pirates who went on to sell Teaser into slavery...",
	"Bloody hell, what interesting twists of fate!",
	"Ain't nothing interesting about it! Why are you so into criminals, anyway?",
	"Mynheer, the thing is... Well, I've become what one might call a collector of national art. Once I return to the Old World, I want to write a book about my adventures in the New World. Yeah... And I think that Teaser would make quite a colorful character for my book!",
	"Eh... are you serious?",
	"Absolutely! Some of your city's residents shared with me some of the stories that Teaser would prattle on about publicly. They're pretty interesting... I mean, I know that it's all old wives' tales, but they're so amusing! It's the perfect material for my book!",
	"Hmm, well, I always encourage creative writing. New lands, new heroes, new horizons on the infinite ocean of our world... Yes, I suppose it's quite interesting. But I must admit, Captain, I never expected such tendencies from you!",
	"Mynheer, I'm still a captain, first and foremost.",
	"I understand. Well, I'd be happy to help you with Teaser Dan, but I don't know where he is. Not even the slightest idea. The thing is, that vagabond violated public order on several occasions. Eventually, I was forced to take punitive measures. My guess is that he's no longer on the island.",
	"That's sad... And you don't know where he might be, right?",
	"I already told you - not even the slightest clue. If you want my advice - describe Curacao as is, and leave out the moronic drivel of a former slave. Trust me, your book will only be better for it.",
	"Well, alright, I'll look for material on your island. Many thanks!",
};
