string DLG_TEXT_GUB [414] = {
	"What questions?",
	"What do you want?",
	"I've changed my mind...",
	"I've got nothing to say now. ",
	"You're in the service of Spain! I'll ask that you complete the task you have taken upon yourself!",
	"Immediately begin carrying out the tasks that you have taken upon yourself!",
	"At the moment I don't have any crucial tasks for you. You may show up at my residency later...",
	"I'll begin immediately, Señor Governor-General ",
	"I'm in the process of completing it...",
	"At the moment I have no crucial tasks for you. You may show up at my residency later...",
	"I'll ask you to excuse me. I'm very busy at the moment!",
	"Focus on your privateering tasks. I've got no missions for you now.",
	"Very well, señor Governor-General.",
	"Ahh. Here you are, ",
	"! They tell me of how your rare courage and resourcefulness! I'm happy to note that the people you've saved are already on their way to Castille. Their gratitude literally knows no bounds. Our friends at Port Royal tell of amazing things, such as that you cut the English jailers to pieces!",
	"Fear has big eyes, Don Francisco...",
	"I'm happy to see you again, my friend. I want to suggest one matter, and think that it will be to your taste.",
	"I'm all ears.",
	"Listen, I've got a somewhat strange task for you this time.",
	"I'm listening to you closely, Don Francisco.",
	"I'm sending you into the service of Governor Jose Sancho Jimenez of Santiago.",
	"What will I have to do?",
	"I've got a task for you. A bit of backstory, to start...",
	"I'm listening to you closely, Don Francisco.",
	"Our glorious corsair Manuel Rivero Pardal is now combing the shores of Antigua for British merchant ships. I've received information that French filibusters under the command of of Moses Beclean have gone to intercept him. Rush to Antigua and give assistance to Pardal. He is a symbol of our bravery!",
	"I understand, Don Francisco. I'll begin immediately.",
	"It's very good that you've showed up now, just in time. I have a very important task for you. A known filibuster. Captain Ansel, has managed to unite the English and French privateers with the goal of attacking Cumana.",
	"Don Francisco, you hold information about the size and character of this squadron.",
	"You are to leave for Portobelo immediately. The governor of the city is waiting for you there, and will give you your next objective.",
	"Señor, can you tell me at least vaguely what I am to do?",
	"I'll ask you to immediately leave for the governor of the city of Maracaibo, to finish the task entrusted to you.",
	"Again, Don Francisco?",
	"Are you ready for the serious operation of storming defended cities?",
	"I'm always ready, Señor Governor-General. ",
	"Ahh! Here you are, Captain! I was waiting for you...",
	"Always at your service, Don Francisco.",
	"Now, then. I was informed of your arrival.",
	"I am greatly honored, Don Francisco. I never expected my humble person to be worthy of the attention of such a high-ranking fellow. Now, then...",
	"Report. How goes the business of freeing the prisoners?",
	"Your order has been completed, Señor Governor-General.",
	"Ahh, and now you've returned. Very good. How did it go, the task ordered by the Holy Inquisition?",
	"Not very well, Don Juan. Nothing scary happened - which is, of course, good.",
	"Ahh, and now you've returned. Very good. How did it go, the task ordered by the Holy Inquisition?",
	"More or less good, Don Juan. The mission has been partially completed, which isn't bad.",
	"Ahh, and now you've returned. Very good. How did it go, the task ordered by the Holy Inquisition?",
	"A success of the highest degree, Don Francisco. Everything is done in the best fashion. The Holy Inquisition is happy beyond belief.",
	"Well, what will you say about Rock the Brazilian?",
	"I attacked his corvet on the shore waters of Maracaibo, where he was hunting our galleons. It's a pity, Don Francisco, but I was unable to take him alive. He sank with his entire ship...",
	"Well, what will you say about Rock the Brazilian?",
	"I was planning on attacking his corvet in the shore waters of Maracaibo, where he was hunting our galleons. Unfortunately, for reasons outside my control, I had to leave the waters in which Rock the Brazilian was. He got away from me...",
	"Well, what will you say about Rock the Brazilian?",
	"He's in my hold, Don Francisco.",
	"Yes, yes, I've already been informed of the Brazilian's successful transport to Santiago. I can congratulate you.",
	"Thank you, Don Francisco. How else may I be of help?",
	"Now, as I predicted, the much-praised corsair couldn't stand the passionate interrogations of the Holy Inquisition for long.",
	"So he was tortured?",
	"I ask you to come back in two days, no earlier.",
	"Forgive me, Señor Governor-General.",
	"Well, then. Report, what did you manage to find, in regard to the Brazilian's treasures?",
	"Nothing new, Señor Governor-General. But I'm searching...",
	"Don Francisco, I'm ready to report that the search is over.",
	"Were you able to learn anything on this matter?",
	"I'm working, Don Francisco, but nothing new as of yet...",
	"Report what you've managed to find about this murder.",
	"I was able to discover that the suspected murderer looks like a Ladron. I presume that the clues lead to Tortuga.",
	"I'm anxiously waiting for your report on the investigation in Tortuga.",
	"Don Francisco, on Tortuga I discovered that some Dona Anna is being taken care of by Bertran d'Ogeron. I can presume that this is the Dona Anna Ramirez de Leiva, but I can't report that for sure.",
	"I'm anxiously waiting for your report on the investigation in Tortuga.",
	"Don Francisco, on Tortuga I discovered that some Dona Anna is being taken care of by Bertran d'Ogeron. I can presume that this is the Dona Anna Ramirez de Leiva, but I can't report that for sure.",
	"I'm anxiously waiting for your report on the investigation in Tortuga.",
	"Don Francisco, on Tortuga I discovered that some Dona Anna is being taken care of by Bertran d'Ogeron. I was also able to come upon the trusted man of the governor-general - a man named Henri d'Estre.",
	"Report. How's your investigation moving along?",
	"I've found out everything. The wife of don Ramirez de Leiva decided to run away to Governor-General d'Ogeron, of Tortuga, of her own free will.",
	"Yes, yes, I already know of your newly successful actions. Well, then. I didn't doubt that Hispaniola would be cleansed to make room for our colonists from the Old World.",
	"The buccaneers have been finished, Don Francisco. And I killed Edward Mansfield personally!",
	"Ah, now... Happy to see the courageous Captain.",
	"And I'm happy to see you as well, Don Francisco.",
	"Ah, now... Happy to see the courageous Captain.",
	"And I'm happy to see you as well, Don Francisco.",
	"Report the results of your mission.",
	"Señor, I was unable to save Pardal. His galleons were sunk by superior forces. Manuel himself died...",
	"Report the results of your mission.",
	"Señor, the information that you've acquired has turned out to be correct. I rushed my sails to Antigua, and just made it to Pardal in time - two of his galleons were already in battle against the superior forces of the French pirates. Uniting our forces, we were able to defeat a strong enemy. The ships of the filibusters have gone down!",
	"Report the results of your mission.",
	"Señor, the information that you've acquired has turned out to be correct. I rushed my sails to Antigua, and just made it to Pardal in time - two of his galleons were already in battle against the superior forces of the French pirates. Uniting our forces, we were able to defeat a strong enemy. The ships of the filibusters have gone down!",
	"Report the results of your mission.",
	"Unfortunately, Señor Governor-General, I wasn't up to this task. I couldn't help Pardal.",
	"Some of the refugees from Cumana have already arrived here. You were unable to save the city and its inhabitants.",
	"I rushed to Cumana on all sails, not stopping for a moment. Even so, I couldn't make it in time. It was impossible.",
	"Some of the refugees from Cumana have already arrived here. You were unable to save the city and its inhabitants.",
	"The United Squadron of Los Ladrones was so strong, that we couldn't handle them. With the forces that I had it was impossible.",
	"I've already been informed that Cumana is saved. Wonderful!",
	"We managed to sink the Ladron fleet. No one was left alive...",
	"Report. What's going on with you?",
	"Don Francisco, I received an order from the governor-general of Portobelo to escort four gold galleons to an uninhabited Cayman island.",
	"I've been informed that Maracaibo has been captured, and that it's now a protectorate of England!",
	"Yes, Señor. Probably...",
	"I already know that you've brilliantly handled the mission!",
	"This time I had to send the English pirate ships to the bottom of the ocean floor.",
	"I already know that you've brilliantly handled the mission!",
	"This time I had to send ships of the English pirates to the bottom of the ocean floor.",
	"You haven't been able to capture either Willimstaad or Marigo...",
	"I am working on it, Señor Governor-General. The task isn't easy. It'll take serious preparation.",
	"Splendid! You've ruined Willemstaad! Now it's Marigo's turn!",
	"That's so, Don Francisco...",
	"Excellent! Marigo has been ruined! But know that I await the capture and destruction of Willemstaad.",
	"I'll do everything I can, Señor Governor-General.",
	"Marigo and Willemstaad have both been taken by storm and ruined! Wonderful work, my friend!",
	"The work is done, Don Francisco...",
	"Now, then. Escorial can be congratulated with a worthy acquisition. The island of Hispaniola is ours!",
	"That is so, Señor Governor-General. I was able to capture Port-au-Prince.",
	"I don't deal with men who break their word. I've got nothing more to say to you.",
	"Don ",
	", Escorial is offering you full freedom to act in the interests of Spain. Act independently.",
	"Fine, Don Francisco.",
	"My attention may be earned by doing work for the benefit of great Castille - which you, Captain, have yet to do.",
	"But you have a ship and a Spanish patent, which is certainly important for my country. Especially now, when the enemies of Spain are trying to get revenge for all their previous failures.",
	"Is the position of Spain really that serious?",
	"Yes. Though at first sight everything looks in order, the wealth and might of Spain have always inspired the envy of the European monarchies. Now, when our enemies are aiming to recruit all types of bandits against us, our position has become unbearably hard.",
	"There's been an increase in attacks on our colonies and trade caravans. Kidnappings of wealthy and renowned citizens, with the aim of getting ransom, have become a common occurrence. Pirates have thoroughly filled all the trade routes, which has made sailing them very dangerous.",
	"Escorial is in a rage. Her majesty the Queen Mother demands quick and prompt actions against Ladrones of all types. To fulfill this objective, it's been decided to fight the enemy with their own weapons. That means hiring privateers to serve the crown.",
	"Looks like I'm just in time...",
	"It looks that way. Yesterday the best someone like you could've hoped for would have been the fires of the Holy Inquisition or the gallows rope. But times have changed. Prove your loyalty to our Lord and Castille, and you will have everything - riches, glory, accolades, and rewards.",
	"Sounds pretty good. I'm ready to begin working at once.",
	"Let's get to business, then. ",
	"English pirates have captured three most respected gentlemen. And the ransom that the known scourge Henry Morgan is demanding is larger than reason would permit. That bandit's demanding 500,000 in gold! You'll have to get into Port-Royal, free our citizens from jail, and get them to me safe and sound.",
	"You must sneak into the prison and attack the guards unexpectedly. The prisoners are being held very closely, so their escape will be known immediately. Because of that, it would be wisest to disembark on a secluded bay, far away from the fort. Not under any circumstances should you endanger the lives of the people in your care. That's an absolute requirement.",
	"Do you understand everything?",
	"Yes, Señor Governor-General.",
	"You have one month to free the prisoners. No more. Get ready, and be on your way.",
	"I'll begin immediately.",
	"Well, then. You've made your first successful step on the rough path of a career for Her Majesty the Queen Mother Marie-Anne of Austria. Receive your honestly earned 50,000. I'm happy that I wasn't mistaken in you.",
	"Thank you, Sir Governor-General. In fact, you're a great mathematician.",
	"What do you mean?",
	"Well. If you add one 0 to the 50,000 given to me, you'll get the sum that you didn't want to give Henry Morgan.",
	"Ahh, about that. We of course could allow ourselves such a boastful ransom, if it were to prove how valuable are citizens are to us - but then that 50,000 wouldn't be stretching your pocket so snugly, now would it?",
	"Oh, certainly, Señor. You've brought up a most educational example!",
	"In that case, I shan't dare to keep you any longer... Stop by my residence from time to time.",
	"Fine. Certainly.",
	"Did you know that our glorious Governor-General Oregon-y-Gascon hired Captain ",
	" to free our cities that were captured by that devil Morgan? And you know, the order was successfully carried out!",
	"Your humbleness honors you... Now, then. Back to work. A high-ranking Jesuit, Antonio de Souza, has arrived here and asked for a cold-blooded, brave, and honest officer be sent to him.",
	"I recommended you. Go to Santiago. There, you'll find the command of the Inquisition for the Caribbean Sea - and from there you'll find de Souza. Do everything he orders, without thinking too much about it. Do you have any questions?",
	"No, Señor Governor-General.",
	"Then go.",
	"Antonio",
	"de Souza",
	"That's great. You rest a few weeks from the labors undertaken in the name of the glory of the Church, and then I'll you to visit me. I think I'll find some new job for you.",
	"Certainly. Always at your service!",
	"There are rumors that Captain ",
	" has geared up to take care of the orders of de Souza himself! Inquisition... The word alone sends a shudder through the body.",
	"Now, then. Do you know anything about the Ladron, Rock the Brazilian?",
	"A well-known character, a very dangerous privateer. Hangs around Tortuga.",
	"Yes, that's so. A real headache for us.",
	"So then, I intend to take care of this migraine and take care of it for our colonists. I want you to capture that slippery Rock the Brazilian - and this is very important - and deliver him alive.",
	"Is that required? The fight will be legendary; you can be sure of that.",
	"And so? I don't seem understand you, Señor ",
	". You're not scared?!",
	"Don Francisco, I'm scared of neither demon nor devil. I think you've had a chance to see that for yourself! I mean that I won't fully be able to control the boarding action. In such a meat grinder, anyone can die.",
	"I understand that. But I will repeat - I need  Rock the Brazilian alive. Or rather, this is for monsignor Antonio de Souza, with whom you are familiar. This is a decree of the Holy Inquisition. Do you understand how important this is for us?",
	"Yes, Señor. I understand. Well, then. I can promise you that I'll do everything in my power to successfully execute this order in its entirety.",
	"Excellent! I'll be waiting for when your ship, with Rock the Brazilian in the hold, stands ready for a raid on the shores of Santiago.",
	"Goodbye, then, Señor.",
	"Hmm... That's bad. I'm disappointed in you.",
	"I'll ask you to leave me alone now... However, you can come for an audience from time to time. It's possible I'll have some work for you...",
	"Certainly, Señor Governor-General. I understand. Thank you...",
	"Did you hear? Captain ",
	" failed a mission from the Governor-General to capture Rock the Brazilian. What a loser! ",
	"Excellent! Now go to Santiago and turn him over to monsignor Antonio de Souza.",
	"Of course, Señor. It shall be done.",
	"Drop by in a few days. Monsignor Antonio will have to work over this Brazilian, and then we'll have news.",
	"Fine. I'll be here in two days, Signor.",
	"Of course, monsignor de Souza wasn't reading him his rights! Rock the Brazilian got exactly what he deserved.",
	"He didn't once flinch when he was torturing Spanish citizens to discover their hidden money. Now under the tortures of the Holy Inquisition, Rock has revealed the location of his own treasure stash. He divided it and hid it in various places throughout Cuba, Hispaniola, and the outskirts of Belize.",
	"You must find and deliver all the stashes of the Brazilian. Preliminary appraisals suggest they contain as much as 500,000 piasters!",
	"Not bad, I wager! Now, Señor. Were you able to discover the exact location of the treasure stash?",
	"No, unfortunately...",
	"Maybe it would be worth waiting and perhaps monsignor Antonio will give the needed details?",
	"That is not possible. Rock the Brazilian has given his soul over to our Lord. Amen...",
	"Amen indeed. So, uh. May I count on getting part of the discovered treasure?",
	"Undoubtedly. A fifth of the Brazilian piasters that you find are yours. And don't bother to bring it back piecemeal. Come back the moment that you have the full sum - 500,000.",
	"Fine, sure. I'll immediately begin the search, Señor Governor-General.",
	"Wonderful! Let's tally things up... You're bringing 500,000 into the treasury of Escorial, so your cut amounts to 100,000 piasters.",
	"I thank you. Lovely, Señor Governor-General.",
	"So all is well... I won't dare to hold you now, but I'll ask you to come back for an audience in a week.",
	"Fine, Don Francisco. I'll be here at the assigned time. For now, allow me to bow out...",
	"You don't know the great news? A certain Captain ",
	" captured the vile Ladron, Rock the Brazilian. Glory to the Almighty Lord!",
	"Havana has been shaken by a strange crime. The strangest thing is that it's unclear how it happened.",
	"The Commandant of Havana, don Jose Ramirez de Leiva, was killed in his own home, along with his four servants. Each was in full combat gear, as if they were readying to go off to war.",
	"That's something! And nobody heard? The kitchen maid, for example?",
	"No, no one other than his wife was in the house. On the eve of this event, Don Jose started a horrible row with his wife and sent all of the female servants back to where they came from.",
	"And what does the wife say?",
	"She has disappeared...",
	"What, you mean completely?",
	"No, partly... Think about what you say!",
	"Forgive me, Don Francisco. This is all so strange... You know, this isn't my style. I'm no detective. Let the commandant's office handle this.",
	"Don Jose was the commandant of Havana. Listen, I can't force you to investigate this murder, but this is what I'm asking you to do now.",
	"The city is in shock, you understand. And this to add to this the disappearance... We've searched the whole area, without results. I need effective methods of investigation right now, and you are the best candidate at hand.",
	"Fine, all right. I'll do what I can, Señor Governor-General.",
	"Tortuga is the hiding place of bandits of all types... And what of Dona Anna?",
	"It's hard to predict... But I found an unfinished letter at the murder site...",
	"Hrrm... Yes... yes, I don't even know what to say. You need to sneak into Tortuga and figure out what's what.",
	"Fine, Don Francisco, I'll do what I can.",
	"I'm giving you a license from the French West Indian company, active for fifty days. This document will allow you to move around Tortuga without suspicion. And hope you'll realize that to hoist a French flag upon your craft...",
	"Of course, Don Francisco. This is very useful. All right, I shall begin completing this task.",
	"Guido",
	"These are just guesses... Not enough to make solid conclusions.",
	"I am disappointed in you. Please leave me. I have no work for you.",
	"Well, I guess you can come see me periodically. Perhaps I'll be able to throw you a bone... a small bone, that is.",
	"Very well, Señor Governor-General.",
	"Have you heard? Our Governor-General entrusted Captain ",
	" to investigate the murder of commandant de Leiva. The Captain turned out to be a rather inept detective.",
	"Go on...",
	"I caught up with this filibuster, but was unable to kill him. He was too strong, and I had to retreat.",
	"Heh, no surprise there. Trying to kill five men, armed to the teeth and ready for combat, ain't exactly the same as poking a dummy at the training grounds...",
	"From my conversation with d'Ogeron, I was able to learn that his love is none other than Anna Ramirez de Leiva. That's basically it...",
	"Well, if Don Jose would treat Doña Anna... ahem, appropriately, then I'm sure none of this would have happened. It is true that Doña Anna suffered a great deal from her spouse's ways and from the order that he established in his house. That's not to say that he had no right to do what he did...",
	"Señor Governor-General, may I consider the investigation complete?",
	"Yes, of course. Your reward is 3,000 piasters. However, if you were to eliminate this 'confidant', the reward would be quite different.",
	"And now I will ask you to leave me. I need to write de Leiva's relatives in Castile and inform them of this terrible loss.",
	"Very well, Don Francisco, goodbye...",
	"Have you heard? Our Governor-General entrusted Captain ",
	" with the investigation of commandant de Leiva's murder. The Captain tracked down the killer, who turned out to be some Frenchman, but he was unable to avenge the commandant's death.",
	"That's hard to believe...",
	"And yet, it is true. At this very moment, she's in Tortuga, and from the looks of it, she's quite happy.",
	"Well, if Don Jose would treat Doña Anna... ahem, appropriately, then I'm sure none of this would have happened. It is true that Doña Anna suffered a great deal from her spouse's ways and from the order that he established in his house. That's not to say that he had no right to do what he did... Anyway, so who was it that killed Don Jose?",
	"A French filibuster named Henry d'Estre, trusted confidant of Governor-General d'Ogeron.",
	"Damn it! I won't claim that I like Don Jose all that much, but I won't stand for this kind of thing happening right under my nose. It's unacceptable! And I will have retribution!",
	"You already have it - Don Jose's killer is dead. I tracked him down in Tortuga and killed him.",
	"Bloody hell! You truly are a valiant officer - and a man of honor, to boot! Please accept my gratitude for this brave deed.",
	"Thank you, Don Francisco.",
	"You may go. As for me, I will make sure to curb some of Doña Anna's happiness. I reckon that her life is about to come to an abrupt and unfortunate end...",
	"You're planning on assassinating her?",
	"Me? Absolutely not, I have better things to do than that. However, I feel it is my duty to provide a detailed report to Don Jose's family on the results of your investigation. And knowing well the Castilian code of honor, I would venture a guess that Doña Anna has, at most, six months left to live...",
	"I see. Well, I guess that's none of my business. Señor Governor-General, may I consider this investigation finished?",
	"Yes, of course. You've completed this task brilliantly; your reward amounts to 120,000 piasters.",
	"And now I will ask you to leave me. But remember to come visit me in my residence from time to time...",
	"Very well, Don Francisco, goodbye...",
	"Have you heard? Our Governor-General entrusted Captain ",
	" with the investigation of commandant de Leiva's murder. The Captain tracked down the killer, who turned out to be some Frenchman, and sent him to kingdom come.",
	"You'll find that out from Jimenez. For the time being, you are to be fully at his disposal. The only thing I can tell you is that you won't be bored - we've got a serious military operation ahead.",
	"The details...",
	"Everything from Jimenez. Set out to Santiago immediately.",
	"Fine. Certainly.",
	"Hmm, that's great news. Mansfield was a Ladrone of considerable authority, so we can consider this an emphatic success of Spanish weaponry. I congratulate you on this victory!",
	"Tell me, was this military operation properly financed by the Governor of Santiago?",
	"Quite properly, Señor Governor-General. Everything is just fine.",
	"Well, that's wonderful! Alright, so I'm expecting you soon. I should have more work for you then.",
	"I will visit you periodically, Señor.",
	"Captain",
	"Cooper",
	"Rumors says that you sent the buccaneer leader, Mansfield, to kingdom come. Good riddance, if you ask me...",
	"The thing is, the French and the Dutch are probably working together behind closed doors. Think about it - Louis XIV is involved in the devolutionary war over Dutch territories in Europe. While the Netherlands aren't brave enough to openly oppose us, their financial support of France may play a vital, perhaps decisive, role in this war. Everyone knows that Louis has money problems.",
	"Your task is as follows: you must secretly sneak into Tortuga and try to intercept some of the correspondence between Governor-General of Curacao, Peter Stuyvesant, and Governor-General of Tortuga, Bertraine d'Ogeron.",
	"Couriers carrying diplomatic mail is pretty common over there, so you'll just need to intercept any one of them. I need a document that our diplomatic apparatus can utilize as proof that the Dutch and the French have been working together.",
	"I understand, Señor. Am I in any way limited by time?",
	"Not at all. I only ask that you don't engage in any open fighting in Tortuga - I value brave and hard-working officers like yourself.",
	"Don Francisco, my job is to survive in any circumstance.",
	"One more thing. I am giving you a license from the French West Indian company, active for 60 days. Present this document to the head of the port and no one will suspect anything.",
	"Well, now that the instructional part of the mission is completed, you may get on with the practical one.",
	"I will do just that, Señor Governor-General.",
	"Well, what is your mission report?",
	"I was able to get my hands on diplomatic correspondence between the Governor-Generals of Tortuga and Curacao.",
	"I wasn't able to get my hands on that document. I think that the task is impossible to complete, and it's useless to continue...",
	"That's very bad news. I'm disappointed in you... Well, I don't need you anymore for now. You can try back later, if you want. Mayhaps I will find some cushy job for a clueless officer like yourself...",
	"Very well, Señor Governor-General.",
	"Our Governor-General sent Captain ",
	" to Tortuga with some extremely important task, but the Captain came back empty-handed. What a loser...",
	"Excellent, ",
	", simply brilliant!",
	"Thank you, Don Francisco...",
	"Now we have a serious argument for our diplomatic war. You've done tremendous work.",
	"Well, it sure wasn't easy, let me tell you...",
	"Your reward is 50,000 coins! Please accept it... And please don't leave Havana for long. I will need your services soon.",
	"Very well, Señor Governor-General.",
	"I hear that Captain ",
	" successfully managed an extremely dangerous job on Tortuga. The man's bravery is a constant source of inspiration.",
	"Damn it; that's very, very bad. This news will have a terrible effect on the settlers' morale.",
	"I am very sorry, Señor. I've done all I could.",
	"Well, what's done is done. Or, rather, what isn't done is... umm... you know what I mean. Consider yourself on vacation. You can come see me some time later. Maybe I'll have some work for you.",
	"Very well, Don Francisco. Goodbye...",
	"Splendid, my friend, simply wonderful!",
	"Señor, it was a good battle. I reckon Manuel will fill you in on the details...",
	"I'm sure... And I'm just as sure that your heroics merit all kinds of praise and a hefty reward - more specifically, 25,000 reals!",
	"Hrm, this sum is... it's... Umm, it's not about money anyway!",
	"Those are words of a true soldier! I was right about you!",
	"I won't keep you longer, but I ask that you come visit me in a week. A job is shaping up that'd be perfect for a brave captain, and I think I know who that captain is...",
	"Very well, Don Francisco. I'll come visit you then.",
	"People say you saved our hero, Pardal! Allow me to express my sincere admiration. You, sir, are a true warrior!",
	"Hmm, that's bad news. I'm disappointed... Well, I won't keep you longer. You can come back to see me some time later, if you want. Perhaps I can find a job for a thick-witted captain like yourself...",
	"All right, Don Francisco. Again, I apologize...",
	"Rumors say that Pardal's death was largely your fault. That's sad to hear, Señor Coward...",
	"Without going into details, unfortunately. I was informed that their squadron also included a first-class battleship, which is totally uncharacteristic of pirates. There's no doubt about it now - this attack was sponsored by Tortuga's authorities...",
	"Is there anything we can do to stop them?",
	"Heh, my friend, we have chanced to live in truly tough times... Spain, our homeland, is suffering blows from all sides. In the Old World, we're losing northern provinces in the devolutionary war with Louis, and here, we're being increasingly pressured by surrounding empires...",
	"And it seems inevitable that the Pope's influence in the world will also take a serious hit real soon...",
	"That's all very sad, Señor...",
	"However, we are not to fall into despondency. We are the very edge of the blade that strikes the final punishing blow to our enemies in the name of Spain and the Almighty Lord! If we are being challenged once again, we must respond to this challenge appropriately.",
	"Many a time now, villains and criminals of all stripes - naturally, I'm talking about all Ladrones - conquered our cities, tortured and killed our colonists...",
	"This time, we must ensure that Cumana is well defended - herein lies your task. Set out for Cumana immediately. Repel the Ladrones' attack, which is headed by Captain Ansel.",
	"Perfectly clear, Don Francisco. It shall be done.",
	"Excellent! And remember that the fate of an entire city lies in your hands and the hands of your soldiers and sailors! Don't let me down.",
	"Have no doubt, Señor. The Ladrones will be destroyed.",
	"Again? I'm very disappointed in you. You can show up in my residence some time later, but I've nothing for you at the moment. I don't have much need for officers that fail missions habitually...",
	"I understand, Don Francisco.",
	"I hear that Captain ",
	" wasn't able to save the citizens of Cumana! They suffered a terrible fate...",
	"Excellent! That's a serious blow to Spain's enemies in the Caribbean. As a reward for your bravery, please accept the sum of 100,000 gold from the Spanish Crown!",
	"Thank you kindly, Señor. And now allow me to take my leave - I need to bring my ships back to order after that battle...",
	"Of course, my friend. But don't leave the city for too long. I will most likely need your services again soon.",
	"I understand, Don Francisco.",
	"Captain, they say it was you who saved Cumana! Allow me to express my sincerest admiration, Señor...",
	"Your task will consist of escorting certain ships. I cannot tell you any more, but you will receive all the necessary instructions from the Governor of Portobelo. Please take this letter of credence in your name to the him.",
	"I understand, Señor. I shall set out at once.",
	"You needed to escort the galleons to Belize; what does Cayman have to do with anything?!",
	"Señor, I've no idea about Cayman, but I was promised that a Spanish combat squadron will meet me there.",
	"So, did it meet you?",
	"A Spanish combat squadron - no. However, five Ladrone ships have prepared quite a warm welcome for me. It was obvious that they were expecting none else but my galleons.",
	"What makes you think that?",
	"Señor, think about it. What else can an entire squadron of pirates be waiting for in the middle of the Caribbean's deserted territories? Of course, one could argue that they gathered for a friendly card game, but I'd find that hard to believe.",
	"Bloody hell, I think you're right! This is either a terrible mistake or a betrayal. Alright, I'll deal with that matter myself, but tell me - did all the galleons survive?",
	"Señor, the attack was entirely unexpected. I was only able to save one galleon.",
	"Señor, the attack was entirely unexpected. I was able to save ",
	" galleons...",
	"Señor, the Ladrone attack was entirely unexpected and terribly furious. I lost all the galleons...",
	"Señor, though the Ladrone attack was entirely unexpected, I was able to save all the galleons entrusted to me...",
	"That's very bad. I understand that you found yourself in a difficult situation, but I'm sure you could've been more capable. Now I must report to Madrid about a major shortage in our gold delivery... And all this while Spain is fighting a grueling war in Europe!",
	"Hrm, that's terrible news. I counted on you, but you did not justify my trust.",
	"Don Francisco, please believe me when I say I've done all I could. More than that, even... The balance of power was not in our favor. I had only one ship to protect four galleons! Such was the order of the Governor of Portobelo, by the way. Perhaps he should answer for this to the fullest extent of the law?",
	"Perhaps, but that's none of your business. I understand what you're saying, but all the various excuses you're offering to justify your defeat still do not lessen your guilt in any way.",
	"I see...",
	"Therefore, I ask that you leave me immediately. You can come visit me in my residence from time to time. Perhaps I'll be able to find a task more appropriate for your 'talents'...",
	"Thank you, Don Francisco.",
	"Whoa, hold on a minute there, Señor. I see you've taken to thievery?! The galleons are missing gold! I want nothing to do with you anymore - no way, no how! Goodbye!",
	"Umm, eh, but...",
	"Captain, people say that you were caught stealing, and that the Governor-General threw you out of his residence. Heh, good luck trying to get work from him now...",
	"Bloody hell! How could this have happened?! I understand that you found yourself in a difficult situation, but I'm sure you could've been more capable. Now I must report to Madrid about a major shortage in our gold delivery... And all this while Spain is fighting a grueling war in Europe!",
	"Don Francisco, please believe me when I say I've done all I could. The reason I fell into this ambush in the first place was because of the Governor of Portobelo!",
	"I want none of your excuses. Get out!",
	"I guess you can visit me from time to time. Perhaps I can even find a job for a talentless worker like yourself...",
	"Fine, Don Francisco.",
	"Is the gold that they carry safe as well?",
	"Yes, Don Francisco, everything's fine.",
	"Not entirely, Don Francisco. On those galleons, I have ",
	" gold.",
	"Hrm, not entirely, Don Francisco... On those galleons, I have ",
	" gold.",
	"That's very good. You've managed to get out of a very difficult situation, and you did it with honor. Therefore, I trust that a reward of 220,000 piasters will be equal to your merit.",
	"Señor, I thank you for your assessment of my deeds. Now, if you no longer need me, allow me to take my leave for a while.",
	"Of course, you may go on with your affairs. But remember to visit me from time to time.",
	"Fine, Don Francisco.",
	"Captain, everyone's talking about how you were ambushed while escorting galleons full of gold! How you managed to get out of such a bind with your honor intact is beyond me...",
	"Well, I guess in a situation like yours, certain losses are justified. However, those losses will come out of your fee, which now amounts to 200,000 gold.",
	"I reckon we can safely say that you got yourself out of a very difficult situation, and with honor.",
	"Señor, I thank you for your assessment of my deeds. Now, if you no longer need me, allow me to take my leave for a while.",
	"Of course, you may go on with your affairs. But remember to visit me from time to time.",
	"Fine, Don Francisco.",
	"Captain, everyone's talking about how you were ambushed while escorting galleons full of gold! Even though you lost some of the galleons, that's alright! As long as you got the better of those Ladrones!",
	"What the hell happened to ",
	" gold?! This is outrageous and simply unacceptable!",
	"Señor Governor-General, imagine the mess of the situation that we got into and what we had to endure... Panic on the galleons. Who knows what people were up to...",
	"That's no excuse! Arguing over this is pointless... I want nothing more to do with you - no way, no how. Goodbye!",
	"Hrm, well then...",
	"Captain, they say that our Governor-General threw you out of his residence.  Heh, good luck trying to get work from him now...",
	"Yes, again!",
	"Señor, you are aware that I got into a real mess while on a mission from the Governor of Portobelo...",
	"The problem you speak of was a result of badly coordinated actions. Appropriate measures were taken to prevent things like this from happening again.",
	"And what do I need to do in Maracaibo?",
	"The reason I'm sending you there is to reinforce the city's squadron and garrison. Your objective is to protect Maracaibo from any acts of hostility.",
	"To what degree should I obey the city's Governor?",
	"Within the framework of the global objective to ensure the city's defense, you are to obey the Governor of Maracaibo. Operations not directly connected to this are not part of your mission.",
	"Great! Well, I'm ready to get on with my mission.",
	"Excellent! Set out for Maracaibo as soon as possible.",
	"Very well, Don Francisco. I'll be in Maracaibo before you know it.",
	"But that is the very reason why I sent you there - to help protect that city!",
	"Don Francisco, the enemy forces were just too many, much greater than mine. It was far from a fair contest, and I had to flee the field of battle to save my life...",
	"I don't believe my ears! ",
	"Alas, it is so...",
	"I want nothing more to do with you! In all its glorious history, Spain has never seen such cowards and slackers on its side! What shame... That's it, this conversation is over, once and for all. Goodbye!",
	"Captain, they say that our Governor-General threw you out of his residence for being a coward.  Heh, good luck trying to get work from him now...",
	"Splendid! I never doubted you, even for a second.",
	"Governor of Maracaibo, Señor ",
	" ordered us to pass along a message of his gratitude for such timely assistance.",
	"All right... Did he thank you?",
	"Yes, Señor. Everything's fine...",
	"Well then, beautiful! Now, I will ask that you rest up and regain your strength for upcoming battles. You can leave the city, but not for long. I may very well require your services quite soon.",
	"Fine, Don Francisco.",
	"Captain, they say you managed to defend Maracaibo! Señor, that is true heroism. Don't let anyone tell you different!",
	"Very good! Alright, so your mission is as follows.",
	"Within the framework of the continuing devolutionary war with France over Spanish territories in Holland, our first and primary objective lies in pillaging Curacao and Saint Martin. An intercepted dispatch revealed that the Dutch are allocating enormous sums of money for French military needs.",
	"Now, we cannot prove this for sure, since the correspondence is protected by a special code; the letter appears to say something completely different. Nevertheless, we must put an end to this, and with it, we will put an end to the trading might of the Netherlands!",
	"You must storm and pillage the Dutch settlements of Willemstad on the island of Curacao and Marigo on the island of Saint Martin. All the trophies you may capture as a result of this operation shall be yours.",
	"Are you ready to execute this mission?",
	"Yes, Don Francisco. Am I in any way limited by time?",
	"Not at all.",
	"Very well, then. I'm on it.",
	"Excellent work! The Dutch got their wrists slapped good. Now, let's hope the sting will help them be a bit more stingy with their money, ha-ha!",
	"All the booty captured on the island is yours by right! Please come visit me in a month. I've got another job shaping up that will require your services.",
	"Very well, Don Francisco. I will definitely visit you then.",
	"You saved us, Captain! You had to be brilliant to repel such a powerful attack, and you were!",
	"I need you to capture another city for me. This time, the goal is not to pillage, but to assert Spain's authority.",
	"Sounds good, Señor Governor-General. What's the city?",
	"The city is Port-au-Prince, currently under French control. You were already successful in solving La Vega's buccaneer problem, now it's this colony's turn. Hispaniola must become entirely Spanish!",
	"I understand... Am I limited by time in any way?",
	"Again, you aren't. Capturing a city is no easy task; it would be foolish of me to demand any kind of deadline. Make all the necessary preparations and get it done. As always, any trophies you find become your legal property.",
	"Excellent, Señor Governor-General. I'm on it.",
	"Splendid! I will immediately inform all the stakeholders of the great news! A brilliant victory, Captain! Your success is miraculous!",
	"Nothing miraculous about it, Señor. It was simply proper preparation and some war prowess...",
	"Ah, modesty only adds to a warrior's character. Well, I am truly happy for you, my friend. You've become the most significant captain in the Caribbean! Please accept my congratulations!",
	"Thank you, Don Francisco...",
	"All right, the primary tasks that Spain has put before me are completed. From hereon, I grant you freedom of action in the interests of the kingdom. I am very hopeful that your future actions will only strengthen and multiply Spain's supremacy in these waters.",
	"Don't doubt it for a second, Señor Governor-General. On this note, allow me to take my leave.",
	"Captain, they say you managed to capture Port-au-Prince! Can it be that the whole island is now ours?! That's amazing!",
};
