string DLG_TEXT_CHR [20] = {
	"Questions, my son?",
	"Ask, and I shall listen...",
	"I'm listening, my son. Pray, speak...",
	"Twice now I've offered my ear. This is the third time, my son. ",
	"A servant of the church has many responsibilities, my son, and you are testing my patience...",
	"I've changed my mind...",
	"Later, Padre...",
	"Well, actually there's not much to say right now...",
	"I'll get around to it... eventually.",
	"Forgive me, Father...",
	"Father, can you tell me if the local loan shark is one of your parishioners?",
	"Yes, I see him at the church, though quite rarely, I admit.",
	"What kind of man is he?",
	"I don't like to speak ill of people, my son.",
	"I think that you should have a talk with Gillian Atterbury. She's also a parishioner in our church, and I know that she's been having serious problems with the man you're asking about. Perhaps you can even help her...",
	"Gillian is a model parishioner. She comes to church pretty much every morning at around eleven, and stays for two to three hours to pray.",
	"But you can also find her in the city.",
	"Thanks, Father.",
	"Gillian",
	"Atterbury",
};
