string DLG_TEXT_CHR [20] = {
	"Questions, my son?",
	"Ask, and I shall listen...",
	"I'm listening, my son. Pray, speak...",
	"Twice now I've offered my ear. This is the third time, my son. ",
	"A servant of the church has many responsibilities, my son, and you are testing my patience...",
	"I've changed my mind...",
	"Later, Padre...",
	"Well, actually there's not much to say right now...",
	"I'll get around to it... eventually.",
	"Forgive me, Father...",
	"I would like to know how often you see Don Salvatore's wife in church?",
	"Señora Olevares? Quite often, my son, she's a fine parishioner... Why do you ask?",
	"Just curious, Padre. Thanks, I'll see ya.",
	", do you take Isabella de Valdez to be your lawfully wedded wife, and swear to love, honor and cherish her in sickness and in health, for as long as you both shall live?",
	"I do, Padre.",
	"And do you, Isabella de Valdez, take ",
	" as your lawfully wedded husband, and swear to love and support him in sickness and in health, for as long as you both shall live?",
	"I do, Padre.",
	"If there's anyone here who knows a reason why this man and this woman should not be joined in holy matrimony, speak now or forever hold your peace.",
	"I hereby pronounce you husband and wife!",
};
