string DLG_TEXT_CHR [34] = {
	"Questions, my son?",
	"Ask, and I shall listen...",
	"I'm listening, my son. Pray, speak...",
	"Twice now I've offered my ear. This is the third time, my son. ",
	"A servant of the church has many responsibilities, my son, and you are testing my patience...",
	"I've changed my mind...",
	"Later, Padre...",
	"Well, actually there's not much to say right now...",
	"I'll get around to it... eventually.",
	"Forgive me, Father...",
	"Tell me, Father, where may I find Antonia de Souza?",
	"Father, can you direct me toward the Inquisition?",
	"Do you know of whom you speak, my son?",
	"Ah, my son, I have told you all that I know.",
	"I am afraid repetition does not change the answer, my son. ",
	"You are persistent. Well, if you want the Inquisition, the entrance is in the area of the steps toward the church...",
	"Of course. He's a high-ranking inquisitor, right?",
	"Sorry about that, Padre, but I didn't get that... Eh, forget it.",
	"I know, but I still don't understand... Hrm, forgive me, Padre...",
	"Phew, thanks, Padre.",
	"Right... well, he's in his residence.",
	"One more thing, Padre. Where exactly is the Inquisition's residence?",
	"Right beneath the church.",
	"What do you mean?",
	"I mean what I said... Go, my son, just go. There aren't many who seek out the Holy Inquisition on their own volition...",
	"I got ya, Padre. Well, thanks...",
	"It's right beneath the church, my son.",
	"It's right beneath our church, my son. The entrance is under the stairway.",
	"I see that you're real hard of hearing, my son. I suggest you seek medical treatment...",
	"Humility...",
	"Thanks, Padre.",
	"Thanks again, Padre.",
	"Certainly!",
	"Oh?",
};
