#ifndef COMMON_LAYER_HPP
#define COMMON_LAYER_HPP

#define EXECUTE 0
#define REALIZE 1
#define SEA_EXECUTE 3
#define SEA_REALIZE 4
#define INTERFACE_EXECUTE 5
#define INTERFACE_REALIZE 6
#define FADER_EXECUTE 7
#define FADER_REALIZE 8
#define LIGHTER_EXECUTE 7
#define LIGHTER_REALIZE 8
#define INFO_REALIZE 9
#define SEA_REFLECTION 10
#define SEA_REFLECTION2 11
#define SEA_SUNROAD 12
#define SUN_TRACE 13
#define SAILS_TRACE 14
#define MAST_ISLAND_TRACE 15
#define SHIP_CANNON_TRACE 16
#define FORT_CANNON_TRACE 17
#define ISLAND_TRACE 18
#define SHADOW 19
#define BLOOD 20
#define RAIN_DROPS 21

#endif