#ifndef COMMON_LAYER_HPP
#define COMMON_LAYER_HPP

#define EXECUTE 0
#define REALIZE 1
#define SEA_EXECUTE 3
#define SEA_REALIZE 4
#define INTERFACE_EXECUTE 5
#define INTERFACE_REALIZE 6
#define FADER_EXECUTE 7
#define FADER_REALIZE 8
#define LIGHTER_EXECUTE 9
#define LIGHTER_REALIZE 10
#define VIDEO_EXECUTE 11
#define VIDEO_REALIZE 12
#define EDITOR_REALIZE 13
#define INFO_REALIZE 14
#define SOUND_DEBUG_REALIZE 15
#define SEA_REFLECTION 16
#define SEA_REFLECTION2 17
#define SEA_SUNROAD 18
#define SUN_TRACE 19
#define SAILS_TRACE 20
#define HULL_TRACE 21
#define MAST_ISLAND_TRACE 22
#define MAST_SHIP_TRACE 23
#define SHIP_CANNON_TRACE 24
#define FORT_CANNON_TRACE 25
#define ISLAND_TRACE 26
#define SHADOW 27
#define BLOOD 28
#define RAIN_DROPS 19

#endif