#ifndef COMMON_LAYER_HPP
#define COMMON_LAYER_HPP

#define EXECUTE 0
#define REALIZE 1
#define SEA_EXECUTE 3
#define SEA_REALIZE 4
#define INTERFACE_EXECUTE 5
#define INTERFACE_REALIZE 6
#define FADER_EXECUTE 7
#define FADER_REALIZE 8
#define LIGHTER_EXECUTE 9
#define LIGHTER_REALIZE 10


#define EDITOR_REALIZE 12
#define INFO_REALIZE 13
#define SEA_REFLECTION 14
#define SEA_REFLECTION2 15
#define SEA_SUNROAD 16
#define SUN_TRACE 17
#define SAILS_TRACE 18
#define HULL_TRACE 18
#define MAST_ISLAND_TRACE 19
#define MAST_SHIP_TRACE 19
#define SHIP_CANNON_TRACE 20
#define FORT_CANNON_TRACE 21
#define ISLAND_TRACE 22
#define SHADOW 23
#define BLOOD 24
#define RAIN_DROPS 25

#endif