string QUEST_REACT [196] = {
	"Officer ",
	" has set foot on the ship.",
	" has surrendered.",
	"The ghost is dispelled, evermore. ",
	"The ghost is dispelled, but might it return?",
	"We held them off!",
	"The task is done! The church should be pleased...",
	"The revolt has been put down.",
	"The city of ",
	" is ours!",
	"Someone's been through your pockets.",
	"The time for your cargo delivery is up. ",
	"You failed to return your employer his money. ",
	"You failed to deliver the credit to its destination.",
	" which is in ",
	"Hey, ja hear? Captain ",
	" crossed swords with a bandit they called ",
	". The rogue to rob 'im, but he didn't have none o' that. The big he-man he is, he just out and killed the lout! ",
	"You know, not long ago there was a fight here, right outside the city - Captain ",
	" was set on by bandits. They meant to plunder him, o'course, but... Ooh! Why, it's you! You're him! You sent that scumsponge ",
	" to his forefathers! That was some work, I must say...",
	"Did you hear? ",
	" and his gang of local ruffians attacked Captain ",
	"! Here's the good part, though! Not only did he refuse to pay; he set into them, and slaughtered them all!",
	"Did you hear? Some captain slew a poor girl in the jungle! The poor girl's name was ",
	". Oh, that bastard deserves to be strung up with razor twine!",
	"You hear the news, Captain ",
	"? Someone killed poor ",
	". Her only crime was setting foot outside the city walls! Oh, she was such a good girl...",
	"Her name was ",
	", and she died in the jungle. That's no surprise, though. It's a wild world, outside these walls...",
	"Surely you've heard? Some sea-captain rescued a girl from bandits, name of ",
	"? They say he literally yanked her out of the brigands' claws! I say, good chap! Good show! A true gentleman, wot.",
	"You hear that Captain ",
	" saved a supple lass from some jungle thugs? Name of ",
	", she was... Oh... Oho, so it was you! So how was it? You get any action? ",
	"You ever hear of a girl named ",
	"? That's one lucky girl. She was pounced upon by jungle bandits, not long ere. Thugs, no doubt. Been a rash of that. Before they got the chance, though - in stepped Captain ",
	"Oh no, dear ",
	"! No one would think for a moment you could leave a fragile woman for the desecration of jungle scum. Ah, poor ",
	". I just don't have the words...",
	"You know, Captain, you are a first-class bastard. How could you leave a defenseless girl in the jungle? Can you even fathom what they did to her? Poor ",
	"... no one will want to marry her now...",
	"Did you hear that some captain killed a defenseless girl in the jungle? It was poor ",
	". Oh, God, that bastard deserves to be drawn and quartered!",
	"Oh, Captain ",
	" - you hear someone killed poor ",
	"? All she did wrong was set foot outside the city. And she was a good girl...",
	"Her name was ",
	", and she died alone in the jungle. No big surprise, of course. I tell you, it's no easy world outside these walls...",
	"Recently, one of our officers and his men were found dead outside the city. Who could have killed them? And whatever for?",
	"Did you hear? Some of our men were just found dead in the jungle... Our commandant is always sending patrols outside the city, but now... I don't know where we go from here.",
	"God damn! Some demon killed our patrol outside the city! Not a man left standing...",
	"They say Captain ",
	" ran into some ",
	" troops in the jungle - and slew them the last man! Hah, those ",
	" are some wusses! ",
	"You hear that Captain ",
	" was beaten down by our border patrol? Ho ho! Some buccaneer!",
	"Hm. I hear you were held up by our border patrol. I'm not sure how well these measures are working out...",
	"Our commandant means to intensify our border patrol. Well, you know that yourself - you having been waylaid and all. Oh yes, I hear all...",
	"You hear? Governor ",
	" has charged a certain Captain ",
	" with besting the infamous ",
	". And I hear our man actually did the job! What do you say to that! I bet the Governor is pleased...",
	"I hear some bold soul agreed to track down and devoid the horrible ",
	". And I think he did it! 'Least, that's what they're tellin' me!",
	"Hah! At long last, the Governor has decided to bring order to the jungle! I hear he brought in Captain ",
	" to track down and squash the infamous ",
	". And you know what? The bandit's dead! Gotcha!",
	"Did you hear? Governor ",
	" has brought in Captain ",
	" to scout out an enemy spy... in this very city! And you know, he did just that! No more spy! Spy gone! What a guy, huh?",
	"Lo and hark! Our fair Governor and lord has charged Captain ",
	" with the location of a subterfugenous ne'er-do-well within our cloistered community. And what ho! Did our man succeed his charge? Did he ever! ",
	"You hear the news? Governor ",
	" charged a certain Captain ",
	" with finding and destroying the smugglers. And hey, it's been done! Look at that. ",
	"Governor ",
	" has ordered Captain ",
	" to find the smugglers in the vicinity of our city. He found and killed them, so I guess the shop prices should rebound any old time now...",
	"pirate ",
	"brigand ",
	"You hear about the big fight between Captain ",
	" and the pirates? Oh Lordy-loo. They say the scoundrels got away in the end...",
	"Captain, how could you let those frickin' pirates escape?! Ah well. It's a real shame, though... A real shame.",
	"Oh, Captain ",
	"! How could you miss those pirates? You're going to go after them, right? Tell me you're going after them!",
	"You heard? Governor ",
	" brought in Captain ",
	" to wipe out the pirate who's been terrorizing the local waters. And lo, he went and sunk the ",
	"Some brave captain volunteered to seek out and gut the pirate that was plundering our merchants. And it seems he's done just that! No more ",
	"Hah! At last our governor has taken the initiative to make the waters of ",
	" safe once more! He brought in Captain ",
	" to track down the marauder who's been giving our merchants such a hard time. And whaddaya know, he went and sunk the ",
	"You heard? Governor ",
	" brought in a certain Captain ",
	" to finding and destroy the pirate what's been plunderin' our merchants right before our eyes! And hey, the bad man went and plundered ",
	" as well! Whaddaya say to that!",
	"So, Captain. Howja like your journey on the pirate ship? You all right? They didn't... hurt you, did they? You sittin' down okay? Haw haw haw!",
	"Ooh, Captain... tee-hee... I hear tell you got your share of a beating recently. How do you find the local pirates? Want to keep looking for them? Hee hee hee!",
	"Alberto",
	"Gaudio",
	"The sentry must be destroyed!",
	"The sentry must be destroyed!",
	"Orangemann",
	"Howard",
	"Tatum",
	"Forward, my eagles!",
	"Morris",
	"Williams",
	"Favorite",
	"Alain",
	"Smith",
	"Santa Águeda",
	"Tom",
	"Atterbury",
	"Lambert",
	"Groff",
	"Dick",
	"Manson",
	"Escado",
	"Manoel Rivero",
	"Pardal",
	"Colonel Thomas",
	"Lynch",
	"Thomas",
	"Modyford",
	"Colonel Thomas",
	"Lynch",
	"Captain ",
	"Cooper",
	"Guillaume",
	"Doutey",
	"About an hour has passed...",
	"La Rochelle",
	"Lorain",
	"de Graf",
	"Cominte",
	"Francisco",
	"de San Agostinho",
	"Joseph Nunes",
	"da Fonseca",
	"Desperate",
	"Jacob Lopez",
	"da Fonseca",
	"Rock",
	"the Brazilian",
	"Impetuous",
	"Andre",
	"d'Estre",
	"Forward, my eagles!",
	"Edward",
	"Mansfield",
	"Manoel",
	"Rivero Pardal",
	"Escado",
	"Mo?se",
	"Vauquelin",
	"Orleans",
	"Captain",
	"Ansel",
	"Zeus",
	"One day later...",
	"Peter",
	"Stuyvesant",
	"Desdichado",
	"Anna Ramirez",
	"de Leiva",
	"José",
	"Ramirez de Leiva",
	"Juan",
	"Galeono",
	"Mario",
	"Esteban de Leiva",
	"Roberto",
	"Vincenzo de Leiva",
	"Miguel",
	"de Valdez",
	"brother is delivered",
	"Rapturous",
	"Forty minutes passed, over the course of the service.",
	"Leif",
	"Ericson",
	"By my foot, I will julienne every stinkin' frog-eater on this God-forsaken island!",
	"Unconscious..",
	"You hear? Someone attacked Cecile Galard!",
	"They say you saved Cecile Galard, when she was attacked.",
	"Cecile Galard was attacked in her own home, on the Eva!",
	"It's well that you saved poor Cecile! I don't know where the admiral's eye is turned these days...",
	"Oh my. If this goes on, we'll be fending off bandits right in our own homes, like Cecile Galard!",
	"Have you heard? Cecile Galard was killed, and in her own home!",
	"They say you failed to protect poor Ms. Galard...",
	"Hmm... Funny thing about these murders, they started right about the time you turned up in the City. And now here's Cecile Galard...",
	"A pity you couldn't save poor Cecile. She was a handsome person...",
	"Another murder. This time it's Cecile Galard. She was the city's oldest inhabitant, you know...",
};
