string REACT_FUNCT [253] = {
	"Bluebird",
	"Emilio",
	"Garcia",
	"Captain",
	"Goodley",
	"John",
	"Avery",
	"Orry",
	"Bruce",
	"Leon",
	"Frigate Leon",
	"Elusive",
	"Battleship",
	"Captain ",
	"ÿ they call ",
	" has sailed away again. Rumor has it, he was bearing in on ",
	"You can find the captain of the ",
	"ÿ? If so, he went to ",
	"If you need Captain ",
	"ÿ, then you'll have to make waves for ",
	". That's whence he departed.",
	"Captain ",
	"ÿ, the man they call ",
	", has sailed off again. Rumor has it, he was heading toward ",
	"You can find the captain of the ",
	"ÿ? If so, he went to ",
	"If you need Captain ",
	"ÿ, then you'll have to make waves for ",
	". That's whence he departed.",
	"Morning has crawled her way out of bed...",
	"Captain ",
	"ÿ, the man they call ",
	", has sailed off again. Rumor has it, he was heading toward ",
	"You can find the captain of the ",
	"ÿ? If so, he went to ",
	"If you need Captain ",
	"ÿ, then you'll have to make waves for ",
	". That's whence he departed.",
	"Brigantine 'Arrow'",
	"the Queen",
	"Hill",
	"Corner",
	"Be very careful with Augusto Brahms. The damned sorcerer...",
	"I advise you steer clear of Augusto Brahms. He is truly a dreadful man...",
	"Chad",
	"Capper",
	"Jean",
	"Bourdie",
	"Lewis",
	"Grommer",
	"Freck",
	"Herring",
	"Raul",
	"Cruz",
	"Gerard",
	"Foure",
	"John",
	"Workman",
	"Hill",
	"Brunner",
	"Armo",
	"Dulaine",
	"Pedro",
	"Hurtado",
	"Gilles",
	"Barou",
	"Tristan",
	"Borcher",
	"Rojel",
	"Haag",
	"Dominic",
	"Legro",
	"George",
	"Stokes",
	"Henry",
	"Folder",
	"Felix",
	"Mendoza",
	"Roger",
	"Vowler",
	"Andre",
	"Labore",
	"Stefan",
	"Klein",
	"Thomas",
	"Flann",
	"Pablo",
	"Barades",
	"padre",
	"Angel",
	"Sandra",
	"Gomez",
	"Monica",
	"Right",
	"Eric",
	"Jost",
	"Gabriel",
	"d'Exmes",
	"Thomas",
	"Boyle",
	"Augusto",
	"Brahms",
	"Henrik",
	"Vedeker",
	"Alice",
	"Taylor",
	"Orelie",
	"Bertine",
	"Lea",
	"Toors",
	"Elisa",
	"Calvo",
	"Cecile",
	"Galard",
	"Thomas",
	"Bull",
	"Fritz",
	"Holt",
	"Roger",
	"Adin",
	"Nick",
	"Nolte",
	"Jeury",
	"Graside",
	"Milon",
	"Bergie",
	"Milon",
	"Bergie",
	"Milon",
	"Bergie",
	"Casper",
	"Longmann",
	"Dennis",
	"Hopfer",
	"Foucher",
	"Hecht",
	"Serj",
	"Chambon",
	"Felipe",
	"Armas",
	"Felipe",
	"Armas",
	"Juan",
	"Cobo",
	"Tagelle",
	"Edo",
	"Zenon",
	"Barrio",
	"Miguel",
	"Batiz",
	"Martin",
	"Camus",
	"Mark",
	"Bishop",
	"You know, Alice Taylor's husband has got himself thrown in jail. There was some uproar at the Admiral's residence. And now poor Alice needs to find a way to bail her man out...",
	"Lea Toors made some mention of Leyton Dexter. The man veritably vanished into the ether...",
	"You know, Dominic Legro has his eye out for a bottle of wine. I get what his problem is. It's not like it's hard to stroll down to the general store and buy a bottle...",
	"I hear you wiped out the Narwhal gang! Well isn't that something!",
	"Wahey! Thanks to you, the Narwhal clan no longer exists! I say, the citizens are duly grateful to your person.",
	"Hm. I know you're a hero and all, but are you sure you needed to be so... severe with the Narwhals'?",
	"Allow me to gaze upon the man who marked his name in the City Annals! I can tell you, I had seen quite enough of those Narwhals...",
	"Thanks to you, San Gabriel is now free.",
	"To tell the truth, I highly doubt the Narwhals were involved in the murder of that militiaman and Labore. Real unlikely, I say...",
	"With the Narwhals gone, it's hard to predict how the Caspers will react...",
	"Why, you're a hero, I do declare! You just strolled right into our City, and look at you! Making a name for yourself already! Clearing out the whole Narwhal clan! Gosh a-landen!",
	"The Narwhals only got themselves to blame. The admiral was right on target. They'd gone unchecked way too long. So you're okay in my book! ",
	"How you dealt with the Narwhals, I have no notion. Warriors, they were - the lot of 'em...",
	"Florence",
	"Slot",
	"Didja hear?! Hill Brunner has gotten himself killed!",
	"You heard the latest news? No? It's awful! Hill Brunner is dead! Murdered!",
	"Hill Brunner, the tavern owner, has been found dead - in his own cellar. Oh my!",
	"Now someone went and gutted our tavern owner! First Andre Labore, now Hill Brunner. Who's next, I ask you! ",
	"You know that Hill Brunner's dead? He is! Killed in his wine cellar, even!",
	"Poor Hill Brunner... Bless 'im on his final journey. What a great loss to our City. He was, after all, our oldest resident!",
	"You know that Hill Brunner is dead? What will become of our tavern now?",
	"Florence",
	"Slot",
	"You hear? Hill Brunner has been killed!",
	"Ain't you heard the claptrap? Hill Brunner's flat daid!",
	"Hill Brunner, the tavern owner, has been found dead - in his own cellar. Oh my!",
	"Now someone went and gutted our tavern owner! First Andre Labore, now Hill Brunner. Who's next, I ask you! ",
	"You know that Hill Brunner's dead? He is! Killed in his wine cellar, even!",
	"Poor Hill Brunner... Bless 'im on his final journey. What a great loss to our City. He was, after all, our oldest resident!",
	"You know that Hill Brunner is dead? What will become of our tavern now?",
	"They say you killed all the Caspers! Interesting...",
	"Can't say I'm sorry for those morons. The Caspers are resting right where they should be...",
	"Oh, you're a demon! First the Narwhals, now the Caspers! Dashing... Our dark knight!",
	"Yeah. Nice work you did, with that sword o' yours. The Casper clan has sunk into dank oblivion... And that's great!",
	"Y'know... the Caspers didn't really bother me. So not so sure what I think of all this business. Ain't pleasant to see anyone loose his blood, 'specially without a need to it...",
	"They say there was a big fight last night, on the Ceres Smithy...",
	"Last night, Alice Taylor, our lady of the Ceres Smithy, heard some fuss up on deck. It sounded like a veritable tempest of blood... Lord knows, I'd have just pulled up the covers!",
	"Flora",
	"",
	"You hear? Poor Armo Dulaine has been killed! Oh, what a good girl she was...",
	"My God, now Armo is down. Maybe it's time to search for a nice refuge...",
	"Where has the admiral been looking?! There were already several murders, and he did nothing. And now poor Armo as well...",
	"The weather is worsening. This is perhaps the last storm we'll see...",
	"Oh my. Lookee there. I reckon another storm's comin' in. ",
	"Blast these storms! I'm sick of them! And look, there's another one gathering right now on the horizon. Just to spite me, I venture...",
	"The weather's really going downhill. I imagine a storm can't be far off now...",
	"A storm is coming. Well, that's it. Time to batten down the hatches again. Several more days of squatting and twiddling our thumbs. Lovely.",
	"They say someone robbed Eric Jost, the storekeeper...",
	"Mictlantecutli",
	"demon",
	"Ozzie",
	"Silvio",
	"Ricci",
	"Montezuma",
	"Mexitli",
	"Auisotl",
	"Andrew",
	"Baynes",
	"Jeremy",
	"Pitt",
	"Captain",
	"Hobart",
	"Governor",
	"Steed",
	"Colonel",
	"Bishop",
	"Ed",
	"Griffin",
	"Tobias",
	"Hells",
	"Nathaniel",
	"Hagthorpe",
	"Nicolas",
	"Dyke",
	"Ned",
	"Ogle",
	"Weapon:",
	"The avatar is about to be relieved of his sword!",
	"James",
	"Nettall",
	"Governor Steed hasn't forgiven Peter Blood",
	" for his lack of initiative, that night.",
	"Having lost the privileges of a Bridgetown doctor, ",
	"Peter has once more been barred from the city and left to rot on Colonel Bishop's plantation.",
	"Two years thence, in the heat of anger, Colonel Bishop shot Peter Blood dead.",
	"Thus the story was over, before it really began...",
	"Later...",
	"Sergio",
	"Crespo",
	"Stuart",
	"Winterwood",
	"Arnold",
	"Summerlite",
	"Jacques",
	"Swallow",
	"The next morning...",
	"John",
	"Mayner",
};
