string DLG_TEXT_STR [23] = {
	"What questions?",
	"What do you desire?",
	"Some time ago, in my store, you tried to ask me a question...",
	"This is your third question today. I need to trade, not conduct empty conversations...",
	"Questions, again? Maybe we should focus on trading?",
	"Sorry, never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Yes, indeed I tried... In your store...",
	"One, two... you're right, third it is!",
	"Hm, shall we trade?..",
	"I have an order of the fort's commandant for you.",
	"That's true, I have received said order. Let's settle the bill with the prices we mentioned, mynheer.",
	"You again, that's good. Let's continue our special deal.",
	"Our gallant captain again! Excellent. Let's continue...",
	"Captain, glad to see you on the same occasion. Well, let's continue the trade on this special consignment of goods.",
	"Let's start trading.",
	"Let's continue...",
	"Indeed, we should...",
	"Oh, please don't sneer, I ask you. I'm bored to death with this myself...",
	"*Cough* Heh, glad to see you in good health, captain. Even more so after such a slaughter!",
	"Hm, yes, that one one tough mess...",
	"I had business with you, captain, and now I see that you're good in something else apart from trading. And those Englishmen will leave you alone for a long time now... Thank you, mynheer, thank you from the bottom of my heart.",
	"Oh don't mention it, continue your trade.",
};
