string DLG_TEXT_STR [21] = {
	"What questions?",
	"What do you desire?",
	"Some time ago, in my store, you tried to ask me a question...",
	"This is your third question today. I need to trade, not conduct empty conversations...",
	"Questions, again? Maybe we should focus on trading?",
	"Sorry, never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Yes, indeed I tried... In your store...",
	"One, two... you're right, third it is!",
	"Hm, shall we trade?..",
	"Excuse me, did Edward Low buy a ship from you?",
	"Me?! You're confuse me with someone else. I'm a trader, but ships... I don't trade in ships! Young man, you need to ask at the shipyard, with the shipbuilders. Yes, yes, ask them, and I'm for everything else!",
	"You already asked. No, he didn't.",
	"No, young man, no...",
	"Oh, you're such a bore!!",
	"Yes, but your puny town doesn't have a shipyard!",
	"Understood...",
	"Aha, I see...",
	"Hm, I'm leaving already...",
	"Can't help you with that, my desire wouldn't be enough to conjure a shipyard in our town. Ask someone else...",
	"I see... Well then, thanks for that.",
};
