string DLG_TEXT_STR [20] = {
	"Ask. What do you need?",
	"We've just raised that topic. I gather you have forgotten...",
	"This is the third time today you've been talking about some question...",
	"Listen, this is a store. People buy things here. Don't distract me!",
	"You know, ",
	", perhaps next time.",
	"Indeed, I forgot that...",
	"One, two... you're right, third it is!",
	"Hm, I won't...",
	"Hey, I'm looking for a merchant by the name of Jacob Lopez de Fonceca. He came here with some business, but didn't returned yet.",
	"Saw him bout a month ago. I must say that was a strange meeting. In the morning, met Jacob in the street, we greeted each other, and he said he would come by about dinner time with some business. But I haven't seen him since.",
	"You already asked about it, I answered you.",
	"I'm telling you, you already asked about this Jacob.",
	"Alright, go away and don't bother me! Are you mad or something?",
	"Did he mention anything specific: where he was staying, where planned to go?",
	"Hm, oh yes...",
	"Yes, indeed I did...",
	"I'm sorry, ",
	"No, nothing specific.",
	"I see... Thank you.",
};
