string DLG_TEXT_STR [29] = {
	"Ask. What do you need?",
	"We've just raised that topic. I gather you have forgotten...",
	"This is the third time today you've been talking about some question...",
	"Listen, this is a store. People buy things here. Don't distract me!",
	"You know, ",
	", perhaps next time.",
	"Indeed, I forgot that...",
	"One, two... you're right, third it is!",
	"Hm, I won't...",
	"Good man, I am looking for one unusual ship, a xebec called 'Blue Bird'. Heard anything about her? I am ready to pay for any information regarding her...",
	"I wanted to tell you that I finally caught the 'Blue Bird'. She won't serve you any more.",
	"I know nothing about this ship. If this is everything you wanted, then leave.",
	"Again? I told you everything.",
	"What, again the same old song?",
	"Oh, when will it come to an end?! I ask you, don't distract me from my work!",
	"You're not very welcoming, dear sir!",
	"Yes-yes, I remember...",
	"Aha.",
	"Alright, alright...",
	"I'm not a dear sir to you, didn't have the pleasure of gulping rum and sleeping under a fence in your company.",
	"Oh, really? I simply asked. Well fine, thanks for at least that much...",
	"Get lost, idiot...",
	"You're tiring me...",
	"Hm, you seem to have lost your mind...",
	"Again about the same things? What do I have in common with this?",
	"Oooh, what epithets!",
	"Yes-yes.",
	"I'm in perfect order!",
	"Maybe nothing, maybe something.",
};
