string DLG_TEXT_STR [40] = {
	"Ask. What do you need?",
	"We've just raised that topic. I gather you have forgotten...",
	"This is the third time today you've been talking about some question...",
	"Listen, this is a store. People buy things here. Don't distract me!",
	"You know, ",
	", perhaps next time.",
	"Indeed, I forgot that...",
	"One, two... you're right, third it is!",
	"Hm, I won't...",
	"Listen, pal, a certain Azzy sent me to you.",
	"I'd like to take my run now.",
	"Listen, I need to find Azzy immediately!",
	"Oh, Sir Azzy sent you to me?! Very glad to hear about him - such a pleasant and trustworthy person! So what did he tell you?",
	"Person?! Hm, well fine... He told me that I can take rum run from you for free, any quantity I want.",
	"Well, not exactly so. You can take 300c of rum once a day. And free of charge, of course.",
	"Sounds good, it suits me. Shall we start the procedure?",
	"I can give you 300c of rum.",
	"You already took today's shipment of rum.",
	"I'm telling you, you've got enough of your rum for today. Come back tomorrow.",
	"Tomorrow, come back tomorrow...",
	"Alright, taking it all!!!",
	"Indeed, I did...",
	"I'm sorry...",
	"Well, see you tomorrow, then.",
	"You may commence loading the goods into the holds. Rum was dispatched to you.",
	"That's good. Thank you, my friend.",
	"I don't know where Azzy is. Simply have no idea.",
	"Told you already, I don't know where he is.",
	"I repeat, I don't know where Azzy is.",
	"Telling you once again, I do not know where Azzy is. And I don't want to know.",
	"But you're receiving the rum from him before I take.",
	"Yes, I remember, indeed",
	"No need to repeat, I remember.",
	"Ah, that's a shame. Downright pity, it is...",
	"I don't know how your rum is brought here. I simply leave the backyard shed open for the night, and in the morning the rum's already there. I leave a third to myself, two thirds go to you. Such is the essence of this commercial transaction.",
	"Damn it... This means I'll have to sneak on the ones who bring your rum at night!",
	"I wouldn't advise you to do that. My assistant was also curious, hid himself in the shed during the day, wanted to peep. Only we've found him in the morning next to rum, completely bonkers, now he sits here for days on end, drooling and mumbling.",
	"I don't know who this Azzy is, but haven't been happy with the gratuitous rum for a long time. I'm afraid for myself, you know.",
	"And you'll see nothing anyway. I already tried locking the shed, thought I'd manage without this rum. And the rum was right there in the morning again. And that's it, pal.",
	"Yes, it's clear that I won't find Azzy here.",
};
