string DLG_TEXT_STR [13] = {
	"Ask. What do you need?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've come in here about some  question...",
	"Listen, this is a store. People buy things here. Don't distract me!",
	"You know, ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Three it is.",
	"Hm. I won't...",
	"(To Isabella): So are you going to pay or should I call the soldiers?",
	"How dare you, scoundrel! Apologize to Señora this very instant or I will pierce your fat body!",
	"Certainly, señor Capitan.",
	"Now we're talking.",
};
