string DLG_TEXT_STR [21] = {
	"Can I help you?",
	"What do you need?",
	"Just recently, you tried to ask me a question...",
	"Haven't heard such questions in the Tortuga store for a long time now...",
	"Again, questions, questions, questions...",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"Well, if you say so.",
	"Queeestions, yes...",
	"Hey, did Pierre le Picard visit your store? I was told that he was headed here.",
	"He did, about two hours ago. Bought another bunch of expensive knickknacks and went on to waste his life.",
	"Señor, let's get back to trading. Why do you keep repeating the same questions?",
	"You already asked me about Pierre...",
	"Listen, why don't you ask about Pierre somewhere else, eh?",
	"Indeed, Pierre's in Clover right now... So, does he often drop in with this kind of business?",
	"You were? Well, probably...",
	"Sure, I wouldn't mind some trading...",
	"Yes, perhaps I'll ask somewhere else.",
	"Comes here nigh every day, with rare exceptions.",
	"Well, some people are just lucky! Anyway, I'm gonna go look for him. Thank you.",
};
