string DLG_TEXT_STR [47] = {
	"Ask. What do you need?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've come in here about some  question...",
	"Listen, this is a store. People buy things here. Don't distract me!",
	"You know, ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Hm, I won't...",
	"You don't look like my average customer. What do you need?",
	"Hm? Oh, the name's ",
	". You are a sinner, my friend, a very big sinner. I was sent by the Holy Inquisition. The Pope's pardon is offered to you; the indulgence will cost you 50,000.",
	"You did it! I am very grateful to you! Here's the agreed sum of 100,000 for the both of us.",
	"Well, that's perfect. I must congratulate you on resolving this issue so successfully.",
	"Did you learn anything about Jacob?",
	"Not yet, but I'm handling it.",
	"Jacob and I are grateful to you. Even though you came with bad news, you still did us a great service. Thanks.",
	"Bah, no problem.",
	"Even under successful circumstances for developing my trade, I am unable to pay such a sum. I don't deceive people and I don't make profit of it. All my money is invested right now.",
	"So you are refusing to pay?",
	"If I had such a sum at my disposal, I would pay.",
	"I see you are not grasping the entire picture, my friend. Even if I pitied you, which would easily cost me my career, the inquisitors won't leave you alone, wherever you go or however you hide. If they put you on their black list, you are doomed. In any case, if you don't pay, I will have to kill you.",
	"I thought I already explained to you that I don't have the money.",
	"If you don't value your own hide and won't even give 50,000 for it, then there are no problems. I will take your life.",
	"I'm curious... Am I the only one one with such an honor, or are there more candidates for the indulgence?",
	"Hm, what a pertinent question! I was just about to ask about the whereabouts of your partner, Jacob Lopez da Fonseca?!",
	"I, too, would like to know... Wait, I think I found a way around the issue that would suit both of us.",
	"At present, I wouldn't even have half of this sum. But if you agree to do me a favor, by the time you are finished, I will have collected the money you need.",
	"Go on.",
	"My partner, Jacob Lopez da Fonseca, went to Panama on trading business and disappeared. He's a good and honest man. I'm worried about him.",
	"If you can find him, our families would be able to collect the needed sum.",
	"Um, maybe I will agree to that... Prepare 50,000 for yourself and as much for your partner. See you again.",
	"Yes, indeed. You have done us a great favor by finding Jacob. Thank you.",
	"Bah, no problem. Farewell.",
	"Hey. Jacob asked me to find a certain book - a Gospel very dear to you, from Judas I think...",
	"And?",
	"Well, I managed to do it. I've got the Gospel.",
	"Oh, nothing really... Farewell.",
	"You don't say! Listen, I'd like to have it. It is very important to our community of Jansenists. You can't imagine what Jansenists had to go through to possess this Gospel...",
	"Why, I can perfectly imagine. Take it.",
	"Oh God Almighty, it truly is IT, the Gospel of Judas Iscariot!",
	"Listen, you probably know that the reward for finding this relic is one million...",
	"What?!",
	"Yes, yes. One million. I happily hand it over to you!",
	"I take it with great pleasure... Perhaps I should go. I am feeling a little dizzy right now...",
	"Go, my friend. Farewell. Our entire community will be forever grateful to you! Ah, I can just imagine what will happen once everyone learns that the lost artifact of Samuel Coheno is found...",
	"Farewell. I won't disturb you now...",
};
