string DLG_TEXT [58] = {
	"Oho, the white man returns to our company? I saw you on the dam.",
	"I welcome you, noble savage! My name is Great Captain ",
	". And what do your friends call you?",
	"Mexitli.",
	"You live here, Mexitli? Who else is here, apart from you?",
	"My brother, Auisotl.",
	"Listen, I see you're quite the typical Aztec so maybe you can help me. It's a bit embarrassing, but I met an Indian over there, painted and dressed up from head to toe, who had the queerest stories for me. He's over there, by the water, said his name was Montezuma...",
	"Hush! That is a name we do not utter here! If Mictlantecuhtli hears you walk the streets of Tenochtitlan, speaking of he one who must not be named, he will be angry, and will make you his servant ahead of your time!",
	"Is Mict... Mictla... Oh, whatever. Is he your god of the dead, then?",
	"He is the one. And I advise that you respect him. Better still, Make him an offering.",
	"Offering? What kind of offering?",
	"The usual - the blood of soldiers you have captured. Bring them here, and then go with them to the sacrificial temple. You should cut out the heart of a warrior while he is still alive, and sprinkle Mictlantecuhtli's sacrificial stone with his blood.",
	"Somehow I don't really want to do that...",
	"Ah. Well, then you will have no luck here. Mictlantecuhtli will be watching you, and will take you.",
	"Well, we'll see about that... How many warriors do you sacrifice, then? I heard that you have a lot of gods...",
	"There were a lot, once. Now, we only serve Mictlantecuhtli. My brother and I neither capture nor offer soldiers, as Mictlantecuhtli promised us his protection in life after death. So we just do odd jobs around the city. We don't even hold weapons.",
	"Oh, so Mictlantecuhtli actually promised you that in person? Ho ho, I guess once a savage always a savage. First that nameless dandy on the shore, now you with your brother here... No offense, but I'm not so easily convinced by your Mictlantecuhtli. Tell me, is there anything of interest here in your Tenochtitlan?",
	"Nothing special. The temple of Great Life Force is the biggest landmark. The pyramids nearby hold the temples of ten gods. The pyramid with a round tower, directly opposite the Temple of Great Vital Force, that's the temple of White Gods is. And we have a swimming pool...",
	"Listen, how could I get into this Great Temple of yours?",
	"I wouldn't, if I were you. We won't stop you, but Mictlantecuhtli will send his warriors after you. And the  temples are protected by his servants - the great warriors of the past.",
	"I see... Well, farewell, Mexitli. I'll chat with your brother if I find him.",
	"He will be very glad. No one else lives in Tenochtitlan, so newcomers are interesting to us.",
	"Hm. I see...",
	"I welcome you, Captain ",
	"And greetings to you, Mexitli",
	"The White Captain went to the Temple of Great Life Force and survived? I am very surprised.",
	"What, didn't think you'd see me alive?",
	"No. I made a bet with my brother, as to when Mictlantecuhtli would take you. It seems that nobody won.",
	"I spoke to your Mictlantecuhtli. He had a lot to say. ",
	"You are lucky, White Captain. Mictlantecuhtli talked to you and then let you leave!",
	"Also, he gave me this jade skull thing.",
	"Yes, this skull has power over the dead. You might want to remember that. You are indeed very lucky, White Captain.",
	"Oh, I know. Well then. Fare thee well, good Mexitli.",
	"Oho. A white man, in Tenochtitlan? Very interesting...",
	"Hello, my Aztec friend. I take it you're Auisotl, then?",
	"I am. And who are you?",
	"Why, I'm Great Captain ",
	". Nice to get friendly with the locals, as they say. I already met your brother, Mexitli.",
	"I see. Tell me, White Captain, what are you doing in our city?",
	"I'm looking for something. Listen, maybe you could give me a hint. How do I get into the Temple of Great Life Force? Oh, and I also need to visit the Temple of White Gods...",
	"Are you quite mad, White Captain? Mictlantecuhtli will devour your body and soul, you know.",
	"Oh, pshaw. Look, if you know something, tell me.",
	"You are a foolish man, White Captain. I must go make a bet with my brother. I give you until mid-day tomorrow. ",
	"Is that all you can tell me?",
	"My brother and I serve the great Mictlantecuhtli. What did you expect to hear from us?   \nBut you are an odd man, White Captain. I like you, even though you are stupid. I will say that the entrance at the top of the pyramid is not the only way into the Temple of Great Life Force...",
	"Well, thank you for at least that much, Auisotl.",
	"You are still alive, White Captain?",
	"Looks that way, Auisotl.",
	"Did you go to Mictlantecuhtli, White Captain?",
	"I did.",
	"And you are not his servant?",
	"No. As you can see, Auisotl, I am still alive.",
	"Oho! Surely you are a great man, if Mictlantecuhtli let you go!",
	"Let me go, nothing! He gave me a jade skull!",
	"The skull of revival?! I cannot believe my eyes.   \nWell, Auisotl wishes your best of luck. Farewell, White Captain.",
	"Farewell, Auisotl. You're not such a bad chap.",
	"My brother and I will remember you, White Captain.",
	"Yes, all the best. Pip pip.",
};
