string DLG_TEXT [24] = {
	"I don't want to talk.",
	"Hmm, I see...",
	"Señor, get out of here! Leave immediately!",
	"What's the problem?",
	"Everyone died! To the last, consumed by hellfire!",
	"Who died?",
	"Ah... Argh, why did we go there in the first place?",
	"Calm down, friend! Tell me what happened, straight and slow...",
	"Very well, Señor. My name is Silvio Ricci.   \nIt all began when Don Esteban hired me, amongst a company of men, for an expedition to El Dorado. We landed in this bay, and set off for the Indian city, which Cortes himself looted more than hundred years ago. My God, what were we thinking?!",
	"Hang about, you're doing it again... Quit it, will you?",
	"Very well, Señor...   \nA week ago, nearly fifty men entered this jungle. And now, I am the only one to return.",
	"So where are the others?",
	"They are dead, Señor! They were consumed by the fires of hell!",
	"What?!",
	"I speak the truth, Señor! Fire from nothing! The bridge was pure stone! Not a trace of combustible material!    \nSeñor, the Devil himself lights that fire!",
	"So you're saying you ran into the Devil? ",
	"Perhaps... Perhaps it was!    \nOver there by the water, near the city, is an Indian, in fancy dress... We were perhaps ten, those who survived the flames. We were already thinking of retreat, when fool Pedro chose to take some gold trinkets from the red man. As he reached out, his head was suddenly caved in with a cudgel. It split open like a ripe melon!   \nAnd then that devil came after the rest of us, beating all he found everyone with his mace. One blow, and your head is in pieces. Only I had the fortune to escape...",
	"And where's your chief? Don Esteban, was it?",
	"Doused in the infernal flames.",
	"Hmm... Sticky way to go. ",
	"Señor, don't go there! This place is cursed!",
	"Thanks, I'll take the risk.",
	"It is your choice, but I have had my fill. Farewell, Señor! God rest your soul...",
	"Yes, goodbye.",
};
