string DLG_TEXT [139] = {
	"Ooh, another white one has come. For what did you come to Tenochtitlan?",
	"To see it for myself. That's the kind of guy I am; I want to know everything.",
	"Greetings, white man. Why did you come to Tenochtitlan?",
	"To see it for myself. That's the kind of guy I am; I want to know everything. So you're an Aztec, then?",
	"I see... But do you even know where you are?",
	"I know that this city is the Indian capital. And that Cortes himself went through this place with his fire and blade.",
	"Yes, it is so. This city has the name of Tenochtitlan, and the people that lived here throughout the centuries were called the Aztecs.",
	"I see. And you too are an Aztec, I believe?",
	"Yes, I am an Aztec, you are right. I am called Montezuma. And how can I address you?",
	"I'm called Captain ",
	". Montezuma... I think that was the name of an Indian leader.",
	"I am named in his honor   \nTell me, White Captain ",
	", what are you going to do now?",
	"I want to get into the city.",
	"You probably understood that it is not so simple to accomplish. The dam leading to the city is reliably protected by the spell of fire. Not long ago many white men came here. All of them were consumed by fire...",
	"Well, not all. As far as I know, some of them had their skulls crushed by you.",
	"It is so, but they have only themselves to blame for their death. They should not have touched Montezuma.",
	"All right, let's not talk about it. Instead, tell me is there anything interesting in the city? Does someone live there, or not? And what are you doing here, on this coast?",
	"Oh, the story is a long one. Prepare to listen, White Captain.",
	"My ancestors came to the shores of this lake named Texcoco many centuries ago. At the time they were called the Mexica people. The shores of the lake were populated by other tribes which have been hostile towards newcomers. But our supreme god Huitzilopochtli commanded them to remain here. Then Tenoch, the leader of the Mexica, made a decision to remain on the shores of Texcoco, and the Mexica started to call themselves the Tenochca.",
	"Coxcoxtli, the leader of the powerful city of Culuacan, decided to exterminate the Tenochca. Then my ancestors left the shores behind and started to live on a boggy island in the middle of the lake. Time passed, and the Tenochca managed to fortify the island and even to construct a dam leading to the shore. And when the Tenochca elected Itzcoatl as their leader, a confederation of tribes was created, and the various people of this confederation became known as the Aztecs.",
	"Blessed times had come, the Aztecs ruled the world. All tribes paid tax to the Aztecs, delivered food, slaves and concubines. The sacrificial blood - food of our gods - painted the waters of Texcoco red. The best warriors were sacrificed to Tezcatlipoca, the patron of our priests, and ordinary warriors were burnt in honor of Camaxtli. Women gave their blood to the goddess Mayahuel, and the children - to the god of fertility Tlaloc.",
	"Thus it was for more than hundred years. But then came the Spaniards and Tenochtitlan was besieged. And our heroes led by Cuauhtemoc have fallen.",
	"Now the god of kingdom of the dead Mictlantecuhtli rules in Tenochtitlan.",
	"So, the city is uninhabited?",
	"No. Both alive and dead people live there.",
	"Say what?",
	"Mictlantecuhtli has the power to revive people. Mictlantecuhtli has returned warriors to life to guard the temples of gods, and there are also live Aztecs.",
	"And why don't you live in Tenochtitlan?",
	"I was expelled by Mictlantecuhtli. While his power is boundless, I can not return   \nListen to me, White Captain. Now I will offer you a deal which I make with everyone who comes here.",
	"I listen to you, Montezuma.",
	"If you manage to reduce Mictlantecuhtli's power I will help you to gain power. In the temple of White Gods there is a weapon unequaled by anything that is or will be. You can take it for yourself.",
	"And what do you need?",
	"Mictlantecuhtli's jade skull. It is in the temple of Great Vital Force.",
	"I assume it won't be easy to get there.",
	"I will help you with advice.",
	"Maybe you'd better go with me to the city? You'll be waving your cudgel, splitting skulls...",
	"Cudgel?! You're a cudgel!   \nIt is the obsidian sword Macuauhitl! Do you know that our obsidian spears and swords frightened the Spaniards more than the iron ones?",
	"Excuse me for the question, Montezuma, but why then have you lost the war?",
	"Our gods turned away from us...",
	"Gods again...",
	"Gods decide everything, not people. One of my ancestors tried to decide everything instead of gods, and he was mistaken. The price he had to pay for this mistake was unreasonably high.   \nWell anyway, let's talk about the deal instead. Will you go to Tenochtitlan and bring me the jade skull?",
	"I am ready to try.",
	"It is good. Then to begin with, you need to remove the spell of fire from the dam that leads to the city.",
	"And how do I do that? Who managed to organize such an inferno, anyway?",
	"Why Mictlantecuhtli, who else? By the force of Camaxtli, the god of war and destiny, he cast the spell of fire on the dam. For Camaxtli is the creator of fire.",
	"I understand... So how do I remove this fire?",
	"There are two ways. The first it to find the totem of Camaxtli, get into the city through the fire and insert this Totem into the sacrificial stone that is near the city entrance.",
	"Get through the fire? That way I'll will burn alive!",
	"On the wooden isthmus of the dam there is no fire. You can have a rest there.",
	"I see... And the second way?",
	"Find two totems - one of the goddess Tlazolteotl, devourer of filth, and one of the god of sky and sun Tonatiuh. Then insert them into sacrificial stones that are on the shore before the dam. Then the curse will be removed and you will be able to easily pass to Tenochtitlan.",
	"I understand. And where should I look for these totems?",
	"I can't tell you that, otherwise our deal will be pointless   \nBut I can give you a hint...",
	"Well, go ahead.",
	"The Camaxtli Totem is closer than you think. The Tlazolteotl Totem is nearby, in the grass. And the Tonatiuh Totem is lost in the jungle between two Spanish cities that are located on an isthmus between the continents.",
	"Damn it! Can't you be more precise?",
	"I can not. Search, White Captain. I have told everything, now it is your time to act.",
	"All right, I will look for them...",
	"Yes, I am an Aztec, you are right. I am called Montezuma. And how can I address you?",
	"I'm called Captain ",
	". Montezuma... I think that was the name of an Indian leader.",
	"I am named in his honor   \nTell me, White Captain ",
	", what are you going to do now? After all, you managed to remove the spell of fire!",
	"I will thoroughly search the city. Perhaps, I will find something worthwhile.",
	"I want to propose something to you, White Captain.",
	"I'm listening to you, Montezuma.",
	"Very well. Listen carefully, White Captain.",
	"My ancestors came to the shores of this lake named Texcoco many centuries ago. At the time they were called the Mexica people. The shores of the lake were populated by other tribes which have been hostile towards newcomers. But our supreme god Huitzilopochtli commanded them to remain here. Then Tenoch, the leader of the Mexica, made a decision to remain on the shores of Texcoco, and the Mexica started to call themselves the Tenochca.",
	"Coxcoxtli, the leader of the powerful city of Culuacan, decided to exterminate the Tenochca. Then my ancestors left the shores behind and started to live on a boggy island in the middle of the lake. Time has passed, and the Tenochca managed to fortify the island and build a stone city, and even a dam to the shore. And when the Tenochca elected Itzcoatl as their leader, the confederation of tribes was created, and the people of this confederation became known as the Aztecs.",
	"Blessed times had come, the Aztecs ruled the world. All tribes paid tax to the Aztecs, delivered food, slaves and concubines. The sacrificial blood - food of our gods - painted the waters of Texcoco red. The best warriors were sacrificed to Tezcatlipoca, the patron of our priests, and ordinary warriors were burnt in honor of Camaxtli. Women gave their blood to the goddess Mayahuel, and the children - to the god of fertility Tlaloc.",
	"Thus it was for more than hundred years. But then came the Spaniards and Tenochtitlan was besieged. And our heroes led by Cuauhtemoc have fallen.",
	"Now the god of kingdom of the dead Mictlantecuhtli rules in Tenochtitlan.",
	"So, the city is uninhabited?",
	"No. Both alive and dead people live there.",
	"Say what?",
	"Mictlantecuhtli has the power to revive people. Mictlantecuhtli has returned warriors to life to guard the temples of gods, and there are also live Aztecs.",
	"And why don't you live in Tenochtitlan?",
	"I was expelled by Mictlantecuhtli. While his power is boundless, I can not return   \nListen to me, White Captain. Now I will offer you a deal which I make with everyone who comes here.",
	"I listen to you, Montezuma.",
	"If you manage to reduce Mictlantecuhtli's power I will help you to gain power. In the temple of White Gods there is a weapon unequaled by anything that is or will be. You can take it for yourself.",
	"And what do you need?",
	"Mictlantecuhtli's jade skull. It is in the temple of Great Vital Force.",
	"I assume it won't be easy to get there.",
	"I will help you with advice.",
	"Maybe you'd better go with me to the city? You'll be waving your cudgel, splitting skulls...",
	"Cudgel?! You're a cudgel!   \nIt is the obsidian sword Macuauhitl! Do you know that our obsidian spears and swords frightened the Spaniards more than the iron ones?",
	"Excuse me for the question, Montezuma, but why then have you lost the war?",
	"Our gods turned away from us...",
	"Gods again...",
	"Gods decide everything, not people. One of my ancestors tried to decide everything instead of gods, and he was mistaken. The price he had to pay for this mistake was unreasonably high.   \nWell anyway, let's talk about the deal instead. Will you go to Tenochtitlan and bring me the jade skull?",
	"I am ready to try.",
	"Very well. Now listen what you have to do.",
	"I'm listening to you, Montezuma.",
	"The spell of fire isn't removed yet from the dam.",
	"Not yet, but I'm working on it.",
	"You managed to remove the spell of fire, it is good. Now listen what you have to do next.",
	"I'm all ears, Montezuma.",
	"You got access to Tenochtitlan and now you can enter the temples of gods. The jade skull I need is in the temple of Great Vital Force. To get inside, you need to collect 10 totems of gods and place them on sacrificial stones of 10 temples.",
	"So where are these temples located?",
	"Five are in the pyramid on the left side of the temple of the Great Vital Force, another five - on the right side of it. There are five entrances in each small pyramid, each of which leads to a temple of some god. Above each entrance you will see the image of god of that temple. It is better to look at midday   \nYou must not make mistakes entering the temples as every time you visit the strength of temple guards will grow.",
	"There's temple guards as well?",
	"Yes, the Aztec warriors revived by Mictlantecuhtli. You will have to fight them. You will not be able to take any assistants inside the temples, so you will have to do it all by yourself.",
	"Hmm, that's bad news... So what are the 10 totems I should find?",
	"You must find the totems of: Xochiquetzal, the goddesses of flowers and love   \nMictlantecuhtli, the already known to you god of the dead   \nQuetzalcoatl, the god of the morning star, lord of elements   \nMixcoatl, the god of hunting   \nTezcatlipoca, the patron of priests   \nChalchiuhtlicue, the goddesses of sea and lakes   \nHuitzilopochtli, the god of blue clear sky   \nHuitzilopochtli, the god of thunder and rain   \nMayahuel, the goddesses of fertility   \nTonacatecuhtli, the god-creator who grants food to people.",
	"I see. And now hint me on where to get these totems.",
	"No, I can't do that. Look for them all around the world yourself.",
	"That's excellent news! Hey, didn't you need the jade skull? Something tells me you're not so eager to settle this issue.",
	"This is all I can do. Everything that I do has its reasons, believe me.",
	"I understand... Well then, you just wait 'till I manage to get these totems, get into the temple and bring you the skull. I'm afraid that it's gonna be a long wait.",
	"I will wait, White Captain. This is the only thing left for me...",
	"In that case, see you later.",
	"You don't have the jade skull! I am waiting for you to bring it to me, White Captain.",
	"I am working on it, Montezuma.",
	"You obtained the jade skull of Mictlantecuhtli! Give it to me!",
	"And what will I receive in exchange? It wasn't easy to get my hands on it, you know...",
	"Not so fast, old pal! You promised me some powerful weapon. I didn't find anything in there.",
	"You were in the Temple of Great Vital Force. But you don't have the jade skull with you. Why didn't you take it?",
	"Didn't find it.",
	"You are telling lies, White Captain. For this, Montezuma will punish you!",
	"Well, try...",
	"The weapon is in the Temple of White Gods, I told you!",
	"It's closed.",
	"The temple is opened by an obsidian knife, with which the priests cut the victim's heart out. Find it, and you will manage to open the temple.",
	"And where should I look for it?",
	"In the Temple of Great Vital Force   \nAnd now give me the skull!",
	"Mere instructions that the weapon lays in some temple isn't enough for me. What else of value I can get? It wasn't easy to get my hands on this skull, you know...",
	"You dare to argue with me, fool?! You don't know whom you are speaking with!",
	"I know. You're Montezuma II, the last ruler of Aztecs. Mictlantecuhtli told me that.",
	"For the last time I ask you to give me the jade skull. I helped you to get it, we had a deal!",
	"Why do you need it?",
	"With its help I will return my people to life. Tenochtitlan will rise to power again, and the empire of Aztecs will subdue other nations!",
	"Your gods have turned away from Aztecs. And your people don't exist anymore.",
	"I will raise my people from the graves with the jade skull! And we'll find new gods, and please them with the blood of slaves. Aztecs will find power once again, but this time we will have experience. I won't repeat the mistakes of our past, and white people will pay for their treachery!",
	"I won't give you the skull, Montezuma. You've painted a picture here which I don't really like.",
	"Then prepare for death.",
	"And you prepare, as well. I survived a fight with Mictlantecuhtli himself, and I won't have any trouble sending you to his realm forever.",
	"I can't die a second time, White Captain!",
	"I have the jade skull, and it gives the power over the dead. Which means over you, as well. I believe that changes everything.",
};
