string DLG_TEXT_SHY [25] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"At my shipyard, and in the city in general, I haven't seen such mundanely inquisitive people.",
	"What questions? My business is building ships. Let's go and work on that.",
	"I've changed my mind...",
	"I've got nothing to say now.",
	"Hm. Something's happened to my memory...",
	"Hm. And yet...",
	"Let's...",
	"Did a certain Edward Low contact you in the hopes of acquiring a ship?",
	"He came by, but didn't acquire anything.",
	"I've said everything on this matter...",
	"Yes, he did. But I don't have anything to add to what I said earlier.",
	"Listen, I'm getting tired of you!",
	"Why is that?",
	"Yeah, that's for sure...",
	"Point taken.",
	"I was just leaving...",
	"Well, he wanted a brig, but pardon me, he barely had enough money for a lugger.",
	"I see... Did you notice where he went?",
	"He-he, it's obvious. He went to the money-lender, to borrow some money, but the man didn't give him any, he-he-he...",
	"Why do you think so?",
	"The fellow never came back, which means he hasn't found any money, he-he...",
	"Makes sense!",
};
