string DLG_TEXT_SHY [370] = {
	"Cough... cursed weather. My name is ",
	", and may a thousand devils take me, I'm the best shipbuilder on these damned islands.",
	"A thousand sharks, you're whining is just what I didn't need. My name ",
	". Surely you've heard of me.",
	"Allow me to disagree. The weather's wonderful! My name is ",
	". Surely you've heard of me.",
	"Oh. It's you again, with your problems... *cough cough*",
	"You're right. It's me again. And I see that you're still unhappy with life. But let's talk about business.",
	"You have a good memory. And now, if you'll allow it, I want to move on to more specific questions.",
	"You've tired me out with your whining about life. Farewell!",
	"It's time for me to go. Sorry to have bothered you.",
	"Oh. It's you again, with your problems... *cough cough*",
	"You're right. It's me again. And I see that you're still unhappy with life. But let's talk about business.",
	"You have a good memory. And now, if you'll allow it, I want to move on to more specific questions.",
	"You've tired me out with your whining about life. Farewell!",
	"It's time for me to go. Sorry to have bothered you.",
	"Youth, youth... Can't expect any reverence from you kids. Hot heads, hard hands, what more do you need?",
	"Yes, old man. It looks like your youth ended so long ago that you can't even remember it.",
	"I'm sorry, but you were young as well. How can you talk like that?",
	"Don't contradict your elders, pup!",
	"What did you call me?! If I hear one more word in that vein, it won't be good for you. Why don't we focus on the matter at hand, instead of empty prattle?",
	"I'll ask you not to raise your voice to me again. And now, if you've finished your monologue, I'd like to get to business.",
	"I've had enough of your empty phrases! Farewell!",
	"I see that we don't see eye-to-eye. Goodbye.",
	"*cough cough* What do you need from me, ",
	"I need to use the services of your shipyard.",
	"I want to use the services of your shipyard.",
	"I've got a question.",
	"I'd like to discuss financial matters with you.",
	"Damn. I've got a few tasks that I can't put off, that demand immediate resolution.",
	"It's time for me to go.",
	"I can offer you a bit of piecework - polishing off the tubs that sail the sea now...",
	"Wonderful! That's what I need. I've got a ship just like that. Maybe you'll take a look?",
	"No, I don't need any improvements. I just want to use the services of the shipyard.",
	"I need cannons for the ship.",
	"Oh... Sorry. I'm leaving.",
	"Oh... It's you again. Did you decide to finish building your ship?",
	"Greetings to the famous seafarer. Something doesn't satisfy you about the ship?",
	"Eh... I don't have a minute of calm, I can't concentrate... You and your improvements, again?",
	"Yes, there is that matter. Maybe we'll take a look at what else can be done?",
	"No, I don't need any improvements. I just want to use the services of the shipyard.",
	"I need cannons for the ship.",
	"I have a question.",
	"I'd like to discuss financial matters with you.",
	"No. I think I'm satisfied with what's there.",
	"Oh, so I see you know how to think as well! You'll go far! Come when you decide to finish building the ship.",
	"Thank you! All the best.",
	"See you, master. I can do without the sarcasm.",
	"Where's the ship? Why do you keep taking me for a ride!",
	"It's the truth... Why have I? I apologize, ",
	"I am, of course, a workaholic - yet even I must eat my lunch. Come back later!",
	"Understood...",
	"Eh... I don't work on boats. That's not my field!",
	"Understood...",
	"Well, well... Let's see what we have here... Uh-huh. ",
	" Bah! This ship has seen more than one set of hands. It's so shabby! Do you have a letter of marque? Now, now, I'm joking. To business.",
	" What would you like to do with it?",
	"Increase the cannon caliber ",
	"Increase the hold capacity ",
	"Increase the speed ",
	"Increase maneuverability ",
	"Add crew space ",
	"Increase the sturdiness of the frame ",
	"Wait! I've changed my mind.",
	"Let's look at what can be done. You've got ",
	" cannons, with a max caliber of ",
	" lbs. ",
	". I'll need ",
	" units of ebony to strengthen the portholes, and ",
	" units of leather for the recoil system to the larger cannons.",
	" For the manpower, I'll ask for ",
	" gold. Half up front.",
	"That works. I'll accept the conditions. I'll bring the materials.",
	"No. I don't agree.",
	"That's great. I'll wait for the work materials.",
	"I'll go get them...",
	"To increase the caliber of the cannons on the ",
	" I require: ",
	" units of ebony, ",
	" units of leather and ",
	" gold.",
	"I don't see the deposit...",
	"I'll come by later, ",
	"Your cannons are waiting. Did you bring ",
	" units of ebony, ",
	" of leather, and ",
	" piasters?",
	"Yes.",
	"No.",
	"Methinks, sir, that you've changed the ship since our last agreement. We'll have to recalculate...",
	"There were matters. It's too bad that the deposit is gone...",
	"Brought everything. Good boy! I'm beginning work...",
	"Thanks!",
	"You still need to bring ",
	" units of ebony, ",
	" of leather, and ",
	" piasters ",
	"Fine.",
	"I still have to bring ",
	" units of ebony, ",
	" units of leather, and ",
	" gold.",
	"Seems like everything...",
	"Thanks! I'll check it for sure.",
	"Let's look at what can be done. You've got a hold with the capacity for ",
	". I'll need ",
	" units of mahogany to decrease the bulkhead volume, and ",
	" units of oil.",
	" For the manpower, I'll ask for ",
	". Half up front.",
	"That works. I'll accept the conditions. I'll bring the materials.",
	"No. I don't agree.",
	"That's great. I'll wait for the work materials ",
	"I'll go get them...",
	"To increase the hold space on the ship, ",
	" I require: ",
	" units of mahogany, ",
	" units of oil and ",
	" gold.",
	"I don't see the deposit...",
	"I'll come by later.",
	"The hold is waiting. Did you bring ",
	" units of mahogany, ",
	" of oil, and ",
	" piasters?",
	"Yes.",
	"No.",
	"Methinks, sir, that you've changed the ship since our last agreement. We'll have to recalculate...",
	"There were matters. It's too bad that the deposit is gone...",
	"Brought everything! Good boy! I'm beginning work..",
	"Thanks!",
	"You still need to bring ",
	" units of mahogany, ",
	" of oil, and ",
	" piasters.",
	"Good.",
	"I still have to bring ",
	" units of mahogany, ",
	" units of oil, and ",
	" gold.",
	"Seems like everything...",
	"Thanks! I'll check it for sure.",
	"Let's get an estimate of what needs to be done. Your speed is ",
	". I'll need ",
	" units of sailcloth, ",
	" units of silk.",
	" For the manpower, I'll ask for ",
	" gold. Half up front.",
	"That works. I'll accept the conditions. I'll bring the materials.",
	"No. I don't agree.",
	"That's great. I'll wait for the work materials.",
	"I'll go get them...",
	"To increase the ship's speed ",
	" I require: ",
	" units of sailcloth, ",
	" units of silk, and ",
	" gold.",
	"I don't see the deposit...",
	"I'll come by later, ",
	"Work awaits. Have you brought ",
	" units of sailcloth, ",
	" units of silk, and ",
	" piasters?",
	"Yes.",
	"No.",
	"Methinks, sir, that you've changed the ship since our last agreement. We'll have to recalculate...",
	"There were matters. It's too bad that the deposit is gone...",
	"Brought everything. Good boy! I'm beginning work...",
	"Thanks!",
	"You still need to bring ",
	" units of sailcloth, ",
	" units of silk, and ",
	" piasters ",
	"Um. Sure, okay.",
	"I still have to bring ",
	" units of sailcloth, ",
	" units of silk, and ",
	" gold.",
	"... That seems done... Now you can catch the wind with full sails",
	"Thanks! I'll check it for sure.",
	"Let's get an estimate of what needs to be done. Your maximum crew with overload is ",
	" sailors",
	". I'll need ",
	" of fruits and ",
	" of clothes.",
	" For the manpower, I'll ask for ",
	" gold. Half up front.",
	"That works. I'll accept the conditions. I'll bring the materials.",
	"No. I don't agree.",
	"That's great. I'll wait for the work materials.",
	"I'll go get them...",
	"To increase the ship's crew capacity ",
	" I require: ",
	" units of fruits, ",
	" units of clothes, and ",
	" gold.",
	"I don't see the deposit...",
	"I'll come by later, ",
	"Work awaits. Have you brought ",
	" units of fruits, ",
	" units of clothes, and ",
	" piasters?",
	"Yes.",
	"No.",
	"Methinks, sir, that you've changed the ship since our last agreement. We'll have to recalculate...",
	"There were matters. It's too bad that the deposit is gone...",
	"Brought everything. Good boy! I'm beginning work...",
	"Thanks!",
	"You still need to bring ",
	" units of fruits, ",
	" units of clothes, and ",
	" piasters. ",
	"Um. Sure, okay.",
	"I still have to bring ",
	" units of fruits, ",
	" units of clothes, and ",
	" gold.",
	"... That seems done... You may start recruiting",
	"Thanks! I'll check it for sure.",
	"Let's get an estimate of what needs to be done. Maneuverability ",
	". I'll need ",
	" planks and ",
	" linen.",
	" For the manpower, I'll ask for ",
	" gold. Half up front.",
	"That works. I'll accept the conditions. I'll bring the materials.",
	"No. I don't agree.",
	"That's great. I'll wait for the work materials.",
	"I'll go get them...",
	"To increase the ship's maneuverability ",
	" I require: ",
	" units of planks, ",
	" units of linen, and ",
	" gold.",
	"I don't see the deposit...",
	"I'll come by later, ",
	"Work awaits. Have you brought ",
	" units of planks, ",
	" units of linen, and ",
	" piasters?",
	"Yes.",
	"No.",
	"Methinks, sir, that you've changed the ship since our last agreement. We'll have to recalculate...",
	"There were matters. It's too bad that the deposit is gone...",
	"Brought everything. Good boy! I'm beginning work...",
	"Thanks!",
	"You still need to bring ",
	" units of planks, ",
	" units of linen, and ",
	" piasters ",
	"Um. Sure, okay.",
	"I still have to bring ",
	" units of planks, ",
	" units of linen, and ",
	" gold.",
	"... That seems done... Try spinning the steering wheel now",
	"Thanks! I'll check it for sure.",
	"Let's get an estimate of what needs to be done. At the moment the body is ",
	". I'll need ",
	" of ebony and ",
	" of sandalwood.",
	" For the manpower, I'll ask for ",
	" gold. Half up front.",
	"That works. I'll accept the conditions. I'll bring the materials.",
	"No. I don't agree.",
	"That's great. I'll wait for the work materials.",
	"I'll go get them...",
	"To increase the strength of the ship's body ",
	" I require: ",
	" units of ebony, ",
	" units of sandalwood, and ",
	" gold.",
	"I don't see the deposit...",
	"I'll come by later, ",
	"Work awaits. Have you brought ",
	" units of ebony, ",
	" units of sandalwood, and ",
	" piasters?",
	"Yes.",
	"No.",
	"Methinks, sir, that you've changed the ship since our last agreement. We'll have to recalculate...",
	"There were matters. It's too bad that the deposit is gone...",
	"Brought everything. Good boy! I'm beginning work...",
	"Thanks!",
	"You still need to bring ",
	" units of ebony, ",
	" units of sandalwood, and ",
	" piasters ",
	"Um. Sure, okay.",
	"I still have to bring ",
	" units of ebony, ",
	" units of sandalwood, and ",
	" gold.",
	"... That seems done... Good enough to withstand a few more bomb explosions",
	"Thanks! I'll check it for sure.",
	"Can I help you?",
	"What do you need?",
	"Just recently, you tried to ask me a question...",
	"On my wharf, and in the city in general, I haven't seen such repetitively curious types.",
	"What questions? My business is building ships. Let's go and work on that.",
	"Sorry, never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"Hm. And yet...",
	"Let's...",
	"Hey, I want to pass here, but the door is locked...",
	"Listen, I need to know one thing concerning your dungeon...",
	"Speak...",
	"Listen, I'd like to know where did a certain person, who was being chased, fall into on your shipyard?",
	"O-o-oh, glad to see you. So I didn't let you in there in vain - you've survived yourself and relieved me from that rubbish... Well tell me, who was there?",
	"It's better for you not to know, you'll sleep more easily. Well, farewell, thanks once again for opening the door.",
	"Did Edward Low come to you?",
	"Jackman gave me the 'Sea Wolf'!",
	"I have some rather bad news concerning your brig which was taken by Low...",
	"He did... Why do you need him?",
	"That... That bad person deceived me and betrayed Morgan. I am looking for him to kill the rascal!",
	"I'm his friend, haven't seen him for a long time, and I was told in the tavern that he came here...",
	"Aha. A friend, you say. That's good... That's simply marvellous! Tell you what, go to Jackman, tell him you're looking for your friend Edward Low. Jackman will help you   \nPerhaps, your friend is still there. Go, go now, you'll meet right there, you've probably missed him.",
	"Thanks! Already on my way!",
	"Why, it seems he's a rascal three times! He managed to deceive me as well! Brought me a letter from Jackman, with a request to give the 'Sea Wolf' to the bearer of this letter...",
	"Sea Wolf?",
	"ÿSea Wolf' is a brig. My brig! My best creation! I've put all my soul in her. It's beautiful, magnificent, captivating! You can't take your gaze off her at the sunset, and during sunrise, when that beauty sets her sails, she looks like a blossoming flower. And whe she runs over the waves...",
	"Hmm... You said something about Low.",
	"Sorry? Ah, yes. Edward Low. I mean, I was building that brig for Jackman, almost completed it, and then this Low comes in with a letter. In short, I've given him the brig, and when I went to see Jackman for my money, it appeared that the letter was forged. Jackman was upset... Very... Very upset   \nWhen they threw me ou... Um, er... When I was leaving the place, Jackman said: 'I respect you, Master, but the brig must be returned'. So I thought here, since you're looking for this Low fellow anyway, maybe you could also find my brig while you're at it?",
	"I don't mind helping you, but where should I be looking for Low right now?!",
	"Oh, you should ask the tavern keeper. They're that kind of folk, they know everything about everyone. He probably knows where the rascal set sail to.",
	"Well then, I'll try.",
	"Captain ",
	"Goodley",
	"I saw it, saw your arrival. Couldn't resist, ran to the pier to have a look.   \nA worthy gift. I congratulate you, and thank you! You've saved the old man.",
	"Oh come on, rescued...",
	"Damn! I knew it... So what?",
	"It sank, I'm afraid....",
	"Oh my, that's bad.",
	"Oh, don't you worry, it'll be alright...",
	"It's not mine. On the contrary, I try not to let anyone in there for their own sake.",
	"Ah, well alright. Actually, here's the question I have. Is anyone carrying any goods into the city through this dungeon?",
	"Ha-ha, of course not, though the dungeon is pass-through. Judge for yourself, what kind of idiot you need to be to drag some cargo on your back through this hole, when you can employ any tartane and easily transport everything by the sea.",
	"Well what if someone doesn't want it to be known in the city?",
	"And you think that nobody will notice if someone starts to drag cargo from my shipyard to the city?",
	"Hm, yes, indeed... So you're saying that no one is carrying anything through your wharf?",
	"No, no one is carrying anything, rest assured.",
	"Well then, I thank you very much!",
	"That's true. To pass here, you must pay me 20000 coins. If you're not paying - I'm not opening it, it's not a double-exit courtyard I've got here. And I wouldn't advise you to gad around it - won't do you any good...",
	"Here's your money, open up.",
	"I have no such money.",
	"No way! I'm not paying for some door.",
	"Go on, the door is unlocked. And don't thank me!",
	"Oh come on, thank you, ",
	"Well come when you have them. And don't try to persuade me - it's useless...",
	"Argh, I can't find any words for you!",
	"Oooh, a good question... And why are you looking for him?",
	"I already told you everything - the door is unlocked.",
	"I repeat once again - the door is unlocked.",
	"Hey, will you ever quit it?",
	"He has a book which doesn't belong to him. He is a thief.",
	"I understand...",
	"Understood...",
	"That's how unimaginably persevering I am...",
	"I understand. You know, his chasers, the sailors, have already asked me about it. Then some merchant came and tried to find it out, too. I told them nothing.",
	"Why?",
	"Didn't want to take a sin upon myself - they'd be dead by now if they went in there... I can tell you, you seem to be a brave one, and strong...",
	"In where would they go?",
	"Right there where that pilferer has gone. Through this door to the right of me.",
	"So what's there behind this door? And why won't you let anyone in there?",
	"Behind this door is a dungeon, I don't know who built it, it already was here when I became the owner of this place. And I'm not letting anyone in because it's dangerous there, very dangerous. I guess that pilferer met his doom in there...",
	"Don't know who, or what, lives in there. But sometimes you can hear blood-chilling cries coming from the place...",
	"My oh my... Hm, well then, let me in.",
	"Go on, it's open... I hope to see you again in this world.",
	"You will, have no doubt.",
};
