string DLG_TEXT_SHY [21] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"At my shipyard, and in the city in general, I haven't seen such mundanely inquisitive people.",
	"What questions? My business is building ships, so let's go and work on that.",
	"I've changed my mind...",
	"I've got nothing to say now.",
	"Hm. Something's happened to my memory...",
	"Hm. And yet...",
	"Let's...",
	"I heard you were selling a schooner. That so? The Swallow, was it?",
	"No, not quite so. It's not on sale, but already sold. There came a buyer and I liked him so much that I sold him the schooner literally for pennies...",
	"I'm not interested in the buyer, but rather the seller. Who sold you the schooner?",
	"Sold? Sold... Some man sold it...",
	"Oh I understand that it wasn't a horse. Who's that man, what's the name?",
	"Don't know the name, I was staring at the ship more than him...",
	"Don't muddle it, pal, that's dangerous for your health.",
	"Damn it! I knew that this purchase would get back to me. But  the price offered was just too good... Just between you and I, it might've been some pirate... But I might be wrong.",
	"Most likely, you are right. So where do I find him?",
	"In the sea. Yesterday he set sail on a frigate 'Leon', as far as I know. Haven't seen the frigate myself, the guy was very careful, but one of my workers saw saw him and told me. Try looking for him somewhere around the coast of Hispaniola. Don't think he got far away, you know yourself - a wolf feeds with his feet...",
	"Perhaps, I will follow your advice.",
};
