string DLG_TEXT_SHY [21] = {
	"What questions?",
	"What do you desire?",
	"Just recently, you tried to ask me a question...",
	"At my shipyard, and in the city in general, I haven't seen such mundanely inquisitive people.",
	"What questions? My business is building ships, so let's go and work on that.",
	"I've changed my mind...",
	"I've got nothing to say now.",
	"Hm. Something's happened to my memory...",
	"Hm. And yet...",
	"Let's...",
	"I hear that Pierre Picardy has the best ship in these waters.",
	"Could be. His frigate was good enough on its own, but a few days ago I finished modernizing it. Now his culevrins are the newest you can find, loaded from the breech end! An expensive pleasure, that, but it's worth it... So I guess you're right. Why are you asking?",
	"Señor, let's move on to the ship business, I've no interest in Picardy right now...",
	"You already asked me about Pierre...",
	"Listen, do you care asking about Pierre in some other place, eh?",
	"I want to undertake a small business affair, but can't handle it alone... So I'm looking for someone to keep me the company.",
	"Indeed, let's move on...",
	"Really? Hm, oh yes, I did...",
	"Yes, perhaps I'll ask in some other place.",
	"I understand. Well then, Pierre is a good choice in this case, Morgan himself offers him such affairs from time to time.",
	"Oooh, Morgan himself?! This Pierre is a serious man. Thanks for your recommendation.",
};
