string DLG_TEXT [281] = {
	"Albert",
	"Greene",
	"Gaytano",
	"Lemier",
	"Esteban",
	"Morua",
	"Juan",
	"Carlos",
	"Miguel",
	"Carlitos",
	"Lorenso",
	"Santino",
	"What is the name for a collection of ropes threaded through the holes of the bow topsail, and passing through a special block on the stay?",
	"Slab Line",
	"It's hard to keep food fresh at sea. But this biscuit can keep for years, so long as you keep it dry. ",
	"Hardtack",
	"What is the name for a cylindrical brush, affixed to a wooden staff, used to clean powder residue from the barrel of a cannon?",
	"Cleaning Rod",
	"What is the name for the reinforced strip of exterior planking on the ship's hull, above the waterline?",
	"Rubbing Strake",
	"What do you call the piece of leather-covered rope used to fasten a yard or gaff around the mast or topmast?",
	"Parral",
	"What do you call it when two ropes are bound together with a thin rope or jackline?",
	"Seizing",
	"What is the name for the lateral bulkead at the bow of a sailing ship?",
	"Beakhead",
	"What do you call the crosstimbers of a ship that support the decks, join together the opposite sides of the frame legs, and give the ship lateral strength?",
	"Beams",
	"What's the name of that ancient oar-driven warship with two banks of oars?",
	"Bireme",
	"What's the wooden bollard on a ship's deck, used to secure ropes?",
	"Bitt",
	"What's the small mast on the bowsprit that holds a yard with a squaresail? ",
	"Spirit Topmast",
	"Name the sail fastened beneath the bowsprit.",
	"Blindsail",
	"What do you call those horizontal spars that are just secured on the one end? Here, I'll give you a hint. They're used to hang the sail out over the water, hold the rigging apart, and suspend the boats.",
	"Boomkins",
	"Tell me, what do you call the spar that extends off the topmast?",
	"Topgallant Mast",
	"What do you call the running rope that you use to turn a yard along a horizontal plane?",
	"Brace",
	"Tell me, what's the gizmo with the horizontal shaft that you use to hoist anchors and cargo?",
	"Windlass",
	"When you shoot a ship's gun, there's all this recoil. What do you call the thick rope that you use to dampen it?",
	"Breeching",
	"Name me the extra sail that is laced directly to the mainsail.",
	"Bonnet",
	"What do you call the rope that holds the leech of a squaresail toward the bow, when the ship is sailing by the wind?",
	"Bowline",
	"Tell me, what do you call the third squaresail from the bottom - the one hoisted between the topgallant yard and the topsail yard?",
	"Topgallant Sail",
	"What do you call those thick ropes in the standard rigging, that steady the mast to the sides?",
	"Shrouds",
	"Tell me, what's the name of the rope that secures the bowsprit to the stem?",
	"Gammoning",
	"Here, what's the name of the auxiliary anchor that you use to heave the ship out of a shallows?",
	"Kedge",
	"What do call the round lug at the breech end of a gun?",
	"Cascabel",
	"What do you call the small ropes fastened across the shrouds, that you use to climb up onto the masts and topmasts?",
	"Ratlines",
	"Tell me, what's the name of the metal catch fixed to the end of a rope that is used for hoisting the boats, cargo, and many other things.",
	"Hook",
	"What do you call the flat part at the ship's stern where the poop lanterns are?",
	"Taffrail",
	"Tell me, what's the name of the running rope used to hold the clew of a sail toward the bow.",
	"Tack",
	"What do you call the inclined spar that holds the head of a trisail?",
	"Gaff",
	"What measure of length is equal to one tenth of a nautical mile?",
	"Cable",
	"What is the little cloth sack holding a charge of gunpowder called?",
	"Powder Bag",
	"What do you call the raised portion of the upper deck at the ship's stern?",
	"Quarterdeck",
	"Tell me, what's the name of the cone-shaped piece of hardwood that is inserted into a knot to prevent it from tightening?",
	"Toggle",
	"What do you call the triangular sail attached to the rigging that runs from the mast to the bowsprit?",
	"Jib",
	"What do you call the opening in the ship's side for the anchor line? Careful now...",
	"Hawse-Hole",
	"What do you call the square topsail of the mizzenmast? ",
	"Mizzen Topsail",
	"What do you call the extra, trapeze-shaped sail, set on the outer edge of a squaresail?",
	"Studsail",
	"What do you call the soft rope used to darn  the edges of sails?",
	"Boltrope",
	"What's that weight called, that you use to measure depth?",
	"Lead",
	"What do you call a man who maps out the shore by measuring the seafloor with a lead? ",
	"Pilot",
	"What do you call that round, overstitched hole in a sail?",
	"Glut",
	"So tell me, what do you call the second squaresail from the bottom of the mast? The one that's held between the head and foot?",
	"Square Topsail",
	"What do you call a wooden nail?",
	"Peg",
	"What do you call the wooden locker where you keep your compass, lamp, and hourglass?",
	"Binnacle",
	"What do you call the ropes that seamen stand on, when they work on the yards? ",
	"Footropes",
	"What's the uppermost timber of the bulwark, on a decked ship?",
	"Gunwale",
	"Sometimes a sail has this horizontal line of lacing through it, that's used to reduce its area. What do you call that?",
	"Reef",
	"So that ring at the end of the anchor, that you tie the rope to - what's that called, again?",
	"Eye",
	"What do you call the framework that joins together the lengths of a mast?",
	"Crosstrees",
	"So tell me, what's the name of the seat where the mast heel is fixed?",
	"Step",
	"What do you call the spar that is an extension of the lower mast?",
	"Topmast",
	"Tell me the name of the triangular, sometimes trapezoidal, fore-and-aft sail that's held on a stay. ",
	"Staysail",
	"What do you use to grease the underside of the ship, and protect it from shipworms?",
	"Tar",
	"So there's a sail - trapezoidal fore-and-aft job. Its top is laced to a gaff, and is bottom stretches along a boom. What's it called?",
	"Trysail",
	"What was that Ancient Grecian warship - it was propelled with three banks of oars, and armed with a battering ram?",
	"Triere",
	"What do you call one of those ancient Roman warships, with three banks of oars?",
	"Trireme",
	"What do you call the spar that extends off the bowsprit? ",
	"Jib Boom",
	"Remind me, what's that rope you use to hoist things? Certain yards, sails, signal flags...",
	"Halyard",
	"What do you call it when the side of a ship continues up above an open upper deck?",
	"Bulwark",
	"What do you call the cylindrical bosses you use to aim a gun vertically?",
	"Trunnions",
	"What do you call the upper deck at the stern of a sailing ship, where the watch officers stand and the compasses are kept?",
	"Quarterdeck ",
	"What do you call the wide boards running horizontally along the sides, for walking from the forecastle to the quarterdeck?",
	"Waist",
	"What do you call the rope that pulls the bottom corner of a sail to stern, and holds the sail in the right position?",
	"Sheet",
	"What do you call the cross-timbering that forms a rib in the ship's hull?",
	"Frame",
	"What do you call it when you wrapp a rope around an object, so it forms a loop? ",
	"Round Turn",
	"What do you call that big, cylindrical ladle you use to unload a gun? I mean, to yank out the ball and the powder bag?",
	"Lantern",
	"What do you call a wooden connecting collar with two holes, used to bind together the parts of a mast?",
	"Mast Cap",
	"Tell me, what do you call those round wooden blocks, without a pulley? They've got three through-holes, for tensioning the stays and shrouds.",
	"Deadeyes",
	"What was the Caribbean's main export, around the middle of this century?",
	"Sugar",
	"What was the Caribbean's main import, around the early-mid mid part of this century?",
	"Slaves",
	"Who was the first Dutch seafarer to circumnavigate the globe?",
	"Oliver van Noort",
	"So the Dutch East India Company established its first trading station in 1626. What was it called?",
	"New Amsterdam",
	"Let's play a game, then. I'm a British poet, pirate, and sea captain. I colonized Virginia, and carry the sweet favor of Queen Elizabeth I. I also was beheaded in 1618. Who am I?",
	"Sir Walter Raleigh",
	"Who was the first pirate to fly a Jolly Roger?",
	"Emanuel Wynne",
	"Oliver",
	"Trust",
	"Humphrey",
	"Douglas",
	" which is in ",
	"a brig called The Sharpnose",
	"Worked on the island.",
	"Worked on the city.",
	"Captain Sharpe was here. I know, I saw him. But he ain't here no more, I don't know where he went.",
	"Sure, Sharpe stopped by here. I don't know where he went, but he ain't here now, that's for sure.",
	"Oh my, yes. Captain Bartholomew Sharpe left the city only just a few days hence...",
	"Captain Bartholomew Sharpe... Yeah, he visited our fair city. Swung by, as usual... But he's gone now. They say he made off for ",
	"You know, Sharpe was here not too long ago. Quite a jolly bloke, that Bartholomew... Good man! Pip, pip. Still, just as well that he left. I believe he heaved off to ",
	"Oho! Yes, it has not been long since Captain Sharpe honored us with his presence. To our great regret, however, he brought us none of his wondrous anecdotes from the Caribbean. A pity... And now, alas, he is off once more. They say he shall next grace ",
	". Lucky sods... ",
	"Oh, you know, you just missed him. If you only got here half an hour earlier, you'd have rammed right into him. Ah well. Them's the strokes.",
	"Sharpe? Huh. Not much of a captain, if you're askin' me. Well, anywho, he lighted off a little while ago. If'n you leave fire in your wake, you may catch him yet. ",
	"The Fair Bartholomew Sharpe departed our harbor for the open sea but an hour hence.",
	"Oh, Sharpe? I bumped into him just a few minutes ago. He was out roaming the streets. Probably forgot where the brothel is... ",
	"Captain Sharpe and I just had a chat, a moment ago on the street. Seems like quite the busy fellow...",
	"Yeah, last I saw Sharpe, he was out for a walk. We all keep waiting to see what he pulls this time...",
	"Have you heard? The local trader, ",
	", is sending his flute '",
	"ÿ to haul back goods from the Old World. The ship just left harbor, not too long ago.",
	"Ho ho. Our little homegrown businessman is doing all right for himself! ",
	" sent his own flute '",
	"ÿ to bring in a range of goods. It just left harbor a moment ago. ",
	"Haw! ",
	" just gets richer and richer. Only yesterday he was unloading his sailer at the harbor, and already today it's gone! The '",
	"ÿ turned right back for another load!",
	"Captain",
	"Goodley",
	"admiral",
	"admiral",
	"innkeeper",
	"innkeep",
	"barman",
	"bartender",
	"tavern keep",
	"tavern keeper",
	"waitress",
	"waitress",
	"mechanic",
	"mechanic",
	"on the battleship Tartarus, by the prison",
	"on the frigate Caroline",
	"on the flute Ceres Smithy",
	"on the galleon Esmeralda, by the store ",
	"on the caravel Fleuron, by the tavern",
	"in the bows of the pinace Fury",
	"in the afterbody of the pinnace Fury",
	"on the galleon Gloria, by the church",
	"on the flute Pluto",
	"on the corvette Protector",
	"on the warship St. Augustine, by the Admiral's quarters",
	"in the bows of the barge St. Gabriel",
	"in the afterbody of the barge St. Gabriel",
	"on the brig Santa Florentina",
	"on the galleon Eve",
	"on the galleon Velasko",
	"in the galleon Eve",
	"in the frigate Caroline",
	"in the flute Ceres Smithy",
	"in the store on the galleon Esmeralda",
	"on the platform Phoenix",
	"in the flute Fernando Diffindur",
	"in the tavern on the caravel Fleuron",
	"in the pinnace Fury",
	"in the church on the galleon Gloria",
	"in the flute Pluto",
	"in the corvette Protector",
	"in the admiral's quarters on the warship St. Augustine",
	"in the barge St. Gabriel",
	"in the brig Santa Florentina",
	"in the prison on the battleship Tartarus",
	"in the galleon Velasko",
	"The captain of the ",
	"ÿ is here in the city. I think his name is ",
	". I expect he should be with the harbor warden about now.",
	"You can find the captain of the ",
	"ÿ with the harbor warden.",
	"If you want to chat with the captain of the ",
	"ÿ, head straight for the harbor master. ",
	" is there right now...",
	" which is in ",
	"The captain of the ",
	"ÿ is anchored in the harbor. I think his name is ",
	". He's an odd duck, let me tell you. Doesn't even come ashore. ",
	"If you're looking for the Captain of the ",
	"ÿ you'll have to take a boat to the harbor. That's where he's anchored, and so far he hasn't set foot in the city. Yeah, he just... sits there. How boring is that?",
	"If you want to chat with the captain of the ",
	"ÿ, then swing by the harbor. ",
	" is the name... I think. Anyway, he dropped anchor at the harbor, but hasn't set foot ashore. Guess he doesn't want to lose his sea legs. A real sea dog, that one.",
	"left",
	"left",
	" which is in ",
	"The captain of the ",
	"ÿ is in the city. I think his name is ",
	"You can find the captain of the ",
	"ÿ in the city.",
	"If you want to chat with the captain of the ",
	"ÿ, you'll want to search the streets. ",
	" is the name... I think.",
	"The captain of the ",
	"ÿ is anchored in the harbor. I think his name is ",
	"You can find the captain of the ",
	"ÿ in the harbor. That's where he's anchored.",
	"If you want to chat with the captain of the ",
	"ÿ, look for his ship in the harbor. ",
	" is the name... I think.",
	" which is in ",
	"There were some sounds of battle on the St. Gabriel...",
	"Max",
	"Taylor",
	"You heard? Seems Chad Capper lost some key. I hear it's real important to him. Now he's runnin' all over town, looking for it...",
	"Fire spell removed",
	"Stony chest opened",
	"Fire spell removed",
	"Fire spell removed",
	"Stony chest opened",
	"Mictlantecutli",
};
