string QUEST_UTIL [24] = {
	"Dear Sir or Madam: Having defaulted on payment for services rendered, we are happy to inform you that your life force has been duly impounded. Welcome to Hell.",
	"Since evidently you missed the fine print before, please take some time to familiarize yourself with our terms. ",
	"Don't make me repeat myself.",
	"We've already gone over this.",
	"The topic is closed. Done. Move on already.",
	"While you're here, would you like me to repeat myself another dozen times?",
	"Hello, we've done this already.",
	"I told you we're done here. What is it, a hearing problem or a memory thing?",
	"Look, let's just stop this here. All right?",
	"Get lost, already! I don't want to talk to you!",
	"You're seriously pissing me off, here. That's it! Zip it! Scram!",
	"Yeah, yeah.",
	"Whatever you say.",
	"Let's pretend I never said that. Deal?",
	"All right, all right. Just keep your shirt on.",
	"Whatever you say. Just quit screamin' at me.",
	"Sorry, friend. I'm not myself today. My head is killing me...",
	"It's your call.",
	"Too bad...",
	"No big loss.",
	"Atila",
	"Salvatore",
	"Olivares",
	"Looks like that's our treasure, right there.",
};
