string DLG_TEXT_TV [24] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question...",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Ask what you will, Señor.",
	"I heard that you recently managed to capture the pirate, Rock the Brazilian himself!",
	"Indeed, it's true. I must tell you it was unprecedented luck, Señor.",
	"You already asked me about the Brazilian.",
	"The Brazilian again?",
	"Quit talking about pirates. Let's speak of something else...",
	"What's true is true... So what became of him? Probably strangled then and there.",
	"Did I? Well, probably...",
	"Yes, precisely, I did. Excuse me...",
	"Well, something else it is...",
	"Oh no, Señor. He was brought here and shown to everyone. Only then was he handed over to the holy fathers...",
	"And why did the holy fathers need him?",
	"Ha, Señor, they weren't confessors. The holy fathers are warrior monks! The Inquisition...",
	"Oh, that makes sense. Well then! I thank you, my friend.",
};
