string DLG_TEXT_TV [30] = {
	"Can I help you?",
	"What do you desire, ",
	"Not too long ago, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"Hey old chap, I'm looking for a young lady by the name of Elizabeth Sheppard. Ever heard of her?",
	"Ms. Liz Sheppard lives in our town. What do you want with her?",
	"You see, she forgot something in the Gulf of Maracaibo...",
	"Yes, Liz has been traveling a lot recently. Normally you wouldn't even be able to catch her in the city.",
	"And where is she now?",
	"At her house.",
	"She owns a house?",
	"Yes, it belonged to her father.",
	"And who is her father?",
	"Well, we're not supposed to talk about it, but I will tell you.",
	"Have you ever heard of Captain Stayton? No? Ho ho... Well know then that Captain Stayton, one of the first filibusters, is the father of Liz. In his time, while he was still alive, Stayton has done much to develop the city. The citizens of Nevis owe him.",
	"Elizabeth's surname is Sheppard.",
	"That was Stayton's decision. When he lodged in the city with his family, he took a different surname. Just in case, you know...",
	"So Liz lives alone now?",
	"Yes, her mother didn't outlive her spouse for very long. She's buried here on the island. And Danielle hasn't been home for two years now.",
	"Danielle?",
	"The elder sister of Liz.",
	"I understand. Well thank you, pal.",
	"Don't mention it. I hope you brought good news to Liz. She is a good girl, Captain...",
	"It's nothing bad, that's for sure.",
};
