string DLG_TEXT_TV [25] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Do you know where I could find the captain of the brig 'Five Wounds of Christ'?",
	"Where can I find the captain of the brig 'Five Wounds of Christ'? I was told he was here.",
	"Did a certain captain by the name of Edward Low show here?",
	"Yes, he dropped in, this captain. Been repairing his ship for some days now. He's not here at the moment. Try looking in town.",
	"Thanks!",
	"He's right over there at the round table, drowning his grief in wine.",
	"Thanks!",
	"No. Never heard the name before.",
	"I already answered your question.",
	"We already spoke about Low...",
	"For the last time, I know nothing about Edward Low!",
	"Thanks, pal.",
	"Yes-yes, I remember...",
	"Yes, of course...",
	"Point taken.",
};
