string DLG_TEXT_TV [18] = {
	"Can I help you?",
	"What do you desire, ",
	"Not too long ago, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"Hey pal, do you know if a certain Edward Low lives in your town?",
	"No. Haven't heard the name before. Haven't got anyone like that in the town.",
	"You already asked about him. There's no one like that here.",
	"I already answered! There is no Edward Low in our town.",
	"You're tiring me...",
	"I see... Thank you.",
	"Okay, okay. I heard you...",
	"Got it...",
};
