string DLG_TEXT_TV [37] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Ask what you will, Señor.",
	"I heard that you recently managed to capture the pirate, Rock the Brazilian himself!",
	"Hey, it's unbelievably quiet today in the town. There's no bustle; all is silent... What could this mean?",
	"Indeed, it's true. I must tell you it was unprecedented luck, Señor.",
	"You already asked me about the Brazilian.",
	"The Brazilian again?",
	"Quit talking about pirates. Let's speak of something else...",
	"What's true is true... So what became of him? Probably strangled then and there.",
	"Did I? Well, probably...",
	"Yes, precisely, I did. Excuse me...",
	"Well, something else it is...",
	"Oh no, Señor. He was brought here and shown to everyone. Only then was he handed over to the holy fathers...",
	"And why did the holy fathers need him?",
	"Ha, Señor, they weren't confessors. The holy fathers are warrior monks! The Inquisition...",
	"Oh, that makes sense. Well then! I thank you, my friend.",
	"Hah, oh yes. People are exhausted. They just haven't got any strength for the usual activity. The thing is, 'twas only the day before yesterday that we've finally seen the man-o-war off...",
	"What man-o-war?",
	"Why, the ship loaded with rubbish. The Governor-General Oregon y Gascon himself ordered all the townsfolk to do the loading. They carried junk - mosaics, jugs, various Indian idols... Heck!",
	"Well that's different! And what for? Up until now, the Spaniards smelted it all into ingots. So what's with the whim?",
	"You think they were golden, these idols? Wait, just stone and wood...",
	"That Mariana went completely mad. So where did this man-o-war go?",
	"Be careful not to talk nonsense - we honor the queen mother. And who are you, exactly? Why do you the need to know where the man-o-war is heading?",
	"No reason, really. I just asked... Excuse me for the rough words. Didn't mean to offend anybody.",
	"Well if you didn't, that's fine. But remember not to stick your nose in other people's business - you could end up behind bars.",
	"Oh come on... What did I do to you? Maybe I'll be going...",
	"Fernando",
	"Gonzales",
};
