string DLG_TEXT_TV [61] = {
	"Questions, ",
	"What do you desire, ",
	"Hmm... Are you flirting with me, ",
	"? Again with the weird questions...",
	"This is the third time today you've rambled on about some question... Are you trying to court me?",
	"Going to ask your questions again, ",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Oh no, gorgeous, not at all...",
	"Not really, darling. Just forgetful...",
	"Oh no, no questions...",
	"I'm listening to you, Señor. Go on.",
	"Hey, gorgeous. Have you noticed anything unusual in the tavern as of late?",
	"I'm listening to you, Señor. Go on.",
	"Oh lovely lady, if your soul is as angelic as your appearance, then of course you will not deny me help.",
	"Ah, here you are, Señor! Just in time.",
	"Aha, I see that you delivered the ring...",
	"Señor, I haven't completed your task yet. I beg you to be patient...",
	"All right, sweetie. I'll be waiting...",
	"No, Señor. Everything is all right.",
	"Noticed any strange people or anything unusual?",
	"A lot of strange people come by the tavern. I can't remember them all...",
	"Seen any strangers here recently?",
	"Many different people come here... Listen, Señor, I need to work. Please don't distract me.",
	"I am compelled to distract you. Do you know about the murder in the house of Havana's Commandant, Don José Ramirez de Leiva?",
	"(turns pale, pauses) I do...",
	"I am investigating this case on the orders of the Governor-General of Havana. I see that you know something. Answer immediately or you will be put in prison today!",
	"Very well, Señor. I will tell you everything! Only promise me that you will not do me any harm.",
	"I promise that if you are not the murderer, I will do nothing to you.",
	"Of course I am not the murdered, Señor...",
	"Oh yes, slaughtering five huge men in full battle armaments is not a feat fit for a waitress. Now, tell me everything you know.",
	"Señor, I think I know who killed Don José and took Doña Anna away...",
	"Who is he?",
	"He appeared unexpectedly. I don't remember seeing him here before. The stranger, I'm assuming a Frenchman by his speech, asked me to give a ring to Doña Anna for him. I did as he asked, what was the harm in it? Doña Anna received the gift and was silent for a minute, blankly staring at the wall. She asked me to wait and wrote a note, then requesting that I give it to the Frenchman.",
	"When I received the note, I suspected that something was amiss, but I gave it to the Frenchman anyway, sensing that he was a terrible person. It would be easier for him to send a man to the forefathers than to drink a cup of wine. His gaze was piercing, like a sword's edge. Most likely he was one of those devils we call Ladrones - they call themselves filibusters.",
	"Damn it! So it was you who informed Doña Anna... What else do you know?",
	"Nothing more, Señor. The Frenchman took the note and left. In the morning, news of Don José's death spread in the city. It was then that I understood what had happened. But I told no one; I was afraid to be called an accomplice to the crime. Señor, you promised not to do me any harm. I ask you to keep your word!",
	"All right, I will grant you freedom although it is clear that it was you who brought the murderer to the house of Don José. However, I also believe that if not through you, he still would have reached Doña Anna somehow. So live for now...",
	"Thank you, Señor! May the Lord keep you safe! I very much regret what happened, but I am not guilty of anything!",
	"If you see the Frenchman again, call the guards immediately. Although... I doubt he will come anymore.",
	"Oh, come on... I couldn't deny such a noble caballero!",
	"I need you to give this ring to Doña Anna Ramirez de Leiva, wife of the Commandant. Not one living soul must know about it!",
	"Oh, Doña Anna already has many beautiful rings. Why would she need another? This poor girl doesn't have anything...",
	"Oh you little rogue, I see where you're going! Well all right, take these 500 coins. You'll get another 500 when you bring me an answer from Doña Anna. You can buy all the jewelry you wish for that money.",
	"Thank you, Señor! You will have to wait a day or two. I must hand over my shift and find the time to head to the house of Señora de Leiva. And I need good reason; I can't just show up on her doorstep...",
	"Very well, darling. I will wait for you...",
	"Yes, I delivered it.",
	"Good. Now tell me what she told you...",
	"Doesn't Señor wish to aid this poor girl a bit more?",
	"Señor, I ask that you not grasp my hand so roughly! I will have bruises from your fingers!",
	"All right... Listen, I am asking you to speak quickly and with purpose. Don't waste my time, darling. That'll help you stay in one piece...",
	"All right, Señor... I gave her your ring. And you know what, Señor? When she saw it, she turned as pale as sailcloth.",
	"So what? What did she tell you?",
	"Nothing special. She asked me to wait and quickly wrote a note to give to me.",
	"Give me the note!",
	"Very well, Señor, just please don't hurt me again... Here it is. Take it.",
	"Good girl. Don't be afraid. Here, have more money. Buy something... And keep your mouth shut, darling. You understand?",
	"I do, Señor. I wasn't born a fool you know.",
	"Very good then.",
	"I recognize him! Guards! Someone call the guards! Seize that Ladrone!",
	"Ay, caramba!",
};
