string DLG_TEXT_TV [33] = {
	"Can I help you?",
	"What do you desire, ",
	"Not too long ago, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"Hey pal, tell me, does Edward Low live in your town?",
	"It's me again, friend... Tell me, where did Edward Low disappear to? It's urgent that I find him...",
	"He does.",
	"I already told you he does.",
	"Yep, he lives here...",
	"You're tiring me...",
	"Mind telling me how to find him?",
	"Okay, okay, I heard you...",
	"Got it...",
	"Of course I don't mind. Always a pleasure helping a good man.   \nFinding his house is simple. When leaving the tavern, turn right and head all the way down. The house lined with planks belongs to Edward Low.",
	"Thanks a lot, pal!",
	"Eh, you're late, pal. He left town. Left for good.",
	"Already told you, Low left town.",
	"He left, I'm telling you...",
	"Oh, you're an annoying one!",
	"Where did he leave to?",
	"Yes, I remember.",
	"Yes, forgot that...",
	"Got it. I'm leaving...",
	"Oh, who knows? He sold all he had in a hurry and left. Most importantly - the keg... He left the keg here. Asked me to put away a keg of Jamaican rum for him.   \nIt seems he was in a rush. Anyway, I already found a use for the keg.",
	"Cut it with the keg. Better yet, tell me where I should be looking for him now?",
	"Oh, I don't know. They say he's off to buy a ship. Ask around, maybe someone saw him or knows something.   \nBut I have no idea. After all, he didn't come here for the keg. A good keg that was...",
	"I understand... Thank you, friend.",
};
