string DLG_TEXT_TV [17] = {
	"Can I help you?",
	"What do you desire, ",
	"Not too long ago, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"I would like to know something.",
	"What exactly are you interested in?",
	"It is said that there was a curse put on Maracaibo. What happened here?",
	"Maracaibo? It's all perfectly fine as you can see. Of course, there's still Des Moines, but that's such a remote place. Nothing ever happens there. Although it's strange... Usually, I've got a few fishermen from there in my tavern, but I haven't seen any for a long time now.",
	"What's this Des Moines?",
	"It's a fishing town in our gulf. You can find your way there through the Cape of Unfulfilled Hope.",
	"Well then, not much news, but thanks anyway.",
};
