string DLG_TEXT_TV [25] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Hey, a certain Aaron Mendes Chumaceiro is staying here in Marigo. You know him?",
	"I wanted to ask about Aaron... But I already found out. Sorry.",
	"Aaron, Aa-a-aro-on...",
	"I've already found out about Aaron. Sorry...",
	"I do. I helped him find a suitable house for rent. He's a good man. Paid a decent amount for it...",
	"I understand... Where's this house Aaron is renting?",
	"It's to the right of our Governor's residence. Head further down a bit and you'll see a small house. It's slightly worn on the outside; inside, everything's all right. ",
	" does no one harm.",
	"Thank you. I'll pay Aaron a visit.",
	"Get in the line, then.",
	"Excuse me?",
	"As I said - get in line. Someone already asked about Aaron and probably headed over to meet with him.",
	"Who?",
	"Some stranger. I've never seen him before in town. Aaron's got an open day today, he-he.",
	"Yes, seems like it... Well all right, thanks again. Farewell.",
};
