string DLG_TEXT_TV [19] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Hey, do you know anything about a Dutch merchant by the name of Jacob Lopez da Fonseca?",
	"No, haven't seen him here or heard anything about him.",
	"You already asked about him and I answered you.",
	"I'm telling you, you already asked about this Jacob.",
	"All right, go away and don't bother me! Are you mad or something?",
	"Well then, thanks anyway.",
	"Hm, oh yes...",
	"Yes, indeed I did...",
	"I'm sorry, ",
};
