string DLG_TEXT_TV [59] = {
	"Can I help you?",
	"What do you desire, ",
	"Not too long ago, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"Hey, I'm looking for a pirate who was selling a strange Bible around here. Heard anything about it?",
	"I was going to ask about the Bible... Already found out. Sorry.",
	"Oh yes, truly...",
	"Ah, already figured it out. Sorry...",
	"Hey, do you know where Atila is hanging out these days?",
	"Yes, yes, we talked about Atila...",
	"Oh yes, truly...",
	"Ah, already figured it out. Sorry...",
	"Listen, friend, have you heard anything interesting in the tavern about a xebec called the 'Blue Bird'?",
	"By chance, Did Edward Low visit this place?",
	"I'm looking for Edward Low.",
	"Did John Avery drop by your tavern?",
	"I've heard a lot of things. Mostly, they say the ship is very fast. They tried to catch it, but to no avail...",
	"We've already gone over this.",
	"Again? We've already discussed everything.",
	"Excuse me... If you don't need anything, I must tend to other customers.",
	"So who tried to catch it?",
	"Yeah, that's for sure...",
	"Hm, indeed.",
	"Fine...",
	"Many tried... and failed, ha-ha!",
	"Do you know anything useful? Like... Where do they usually meet her?",
	"Why, right here in Bermuda. Nothing rivals the 'Blue Bird' when it comes to dodging our reefs. Time and time again galleons and frigates collide into them while pursuing the xebec. They often end up at the bottom!",
	"You don't say... Well then, I'll keep looking. Listen, um, the local shopkeeper... What kind of man is he?",
	"He possesses much authority and is respected among the merchants.",
	"I understand... Is there anyone who's in bad standing with the shopkeeper?",
	"He doesn't have any open enemies, but I think the former owner of the store has a grudge against him, he-he...",
	"Would you be so kind as to tell me his name?",
	"His name is John Norton. You won't find him in Bermuda anymore. I heard he settled in Puerto Principe, quietly plying his trade and doesn't get out much.",
	"A big thank you, my friend. You're a good innkeeper.",
	"Thanks for the compliment, ",
	". Good luck to you!",
	"And best wishes to you, pal.",
	"No, I haven't.",
	"It's apparently a well-known story; I've heard it on Curacao.",
	"Don't know anything about it. There's nothing like that in my tavern.",
	"Thanks for the help.",
	"I do know he bought a house here in town. So he should be there.",
	"Thanks, pal...",
	"He did. Paced the place, snooping around. He'd sit down with one person, then another... It seems he was interested in our shipyard.",
	"Many thanks.",
	"But you already asked about him.",
	"Perhaps you remember something?",
	"Oh, there's not much to remember. He kept asking about the shipyard. Tried sitting next to all kinds of folk. By the way, Captain Goodley's sitting over there. He was the last one to talk to him.",
	"Captain Goodley?! Thanks! That's something already.",
	"Oh, he dropped by just now. Asked me where Orry Bruce lives and left. ",
	"So where does this Orry Bruce live?",
	"Why, in the two-story house with stone laying. When leaving the tavern, it will be the first house on your left. He lives there...",
	"Thanks, you've helped me a lot!",
};
