string DLG_TEXT_TV [26] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Tell me, what kind of person is the local usurer?",
	"Where can I find Captain Guay? I have important business with him.",
	"The usurer is an usurer; there are no good people among them.",
	"Heard anything interesting about him?",
	"Well no, nothing special.",
	"So who in town knows him well?",
	"Oh, he doesn't really communicate with anyone. Can't tell you anything.",
	"Oh well. Thanks for that much.",
	"Captain Guay? Couldn't be easier. He's renting a room from me. He hasn't come out yet today, so you'll see him in his room for sure.",
	"I already told you everything...",
	"There is nothing to talk about...",
	"Sir, please leave me to my work!",
	"Thanks, pal...",
	"I understand. Sorry...",
	"Hm, oh yes...",
	"Yes, of course. Sorry pal...",
};
