string DLG_TEXT_TV [30] = {
	"Questions, ",
	"What do you desire, ",
	"Hmm... Are you flirting with me, ",
	"? Again with the weird questions...",
	"This is the third time today you've rambled on about some question... Are you trying to court me?",
	"Going to ask your questions again, ",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Oh no, gorgeous, not at all...",
	"Not really, darling. Just forgetful...",
	"Oh no, no questions...",
	"Listen, gorgeous, I need to know what Sawkins is about to do.",
	"I brought you what you asked for. Here are your rings.",
	"Bring me a ringlet with an emerald and a ringlet with a ruby. And then, mayhaps, I will be able to help you...",
	"I don't have such things...",
	"Here are your rings, darling...",
	"A pity, but these are my conditions.",
	"Understood...",
	"Mmm, so pretty! Thanks. So, what did you want to know?",
	"I need to know what Richard Sawkins is about to do. Do you have any idea?",
	"No.",
	"Then why the hell are you fooling around with me?!",
	"I'm telling you, I know how to acquire that information, so listen carefully. Richard is pedantic; he writes everything down in his log. All you need to do is get your hands on it.",
	"Hah! Maybe you also know how to do that?",
	"I do. Take the logbook from his residence. He stays there during the day, so you don't have a chance of escaping alive if you dared to attempt stealing it. But at night...",
	"Everything's locked at night!",
	"Get in through a window at the back side of the house. You'll need a ladder to climb up.",
	"Where do I find one?",
	"I don't know...",
	"Hm, well then, thanks for that much.",
};
