string DLG_TEXT_TV [23] = {
	"Can I help you?",
	"What do you desire, ",
	"Not too long ago, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"There are rumors floating around that Sawkins is recruiting people for some task. Heard anything about it?",
	"Yes, something's coming. Richard's going to poke the Spaniards again. That's a fact.",
	"We already spoke about that.",
	"Richard's plan again?",
	"I won't give you any new advice.",
	"I understand. Do you know whom, exactly? And where?",
	"Yes, that's correct.",
	"Yep, again...",
	"Hm, thanks for that much...",
	"Hah, you're a joker! That's a military secret, you know. Richard never discloses such things till the last moment, not even to his captains! And you're asking me...",
	"Um, that was only in case you knew... Do you think it's worth it for me to go with him on this mission?",
	"I don't know. Decide for yourself. Sawkins has a reputation as a successful cap'n. Personally, I would go with him. Richard's been preparing for this carefully; he stays in his residence for days on end, scribbling into his log...",
	"Heh, understood... Well then, thank you for your advice.",
};
