string DLG_TEXT_TV [23] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Haven't been here in a long time... What's new in San Juan?",
	"In general, everything's the same as it was. The city prospers.",
	"I understand... Hey, did a pinnace, the Santa Agueda, sail into the city by any chance?",
	"Yes, it arrived here straight from Port Royal itself!",
	"You don't say! So you're at peace with the English?",
	"Not exactly peace just yet, but it's definitely not war. The English are fighting the Dutch now, so relations in the Old World are improving.",
	"Well then, that's for the best... So where's the pinnace now?",
	"Its holds were unloaded; it left shortly after. Now San Juan is buried in indigo and silver. The prices have fallen...",
	"So the cargo from the pinnace were sold?",
	"Of course! What do you want with that pinnace?",
	"They made a deal that they would hold this cargo for me, but they sold it all here...",
	"Next time, try making deals with someone else.",
	"Very true, my friend. Thank you, and best wishes.",
};
