string DLG_TEXT_TV [42] = {
	"Can I help you?",
	"What do you desire, ",
	"Just recently, you tried to ask me a question, ",
	"You keep mentioning you have a question for me. This is the third time today...",
	"Asking questions again?",
	"Sorry. Never mind...",
	"Uh, yes. I can see that you are busy, we can talk next time.",
	"Something's happened to my memory...",
	"One, two... you're right! Third it is.",
	"Oh no, no questions...",
	"How are things here? How's the city?",
	"I heard that the famous pirate, Rock the Brazilian, was snatched by the Inquisition...",
	"Praise the Lord Almighty. We are well. The city prospers.",
	"It's hard to prosper when you're surrounded by enemies. How do you manage that?",
	"Our Governor, José Sánchez Jiménez, knows how to solve problems. Recently, he rid Hispaniola of a buccaneer settlement. Nice business that was, I must say!",
	"You don't say! Did the buccaneers bother you that much?",
	"Why, no. I'd say it was more convenient when they were around. I used to always have good fresh meat in my kitchen. And cheap, too, by the way. Now finding it is becoming more difficult; everything is more expensive these days.",
	"Hm... So why did your Governor do it, then?",
	"Ah, devil only knows. It may be because the buccaneers were the dirty French. Hispaniola should be Spanish!",
	"Well then, I'll let it be... Listen, I wish to enter your Governor's service. What would you recommend? Is he in the city at all?",
	"Yes, he is now. As for entering his service, it would be easy if you address him personally.",
	"I understand... Do you know if he plans to leave in the near future?",
	"No, nowhere. There will be a festival in our city soon, so he will be here, for sure... Hey, why are you asking?",
	"Oh, no reason...",
	"There must be a reason. If you want to serve the Governor, go and enter his service. Why do you need to know where he will be in the near future?",
	"Hey, why are you bristling up?! Mind your business here... Roast your meat, sell your scratchings...",
	"Somehow you appear suspicious to me, dear sir.",
	"Oh officers, you're just in time! Detain this person for investigation; I believe he's a spy!",
	"Ah, damn it!",
	"True, he is with the holy fathers now.",
	"You already asked me about the Brazilian.",
	"The Brazilian again?",
	"Quit talking about pirates. Let's speak of something else...",
	"Hah, so when will he be hung?",
	"Did I? Well, probably...",
	"Yes, precisely, I did. Excuse me...",
	"Well, something else it is...",
	"Now it is up to Antonio de Souza himself! At present, he is in charge of the local Holy Inquisition.",
	"Well, where is the Inquisition itself located?",
	"Oh, where would it be? Right here in the city, Señor.",
	"Señor, we'd better end this conversation. It would not do you any good to mention the holy fathers in vain...",
	"All right. Best of luck to you, innkeeper.",
};
