string DLG_TEXT_TV [86] = {
	"Every rumor in the city of ",
	" at your service. What would you like to know?",
	"We just went over that. I gather you have forgotten...",
	"This is the third time today you've rambled on about some question... ",
	"You're starting to sound like a parrot...",
	"You know ",
	", perhaps next time.",
	"Indeed I did. Silly me...",
	"One, two... you're right! Third it is.",
	"Yeah, well...",
	"Hey, do you know the filibuster Pierre le Picard?",
	"Hey, um, are you in the know on this? Someone's waiting for me here. I arrived from Curacao...",
	"Where's the person that was waiting for me in the room above?",
	"Do you know where I could find Lorain de Graf, the filibuster?",
	"Hey pal, you mind telling me how to find Rock the Brazilian?",
	"What's new in Tortuga?",
	"Listen, do the Dutch from Curacao often come here?",
	"Listen, do the Dutch from Curacao often come here?",
	"I know him, of course I do. He rented a room from me and paid for a year in advance!",
	"Hey, was it you who already asked me about it?",
	"Hm, we already spoke about Pierre...",
	"Maybe you should stop distracting me? I can send for Pierre if you wish to see him so terribly.",
	"You don't say! He doesn't seem to have any problem with money...",
	"Did I? Well, probably...",
	"Yes, indeed, we did. Sorry...",
	"Oh no, don't bother. I'll find him myself...",
	"Of course! Recently, Morgan invited him to participate in an attack on the Spanish silver mines. It seems to me they went there just in time.",
	"Now that's good luck...",
	"He's not in his room. Try back later. Maybe you'll find him then.",
	"Thanks. I'll do just that.",
	"I am. Head to the room above. There's someone waiting for you.",
	"You already asked me this question today.",
	"Again?",
	"Maybe you will stop distracting me from my work?",
	"Thanks, ol' chap.",
	"Indeed, I did...",
	"Hm, sorry...",
	"All right, I won't. Sorry...",
	"He left about an hour ago; you're really late...",
	"You already asked me this question today.",
	"Again?",
	"Maybe you will stop distracting me from my work?",
	"Damn it! Do you know who he was and where he went?",
	"Indeed, I did...",
	"Hm, sorry...",
	"All right, I won't. Sorry...",
	"He came here the day before yesterday, and told me straight away that he was waiting for someone. He asked around about ships from Curacao, which means he was probably waiting for you. But I don't know where he went.",
	"And you know absolutely nothing about him?",
	"Haven't seen him before, but he's a good lodger. Paid double for the room. Can't tell you anything other than that.",
	"Well then, thanks for that much...",
	"You won't find him in Tortuga right now. He left the city a few weeks back, most likely to butcher the Spanish again...",
	"You really don't know where he went?",
	"In general, you shouldn't discuss your plans with a filibuster.",
	"I understand... Do you know who might be able to tell me that?",
	"And why?",
	"I must see him; it concerns an important issue. I've searched for him in Bermuda, and now I'm looking here. I'm Dutch myself, just like Lorain...",
	"All right, I'll tell you since you need to see him so badly. I heard he was plying near Cartagena. De Graf possesses the Cominte.",
	"I understand. Thank you, friend.",
	"Depends on why you need him. How urgent is it?",
	"It's very important that I see him. I have serious business for him.",
	"Then that's a problem. Rock left for Maracaibo on his corvette; he'll ply thereabouts until he catches a galleon with decent loot.",
	"Really? Why, that's simply marvelous as I, too, need to get to that region. I hope to meet him there. Thank you.",
	"Anytime...",
	"Best wishes to you, ol' chap.",
	"Oh, same old... Fighting the damned papists.",
	"Aaah, that's a good thing to do. What about Papiettes? Have those in the city? They say they are very attractive women...",
	"There were none until recent times. But now, our honored Governor-General d'Ogeron has a Spanish nanny-goat. Beauty beyond measure! The Governor-General is simply overjoyed, and smiles from ear to ear every morning until late evening. I'm not sure about at night, tee-hee...",
	"Really? So who is she, this brave woman?",
	"Doña Anna, that's her name. I hear she is from Havana.",
	"Filibusters haven't reached Havana yet. How did d'Ogeron get his hands on her? Was she captured from a Spanish galleon?",
	"Oh no-o-o! The feeling is mutual - Doña Anna loves our Governor-General just as he loves her. I heard they became acquainted while still in the Old World. One of the Governor-General's entrusted officers, Henry d'Estre, brought her to Tortuga. No one knows where he found her.",
	"I understand... So where is this Henry d'Estre now?",
	"At home, probably. He has a house here on the island.",
	"I see that Tortuga prospers; I'm glad. All the best to you, friend.",
	"They do. Why are you asking about them?",
	"The Dutch? Oh yes, they do come here...",
	"We already talked about the Dutch today...",
	"I don't want to talk about the Dutch anymore...",
	"I'm waiting for a person from Willemstad. I'll need to rent a room at your place for a week.",
	"Great!",
	"We did, indeed...",
	"Okay. As you say...",
	"No problem. The room is free. Just pay 35 coins for the week.",
	"I'll pay you a hundred coins for the week. What's 35 coins? Nothing...",
	"Heh, well thank you, good sir. I won't refuse money. You may occupy the room immediately if you'd like; it's not locked.",
	"Thank you.",
};
