string DLG_TEXT_TV [27] = {
	"Questions, ",
	"What do you desire, ",
	"Hmm... Are you flirting with me, ",
	"? Again with the weird questions...",
	"Land sakes, you just keep coming back to me with these questions of yours. I'm startin' to think you might have yourself an ulterior motive, sir.",
	"Mm? More of your questions, ",
	"Er. Sorry. Never mind...",
	"Well, I've nothing to say at present...",
	"Why no, gorgeous. Not at all...",
	"Not really, sweetie pot. It's just this memory of mine...",
	"Oh, no. No questions this time...",
	"You got something to say to me? ",
	"Yes. I want to say you look simply remarkable. Your beauty shines even through the tears in your eyes.",
	"Oh...",
	"Oh, yeah, we've already gone over that...",
	"Listen, we had our chat. Now let's move on, shall we? ",
	"Oh, why would you trouble a poor girl? You think that just because I'm in grief, you can just waltz in and console me?",
	"So who is he? Who brought you to this? Maybe I can help?",
	"Yes, you got it.",
	"All right, all right...",
	"It's all right, toots. I'm not the thinkin' sort.",
	"It's Jansen - the moneylender's. He... He...",
	"You don't say. It just happens I was looking for him. Where is he? What did he do to you?",
	"Oh, that shyster. Said he'd marry me. Promised me mountains of gold. And then... nothing. He left for Fort Orange yesterday, on a lugger full of pirates!",
	"Oh, the cur! Why, if I meet him, I'll let out his entrails to say hello!",
	"That's sweet, but what if it kills him? No, better just tell him to steer clear of our tavern... Lest I scratch his eyes out!",
	"Well, all right. I'll tell him.",
};
