string DLG_TEXT_TV [106] = {
	"Every loose tongue in old ",
	" town, at your disposal. What would you like to know?",
	"Mind like a sieve. My friend, we've just gone over that.",
	"This is the third time today you've come in here about some  question...",
	"Good grief, you're like a parrot. My time is in fact limited, you know...",
	"Tell you what, ",
	" - maybe some other time.",
	"Yes, well. I forgot something...",
	"Really? One, two... oh, so it is. Imagine that.",
	"Hm. Indeed...",
	"Listen, I need to know something...",
	"Have you come round?",
	"I sure did. Here's your grand.",
	"A thousand coins? For two bleedin' words?! That's ridiculous!",
	"Been counting your pennies, eh?",
	"Yeah, I guess I have been.",
	"I'm listening.",
	"I am interested in the following people: Joao d'Ylan, Joseph Nunes da Fonseca, and Jacob Lopez da Fonseca. What can you tell me about them?",
	"I'm listening.",
	"I am interested in the following people: Joao d'Ylan, Joseph Nunes da Fonseca, and Jacob Lopez da Fonseca. What can you tell me about them?",
	"I listen with fervor, to my dear French guest!",
	"Yes, well. What I want to know is why the hell Governor-General Stuyvesant has placed France's official courier behind bars. What in God's name are you doing to him?",
	"I'm listening.",
	"Listen, er. I need to order a key for a chest.",
	"My ears are wide open.",
	"Hey, I need to see the Keymaster. Is he around?",
	"Speak your say. ",
	"Hey, do you know a hobo, name of Teaser Dan? I hear he lived around here for a while.",
	"I'll do what I can. Ask away.",
	"I've got some material - gold, stones - that I need to, er, discreetly unload. Basically... I need a man without too many scruples.",
	"Hm... A thousand coins, and you get a name.",
	"Isn't that a bit steep, for two little words?",
	"All right, here's your thousand.",
	"No, not quite. You're a bit short. Look, if you don't want to pay you're free to ask around. I assure you, though, you'll be back.",
	"Fine, you don't have to tell me twice. I'll go take my business elsewhere!",
	"The man's name is Joseph Nunes da Fonseca. He's a merchant, arrived with all those Jansenists a while back. Joseph took it on himself to organize em all and bring em together as a community. ",
	"And that's fine. Good people, most of them. But this man has no conscience. First thing he did here was set up as a moneylender. However much you want, he'll give you with a smile. But miss your payment by a single day, and wham, next morning you wake up in prison.",
	"Doesn't bother him at all, the men he's starved to death or driven to suicide. The man's a devil, pure and simple.",
	"Why doesn't the Governor-General step in?",
	"Hah! Having money problems, friend? I can spot em a mile away. Look, it's fine. Just come back when we can do business.",
	"Oh well. You're not getting to the ball on an empty pocket...",
	"Joseph is, shall we say, a welcome guest in his house. You see, our esteemed Governor-General helps Joseph to collect his debts. ",
	"So wait. If he's so cozy with the authorities, why are you sending me to him?",
	"Oh, don't worry. He's a businessman, so as long as he can profit off you you're fine. You won't get market prices from him, of course, but you're safe in his hands. It's fine; you're not the first I've sent his way. ",
	"Uh-huh. Thanks a heap.",
	"Joao d'Ylan is a good man, an honest trader. He keeps the market rate low, doesn't pinch the pennies too tight. Jacob Lopez da Fonceca is one of his associates; they hold the store together. But Joseph Nunes da Fonseca is a moneylender. He's driven more than one man to bankruptcy and suicide...",
	"We've already gone over this...",
	"Here we go again...",
	"Oh, when will you stop?",
	"The devil incarnate!",
	"Yes indeed, ",
	"No, sorry...",
	"Pardon...",
	"Well, maybe not the devil himself - but his assistant, surely.",
	"Thanks, pal. You really helped me out there.",
	"Little wonder he's suspicious of all strangers! It's no joke when in one short month the pirates plundered and sunk nineteen of our ships. Two of those were even carrying the Governor-General's own personal goods.",
	"Yeah, we've gone over that.",
	"Here we go again...",
	"Oi! Leave off, will you? ",
	"And I'm a particularly suspicious character, I take it?",
	"Right in one.",
	"No, sorry...",
	"Pardon...",
	"Oh, you just probably found him in a mood. There are stranger characters around.",
	"By the way, that table in the corner, to the right of you - the two fellows sitting. Who are they? Never saw them before. Suppose there's no reason to call the guards yet - I've got a reputation to keep here. If you want to talk with them, though...",
	"Yeah... Thanks. You were actually a big help. ",
	"Ah. Well, you need to see the Keymaster.",
	"Who's this Keymaster when he's at home?",
	"That's how we call Hill Corner, see. What he does is he makes locks and keys for stuff. Doors and chests.",
	"Hm. So he's a locksmith, then.",
	"Mm... Ha. There you are. On your right, at a round table.",
	"Oh. Yeah, I see him. Thank you.",
	"Why, he's right there - table to your right, like usual.",
	"Aha. Thanks...",
	"Well, course I knew him! Who didn't? And a fine liar he was...",
	"Hey, I've already told you once...",
	"Oi. Not fond of repeating myself, mate.",
	"Begging your pardon, I don't have the time for meandering effluvium. ",
	"Why's that, then?",
	"Ah, yes. I see.",
	"Yes, of course.",
	"I see...",
	"Well, you see, he pulled a decent income telling tale of his adventures. It's all very fashionable, traveling and discovering new lands. The public just eat it up! If Marco Polo were with us today, I tell you...",
	"Something about an island, right?",
	"Sure, that too. He was pretty great to have around, really. He'd say, 'Have you ever been to Tahiti?' and folks would start to gather round. And the tales that he spun... whee. A pity he left.",
	"Where'd he go?",
	"Dunno. Didn't say. Just one day, he didn't turn up. That's all I know. Well, also his... colleagues, so to speak - other bums that is - they were looking for him. Dunno if they found him. If they did, no one's told me. ",
	"No, they haven't.",
	"Shame. Good man, he was. Despite the smell. You know, there's folks with an inflamed sense of justice. Our Teaser, he was like that. Life, it weren't none too kind to the wretch. His favorite tale to tell was of the Island of Justice.",
	"Really. So what was that all about? ",
	"Said there was an island not even too far from here, built entirely out of ships! He said people there lived good lives, and everyone was equal 'mongst themselves. A sort of paradise on on Earth, y' might say. An eden. A Utopia.",
	"And what's your governor-general's position on the homeless situation?",
	"Oh, nothing good. Y'know, teaser had it he was sold into slavery once, and our Stuyvesant, he don't think of slaves as real people. Not even former slaves.",
	"I see. Hey, um, they say Stuyvesant has some business with the Dutch West India Company, and...",
	"Hush now! Quiet, friend. Best we don't discuss the company of our good Peter. Don't you go asking around, neither. Least, not less you're looking for more trouble than you can bear!",
	"Ah? What's the deal there? ",
	"The Company doesn't play around, my friend. And don't you mind that they're most visible in Europe and the East Indies; they're as present here as anywhere, if not so overtly...",
	"Well, damn. So where can I find them? ",
	"Why? Why do you need them?",
	"I want to offer them my delivery services.",
	"You know, buddy, the Company doesn't need your kind of help. Some have it, they own the whole of Curacao - and probably more! ",
	"Blighted spires! That's one serious operation.",
	"Mm. Well, my advice is, don't try to do business with them. They only work with our Peter, here. Understood?",
	"Understood... Well, thank you, my friend, for such a detailed story. I was most enthralled. ",
	"Don't mention it. I'm glad to get outside myself when I can.",
	"Best wishes to you.",
};
