string DLG_TEXT_PRT [40] = {
	"What questions?",
	"What do you want, ",
	"Just recently you tried to ask me a question, ",
	"You keep mentioning you have some question for me. This is the third time today... ",
	"Listen, unless it's got something to do with the port, don't addle me with your questions.",
	"I've changed my mind...",
	"I've got nothing to say now. ",
	"Something's happened to my memory...",
	"Oh, now this is the third time... ",
	"I'm sorry, but port matters are of no concern to me now.",
	"I'm looking for Edward Low. Did he hire a ship from you?",
	"What's this, money?",
	"Edward Low? He stopped by, but he didn't hire a thing. I had a French privateer here, and he went on board as a passenger.",
	"We've already discussed this topic!",
	"Immediately stop repeating the same thing.",
	"Hm. You've tired me out...",
	"Do you know where the privateer went?",
	"Yes, I remember.",
	"Good...",
	"Understood...",
	"Yes, yes, but you understand if I am not prepared to discuss such things... ",
	"I must find him, the villain! When I find 'im, I'll kill 'im! ",
	"Edward Low is a distant relative, y'see. His mother is in a bad way, and I'm in a rush to bring him back with me. Poor old girl won't last a month, and has been asking after him... ",
	"Ooh la la! So you are ze murderer! Leave at once, or I shall call ze guards! ",
	"Oh hell.",
	"Zat is a great tragedy. Yes, I will help you. Ze brigand is on sail to ze Bermudas.",
	"Oh, thank you! Thank you so much. You have no idea what this means to me! Truly, thank your toes... ",
	"Oh, sure. Everyone has ze tales-tall of poor relations and ze mommy on ze deathbed. Zey have come to bore me, mon chere. Bring me a better story. ",
	"Might a small financial incentive spark your interest?",
	"Hum. If you insist, zen fifteen thousand would go far in helping your poor relative with ze mommy problems.",
	"Yeah, all right. So there's that. Now give me what I want.",
	"You think I carry that kind of money on me?",
	"Your brigand, he left for ze Bermudas... ",
	"I see. Thank you for your passionate participation in our family drama. Farewell... ",
	"Zen you must find it. Do not worry, I will wait... ",
	"All right, fine. I'll get you the money.",
	"All right! ",
	"Here's your fifteen thousand. Now lay it on me.",
	"You think me a foo, yesl? Bring me the money, mon cher... ",
	"Devil! Roustabout! Vagabond! ",
};
