string DLG_TEXT_PRT [19] = {
	"What questions?",
	"What do you want, ",
	"Just recently you tried to ask me a question, ",
	"You keep mentioning you have some question for me. This is the third time today... ",
	"Listen, unless it's got something to do with the port, don't addle me with your questions.",
	"I've changed my mind...",
	"I've got nothing to say now. ",
	"Something's happened to my memory...",
	"Oh, now this is the third time... ",
	"I'm sorry, but port matters are of no concern to me now.",
	"You see any Spaniards in port lately?",
	"Spaniards? That's a rare fish in these waters. Still, there was one the other day, dropped anchor here. Even had some protection, from the garrison.",
	"How odd. Why would British soldiers protect a Spanish ship?",
	"Devil knows. Him, or the Governor-General.",
	"And where is this Spaniard now? What kind of a ship?",
	"It was a pinnace, the 'Santa Agueda'. She launched yesterday on a good wind to San Juan. What's your interest with this bloke?",
	"I'd like to talk to 'im. You could say he owes me... ",
	"Ha! All right... Well, you want to catch him, you'd best set off now while the wind's still good. Even then, good luck to you.",
	"I'll give it my best. Farewell, my salty friend.",
};
