string DLG_TEXT_PRT [46] = {
	"What questions?",
	"What do you want, ",
	"Just recently you tried to ask me a question, ",
	"You keep mentioning you have some question for me. This is the third time today... ",
	"Listen, unless it's got something to do with the port, don't addle me with your questions.",
	"I've changed my mind...",
	"I've got nothing to say now. ",
	"Something's happened to my memory...",
	"Oh, now this is the third time... ",
	"I'm sorry, but port matters are of no concern to me now.",
	"D'Ojeron has sent me for you, to immediately tell me what ship left the waters of Tortuga in the past two hours!",
	"I'm at liberty to reveal my acclaim, and introduce you to my identifying papers. Please read my trade license with the French East India company.",
	"Listen, has the Dutch ship I'm waiting for come around yet?",
	"According to the orders given by d'Ojeron, you need to give over to me the  command of the ship-of-the-line first class, Soleil Royal.",
	"Just one brig, the La Rochelle. It set out toward San Juan, on its way to Puerto Rico. Some bigwig from the French East India company, trade representative or whatever, was on board.",
	"What representative?!",
	"You deaf? I said, a representative of the French East India company. He arrived here a few days ago, and immediately revealed his company warrant. He did his business then wanted to leave immediately for Curacao. I was looking for a ship on the way, so I sent him to you.",
	"But his plans changed at the last moment, and he left with the brig that he arrived with on Tortuga, actually.",
	"Damn it, it looks like that was Antonio...",
	"Absolutely right. Antonio de, uh... de... Well, I can't remember everything.",
	"I must catch up with that cursed brig immediately. This is a question of life and death.",
	"It can't be? Well, it's possible. In that case, don't lose time.",
	"Thank you for the information, though I'm not very grateful about you meeting Antonio...",
	"I see. But what has this to do with me? I'm not involved in any commercial ventures... ",
	"Yeah, yeah. I know that already... ",
	"What, you again?",
	"Look, enough is enough. You already showed me your papers... ",
	"Yes, I know. I'm here about something else. Thing is, I'm nearly done with my business here. So next I'm off to Willemstad, on Curacao, and would like to catch a lift - preferably on a nice, swift vessel. Could you tell me if any ships in port are heading my way?",
	"Oh... well, alright...",
	"Well, yes, I... ",
	"Yes? Splendid... ",
	"Hmm, not at the moment. However, I believe there shortly will be -- the Dutch from Willemstad are frequent guests here.",
	"Merchants?",
	"Some. But I suggest waitin' on a courier ship out o' Curacao. They never stay long; an exclusive hour, two at the Governor's residence, then high-tail it back to Willemstad. And when they're with the Governor-General, ain't no one else seein' 'im.",
	"Oh, that's just dandy. Don't suppose you could alert me when one of them pulls in?",
	"Sure thing. Where you stayin' at, Monsieur?",
	"I've got a room at the tavern.",
	"Good, good. Soon as a Dutch ship drops anchor, I'll light a messenger's tail on fire. ",
	"Thank you ever so, Monsieur. You've done a service to our company, and we shan't forget it.",
	"No, not yet. I told you, I'll let you know. Don't worry, I keep my promises.",
	"Thank you, Monsieur. A hundred apologies for my importunity.",
	"Yes, Monsieur. So I have been informed. The helm is yours. In all frankness, even an admiral would be tickled to command such a ship... ",
	"I completely agree, sir. Excuse me, I must take my leave - business, you understand.",
	"You must shed your squadron of extra vessels. You may do this however you please. Regardless, at the point of transfer, you must be otherwise wholly free of obligation.",
	"Very well, I'll see it done.",
	"Soleil Royal",
};
