string DLG_TEXT_PRT [15] = {
	"What questions?",
	"What do you want, ",
	"Just recently you tried to ask me a question, ",
	"You keep mentioning you have some question for me. This is the third time today...",
	"Listen, unless it's got something to do with the port, don't addle me with your questions.",
	"I've changed my mind...",
	"I've got nothing to say now. ",
	"Something's happened to my memory...",
	"Oh, now this is the third time... ",
	"I'm sorry, but port matters are of no concern to me now.",
	"I'm here on Stuvesant's orders. I'm to take command of the three flutes.",
	"Sure thing. That's three flutes, now at your command.",
	"Bravo! ",
	"Yes, so I heard. Before you do that, though, you must ditch the dead wood. I don't care what you do with that squadron of yours, but get rid of it before you come asking. ",
	"What? Well... all right, I can do that.",
};
